### ISSUE TITLE
Duplicating existing routines (template for multiple similar routines)

### ISSUE THREAD

**Issue by wildetudor** [psychopy/psychopy#1000]
Some routines take a while to customise in the Builder, such as instruction screens. They then need to be repeated in several parts of the flow, and so it would be very useful to be able to duplicate an existing routine and to save it as a different routine once you've made changes to it starting from the original template. 

For instnace, when right clicking on a routine in the flow, there could be a Duplicate option, which brings up the New Routine dialogue to select a new name, but then isntead of creating a blank routine, creates a copy of the old routine.

**Comment by jeremygray** [comment]
This feature is already present: you can copy and paste routines (see the Experiment menu in the Builder). If this meets your needs, you can close this issue. If not, please explain more.

**Comment by wildetudor** [comment]
Ah yes - sorry, silly of me not have noticed!..
