### ISSUE TITLE
Word wrapping in Text routines

### ISSUE THREAD

**Issue by wildetudor** [psychopy/psychopy#1001]
For long instruction screens, it's really hard editing the text under the non-word-wrap-enabled Text field of "text stimuli" windows. Would be great for this field to be (i) larger, and (ii) word-wrap-enabled

Thanks!

**Comment by jeremygray** [comment]
I agree. But its possible to get around this by having a code component that contains multi-line instructions like this, Begin Experiment. It will give you a wide window that is easy to edit

instr = """Welcome
instructions
more instructions
"""

and then in the TextComponent, you can put 

$instr

**Comment by peircej** [comment]
I agree too. Sounds handy, but not my number 1 priority




This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by jeremygray** [comment]
Another work around is to compose the text elsewhere, in another program, and then paste it into the TextComponent

**Comment by TEParsons** [comment]
Pleased to say this is now handled by the TextBox component!

**Comment by peircej** [comment]
(TextBox and TextStim)
