### ISSUE TITLE
QUEST creates grid of counter-intuitive dimensions

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1005]
## Motivation

Encouraged by [this discussion](https://groups.google.com/d/msg/psychopy-users/5AsGnvLsPpU/3MA0WJTJRF4J) on the users mailing list, I looked into the QUEST implementation in greater detail. I found that the current API and documentation are counter-intuitive, potentially leading to undesired _("wrong")_ results.

Please bear with me while I'm trying to demonstrate what causes my concerns.
## Problem Description

Currently, `data.QuestHandler.__init__()` has, among others, the following parameters:
`minVal`, `maxVal`, `grain`, and `range`.

They are documented as follows:

```
minVal: *None*, or a number
    The smallest legal value for the staircase, which can be used to prevent it
    reaching impossible contrast values, for instance.

maxVal: *None*, or a number
    The largest legal value for the staircase, which can be used to prevent it
    reaching impossible contrast values, for instance.

grain: *0.01* or a number
    The quantization of the internal table.

range: *None*, or a number
    The intensity difference between the largest and smallest intensity that the
    internal table can store. This interval will be centered on the initial guess
    tGuess. QUEST assumes that intensities outside of this range have zero prior
    probability (i.e., they are impossible).
```

At a first quick glance, this seems pretty straightforward, except for that weird `range` parameter. But since it's optional, the naïve user is just going to omit it for the time being.

However, the other three parameters appear to be useful.

What one should be able to reasonably assume is:
**If I supply a `minVal`, `maxVal`, and `grain` argument, some internal grid of the size `(maxVal - minVal) / grain + 1` should be created.**

(The `+ 1` accounts for the endpoint)

That means, one would assume that the resulting grid has a resolution equal to the `grain` parameter. But this is in fact usually **not** the case with the current QUEST implementation, and should, IMHO, be considered a bug.

The reason for this behavior, which I will demonstrate in the next paragraph, is in fact the dubious `range` parameter. Looking into `contrib.quest.QuestObject`, one [finds](https://github.com/psychopy/psychopy/blob/master/psychopy/contrib/quest.py#L113) that a certain parameter `dim` seems to play a role (unnecessary lines removed):

``` python
if range is None:
    dim = 500
else:
    dim=range/grain
    dim=2*math.ceil(dim/2.0) # round up to even integer
```

This means that, by default, `dim` will be `500` for `QuestObject`s created through PsychoPy, if the user does not specify the `range` argument. But how does this relate to the internal grid?
In `QuestObject.recompute()`, we [find](https://github.com/psychopy/psychopy/blob/master/psychopy/contrib/quest.py#L290) the following lines:

``` python
self.i = num.arange(-self.dim/2,self.dim/2+1)
self.x = self.i * self.grain
```

This is the internal grid, still centered around zero. We can see that it depends directly on the `range` and `grain` that were supplied to the `QuestObject`.

What else do we see? Well, the grid does **not** depend on the `minVal` and `maxVal` parameters at any time!
## Problem Example

This is extremely problematic, as the following example demonstrates.

``` python
from __future__ import division, print_function
from psychopy.data import QuestHandler

if __name__ == '__main__':
    q = [None] * 5
    startVal, startValSd = 0.5, 1

    params = [
        {'grain': 0.01, 'range': None, 'minVal': None, 'maxVal': None},
        {'grain': 0.01, 'range': None, 'minVal': 0,    'maxVal': 1},
        {'grain': 0.01, 'range': None, 'minVal': 0,    'maxVal': 1000000}
    ]

    for i, p in enumerate(params):
        q[i] = QuestHandler(
            startVal=startVal, startValSd=startValSd, grain=p['grain'],
            range=p['range'], minVal=p['minVal'], maxVal=p['maxVal']
        )

        minVal = q[i].minVal
        maxVal = q[i].maxVal
        grain = q[i]._quest.grain
        grid_min = q[i]._quest.x[0]
        grid_max = q[i]._quest.x[-1]
        grid_size = len(q[i]._quest.x)
        if minVal is None:
            grain_effective = q[i]._quest.x[1] - q[i]._quest.x[0]
        else:
            grain_effective = (maxVal - minVal) / (q[i]._quest.dim)

        print(
            'QuestHandler #%d: '
            'Requested Grid: [%s, %s], '
            'Requested Grain: %.3f, '
            'Effective Grid: [%.2f, %.2f], '
            'Effective Grid Size: %d, '
            'Effective Grain: %.3f, ' %
            (i,
             str(minVal), str(maxVal), grain,
             grid_min, grid_max, grid_size, grain_effective)
        )
```

Output:

```
QuestHandler #0: Requested Grid: [None, None], Requested Grain: 0.010, Effective Grid: [-2.50, 2.50], Effective Grid Size: 501, Effective Grain: 0.010, 
QuestHandler #1: Requested Grid: [0, 1], Requested Grain: 0.010, Effective Grid: [-2.50, 2.50], Effective Grid Size: 501, Effective Grain: 0.002, 
QuestHandler #2: Requested Grid: [0, 1000000], Requested Grain: 0.010, Effective Grid: [-2.50, 2.50], Effective Grid Size: 501, Effective Grain: 2000.000, 
```
- In run 0 (neither `minVal` nor `maxVal` specified), the granularity is as requested.
- In run 1 (both `minVal` and `maxVal` specified), the granularity is finer than requested, which improves precision of the calculations, but slows down computation.
- In run 2 (both `minVal` and `maxVal` specified), the granularity is extremely low, possibly leading to untrustworthy results.
## Workaround

Now let's see what happens if we supply a `range` parameter. We change the `params` list from the example code given above, and re-run the script (warning, this is going to use up a lot of RAM and CPU time!):

``` python
    params = [
        {'grain': 0.01, 'range': None,    'minVal': None, 'maxVal': None},
        {'grain': 0.01, 'range': 1,       'minVal': 0,    'maxVal': 1},
        {'grain': 0.01, 'range': 1000000, 'minVal': 0,    'maxVal': 1000000}
    ]
```

Output:

```
QuestHandler #0: Requested Grid: [None, None], Requested Grain: 0.010, Effective Grid: [-2.50, 2.50], Effective Grid Size: 501, Effective Grain: 0.010, 
QuestHandler #1: Requested Grid: [0, 1], Requested Grain: 0.010, Effective Grid: [-0.50, 0.50], Effective Grid Size: 101, Effective Grain: 0.010, 
QuestHandler #2: Requested Grid: [0, 1000000], Requested Grain: 0.010, Effective Grid: [-500000.00, 500000.00], Effective Grid Size: 100000001, Effective Grain: 0.010, 
```

Kaboom! This is **exactly** what we want: The grid has now the desired size and grain. We might as well leave out the `minVal` and `maxVal` parameters, since, as I pointed out earlier, `QuestObject` completely ignores them.
## Proposed Solution

The simultaneous presence of the `minVal`/`maxVal` and `range` parameters in `data.QuestHandler` is very problematic, most certainly leads to undesired behavior and causes confusion. The underlying QUEST implementation does at no time consider the `minVal` and `maxVal` values, but only the `range` parameter.

I propose:
- The `range` parameter be flagged as deprecated and scheduled for removal at a later release.
- The `minVal` and `maxVal` parameters be kept; this API would also be consistent with the other staircase procedures in PsychoPy.
- Internally, `minVal` and `maxVal` be used to calculate the `range` that `QuestObject` expects.
- This last point is mostly a note to myself: Possibly, [`QuestHandler.calculateNextIntensity()`](https://github.com/psychopy/psychopy/blob/master/psychopy/data.py#L2858) should _not_ take into consideration `minVal` and `maxVal` anymore, because, to my understanding, `QuestObject` would already take care of this; but I would have to dive a bit deeper into its code to fully understand what is going on. However, **if** we decide to implement this change, we must also not forget  to look into [`QuestHandler.addResponse()`](https://github.com/psychopy/psychopy/blob/master/psychopy/data.py#L2819).

I would like to point out that I have not verified if the described problem and the proposed fix will actually resolve the issue/irritation mentioned on the mailing list (referred to in the very first paragraph). However, it should at least be part of the solution.

I would like to also mention that we should probably not start the fiddle with this until we have better (or any) test coverage for `QuestHandler`. I am actually currently working on the implementation of some tests and will refer to them here as soon as they are ready.

**Comment by peircej** [comment]
Ah, I can see that, yes. Looks like VisionEggs QUEST used `range` where we were using `min/max` in the Stairhandler and I can well imagine the person that provided the combination didn't realise the overlap/inconsistency. If possible I think min/max is nicer for a user (and deprecate `range`) rather than having to work out where a centered range should extend up and down to.

**Comment by hoechenberger** [comment]
For reference, the issue regarding improved test coverage: #1007.

**Comment by hoechenberger** [comment]
Thinking more about this, I am not really sure how to implement a "smooth" transition scheme with first deprecating, and only at a later point in time removing, the `range` parameter.

We can safely assume the following use cases up until now:
```python
QuestHandler(…, grain=G, minVal=X,    maxVal=Y,    range=None)
QuestHandler(…, grain=G, minVal=X,    maxVal=Y,    range=Y-X)
QuestHandler(…, grain=G, minVal=X,    maxVal=Y,    range=Z)
QuestHandler(…, grain=G, minVal=None, maxVal=None, range=None)
```
In the following I try to compare the current behavior of these examples to the expected behavior after implementation of the proposed changes.

Example # | Old Behavior | New Behavior | Comments, Implementation, Problems
-------|-------|-------|-------
1 | Granulatiry most likely `!= G`. | Granularity `G`. | `range` would be calculated from `minVal` and `maxVal`.
2 | Granulariy `G`. | Granularity `G`. | Resembles the behavior we always wanted.
3 | Granulatiry `!= G`.  | Unedefined. | Over-specification (`minVal`/`maxVal` *and* `range` supplied). Which parameter(s) should we consider, which ignore?
4 | Granulariy `G`. | Granularity `G`. | The resulting grid spans across the interval `G * [-500/2, 500/2+1]`.

To recap:
* The behavior would change in at least one use case (1, and possibly 3).
* The behavior would be undefined in one use case (3).
* The behavior in one of the use cases (4) always was, and would be, practically pointless to anyone.

The biggest problem is case 3, where we have no idea what the user actually wants, and how to behave correctly.

Since the behavior of the QUEST implementation is bound to change in any way -- because it is not behaving correctly at the moment --, I would now suggest to perform the transition to the new behavior without prior deprecation period of the `range` parameter, because this would lead to situations in which the desired behavior is unclear. I really wouldn't know how to approach this differently, except for adding different types of checks/heuristics and throwing warnings at the users.

Any feedback on these thoughts is highly welcome.

**Comment by hoechenberger** [comment]
We still need to agree upon the best approach here. Re-reading my previous comment, I realize I probably didn't explain the issue arising from keeping both the `minVal`/`maxVal` *and* `range` parameters for a limited period of time in an easily understandable manner. I'll try to recap:

If we
* adapt `QuestHandler` to reflect the `minVal`/`maxVal` paramters on its internal grid, so that the `grain` paramter will be respected,
* *and* keep the `range` parameter,

we wouldn't know what to do if 
* a user *specifies both* `minVal`/`maxVal` *and* `range`
* `range != maxVal - minVal`

In that sense, a "soft" transition of the API, including a deprecation period for `range` (and emitting a respective warning), is not possible -- contrary to what I proposed first.

And even if we *did* keep the *API* unchanged until we eventually removed the `range` argument (and raised an error in case of unclear paramter combinations), we would not be backward-compatible *result-wise* for many users.

Therefore, I would be all for removing the `range` argument right away. Yes, this *will* likely break existing code. But then again, we are facing a rather serious issue here, users a likely running staircases with unintended parameters.  I could contribute a paragraph to the changelog, explaining the adjustments, trying to point out which users will have to expect changed behavior, and how to transition existing code. We could issue a warning that the behavior has changed, and refer to the changelog.

I know this is a very delicate issue on many levels, and I would like to again ask for you to share your thoughts on this one. :)

**Comment by janfreyberg** [comment]
My thoughts from issue #1396 :

> Very well described issue!

> My proposal would be to:
> 
> - keep all three kwargs for now
> - raise an error when all three are actually defined
> - raise a deprecation warning when range is defined
> - remove it in some future release
> That way we keep compatibility for anyone who's using range at the moment, but the bug is clear to anyone who uses all three at the moment

**Comment by hoechenberger** [comment]
Ok good idea, I like that! Brings me to test next issue: currently we have not defined way to deprecate stuff in PsychoPy ;) I have seen in other projects that they used some sort of decorator etc. and they actually _do_ drop deprecated elements after a defined time. I guess we simply haven't gotten around implementing anything similar so far.

**Comment by janfreyberg** [comment]
Yep, that might be helpful! We could start with something like this?

https://wiki.python.org/moin/PythonDecoratorLibrary#Smart_deprecation_warnings_.28with_valid_filenames.2C_line_numbers.2C_etc..29

**Comment by hoechenberger** [comment]
Cool! Although I would like to have an (additional?) approach for function arguments! -- Could you open a new issue for this deprecation stuff, please?

**Comment by hoechenberger** [comment]
x-ref deprecation warnings: #1397

**Comment by hoechenberger** [comment]
> - keep all three kwargs for now
> - raise an error when all three are actually defined
> - raise a deprecation warning when range is defined
> - remove it in some future release

Ah crap, we forgot one important thing, which is that already when implementing`minVal` and `maxVal` handling correctly, behavior would change (see [Case 1](https://github.com/psychopy/psychopy/issues/1005#issuecomment-158651972))

So even if we _do_ keep all three kwargs -- `minVal`, `maxVal`, `range` -- for now, fixing `minVal` / `maxVal` to produce a grid with the correct granularity means we're breaking backward-compat. 
Currently we don't even force specification of _both_ `minVal` and `maxVal`, i.e. users are free to supply _either_, but not required to supply _both_. But without either `minVal` / `maxVal` or `range`, we cannot calculate the grid according to the `grain`. This is all a huge mess and I am starting to believe we should clean it up in _a single_, strict and painful step.

I would propose:

- we fix `minVal` / `maxVal` handling to properly respect the `grain` setting
  - need to provide a big fat warning that behavior has changed, and in which PsychoPy version
- we _keep_ the `range` parameter,
- if only either `minVal` or `maxVal` is specified, enforce specification of the respective other one
- if `minVal` / `maxVal` and `range` are specified, raise an exception
- if only `range` is specified, we could
  - derive the respective `minVal` and `maxVal` parameters automatically:
    ```python
    minVal = startVal - range/2
    maxVal = startVal + range/2
    ```
    (or something like that)
  - raise a helpful deprecation warning that the `range` parameter will be dropped in favor of `minVal` / `maxVal`, and how to transition the code (we can easily provide the derived `minVal` / `maxVal` parameters to the user!)

**Comment by hoechenberger** [comment]
We must also make `minVal` and `maxVal` required arguments at some point. This means the entire function signature would change.

**Comment by hoechenberger** [comment]
Current signature:
```python
    def __init__(self,
                 startVal,
                 startValSd,
                 pThreshold=0.82,
                 nTrials=None,
                 stopInterval=None,
                 method='quantile',
                 beta=3.5,
                 delta=0.01,
                 gamma=0.5,
                 grain=0.01,
                 range=None,
                 extraInfo=None,
                 minVal=None,
                 maxVal=None,
                 staircase=None,
                 originPath=None,
                 name='',
                 autoLog=True,
                 **kwargs):
```

Proposed new signature:
```python
    def __init__(self,
                 startVal,
                 startValSd,
                 minVal,
                 maxVal
                 grain=0.01,
                 pThreshold=0.82,
                 nTrials=None,
                 stopInterval=None,
                 method='quantile',
                 beta=3.5,
                 delta=0.01,
                 gamma=0.5,
                 range=None,
                 extraInfo=None,
                 staircase=None,
                 originPath=None,
                 name='',
                 autoLog=True,
                 **kwargs):
```
In Python 3 we could have just used required keyword arguments... Another reason to finally do the switch!

**Comment by hoechenberger** [comment]
Also wondering if we shouldn't give `beta`, `gamma` and `delta` more "useful" names, i.e., `steepness`, `guessingRate`, `lapseRate`.

**Comment by peircej** [comment]
No, please don't change them to more "useful" names. I'll just not accept the pull request! Are you just baiting me here? ;-)

To change the order of args is bearable I guess, but it doesn't seem necessary. If they are needed then just raise an error if the user doesn't define them. Doesn't that achieve the same thing, except without breaking anyone's working experiment?

But here's another suggestion: just let it be and work on something more useful! ;-) If you want it to be on this improving staircases then how about forgetting QUEST altogether (it was written decades ago... in BASIC using GOSUB routines!). Andrew Watson, one of the original QUEST authors, wrote to me recently asking if we'd implement his new QUEST+ as an improved alternative. I can send the details, which he's written as a paper. We can recommend that people use it instead of QUEST and you can create it from scratch any way you like! I'm happy for you to use whatever kwargs you like for it! ;-) Does that sound good? This is the abstract from his paper (not sure if it's out yet)

> QUEST+ is a Bayesian adaptive psychometric testing method that allows an arbitrary number of stimulus dimensions, of psychometric function parameters, and of trial outcomes. It is a generalization and extension of the original QUEST procedure, and incorporates many subsequent developments in the area of parametric adaptive testing. With a single procedure, it is possible to implement a wide variety of experimental designs, including conventional threshold measurement, measurement of psychometric function parameters such as slope and lapse, estimation of the contrast sensitivity function, measurement of increment threshold functions, measurement of noise masking functions, Thurstone scale estimation using pair comparisons, and categorical ratings on linear and circular stimulus dimensions. QUEST+ provides a general method to accelerate data collection in many areas of cognitive and perceptual science.

**Comment by peircej** [comment]
Ah, yes, it was published in March: http://jov.arvojournals.org/article.aspx?articleid=2611972&resultClick=1
The idea is to take QUEST and make it more general, to estimate multiple parameters (like slope and lapse rate rather than just threshold) and more complex tasks (like multi-way categorisation rather than just yes/no)

**Comment by hoechenberger** [comment]
> No, please don't change them to more "useful" names. I'll just not accept the pull request! Are you just baiting me here? ;-)

Hehe, no, not really, I swear ;) I just thought: Ugh, we _will_ have to break this, so why not take the entire thing apart while we're at it anyway. But yes, sure, we can also keep the current argument names :)

> To change the order of args is bearable I guess, but it doesn't seem necessary. If they are needed then just raise an error if the user doesn't define them. Doesn't that achieve the same thing, except without breaking anyone's working experiment?

Yes, we could do that, although I would prefer a more explicit API. But yes, this would certainly work!

> But here's another suggestion: just let it be and work on something more useful! ;-) If you want it to be on this improving staircases then how about forgetting QUEST altogether (it was written decades ago... in BASIC using GOSUB routines!). 

Hey, doesn't mean it's bad ;)

I strongly believe that, if we _do_ offer a staircase implementation, it should at least function as advertised, which is currently not the case... 

Also we (our lab) collected, like, hundreds of datasets for gustatory threshold estimation using PsychoPy's QUEST (from version 1.82 or so) over the past 1.5 years, with (IMHO) great success, and a related publication of mine is currently being reviewed. I would like to "clean up" the PsychoPy implementation to ensure everything is properly documented, working as expected, and therefore replicable.

> Andrew Watson, one of the original QUEST authors, wrote to me recently asking if we'd implement his new QUEST+ as an improved alternative. I can send the details, which he's written as a paper. We can recommend that people use it instead of QUEST and you can create it from scratch any way you like! I'm happy for you to use whatever kwargs you like for it! ;-) Does that sound good? This is the abstract from his paper (not sure if it's out yet)

Sounds great! I actually implemented [SIAM](https://www.ncbi.nlm.nih.gov/pubmed/2283438) and [quick Yes-No](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4523789/) last year, but never proposed them for inclusion in `master`, because I never had the time to write all the documentation and test cases.

QUEST+ indeed sounds interesting, seems a bit like the Psi or quick Yes-No approach. Fulltext of the paper can be found at http://jov.arvojournals.org/article.aspx?articleid=2611972
I could imagine myself implementing this thing, maybe together with @janfreyberg! But the authors do not provide data that shows how QUEST+ compares to QUEST if only the threshold is to be estimated. Using QUEST, I could estimate usable gustatory thresholds in < 20 trials; wonder if this would work with QUEST+ too.

In any case, I think we really should get at least the most serious issues about our QUEST implementation fixed... This stuff won't let me sleep at night! ;)

**Comment by hoechenberger** [comment]
> The idea is to take QUEST and make it more general, to estimate multiple parameters (like slope and lapse rate rather than just threshold) and more complex tasks (like multi-way categorisation rather than just yes/no)

Yep, it's similar to Psi and the methods proposed [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4523789/).

**Comment by hoechenberger** [comment]
> In any case, I think we really should get at least the most serious issues about our QUEST implementation fixed...

... or we should emit a warning and mark the algorithm as kind-of-flawed in the docs, start implementing QUEST+, see how it performs, and if it can actually keeps up with QUEST for single-parameter estimations (e.g., thresholds), officially recommend it and declare QUEST deprecated. @janfreyberg?

**Comment by peircej** [comment]
That's the direction I'm suggesting. Put a band-aid on the current QUEST with improved documentation and some warning/error messages when people are about to fall into one of its traps. Then focus the effort on the new improved one.

Andrew "Beau" Watson has already come back to me, excited that we might take this up (he wants a package to use it to get it into mainstream). He's very happy to help with implementation ideas as needed. And I think he already answered the question above about performance against QUEST in his email: "QUEST+ subsumes vanilla QUEST, but offers so much more, and would have a somewhat different set of configuration options/parameters."

**Comment by hoechenberger** [comment]
> That's the direction I'm suggesting. Put a band-aid on the current QUEST with improved documentation and some warning/error messages when people are about to fall into one of its traps. Then focus the effort on the new improved one.

Yeah, this is probably the sanest approach. Although not super satisfactory. @janfreyberg, what's your stance on this?

> Andrew "Beau" Watson has already come back to me, excited that we might take this up (he wants a package to use it to get it into mainstream). He's very happy to help with implementation ideas as needed. And I think he already answered the question above about performance against QUEST in his email: "QUEST+ subsumes vanilla QUEST, but offers so much more, and would have a somewhat different set of configuration options/parameters."

Oh, neat. You see, I have been working with Docker (actually I'm currently in the process of creating a Python & R data analysis image), and have done a bit of Python web development, i.e., exposed some PsychoPy functionality via a REST API. Never actually finished implementing the JS frontend, though; but the idea was to have a PsychoPy QUEST staircase running in the browser. Could probably be an interesting approach for this project, too...

**Comment by hoechenberger** [comment]
About implementing QUEST+, again:
Since I've implemented a similar algorithm (quick Yes-No) last year, I believe I actually could help out here. The data becomes multidimensional (each parameter to estimate adds another orthogonal dimension!!), which can neatly be dealt with using [xarray](http://xarray.pydata.org). Aaaand it quickly eats up all your memory :D Sounds like an interesting challenge indeed! How would we go about this, does Prof Watson have a specific time frame in mind? -- You may of course also contact me via email with further details if you think that's more appropriate than this issue tracker. :)

**Comment by janfreyberg** [comment]
I think this sounds like a good idea! I would be keen on making it very clear with warnings and in the docs that the new quest is the preferred one, as otherwise we'd have lots of forum posts about it :P 

But yes, this seems like a great way to keep backward compatibility and sorting out the confusion. I'm interested in getting that done :)

**Comment by szekely** [comment]
Hello all,

I just wanted to chime in as a somewhat naive user.  My group has been having issues with using QuestHandler() for a 2AFC task that seem to strongly echo the potential problems mentioned here.  We specify minVal and maxVal, and largely keep all the default parameters for a 3 up 1 down staircase, and don't alter grain or specify range.
We have huge jumps (low granularity) based on more than one incorrect response, and end up with quantile(p=0.75) above maxVal or below minVal with a distressing degree of regularity.  Would adding a range of maxVal - minVal and specifying the grain help get accurate outputs?

Best,
Akos Szekely

**Comment by hoechenberger** [comment]
Hi @szekely,

would you mind sharing the parameters you pass to the `QuestHandler` or, even better, an [MWE](https://stackoverflow.com/help/mcve)? I don't believe the issue you experience is related to the granularity, but rather caused by the parameters used. Thanks!

**Comment by szekely** [comment]
Hello @hoechenberger,

Here's the best I can come up with as far as an MWE is concerned:

```
from psychopy import visual,core, gui, data, misc, event
mywin = visual.Window([1440,900], color=('#999999'),colorSpace='rgb',fullscr=True,monitor="testMonitor", units="deg")
Image=visual.ImageStim(mywin, image='Path_to_image_here', mask=None, pos = [0,0]) #I'd normally have two lists of images loaded instead of just one, as there are two image types participants decide between
Mask=visual.ImageStim(mywin, image='Path_to_mask_here', mask=None, pos = [0,0])
thisStair=data.QuestHandler(.1, .2, pThreshold=0.82, extraInfo=1,gamma=0.5,
            nTrials=128, minVal=0, maxVal=1, stepType='log') 
timer=core.Clock()
for trial in range(0,5):
    Image.setContrast(thisStair.next())
    Image.draw()
    mywin.flip()
    Accuracy='NR'
    RT='NR'
    timer.reset()
    while timer.getTime()<.1:
        for key in event.getKeys():
            RT=timer.getTime()
            if key in ['num_1','1']:
                Accuracy=1
            else:
                Accuracy=0
    Mask.draw()
    mywin.flip()
    timer.reset()
    while timer.getTime()<.3:
        for key in event.getKeys():
            RT=timer.getTime()
            if key in ['num_1','1']:
                Accuracy=1
            else:
                Accuracy=0
    mywin.flip()
    timer.reset()
    while timer.getTime()<1:
        for key in event.getKeys():
            RT=timer.getTime()
            if key in ['num_1','1']:
                Accuracy=1
            else:
                Accuracy=0
    if Accuracy=='NR':
        thisStair.addData(0)
    else:
        thisStair.addData(Accuracy)
print thisStair.quantile(p=0.75)
```

Best,
Akos Szekely

**Comment by hoechenberger** [comment]
Thanks @szekely! May I ask which version of PsychoPy you are using?

**Comment by szekely** [comment]
@hoechenberger, that may be an issue.  The computer I test things on is version 1.82.01 with Windows 7, but a lot of problems arise on computers with version 1.85.6 or 1.90.00 with Windows 10

**Comment by hoechenberger** [comment]
Looking at the MWE, the code wouldn't (or at least: shouldn't) really work like that anyway… In your actual experiment, do you really loop over trials like this:

```python
for trial in range(0,5):
```

or do you iterate over the `QuestHandler`, i.e.,

```python
for contrast in thisStair:
```

**Comment by szekely** [comment]
The actual code looks more like this:
```
while TotalBlocks < maxBlocks: 
    checklist=checkmaker(0,32) #list for this block
    pathnumsF=quickListMaker(1,16) #counter-balancing by making this list each block
    pathnumsN=quickListMaker(1,16) #counter-balancing by making this list each block
    TrialNum=0 #for writing
    for trial in range(0,16):
        random.shuffle(staircase)
        for thisStair in staircase:
            thisIntensity=thisStair.next()
```
Though I have two of those `thisStair` variables within a `staircase` variable

**Comment by hoechenberger** [comment]
Wow that's super convoluted ;) But I have an idea what's might be the problem. Will get back to you.

**Comment by szekely** [comment]
(chuckles) oh definitely, I had help writing this six years ago when I was starting out and haven't touched it since.  The itch to re-code everything is strong.  Either way, @hoechenberger, thanks very much for your help!
