### ISSUE TITLE
`nTrials` parameter in `MultiStairHandler` is ambiguous

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1016]
Depending on the staircase type, the `nTrials` argument of the `MultiStairHandler` can have contrdicting meanings:
- for simple staircases, this is the _minimum_ number of trials to execute per staircase
- for QUEST staircases, this is the _maximum_ number of trials to execute per staircase

This at least needs clarification in the docs.

However, I think a generally better approach would be to start thinking about the removal of this parameter, and replacing it with a `minTrials` and `maxTrials` parameter.

**Comment by hoechenberger** [comment]
For the time being, maybe just updating the documentation would suffice. Would not break backward compatibility.

**Comment by peircej** [comment]
I think I agree with the minTrials and maxTrials, at least in principal. 
nTrials should provide the current behaviour and a logging.warning() to 
suggest using the more explicit versions?

-- 
Jon Peirce
http://www.peirce.org.uk

**Comment by hoechenberger** [comment]
Great idea, will look into this!
