### ISSUE TITLE
Order of routine tabs is not preserved when re-opening Builder experiments

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1020]
I've just started working with the Builder a bit, and it occurs to me that the routine tabs are always ordered alphabetically automatically when opening a Builder experiment, disregarding previous re-arrangements I had done before saving the experiment. I would like to have the routine tabs ordered the way they appear in the experiment, but right now I have to re-arrange them manually  that way every time I re-open the Builder.

**Comment by peircej** [comment]
Yes, this is one of those things that would be good but I've never cared enough to spend time on it. 
Two ways to go about it:
  - detect the events thrown by the Routine panes (wx notebook pages) being moved and reorder each time that occurs
  - when it comes to saving the experiment simply clear the list of Routines and recreate it by iterating through the notebook pages

I expect the second one will be easier to implement

**Comment by hoechenberger** [comment]
Thanks for these hints. If nobody else is planning to work on this, I think I would try to implement the appropriate changes as soon as I'm finished with my staircase project. :) Because this was one of the things that made using the builder a bit unpleasant to me.
