### ISSUE TITLE
Renaming of static component in builder causes issues

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1022]
I renamed a static component from ISI to ITI (typo), while this component was "in use" by stimuli selected to be "set during: Feedback.ISI". I then couldn't edit those stimuli anymore (clicking on them, or right-clicking -> Edit), getting the error messages:

``` python
Traceback (most recent call last):
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 1262, in OnMouse
    self.editComponentProperties(component=self.componentFromID[icons[0]])
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 1539, in editComponentProperties
    helpUrl=helpUrl, editing=True)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 3211, in __init__
    editing=editing)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 2257, in __init__
    ctrls = self.addCategoryOfParams(theseParams, parent=page)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 2319, in addCategoryOfParams
    self.addParam(fieldName, parent, sizer, currRow, valType=self.params[fieldNa
me].valType)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 2419, in addParam
    param=param, advanced=advanced, appPrefs=self.app.prefs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.83.01-py2.
7.egg\psychopy\app\builder\builder.py", line 2070, in __init__
    index = allowedUpdates.index(param.updates)
ValueError: 'set during: Feedback.ISI' is not in list
```

I then renamed the component back to ISI, but suddenly my complete experimental flow was empty! Also when compiling the experiment, I get an almost-empty Python file. However, at least I could then edit the stimuli and set their updates to "constant".

But my experimental flow is gone, although all routines are still available in their respective tabs.

Super frustrated right now :( 

Related: #853, #871

**Comment by jeremygray** [comment]
It would be nice if the undo-stack enabled people to back-track in such situations. 

ISI components should keep track of what things depend on them, to enable reference-counting (as is done for python objects), and don't allow a delete until the ref count is appropriate (1 or 0, depending on how you count).

**Comment by peircej** [comment]
@jeremygray  I think the undo stack should be able to backtrack but that only survives as long as the experiment is kept open

**Comment by TEParsons** [comment]
Tried this out in 2021.2.0 and seems to no longer be an issue :) Instead of crashing it reverts back to Constant - might be the changes we made to Params in 2021.1, as there's new behaviour when the value is not in allowedVals for a list ctrl
