### ISSUE TITLE
Support for "static" periods of random duration

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1026]
It would be nice to have built-in support for creating variable-duration ITIs, as is often required in experiments to avoid stimulus anticipation.

## Proposed Solution 1
Extend the `core.StaticPeriod` API:

Current:
```python
StaticPeriod(screenHz=None, win=None, name='StaticPeriod')
 ```
New:
```python
StaticPeriod(screenHz=None, win=None, randomRange=None, 
             randomDist='uniform', name='StaticPeriod')
 ```
with `randomRange` taking an array-like object of length 2, specifying the closed interval of random durations to draw from in a manner specified by `randomDist`. If `randomRange` is `None` (default), the behavior would be identical to the current one.

The order of the first two arguments (`screenHz`, `win`) would stay the same to ensure backward compatibility.

I don't know if this period would still qualify as "static" then, though. :)

## Proposed Solution 2

Add a new `core.RandomPeriod`:
```python
RandomPeriod(range=None, dist='uniform', screenHz=None,
             win=None, name='RandomPeriod')
 ```
with a default `range` of `[1, 2]` (seconds; not part of the signature, since lists are mutable).

Any thoughts on this are highly welcome.

**Comment by peircej** [comment]
This is confusing but static periods don't cause there to be an interval at all. They merely indicate to PsychoPy that this would be a good time to do background work like loading files.

**Comment by hoechenberger** [comment]
I always thought the intended use was like:
```python
from psychopy.core import StaticPeriod

ITI = StaticPeriod()
ITI.start(2)
# do stuff
# ...
ITI.complete()
```
But a random period could probably also be easily achieved via
```python
ITI.start(1 + np.random.rand())
```
or similar in the coder, so there's no need to change anything for now. Things might look different with the respective builder component, but this would be another issue. Closing for now. Thanks for your comment, Jon.
