### ISSUE TITLE
StaticPeriod: `screenHz` argument superfluous?

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1027]
The current API for `core.StaticPeriod` is:
```python
StaticPeriod(screenHz=None, win=None, name='StaticPeriod')
```
However, since a `win` is specified, `screenHz` could be considered redundant:
```python
>>> 1 / win.monitorFramePeriod
Out[2]: 60.17153132027925
```
In fact, **not** specifying `screenHz` and only using the "true" refresh rate, derived from `win.monitorFramePeriod`, would improve timing accuracy.

The API could be simplified like:
```python
StaticPeriod(win=None, name='StaticPeriod')
```

**Comment by peircej** [comment]
I don't see a need to remove this. Doing so would potentially break existing code and some users might actually want to set the refresh to something (e.g. preparing an experiment for a different machine?). Either way, I don't think this is something that needs doing.
