### ISSUE TITLE
Add tests for Psi method

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1035]

**Comment by JosephGlavan** [comment]
What sort of tests are we interested in for Psi? The way I've used to validate that it works has been to generate responses using some psychometric function and then see if Psi recovers those parameters. I can provide sample code if helpful

**Comment by hoechenberger** [comment]
The sample code would be most helpful! The code could then be used to create unit tests to ensure we won't break `PsiHandler` when refactoring parts of PsychoPy :)

**Comment by JosephGlavan** [comment]
This simulates 100 independent runs of Psi within each of 10 different levels of nTrials (5, 10, 20, 30, 40, 60, 100, 200, 250, 300) to examine parameter convergence over trials.  

```python
from __future__ import division #so that 1/3=0.333 instead of 1/3=0
from psychopy import visual, core, data, event, logging, gui, sound
from psychopy.constants import * #things like STARTED, FINISHED
import numpy as np  # whole numpy lib is available, prepend 'np.'
from numpy import sin, cos, tan, log, log10, pi, average, sqrt, std, deg2rad, rad2deg, linspace, asarray
from numpy.random import random, randint, normal, shuffle
from scipy import stats
import os #handy system and path functions
import random
import time, sys

random.seed(1337)

logfile = open("Psi Validation GnG.txt", 'a')
logfile.write("Set\tRun\tEstimate\tLocation\tSlope\n")

true_lambda = [.05, .01]
test_sets = [5, 10, 20, 30, 40, 60, 100, 200, 250, 300]
guess_rate = 0.04

for each in test_sets:
    for i in range(100):
        mypsi = data.PsiHandler(each, [.001, .2], [0.001,.2], [.001, .1], 200, .001, .0005, guess_rate, stepType='log', prior=None, TwoAFC=False)
        trialcounter = 0
        for trial in mypsi:
            trialcounter += 1
            chance = random.random()
            decision_threshold = stats.norm.cdf(trial, true_lambda[0], true_lambda[1])*(1-guess_rate)+guess_rate/2 # taken from psychometric function specified in ./contrib/psi.py
            if chance < decision_threshold:
                mypsi.addResponse(1)
            else:
                mypsi.addResponse(0)
        myL = mypsi.estimateLambda()
        logstr = str(each) + "\t" + str(i) + "\t" + str(mypsi.estimateThreshold(0.9)) + "\t" + str(myL[0]) + "\t" + str(myL[1]) + "\n"
        logfile.write(logstr)
logfile.close()
print("\nFinished...")
```

**Comment by hoechenberger** [comment]
This is awesome, Joseph! Would you like to write a unit test for the `PsiHandler` yourself? With this code, you're almost there. I could try to guide you through the process. (But not before the end of this week, as I'll be busy :))

**Comment by JosephGlavan** [comment]
I'm extremely busy this week and next with Finals, but I could probably write them after. You'll have to guide me through it. I'm not sure what exactly to test and how. @jeremygray I believe you were asking about this?

**Comment by hoechenberger** [comment]
A unit test essentially just runs part of a program, and checks if the produced result matches the expected result. If it does, the test passes; if it doesn't, the test fails, and you know something fishy is going on: usually, you introduced a bug somewhere. Examples for unit tests of staircase handlers can be found here: https://github.com/psychopy/psychopy/blob/master/psychopy/tests/test_data/test_StairHandlers.py#L115

Let me know when and if you have time and motivation, and I will help you putting something together for Psi. Jeremy might also be willing to help, yes. :)

**Comment by jeremygray** [comment]
Yeah, I think I did ask somewhere -- it sounds like Richard is already on it! I was going to suggest he help with this since he's thought through adaptive methods and has more expertise than I do with that.

**Comment by hoechenberger** [comment]
@JosephGlavan just poke me when you're ready.

**Comment by jeremygray** [comment]
I'm certainly willing to be involved here too. Tests are really awesome. I consider them to be an essential part of the documentation: the code is supposed to work exactly like this, and not like that. Test that the right things happen, and that the wrong things do not.

**Comment by jeremygray** [comment]
@JosephGlavan When you have a moment, would you mind rewriting the numpy import to avoid using a wildcard in psi.py? Either `import numpy as np` and then pre-pend `np.` to everything that needs it, or `from numpy import (linspace, ....stuff........).

**Comment by JosephGlavan** [comment]
I'll add it to the to-do list
