### ISSUE TITLE
Some methods in `data.py` violate LSP

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1042]
Some methods in `data.py` have signatures differing from those of their base classes; this violates [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle) and can lead to problems.

**Comment by peircej** [comment]
Unless the problems it leads to are serious I don't want to change any call signatures. Users really do't like the API changing unless it has to

**Comment by hoechenberger** [comment]
Hi Jon, the good thing is that it won't break the API; I think adding `*args` or `**kwargs` arguments in some places would suffice, but I will have to do some more research about it first.

The problems the current implementation can lead to are not just of hypothetical nature. Consider for example `TrialHandlerExt.saveAsWideText()` (code reformatted to save space here):
```python
class TrialHandlerExt(TrialHandler):
    ...
    def saveAsWideText(self, fileName, delim='\t', matrixOnly=False, appendFile=True):
```

As we can see, `TrialHandlerExt` inherits from `TrialHandler`, so let's look at this class:
```python
class TrialHandler(_BaseTrialHandler):
    ...
    def saveAsWideText(self, fileName, delim=None, matrixOnly=False, appendFile=True,
                       encoding='utf-8', fileCollisionMethod='rename'):
```
As we can see, `TrialHandlers` implementation of `saveAsWideText` takes more arguments than `TrialHandlerExt`'s.

The following code demonstrates the kind of problems this causes:
```python
from psychopy.data import TrialHandler, TrialHandlerExt
import tempfile

conditions = [{'cond0': 0, 'cond1': 1}]
nreps = 10

trialHandler = TrialHandler(conditions, 10)
trialHandlerExt = TrialHandlerExt(conditions, 10)

if isinstance(trialHandler, TrialHandler):
    trialHandler.saveAsWideText(
        tempfile.TemporaryFile(), fileCollisionMethod='overwrite'
    )

if isinstance(trialHandlerExt, TrialHandler):
    trialHandlerExt.saveAsWideText(
        tempfile.TemporaryFile(), fileCollisionMethod='overwrite'
    )
```
Output:
```python
Traceback (most recent call last):
  File "C:/Users/hoechenberger/.PyCharm50/config/scratches/scratch_2", line 17, in <module>
    tempfile.TemporaryFile(), fileCollisionMethod='overwrite'
TypeError: saveAsWideText() got an unexpected keyword argument 'fileCollisionMethod'
```
The error occurs because `trialHandlerExt` is indeed an instance of `TrialHandler`, but doesn't behave like a `TrialHandler`. This should never, ever happen without extremely good reason in OOP.

I am very confident we can find a solution that won't break backward-compatibility of the API.

**Comment by m-macaskill** [comment]
I guess the original `TrialHandler` SaveAsWideText method could stand to get those extra arguments added (and the corresponding features implemented). If those arguments have default values reflecting current behaviour, then it probably wouldn't result in any old code breaking?

**Comment by hoechenberger** [comment]
@m-macaskill Yes, that's what I assume. :)
