### ISSUE TITLE
PsiHandler API potentially counter-intuitive

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1043]
As was [pointed out](https://github.com/psychopy/psychopy/issues/1013#issuecomment-159314439) by @JosephGlavan, the current Psi staircase API might be confusing:

>The three "precision" keywords (intensPrecision, alphaPrecision, betaPrecision) all specify the step sizes of the array to search over, not the number of step [...]

> The exception to this is when the stepType is set to 'log'. Then intensPrecision specifies the number of steps [...] alphaPrecision and betaPrecision would still specify the size of the steps though. Admittedly this might be confusing for the user, and if it's generally agreed by everyone that it should be changed I can. [...] Unfortunately step size is not meaningful for log space.

Since we are going to break API backward compatibility anyway (#1034), we should discuss if further changes are required before the next PsychoPy version is released.

Joseph, what would your proposal be to "harmonize" the linear and log step behaviors?

Since the different implications of the `intensPrecision` parameter in "linear" and "log" environments are already documented in the docstring, I don't necessarily see a reason to change anything at all. But if somebody else does, we should discuss it. :)

**Comment by JosephGlavan** [comment]
The most "harmonious" thing to do would be to switch everything over to number of steps. This also makes it easy to calculate the maximum size of the 4D array underlying the PsiObject (2 * #ofIntensitySteps * #ofAlphaSteps * #ofBetaSteps), which is limited by your memory size and OS type (32bit/64bit) I believe.

On the flip side, my expectation is that what the user cares most about is the step size. As long as the number of steps is small enough to run smoothly, the meaningful information is what range of values am I searching over and with what level of detail am I searching. While it's possible to calculate the logspace from a specified step size, it doesn't translate directly to the granularity of the parameters like it does in linear space.

Besides switching everything to number of steps, I can't see any other way to make the instructions more uniform than they already are. But then again it is difficult for me to approach this code from a new user's perspective.

**Comment by hoechenberger** [comment]
So it seems the current implementation is the best compromise between consistency and users' expectations. Thanks for your elaboration on that, Joesph. Closing for now.
