### ISSUE TITLE
StairHandler should support different step sizes for up and down steps

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1047]
[Requested on the mailing list.](https://groups.google.com/d/msg/psychopy-users/PQwxOHsU6RA/OPcgvRtfjHUJ)

This should probably go into a new class.

**Comment by janfreyberg** [comment]
I just came to this issue while working on a staircase - is this implemented yet? At the moment, I'm just re-assigning the stepsize on every iteration, but that seems like bad practice...
