### ISSUE TITLE
Allow specification of decimal separators when saving text data files

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1049]
Esp. German systems tend to interpret a comma as decimal separator. This leads to issues when opening PsychoPy output files (CSV, TSV) in Excel. We should allow the users to select a custom decimal separator, or, even better, use the system default.

**Comment by peircej** [comment]
For the new trialhandler that will be easy because pandas is being used to output the csv and pandas supports `decimal` as an arg

**Comment by hoechenberger** [comment]
Absolutely, I hadn't thought about this. This is great :)

And it also reminds me, I cannot really follow anymore with all the different TrialHandlers in data.py and all. Maybe we should start discussing about a larger data.py refactoring, involving a split across smaller sub-modules or so (I don't have any experience with this, so don't know if this would cause breakage of older code); you recently suggested something similar on the mailing list IIRC? (my memory is bad, sorry ;)) Would that be worth opening another issue here? Would we want to eventually migrate all CSV/TSV output to pandas anyway? Because in that case, maybe the decimal separator thingy should wait until we have pandas in place anywhere required, and resolving this issue will be a piece of cake.

**Comment by jeremygray** [comment]
Yes, best to start a new issue for discussion of breaking out data.py into separate files. (Yes, Jon did suggest this, and it need not cause any old code to break.)
