### ISSUE TITLE
Output window buggy (cursor/editing unreliable)

### ISSUE THREAD

**Issue by wildetudor** [psychopy/psychopy#1050]
After an experiment finishes, the Output window opens with any error/warnings. However, the content of this window is unstable, i.e. the cursor does not reliably appear in there for the user to copy or delete text from the window. I say 'reliably' because if you wait a few seconds, the cursor suddenly appears in there and you have normal editing abilities. Tested this on two Win7 machines. Hope this helps figuring out what the bug is.

**Comment by wildetudor** [comment]
Just an update to say that this problem continues to exist in v1.83.04 too. It manifests itself in that it takes a lot of fiddling with the Output window before one can use it (e.g. copy text from it or scroll it).

**Comment by hoechenberger** [comment]
Thanks for reporting, @wildetudor 
On what platform does this happen?

**Comment by wildetudor** [comment]
You mean what OS? That's Windows 7 as I mentioned above. However, I have realised that a workaround for this bug is to just click in the very bottom part of the Output window - then you can select text and move the cursor.

**Comment by hoechenberger** [comment]
Have you tried PsychoPy with 1.82 yet? Does the problem still exist for you? Cannot really reproduce it on my Windows computer...

**Comment by wildetudor** [comment]
1.82 not, but newer versions (1.83 and 1.84). But I think the workaround that I mentioned should be satisfactory for most users.

**Comment by hoechenberger** [comment]
Haha that was a typo from my side, I meant 1.84, of course. :)

So this appears to be not a "real" bug then, but rather a usability issue. Glad you found a workaround!
