### ISSUE TITLE
Keyboard component should allow specification of how many characters to read

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1052]
If I am not mistaken, the Builder keyboard component cannot easily be configured to collect a specific number of characters before terminating; it is always terminated after a certain duration or as soon as a user-specified code condition is met. It would be nice if there was an explicit field in the settings form that allowed to directly select how many characters to read.

**Comment by lucaf** [comment]
Also, I think it'd be useful to store the keys sequence as a unicode string field of the BuilderKeyResponse object. Or, better, it'd be great if we could automatically link a BuilderKeyResponse a  to a TextStim, whose text field would be updated by the former automatically. By this way one could record an input text from the user and get it echoed on the screen in the desired format. The BuilderKeyResponse form could come with an extra field 'Echoing', where to specify the name of the TextStim object.
