### ISSUE TITLE
psychopyApp.py exits with no error message after startup when .psychopy2 directory is not owned by user

### ISSUE THREAD

**Issue by fnielsen** [psychopy/psychopy#1055]
Starting psychopyApp.py it immediately exits with no error message. The problem seem to be the permission on the ~/.psychopy2 directory. Installation with root on Ubuntu makes it owned by root. When changing the owner and group of the directory psychopyApp.py starts up.

psychopyApp should have a better error message in this case.

This was for the present pip version.

**Comment by jeremygray** [comment]
I agree there should be a better error message, should be easy to add although might not be easy to get that error message back out to the user if the app exits immediately.

Just trying to understand what happened in your case: Did "installation as root" really create the ~/.psychopy2 directory? Here ~ should be root, yes? And if ~ is not root, I'm surprised that it knows which regular user is intended when installing as root.

**Comment by fnielsen** [comment]
Regarding your question 'Did "installation as root" really create the ~/.psychopy2 directory?' Apparently yes:

    $ mv .psychopy2/ ~/tmp/.psychopy2
    $ sudo pip uninstall psychopy
    $ sudo pip install psychopy==1.82.1
    $ ls -tral .psychopy2/
    total 16
    drwxr-xr-x 142 fnielsen fnielsen 12288 Dec 16 13:34 ..
    drwxr-xr-x   2 root     root      4096 Dec 16 13:34 .

**Comment by fnielsen** [comment]
Should I make a new issue on the permission issue? As far as I see https://github.com/psychopy/psychopy/commit/300175b1977f90322a69d772bde1f8c3a6619a63 changes to a more informative error message, - not the installation issue.

**Comment by jeremygray** [comment]
Yes, please open a new issue and link to this one. Your shell output is useful. The bug is related to the fact that `os.path.expanduser('~')` is always the regular user, not root when using sudo. Should be easy to fix.

**Comment by fnielsen** [comment]
Thanks! As noted about I have created a new issue https://github.com/psychopy/psychopy/issues/1073
