### ISSUE TITLE
python3: propose move to pillow 3.x

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1076]
As a small part of #1061 (python 3):

PIL development seems to have stalled ~6-7 years ago, and seems unlikely to support python3. The 3.0.x version of its friendly fork, pillow, has deprecated the Image .tostring() and .fromstring() methods, and will raise an error. All PsychoPy visual tests pass on travis when using pillow 2.9, and also pass with 3.x if .tostring() is replaced by .tobytes(), and .fromstring() by .frombytes() in PsychoPy code. Visually, images look right on my local machine. So this seems like a good direction to go for python3 support in PsychoPy. Anything else to consider with pillow?

There are a couple non-pillow uses of the characters "tostring": one is XML-related code, and one is pygame.image.tostring. These should not be changed (at least not as part of moving to pillow 3.x).

**Comment by peircej** [comment]
I've been using pillow in place of PIL for some time and it's fine. As always we can do this so as not to break existing installations (people might have old versions of PIL installed and it was working fine already so no need for them to update):

https://github.com/psychopy/psychopy/commit/19ac0731ce2f517717d1c38bdb851a3caf51e704#diff-cda84636cb4f6d4cb755c63f677d76ac

**Comment by jeremygray** [comment]
Ah, great. On travis, pyautogui pulled in pillow 3.x by default, and most visual tests promptly failed. So it sounds like its just a case of doing a similar try except to handle this in all other places (= just a few.)

**Comment by jeremygray** [comment]
numpy has a similar issue (tostring vs tobytes), looks like it supports both, at least currently (possibly not under python 3)

**Comment by peircej** [comment]
looks like tobytes was added there in v1.9 (about a year ago) so if you're changing anything it should support both options for the foreseeable future. Actually, I expect numpy will maintain support for the tostring method for a good while so I'd say just leave it as is.

**Comment by jeremygray** [comment]
Sounds good, will leave numpy tostring as is until something breaks.
