### ISSUE TITLE
preferences / configobj.py needed?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1077]
I only see one place that imports and uses configobj, namely preferences.py. The current import there is an implicit relative import of the file in that directory, configobj.py. However, the build instructions and .travis.yml file all specify that configobj needs to be packaged or installed as appropriate. So the package is there but not being used. It seems to work either way, when starting the app. A diff of the file against a current version of configobj.py from that package reveals quite a few changes, including some that look relevant for python3 (like the six module).

So I think we can and probably should no longer include the file within preferences/. Same for validate.py.

**Comment by jeremygray** [comment]
713c9a82c46e6

**Comment by peircej** [comment]
Hazy memory on this. I think at one point a long time ago I came across 
this and because it was a single-file and a compatible license I just 
provided it within prefs. But then yaroslav didn't like that because 
Debian has a rule of not including things that are part of another 
package (because we end up not updating it and getting multiple old 
versions of the same file on a system).

I think at the time I left it in because it used to be harder to install 
stuff (and Yaroslav removes it during debian package build) but this 
installs with pip so no big deal either way.

**Comment by jeremygray** [comment]
Cool, it sounds pretty safe to remove the files then -- we would have heard from Debian users, I would think.

**Comment by jeremygray** [comment]
Seems best to package configobj using pip or however you do it, and not include the extra two files in preferences/. I can't tell what adjustments might be needed during packaging.

**Comment by Victor-Savu** [comment]
Just a note that the `configobj` package should be added as a dependency (in `setup.py`) so that `pip install psychopy` transitively installs `configobj`.

**Comment by peircej** [comment]
It looks like it is there already (line 23):
https://github.com/psychopy/psychopy/blob/master/setup.py

Either you're using a different version of setup.py or that dependencies system isn't working.

**Comment by Victor-Savu** [comment]
Thanks for pointing it out! I will test this evening. I installed `psychopy` using `pip install psychopy`. I will try to reproduce by installing from git and will get back to you.

**Comment by peircej** [comment]
Ah, wait, yes. `pip install psychopy` doesn't install the dependencies at all in the released version. We've added that to the repository for the next major release (1.86) but that hasn't happened yet. You can use the repository version and to `pip install .` instead

**Comment by Victor-Savu** [comment]
@peircej Oh, I see. This was already solved. Thank you and I am sorry for the noise.
