### ISSUE TITLE
VLC problem perhaps?

### ISSUE THREAD

**Issue by ralphp15** [psychopy/psychopy#1078]
Just a puzzler that someone might be able to cast come light on.

I'm running a very basic set of questionnaires in an up to date version of PsychoPy, using an old Windows XP machine.  For a couple of years now I've had no issues with PsychoPy on this machine.

I'm finding that maybe 50% of the time when I run my questionnaires, PsychoPy fails to clear the screens of text, leaving the title screen flickering away behind the instructions, then both of these behind the first question etc..  The only way to sort the problem out is to reboot the machine.  Restarting the questionnaire doesn't work.

The questionnaires are run from a central script, which runs each questionnaire from its own script, in a random order - so all run through Coder.  

Prior to running these scripts I run a video in VLC - just something for the participant to watch while baseline readings are taken.  I also run a task in E-Prime.  In previous experiments I've used E-Prime prior to running PsychoPy, with no ill effects.  Could this be a problem between VLC and PsychoPy?

Thanks for any thoughts

Ralph

**Comment by jeremygray** [comment]
Its disturbing that its intermittent. If you don't run the video in VLC, does the issue go away?

**Comment by ralphp15** [comment]
Hi Jeremy - back in the lab now and I ran a couple of participants on Tuesday and with both of them PsychoPy failed to clear the screen properly, after VLC had previously been used.  For the third participant of the day I restarted the computer between the two stages and I had no problem.

It's definitely weird that it's intermittent.  I can't see anything that I'm doing differently between participants.  I open PsychoPy Coder, EPrime and VLC. Play the participant the video in VLC, close VLC, the participant does a task in E-Prime, I close E-Prime and run the PsychoPy script.

My labmate has recommended trying a video player called Media Player Classic, which I'll try in place of VLC (Windows Media Player gave back playback of my video file).  And I'll keep restarting the machine in the mean time.  

I'll be intrigued if this does turn out to be a VLC PsychoPy clash. I've been running EPrime and PsychoPy tasks together for a couple of years now, so I'm confident EPrime isn't the problem.

Thanks for your input :)

**Comment by peircej** [comment]
I'm afraid I have no idea what would cause this. It sounds like the computer is getting itself in a broken state, to be honest, but I've never seen such a thing before. I'm closing this as an issue for PsychoPy until we hear about it happening on another machine.
