### ISSUE TITLE
Q: controlling sound onset?

### ISSUE THREAD

**Issue by kingjr** [psychopy/psychopy#1081]
Hi all,

Is there a way to precisely control the onset of a sound? I'm looking for something like:

```
wav = sound.Sound('my_file.wav')
onset = time.now() + .100
wav.play(start=onset)
```

Thanks!

**Comment by kingjr** [comment]
Apparently this is not possible:
https://groups.google.com/forum/#!searchin/psychopy-users/onset$20sound/psychopy-users/ZPdusXWPB_A/qh6EtvyYSFIJ

**Comment by peircej** [comment]
Your question combines too things. One is whether psychopy allows a delayed onset and for that the answer is "no". You'd have to write the code yourself to check when the time has come for `wav` to `play()`
To the question of whether it can be precise, that is very much system-dependent. The thread you point to was started when the answer was "no" as well, but nowadays we have pyo which uses portaudio and depending on your system you can easily get 10-15ms precision and potentially down to <1ms precision (linux real-time kernel and good audio card).
In the end there is not a single answer. You definitely need to test on your own system what the latency is.

**Comment by kingjr** [comment]
Thanks; do you have a link to setup a 'real-time kernel' ?

**Comment by peircej** [comment]
No, only what google would provide you with
