### ISSUE TITLE
RatingScale not behaving as advertised, multiple labels

### ISSUE THREAD

**Issue by chucktheobald** [psychopy/psychopy#1082]
This does not work:
rating = visual.RatingScale(win=win, name='rating', marker=u'triangle', size=1.5, pos=[0.0, -0.4], low=5, high=9, labels=[u'a', u'b', u'c', u'd', u'e'], scale=u'')
The above results in a scale with end points labeled 5 and 9. If I provide only three labels, then the labels do get shown.
How can I have a rating scale responding to keys 5 through 9 (right button box key assignments) and labels at each tick mark?

**Comment by jeremygray** [comment]
answered on the email list
