### ISSUE TITLE
Low latency sound presentation with PyAudio

### ISSUE THREAD

**Issue by kingjr** [psychopy/psychopy#1093]
Hi all,

I encountered several difficulties to make pyo work on Ubuntu 14.04 and on old mac os, I've written this class to handle good sound timing without pygame or pyaudio.

https://gist.github.com/kingjr/65391fb1dd5cf2b4bee5

On my setup I get a jitter of 4-8 ms on average when using the following example.

```
import os.path as op
import time
import numpy as np
import matplotlib.pyplot as plt
from pyaudiosound import PyAudioSound

# Params
fname = op.join('sounds', 'test.wav')
delay = .200
n_sounds = 50
all_sounds = list()

# load multiple sounds
for ii in range(n_sounds):
    print ii
    sound = PyAudioSound(fname, chunk_size=2**15)
    all_sounds.append(sound)

# Define sound onsets
onsets = np.cumsum(np.ones(n_sounds)) * delay + time.time()
for sound, onset in zip(all_sounds, onsets):
    sound.play(onset=onset)

# wait until finished and plot summary metrics
time.sleep(.500)
print np.std([sound.stop_time_ - sound.start_time_ for sound in all_sounds])
starts = np.array([sound.start_time_ for sound in all_sounds])
starts -= starts[0]
plt.plot(onsets - onsets[0] - starts)
```

In case it help some..

**Comment by peircej** [comment]
We did support a pyaudio backend as well at one point. I found it too much to keep on top of the whole set of backends though

**Comment by jeremygray** [comment]
@kingjr Thanks for sharing. You might check out Jon's newest sound option (on github in psychopy/master, not yet released in a StandAlone version). It uses pysoundcard as a backend. Hopefully it too overcomes the issues you (and others!) were having with pyo.

**Comment by kingjr** [comment]
great, I'll give it a try; thanks for this great toolbox

**Comment by jeremygray** [comment]
I expect I'll be doing more work on sound-related classes, starting in a few weeks from now. We know that the pysoundcard code is not completely integrated yet, and I want to move a few things around to be more logically organized. So if you have observations or suggestions, or want to help out, this is a great time to get involved.

**Comment by kingjr** [comment]
Sure, I'll be watching the rep.

**Comment by peircej** [comment]
Jeremy, I won't be doing any more sound work for now. I've got other priorities. So feel free to refactor the sound backends into different files if you want
