### ISSUE TITLE
BUG: infinite wait depending on the import order of visual and gui

### ISSUE THREAD

**Issue by kingjr** [psychopy/psychopy#1100]
Hi,

On Mac OS X 10.6.8, `from psychopy import visual, gui` takes forever (i.e. it is stuck) whereas `from psychopy import gui, visual` is fine.

I don't get this issue on Ubuntu. I don't really know how to debug. Let me know if I can try something to dig and detail the issue.

**Comment by jeremygray** [comment]
Mac OS X 10.6.8 is quite ancient, and it does not seem worth the effort to fix the underlying problem (if its even possible to fix, which it might not). Its not a problem on more recent versions of Mac OS X.

In your code, where do you encounter the problem--and can you just import them in the order that does work?

**Comment by kingjr** [comment]
It works fine when gui is imported before visual. I'll close the issue.
