### ISSUE TITLE
iohub keyboard events show 3-15ms lag

### ISSUE THREAD

**Issue by onesandzeroes** [psychopy/psychopy#1104]
This was mentioned on the mailing list [here](https://groups.google.com/forum/#!topic/psychopy-users/0B14e8MsQWg) but is probably worth posting as an issue. We recently got our hands on a BBTK testing kit and USB response pad and were able to test out the timing characteristics of Psychopy on our hardware. 

Stimulus onset was recorded using a photodiode and the USB response pad sends a TTL signal to the BBTK testing kit when a button press occurs. We saw millisecond-level accuracy from `psychopy.event` which is great, but when using `iohub`'s event processing functions there were consistent lags of anywhere from 3 to 15ms, e.g.:

```
using waitforkeys(), lag in milliseconds:
12.2
12.9
4.3
7.5
13.0
6.4
13.6
5.2
7.9
8.7
```

```
using getpresses():
6.2
4.7
13.3
10.7
14.6
4.4
9.1
3.7
7.3
7.0
```

This is on Windows 7, using v183.03 of the Psychopy standalone application. I can track down the hardware specs of the machine we tested on shortly. Since we still have access to the BBTK kit I can try to run some further tests if there is anything specific that people want to investigate.

**Comment by peircej** [comment]
This is fixed in fc47fd2495b8f1 so will be release 1.84.0
