### ISSUE TITLE
sound.py:  maximum recursion depth exceeded

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#1108]
Have you seen this one ?
```
> cd build \
	&& USER=nobody TRAVIS=true \
	xvfb-run -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" \
	python ../psychopy/tests/runPytest.py --tb=line -s -m "not needs_sound" || { echo "TESTS FAILED"; :; }
============================= test session starts ==============================
platform linux2 -- Python 2.7.10 -- pytest-2.2.3
....
=================================== FAILURES ===================================
/home/yoh/deb/gits/pkg-exppsy/build-area/psychopy-1.83.04.dfsg/build/lib.linux-x86_64-2.7/psychopy/tests/test_app/test_builder/test_Experiment.py:251: assert not '@@ -1,7 +1,7 @@\n #!/usr/bin/env python2\n # -*- coding: utf-8 -*-\n """\n-This experiment was created using PsychoPy...\n     pos=[0, 0], height=0.1, wrapWidth=None,\n     color=\'gray\', colorSpace=\'rgb\', opacity=1,\n     depth=0.0)\n'
/home/yoh/deb/gits/pkg-exppsy/build-area/psychopy-1.83.04.dfsg/build/lib.linux-x86_64-2.7/psychopy/sound.py:645: RuntimeError: maximum recursion depth exceeded while calling a Python object
================ 12 tests deselected by "-m 'not needs_sound'" =================
====== 2 failed, 288 passed, 39 skipped, 12 deselected in 389.13 seconds =======
t booted.
```

**Comment by yarikoptic** [comment]
happens in 1.83.04
```
(git)hopa:~exppsy/psychopy[tags/1.83.04^0]git
$> python psychopy/tests/runPytest.py --tb=line -x psychopy/tests/test_app/test_builder/test_Experiment.py
======================================================================== test session starts =========================================================================
platform linux2 -- Python 2.7.10 -- pytest-2.2.3
collected 9 items 

psychopy/tests/test_app/test_builder/test_Experiment.py ..F

============================================================================== FAILURES ==============================================================================
/home/yoh/deb/gits/pkg-exppsy/psychopy/psychopy/tests/test_app/test_builder/test_Experiment.py:251: assert not '@@ -1,7 +1,7 @@\n #!/usr/bin/env python2\n # -*- coding: utf-8 -*-\n """\n-This experiment was created using PsychoPy...\n     pos=[0, 0], height=0.1, wrapWidth=None,\n     color=\'gray\', colorSpace=\'rgb\', opacity=1,\n     depth=0.0)\n'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================= 1 failed, 2 passed in 3.67 seconds =================================================================
D: KILLING THE APP
python psychopy/tests/runPytest.py --tb=line -x   5.50s user 0.60s system 103% cpu 5.875 total
```
but hangs after a while in master (at cpu busy but nothing progressing etc)
```
(git)hopa:~exppsy/psychopy[master]git
$> python psychopy/tests/runPytest.py --tb=line -x psychopy/tests/test_app/test_builder/test_Experiment.py
======================================================================== test session starts =========================================================================
platform linux2 -- Python 2.7.10 -- pytest-2.2.3
collected 9 items 

psychopy/tests/test_app/test_builder/test_Experiment.py ....
```

**Comment by yarikoptic** [comment]
ok -- in master hangs on `psychopy/tests/test_app/test_builder/test_Experiment.py:273: TestExpt.test_loopBlocks ` while in 1.83.04 happens in another test: `psychopy/tests/test_app/test_builder/test_Experiment.py:197: TestExpt.test_Exp_LoadCompilePsyexp FAILED` so that hanging is a different issue which seems was addressed in master... commit hexsha? ;)

**Comment by peircej** [comment]
Not sure what this is about. Will have to wait until Monday when I can get back to my ubuntu box. 
Master is passing on Travis though so seems not universal to linux

Oh and apparently, although lxml is no longer needed for the app it turns out it is still used in the test suite - I'll have to weed that out another day.

**Comment by peircej** [comment]
For me master and r1.83 branches both pass on ubuntu 14.04 with the 
usual warnings about AL lib
Jon

    PLPCuckoo (master) git$ python psychopy/tests/runPytest.py --tb=line
    -x psychopy/tests/test_app/test_builder/test_Experiment.py

    (python:1316): Gtk-WARNING **: Unable to locate theme engine in
    module_path: "pixmap",
    ============================= test session starts
    ==============================
    platform linux2 -- Python 2.7.6 -- pytest-2.2.3
    collected 9 items

    psychopy/tests/test_app/test_builder/test_Experiment.py .....s...

    ===================== 8 passed, 1 skipped in 9.48 seconds
    ======================
    D: KILLING THE APP
    AL lib: ReleaseALC: 1 device not closed






This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by yarikoptic** [comment]
On Mon, 15 Feb 2016, Jon Peirce wrote:

>    For me master and r1.83 branches both pass on ubuntu 14.04 with the
>    usual warnings about AL lib

14.04 is something released almost 2 years ago, from libraries
uploaded to debian even before then.  I was testing on current state of
Debian sid, whatever ubuntu 16.04 would become I guess

you can easily deploy debian sid in a variety of ways, from chroot to
docker to full VM... I can give you instructions if you like.

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by peircej** [comment]
On 15/02/2016 14:26, Yaroslav Halchenko wrote:
>
> On Mon, 15 Feb 2016, Jon Peirce wrote:
>
> > For me master and r1.83 branches both pass on ubuntu 14.04 with the
> > usual warnings about AL lib
>
> 14.04 is something released almost 2 years ago, from libraries
> uploaded to debian even before then. I was testing on current state of
> Debian sid, whatever ubuntu 16.04 would become I guess
>
> you can easily deploy debian sid in a variety of ways, from chroot to
> docker to full VM... I can give you instructions if you like.
I'll try and get around to an additional install. Is there a VM that 
gives me access to a full OpenGL suite? Last I knew the OpenGL support 
in free VMs was pretty limited and made it pointless for testing.

For now though 14.04 looks like the most important thing to support. I'm 
only interested in working out issues with LTS releases and 14.04 is the 
current LTS.

If other people want to find fixes for other systems that's fine too! ;-)

cheers
Jon

**Comment by yarikoptic** [comment]
On Mon, 15 Feb 2016, Jon Peirce wrote:

>    On 15/02/2016 14:26, Yaroslav Halchenko wrote:

>    > On Mon, 15 Feb 2016, Jon Peirce wrote:

>    > > For me master and r1.83 branches both pass on ubuntu 14.04 with the
>    > > usual warnings about AL lib

>    > 14.04 is something released almost 2 years ago, from libraries
>    > uploaded to debian even before then. I was testing on current state of
>    > Debian sid, whatever ubuntu 16.04 would become I guess

>    > you can easily deploy debian sid in a variety of ways, from chroot to
>    > docker to full VM... I can give you instructions if you like.
>    I'll try and get around to an additional install. Is there a VM that
>    gives me access to a full OpenGL suite? Last I knew the OpenGL support
>    in free VMs was pretty limited and made it pointless for testing.

if you have physical access to 14.04 box, you can easily install debian
sid there within chroot and it should  have access to all of your X.
Could you try (copy/pasting from
http://neuro.debian.net/blog/2011/2011-12-12_schroot_fslview.html
changing squeeze into sid ;) and trying it out):

    sudo apt-get install debootstrap schroot
    sudo debootstrap --include=psychopy sid /srv/chroots/sid http://http.debian.net/debian
    # above so we install all regular dependencies etc for psychopy, it will
    # take a while
    echo -e "[sid-psychopy]\ntype=directory\ndirectory=/srv/chroots/sid\nusers=$USER\nroot-users=$USER\n" | sudo bash -c 'cat - >| /etc/schroot/chroot.d/sid-psychopy' 

    # and lets' remove preinstalled version just in case
    schroot -u root -c sid-psychopy -- dpkg --purge psychopy      

    # and install some additional build-dependencies which were not needed
    # for the version before I guess, but also just to give you more complete env
    schroot -u root -c sid-psychopy -- apt-get install python-wxgtk3.0 python-qt4 python-pandas xvfb mesa-utils libgl1-mesa-dri python-pyo

now you are pretty much all set to run that test to reproduce the failure.
Just enter that environment for your interactive pleasure while already within
your git repo for psychopy

    schroot -c sid-psychopy -p

and within there run the failing test -- now failure is different due to too
flashy/new numpy:

    hopa(sid-psychopy):~/deb/gits/pkg-exppsy/psychopy
    $> LC_ALL=C.UTF-8 python psychopy/tests/runPytest.py --tb=line -x psychopy/tests/test_app/test_builder/test_Experiment.py
    Gtk-Message: Failed to load module "gail"
    Gtk-Message: Failed to load module "atk-bridge"
    Gtk-Message: Failed to load module "canberra-gtk-module"
    ================================================================================= test session starts =================================================================================
    platform linux2 -- Python 2.7.11 -- pytest-2.2.3
    collected 9 items 

    psychopy/tests/test_app/test_builder/test_Experiment.py ....F

    ====================================================================================== FAILURES =======================================================================================
    /usr/lib/python2.7/dist-packages/numpy/ma/core.py:3242: IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ========================================================================= 1 failed, 4 passed in 1.61 seconds ==========================================================================
    pyo version 0.7.8 (uses single precision)
    D: KILLING THE APP


heh -- what a life ;)


>    For now though 14.04 looks like the most important thing to support. I'm
>    only interested in working out issues with LTS releases and 14.04 is the
>    current LTS.

as the party said? and/or supported by whom? ;) 

Debian jessie is probably the one which will get proper LTS for a while,
so why not to try also that one? ;)

>    If other people want to find fixes for other systems that's fine too! ;-)

gy, sure thing

here question is though not about LTS but seems to be about
incompatibility with a recent release of underlying libraries.

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by peircej** [comment]
OK. Yes the physical 14.04 machine is in my office. I'll try an do that 
setup when I get a chance (not in the next 2 weeks I think).

>
> > For now though 14.04 looks like the most important thing to support. I'm
> > only interested in working out issues with LTS releases and 14.04 is the
> > current LTS.
>
> as the party said? and/or supported by whom? ;)
>
> Debian jessie is probably the one which will get proper LTS for a while,
> so why not to try also that one? ;)

OK, let me put it another way. Most of our linux users are on ubuntu.
Most of them will be on 14.04. That's the priority linux system for me.


-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by yarikoptic** [comment]
on a rebuild today I didn't run into the infinite recursion issue... may be it was due to some dependencies. I will close it for now, but instructions above on schroot could help us in the future to react fast ;)
