### ISSUE TITLE
test_Exp_LoadCompilePsyexp - picks up old demos and replaces newlines?

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#1112]
with 1.83.04

as originally reported in #1108 but a separate issue probably -- what could lead to such a diff while running test_Exp_LoadCompilePsyexp  -- seems to be picking up some other psychopy (I don't have 1.81.03 installed afaik) or smth... and all the newlines conversions..

```
-This experiment was created using PsychoPy2 Experiment Builder (v1.81.03), Tue 16 Feb 2016 08:22:17 AM EST
+This experiment was created using PsychoPy2 Experiment Builder (v1.83.04), Tue 16 Feb 2016 08:22:17 AM EST
 If you publish work using this script please cite the relevant PsychoPy publications
...
 Instr_7Clock = core.Clock()
 Instr7 = visual.TextStim(win=win, ori=0, name='Instr7',
-    text='Sort the same four categories again. The same rules still apply.\r\n\r\nPress the spacebar to begin the next set of trials.',    font='Arial',
+    text='Sort the same four categories again. The same rules still apply. \n \nPress the spacebar to begin the next set of trials.',    font='Arial',
     pos=[0, 0], height=0.08, wrapWidth=1.2,
     color='white', colorSpace='rgb', opacity=1,
     depth=0.0)
@@ -540,7 +540,7 @@
 # Initialize components for Routine "thanks"
 thanksClock = core.Clock()
 Thanks = visual.TextStim(win=win, ori=0, name='Thanks',
-    text='End of this part.\r\n\r\nPress space to end.',    font='Arial',
+    text='End of this part. \n \nPress space to end.',    font='Arial',
     pos=[0, 0], height=0.1, wrapWidth=None,
```

**Comment by jeremygray** [comment]
I have been having similar (weird) newline conversions the last few days. It was in a temp file that I was using to keep track of other files, and so I didn't pay it much mind. No idea where it was coming from.

**Comment by peircej** [comment]
This one looks like an overzealous file compare. The diffs here are expected with new->old file comparisons but are irrelevant. 
There's a function to try and identify what diffs between builder-generated python scripts we should worry about and these look like changes to be added (although I don't have any idea why they'd show up in Yaroslav's test set up and not ours!).
