### ISSUE TITLE
Nonsensical column added to data output on early termination

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#1115]
In a Builder experiment with nested loops, terminating the experiment early via the `escape` key results in a nonsensical column being inserted into the .csv data output file. 
e.g. if the outer loop is named `trials_2`, then following early termination, a column will be added after the `trials_2.thisIndex` column, labelled `trials_2.thisTrial`, with cell values of `None`. i.e. it seems that the entire `thisTrial` object is being passed to be saved in the data in this situation. This makes data files following early termination have one extra column than data files from regular sessions.

**Comment by jeremygray** [comment]
`._getLoopInfo()` has a couple lines that appear to be responsible. If I comment them out I don't see the odd columns when ending early via `escape`.

```
            else:
                names.append(name + '.thisTrial')
                vals.append(trial)
```

At first glance, the data output seems normal when NOT using escape. Important to test more carefully (!).

**Comment by peircej** [comment]
I don't recall the point of that code. Maybe it's a pure unnecessary piece!
