### ISSUE TITLE
Nested loops in Builder add partially blank lines to the data output

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#1116]
If a Builder experiment is set to loop twice over a conditions file of 5 rows, then the resulting .CSV file would have 10 contiguous data rows, as expected.

Adding additional enclosing loops, however, breaks this one-row-per-trial structure of the data file. e.g. see this attached file: 
[test_2016_Feb_17_1346.xlsx](https://github.com/psychopy/psychopy/files/133502/test_2016_Feb_17_1346.xlsx)

Note that the first ten rows, controlled by the inner loop (2 reps of 5 rows)  appear contiguously as expected.  But before the next block of ten rows, an intervening row is inserted that doesn't correspond to an actual trial (no information from the conditions file appears in this row. It does contain index columns (.thisN, .thisIndex, etc) that relate to the second and third (middle and outer loops).

After the next block of trials, there are actually two partially incomplete lines, contributed by the second and third nested loops respectively.

That is, on the completion of any loop, its data is appended by a partially blank, non-trial-related line contributed by its immediately enclosing loop. So the number of partially blank lines will cycle from 1, to 2, to 3, etc and back again. 

This will break many analysis pipelines, as these additional lines break the consistent data structure without contributing any useful information.

**Comment by jeremygray** [comment]
Nice detective work! I made a test exp with 3 loops. The generated code has this:

```
            # ... routine code here ...
            thisExp.nextEntry()
        # completed 1 repeats of 'trials'
        thisExp.nextEntry()
    # completed 2 repeats of 'trials_2'
    thisExp.nextEntry()
# completed 5 repeats of 'trials_3'
```

I think that a possible way to fix the behavior would be inside .nextEntry: check and do nothing if no data have been added since the last call to .nextEntry.

**Comment by jeremygray** [comment]
Adding this at the top of the nextEntry() method fixes the behavior:
```
    if not self.thisEntry:
        return
```
Are there any bad side effects this could have?

**Comment by m-macaskill** [comment]
Nice: one looks like a great catch and simple fix. 
Plus I just learned for the first time that `not {}` or `not []` returns `True`.  

Now I'm wondering if this will also fix https://github.com/psychopy/psychopy/issues/1115 ...

**Comment by jeremygray** [comment]
I still get the odd column (so it does not fix #1115).

**Comment by peircej** [comment]
I don't think we should add code that skips nextEntry() if no data has been added. We could have a valid trial where there was simply no data collected? I think we should leave it to the user to determine explicitly what they want to be treated as a row/entry/trial

**Comment by jeremygray** [comment]
Hmmm, the "Is trials" check box is not something I understand, maybe that can help here?

**Comment by m-macaskill** [comment]
Probably best we close this issue, as it seems it isn't really a bug at all, and skipping nextEntry() in some situations could be confusing as opposed to telling users to simply de-select "is trials" for that loop.

Sorry for the false alarm. Agree to close?

**Comment by jeremygray** [comment]
Sure

--Jeremy

On Wed, Feb 17, 2016 at 6:39 PM, Michael MacAskill <notifications@github.com
