### ISSUE TITLE
First call to core.wait() can be unreliable

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#1117]
When making multiple calls to `core.wait()`, the first call reliably runs longer than intended. For example:

```
from psychopy import core

timer = core.Clock()
t_list = []

for i in range(5): # or any much larger number
    timer.reset()
    core.wait(0.1)
    t = timer.getTime()
    t_list.append(t)
    
print(t_list)
```
This produces output typically like this:

[0.30477309226989746, 0.10000896453857422, 0.10001206398010254, 0.10001111030578613, 0.10000896453857422]

On my computer, the first duration is reliably ~ 300 ms until the nominal wait period itself exceeds 300 ms, whereupon the first duration becomes approximately the sought duration + 120 ms. Subsequent durations appear accurate to about 4 decimal places.

In the source code for `core.wait()`, the first line is `import core`. This is due to `wait()` actually being in `clock.py`, so there is actually some circular importing going on to get `wait()` into the `core` namespace.

The above import could explain the one-off nature of the delay. BUT changing the code above to `core.wait(0.1, hogCPUperiod=0)` normalises the first duration markedly, at the cost of making the subsequent durations no longer quite as accurate:

[0.10128092765808105, 0.10014700889587402, 0.10367798805236816, 0.10396695137023926, 0.10286688804626465]

It is unclear how this would mitigate the effects of the import statement. Note that non-zero hogCPUperiod values don't fix the first duration but still make subsequent ones very slightly worse (accurate to 2-3 decimal places). e.g. with hogCPUperiod=0.05:

[0.36731696128845215, 0.10068988800048828, 0.1010739803314209, 0.10039401054382324, 0.10106611251831055]

Since the API and documents all refer to `core.wait()` rather than `clock.wait()`, perhaps it would be best if this function was simply moved to `core.py`. But at this stage I'm not sure that the import within the `wait()` function is the cause of the problem...

**Comment by peircej** [comment]
Turns out was not a problem with core/clock importing. It was the (first) call to pyglet get_windows() taking time if (and only if) a window hadn't yet been created. We can get around that by tracking the windows ourselves more efficiently (we're already doing that - just needed to be used here too)
