### ISSUE TITLE
Blurry text rendering in Coder view on high resolution displays

### ISSUE THREAD

**Issue by papr** [psychopy/psychopy#1118]
I am using a Macbook Pro with a Retina display. The Coder view does not render the source code sharply. This follows most likely from not checking if the view draws onto a HDPI display. I attached a screenshot and a selection of it as prove/example.

Thanks for your hard work! It is appreciated. <3

<img width="1357" alt="screenshot 2016-02-17 16 17 29" src="https://cloud.githubusercontent.com/assets/168390/13114138/7752c148-d592-11e5-9622-e9f1180c3626.png">
<img width="183" alt="screenshot 2016-02-17 16 17 29-clip" src="https://cloud.githubusercontent.com/assets/168390/13114201/c105ef9a-d592-11e5-813c-711d87156464.png">

**Comment by jeremygray** [comment]
Yeah, I too have a retina display and know exactly what you mean. If you can figure out how to systematically check whether the display is retina type, and then how to tell wx (v3.0+) to render text using that high-res option, I'll have a go at tweaking the PsychoPy code.

**Comment by papr** [comment]
It sounds like you are using a default wx text view? If so the text view should be responsible for drawing sharp text. Therefore this issue would not belong here but on the wx bug report page...

**Comment by m-macaskill** [comment]
Rendering of interface elements in Builder and Coder on retina displays has improved progressively over recent releases, but text rendering does remain strikingly low-quality, which will be turning off potential new users.
For me, the issue also affects rendering of stimuli within the experiment window itself, which is even more  serious.

**Comment by jeremygray** [comment]
I use the Coder window for quick small things, and use PyCharm for longer code.

For the visual display in the window, this patch for pyglet looks promising: https://bitbucket.org/pyglet/pyglet/commits/c6c387c. I see a crisper display, but the scale is off and things are not centered. So will need more work.

**Comment by peircej** [comment]
I do think this is a wxPython issue more than ours probably. It should detect the retina display and adjust accordingly. My sense was that some aspects of it are doing so already. The pyglet code Jeremy points to looks interesting from our stimulus-rendering point of view though!

**Comment by m-macaskill** [comment]
Resolved by https://github.com/psychopy/psychopy/commit/07e64720d09cd61f43caee5fe567f8f57b3a798a
