### ISSUE TITLE
is app/coder/debugger.py abandoned? 

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1124]
I think writing a full-feature code editor is beyond scope for PsychoPy. Important to have code editing & running, but debugging not so much.

Comment at top of file:

    # it doesn't work - it was too hard and will need too many hours to get right!

Remove the file from master branch? It seems neglected.

**Comment by jeremygray** [comment]
More stats: the file history looks like nothing of substance has happened since before 2009, and I can't find any references in the wider codebase to debugger.py

**Comment by peircej** [comment]
Can delete for now. Might revisit another day :-)

On 26/02/16 12:29, Jeremy R. Gray wrote:
>
> I think writing a full-feature code editor is beyond scope for 
> PsychoPy. Important to have code editing & running.
>
> Comment at top of file:
>
> |# it doesn't work - it was too hard and will need too many hours to 
> get right! |
>
> Remove the file from master branch? It seems neglected.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1124>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
