### ISSUE TITLE
Builder: variable naming collisions not apparent to novice user

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1132]
Hello!

I tried building a test experiment through the builder, and imported a conditions file that has a column named "image". When I added an Image stimulus by clicking on one in the Components, and left the default name as "image" and set the image as $image, this generated a python error: 

`Traceback (most recent call last):
  File "/home/daniel/ownCloud/phdExperiments/maskedVocabTraining/vocabTraining-builder_lastrun.py", line 109, in <module>
    image.setImage(image)
AttributeError: 'unicode' object has no attribute 'setImage'`

The problem was that the stimulus's variable name is "image", and also the variable used in the conditions spreadsheet is "image", so I inadvertently created a naming collision. I was able to quickly figure this out because I program, but I'm posting this here as a bug because to someone who has no programming background this would be a meaningless and intimidating error message, which could give them a negative impression of your wonderful software. I've included a snapshot of the dialogue to hopefully make what I'm saying clearer.
![screenshot from 2016-03-07 14 52 20](https://cloud.githubusercontent.com/assets/10103957/13581338/5b615b5c-e474-11e5-9f3a-3aa118b4b84a.png)

I suggest that a simple way to avoid this could be that when adding a stimulus from the builder's  dialogues, that if the user tries to click OK and the name of the stimulus and the image (or the Text, for a text stimulus) will be the same, that a clear error or warning be generated, saying something like "The fields for Name and Image cannot have the same value". Just a thought.

Thank you for the great software. I do hope you consider this, it seems like an easily implemented improvement to the user experience.  Take care,

**Comment by jeremygray** [comment]
Good catch. I agree this should be fixed. The Builder does try to keep track of what the namespace will be when the program is converted into python code, including some inspection of the headers in conditions files when they are linked. But there are some holes in this process, as you discovered. If you wouldn't mind poking around a bit more to try to find other holes, that would be useful. Thanks for reporting this.

**Comment by dantheman39** [comment]
Thanks Jeremy, I'll certainly keep my eyes open, and if I find anything that I think will help, I'll try to respectfully point it out. Thanks again.

**Comment by dantheman39** [comment]
Sorry, one more note, I made the exact same mistake with the Text component, so the same issue applies there.

**Comment by jeremygray** [comment]
This should be fixed now in 30ee241, for all similar cases.
