### ISSUE TITLE
Psychopy icon is pixelated in Ubuntu, fix suggested

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1133]
Hello! Sorry if this is a bit nit-picky, but it's been bugging me for a while. The icon for psychopy in Ubuntu is 32x32 pixels (installed in /usr/share/pixmaps/psychopy.xpm), so it looks pretty terrible whenever I open the application. I believe this can be fixed very easily.

**Quick fix**: 

Use the 256x256 psychopy.png file already in the Mac package instead. This size happens to be the required size for apps in Ubuntu's store, so I suppose it's some type of standard.

It's in (github path) psychopy/psychopy/apps/Resources/psychopy.png. We could install this file in /usr/share/pixmaps/ instead of the psychopy.xpm.

Change the last line of the .desktop file that tells the system about the application (/usr/share/applications/psychopy.desktop):

Now it's:

`Icon=/usr/share/pixmaps/psychopy.xpm`

Could be:
`Icon=psychopy.png`

That's it! 

The relative path works because /usr/share/pixmaps is one of the places the system searches for icons (Reference: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html). I tested this on Ubuntu Unity (14.04), and on the XFCE desktop. Note that the system automatically scales it down to a smaller size for the menu in XFCE, (which is something I was worried about), so it works fine. The info in the link above also leads me to believe it should work on KDE as well (see the section **Installing Application Icons**).

There are other slightly more involved ways of bringing this more up to standard, such as including the icon in several sizes (but not in the pixmaps folder). Check out the link for some more info if you're interested.

Hopefully you wouldn't mind making this simple change to the Debian/Ubuntu package! Take care, hope you are all doing well.

**Comment by peircej** [comment]
Hi Dan, I agree that things with easy fixes that make the world nicer should be fixed! ;-)

@yarikoptic manages the packaging of the (neuro)debian release. Maybe he can implement this so it looks nicer in future (assuming that the ubuntu and debian treatment of icons is the same)

**Comment by peircej** [comment]
@yarikoptic did this get done? Can I close the issue? (Am currently building 1.84.0 and checking for important and/or easy fixes first)

**Comment by yarikoptic** [comment]
cool, thanks -- https://github.com/neurodebian/psychopy/commit/18a915fcc52d57456a453f9497c13f49ca098e66 will come with the next upload (probably with the next release).

**Comment by peircej** [comment]
cheers buddy
