### ISSUE TITLE
ColorCal 2 fails to connect

### ISSUE THREAD

**Issue by brittAnderson** [psychopy/psychopy#1138]
Setting up a new machine today I could not get the ColorCal2 to connect properly for gamma correction. The error message related to an inability to find a baud rate. From a google search found a similar error that related to version 3 of Pyserial having changed their "interface". Downgraded to pyserial2.7 and was able to connect. My guess is the pyserial library changed something about their interface. Might be best to recommend pyserial less than 3.0.

Ref: https://stackoverflow.com/questions/34602168/dronekit-failed-to-connect-to-dev-tty-usbmodem1411-serial-object-has-no-at/34615374#34615374

**Comment by peircej** [comment]
Thanks for the heads-up Britt. Probably we should change our code to be 
compatible with the new version:
   https://github.com/mavlink/mavlink/issues/498

On 14/03/2016 23:01, brittAnderson wrote:
>
> Setting up a new machine today I could not get the ColorCal2 to 
> connect properly for gamma correction. The error message related to an 
> inability to find a baud rate. From a google search found a similar 
> error that related to version 3 of Pyserial having changed their 
> "interface". Downgraded to pyserial2.7 and was able to connect. My 
> guess is the pyserial library changed something about their interface. 
> Might be best to recommend pyserial less than 3.0.
>
> Ref: 
> https://stackoverflow.com/questions/34602168/dronekit-failed-to-connect-to-dev-tty-usbmodem1411-serial-object-has-no-at/34615374#34615374
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1138>.
>

-- 
Jon Peirce
http://www.peirce.org.uk
