### ISSUE TITLE
Error message in PsychoP

### ISSUE THREAD

**Issue by dmontoya16** [psychopy/psychopy#1140]
Hello; I'm receiving this message after running every new experiment:

Incompatible library version: _pyo.so requires version 10.0.0 or later, but liblo.7.dylib provides version 9.0.0

I have the latest version installed (V1.83.04) in a Mac laptop.

Any suggestions?
Thanks in advance

**Comment by peircej** [comment]
This is a problem I've been having getting pyo to compile in the 64bit version well enough to run on all machines. The workaround is to download an earlier version of the app (before it went 64bit) and then upgrade it using the zip file download
