### ISSUE TITLE
Download source code for 1.79.01?

### ISSUE THREAD

**Issue by lholsen** [psychopy/psychopy#1142]
Hello,

We currently have PsychoPy v1.79.01 installed on a macbook pro (OS X.10.5), where it is running fine. Now I need to install and run it from a different macbook (same OS). I had planned to just download v1.79.01 on the new laptop, and go from there. However, I am unable to find it listed under Releases. It skips from v1.79.00 to 1.80.00. Can anyone direct me  as to how to obtain the source code (.zip) for 1.79.01?

Thank you!

Laura

**Comment by jeremygray** [comment]
PsychoPy has a feature called useVersion() that might be of interest to you. It will automatically download if necessary and switch to using the specified version.
