### ISSUE TITLE
"continueRoutine = True" in Builder generated code should occur earlier

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#1143]
To have conditional execution of a routine (e.g. a rest break every 10th trial), a code snippet like this is often suggested:

    if not loopName.thisN in [9, 19, 29]:
        continueRoutine = False

It would be logical if such code was placed in the "Begin routine" tab of a code component. But this is executed immediately prior to a routine:

    #-------Start Routine "trial"-------
    continueRoutine = True

So a change affecting `continueRoutine` in the "begin routine" tab is immediately counteracted by the template code. 

Should the above line in the compiled code be shifted to *before* where  any "begin routine" code is placed? Otherwise any attempt to end a routine has to occur in the "Every frame" tab. 

Needing to always put `continueRoutine` code in the "Every frame" tab has two disadvantages:
- Probably one frame of a routine will be presented before it can then be terminated. This could cause a visible flicker in stimuli, or some other undesired action.
- It encourages inappropriate mixing of logic, and needlessly performing a single check multiple times. That is, some `continueRoutine` checks should be evaluated only once, prior to a routine (e.g. checking a trial number), while other `continueRoutine` checks should be monitored continuously, on every frame. We should allow hose checks to be placed where they should be, logically and performance-wise.

**Comment by peircej** [comment]
Good idea Mike. I went ahead and did it

**Comment by m-macaskill** [comment]
Cheers. Wasn't sure if it would cause other issues. Great that it was so simple.
