### ISSUE TITLE
Missing conditions.pkl file for RatingScales demo

### ISSUE THREAD

**Issue by rachhaney** [psychopy/psychopy#1149]
Hello,

I downloaded PsychoPy 1.83.04 today and tried to run the builder demo for RatingScales and keep encountering an error, in which I think the conditions.pkl file was not included in the PsychoPy standalone download. Is this correct? Is there a way for me to obtain this file?

Thank you,
Rachel

![ratingscaleerror](https://cloud.githubusercontent.com/assets/18154696/14128006/8ef21ed4-f5d1-11e5-9e98-5180d1b106f1.png)

**Comment by jeremygray** [comment]
The conditions.pkl file can downloaded from here https://github.com/psychopy/psychopy/tree/master/psychopy/demos/builder/ratingScales I am not sure why it would not be included in the StandAlone version.

**Comment by rachhaney** [comment]
Got it, thanks for your help Jeremy!
