### ISSUE TITLE
Dlg.display() and API docs

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1150]
Hello! I'm wondering if the docs are up to date on this ( http://www.psychopy.org/api/gui.html )

That page led me to believe that I should be calling .display() instead of .show(), but I'm getting an error saying that the object has no attribute display. To quickly replicate via the python shell.

`\>>>from psychopy import gui

\>>>dlg = gui.Dlg(title="I'm a dialogue")
\>>>dlg = addText("Hey there")
\>>>dlg.display()
Traceback (most recent call last):
    File "\<stdin>", line 1, in \<module>
AttributeError: 'Dlg' object has no attribute 'display'
\>>>dlg.show()
\>>>
`

dlg.show() works fine. Hopefully I haven't made a silly error here. I'm using psychopy version 1.83.04. Take care,

**Comment by jeremygray** [comment]
It looks like the docs are showing information about `qtgui.py`, and your code is using `wxgui.py` (probably because your version of PsychoPy does not have either PyQt4 or PyQt5 installed).

**Comment by dantheman39** [comment]
I'm using Ubuntu 14.04, and have installed from the psychopy repo (sorry, should have posted that earlier), so I import psychopy just like any other python library (I'm coding the experiment myself in a text editor and running from the command line). I actually already have a working PyQt4 install on my system. I'm not sure if in this case using wxgui.py is expected behavior.

**Comment by jeremygray** [comment]
It might be installed but not found. You can do this to see if it is finding PyQt or not:

```
>>> from psychopy import gui
>>> gui.haveQt
```

.display() should work with Qt but not with wx. I am not sure why the API is different, would be nice to have it consistent.

**Comment by dantheman39** [comment]
This is odd. I get an AttributeError;

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'haveQt'

dir(gui) Shows this:

['Dlg', 'DlgFromDict', 'OK', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'ensureWxApp', 'fileOpenDlg', 'fileSaveDlg', 'localization', 'logging', 'numpy', 'os', 'string', 'wx']

If I actually type the first lines of psychopy/gui/.__init__py into the console...

```python
from __future__ import absolute_import
 
 try:
     import PyQt4
     haveQt = True
 except ImportError:
     try:
         import PyQt5
         haveQt = True
     except ImportError:
         haveQt = False
```

... haveQt is True.

**Comment by peircej** [comment]
Are  you /sure/ you're using the version of psychopy you installed from 
the repository then (and if so when did you install it from there)? 
Maybe you have multiple versions installed?
Try doing:
     import psychopy
     print psychopy
to check the path of the one that's being imported.

**Comment by dantheman39** [comment]
Pretty sure, I've only installed once, and install updates as they become available (pretty standard use of apt-get package manager). This is the source in my /etc/apt/sources.list :

deb http://neuro.debian.net/debian trusty main contrib non-free
deb-src http://neuro.debian.net/debian trusty main contrib non-free

Here's where psychopy and PyQt4 are run from, both standard, I believe.
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psychopy
>>> print psychopy
<module 'psychopy' from '/usr/lib/python2.7/dist-packages/psychopy/__init__.pyc'>
>>> import PyQt4
>>> print PyQt4
<module 'PyQt4' from '/usr/lib/python2.7/dist-packages/PyQt4/__init__.pyc'>
>>> 
```

Very strange!

**Comment by dantheman39** [comment]
Hopefully the issue with my installation not loading qt  is simply local to my computer, and as of yet hasn't seemed to cause any trouble.

The main issue here I think would be that, as Jeremy has pointed out, the API for wx and qt should either be the same, or the difference should be noted in the docs.
