### ISSUE TITLE
problems with csv. data

### ISSUE THREAD

**Issue by GiovannaLicea** [psychopy/psychopy#1156]
Hi!
I update my computer to windows 10, since then I am having problems to see my csv data, they are really messy, and Im wondering how i can fix this to see my csv data in the proper way.

**Comment by peircej** [comment]
There's no way we can help you with that level of information. Sorry. Please write to the mailing list but with further info (e.g. an example csv file)

**Comment by mmagnuski** [comment]
just guessing: Windows does not see `\n` as line breaks so if you are trying to open a csv file in notepad you will see mess most likely. Try opening in a decent text editor like sublime text and see if it works...
