### ISSUE TITLE
PsychoPy quits unexpectedly when removing experiment info options

### ISSUE THREAD

**Issue by OliJimbo** [psychopy/psychopy#1157]
This is on Mac OSX El Cap Standalone version - when I open Experiment Settings from builder and click the minus sign to remove an experiment info form PsychoPy quits unexpectedly.  This occurs even when the form is blank (i.e. adding one and then removing it).  No error messages - quite interested to see if this can be replicated.
Oli

**Comment by jeremygray** [comment]
This is the same as issue #827, closing this one.
