### ISSUE TITLE
Problem with "native gamma"

### ISSUE THREAD

**Issue by MilosUroboros** [psychopy/psychopy#1158]
Hi all,

Would anyone help me with this problem?  Thank you in advance.

Best,
Milos
![img_20160423_163138](https://cloud.githubusercontent.com/assets/18632248/14762542/222e7512-097d-11e6-93c4-bc19ee34cdda.jpg)

**Comment by peircej** [comment]
This is the pyglet "unable to share contexts" issue that has been discussed in several threads. e.g. https://groups.google.com/forum/#!topic/psychopy-users/pED3e4YiWoE
