### ISSUE TITLE
Subclassing visual stimuli no longer works

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#1159]
See user group thread here:
https://groups.google.com/forum/#!topic/psychopy-users/60pt6b9Y3do

Basically the new mixin classes(?) mean that this code raises an error:
```
from psychopy.visual import GratingStim
class SubClass(GratingStim): pass
```
TypeError: Error when calling the metaclass bases
metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

From google it looks like either we've got a clash between metaclasses (mixins) or we need to specify explicitly what the metaclass is of the final class

**Comment by hoechenberger** [comment]
This appears to be caused by/related to the lazy importing taking place in `psychopy.visual`, since the following code _does_ work:
```
from psychopy.visual.grating import GratingStim

class SubClass(GratingStim):
    pass
```

Also, if I remove the lazy importing from `visual.py`, and insert a `from psychopy.visual.grating import GratingStim` in `visual.py` instead, then your original example also works.

**Comment by peircej** [comment]
Nice detective work Richard. In this case, the key might be to import the base classes not using lazy import and then just lazy import the final class. That way users can probably use the original method of subclassing

**Comment by peircej** [comment]
OK, so my plan to fix this by immediate import of the base classes and only lazy-importing the GratingStim doesn't work. I've checked an alternative package for lazy importing, called api_pkg, that doesn't seem to have this problem but I'm not inclined right now to switch to using that (it might have some other thing that breaks!)
So for now I think we just stick with Richard's solution of importing direct from the class's folder rather the level of visual.

thanks @hoechenberger ! ;-)

**Comment by hoechenberger** [comment]
Sorry, I could have saved you some time: I already tested the approach you suggested in the first place several days ago, and also didn't have success. I've read about apipkg, but I hear [one would have to transition the entire project at once...](https://github.com/njsmith/metamodule/issues/1)

Another alternative could be [metamodule](https://github.com/njsmith/metamodule), but while it's super-convenient for lazy-loading *modules*, I cannot seem to lazy-load *classes* (i.e., `from foo import bar`). I'll contact the developers about this.

**Comment by peircej** [comment]
haha, no worries ;-)
You did save me a lot of time tracking it down in the first place

On 12/05/16 18:08, Richard Höchenberger wrote:
>
> Sorry, I could have saved you some time: I already tested the approach 
> you suggested in the first place several days ago, and also didn't 
> have success. I've read about apipkg, but I hear one would have to 
> transition the entire project at once... 
> <https://github.com/njsmith/metamodule/issues/1>
>
> Another alternative could be metamodule 
> <https://github.com/njsmith/metamodule>, but while it's 
> super-convenient for lazy-loading /modules/, I cannot seem to 
> lazy-load /classes/ (i.e., |from foo import bar|). I'll contact the 
> developers about this.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1159#issuecomment-218822456>
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
