### ISSUE TITLE
Unnecessary `global` statements?

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1162]
Some modules have`global` statements at module top-level, which are used in the following way:
```
global var
var = f()
```
This appears to be redundant (and somewhat confusing), because the exact same behavior could be achieved using only the single line:
```
var = f()
```
I removed these unnecessary `global` statements; as expected, all tests still pass, and the demos still appear to be working correctly. However, I am not sure if the statements had been placed there for a good reason, or are simply "accidental leftovers".

The commit can be found here: hoechenberger/psychopy@e725f708f514c0de324ff46d2bc9b27fbed8fdaa

I can file a PR if these changes are actually not removing something that was intentionally put there :)

**Comment by hoechenberger** [comment]
Apparently github does not automatically send out notifications to other collaborators when an issue is created; therefore explicitly mentioning @peircej and @jeremygray here :)

**Comment by jeremygray** [comment]
My understanding is that `global` is not needed in these instances, nor is it functional, so can be removed. (I used to think it was needed, so ended up adding it in a few places.) And I would not rely on tests -- test by hand if possible as well.

**Comment by hoechenberger** [comment]
Thanks Jeremy. I ran the demos manually, seemed fine. And yes, I also believe it is safe to remove these statements, because module top-level variables "global" by definition already...

**Comment by jeremygray** [comment]
Exactly. They already are global

**Comment by peircej** [comment]
That mostly looks like me - I've had errors in the past with global vars and overgeneralised my mistake ;-)
