### ISSUE TITLE
psyexp seemingly overwritten by .py

### ISSUE THREAD

**Issue by OliJimbo** [psychopy/psychopy#1164]
Hi,

The following is from OSX 10.11.3 on the standalone build of psychopy.

I've been having some troubles with psyexp files being overwritten by the .py file contents.  This has happened a couple of times in the past week so I thought I'd post something up here.

What appears to be happening is rather than the XML that the psyexp file stores, the coder py representation of the experiment is being saved (spontaneously it seems).  I have managed to restore a prior version of the experiment using dropbox which tracked the changes to the file which kind of verifies that this is the problem.

The only other info I can give you is the output from the console when I try to open the .psyexp file:

Failed to load /Users/oliverclark/Dropbox/Between PC and MAC/YB/fMRIExperimentMK4.psyexp. Please send the following to the PsychoPy user list
Traceback (most recent call last):
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/builder.py", line 4266, in fileOpen
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/experiment.py", line 362, in loadFromXML
  File "lxml.etree.pyx", line 3083, in lxml.etree.XML (src/lxml/lxml.etree.c:70338)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

Has anyone else had this behaviour at all?

BW

Oli

**Comment by peircej** [comment]
This issue has been seen twice by other users on the mailing list, but not in a way that could be reliably reproduced. My best guess so far is that they've managed to save the file without an extension (.psyexp) and then done the same with the script file. This was based on the fact that the two times it's been reported the file they provided had no extension.
But yours *does* have its `psyexp` extension so I don't know what's going on.

Is it possible that you saved it without that at some point? I presume you can't reproduce this reliably?

**Comment by OliJimbo** [comment]
You're right - it does seem like human error here.  In fact - I think I may have just added the psyexp extension (this was before I knew that there was an XML element to these files and was just hoping that changing the filename would fix it!).  I suppose one way around this would be to automatically make the .py filename distinctive aside from the extension but that sounds like a mass of confusion.  Can probably close this issue!

**Comment by peircej** [comment]
OK, glad to hear that it makes sense as a possible cause. The solution I 
came up with was to force psyexp to be added on save (previously psyexp 
was added to the SaveAs... dialog but didn't prevent users from deleting it)

https://github.com/psychopy/psychopy/commit/3f490506f1574abc8cd92796ab13f8b18997de27

On 17/05/2016 10:37, OliJimbo wrote:
>
> You're right - it does seem like human error here. In fact - I think I 
> may have just added the psyexp extension (this was before I knew that 
> there was an XML element to these files and was just hoping that 
> changing the filename would fix it!). I suppose one way around this 
> would be to automatically make the .py filename distinctive aside from 
> the extension but that sounds like a mass of confusion. Can probably 
> close this issue!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1164#issuecomment-219668057>
>

-- 
Jonathan Peirce
Nottingham Visual Neuroscience

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
