### ISSUE TITLE
Exception is raised every time when starting PsychoPy if git is not installed

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#1179]
I'm testing 1.84.0 on my Windows10 machine. Every time when starting PsychoPy, following exception is shown at the Output pane of the Coder window.

> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\site-packages\psychopy-1.84.0-py2.7.egg\psychopy\tools\versionchooser.py", line 195, in _remoteVersions
>     stderr=subprocess.PIPE)
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\subprocess.py", line 566, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "C:\WinPython-PsychoPy\python-2.7.10\lib\subprocess.py", line 958, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified

In Line 192-197 of versionchooser.py, git is as following. After I installed git on my PC, this exception has not occur.

```
        try:
            cmd = 'git ls-remote --tags https://github.com/psychopy/versions'
            tagInfo = subprocess.check_output(cmd.split(),
                                              stderr=subprocess.PIPE)
        except CalledProcessError:
            pass

```

I think that exception should not occur even if git is not installed.  I confirmed that relacing CalledProcessError with OSError works fine on Windows.  Simply deleting CalledProcessError to ignore all exceptions seems to work.
Is there any reason to handle only CalledProcessError here?

**Comment by peircej** [comment]
Thanks - I've fixed this in my own branch now and will merge in before release. Thanks for tracking down the problem

**Comment by hsogo** [comment]
I see.  Specifying exceptions under various versions/platforms will be hard work, but It's really nice.
