### ISSUE TITLE
Flow Menu not updating when routine deleted

### ISSUE THREAD

**Issue by OliJimbo** [psychopy/psychopy#1182]
MAC OSX El Cap Ver 184.ORC standalone

Deleted routines still showing in Flow - when all deleted and context menu opening attempted a list out of range error is returned.

Also with loop.

Will delete when Tab is closed.

Likely redraw isn't being called - but i can't find where it at the moment - am looking though.

**Comment by peircej** [comment]
Fixed in d8e388cd (should have been calling draw() rather than redraw() )
