### ISSUE TITLE
Highlight tabs with code in code properties

### ISSUE THREAD

**Issue by tstenner** [psychopy/psychopy#1194]
The code properties view shows only the code in the "Begin Experiment" tab with no indication if any other tabs contain code.
Highlighting tabs with code (e.g. by underlining the text; in the attached mockup the `Begin Experiment` and `End Experiment` tabs are highlighted) could show immediately where code is inserted.
I could implement it in the next weeks, but I'd need some feedback how it should look first.

![highlight_mockup](https://cloud.githubusercontent.com/assets/920936/16034581/dd658e3e-3212-11e6-9852-c2c67d2838ef.png)

**Comment by peircej** [comment]
If wx widgets ( FlatNotebook)  supports formatting in the tabs then it 
sounds handy. My guess is that bold will look least ugly. Underlined (or 
just a different colour) will be fine too if you can't make it bold.
cheers
Jon

On 14/06/16 08:33, tstenner wrote:
>
> The code properties view shows only the code in the "Begin Experiment" 
> tab with no indication if any other tabs contain code.
> Highlighting tabs with code (e.g. by underlining the text; in the 
> attached mockup the |Begin Experiment| and |End Experiment| tabs are 
> highlighted) could show immediately where code is inserted.
> I could implement it in the next weeks, but I'd need some feedback how 
> it should look first.
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1194>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AAXOpnvVxn08y8GI-v1G9HFwHemcQetcks5qLllCgaJpZM4I1CYi>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by tstenner** [comment]
Closed by pull request #1204
