### ISSUE TITLE
Using variable durations for Expected Duration fields

### ISSUE THREAD

**Issue by wildetudor** [psychopy/psychopy#1198]
The Expected Duration fields of some components are perhaps more useful than the developers might think. Right now these fields only take constant values, and using a $variable does not work - but would be very useful to have!

**Comment by peircej** [comment]
I don't think that's possible, but I also don't know why it's useful.

Expected duration does nothing more than allow the bar to be drawn on the routine timeline. If the value is a variable then it can't be determined until run-time so what do we draw in the pink bar?

What are you aiming to use this for?

**Comment by wildetudor** [comment]
THe use would be just a correct intuitive visualisation of the experiment's
timeline, which would change as soon as time-related variables (durations
etc) are changed (I set these experiment-wide global variables in a code
component in the first - Instructions - routine). But if variable values
can't be retrieved until run-time, I guess it cannot be done like that..

**Comment by peircej** [comment]
Yes, I don't think PsychoPy could know where your variable will have been defined (e.g. in a conditions file, in code or in come other location) so I don't think we can do this. I think we'd need to introduce the concept of constants (looking and acting like variables but they aren't expected to change during the experiment) but I don't want to get into that for now
