### ISSUE TITLE
Inconsistent text rendering

### ISSUE THREAD

**Issue by lindeloev** [psychopy/psychopy#1212]
Underscores are not rendered consistently between systems. There's spacing on some and not on others. See report on Discourse: http://discourse.psychopy.org/t/how-can-i-render-a-blank-mid-sentence/784/3

Is this just specific to this single user? Or is it OS-specific? Or hardware/OpenGL specific?

**Comment by ghcmat** [comment]
Font rendering is OS specific and differs between platforms. Pyglet automatically selects the font rendering interface native to the platform (Quartz, freetype, win32, etc.) 

You might be able to install freetype on all platforms to have a common text rendering interface; possibly solving some of the portability issues with font rendering.

**Comment by peircej** [comment]
I wonder if this is resolved by TextBox, but actually I don't think there's much we can do about it either way. Closing for now
