### ISSUE TITLE
Show only part of a video stimulus

### ISSUE THREAD

**Issue by TheChymera** [psychopy/psychopy#1225]
Is it possible to have [`MovieStim`](http://www.psychopy.org/api/visual/moviestim.html#psychopy.visual.MovieStim) play only a certain *spatial* percentage of a movie file?

I would like to be able to show 0-25% of the x-size of a stimulus, then 25-41% etc. It is not feasible for me to manually crop the videos, because I need to control the crop coordinates at runtime.

I am currently using [this code](https://github.com/TheChymera/behaviopy/blob/master/behaviopy/event_tracking.py), and I was hoping I can get this effect with the `MovieStim.size` attribute somehow, but that invariably controls the size of the entire movie.

**Comment by mmagnuski** [comment]
I don't know how to do it in psychopy (maybe its even not possible), but you can also try using [moviepy](http://zulko.github.io/moviepy/) to edit the movies from python.

**Comment by TheChymera** [comment]
Apparently this can be done via an Apperture object:

```
aperture = visual.Aperture(win, size=0.2, pos=(0, 0), ori=0, nVert=120, shape='square', inverted=False, units="norm", name=None, autoLog=None)
```
