### ISSUE TITLE
Error in builder generated code and accuracy scoring

### ISSUE THREAD

**Issue by jarrodmoss** [psychopy/psychopy#1229]
For a keyboard component in 1.83.04, Builder generates this code:
```
# check responses
if key_resp_2.keys in ['', [], None]:  # No response was made
   key_resp_2.keys=None
   # was no response the correct answer?!
   if str(correctAns).lower() == 'none': key_resp_2.corr = 1  # correct non-response
   else: key_resp_2.corr = 0  # failed to respond (incorrectly)
```

In 1.84, Builder generates this code:
```
# check responses
if key_resp_2.keys in ['', [], None]:  # No response was made
    key_resp_2.keys=None
# was no response the correct answer?!
if str(correctAns).lower() == 'none':
   key_resp_2.corr = 1  # correct non-response
else:
   key_resp_2.corr = 0  # failed to respond (incorrectly)
```

I believe the second if statement in the 1.84 code should be indented such that it is only executed if no key was pressed.

**Comment by peircej** [comment]
You're quite right. Many thanks for finding that. 
 In 
https://github.com/psychopy/psychopy/blob/master/psychopy/app/builder/components/keyboard/__init__.py
lines 435-439 we need 4 extra spaces in the string.

Do you want to fix and make a pull request or shall I do it? You doing it means you get credit (I like things being credited to the originator and happy to instruct you - this will be an easy one to fix just online) but I'm happy just to do it if you prefer.

**Comment by jarrodmoss** [comment]
Ok. Thanks for pointing me in the right direction. I've got some experience with git but none with pull requests. I've attempted to create one. Let me know if there is something I need to do differently.

**Comment by peircej** [comment]
Looks perfect. I'll probably build a new release, with this included, 
pretty quickly. Thanks for your help!




This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
