### ISSUE TITLE
Suggest moving "GL.gl_info.have_extension('GL_STEREO')" checks in window._setupPyglet to precede creating a GL.config

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#1235]
Hello,
I'm finding that requesting a stereo window on a system without hardware support causes pyglet (version 1.2.4) to throw a "pyglet.window.NoSuchConfigException" error instead of warning that the driver does not support it. 

If the check precedes the first GL.config call and sets self.stereo=False, a warning is displayed and the problem is circumvented with no apparent side-effects.

**Comment by ghcmat** [comment]
I submitted pull request #1236 that fixes this.
