### ISSUE TITLE
iohub EyeLink unresponsive keyboard during calibration

### ISSUE THREAD

**Issue by egorananyev** [psychopy/psychopy#1239]
Hi everyone,

I'm running into an issue eye-tracking calibration: the keyboard freezes at the setup screen, and one of the new instances/processes crashes (probably the one associated with the keyboard). I have EyeLink 1000 Plus, running PsychoPy 1.82.01 from OS X 10.9 Mavericks. None of the keys are working (including Esc), and the program simply hangs, so it's different from the issue reported here: https://groups.google.com/forum/#!topic/psychopy-users/tzLPxZaPeYg

Note that I used a modified SRR_eyelink_std.yaml file to only have three values for screen_background_color -- minus the alpha value -- otherwise it crashes ("ValueError('Invalid parameter. Should be length 3 but got length 4',)" in setColor).

The following error is produced when running 'getting_started.py':

> ###### #### Running: /Users/egor/Dropbox/Projects/mc/mc/mcbsf_iohub.py
> 
> [CarbonScreen(x=0, y=0, width=1920, height=1080), CarbonScreen(x=-1680, y=0, width=1680, height=1050)]
> 2016-09-05 17:58:57.929 python[66707:507] PyObjCPointer created: at 0xa09a1438 of type {__CFBoolean=}
> {...}
> 964 thread_policy_set failed: 4.
> EL Modes: ['250B', '500B', '1000B', '2000']
> EL srate: -32768
> EL rts: [250, 500, 1000]
> ERROR: setEyesToTrack: Selected sample rate is not supported!
> 2016-09-05 17:59:06.458 python[66721:507] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/6k/qxj7wz1n5kbff7v1rdlvbkkr0000gv/T/org.psychopy.PsychoPy2.savedState

The unresponsive keyboard issue seems to be similar to the following one: https://groups.google.com/forum/#!topic/psychopy-users/_mXv6gUlg4w
The proposed solution (replacing iohub with the version written by Sol to deal with this issue) only helped somewhat: it got rid of the unsupported sample rate, but not the keyboard issue. 

> ##### Running: /Users/egor/Downloads/distribute/demos/coder/getting_started/getting_started.py
> 
> 2016-09-05 17:29:46.829 python[66393:507] PyObjCPointer created: at 0xa09a1438 of type {__CFBoolean=}
> {...}
> 964 thread_policy_set failed: 4.
> 2016-09-05 17:29:54.942 python[66406:507] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/6k/qxj7wz1n5kbff7v1rdlvbkkr0000gv/T/org.psychopy.PsychoPy2.savedState

However, the solution also proposed to upgrade to 1.83.04. I tried upgrading but ran into the following issue instead, to which the only solution seems to be downgrading back to 1.82.01:
https://groups.google.com/forum/#!msg/psychopy-users/X0Q3NkZDXPc/_sqSrZzTAQAJ

I made a single modification in my psychopy installation: I renamed the directory

> /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/win32/

 into 

> /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/darwin/

Before that, PsychoPy gave the following message: 

> Could not add path: /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/darwin/python27/
> 964 thread_policy_set failed: 4.
> EL Modes: ['250B', '500B', '1000B', '2000']
> EL srate: -32768
> EL rts: [250, 500, 1000]
> ERROR: setEyesToTrack: Selected sample rate is not supported!
> Could not add path: /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/darwin/python27/

It still ran the calibration, but gave the same thread_policy_set error, as seen above.

I know that EyeLink 1000 Plus is not tested, but I am eager to resolve this issue, so please let me know if you need more information.

Best,
--Egor

**Comment by egorananyev** [comment]
Sorry, I think I was supposed to post this on Discourse instead. Feel free to close this issue.

**Comment by egorananyev** [comment]
The issue was reposted here: http://discourse.psychopy.org/t/iohub-eyelink-unresponsive-keyboard-during-calibration/1023

**Comment by peircej** [comment]
Whether you post it here or on discourse, I think the only person that can probably help is @isolver

**Comment by isolver** [comment]
This issue seems to be fixed. Tested with python 3.6, using eyelink 1000, on macos catalina.
