### ISSUE TITLE
Error with the test_loopBlocks unit test

### ISSUE THREAD

**Issue by danielshub** [psychopy/psychopy#1243]
The test_loopBlocks unit test in tests/test_app/test_builder/test_Experiment.py requires an audio API, but the test is not marked "@pytest.mark.needs_sound".

**Comment by hoechenberger** [comment]
Do you feel like filing a pull request for this one? :)

**Comment by peircej** [comment]
I think the `test_loops` test no longer needs sound - it's running and passing on GitHub ubuntu VM with no sound
