### ISSUE TITLE
Rating scale, builder: key presses made before ratings scale is shown are registered

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1246]
If there are unprocessed key presses made before the rating scale is shown, those keypresses are accepted by the rating scale. This occurs regardless of whether the rating scale is shown after the prior stimulus within the same routine, or if the rating scale is in a routine by itself.

I'm including an example .pysexp file that demonstrates this, along with workarounds for both cases.

[ratingScale-keyBleeds.psyexp.zip](https://github.com/psychopy/psychopy/files/485778/ratingScale-keyBleeds.psyexp.zip)

The workaround is simply to call event.clearEvents() before displaying the rating scale. When the rating scale is in its own routine, in a code component, in Begin routine, the call:

```
event.clearEvents()
```

solves the problem. When the prior Stimulus is in the same routine as the rating scale (i.e. Show text for 3 seconds, then rating scale), the code component has:

**Begin routine**

```
eventsCleared = False
```

**Each frame**

``` python
if ratingScale.status == STARTED:
    if not eventsCleared:
        event.clearEvents()
        eventsCleared = True
```

**Comment by jeremygray** [comment]
Interesting. I'm not sure what is best here. I don't think that the `visual.ratingscale.RatingScale()` class should ever be clearing events (just like it should not control the stimulus to be rated). 

The builder rating scale component should probably do clear events by default, but have an option not to do so. Clearing keys should only clear those keys that would impact the rating scale behavior (leaving other keys unaffected). 

After an instance `rs` has been created with various options, `rs.allKeys` is a list of those keys that could / should be cleared: `events.clearEvents(keys=rs.allKeys)`

**Comment by TEParsons** [comment]
Closing this now as RatingScale is deprecated, the best solution is to use Slider
