### ISSUE TITLE
Release archive names

### ISSUE THREAD

**Issue by TheChymera** [psychopy/psychopy#1247]
I am providing psychopy for Gentoo Linux users, and I use the tarballs from the GitHub releases as the upstream sources. The `1.84.0` sources link was prepended with a “v”, the `1.84.1` sources link is not, earlier releases are also missing the “v”. Would it be possible to choose one naming scheme and stick to it for future releases? It would help us provide the newest version of you software to users.

**Comment by peircej** [comment]
I was intending to switch (following github recommendations) and then decided it was a bad idea (because of the knock on effects like this). So yes, generally we won't be switching.


-------- Original message --------
