### ISSUE TITLE
Rating component doesn't save data in staircase loop. Builder

### ISSUE THREAD

**Issue by ababino** [psychopy/psychopy#1255]
Dear all,
thank you for this marvelous program. I have a problem with the rating component. If I use it in a random loop it works fine but if I use it in a staircase loop then it doesn't store any rating data. I mean that doesn't store not 'rating.response' neither 'rating.rt' in the ouput .csv file.  

I can fix this adding some code like this:

```
trials.addOtherData('rating.response', rating.getRating())
trials.addOtherData('rating.rt', rating.getRT())
```

That is ok but I think that this is not the expected behavior. Am I right?

I am using psychopy v1.83.04 in ubuntu 14.04 and I observed the same behavior in windows. 

I have attached a minimum example that reproduce the behavior.
[rating_problem.psyexp.zip](https://github.com/psychopy/psychopy/files/512258/rating_problem.psyexp.zip)

Thanks!

**Comment by TEParsons** [comment]
RatingStim is now deprecated, instead it's better to use Slider as it can do everything Rating could and more.
