### ISSUE TITLE
visual.helpers.setColor() sets color space to None if color is None

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1260]
`visual.helpers.setColor()` would reset the object's color space to `None` if
the passed color was `None`. This is unnecessary and causes an error message
to be logged.
## Reproducible examples

**Snippet 1:**

``` python
from psychopy.visual import Window
from psychopy.visual.circle import Circle

win = Window()
circle = Circle(win, fillColor=None)
win.close()
```

**behavior:** Works as expected.

**Snippet 2:**

``` python
from psychopy.visual import Window
from psychopy.visual.circle import Circle

win = Window()
circle = Circle(win)
circle.fillColor = None
win.close()
```

**behavior:** logs an error: `ERROR     Unknown colorSpace: None`.

The responsible lines is this: https://github.com/psychopy/psychopy/blob/88a359df45ce453d4fd95986cf902e66cf2fe480/psychopy/visual/helpers.py#L196

``` python
if color is None:
    ...
    obj.__dict__[colorSpaceAttrib] = None  # e.g. obj.colorSpace='hex'
    ...
```

If this line is removed, the above examples do work flawlessly; however, the following generates a new error:
## Reproducible example

Snippet 3 (with the abovementioned change to `setColor()` applied):

``` python
from psychopy.visual import Window
from psychopy.visual.circle import Circle

win = Window()
circle = Circle(win)
circle.fillColor = 'red'
circle.fillColor = None
win.close()
```

**behavior:** logs an error: `ERROR     If you setColor with a numeric color value then you need to specify a color space, e.g. setColor([1,1,-1],'rgb'), unless you used a numeric value previously in which case PsychoPy will reuse that color space.)`

This happens because the object's `colorSpace` attribute is set to `'named'` when 

``` python
circle.fillColor = 'red'
```

is invoked, and stays that way when we execute the line

``` python
circle.fillColor = None
```

To avoid this problem, I have considered changing the above `if` block to:

``` python
if color is None:
    ...
    obj.__dict__[colorSpaceAttrib] = None  # e.g. obj.colorSpace='hex'
    ...
    return
```

but I don't fully understand the code that follows inside the function, and possible side effects of not executing it.

**Comment by peircej** [comment]
Hmm. The reason colorSpace is needed is to:

- know how to translate the color when rendering (not needed here)
- know whether a subsequent color can be *added* using += operations. In this case we want it to be clear that this isn't possible without an obscure default message `TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

I would change the code at the point where the assignment and error message are though. Around line 202 of visual.helpers `if colorSpace is None and color is not None:` but possibly your fix achieves the same

**Comment by peircej** [comment]
Yes, looking more, I think we should not `return` after setting colorspace to None we should just continue but handle it better in the following code. The last line of that function where we `setTexIfNoShaders(obj)` may be needed, for instance.

**Comment by TEParsons** [comment]
Once #3189 is pulled in this will no longer apply, setColor will create a Color object which knows its color space - for None this will be `named`
