### ISSUE TITLE
Weird code block in visual.window

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1264]
In `visual.window`, there is a [weird code block](https://github.com/psychopy/psychopy/blob/88a359df45ce453d4fd95986cf902e66cf2fe480/psychopy/visual/window.py#L1539)

```python
    def _setupGL(self):
        if self.winType == 'pygame':
            try:
                pygame
            except Exception:
                logging.warning('Requested pygame backend but pygame ,'
                                'is not installed or not fully working')
                self.winType = 'pyglet'
```
Was the `try` block meant to be `import pygame` instead of just `pygame`? But we already try to import PyGame [at the top of the module](https://github.com/psychopy/psychopy/blob/88a359df45ce453d4fd95986cf902e66cf2fe480/psychopy/visual/window.py#L96):

```python
try:
    import pygame
except Exception:
    pass
```
What's going on here?

**Comment by peircej** [comment]
As you say, we already tried to import pygame. If that has been successful then no exception will occur here but if not then pygame will not be in the namespace to exception will be triggered. Might look weird but is working and not requiring import to run again.

**Comment by hoechenberger** [comment]
Thanks, makes sense!
