### ISSUE TITLE
keyboard from iohub doesn't work on osx 10.7 and 10.8

### ISSUE THREAD

**Issue by eyelink** [psychopy/psychopy#1270]
Hi, 

```
 I tried the demo (keyboard.py and keyboardreactiontime.py) from iohub, but neither works. 
 I pressed keys but got no responses. (mouse works)

 Thanks.
```

Li

**Comment by dpaniukov** [comment]
Any updates on this? I have the same issue on El Capitan, but it works on Ubuntu (standalone from neurodebian). 

Is there an alternative to ioHub that can give me pressed and released keys and times for them?

**Comment by hoechenberger** [comment]
Doesn't it work *at all,* or do you get a response in the `keyboard.py` demo if you press the CMD, Ctrl, Option, Shift, Caps Lock keys?

**Comment by hoechenberger** [comment]
@dpaniukov If the modifiers do work, the problem is related to macOS's security features. You would have to add PsychoPy.app to the list of apps "to control your computer" in the System Preferences, and then click the lock icon to prevent any changes. This should fix the issue.

If you not even modifiers keys are working, then it's probably "something else".

**Comment by dpaniukov** [comment]
On Mac El Capitan, It works with sudo, which is good enough. Same for Windows 7, works only with Administrator privileges. 

On mac it does not work the way you described. Crashes when I run the keyboard.py demo. But you're right, it's a mac issue.

**Comment by hoechenberger** [comment]
What exactly does it mean when you say "it crashes"? On my computer, the script takes 20 seconds or so to "fully initialize", exceeding [the built-in time limnit](https://github.com/psychopy/psychopy/blob/7216a79e12e9d839f6cc87618610077a824efb3d/psychopy/demos/coder/iohub/keyboard.py#L142) and quitting "immediately". Changing line 142 from

```python
while not 'q' in events and flip_time - demo_timeout_start < 15.0:
```
to
```python
while not 'q' in events:
```
fixes this issue.

**Comment by dpaniukov** [comment]
It shows you the grey window and then it disappears.

**Comment by hoechenberger** [comment]
Regarding privileges:
iohub should work on Windows even when you do not run PsychoPy with admin privileges (right-click -> Run as Adminsitrator (or however it's called) should *not* be necessary). You may, however, be required to start it from a Admin account, yes.

On OS X, sudo should not be required.

**Comment by hoechenberger** [comment]
> It shows you the grey window and then it disappears.

Ok so this is probably the timeout issue I mentioned, change line 142 as proposed and this problem should be gone.

**Comment by dpaniukov** [comment]
Hm.. It starts, but then it captures only shift, ctrl, alt keys, but not the letters or space (nothing happens for the latter). 

Here are my system preference changes I made based on your response. 

![image](https://cloud.githubusercontent.com/assets/16146198/24206803/57641f18-0eed-11e7-8659-5daa49a02614.png)

**Comment by hoechenberger** [comment]
Thanks!

Can you try to:
- close PsychoPy
- go to the Preferences again
- click the lock to unlock
- untick PsychoPy in the list
- set the tick again
- click the lock to "lock" it again
- run PsychoPy again?

**Comment by dpaniukov** [comment]
That solves the problem! Thank you!

PS sorry for delays in the answers, I do not have access to a mac very often.

**Comment by hoechenberger** [comment]
Glad I could help!
