### ISSUE TITLE
Drop PyGame support for visual stimuli

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1280]
PyGame has been marked as deprecated for quite a while now, and recently, PyGame tests have been dropped for visual stimuli (#1222). I propose to completely remove PyGame from the visual domain of PsychoPy with the next major release, as we cannot even guarantee that _any_ visual stimuli will be working when using PyGame.

**Comment by hoechenberger** [comment]
Is there already working joystick support in PyGlet?

**Comment by mdcutone** [comment]
Will this result in the SDL interface being dropped (just interested)? The stereo libs I'm working on will not support PyGame at all for rendering.

**Comment by peircej** [comment]
I don't see the need to remove this. We don't support it but we don't care if people use it do we? Why break people's code unless there's a clear need?

**Comment by OscartGiles** [comment]
Out of curiosity what was the reason for depreciating PyGame for visual stimuli?

**Comment by peircej** [comment]
The hassles for me of testing and fixing bugs on multiple platforms

**Comment by ofgulban** [comment]
@hoechenberger, I use a joystick in psychopy with pyglet. However it required a small change in the code. The relevant pull request is [here](https://github.com/psychopy/psychopy/pull/1331).
