### ISSUE TITLE
Possible names conflict when using condition files

### ISSUE THREAD

**Issue by lucaf** [psychopy/psychopy#1281]
The automatic extension of the namespace with the fields' names of the condition file can cause unexpected/bizarre behaviors. Would it be possible to give the chance to define a tag to be prepended to the fields' names when one loads a condition file? So if, let's say, the fields' names are Field1, Field2 etc, and my tag is TaskA, then I could reference the conditions' through the names TaskAField1, TaskAField2, etc.

**Comment by TEParsons** [comment]
We haven't directly solved this, but there are two roundabout solutions which I think effectively address it:
1. Thanks to @tpronk the template conditions file created when clicking the excel button on a TableCtrl has Excel validation on the top row to avoid any namespace clashes
2. There's an option in prefs to not expand conditions file variables, so as to keep the namespace clear
