### ISSUE TITLE
Skipping routine with Scale will result in timedout error 1.83.04

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#1292]
Found an interesting issue today, where if you have a routine that has a scale object but try to skip the routine for the first pass with a "continueRoutine = False", you end up with a:

**"RatingScale object has no attribute 'timedOut'"**

This is caused by the code generation trying to add a RT column to the trial data and passing rating.getRT().    Nothing unusual if you have told the Scale to record the reaction time under "advanced" settings.

If you run a trial and use the scale on the first iteration, then try and skip the routine on the 2nd (and so on) iteration - then it works perfectly fine.  So it seems that getRT() for the scale object needs a fallback of some kind for the scale object  if it hasn't been used at all.   No problems with keyboard and mouse components.

Attached is a sample script demonstrating the issue, built in Builder - 1.83.04
[scaleskip-test.zip](https://github.com/psychopy/psychopy/files/562242/scaleskip-test.zip)

**Comment by jeremygray** [comment]
I am not seeing this error (or another one) when running your script. I see a fixation point for ~3 sec. 

In the `visual.ratingscale.RatingScale` class, at the end of `__init__` there's  a line that sets `self.timedOut = False`. So I am quite surprised that the error is that the object has no such attribute.

**Comment by jeremygray** [comment]
@hoechenberger can you replicate the bug?

**Comment by frankgasking** [comment]
Hi Jeremy,  embarrassingly - i've re-ran the script, and I too am not getting the issue any longer.  Not entirely sure what is going on.   Even on the original script with the issue, it seems fine.   Not upgraded PsychoPy or re-installed.   Happy to close this at the moment, but apologies for wasting anyone's time.
