### ISSUE TITLE
Add ___2norm and norm2___ conversion functions to monitorunittools

### ISSUE THREAD

**Issue by janfreyberg** [psychopy/psychopy#1296]
This was recently referenced on the forum:
http://discourse.psychopy.org/t/ratingscale-from-norm-to-cm-units/1398

Would it make sense to add these functions, particularly since some stimuli only accept norm units?

**Comment by janfreyberg** [comment]
This would obviously require a dimension argument (since x and y will be scaled differently). Would be nice if it worked for tuples and lists with two elements, as well.

**Comment by TEParsons** [comment]
#4211 will essentially add this :) You'll be able to make a Vector in one unit space and then access its value in another, so can convert to and from any valid unit space.
