### ISSUE TITLE
Pysoundcard has bug, fixed in most recent github version 

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1300]
There was a bug in Pysoundcard that was not allowing sound.py to correctly init (at least on Ubuntu 14.04, not sure if it affected other systems), the error was:

    CDefError: 'enum PaHostApiTypeId' has no values explicitly defined: refusing to guess which integer type it is meant to be (unsigned/signed, int/long)

Apparently one of their dependencies (cffi) had changed a warning to an error. Here's where I found that PySoundCard had found out about it:

https://bitbucket.org/cffi/cffi/issues/234

PySoundCard's latest version includes a fix:

https://github.com/bastibe/PySoundCard/commit/7490aae6cfb6c85d15ba81d46e35c7843e5b6cda

Here it is, beginning at line 112 of pysoundcard.py (nothing was deleted, this is all added code :

 ```c
typedef enum PaHostApiTypeId
{
    paInDevelopment=0, /* use while developing support for a new host API */
    paDirectSound=1,
    paMME=2,
    paASIO=3,
    paSoundManager=4,
    paCoreAudio=5,
    paOSS=7,
    paALSA=8,
    paAL=9,
    paBeOS=10,
    paWDMKS=11,
    paJACK=12,
    paWASAPI=13,
    paAudioScienceHPI=14
} PaHostApiTypeId;

```

**Comment by peircej** [comment]
pysoundcard has been superseded by several superior packages and I think we can close this now
