### ISSUE TITLE
on the scaling of `psychopy.visual.window.viewPos`

### ISSUE THREAD

**Issue by cjayb** [psychopy/psychopy#1322]
I find the use of the `viewPos`-attribute of a `window` slightly unclear. I could manipulate it real time, but the units did not follow anything I specified (`pix` or `deg`). The `flip`-method says:

https://github.com/psychopy/psychopy/blob/89cce557d6daaab4fd7136de22f457322dc96b64/psychopy/visual/window.py#L653-L656

and after some testing I figured out that `viewPos` is in "normalised" coordinates. Presumably because `glTranslate` assumes this.

Am I correct in saying that the handling of `viewPos` should be checked against the current `units` of the window?

All that said, I'm pretty stoked about the ability to manipulate this parameter! /Chris

**Comment by peircej** [comment]
I think it would be ideal if it followed the default units of the Window. I think it's just following `norm` because that is the natural unit of OpenGL. Feel free to add the conversion if possible

**Comment by cjayb** [comment]
Thanks for the quick response. I've been looking at the implications of changing how `viewPos` is handled: it's not used by any `psychopy` methods. There may be good reasons to let the parameter remain in GL-coordinates (norm)? You are very explicit about each stimulus being able to override the window units,  and then there's this:

https://github.com/psychopy/psychopy/blob/2541564da842dc606f6e77ae60c9ba53fd119373/psychopy/visual/window.py#L1273-L1277

Are you in fact moving to `Window` only ever being in `pix`-units? I'm having trouble grokking how the window units are used currently.

Re: `viewPos`, I can see a couple of alternatives here:
* add a comment to docstring to the effect of: "viewPos : *None*, or [x,y] in normalised units", leaving the task of translation to the user
* make `viewPos` a property add a method `setViewPos` for manipulating it between the possible units to normalised (is this overkill?)

**Comment by cjayb** [comment]
BTW: I spent considerable time today installing the dev-version of psychopy... Here's the yaml-file of the `conda` environment I managed to set up that finally worked:

https://gist.github.com/cjayb/67d8f6ada85f8fcd58ff1d4e1fc20764

In it, this works, for me (OS X 10.11.5)

```
python.app psychopyApp.py
```
(I hit a little `matplotlib vs. OS X 10.11` snag with locales on the way, which I understand is fixed in Sierra/10.12)

**Comment by peircej** [comment]
No, it isn't that window will only support pix in future; it's just I changed (several years ago) the way that scaling was handled. It used to be that the window had to change its scale as each stimulus was drawn. Now it is left in one of two "native" scales (pix and norm) and then the stimuli handle the transformations themselves.
Window will continue to have a units setting that will be applied to the mouse and to any stimulus that doesn't override it. I think it would be _ideal_ if this were applied to the viewPos, as you suggest, but it isn't a big deal and might be a hassle to sort out. Simply changing the documentation is fine too. Whatever you can be bothered with :-)

**Comment by peircej** [comment]
Thanks for the conda recipe Chris. I don't use Conda so I don't know much about this, but maybe your yaml file is a useful update for @kastman's Conda recipe?

**Comment by cjayb** [comment]
Let me sleep on it. Now that I know how viewPos is handled, I can use it as-is (and would have figured it out immediately from the docstring). In my application, input is coming in `pix` coordinates (from an eye tracker), so scaling to `norm` is no big deal.

At the very least I will submit a PR for a docs-enhancement to close this. Since I'm used to a slightly different workflow in other projects, I need to ask: do you really need me to PR my `master` against yours? I usually submit my feature branch against the current `master`. I'm referring to [this page](http://www.psychopy.org/developers/repository.html).

**Comment by peircej** [comment]
Nope, happy for you to PR from any branch. :-)

**Comment by kastman** [comment]
Hi @cjayb - thanks for the conda gist. I'm actually in the process of moving over to conda-forge, so this will be very helpful. I may get in touch if I have any questions?

**Comment by cjayb** [comment]
@kastman excellent! Haven't tried anything so ambitious, so not sure I can directly help. But I'm more than happy to beta(/alpha)-test for you! Convinced conda-forge has a brilliant future, PsychoPy should be there too!
