### ISSUE TITLE
TextStim: Unicode characters not displayed correctly on Windows 10

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1324]
User reported unicode characters don't display correctly with `TextStim` using the Arial font on Windows 10; working fine on Linux Mint 13 & 14 and Windows 7 & 8.1, though.

http://discourse.psychopy.org/t/unable-to-show-unicode-from-excel-files/1630/

**Comment by peircej** [comment]
I think this is something we won't have any control over. I still suspect it's due to the font file or, possibly, to pyglet text rendering. I think the solution will remain "use a different font"

**Comment by TEParsons** [comment]
@peircej does this carry through to TextBox or does glyph-by-glyph rendering solve it?
