### ISSUE TITLE
Builder - Strings in compiled scripts flip between Unicode and Regular randomly?

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#1335]
At present, exported Builder scripts sometimes add a u'' prefix to strings, and sometimes don't. This behavior seems very inconsistent, and happens even when the values of the strings themselves doesn't change; it's especially frustrating because the prefix can also disappear.

This is especially obvious when scripts are checked in to version control - compiling a .py script using the exact same version of psychopy, and changing only things that don't seem superficially string related (e.g. extending the duration of a component) causes certain things to be prefixed or not, e.g. a key in the expInfo front matter will go from a regular string to a unicode string, even though the expInfo dict is unchanged, and will then revert back to being a regular string after a few more changes that again don't change the expInfo. This is also common for setting variables of stims (e.g. text stim text, color attributes). The unicode just shows up without making any changes to the relevant parts, and then disappear again later with no noticeable pattern.

Once I figure out what causes the flip back and forth (still don't know after watching the problem pretty carefully for months), I would ideally identify whether a string contains any unicode characters and the prefix only when required, or at the very least escaping all Builder strings with the u prefix, in order to avoid lots of noise when checking in updated versions of scripts. This is really only a problem when tracking scripts long-term with source control, and has no effect on the outcome of scripts, but would be helpful for increased support for best practices in the community.

I haven't done any real work with unicode, but I'm going to take a peak and see if there's anything obvious about why strings are unicode or not. Has anyone seen this before? I'm going to poke around in `app/builder/experiment.py#writeScript()` but wanted to add this issue in case someone was already working on it before I went too far down a rabbit hole.

**Comment by peircej** [comment]
One place I know that things get forced to unicode is when they come back from the a wx dialog. SO if you go into any component properties dialog and change something (don't press cancel) you'll get all the properties in unicode.
One place that they (probably) get switched back is in saving/reloading a file from psydat. That involves saving as a text (xml) file and the values are converted to pure text representation for that but they could/should probably be converted to unicode when they get reloaded (in `Experiment. _getXMLparam()`) so that the internal representation is always u"". It looks like some types of parameter value are already being forced to unicode but maybe more of them need it.

**Comment by kastman** [comment]
Any reason to not force everything to unicode on xml load? The only thing I can think of is readability of the compiled script (I often get questions from new users about "what does that u mean?")

Seems a reasonable alternative would be testing each string and using the regular version if it is successfully encoded, e.g. [these SO](http://stackoverflow.com/questions/196345/how-to-check-if-a-string-in-python-is-in-ascii) [questions](http://stackoverflow.com/questions/447107/what-is-the-difference-between-encode-decode).

I personally think this would be worth the added complexity, but what do you think Jon? People tend to just accept and ignore the "u" after they see it once or twice, so maybe casting everything to unicode would just be easiser and safer.

**Comment by peircej** [comment]
Yes, I'm comfortable with it being encoded to unicode on loading. I was only wondering where it could lead to problems (e.g. if we accidentally converted a parameter that's a bool) but I don't think there are actually any issues.

**Comment by hoechenberger** [comment]
+1 for all-unicode

**Comment by TEParsons** [comment]
String params are handled by the `Param.__str__` method which always compiles them as a regular string with no prefix, so default unicode. The only case where it's not is if the value of the param is `$u'whatever'`, in which case it probably should be prefixed as the user has deliberately specified for it to be. So I think it's safe to close this? Please do reopen if not
