### ISSUE TITLE
Simple clarification of dependencies in Docs

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1339]
In the updated Dependencies section of the <a href="http://www.psychopy.org/installation.html#dependencies">docs</a> , I believe these two packages are platform-specific, no?

    pypiwin32
    pyobjc

They're currently included in a list of packages that is suggested could be copy-pasted when installed, which I somewhat blindly did, only to have these two fail to install (I'm on a Linux machine), and then thinking "Duh", those seem like Windows and Mac-specific packages, respectively. So unless I'm wrong, maybe they should be moved out of that catch-all list?

Btw, thanks for updating the list!

**Comment by peircej** [comment]
correct :-) 
Feel free to submit a pull request on this

**Comment by dantheman39** [comment]
Done. I didn't actually realize the docs were there in the repository! Hopefully I've done it correctly.
