### ISSUE TITLE
Coder tutorial 3 uses deprecated function

### ISSUE THREAD

**Issue by m2march** [psychopy/psychopy#1343]
The script returns the following error:

> DeprecationWarning: FitFunction is now fully DEPRECATED: use FitLogistic, FitWeibull etc instead

See: https://github.com/psychopy/psychopy/blob/master/docs/source/coder/tutorial3.py#L37

**Comment by peircej** [comment]
Yes, this needs fixing. Thanks for reporting it. Want to submit a pull request?

**Comment by peircej** [comment]
The fix above wasn't quite right - it changed the fit from a Weibull to a Logistic. I've updated the docs with the correct fix in 671be2d73cf9c47f43e04e9b5b1d2c3016d804d2
