### ISSUE TITLE
Text elements are not appearing when generated in builder mode

### ISSUE THREAD

**Issue by ryanHutchings** [psychopy/psychopy#1352]
In the newest version (1.85), text elements that I added using the builder mode were not appearing when I ran the experiment. I tried to change the colors and size, and the text elements remained invisible. 

Best, 
Ryan

**Comment by peircej** [comment]
I just ran stroop demo on mac 1.85 version and it seems fine. More details on how to replicate this please

**Comment by hoechenberger** [comment]
@ryanHutchings any news on this one?

**Comment by hoechenberger** [comment]
Closing for now, feel free to re-open any time.
