### ISSUE TITLE
Participant Feedback Visibility

### ISSUE THREAD

**Issue by Humuhumunukunukuapuaa** [psychopy/psychopy#1355]
Hi all, 

I have two issues that I'm having trouble figuring out in builder code. ( Am new to psychopy). 

1. I would like the participant feedback to be visible when they are keying it in. Is this possible? 

2. The participant will be keying in two letters and then hitting spacebar to go to next trial. I know how to "force end trial" if they are only responding with one keypress, but am not sure how to record the two key presses without forcing the end of trial. 

If you could help with either or both, it would be much appreciated :) We are scheduled to start running participants early next week so I'm in a bit of a time crunch. 

Thank you, 

Nikki

**Comment by peircej** [comment]
Please use the forum for user support. This issues list is for tracking bugs and new features. Sorry to hear you're in a rush. All the things you ask are possible but you're going to need to learn a bit about how to write code components.  Maybe you have a supervisor that could help?
