### ISSUE TITLE
 ioHub SMI eyetracker device creation Psychopy 1.84.2

### ISSUE THREAD

**Issue by hannehuygelier** [psychopy/psychopy#1372]
The launchHubServer function to create a device that refers to the SMI RedM eyetracker throws a Yaml scanner error (in Psychopy 1.84.2). I checked the yaml file that contains the description of my device that I refer to in the launchHubServer function and I cannot find any formatting errors (extra tabs, etc...).  I also double checked with an online tool called "YAML Lint". I also did the same check for the "default_eyetracker.yaml" file that is located in this folder: "C:\Python27\Lib\site-packages\psychopy\iohub\devices\eyetracker\hw\smi\iviewx". So the YAML scanner error must be coming from a different YAML file, but I have no idea which one. 

**This is the error that I get:** 

> Error

 during device creation ....
<class 'yaml.scanner.ScannerError'>
ScannerError()
['  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 591, in createNewMonitoredDevice\n    device_instance_and_config=self.addDeviceToMonitor(device_class_name,deviceConfig)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 754, in addDeviceToMonitor\n    self.processDeviceConfigDictionary(device_module_path, device_class_name, device_config,default_device_config)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 564, in processDeviceConfigDictionary\n    device_config_errors=validateDeviceConfiguration(device_module_path,device_class_name,device_config_dict)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\devices\\deviceConfigValidation.py", line 423, in validateDeviceConfiguration\n    device_settings_validation_dict=loadYamlFile(validation_file_path,print_file=True)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\devices\\deviceConfigValidation.py", line 351, in loadYamlFile\n    yaml_file_contents=load(file(yaml_file_path,\'r\'), Loader=Loader)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\__init__.py", line 71, in load\n    return loader.get_single_data()\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\constructor.py", line 37, in get_single_data\n    node = self.get_single_node()\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 36, in get_single_node\n    document = self.compose_document()\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 55, in compose_document\n    node = self.compose_node(None, None)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 133, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 133, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 133, in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\composer.py", line 64, in compose_node\n    if self.check_event(AliasEvent):\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\parser.py", line 98, in check_event\n    self.current_event = self.state()\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\parser.py", line 449, in parse_block_mapping_value\n    if not self.check_token(KeyToken, ValueToken, BlockEndToken):\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\scanner.py", line 116, in check_token\n    self.fetch_more_tokens()\n',
 '  File "C:\\Python27\\lib\\site-packages\\yaml\\scanner.py", line 257, in fetch_more_tokens\n    % ch.encode(\'utf-8\'), self.get_mark())\n']
Error during device creation ....
<class 'psychopy.iohub.util.exception_tools.ioHubError'>
ioHubError:
Args: ('Error during device creation ....',)

['  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 520, in __init__\n    self.createNewMonitoredDevice(device_class_name,deviceConfig)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 603, in createNewMonitoredDevice\n    raise ioHubError("Error during device creation ....")\n']
<class 'psychopy.iohub.util.exception_tools.ioHubError'>
ioHubError:
Args: ('Error during device creation ....',)

['  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\launchHubProcess.py", line 35, in run\n    s = ioServer(rootScriptPathDir, ioHubConfig)\n',
 '  File "C:\\Python27\\lib\\site-packages\\psychopy\\iohub\\server.py", line 524, in __init__\n    raise ioHubError("Error during device creation ....")\n']
Traceback (most recent call last):
  File "C:\Dropbox\PHD_MultisensoryNeglect\ExperimentScripts\BasicEyeTracking\IoHubTest.py", line 27, in <module>
    io = launchHubServer(iohub_config_name = "iohub_config_SMI.yaml")
  File "C:\Python27\lib\site-packages\psychopy\iohub\client\__init__.py", line 1504, in launchHubServer
    return ioHubConnection(ioConfig)
  File "C:\Python27\lib\site-packages\psychopy\iohub\client\__init__.py", line 285, in __init__
    self.iohub_status = self._startServer(ioHubConfig, ioHubConfigAbsPath)
  File "C:\Python27\lib\site-packages\psychopy\iohub\client\__init__.py", line 943, in _startServer
    isDataAvail=self._serverStdOutHasData()
  File "C:\Python27\lib\site-packages\psychopy\iohub\client\__init__.py", line 1052, in _serverStdOutHasData
    raise e
pywintypes.error: (109, 'PeekNamedPipe', 'The pipe has been ended.')

> 

**And this is my code:**

`#============================================================================#
# Figuring out IoHub for Eyetracking with SMI RedM eyetracker
# Date: 10/03/2017
# Author: Hanne Huygelier
#============================================================================#

#-----------------------
# LIBRARIES:
#-----------------------
from psychopy import iohub, monitors
from psychopy.iohub import launchHubServer, devices
import os

#---------------------------------
# FOLDERS
#---------------------------------
RootFolder = os.getcwd()
#EyeTrackerFile = RootFolder + "\\" + 'default_eyetracker.yaml'

#---------------------------------
# Initialize Monitor & EyeTracker
#---------------------------------
mon = monitors.Monitor("00.68", distance = 50, width = 52)
mon.setSizePix([1920, 1080])
mon.saveMon()

io = launchHubServer(iohub_config_name = "iohub_config_SMI.yaml")`

I posted this here instead of stackoverflow, because I think it might be a bug, but I'm not 100% sure.

Any help would be much appreciated!

**Comment by cocoggfr** [comment]
Hello Hanne, hello dear PsychoPy developers,

I have been running a Python experiment (based on the gc_cursor/run.py demo) with a SMI eye-tracker on a laptop (Windows 7 64bit OS) without any problem for about a week (two computer setup). This 'stimulus PC' has been lent to me so I just used what was already installed on it: a manual installation of PsychoPy (in C:\Python27\lib\site-packages\), version 1.84.
Around 5% of the gaze samples were missing so I decided to run the experiment on the [fairly old] computer where iView X is installed (Windows XP 32bit OS) - I think SMI calls this a 'single computer setup'.
For the sake of simplicity (and also because the computer running iView X is not connected to the Internet) I installed the Standalone version of PsychoPy (1.84.2). And bam!... I tried to run my fully functional script (up to now...) and I encountered exactly the problem described above by Hanne.
So I went back to the two computer setup, installed the Standalone version of PsychoPy on the laptop ('stimulus PC ' with Windows 7) and tried to run my script in Coder view, I had the exact same problem as above (so obviously not a Windows XP problem)...

So it might be related to the Standalone installation? Or some module version on my 'manually installed' PsychoPy are different and don't create this problem?

Looking forward to hearing from you!
Best,

Coco

**Comment by hannehuygelier** [comment]
Dear Coco,

I don't think it is related to Psychopy Standalone, because I didn't install the standalone version. I installed Psychopy 1.84.2 using pip.

Best,
Hanne

**Comment by hannehuygelier** [comment]
Dear people who are stuck on this issue, 

I found the solution. There was some bad Yaml formatting in the file called "supported_config_settings.yaml" in the folder: C:\Python27\Lib\site-packages\psychopy\iohub\devices\eyetracker\hw\smi\iviewx. 

I deleted the spaces after each line in the yaml file and the last two enters after the last line and that fixed this issue.

Best,
Hanne

**Comment by peircej** [comment]
Well done Hanne. If you like you could submit a "pull request" to have this fixed in the project:

* create a fork of the psychopy respository
* edit the file in your fork (for a simple change like this you can probably use the built-in online editor)
* commit your change with a message like "BF: fix yaml formatting for SMI eyetrackers"
* create new pull request so we can use it

This way we keep track of who finds/fixes problems (i.e. you get credit for your contribution). If you prefer not then I can obviously make the change myself

**Comment by cocoggfr** [comment]
Dear Hanne,

Thank you very much for sharing your solution. Unfortunately this doesn't seem to work for me.
I will try to find out if something else can cause the same problem and post here asap if it is the case.

We can either keep this issue open or I can open a new one. Let me know what you prefer!

Coco

**Comment by hoechenberger** [comment]
@cocoggfr, if @hannehuygelier submits a pull request, you would then be able to check again with the exact YAML file she used. 

@hannehuygelier, if you feel that pull request stuff all too complicated, you could still help @cocoggfr by simply pasting the contents of your YAML file into a paste bin (e.g., http://pastebin.com) and sharing the URL with us. Thank you very much!

**Comment by cocoggfr** [comment]
Hello @hoechenberger , hello Hanne,

As I explained before, I didn't have the problem with the manually install version of PsychoPy1.84.
What could be useful though as it might be a 1.84.02 standalone version problem would be for @hannehuygelier (if you have time to do it, shouldn't take more than 15 minutes) to install the 1.84.02 standalone version of PsychoPy and try to run your script.
I couldn't get mine to run with this latest standalone version,  but after reading this https://discourse.psychopy.org/t/select-tracker-demo-for-smi-eyetracker-not-working-in-version-1-84-2-worked-in-1-82-01/1673 , I tried with PsychoPy 1.82.01 standalone version and my script worked. So it might be a 1.84.02 standalone version, but it would be nice to have the confirmation.

I am more than happy to help digging up this problem next week! (won't have time today and tomorrow)
Best,

Coco

**Comment by hannehuygelier** [comment]
Sorry for the late response! I tried to fix it and did what John said. I hope I did it the right way and that it works for other people now.

**Comment by hoechenberger** [comment]
I cannot seem to find a related pull request, is this issue really resolved?

**Comment by hoechenberger** [comment]
Ah I see. @hannehuygelier, you only committed to your "private" fork of the PsychoPy repository. To get the changes included "upstream", you must create a pull request. To do so, go to https://github.com/hannehuygelier/psychopy and click on "New pull request". Thanks!
