### ISSUE TITLE
pip installation does not install requirements

### ISSUE THREAD

**Issue by arokem** [psychopy/psychopy#1375]
Might be just a matter of adding an `install_requires` field here: https://github.com/psychopy/psychopy/blob/master/setup.py#L59

**Comment by peircej** [comment]
Yes, I've never set it up to do that for a few reasons, but they're all up for change:

- the requirements are many - does the user want us to make *that many* installations for the one package that they requested? Also, one of the not-really-strict dependencies on Mac (pyobjc) takes *ages* to install although we might limit it to a subset of the full objc package
- the requirements are complicated:
  - many are not strict requirements but nearly always needed. What to do then? e.g. technically you don't even need pyglet, depending on what you want to do
  - many are platform specific (although I guess we could have different wheels for different platforms to get around this? Or no wheels at all so the pip setup.py gets run on the intended platform?)

- not all the dependencies are pip-installable. To be fair this reason used to be the biggy (it used to be about half the packages that needed a different installer) but it's getting weaker. I think now it might just be wxPython and pyo that can't install from pip. And wxPython should be able to in the new Phoenix re-write

As a result of the above I've just gone with providing the requirements.txt so you can do 
`pip install -r requirements.txt`
which doesn't seem *too* bad, but I'm happy to see the full (minimal?) requirements in setup if that's what people want

**Comment by arokem** [comment]
I've gotten really spoiled, so when I want some software, I just type `pip install foo`, cross my fingers, and wait to see whether that would just work. 

So - regarding the first point: yes - I think that if a potential user types `pip install foo`, that user usually hopes that foo, together with all its myriad dependencies appear on their machine. Even if it means sacrificing a bit more disk space and waiting a few minutes. If that's possible, that would be what I would expect.

That said, the complicated requirements are more of a concern -- I for one couldn't install wx on my mac laptop using pip. Looking through the docs, I saw that the story is more complicated, and ended up installing the app from the dmg, which works just fine for my current needs.

Either way, this is just my opinion, and feel free to close this issue. Thanks!

**Comment by peircej** [comment]
> waiting a few minutes

Yes, for pyobjc that's about 30 minutes though, hence my concern. For the rest I think it's fine

I'm hoping the other depends will get easier - they have been doing consistently for some time - so I'll leave this open and hope it gets done one day!

**Comment by cbrnr** [comment]
I think PsychoPy should automatically install its hard dependencies (i.e. everything that's required when I type `import psychopy`). I just tried this with the current master on Python 3 on a Mac, and the hard dependencies are `configobj` and `future`.

Of course there are more dependencies if you import other modules such as `psychopy.visual` or `psychopy.core`, and these dependencies could also be added depending on how necessary they are. But we should start with the two modules as soon as possible and discuss what to do with the not-so-hard deps later. I can take care of this in a PR if you want @peircej.

**Comment by cbrnr** [comment]
Oh I see that many dependencies have already been added to `setup.py` - so this issue could be closed then I guess?
