### ISSUE TITLE
Windows: Freetype 32bit missing in standalone install (TextBox not working)

### ISSUE THREAD

**Issue by EruIluvatar** [psychopy/psychopy#1383]
Hi

I had trouble getting the textbox_simple demo working, resulting the following error message:
```
FreeType import Failed: Freetype library not found
Traceback (most recent call last):
  File "C:\Users\stbo\Desktop\temp\textbox_simple.py", line 29, in <module>
    units='norm',
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.84.2-py2.7.egg\psychopy\contrib\lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.84.2-py2.7.egg\psychopy\visual\textbox\__init__.py", line 376, in __init__
    self._font_name = fm.getFontFamilyStyles()[0][0]
IndexError: list index out of range
```

Turns out the freetype.dll is missing in the Windows 1.84.2 Standalone installer.
I needed to install a 32bit version of the library in `C:\Program Files (x86)\PsychoPy2\` (or `C:\Program Files (x86)\PsychoPy2\DLLs`) and the demo worked.

The tricky thing was realizing the 32bit version is needed and finding a precompiled download (it's not available on `http://gnuwin32.sourceforge.net/packages/freetype.htm`).
I got mine from `http://download.cnet.com/Freetype-32-bit/3000-2316_4-75824465.html` but its not really a good idea to rely on 3rd parties to download a library...

So could you please add it to the standalone installer?

**Comment by peircej** [comment]
Ah. I think this used to be included by the matplotlib installer but presumably not anymore (maybe when they switched to pip installs). OK, I'll add it to my dev machine DLLs folder so that it will be included in future.
