### ISSUE TITLE
No xlwt in psychopy again

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#1400]
xlwt is not found in recent (1.85) psychopy.
This was fixed in #745 so it seems to be a regression.

**Comment by peircej** [comment]
I just tried installing this using pip and although it installed I couldn't get it to import properly.

But... xlwt is only to write xls files, which are surely obsolete, no? Can't we use xlsx by now?

**Comment by mmagnuski** [comment]
Yes, I wouldn't say that this is an important fix. And adding path (in psychopy gui) to xlwt copied from conda install is easy and works well for me. I can also step into 21 century and start using xlsx files :)

**Comment by peircej** [comment]
hahah, OK, I'll close this but thanks
