### ISSUE TITLE
Cannot find additional package installed

### ISSUE THREAD

**Issue by wizardone** [psychopy/psychopy#1405]
Hi all,
I just started to use psychopy, installed it via the `.dmg`. Everything runs ok, until I decide to install a package with `pip`. For example I wanted to try and integrate `tobii_research`, however I get:
```
import tobii_research
ImportError: No module named tobii_research
```
If I am trying to achieve something that is not supposed to happen you can stop reading now :)

From what I saw psychopy comes with its own version of Python (used to have 2.7.13 on my machine),  currently I have only `2.7.12`, installed from here: https://www.python.org/downloads/mac-osx/ which is the same version PsychoPy comes with.
```shell
python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
```

```shell
pip list
 pip (8.1.1)
 setuptools (20.10.1)
 tobii-research (1.0.1)
```

I haven't used python so far, but it seems like a pretty straight forward setup, what am I missing? I went through the whole documentation, but was not able to find anything on the subject. I am sorry if this is a rather stupid question, but I am not sure how to proceed. Would appreciate if you can just point me in the right direction :)

**Comment by hoechenberger** [comment]
> If I am trying to achieve something that is not supposed to happen you can stop reading now :)

Ok I stopped. ;)

No seriously, PsychoPy comes with its own Python installation. If you simply install something using `pip` on the command line, you're going to make these packages available to the _system Python_, not to the _PsychoPy Python_. You will want to add your package to `/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/`; there's an (outdated) howto available at http://www.psychopy.org/recipes/addCustomModules.html

**Comment by wizardone** [comment]
@hoechenberger Thank you for the response. I expected something like this to be the reason in the first place but had to ask :)
I honestly never saw this section of the documentation, don't know how I missed it. Anyways, I believe your answer absolutely closes this issue, hope the docs are **not** that outdated and I will be able to install the packages. Thank you once more.
🙇

**Comment by hoechenberger** [comment]
@wizardone Please let us know if you manage to get this to work, and how difficult and intuitive to find the docs to understand.

**Comment by wizardone** [comment]
@hoechenberger Sure, I will give it a try this evening EET and write back here.

**Comment by wizardone** [comment]
Unfortunately I wasn't able to succeed. However I was able to crash the whole application :) Now every time I start it I get PsychoPy error. This seems to be caused by me trying to add a new component path. Even after reinstalling I still get the error and cannot get into the preferences to fix it. Probably the various configuration options continue to live somewhere within the file system?
Anyways I did not have much time today to try and find a solution, but I need one, so I will continue tomorrow. Will update you on my progress.

**Comment by peircej** [comment]
If the app doesn't start due to broken prefs see this guide: http://www.psychopy.org/troubleshooting.html

**Comment by wizardone** [comment]
Yes, this fixed the startup. Still I am not able to use the additional package. For example:
I create a file called `extra.pth` and put it `/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7`
If I read the documentation correctly I need to just add the path to the folder where the desired package is located, is this correct?
If I install the package with pip it goes to:
`/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tobiiresearch`

So I just need to paste the path in the `extra.pth` file?

If I add the path to the `path` in Preferences -> General I get the following error:
```python
        raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the CheckBox object has been deleted, attribute access no longer allowed.
```

I am sorry if my questions seem a bit primitive, it is just that the documentation does not make it very easy for me to grasp

**Comment by hoechenberger** [comment]
Can you try to remove the `pth` file, remove the `path` entry you added in the prefs, and copy the entire directory `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tobiiresearch` to `/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/tobiiresearch`?

**Comment by wizardone** [comment]
@hoechenberger Thank you, it seems that this actually does the trick. At least the project importing `tobiiresearch` does not crash.
I will verify this later today and update you.

**Comment by hoechenberger** [comment]
@wizardone Any news on this one? :)
