### ISSUE TITLE
unble to run (gui) git version on Fedora 24

### ISSUE THREAD

**Issue by umarbrowser** [psychopy/psychopy#1408]
i am working with my git version and this morning i found this error 

[root@localhost ~]# python /psychopy-master/psychopy/app/psychopyApp.py
Traceback (most recent call last):
  File "/root/incf_gsoc2017_psychopy/psychopy-master/psychopy/app/psychopyApp.py", line 10, in <module>
    from psychopy.app._psychopyApp import PsychoPyApp, __version__
ImportError: No module named psychopy.app._psychopyApp

i try $ export PYTHONPATH = "/root/psychopy-master/"
i all ready add my pythonpath to psychopy path

**Comment by umarbrowser** [comment]
oh thats why i love google i have found the solution i just found the simple way i start by editing my .bashrc script in the Home directory and add those lines:


PYTHONPATH = "$ {PYTHONPATH} : /usr/lib/python2.7/site-packagesed/" export PYTHONPATH

alias psgui="/root/psychopy-master/psychopy/app/psychopyApp.py"

and after that i run [root@localhost ~]# export PYTHONPATH="/root/psychopy-master/"
to export the python path and [root@localhost ~]# psgui
to run the (Gui) with run perfectly 
![screenshot from 2017-04-30 11-24-09](https://cloud.githubusercontent.com/assets/16499126/25563625/c868ef68-2d97-11e7-9f33-7c5892db10c5.png)

**Comment by hoechenberger** [comment]
You can simplify this even further when using pip:
`pip install -e /path/to/psychopy`
(see https://pip.pypa.io/en/stable/reference/pip_install/#install-editable)

As a side note, you should not work as root during development.

Closing as resolved.

**Comment by umarbrowser** [comment]
ok thanks
