### ISSUE TITLE
Unresolved reference and assignments to keywords in eyetracker.py

### ISSUE THREAD

**Issue by cbrnr** [psychopy/psychopy#1410]
The module `eyetracker.py` seems to contain some errors. First, `KeyboardPressEvent` cannot be resolved on line 607 since this symbol is not available at the specified location (I haven't actually executed this code, but PyCharm spits out this error message).

Second, line 1036 reads:

    auto_pace = dict (True=1, False=0, Yes=1, No=0, On=1, Off=0)

You cannot assign values to the literals `True` and `False` in Python 3 anymore (and even though this was possible in Python 2, it was never a good idea). Any suggestions/preferences how to fix this? This is relevant for #1407 in order to make it compatible with Python 3.

**Comment by mdcutone** [comment]
A possible solution would be to use all-caps TRUE and FALSE. Or define the dictionary as such:

`auto_pace = {"True": 1, "False": 0, ... }`

**Comment by cbrnr** [comment]
Right, but it would be good to know how these changes influence the functionality of the underlying iohub eyetracking module (or in other words, if we change the dict to use all string keys, where do we need to make further changes).

**Comment by peircej** [comment]
I think we need @isolver to comment on why this was needed

**Comment by hoechenberger** [comment]
Which `eyetracker.py` module are you referring to? There are multiple files with that name in the repository.

**Comment by cbrnr** [comment]
I was referring to `psychopy/iohub/devices/eyetracker/hw/smi/iviewx/eyetracker.py`.

**Comment by hoechenberger** [comment]
The change proposed by @mdcutone should not lead to any functional differences. In Python 2.7, we have:
```python
In[5]: auto_pace = dict(True=1, False=0, Yes=1, No=0, On=1, Off=0)
In[6]: auto_pace
Out[6]: 
{'False': 0, 'No': 0, 'Off': 0, 'On': 1, 'True': 1, 'Yes': 1}
```
So the resulting dictionary would be identical with the approach @mdcutone proposed. For the record, this is Python 3:
```python
In [1]: auto_pace = {'False': 0, 'No': 0, 'Off': 0, 'On': 1, 'True': 1, 'Yes': 1}

In [2]: auto_pace
Out[2]: {'False': 0, 'No': 0, 'Off': 0, 'On': 1, 'True': 1, 'Yes': 1}
```

**Comment by cbrnr** [comment]
Alright, I didn't even know that you can create a dict with keyword arguments :smile: - OK, so this is settled then. What about the other issue concerning the unresolved import of `KeyboardPressEvent`?

**Comment by mdcutone** [comment]
Since keyword arguments follow variable naming conventions (must be alphanumeric, etc.), keywords passed to `dict()` are always coerced into strings. Using literals on the left-hand side of `=` will likely be evaluated as an expression and not a keyword, therefore literals cannot be defined as keys using the `dict(**kwargs)` syntax.
