### ISSUE TITLE
EnvelopeGrating component doesn't set appropriate default value of parameters

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#1415]
EnvelopeGrating component shows following error messages when parameters are set to 'set every frame' or 'set every repeat'.

> I don't know the appropriate default value for a 'blendmode' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'contrast' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'moddepth' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'beat' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'envori' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'envelope' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'envphase' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'envsf' parameter. Please email the mailing list about this error
I don't know the appropriate default value for a 'carrier' parameter. Please email the mailing list about this error

I think that default values of these parameters should be added to getInitVals() in psychopy/app/builder/components/\_\_init\_\_.py, or should be set in writeInitCode() in psychopy/app/builder/components/envelopegrating/\_\_init\_\_.py.

**Comment by hsogo** [comment]
I think that default values of parameters of officially-supported components should be added to getInitVals() in principle, but on the other hand I feel that parameters such as envori, envsf, ... might be too specific to EnvelopeGrating component to add to getInitVals(). What do you think?

**Comment by peircej** [comment]
Yes, I guess this is tricky. The idea of `getInitVals()` is to have some sense of what the default value should be (a string, a value 0-1 etc) but it's true that we could end up with a long list of look-up values.
I don't think I have another solution at the moment except to add them

**Comment by hsogo** [comment]
At first I thought that appropriate default values can be known from arguments of __init__() function of components, but it was not easy.  Running following script, I found that parameter names are identical with arguments only in Aperture, Microphone, ParallelOut, RatingScale, Sound and Unknown components.

```
import psychopy.app.builder.experiment
import psychopy.app.builder.components
import inspect

exp = psychopy.app.builder.experiment.Experiment()
allComponents = psychopy.app.builder.components.getAllComponents()

componentNames = allComponents.keys()
componentNames.sort()

for component in componentNames:
    if component == 'SettingsComponent':
        continue
    print('\n----- ' + component + ' -----')
    object = allComponents[component](exp, 'parentName') # get parameters
    args, varargs, varkws, defaults = inspect.getargspec(allComponents[component].__init__) # get arguments
    
    paramNames = object.params.keys()
    paramNames.sort()
    argNames = args[3:] # first 3 args (self, exp, parent) don't have default values
    argNames.sort()
    
    if paramNames != argNames:
        print('Params only: {}'.format(list(set(paramNames)-set(argNames))))
        print('Args only: {}'.format(list(set(argNames)-set(paramNames))))
    else:
        print('OK')
```

Another solution is to make parameters hold initial values. Insert following codes at the end of psychopy.app.builder.experiment.Param.__init__() function (line 838 of psychopy/app/builder/experiment.py).

```
        self.initVal = val
        self.initValType = valType
```

Then, replace warning message of getInitVals() function (lines 292-294 of psychopy/app/builder/components/\_\_init\_\_.py) with following codes.

```
            params[name].val = params[name].initVal
            params[name].valType = params[name].initValType
```

I think that lines 254-289 are not necessary if this change is applied, but it needs to be tested.

**Comment by hsogo** [comment]
At the moment, I've fixed this problem by adding default values of these parameters to getInitVals().  Please see my pull request.
