### ISSUE TITLE
height = 0.15 in TextStim causes text not to be displayed in fullscreen mode

### ISSUE THREAD

**Issue by piotx** [psychopy/psychopy#1420]
After an upgrade to 1.85.1 there are some problems with height in TextStim in fullscreen or in windows with higher resolution (size=(1920, 1080)) mode.

OS: Windows 7 and Windows 8

The text stimulus is not displayed, if height is set to 0.2 or 0.15; The text is diplayed properly, if height is set to 0.1

minimal example:

```python
from psychopy import visual, core, event

win = visual.Window(fullscr=True)
// same problem with: win = visual.Window(size=(1920, 1080), fullscr=False)

o = visual.TextStim(win, text='o', pos=(0,0), height=0.2)

while True:
    if event.getKeys(keyList=["escape"]):
        core.quit()
    o.draw()
    win.flip()
```

**Comment by mmagnuski** [comment]
The same issue is here: #1385
Can you close this one and move your message there?
