### ISSUE TITLE
Windows standalone uninstaller does not clear \Users\$USER\AppData\Roaming\psychopy

### ISSUE THREAD

**Issue by davidt0x** [psychopy/psychopy#1449]
Just ran into a problem where configuration settings stored in \Users\\$USER\AppData\Roaming\psychopy
were causing issues after I upgraded from PsychoPy 1.84.12 to 1.85.1. Before deleting this folder the experiment I was running had different fonts and would not respond to mouse input. After deleting this folder the experiment ran as expected. Not sure what the issue was exactly but thought I would mention it in case others were experiencing something similar. Maybe the uninstaller should clear this directory though I could see why it does not.

**Comment by peircej** [comment]
That's weird> The folder should only have your prefs in it, and info about the previous files you loaded etc. I'd prefer not to delete it between versions if possible, or it would mean you losing your prefs on each upgrade.
Let's hold fire and see if others complain of the same problem occurring

**Comment by davidt0x** [comment]
I think I just figured out the issue. It seems that the window type in the preferences was set to pygame instead of pyglet. I was testing the program on different user accounts and they had different settings. This is my mistake, I will close the issue and thanks.
