### ISSUE TITLE
Add future to pip dependencies

### ISSUE THREAD

**Issue by cefn** [psychopy/psychopy#1471]
There is a line like...

```
from future import standard_library
```

...routinely used throughout Psychopy. However, future doesn't seem to be declared as a pip dependency anywhere I can see, including the manual instructions for explicitly bringing in dependencies at http://psychopy.org/installation.html 

Following https://discourse.psychopy.org/t/how-to-run-psychopy-after-pip2-install/2798 resolved the issue of installing and running 1.85 from Pip on Linux.

BTW Is it possible to configure the pip install to bring in all dependencies, (avoiding the need to install them manually) and perhaps install a binary link and maybe a menu file (the .desktop file) so that psychopy can be run from the desktop or console after just ```sudo pip install psychopy```?

**Comment by peircej** [comment]
Both parts of this are already done! :-)
It's just that they exist in the repository but have not yet been released. Currently if you download a copy of the repository, cd into that directory and do this (for a standard install):

    pip install .

or this (for a developer-install that can be edited):

    pip install -e .

Either of these should install all the necessary dependencies (including future)

**Comment by cefn** [comment]
Is there a chance of distributing the latest version to pip3? Given the version there is currently 1.84 and non-functional (won't even install) the cost of using it as a beta channel is fairly low, perhaps. People using Pip instructions would still get the stable version targeting Python2 and those explicitly using pip3 would get the testing version targeting Python3. 

It would be great to migrate to python3 version for some teaching coming up soon, given https://wiki.python.org/moin/Python2orPython3...

"In particular, instructors introducing Python to new programmers should consider teaching Python 3 first and then introducing the differences in Python 2 afterwards (if necessary), since Python 3 eliminates many quirks that can unnecessarily trip up beginning programmers trying to learn Python 2."

**Comment by peircej** [comment]
> Is there a chance of distributing the latest version to pip3? 

You mean PyPI? If you do mean pip3 (which installs things to Python3) then see separate answer below

> Given the version there is currently 1.84 and non-functional (won't even install) the cost of using it as a beta channel is fairly low, perhaps. 

1.85.2 is the current newest version on PyPI and I'm not aware of any not-installing problems

> It would be great to migrate to python3 version

The instructions I gave above to install from the repository version *will* install the same using pip3. I'm not going to release that to PyPI just yet. We've only just performed the code conversion and we need to test it before releasing

**Comment by cefn** [comment]
Raised the suggestion because I get the below results via pip3. (without targeting the downloaded repo) 

Because a regular pip3 install attempts to install an outdated version which cannot run against python3 anyway, I speculated it might be better to have an in-testing package come via a regular pip3 install, rather than a broken package.

I understand the wisdom of your suggestion to install via pip3 against repo sources to get a testing version for users like myself who are comfortable with the steps. However, making the in-testing unstable version available via Pip3 would be an advantage for some. For those people extracting a zip or downloading via git, and getting a console with the right working directory might be more of a challenge than running a generic pip3 install, (which doesn't require either of those steps). 

Perhaps you would like the broadest range of users and environments to test and provide feedback on the Python3 version? It certainly would make Python3 teaching with users on their own laptops much more accessible assuming our testing shows the environment is stable enough.

I'm basing this on the idea that you can differentiate between the versions distributed in the Python2 vs the Python3 channel in PyPI. The idea would be absolutely to leave the stable version in the Python2 channel. 

This may be a clueless suggestion which should be dismissed. I also recognise that the project has standards of its own which might mean the idea of a testing version in PyPI is unthinkable regardless of channel.

```
~ $ sudo -H pip3 install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages
~ $ sudo -H pip3 install psychopy
Collecting psychopy
  Downloading PsychoPy-1.84.2.tar.gz (11.6MB)
    100% |████████████████████████████████| 11.6MB 45kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_yi8wa5a/psychopy/setup.py", line 28, in <module>
        exec(vStr)
      File "<string>", line 42, in <module>
      File "/tmp/pip-build-_yi8wa5a/psychopy/psychopy/__init__.py", line 47, in <module>
        from psychopy.tools.versionchooser import useVersion, ensureMinimal
      File "/tmp/pip-build-_yi8wa5a/psychopy/psychopy/tools/versionchooser.py", line 19, in <module>
        from psychopy import logging, tools, web
      File "/tmp/pip-build-_yi8wa5a/psychopy/psychopy/web.py", line 13, in <module>
        import httplib
    ImportError: No module named 'httplib'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_yi8wa5a/psychopy/

```

**Comment by peircej** [comment]
As I say, we've only just converted the code to Python3. It isn't ready for the "broadest range of users". It should only be used by enthusiast developers for now, not general users. In my experience, creating releases for people to play with, even with strong and explicit warnings that this is not production-ready, results in people using it and getting stuck. I've been burnt too often and this is not ready for that yet.

I'd rather have Python3 fail catastrophically (as you're finding) than have it appear to work but introduce some subtle bug in experiments, that people then run without noticing/testing thoroughly
