### ISSUE TITLE
Trial csv not written when 'esc' key pressed

### ISSUE THREAD

**Issue by CRiddler** [psychopy/psychopy#1497]
I'm testing an experiment (very simple set up) that, when run in its entirety is perfectly fine. It logs everything, and my output is written as expected. However whenever I interrupt the experiment via the 'esc' key I get this output message:

`Exception RuntimeError: RuntimeError('sys.meta_path must be a list of import hooks',) in <bound method ExperimentHandler.__del__ of <psychopy.data.experiment.ExperimentHandler object at 0x112387550>> ignored`

Which, to my knowledge, appears as if the ExperimentHandler.__del__ method is being skipped over- resulting in no output `.csv`

This is on a fresh standalone install of psychopy 1.85.3 on a Mac OS X El Capitan 10.11

Edit:
Forgot to mention that this experiment was built completely with the psychopy builder gui- I have not used to coder to create this experiment.

**Comment by CRiddler** [comment]
Did some poking around and found out that this bug has to do with an issue from the pickling the ExperimentHandler class and the python 2 to 3 compatibility changes. 

Prior to the change, python 2x's cPickle module was used- however python 3x only has pickle (which is the equivalent of cPickle to my understanding, pickle was essentially replaced by cPickle). However, to make it 2/3 compatible `import cPickle` was replaced with `import pickle`. This means in python2 the regular `pickle` is being used, while in python3 `cPickle` is being used under the hood. The reason this makes breaking difference is that python2 `pickle.dump()` uses a default protocol of 0- which is "… the original ASCII protocol and is backwards compatible with earlier versions of Python" (see python2.7 pickle module on the docs). This protocol encounters an error when attempting to pickle the ExperimentHandler object- more testing is required to dive into the specifics as to why this is an issue though.

However to remedy this error we can do either of the following inside of `experiment.py`
* replace `import pickle` a version dependent importation of cPickle for py2, or pickle for py3-
    try:
        import cPickle as pickle
    except ModuleNotFoundError:
        import pickle as pickle
* replace line 333 `pickle.dump(self, f)` with `pickle.dump(self, f, pickle.HIGHEST_PROTOCOL)`

I'm more than willing to make a pull request for these, but I figured since I reported this as an issue/bug I'd post it here first.

**Comment by peircej** [comment]
Ah, OK. Thanks for digging around there.

I'm still not entirely sure I understand why that would affect things part-way through a run but not at the end. But I agree that we've potentially introduced an incompatibility. I guess the try...except... option makes sense to be on the safer(?) side, even though the `pickle.HIGHEST_PROTOCOL` seems more elegant. I guess I don't have a strong opinion either way! ;-)

**Comment by peircej** [comment]
Oh, wait, maybe it's just that at the end of the script we force a csv-write before the pickle file is written. Out of interest, is it possible your experiment contains unicode characters anywhere?

**Comment by CRiddler** [comment]
I was just thinking the same thing! the csv is written before the pickle if the experiment runs successfully. Whereas if they are saved via the object being garbage collected, the pickle saves first.

I stopped using my own experiment and switched to the "branching.psyexp" but for some reason the issue persists when not using either of the above two fixes.

* Experiment is aborted via 'esc' key- exception appears, no .csv and partial .psydat file that can not be read back via `filetools.fromFile()`
* Experiment runs all the way though- csv file, and a full .psydat file is outputted that can be read back via `filetools.fromFile()`

With the fix- the .psydat file is always able to be read back in via `fromFile()` regardless of if the experiment went all the way through or was aborted.


On a separate note and equally interesting note-
If an explicit `del(thisExp)` is called before the `core.quit()` on an experiment abortion (without the aforementioned fix in place) the pickle and .csv are written properly.

This one really has me scratching my head at why the fix works.

**Comment by CRiddler** [comment]
Another observation-

without the above fixes. If at the end of a successfully run experiment, the explicit 

# these shouldn't be strictly necessary (should auto-save)
thisExp.saveAsWideText(filename+'.csv')
thisExp.saveAsPickle(filename)
logging.flush()
# make sure everything is closed down

Lines are all deleted or commented out (forcing the data dump to rely on garbage collection via core.quit()) then the error returns!

So it seems like it is an issue with relying on garbage collection to delete the ExperimentHandler object. Still not sure as to exactly why using a higher protocol for the pickle dump fixes this though.

**Comment by hoechenberger** [comment]
> replace import pickle a version dependent importation of cPickle for py2, or pickle for py3-
> try:
> import cPickle as pickle
> except ModuleNotFoundError:
> import pickle as pickle

I would rather we used the value of `psychopy.constants.PY3` in an `if` statement here instead of `try / except`, since it's more explicit. :)

**Comment by hoechenberger** [comment]
> So it seems like it is an issue with relying on garbage collection to delete the ExperimentHandler object. Still not sure as to exactly why using a higher protocol for the pickle dump fixes this though.

Maybe it just saves quicker ;)

**Comment by hoechenberger** [comment]
Well okay so then the problem is simple, as you already disovered: The Builder calls `core.quit` if `ESC` is pressed. `core.quit()`does not explicitly call `ExperimentHandler.__del__()`:

```python
    # check for quit (the Esc key)
    if endExpNow or event.getKeys(keyList=["escape"]):
        core.quit()
```

The solution would be to change the above lines to something like:
```python
    # check for quit (the Esc key)
    if endExpNow or event.getKeys(keyList=["escape"]):
        del thisExp
        core.quit()
```

Regarding the "correct" end of the script -- the Builder inserts the following lines:
```python
# these shouldn't be strictly necessary (should auto-save)
thisExp.saveAsWideText(filename+'.csv')
thisExp.saveAsPickle(filename)
logging.flush()
# make sure everything is closed down
thisExp.abort()  # or data files will save again on exit
```
I think we're saving explicitly here because `ExperimentHandler.abort()` does nothing except
```python
        self.savePickle = False
        self.saveWideText = False
```
I think the idea is the avoid re-saving when opening the pickle. However, I think we should deal with this in `tools.filetools.fromFile()` instead. Currently, we do:
```python
    with open(filename) as f:
        if filename.endswith('.psydat'):
            contents = pickle.load(f)
            # if loading an experiment file make sure we don't save further
            # copies using __del__
            if hasattr(contents, 'abort'):
                contents.abort()
```
I believe instead of calling `abort()` here, we should manually set the two attributes to `False`.

Then we could change the last lines of Builder scripts from
```python
# these shouldn't be strictly necessary (should auto-save)
thisExp.saveAsWideText(filename+'.csv')
thisExp.saveAsPickle(filename)
logging.flush()
# make sure everything is closed down
thisExp.abort()  # or data files will save again on exit
```

to

```python
logging.flush()
del thisExp
```

**Comment by hoechenberger** [comment]
A note on semantics: The current approach in the Builder scripts doesn't make much sense to me anyway -- if we shutdown successfully, we call `abort()`. Seems very counter-intuitive!

**Comment by peircej** [comment]
1. I agree that an explicit check for PY3 from psychopy.constants may be better than the `try...except` (more explicit and easier to remove the clunky code later on, when we eventually drop support for py2).

2. I also see the advantage of adding `del thisExp` into `core.quit()` partly because it will encourage `thisExp` to be garbage collected earlier than other libs. We sometimes see error messages occurring in `__del__` methods simply because the libs the objects depend on was cleared up before the object themselves. :-/ I guess the problem is that we'd need to keep track of the names of any experiment handlers (because the experimenter might not call it thisExp). We do something like that for Window (tracking all current windows that have been created) so could do something similar for experiments.

3. The question of the final piece of code is more tricky. We previously didn't have the explicit save lines and relied on the `__del__` method working, but sometimes it didn't and data were lost! Garbage collection routines are a little fragile (as you note above) and I'd rather have some extra lines here even though they shouldn't be necessary. Even calling `del thisExp` doesn't necessarily cause `__del__` to be called (if someone accidentally creates a circular reference with the experiment handler).

4. Yes, abort() is simply a way to prevent re-saving and shouldn't strictly be necessary (and seems counterintuituve). The problem is that some users may not load the psydat file using `fromFile()` but using their own pickle loading(?) in which case they'll start doing auto-saving again. We could simply execute the two lines of code that abort() is doing after each `save` line? Slightly more lines but more clear what's going on?

**Comment by hoechenberger** [comment]
> We could simply execute the two lines of code that abort() is doing after each save line? Slightly more lines but more clear what's going on?

We would have to execute them _before_ actually saving :) And restore the original state afterwards. This should happen in the `saveAsPickle() / saveAsWideText()` methods.

**Comment by hoechenberger** [comment]
Wait a second, we already do that!
https://github.com/psychopy/psychopy/blob/e4052917eb2912f3b4573e908962b15328f70727/psychopy/data/experiment.py#L310

**Comment by peircej** [comment]
Oh, yes. I sometimes forget the problems I've already solved! ;-)
The remaining `thisExp.abort()` simply prevents us from doing the save twice at the end of the study, rather than altering the state of the saved file at garbage collect.

**Comment by hoechenberger** [comment]
> The remaining thisExp.abort() simply prevents us from doing the save twice at the end of the study(once explicitly and once implicitly), rather than altering the state of the saved file at garbage collect.

To get around this, we could potentially explicitly `del thisExp`, like I said earlier; would solve all problems I guess :)

**Comment by peircej** [comment]
> To get around this, we could potentially explicitly del thisExp, like I said earlier; would solve all problems I guess :)

As I say, `del thisExp` does **not** necessarily run `thisExp.__del__()`. It merely decrements the reference count by 1 and with an erroneous circular reference somewhere this can mean that the object never gets deleted.

**Comment by hoechenberger** [comment]
Right, thanks for reminding me again (sometimes reading isn't my strength ;))

So, this brings is back to this issue, I guess: #1083

**Comment by hoechenberger** [comment]
You know, maybe we should also think about using context managers. I believe situations like this are one of the reasons why these things were developed in the first place.

**Comment by CRiddler** [comment]
Just catching up on all of this talk now, but in my opinion there's just an inherent issue relying on \__del__ to dump collected data to file(s). This seems like it should be something thats designed for a context manager, but an `ExperimentHandler` would require a chunk of new code. Regardless, I think there should be an explicit `ExperimentHandler.close()` method that does the same as the current `ExperimentHandler.\__del__()` (in that it saves all the appropriate files, but then should also turn the save state to false). 

    class ExperimentHandler(_ComparisonMixin):
        def __enter__(self):
            return self
        def __exit__(self):
            self.close()
        def close(self):
            \#Save all the files, then call abort to ensure \__del__ doesn't attempt to overwrite
            if self.dataFileName not in ['', None]:
                if self.autoLog:
                    logging.debug(
                        'Saving data for %s ExperimentHandler' % self.name)
                if self.savePickle == True:
                    self.saveAsPickle(self.dataFileName)
                if self.saveWideText == True:
                    self.saveAsWideText(self.dataFileName + '.csv', delim=',')
            self.abort()
            self.autoLog = False

However implementing a context manager from the builder interface is another ordeal entirely since it adds yet another level of indentation. Context manager idea aside, we can use the `self.close()` method before calling core.quit() to ensure that the `ExperimentHandler` is cleaned up properly. However we still maintain the `\__del__` method for backwards version compatibility?

Lastly, I propose we add a `_instances = weakref.WeakSet` to the ExperimentHandler as a class variable. Then inside of `\__init__` each time a new object is initialized, we add a reference  to the weakref.WeakSet variable. The inside of core.py we can import the ExperimentHandler class and call its `.close()` method on all active ExperimentHandler instances, thus dumping the data out BEFORE we start shutting down threads and using `sys.exit(0)`

Sorry for throwing 10 million suggestions at you guys, but I think these are all possibilities that should be discussed!

**Comment by peircej** [comment]
Yes, exactly. We shouldn't _rely_ on `__del__` methods, but they're useful as an extra option.

I agree on a list of weak refs. For Window I stored this in core (I think) but storing it as a class variable is a neat solution too. :-) That would allow core.quit to have:
``` python
for thisExp in psychopy.data.Experiment._instances:
    thisExp().close()
``` 
The only downside I can see is that this means psychopy.core needs to import data, and I was trying to reduce the things that core necessarily imports. Otherwise, that all sounds good (in addition to the PY3 check and cPickle decision, where this all started).

I don't like the Context Handler for the sake of this. They're great for a few lines but not for the entirety of a large script like this.

**Comment by CRiddler** [comment]
I agree with your view on the context manager… although it definitely is the purpose here, in order to properly capture the experiment inside of the context, nearly the entire script (save for the imports and setting up of specific variables) would need to be written inside of the `with` statement- which is not pretty to look at.

As for the rest of this discussion, I think you stated exactly how I had it envisioned. I'll go ahead and make a PR with those above changes, and we can go from there?
* implement `_instance` weakref class variable for the `ExperimentHandler` class
* create a `.close()` fxn for `ExperimentHandler`
* replace the the innards of `__del__` with `self.close()` to make sure our code is DRY
* Preface the `core.quit()` fxn with a for loop that calls `.close()` on each `ExperimentHandler` object.

**Comment by CRiddler** [comment]
Recommenting on this since I had an idea this morning.

How come we aren't using `atexit` to register `self.close()` in the ExperimentHandler's `__init__`. This should ensure that each ExperimentHandler's close method is called prior to the rest of garbage collection. This would also circumvent the need to use a weakref set to keep track of each ExperimentHandler instance and manually close out of them in `core.py` (which allows us to get rid of the import we added into core.py)

@peircej @hoechenberger thoughts on this?

**Comment by hoechenberger** [comment]
> How come we aren't using atexit to register self.close() in the ExperimentHandler's __init__.

I would assume this is the cleanest solution; I brought this up [earlier](https://github.com/psychopy/psychopy/issues/1497#issuecomment-326572953), but didn't follow up. I would very much like to see the `atexit()` approach being implemented.

**Comment by CRiddler** [comment]
I played around with `atexit` in my psychopy a couple days ago. Everything seemed to clean up nicely when I deleted the manual close calls from `core.py` and added `atexit.register(self.close)` at the end of ExperimentHandler's `__init__`

I agree that this does seem like the cleanest solution though. If we want to go ahead and change it, I can submit a PR deleting the previous fix and implementing this one on Monday.

**Comment by hoechenberger** [comment]
> If we want to go ahead and change it, I can submit a PR deleting the previous fix and implementing this one on Monday.

This would be great IMHO. What do you think, @peircej? :)

**Comment by peircej** [comment]
My hunch is that, yes, this would be a great idea. Caveat is that I don't currently know much about `atexit()` so, whereas I've learned some of the "gotchas" of `__del__` methods over the years I don't yet know the potential pitfalls in atexit. 

One of the problems with garbage collection is that you don't really get to specify the order in which things are collected. e.g. if `sys` has been collected and then a class tries to use it in its __dell__ method you get an error (which might be the root of the error in @CRiddler's OP). My assumption is that `atexit()` gets run before garbage collection so might help.

This can't be used *instead* of the `__del__` methods. We still need these in case something gets deleted during a run, but I think it's useful as an additional measure, essentially to ensure that some of these objects are closed before the rest of the globals.

**Comment by CRiddler** [comment]
So I think we're all in agreement. And to answer your concerns @peircej I think its still in our best interest to keep the `.close()` class method and simply have `__del__` call `self.close()`. This way we can also use `self.close()` to register in `atexit` and have it be run before garbage collection. I'll get working on a PR for this, shouldn't take long at all.
