### ISSUE TITLE
OpenCV playback of movies giving type error float in 1.85.03

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#1509]
Hi there,  

I'm currently running PsychoPy 1.85.03 on Windows 7, where i'm getting the attached error message each time I run a movie file using the "opencv" playback.

I'll try and dig a bit further next week - but was wondering if anyone has seen this before and know how to resolve?

Many thanks,

Frank
![opencv-error](https://user-images.githubusercontent.com/2048377/30220436-4ed5c4dc-94b7-11e7-91c7-4ef513d93494.PNG)

**Comment by CRiddler** [comment]
It appears that the issue stems from at least one of the inputs into `numpy.zeros()` is a float.

    >>> np.zeros((1.0, 5, 7), dtype=np.uint8)
    Traceback (most recent call last):
        File "<input>", line 1, in <module>
    TypeError: 'float' object cannot be interpreted as an index

The full line in question is:

    `self._numpy_frame = numpy.zeros((self._video_height, 
                                      self._video_width,
                                      self._video_frame_depth),
                                      dtype=numpy.uint8)`

A few lines above this, `self._video_frame_depth` is hard coded to 3, which means this isn't the source of our float issue, which means that `self._video_width` or `self._video_height` which are both gotten via opencv are being returned as floats. 

The `self._video_width` and `self._video_height` are defined as follows:

    self._video_width = self._video_stream.get(
            cv2.CAP_PROP_FRAME_WIDTH)
    self._video_height = self._video_stream.get(
            cv2.CAP_PROP_FRAME_HEIGHT)

On my psychopy if I enter the following commands:
    
    >>> cap = cv2.VideoCapture(0)
    >>> cap.get(cv2.cv.CV_CAP_PROP_FRAME_WIDTH)
    1280.0
    >>> cap.get(cv2.cv.CV_CAP_PROP_FRAME_HEIGHT)
    720.0

They are in fact returned as floats, confirming my suspicions. A fix should be to  wrap both self._video_width and self._video_height inside of `int()` (when we define them) to ensure that they are integers and not floats.

I'll submit these changes as a PR, but if you want to change these inside your copy of psychopy, this should solve the issue you're experiencing.

**Comment by frankgasking** [comment]
Ah, that's brilliant - thanks CRiddler for the explanation and diagnosis.  

I'll give that a try first thing on Monday.  As we are fixing on 1.85.03 for the academic year, i'll see if we can push out just the movie2.py file with the fix for now and keep a note on how to fix if it crops up.
