### ISSUE TITLE
Error with event.mouse.getPos() in standalone version 1.85.3

### ISSUE THREAD

**Issue by noahmotion** [psychopy/psychopy#1518]
I just upgraded standalone to version 1.85.3, and I get the following error when I try to use the following code (`win` is a `visual.Window()` object):

    mouse = event.mouse(win=win)
    mouse.getPos()

    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/event.py", line 558, in getPos
    TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

This worked fine in version 1.85.1. This is on a Macbook Air with OS Sierra (10.12.6), for what it's worth.

**Comment by hoechenberger** [comment]
Please provide a minimal working example. Thanks.

**Comment by noahmotion** [comment]
This is from code generated originally by a gui-designed experiment. It runs fine in 1.85.1, and it gives me the error above in 1.85.3.

    from psychopy import visual, event
    win = visual.Window(size=(1440, 900), fullscr=True, screen=0, allowGUI=True, allowStencil=False, monitor='testMonitor', color=[0,0,0], colorSpace='rgb', blendMode='avg', useFBO=True)
    mouse = event.mouse(win=win)
    mouse.getPos()

**Comment by hoechenberger** [comment]
This is still not a working example. `event.mouse` does not exist; I had to change it to `event.Mouse` to get the script running.

I cannot seem to reproduce this error with 1.85.3 on macOS 10.12.6 with
`Python 2.7.13 :: Anaconda 4.3.0 (x86_64)`. How do you invoke Python to run the script?

**Comment by hoechenberger** [comment]
Also, are you sure you are running 1.85.3? In this version (as least the tagged version), line 558 of `event.py` does not contain a division operation...

**Comment by hoechenberger** [comment]
Could also be that something when wrong with the update procedure. Could you try fetching a fresh install of 1.85.3 and try again?

**Comment by noahmotion** [comment]
Sorry about the non-capitalized `mouse` before. I just re-downloaded standalone PsychoPy 1.85.3, and in Coder shell, I did this:

    from psychopy import visual, event
    win = visual.Window(size=(500,300),fullscr=False)
    mouse = event.Mouse(win=win)
    mouse.getPos()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/Applications/PsychoPy2 1.85.3.app/Contents/Resources/lib/python2.7/psychopy/event.py", line 558, in getPos
    TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

**Comment by noahmotion** [comment]
Also, yes, I first noticed this error after trying to run an experiment by pressing "run" in the Coder.

**Comment by noahmotion** [comment]
Here's what I just downloaded: https://github.com/psychopy/psychopy/releases/download/1.85.3/StandalonePsychoPy-1.85.3b-OSX_64bit.dmg

And here's line 558 in event.py in the version of PsychoPy that this installed on my computer:

    lastPosPix = lastPosPix - self.win.size / 2

**Comment by hoechenberger** [comment]
Thanks @noahmotion, I will look into this

**Comment by hoechenberger** [comment]
@peircej I find this quite weird, apparently the standalone release does not contain the version of PsychoPy it claims it does. At least `event.py` is different.

1.85.3 release code, `event.py`, line 558:
https://github.com/psychopy/psychopy/blob/1.85.3/psychopy/event.py#L558
```python
                return False  # just resetting prevPos, not checking distance
```

1.85.3 macOS standalone code, , `event.py`, line 558:
```python
            lastPosPix = lastPosPix - self.win.size / 2
```

**Comment by hoechenberger** [comment]
@noahmotion I cannot reproduce with latest `master`, so the bug apparently has already 'vanished' from the main development branch in the meantime. Is there any particular reason for you to use 1.85.3? Could you maybe downgrade to 1.85.1 for the time being until the next version is released?

The problem for me is that I don't know which code got packaged with the 1.53.3 macOS release, and I don't want to end up trying to fix something that's already been fixed :)

**Comment by peircej** [comment]
Yes, I think this was an error that was introduced during the PY3 compatibility conversion that I have already fixed (and was not deliberately released!)

I've been puzzled by a few error reports in the last week that indicate 1.85.3 containing code from 1.86 and yesterday I confirmed that this is true. It's a bit of a puzzle. Maybe I forgot to switch to the correct tag when I built it (hard to imagine) or conceivably git failed in the switch and I didn't notice the message telling me that. Anyway, I'll build a new version now, called 1.85.4 using the 1.85 branch

I think it's also worth building 1.86.0alpha1 so that people can start finding the additional errors (especially unicode-conversion) that are bound to exist.

**Comment by hoechenberger** [comment]
Thanks Jon, I already suspected sth. like this! Args! :)

**Comment by peircej** [comment]
FYI We add the git sha of the file from which the build was created and that reveals that it was created from commit https://github.com/psychopy/psychopy/commit/2ffa752ece729b086088d217f5a8fbaf0bb75654
which also confirms the issue. This commit was on the master branch not the 1.85 branch :-/

**Comment by noahmotion** [comment]
Yes, it's no problem to use 1.85.1. I upgraded mostly because I got tired of seeing the window recommending that I upgrade to 1.85.3 every time I opened 1.85.1.

Thanks for your help with this. PsychoPy is a fantastic tool.

**Comment by peircej** [comment]
FYI I've now released a new OSX version (1.85.4) to replace 1.85.3 with correct (bug-fix-only) release

**Comment by hoechenberger** [comment]
Great, thanks @peircej! And thanks @noahmotion for bringing this issue to our attention!

**Comment by kohske** [comment]
I found this issue again in 1.85.6 when using setPos().

https://github.com/psychopy/psychopy/blob/37507cb84bbcad2e1a8cfda51f1bef8fbb532787/psychopy/event.py#L473
