### ISSUE TITLE
visual.TextStim and autoDraw

### ISSUE THREAD

**Issue by ghost** [psychopy/psychopy#1521]
Is there a reason why autoDraw is not possible with the initial call of visual.TextStim? It works with a subsequent setAutoDraw(True) call. Fix to text.py? This would be consistent with other visual.xxx functions.

**Comment by hoechenberger** [comment]
As far as I can tell, setting the `autoDraw` attribute on object instantiation is not possible with any (?) visual stimulus except for `Rect`, `Line`, `Circle`, and `PatchStim`. Thus I don't fully understand your question?

Still this appear to be quite an inconsistent behavior that should get improved by adding an `autoDraw` keyword argument to all the above-mentioned classes.

**Comment by hoechenberger** [comment]
@ogigm Want to try a pull request on this one?

**Comment by ogigm** [comment]
Yes, my question is just about the inconsistency between visual.TextStim and Rect, Line, Circle.
Rect, Line and Circle can take autoDraw=True on object instantiation whereas TextStim requires 
a .setAutoDraw(True) after instantiation. 
Polygon also allows autoDraw whereas DotStim does not.

**Comment by hoechenberger** [comment]
@ogigm It's because `Rect` etc. accept "additional" keyword arguments via the `**kwargs` parameter and pass it to their parent class(es). The `autoDraw` parameter is implicitly passed to the parent.

**Comment by ogigm** [comment]
OK, I see. My "fix" was to just hack text.py with an additional keyword argument and explicity set the autoDraw value.

**Comment by hoechenberger** [comment]
@ogigm I anticipate we'll provide a "proper" fix when working on #1523 :)
