### ISSUE TITLE
Docs and (kw)args (?) of some visual stimuli need improvement

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1523]
#1521 has reminded me of something that's always been bugging me with the following visual stimuli:

- `Circle`
- `Line`
- `PatchStim`
- `Rect` 

Their `__init__()` methods all share a similar signature & functionality:

```python
class Circle(Polygon):
    def __init__(self, win, radius=.5, edges=32, **kwargs):
        ...
        super(Circle, self).__init__(win, **kwargs)

class Line(ShapeStim):
    def __init__(self, win, start=(-.5, -.5), end=(.5, .5), **kwargs):
        ...
        super(Line, self).__init__(win, **kwargs)

class PatchStim(GratingStim):
    def __init__(self, *args, **kwargs):
        ...
        super(PatchStim, self).__init__(*args, **kwargs)

class Rect(BaseShapeStim):
    def __init__(self, win, width=.5, height=.5, **kwargs):
        ...
        super(Rect, self).__init__(win, **kwargs)
```
While reducing code redundancy, these signatures commonly come with rather uninformative docstrings: The "optional" `(kw)args` are not explained, and to figure out which parameters might be valid, one would have to dig through the parent classes' `__init__()`s. I've always hated this design choice in matplotlib, and I also dislike it here ;)

I see two possible options to improve upon this:

- keep the signatures as-is, but list the potential additional arguments in the docstring nevertheless. However, this would not provide auto-completion in an IDE.
- Alternatively, explicitly list all (keyword) args in the signatures and add them to the docstring. While introducing a little bit of redundancy, I believe this would greatly improve the user experience: we'd get better docstrings, parameter auto-completion and type-hints in modern IDEs.

Any thoughts on this?

**Comment by peircej** [comment]
I prefer explicit lists for readability (my own classes and subclasses do that). I guess `**kwargs` reduces chance that a change will fail to get propagated so, when contributors wrote their code that way, I've allowed it.

**Comment by hoechenberger** [comment]
So I think we’re on the same page here (proposition 2)? :) If we switch to “explicit args”, should we still keep *args, **kwargs in the signature “just to be sure”?

--

**Comment by peircej** [comment]
Oh, yes, I guess we can keep them too as a "belt-and-braces" approach.

**Comment by hoechenberger** [comment]
Perfect, I'll propose a PR soon.

**Comment by mdcutone** [comment]
We removed the **kwargs argument as of PsychoPy 2021+ for visual stimuli classes. Documentation is also being refreshed.
