### ISSUE TITLE
Attribute Error: 'module' object has no attribute 'ManagedSoundplayer'

### ISSUE THREAD

**Issue by drompi1** [psychopy/psychopy#1532]
OS: Windows 7
Psychopy: v1.85.3 

Hi, 
 I am receiving the following error when trying to add videos into the experiment that load through avbin:
![psychopyerror](https://user-images.githubusercontent.com/32279346/30830464-bf669f50-a209-11e7-9acb-43f7dc0915a1.png)

This error does not appear when I run the experiment on 1.85.2. However, large text is needed for this experiment, which seems to be an issue with 1.85.2, so I cannot use that version either. 

Let me know if there is anything I could do to fix this issue.

Thanks!
David

**Comment by CRiddler** [comment]
Hi, just a few questions to help narrow down your issue- this sounds like an issue with you version of `pyglet`, but I guess we'll find out!

* Is your copy of psychopy from the standalone version? Or did you install it some other way?
* What is the output of `import pyglet; pyglet.version`?
* What is the output of `import pyglet; pyglet.media.ManagedSoundPlayer()`?

Note- that if you're relying on the standalone version, you will need to open up PsychoPy's "coder" view and then change to the "shell" tab to enter these commands!

**Comment by drompi1** [comment]
Hi, CRiddler

Thank you for your quick response to my post! Much appreciated! --

1) I installed it with the standalone version

2) The output of import pyglet; pyglet.version is '1.3.0b1'

3) The output of import pyglet; pyglet.media.ManagedSoundPlayer() is as follows:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'ManagedSoundPlayer'

**Comment by CRiddler** [comment]
Perfect! Thanks so much for that output.

 It seems that `pyglet` completely deprecated and removed `ManagedSoundPlayer()` from version `1.2.4` to `1.3.0b1` so although this switch fixed the issue of rendering large text, it broke our reliance of `pyglet.media.ManagedSoundPlayer()` which is suggested to use `pyglet.media.Player()` now. This is definitely a bug, I'm going to be a little busy this week so hopefully @hoechenberger or @peircej can tackle this issue!

**Comment by drompi1** [comment]
Thank you for your effort!

**Comment by peircej** [comment]
Pyglet movies are troublesome in several ways; they require avbin which has always been a nightmare and they have poor performance with high-resolutino movies. Rather than trying to fix this I suggest we focus our efforts on the newer `moviepy` backend (aka MovieStim3). That is superior in nearly all ways. It's only problem is for long movies because it loads the entire audio file in one go and for long movie files that results in running out of memory. We need to add streaming audio to that player and then it will be entirely superior! :-)
I'm closing this as a "not fixing" issue

**Comment by hoechenberger** [comment]
@peircej Shouldn't we entirely drop `MovieStim` then, if it's now non-maintained anyway?

**Comment by peircej** [comment]
Delete it? No, I don't see the need for that. Like pygame, we can have it present for a period after we no longer actively support it:

- some users may be finding it handy and it actually works for them 
- there are some things it can do that the newer versions can't (long movies with audio)
- as always that means old scripts that people have will stop working

We could advertise more strongly (e.g. log a warning message) that in most cases moviepy/MovieStim3 is better and less troublesome but I'm not ready to break old code by forcibly removing it (yet)

**Comment by drompi1** [comment]
Hi  @hoechenberger and @peircej,

Before posting this error, I tried using moviepy to load the videos. However, moviepy only successfully loads the movies if the movie files are apart from other routines and loops. In other words, the movie files load with moviepy if I create a new experiment with nothing else in it, but they do not load within the experiment I am trying to create. 

My issues with moviepy may be related to the limitation that you alluded to above with long movies resulting in running out of memory. My experiment specifically involves 6 movie clips (about 2 min length), along with various other cognitive tasks/routines. When trying to run the experiment, psychopy freezes on a grey screen and results in the following error message: 

![moviepy error](https://user-images.githubusercontent.com/32279346/30867019-6ecb6dd6-a2a0-11e7-94da-c9e5654d0855.png)

I was wondering if you had any suggestions with moviepy or options I could explore to get such an experiment working? -- Or if you have a timeline of when an update may come out that improves moviepy and possibly fixes the issue?

**Comment by drompi1** [comment]
No worries! That sounds good.

**Comment by peircej** [comment]
Fair point @hoechenberger  - most people are going to be using standalone, and for them it's already broken. If they aren't then they're probably the sort of user that doesn't mind fixing things. 

OK, I'll accept this time that we should remove original MovieStim. ;-) Maybe we should effectively redirect to MovieStim3, with a warning that this has been done, so that users do get a working script again?

**Comment by hoechenberger** [comment]
Hi @peircej, I don't know, just by looking at the docs, switching to `pyglet` 1.3's `Player` should be as easy as simply instantiating this class instead of the `ManagedSoundplayer`. So I would say if somebody's willing to implement this change, it should be included... And we could still add a big fat deprecation warning in the docs/changelog, and maybe emit a warning once `MovieStim` is instantiated?

**Comment by peircej** [comment]
If it works that sounds good, but last I knew (a while ago) the difference between Player and ManagedSoundPlayer was that the former had to be prodded to update its buffers whereas the latter periodically checked if it needed updating. We could have a look and if it "just works" then we're all set, but I suspect the audio is not going to play using simple Player.

**Comment by hoechenberger** [comment]
I like this idea. I'm not willing to invest any development time into this thing myself though *cough* -- Re-opening this issue for brave volunteers!

**Comment by CRiddler** [comment]
>Re-opening this issue for brave volunteers!

@hoechenberger I'm feeling brave so I'll take a whack at it if I can free up some time today! :)

**Comment by hoechenberger** [comment]
Yes, seems nobody cared enough to fix it, see also #1837. I would suggest you try to use `MovieStim3` If that’s an applicable solution for you...

**Comment by hoechenberger** [comment]
(Also, I'd be in favor of clearly deprecating both `MovieStim and `MovieStim2` and officially discouraging their use.)

**Comment by peircej** [comment]
I agree. Let's deprecate them (but keep them available for backwards compat obviously)

**Comment by hoechenberger** [comment]
How would we go about this? I believe we never actually decided how to do a "deprecation cycle" :) Update the docs and spit out a warning message when the module is imported / when the class is used? "Feature is deprecated and might be removed in a future version of PsychoPy; please use xxx instead. Get in touch on the forum [url] if you experience difficulties", something like that?

**Comment by leeweizhe1993** [comment]
> Yes, seems nobody cared enough to fix it, see also #1837. I would suggest you try to use `MovieStim3` if that’s an applicable solution for you...

Thanks, after using `MovieStim3` it finally worked.

**Comment by peircej** [comment]
Yes. We mark as deprecated, and log a warning. I've always done it when the class is used, rather than when it's imported (if someone imports all they don't need a message, or at least they need a different one!). I've never written to get in touch no the forum though for a deprecation.

**Comment by lulucasg** [comment]
>
> 
> Yes, seems nobody cared enough to fix it, see also #1837. I would suggest you try to use `MovieStim3` if that’s an applicable solution for you...

Hi, I'm new to psychopy. I tried using 'MovieStim3' and I got this error:

AttributeError: 'MovieStim3' object has no attribute '_texID'

Anyone knows how to solve it? or what should I use instead?
Thanks :)

**Comment by Jonas-N** [comment]
> > Yes, seems nobody cared enough to fix it, see also #1837. I would suggest you try to use `MovieStim3` if that’s an applicable solution for you...
> 
> Hi, I'm new to psychopy. I tried using 'MovieStim3' and I got this error:
> 
> AttributeError: 'MovieStim3' object has no attribute '_texID'
> 
> Anyone knows how to solve it? or what should I use instead? Thanks :)

Did you ever figure this out? I'm having the exact same issue.

**Comment by lulucasg** [comment]
> > > Yes, seems nobody cared enough to fix it, see also #1837. I would suggest you try to use `MovieStim3` if that’s an applicable solution for you...
> > 
> > 
> > Hi, I'm new to psychopy. I tried using 'MovieStim3' and I got this error:
> > AttributeError: 'MovieStim3' object has no attribute '_texID'
> > Anyone knows how to solve it? or what should I use instead? Thanks :)
> 
> Did you ever figure this out? I'm having the exact same issue.

No :/ I ended up using the common ImageStim and cicled throw all the frames of the original movie. Not quite practical and also very poorly optimized for that. But that was my solution. Hope it helps

**Comment by TEParsons** [comment]
Closing as these classes are long since deprecated in favour of a single class with multiple backends
