### ISSUE TITLE
Balloon Analogue Risk Task (BART): BART: Balloon images do not change between trials with different conditions

### ISSUE THREAD

**Issue by FPilar** [psychopy/psychopy#1537]
Hello everyone! I'm a predoctoral student from Almería who needs to build the Balloon Analogue Risk Task (BART) designed by Lejuez in 2002. I downloaded a demo which includes only the red balloon. So I need to redesign the task to include the green and blue balloons, each with its own properties (PsychoPy version 1.85.2). I have modified xlsx. file including the three types of balloons and the blast points of each one, but when the experiment runs only the green balloon appears. What can I do? Is it because I've modified the demo instead of starting from the scratch? 
Could someone please give me the original task? I would be very grateful... I need to fix it quickly because the study starts soon.

I hope you can help me.
Thanks in advance,
Pilar # #

**Comment by peircej** [comment]
Closing (message is already on discourse, which is the appropriate place)
