### ISSUE TITLE
Error with Bits++ box on 1.85.3b

### ISSUE THREAD

**Issue by schofiaj** [psychopy/psychopy#1539]
I'm copying this message over from the PsychoPy Discourse page as I think it needs some developer attention. The original post was from MThirkettle. Below the original post is a note from me on the results of my investigation into this issue - such as it is.

Original Post.
I’m getting an error when setting up the Bits# box on 1.85.3b which wasn’t there on the previous version. The same error occurs with the demo files too, so I suspect it’s not my coding.

Here’s the error output from the CRS_BitsBox demo file which I’ve edited and resaved as CRS_BitsBoxDemo only to refer to the right monitor here. Any advice would be welcome, in the meantime I’ve rolled back to 1.85.2 and all is working fine (other than then nudge to update!)

```
################## Running: C:\Python Code\CRS_BitsBoxDemo.py ##################
1.6479 ERROR avbin.dll failed to load. Try importing psychopy.visual
as the first library (before anything that uses scipy)
and make sure that avbin is installed.
2.5811 INFO Opened port COM1 but it didn’t respond like a CRS Bits#
2.9560 INFO Opened port COM3 but it didn’t respond like a CRS Bits#
3.3379 INFO Opened port COM4 and looks like a CRS Bits#
3.4405 INFO Successfully opened COM4 with a CRS Bits#
Traceback (most recent call last):
File “C:\Python Code\CRS_BitsBoxDemo.py”, line 26, in 
bits = crs.BitsSharp(win=win, mode=‘bits++’)
File “C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\hardware\crs\bits.py”, line 530, in init
ok = self.checkConfig(level=checkConfigLevel)
File “C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\hardware\crs\bits.py”, line 810, in checkConfig
self.win.winHandle, self.config.identityLUT)
File “C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\gamma.py”, line 74, in setGammaRamp
0xFFFFFFFF & pygletWindow._dc, newRamp.ctypes) # FB 504
TypeError: unsupported operand type(s) for &: ‘long’ and 'LP_c_void’
3.4415 INFO Switched $ProductType;Display++ to bits++ mode
```
And my observations
So far I’ve tracked the problem back to pygletWindow._dc being of type LP_c_void when it is references by gammy.py2 so I am assuming that its not being set correctly.

If you roll back pyglet to the version shipped with PsychoPy 1.85.2 (I think pyglet version 1.2.4) this issue goes away comparisons between the older and newer version of pyget suggest that the new version does not set the  ._dc member for the Window but that bits.py expects it to be set.

**Comment by peircej** [comment]
More broadly it seems that gamma can't be controlled at all using our code with 1.3.0 :-/
I'm looking into this at the moment

**Comment by peircej** [comment]
This turns out to be a bug in Pyglet. It can be fixed by opening:
`pyglet/libs/win32/types.py`
end commenting-out line 81:
```
 c_void_p = POINTER_(c_void)
```
I'm uploading a windows release 1.85.4 that contains this pyglet fix.

FYI making this fix might break some pyglet issues on 64bit python btu that isn't the version we distribute. (And I haven't got a windows 64bit python to test that theory on!)
