### ISSUE TITLE
iohub : datastore errors due to outdated calls to tables API

### ISSUE THREAD

**Issue by dantheman39** [psychopy/psychopy#1548]
Hello all!

I've been having a lot of trouble with ioHub, and when I saw the same type of errors between operating systems (Ubuntu and Mac) I tried to investigate. I've been down a real rabbit hole so I'm trying to keep this constructive, and will only address one issue here. 

iohub.datastore uses pytables (imported simply as "tables"). Since these are manual installs, pip on Mac (via homebrew) and Ubuntu installs a newer version of pytables. The issue here is that PyTables has done a lot of reorganizing and renaming in their API (see <a href="http://www.pytables.org/MIGRATING_TO_3.x.html">here</a>), so this essentially breaks parts of ioHub. 

In my case (on the Mac) I had tried to install an older version of PyTables, but it created some dependency hell with hdf5, and I just couldn't go down that road. PyTables 3 automatically installs a script that can quickly convert a lot of those API calls, and I ran it on datastore.\_\_init__.py, it seemed to do the job, but now on the Mac it's hanging on a call to subprocess (client/\_\_init__.py, about line 960, r=self._server_process.stdout.readline(), which is (probably?) a separate issue ... 

So back to the topic at hand, I have seen a number of issues in discourse and here in the issues page that could be related to this. Particularly import errors, name errors, conspicuously errors where the datastore is not being created or method calls are coming back as not existing: it's because if the user has a more recent version of PyTables, ioHub won't work (and all of the calls to subprocess make this a real pain to debug). 

Of course any decisions will have to include backwards compatibility... I'm curious to see what you all think the way forward on this will be. Thanks, hope you're all well.

**Comment by peircej** [comment]
Yes, it looks like the pytables people read most of PEP8 but not the section https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
where it says very clearly "do not break backwards compatibility just to comply with this PEP!" ;-)

My *guess* is that there are relatively few of these calls to pytables and we could insert some if... statements to execute the appropriate version (i.e. try to maintain dual compatibility). When I search for `openFile` across all files it only crops up once (in datastore.py).

**Comment by dantheman39** [comment]
I saw that @Schubisu has fixed most of the calls, but I believe two were missed. Check the pull request here: https://github.com/psychopy/psychopy/pull/1582 
As stated there, the machine I'm on at the moment can't run ioHub due to some type of issue with wxPython, so I can't actually test it. The changes were pretty simple, but I would appreciate it if someone double-checked my work.

**Comment by hoechenberger** [comment]
Closed via #1582.
