### ISSUE TITLE
 ioHub not working with updated PyTables API (no camelCase)

### ISSUE THREAD

**Issue by Schubisu** [psychopy/psychopy#1576]
As per @m-macaskill\'s suggestion, I'm moving my [question from discourse](https://discourse.psychopy.org/t/iohub-not-working-with-updated-pytables-api-no-camelcase/3305) here:

I’m trying to feed PsychoPy with my serial device using ioHub. Apparently, in ioHub/datastore/\_\_init\_\_.py (and other ioHub modules as well) PyTables’ method `openFile` is used, which has changed from `camelCase` to more pythonic `open_file.`

I’m using PsychoPy 1.85.3 in a virtual environment and installed via pip from the git master branch directly. The installed PyTables version is 3.4.2.

I’m not quite sure how to proceed, as changing the code might break backwards compatibility. As the PyTables API also has been updated for other methods, this might have a bigger impact. For now, specify the version of PyTables in the requirements is probably the best solution?

I understand that there is a general discussion about ioHub here [#1541](https://github.com/psychopy/psychopy/issues/1541), so as suggested I patch ioHub related issues locally for now, but will also check out the other options to find a more sustainable solution.

**Comment by peircej** [comment]
Let's discuss this in #1548
