### ISSUE TITLE
Comparing corrAns to inputText

### ISSUE THREAD

**Issue by drompi1** [psychopy/psychopy#1597]
Hi, I am trying to get Pyschopy to return whether a response was correct or not for a basic digit-span task with an inputText feature. For this task, participants are shown a picture (.png) of a digit, one at a time, and prompted to type all digits in the order they were shown. Right now, I am using the code component with the code below in builder to give the participants the ability to see what they are typing on the screen. This code displays any digits the participants type, and the routine is ended when enter is pressed.

`#Begin Experiment
inputText = ""

#Begin Routine
theseKeys=""
shift_flag = False

#Each Frame
n= len(theseKeys)
i = 0
while i < n:

    if theseKeys[i] == 'return':
        continueRoutine = False
        break

    elif theseKeys[i] == 'backspace':
        inputText = inputText[:-1]  
        i = i + 1

    elif theseKeys[i] == 'space':
        inputText += ' '
        i = i + 1

    elif theseKeys[i] in ['lshift', 'rshift']:
        shift_flag = True
        i = i + 1

    else:
        if len(theseKeys[i]) == 1:
            if shift_flag:
                inputText += chr( ord(theseKeys[i]) - ord(' '))
                shift_flag = False
            else:
                inputText += theseKeys[i]

        i = i + 1

#End Routine
thisExp.addData('inputText', inputText)
inputText=""`

Also, here are the settings for the keyboard component, routine setup, conditions file, data output, and message displayed after running the routine:

Keyboard component:
![data_output](https://user-images.githubusercontent.com/32279346/32956223-d88f768a-cb7d-11e7-91fc-fc594dfabe6e.PNG)

Routine setup:
![digitspan_routine](https://user-images.githubusercontent.com/32279346/32956298-04e9dd88-cb7e-11e7-8aa3-239955293694.PNG)

Conditions file:
![conditions_file](https://user-images.githubusercontent.com/32279346/32956323-10022cac-cb7e-11e7-932d-0be6347d9ca1.PNG)

Data output:
![data_output](https://user-images.githubusercontent.com/32279346/32956330-18a275a6-cb7e-11e7-9c0b-91d4320d7fc6.PNG)

Message:
![message](https://user-images.githubusercontent.com/32279346/32956349-21c556f8-cb7e-11e7-8b5a-622483d259c7.PNG)

-My issue has been getting Psychopy to output the corrAns based on the final string of text entered. The final inputText string has to be compared, rather than recorded key presses (e.g., [‘5’, ‘6’, '1', ‘return’] ), because participants have the ability to use backspace in case they mistype something. With backspace enabled, endless amounts of correct responses, such as [‘5’, ‘6’, ‘backspace’, ‘1’, ‘return’], are possible. Thus, the only way to compare to corrAns would be to compare corrAns with the final string of text (inputText) submitted. However, keyboard_resp_13.corr outputs a 0 regardless of whether the string of numbers submitted matches the corrAns.

**Comment by peircej** [comment]
Closing as this looks like a request for programming help more than an issue with PsychoPy.
