### ISSUE TITLE
Improve coverage calculation: Py2 vs Py3

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1600]
Might be worth looking into:
[Better unittest coverage stats: excluding code that only executes on Python 2/3
](https://anonbadger.wordpress.com/2017/11/24/better-unittest-coverage-stats-excluding-code-that-only-executes-on-python-2-3/)

**Comment by peircej** [comment]
That means excluding the lines that are in different environments. What we'd like to do is merge the coverage test. Codecov can do this, even for different environments (e.g. when we have appveyor for windows and travis for linux):
https://docs.codecov.io/docs/merging-reports
