### ISSUE TITLE
Multiple versions installed parallel on Windows

### ISSUE THREAD

**Issue by bergwiesel** [psychopy/psychopy#1603]
It would be helpful to have PsychoPy2 installed within folders of version numbers like:

C:\Program Files (x86)\PsychoPy2\1.85.4
C:\Program Files (x86)\PsychoPy2\1.86.0

That way it would be possible to have several versions installed on the same machine, which will end the requirement to uninstall and install PsychoPy with different versions every time "older" studies need to test new patients while new studies want to use PsychoPy with newest features and bug fixes.

**Comment by dvbridges** [comment]
Hi @bergwiesel , PsychoPy2 already allows the user to choose any previous versions of psychopy 1) in Builder from the Experiment Settings > Use PsychoPy version, and 2) in Coder using `psychopy.useVersion('latest')`
