### ISSUE TITLE
UTF-8 encoding with french characters

### ISSUE THREAD

**Issue by yuguen** [psychopy/psychopy#1619]
The decode function from lib/encodings/utf_8.py generates decoding errors for french characters.
Replacing errors='strict' by errors='replace' fixes the problem on my end.

Using Windows 10

**Comment by peircej** [comment]
Decoding is required in many places in the application and in scripts, and differs according to Python versions. Please specify the actual error messages you're getting and from aspects of PsychoPy use

**Comment by yuguen** [comment]
Of course, but changing the parameter from 'replace' to 'strict' avoids hard crashes of the applications when using french letters such as "éèàêë" and so on. This problem only occured to me using windows 10 though.
The error message that I get is like the following:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 71: invalid continuation byte

**Comment by peircej** [comment]
I understand the point.
Again, this is potentially in many places and your last-line-only error message doesn't tell me which one is important to you. Or are you suggesting we make a change to the lib itself?

I'm happy to accept a pull request with the necessary changes in but I'm not considering this a priority for my own time, especially as it will all change shortly when we release a Python3 compatible version.

**Comment by yuguen** [comment]
I found what caused the utf-8 decoding problem, my fix was just solving my problem but it did not explain it.
In the file PsychoPy2/Lib/site-packages/pyglet/window/__init__.py there is a "decode hack for python2 unicode support". This hack is causing the UnicodeDecodeError.

To be clear, the original code is the following:
`if hasattr(caption, "decode") 
    caption = caption.decode(utf-8")`

I propose the following change:
`if hasattr(caption, "decode") 
    try:
        caption = caption.decode(utf-8")
    except UnicodeDecodeError:
        pass`

This way, it won't hurt any existing application and will solve the decoding error for french characters.
I can't make a pull request atm thought.
Thanks

**Comment by peircej** [comment]
The file `pyglet/window/init.py` is not part of the PsychoPy library. It's a dependency that we include but don't control. If you post the entire error message you are getting (copy and paste all the lines) then I can help but until you do that I can't.

**Comment by yuguen** [comment]
Here is the complete Traceback:

Traceback (most recent call last):
  File "D:\Adaptive Composite Complex Span (ACCES)\PsychoPy version\ACCES 1.5 Déploiement\ACCES.py", line 19, in <module>
    from psychopy import visual, core, data, event, logging, gui, misc
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\__init__.py", line 17, in <module>
    from .window import Window, getMsPerFrame, openWindows
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\visual\window.py", line 57, in <module>
    from psychopy import core, platform_specific, logging, prefs, monitors, event
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\event.py", line 44, in <module>
    from pyglet.window.mouse import LEFT, MIDDLE, RIGHT
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\gl\__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\win32\__init__.py", line 133, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\pyglet\window\__init__.py", line 569, in __init__
    caption = caption.decode("utf8")
  File "C:\Program Files (x86)\PsychoPy2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 71: invalid continuation byte

**Comment by yuguen** [comment]
I've just checked the pyglet project and they fixed this issue already by using the "try .. except..." method.
Updating your pyglet version should solve the problem

**Comment by peircej** [comment]
OK, yes. I was hoping that this could be fixed by us setting the caption to something without unicode before it ever gets to pyglet but apparently not. They're calling it from a very strange place, while creating a mouse object(!) and there's not much we can do about that. So upgrading the pyglet lib is the thing to do. I'll close this as a result.

Thanks!

**Comment by yuguen** [comment]
I have another problem on windows 10 that can be solved by upgrading your pandas version.
Indeed, reading a xlsx file with lines of different width will create errors. Again, this problem does not happen on a linux machine, only using windows 10.
Upgrading the pandas version by hand solved my problems.

Sincerely,

Yohann
