### ISSUE TITLE
ioHub error for camera setup during eyelink tracker calibration, deprecated scipy function used

### ISSUE THREAD

**Issue by hstojic** [psychopy/psychopy#1638]
Hello,

during the eye tracker calibration, when trying out camera setup part I receive an error:
```python
Error during eye image display: 'module' object has no attribute 'misc'
	<type 'exceptions.AttributeError'>
	AttributeError("'module' object has no attribute 'misc'",)
	['  File "/home/hstojic/.pyenv/psychopy1853/local/lib/python2.7/site-packages/psychopy/iohub/devices/eyetracker/hw/sr_research/eyelink/eyeLinkCoreGraphicsIOHubPsychopy.py", line 508, in draw_image_line\n    image = scipy.misc.toimage(self.rgb_index_array,\n']
```
The source is a deprecated scipy function, `scipy.misc.toimage`,  in `eyeLinkCoreGraphicsIOHubPsychopy.py`.

I used PIL instead, as suggested at  [scipy.misc.toimage info](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.toimage.html), and I think I got it to work with the following code

```python
from PIL import Image
image = Image.fromarray(self.rgb_index_array, mode='P')
image.color = self.rgb_pallete
```

instead of 

```python
image = scipy.misc.toimage(self.rgb_index_array,
                                           pal=self.rgb_pallete,
                                           mode='P')
```

However, I'm not sure whether the images I get are indeed what I should see. For example, crosshairs are missing and colors are a bit off from what one can see on the eyelink computer, and strangely only one quarter of the determined space is filled with the image feed.

Best
Hrvoje

**Comment by isolver** [comment]
Fixed (not sure when). Code is using Image.fromarray now
