### ISSUE TITLE
UnicodeChars constants defined twice with different values

### ISSUE THREAD

**Issue by boazmohar** [psychopy/psychopy#1640]
Using [lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/snapshot/d0ddaca2429ab89b7f8575e1e14d271a5475d504/files/psychopy/iohub/constants.py#x1b62aba3ab970038%3A1)

In [IOhub](https://github.com/psychopy/psychopy/blob/master/psychopy/iohub/constants.py#L658), three constants are defined twice:
INSERT = 0xF727  # "Insert"
INSERT = 0xF73D  # "InsertChar"

DELETE = 0xF728  # "Delete"
DELETE = 0xF73E  # "DeleteChar"

PRINT = 0xF738  # "Print"
PRINT = 0xF72E  # "PrintScreen"

I am not sure what are the ramifications of this or what is the right way to fix it.

**Comment by peircej** [comment]
Not sure about this. I'm not sure I've ever seen a keyboard with Insert and InsertChar keys :-/ but I think it would be sensible to rename those variables as INSERT_CHAR, DELETE_CHAR and PRINT_SCREEN
