### ISSUE TITLE
[expfactory] integration

### ISSUE THREAD

**Issue by vsoch** [psychopy/psychopy#1641]
hey Psycopy team! 

I'm the lead developer for the Experiment Factory (https://expfactory.github.io/expfactory), and I'm hoping we can work together a bit! Expfactory doesn't help much with creating the experiments, but rather reproducible experiment containers to serve them (and note this is the second version of the software I implemented after its initial publication, and it's totally different). So I'm interested in the possibility to have an ability to export psycopy experiments to plug into an Experiment Factory container!

It looks like you have an export option, from your builder:

http://www.psychopy.org/online/fromBuilder.html

and even the files exported are very similar to the expectation that Expfactory has (e.g., some set of resource files with an index.html).  I think it would be pretty trivial to have an integration that would export static files for expfactory, likely just ensuring that the data posts appropriately, and then routes correctly. I would like to offer to contribute / work on this, but I wanted to get your thoughts and feedback first. Happy New Year! :tada:

**Comment by peircej** [comment]
Hi there @vsoch ! Your project looks interesting, although we are also about to build our own server/repository system, so we'll have to look at how these would complement each other and/or work together. I'd be keen to chat about the possibilities (maybe by hangout/skype?). I'll mail you and see how it might work :-)
