### ISSUE TITLE
gui.Dlg() ignoring position argument 

### ISSUE THREAD

**Issue by AW-Ingling** [psychopy/psychopy#1644]
bug explained here:
https://discourse.psychopy.org/t/change-position-of-gui-dlg/3302

**Comment by peircej** [comment]
FYI this would preferably be fixed in qtgui.py as well as wxgui.py

**In qtgui.py** adapt the `_exec()` method to include something like
```
if self.pos is None: 
    <center the dlg> 
else: 
    <set pos>
```

**In wxgui.py** adapt the `super.__init__()` to include a `pos=self.pos` argument
