### ISSUE TITLE
visual.RatingScale doesn't display correct labels with choices that start with 0

### ISSUE THREAD

**Issue by ejolly** [psychopy/psychopy#1648]
When creating a `visual.RatingScale` with the `choices` option, if the `choices` list begins with an _integer_ or _float_ that is falsey (i.e. 0, or 0.0), the left most tick label does not get drawn. 

Example:
```
choices = list(np.arange(10))
spending_scale = visual.RatingScale(win=window, choices=choices,
                                                              showAccept=False,
                                                              noMouse=True,
                                                              stretch=2,
                                                              pos = (0,0),
                                                              textColor= 'White')
```
![image](https://user-images.githubusercontent.com/8481982/34645020-4449177c-f311-11e7-922f-018f31e2cbd2.png)

Version: Psychopy2 Standalone 1.85.3
OS: Mac OSX 10.11.6 El Capitan
Hardware: Macbook Pro Retina 15inch (Mid 2015)

**Comment by ejolly** [comment]
I can post this in https://discourse.psychopy.org if that's preferable

**Comment by peircej** [comment]
No need to post on discourse for this - it looks like a genuine bug. @dvbridges cold you have a dig around RatingScale and see if you can work out the problem?

**Comment by dvbridges** [comment]
No problem, looking now.
