### ISSUE TITLE
event.globalKeys not accessible even with pyglet backend on OSX

### ISSUE THREAD

**Issue by ejolly** [psychopy/psychopy#1658]
Following [this guide](http://www.psychopy.org/coder/globalKeys.html) is not possible even with a pyglet backend using a standalone release on OSX.
Specific error is: `AttributeError: 'module' object has no attribute 'globalKeys'`

I've tried a few recent releases and the issue is specific to following standalone versions on OSX:
- 1.85.6 (most recent)
- 1.85.4b (second most recent)

I have to use 1.85.3 for this to work properly.

**Comment by peircej** [comment]
globalKeys was not supposed to be release yet because it represents a new feature and we only introduce new features in changes to the major version number. The 1.85.3 release was an accidental release of future features. globalKeys will be included in the next release (1.90.0)
