### ISSUE TITLE
A script named "test.py" is executed automatically

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#1663]
I noticed that a script named "test.py" is executed automatically when running a script which contains `import psychopy`.  For exampe, suppose I have "foo.py" and "test.py" in the same directory.  Contents of these files are following:

```
# foo.py
import psychopy
print('This is "foo.py"')
```

```
# test.py
print('This is "test.py"')
```

Running "foo.py", "test.py" is also executed automatically.

```
$ python foo.py
This is "test.py"
This is "foo.py"
```

I observed this phenomenon in following setups.

- Windows 10, Python 2.7, the latest main branch in the repository
- Ubuntu 16.04LTS, Python 2.7, the latest main branch in the repository

On the other hand, this phenomenon doesn't occur in following setups.

- Windows 10, Python 3.6, the latest main branch in the repository
- Ubuntu 16.04LTS, Python 3.6, the latest main branch in the repository

At present I have no idea how to fix this issue.
I'd appreciate any comments or suggestions.

**Comment by hsogo** [comment]
I tested this issue on Standalone PsychoPy 1.85.6 for Windows.  "test.py" was not automatically executed when running "foo.py".  But I noticed that test.py was executed twice when "test.py" contained `import psychopy` and "test.py" was executed on Standalone PsychoPy.  Suppose contents of "test.py" is as below.

```
import psychopy
print('This is "test.py"')
```

Runnning this "test.py", the string is output twice.  Interestingly, it takes a while between the first and the second output.

```
This is "test.py"
This is "test.py"
```

This phenomenon also occurs in both of following setups, but it doesn't take time between two outputs.

- Windows 10, Python 2.7, the latest main branch in the repository
- Ubuntu 16.04LTS, Python 2.7, the latest main branch in the repository

**Comment by ariekahn** [comment]
Appears to be an issue with the future package:

See: https://github.com/PythonCharmers/python-future/issues/259

**Comment by hsogo** [comment]
Hi ariekahn,
Thank you for the information.
That’s really helpful!

**Comment by peircej** [comment]
The lines about `setup_aliases()` were inserted by python futurize automatically and may not be necessary (at least some of them):

- in some places they are trying to support versions of Python that I think we shouldn't try to support (e.g. 3.4 or 2.6)
- in some places we've made the changes to the code manually that make the `setup_aliases()` unnecessary (e.g. importing of urllib in connections.py has been fixed, but in microphone it has not)

So maybe we should remove those lines and try to work out whether anything in those files breaks as a result (and immediately fix microphone code, which I'm confident will break without that line)?

**Comment by hsogo** [comment]
I searched `install_aliases()` from source tree and tried commenting out .  This caused attribute error in psychopy/web.py, but this error seems to be fixed easily.  urllib in microphone.py can be dealt with in the same way as psychopy/web.py, I think.
psychopy/data/utils.py imports `collections.OrderedDict`, which may affect compatibility with Python 2.6.

**Comment by glupyan** [comment]
This bit me in the butt today during a demo in class. Had a test.py in the same directory (because of course). Glad to see it's been addressed!
