### ISSUE TITLE
event.py in 1.85.6 looks like the wrong version

### ISSUE THREAD

**Issue by jonathanoroberts** [psychopy/psychopy#1672]
It looks like the event.py that is packaged in 1.85.6 is an old version. The rating scale demo crashed with:
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/event.py", line 499, in getPos
    lastPosPix = lastPosPix - self.win.size / 2
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

I believe this is an old bug that was fixed. The current source code for event.py has the correct fixed version, but does not appear to have made it into the package.

**Comment by jonathanoroberts** [comment]
This was kind of a false alarm... After looking more closely I see that this issue only affects Macs with Retina displays, and I see it is fixed in the master repository. We have a workaround for our classroom labs until the next release comes out.

**Comment by peircej** [comment]
I am puzzled and I do want to try and work out what's happened in case other files are not the right version (I thought, as you say, that this _had_ been included so I'm worried that some cached files made their way into the release somehow instead of the fresh ones.

**Comment by jonathanoroberts** [comment]
I think it was a mistake by me… sorry. I  was comparing the event.py in the 1.85.6 packaged distrubution to the one in the master branch on the github repository, and not to the one from the r1.85 branch which does match the 1.85.6 packaged version. I presume the master branch will eventually become 1.86 or something, and 1.85.6 is based on the r1.85 branch?

The cause of our crash is in visual/window.py where it checks for the darwin platform and self.useRetina is true. Here are lines 1503 through 1509. In line 1509 it sets the window size to be a tuple instead of a numpy array. In the master branch, this change has been made...

        elif sys.platform == 'darwin':
            if self.useRetina:
                global retinaContext
                retinaContext = self.winHandle.context._nscontext
                view = retinaContext.view()
                bounds = view.convertRectToBacking_(view.bounds()).size
                self.size = (int(bounds.width), int(bounds.height))

Last line should be:
                 self.size = numpy.array([int(bounds.width), int(bounds.height)])

We manually patched this one thing on the standalone psychopy version installed in our undergraduate lab of retina iMacs where the problem came up… so we are OK for now.

Thanks!!!
-Jon



On Jan 17, 2018, at 1:30 PM, Jon Peirce <notifications@github.com<mailto:notifications@github.com>> wrote:


I am puzzled and I do want to try and work out what's happened in case other files are not the right version (I thought, as you say, that this had been included so I'm worried that some cached files made their way into the release somehow instead of the fresh ones.

**Comment by jonathanoroberts** [comment]
I think I'm confused about how the different branches get merged into each other...

**Comment by peircej** [comment]
Yes, with the branches, when I release a new major version, I do so from master and then I create a branch for that release series. From then onwards I 'cherry pick' commits that are marked as `BF:` (i.e. bug fixes only) to that release branch and compile from there. 

The next major release has been a while coming and involves a lot of refactoring (including Python3 support) so I think I'll make it a bigger jump than usual - it will be the 1.90.x series
