### ISSUE TITLE
pip install pscyhopy on Windows 10 tries to install pyobjc-framework-quartz

### ISSUE THREAD

**Issue by Tal-Golan** [psychopy/psychopy#1684]
It then hangs (but I didn't let it run for more than a couple of minutes).

The issue is reproducible simply by `pip install psychopy` on Windows (both using an Anaconda python 2.7 env and a native python 2.7 installation).

The problem seems to be specific to PsychoPy-1.85.6-py2-none-any.whl (md5),
since `pip install psychopy==1.85.3` works.

See also
https://discourse.psychopy.org/t/py2exe-and-psychopy-manual-install/3756/2

**Comment by djmannion** [comment]
This also occurs on 1.90.dev1 on linux.

**Comment by peircej** [comment]
It's puzzling because the setup.py clearly states that the this is only needed for `platform=='darwin'` but I guess the wheel was generated on the mac so it uses that. Hmmph, that means I have to build the wheels separately on each platform :-(

**Comment by peircej** [comment]
I think the solution here is not to build wheels at all. 
pip then installs the zip file, which runs setup.py on your own system (thereby hopefully obeying the platform-specific calls within that).

Try doing 
```
pip install psychopy==1.90.dev2
```
now to test. You can reopen this if it turns out I'm wrong! :-)
