### ISSUE TITLE
Problem with psychopy logging on linux

### ISSUE THREAD

**Issue by tomwallis** [psychopy/psychopy#1687]
Perhaps I am using this incorrectly, but the following script produces no console output on Ubuntu 16.04:

```python
#! /usr/bin/env python

from psychopy import logging
logging.fatal('should be an error')
```

I'm using a conda virtualenv with the psychopy development version (current commit, version 1.90.0).

Thanks

**Comment by peircej** [comment]
What if you add `logging.flush()` at the end?

The PsychoPy logging module (unlike the built-in one) is designed to flush the log messages to their targets only when told to do so, or at the end of the experiment. Possibly the mechanism to do this at the end of the experiment hasn't worked - it's designed to occur during 'garbage collection' but that mechanism appears fragile. I've just pushed a new way to make sure it gets done at the end of the script now, using the atexit module to force this.

**Comment by tomwallis** [comment]
That did the trick; thanks @peircej
