### ISSUE TITLE
problem please help

### ISSUE THREAD

**Issue by roee121212** [psychopy/psychopy#1692]
![wwww](https://user-images.githubusercontent.com/35845817/35450619-38708044-02c9-11e8-9d36-fe01a3350ab9.PNG)

**Comment by hoechenberger** [comment]
This is not a PsychoPy-related issue. You are using`raw_input()` incorrectly by passing it 2 arguments instead of just one, like the error message says. You are doing it correctly in line 2 though.

**Comment by roee121212** [comment]
so how I supposed to write it?

**Comment by hoechenberger** [comment]
Like in your line 2.

**Comment by roee121212** [comment]
@hoechenberger ok, but why? thats fucked up why I need need give value to any raw input? it is usaually work if I dont give value.

**Comment by hoechenberger** [comment]
You only need to assign the return code to a variable if you want to use that value later on. Otherwise, simply do `raw_input('Foo')` instead.

This is also not the right place to ask these questions, as they are by no means PsychoPy-related.

**Comment by roee121212** [comment]
@hoechenberger ok, how much "," I need to put? and how to use the foo? for example I want to write in the input "example" how to use it with "foo"?

**Comment by hoechenberger** [comment]
I told you this is not the place to ask such basic Python programming questions. Please go away. Use Google to get help. Thank you.
