### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MovieStim2'

### ISSUE THREAD

**Issue by johnkmaxi** [psychopy/psychopy#1693]
Hi,

I have been using PsychoPy 1.82.01 (standalone) to present video files during EEG experiments. Suddenly, I am getting an error regarding the MovieStim2 attribute. It occurs at this line:

`# Create your movie stim.
mov = visual.MovieStim2(win, videopath,`

If I try:
`from psychopy.visual import MovieStim2`
I get:
`from psychopy.visual import MovieStim2
ImportError: cannot import name MovieStim2`
This is happening on 2 different laptops. The experiment previously worked on both laptops. The MovieStim2.py demo script has also stopped working.

I'm using Windows 10. Any reason why this would stop working since yesterday?

**Comment by peircej** [comment]
I have no idea what could have "changed" for that to be an issue.
But I'm also not still troubleshooting issues from v1.82. Could you see if this is a problem when you update to a newer version? We can reopen this if it's still a problem
