### ISSUE TITLE
test failures due to back/front buffer differences

### ISSUE THREAD

**Issue by djmannion** [psychopy/psychopy#1701]
I am getting test failures in the 'height' context of ```test_all_stimuli``` - as shown in the example below, ~half the image is shown.

They look to be false positives though, seemingly due to the screen being captured from the back buffer in the test. If I flip the window after running the test, the image looks as expected and not as below.

![envelopeandrcos_height_local](https://user-images.githubusercontent.com/1371039/35723215-a11ad12e-084d-11e8-8e7e-222456db4857.png)

This is with 1.90.0-dev1 on linux with an ATI graphics card under Python2.

**Comment by hoechenberger** [comment]
Does this issue still occur with current master?
