### ISSUE TITLE
If anybody recently experiencing pyglet error.

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychopy#1712]
If anybody who installed Psychopy manually using cmd.exe or commandline, 
One might experience the error related to pyglet as below.

NameError: name 'PUINT' is not defined

It's due to incompatibility between Python 2 and 3. The variable 'PUINT' called by pyglet only exists in Python 3.

So, if you want to run Psychopy with Python 2 env. download older version of pyglet as tar.gz,
and install it using

pip install <filename>
(i.e. pip install pyglet-1.2.1.tar.gz)

I succeed with Python 2.7.14, Psychopy 1.85 and pyglet 1.2.1 manual install.

**Comment by mpichowsky** [comment]
Excellent advice.  I had a similar problem when installing openAI gym package in python 2.7.  The function Environment.render() failed with same error "PUINT" not defined.

so I installed
pip install pyglet-1.2.1-py2-none-any.whl
and Environment.render() works now!

**Comment by peircej** [comment]
I'm assuming there's a longer error message than this one line? Could one of you post the entire trace? 
Could you also tell us which version of pyglet this is NOT working on. I've been using pyglet 1.2.4 and that seems fine. I can see there's a 1.4 and a 1.3 version too though.

**Comment by mpichowsky** [comment]
Hello Peircej, 
I was using pyglet-1.3.1 which led to the following trace below when I ran  "environment.render()" in openai gym.   (I am running on this on Windows in an Anaconda environment.)  Thanks!


NameError                                 Traceback (most recent call last)
<ipython-input-5-a692a1a1ffe7> in <module>()
----> 1 env.render()

F:\gym\gym\core.pyc in render(self, mode)
    241
    242     def render(self, mode='human'):
--> 243         return self.env.render(mode)
    244
    245     def close(self):

F:\gym\gym\envs\classic_control\cartpole.pyc in render(self, mode)
    104
    105         if self.viewer is None:
--> 106             from gym.envs.classic_control import rendering
    107             self.viewer = rendering.Viewer(screen_width, screen_height)
    108             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

F:\gym\gym\envs\classic_control\rendering.py in <module>()
     21
     22 try:
---> 23     from pyglet.gl import *
     24 except ImportError as e:
     25     reraise(prefix="Error occured while running `from pyglet.gl import *`",suffix="HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'. If you're running on a server, you may need a virtual frame buffer; something like this should work: 'xvfb-run -s \"-screen 0 1400x900x24\" python <your_script.py>'")

d:\Users\Michael\Anaconda2\lib\site-packages\pyglet\gl\__init__.py in <module>()
    217     from .base import Config
    218 elif compat_platform in ('win32', 'cygwin'):
--> 219     from .win32 import Win32Config as Config
    220 elif compat_platform.startswith('linux'):
    221     from .xlib import XlibConfig as Config

d:\Users\Michael\Anaconda2\lib\site-packages\pyglet\gl\win32.py in <module>()
      4 from __future__ import absolute_import
      5 from builtins import zip
----> 6 from pyglet.canvas.win32 import Win32Canvas
      7 from .base import Config, CanvasConfig, Context
      8

d:\Users\Michael\Anaconda2\lib\site-packages\pyglet\canvas\__init__.py in <module>()
     97             from pyglet.canvas.carbon import CarbonCanvas as Canvas
     98     elif compat_platform in ('win32', 'cygwin'):
---> 99         from pyglet.canvas.win32 import Win32Display as Display
    100         from pyglet.canvas.win32 import Win32Screen as Screen
    101         from pyglet.canvas.win32 import Win32Canvas as Canvas

d:\Users\Michael\Anaconda2\lib\site-packages\pyglet\canvas\win32.py in <module>()
      5 from .base import Display, Screen, ScreenMode, Canvas
      6
----> 7 from pyglet.libs.win32 import _kernel32, _user32, types, constants
      8 from pyglet.libs.win32.constants import *
      9 from pyglet.libs.win32.types import *

d:\Users\Michael\Anaconda2\lib\site-packages\pyglet\libs\win32\__init__.py in <module>()
    235 _user32.RegisterRawInputDevices.argtypes = [PCRAWINPUTDEVICE, UINT, UINT]
    236 _user32.GetRawInputData.restype = UINT
--> 237 _user32.GetRawInputData.argtypes = [HRAWINPUT, UINT, LPVOID, PUINT, UINT]
    238

NameError: name 'PUINT' is not defined

**Comment by peircej** [comment]
This has been solved in the pyglet code https://bitbucket.org/pyglet/pyglet/commits/a69ff38c23dc5bec51b2a53c4697b671885d35da
but that code has not yet been released. Sadly it looks like it missed the release of pyglet 1.4.0a1 but I'm sure it will be fixed in 1.4.0 main release. Either way, it isn't an issue that we have any control over so I'm closing this
