### ISSUE TITLE
problems with dual-screen setup on psychopy 1.85.6 with fullscr=True

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#1728]
This simple script works on pyschopy 1.83.04 without problem but causes 1.85.6 to freeze - only one of the windows is seen, the text is not visible and `event.waitKeys()` seems to wait forever:
```python
from psychopy import visual, event, core

window_1 = visual.Window(screen=0, fullscr=True, monitor='testMonitor', blendMode='avg')
window_2 = visual.Window(screen=1, fullscr=True, monitor='testMonitor', blendMode='avg')
text1 = visual.TextStim(window_1, text='1')

text1.draw()
window_1.flip()
event.waitKeys()
core.quit()
```
it works fine with `fullscr=False`. I tested it on Windows 7.

I was previously using psychopy 1.83.04 but I had a very wierd bug when clicking on second screen led to keybord being unresponsive - clicking back on the first screen made the keyboard responsive again. This may or may not be related - I had problems reproducing that problem in a simple script, but I am looking for a psychopy version where dual-screen setup works well. I will report back after checking other versions.

**Comment by mmagnuski** [comment]
Same problem on 1.84.2

**Comment by mmagnuski** [comment]
and going back to `1.83.04` fixes the problem.

**Comment by mdcutone** [comment]
Have you tried flipping both windows prior to calling waitKeys()?

**Comment by mmagnuski** [comment]
Yes, AFAIR I originally was flipping both windows but found that it doesn't matter. The other screen was not visible BTW. 
I cannot test it now because I went back to `1.83.04` for my experiment to run correctly. I'll try to reproduce on some other dual-screen setup but this may take a few days before I have time to do so.

**Comment by mdcutone** [comment]
At first glace it looks like effort was made in the code to prevent this from happening. I would assume the window without focus might not be having its event dispatcher called, but it seems like waitKeys() does that for all open windows. I'm not sure where this issue arises from (either Pyglet or PsychoPy) at this point.
