### ISSUE TITLE
newest version 1.90 "coulmmn"

### ISSUE THREAD

**Issue by jano15** [psychopy/psychopy#1729]
Bug in psychopy/data/staircase.py

```
                for oDatN in range(len(self.otherData[key])):
                    ws.cell(**colummn**=col, row=oDatN+2,
                            value=u"{}".format(self.otherData[key][oDatN]))
                col += 1
```

colummn is wrong. it mus be **column**=col

see line 631

**Comment by mmagnuski** [comment]
@jano15 just a small tip: use three backticks (` ``` `) before and after code block (instead of `/code`). And using ` ```python ` gives nice syntax highlighting.
