### ISSUE TITLE
ShapeStim: changing vertices causes psychopy to change their order

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#1734]
Changing the vertices values causes psychopy to chage their order which changes the shape:
```python
import numpy as np
from psychopy import visual, event

window = visual.Window(monitor='testMonitor')
vertices = np.array([[-0.5, -0.5], [0.5, -0.5], [0.3, 0.], [0.5, 0.5],
                     [-0.5, 0.5]])
shape = visual.ShapeStim(window, vertices=vertices)
shape.setFillColor('pink')

shape.draw()
window.flip()
event.waitKeys()

shape.vertices += 0.2
shape.draw()
window.flip()
event.waitKeys()
```
In the example above the effect is just that border lines get messed up and the shape is triangulated but using more complex stimuli leads to stronger effects:
before repositioning
<img width="246" alt="psychopy_bug_vert01" src="https://user-images.githubusercontent.com/8452354/36344528-2e242e06-141c-11e8-9fa6-0db77a740d5a.PNG">

after repositioning
<img width="254" alt="psychopy_bug_vert02" src="https://user-images.githubusercontent.com/8452354/36344529-33a5ac10-141c-11e8-8f55-5d2bed7e628e.PNG">

Tested on windows, psychopy 1.85.0

**Comment by peircej** [comment]
This is bizzaro!

**Comment by mmagnuski** [comment]
Yes, I find it very weird too - I tried to track it down in the psychopy code, but I am not very familiar with the codebase and my search was fruitless. 
BTW - it seems that any access to `.vertices` with an operation even without *in-place* intention results in this bug. Both `print(shape.vertices + 0.5)` and `shape.vertices += 0.5` should result in that error.

**Comment by gitgmi** [comment]
Is the problem with closeShape? 
Code seems fine with closeShape=False

**Comment by peircej** [comment]
The problem was with the call to tesselate (which turns a shape into a set of triangles as needed). It's fixed by commit 9b47ab7 (and b1a2289)

**Comment by peircej** [comment]
Sorry to me a couple of attempts to get that in, but master now has this fixed

**Comment by mmagnuski** [comment]
great, thanks @peircej!
