### ISSUE TITLE
can't use module of 'visual'

### ISSUE THREAD

**Issue by Iv911** [psychopy/psychopy#1756]
![Uploading image.png…]()

when i set the display, get an error message
‘AttributeError: 'module' object has no attribute 'visual' 

my code

win = psychopy.visual.Window(size = [800,600],
                             units = "pix",
                             fullscr = False,
                             color=[128,128,128],

**Comment by peircej** [comment]
You want 
```
from psychopy import visual
win = visual.Window(...)
```
Please take a look at the demos or read the tutorial for the correct usage
