### ISSUE TITLE
pyWinhook instead of pyHook in iohub?

### ISSUE THREAD

**Issue by tjwilli58** [psychopy/psychopy#1758]
Would it be possible to allow using pyWinhook instead of pyHook in iohub/
Where I work, I can't download exe files, but I can pip install things. It looks like pyHook is only available as an EXE installer.  pyWinhook however, is available on PyPi as a wheel.  This seems to work for me, though I'm just getting into using PsychoPy, so just being able to import iohub isn't much of a test.

I modified my copy of iohub/server.py and iohub/devices/keyboard/win32.py like this:

win32.py (line13):

```
try:
    import pyHook
except ImportError:
    import pyWinhook as pyHook

```
server.py (line 636):

```
            if Computer.system == 'win32':
                try:
                    import pyHook
                except ImportError:
                    import pyWinhook as pyHook

```

**Comment by tjwilli58** [comment]
Found a wheel for this.
[https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook]

**Comment by hoechenberger** [comment]
Maybe we should add this reference to the installation instructions?

**Comment by tjwilli58** [comment]
I think that would be great. I'm restricted from downloading and running exe's w/o admin privs, but wheels are ok, I guess since I have a local anaconda install.

**Comment by hoechenberger** [comment]
I don't think this is an Anaconda-specific issue…

**Comment by tjwilli58** [comment]
No. It's more of a python/pip issue. If you go to pypi.org, the latest installer is `pyHook-1.5.1.win32-py2.7.exe`. Not only is it specific to python2.7, but it's also 32-bit.

Another argument for having the wheels on the unofficial wheels page
[https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook)

**Comment by peircej** [comment]
OK, I guess my point is that the reason I provide a Standalone distribution is so that I don't have to spend time fixing problems with incompatible dependencies in the range of python environments that are possible. I'm happy to take pull requests (where these don't damage other features or the Standalone distributions) but I'm not working on these issues myself.

**Comment by hoechenberger** [comment]
@tjwilli58 I have managed to build `pyWinhook` on Python 3.7, Windows 10. In fact, I built a `conda` package, which I intend to publish on `conda-forge` soon. I had to patch `pyWinhook` to support Python 3; there's an open PR at https://github.com/Tungsteno74/pyWinhook/pull/2

The project seems to be pretty much inactive; if the PR doesn't get merged, I can patch the latest release to make a proper `conda` package (in fact, that's what I'm currently doing for my local builds).

Considering that `pyHook` is dead, we _have_ to switch to `pyWinhook` anyway (or ditch iohub).

**Comment by tjwilli58** [comment]
@hoechenberger , I didn't think this was an issue anymore since I haven't seen any comments since April, so I just closed it.  Thanks for working on it. I haven't had any issues with the latest versions of PsychoPy, so I thought this wasn't a  problem anymore, but maybe I was just not getting into those parts.

**Comment by hoechenberger** [comment]
@tjwilli58 Just today a colleague of mine couldn’t use iohub with PsychoPy3 Standalone. It threw an error message indicating that something was wrong with pyHook (don’t remember the details). That was when I realized something was still wrong.

**Comment by hoechenberger** [comment]
@peircej 
Just a recap and an update. So, initially, @tjwilli58 was asking whether we could switch iohub from using `pyHook` to `pyWinhook`, the issue being that they couldn't find a pip-installable version of `pyHook` on PyPI. The last build is from 2010, does not support Python 3 and won't compile with modern compilers (required for recent Python versions on modern Windows releases).

This has been kind of resolved by using unofficial wheels found at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook

Apparently they patched `pyHook` to be Py3-compatible and build on current platforms, but they don't specify anywhere what they did exactly or which kind of sources they use.

In any case, it would be nice if installing `pyHook` wasn't so much of a pain. `pyWinhook` was forked from `pyHook` to add support for more recent compilers, but also lacks Python 3 support. I patched `pyWinhook` for Python 3 compatibility and built `conda` packages, which can be found on `conda-forge`:

- [recipe](https://github.com/conda-forge/pywinhook-feedstock/tree/master/recipe)
- [packages](https://anaconda.org/conda-forge/pywinhook)

With this in place, users using their custom `conda` Python installation can now simply do `conda install -c conda-forge pywinhook` and they're set. I believe this can also be of advantage for our CI testing as soon as start testing on Windows, and, of course, it brings us another step closer to a PsychoPy conda package.

I therefore would like to propose to
- switch iohub from using `pyHook` to `pyWinhook`
  - if preferred, we could support both, using a `try ... except` around the imports
  - `pyWinhook` is a drop-in replacement for `pyHook`, so no further code changes would be necessary
- add `pyWinhook` to the PsychoPy package depdendencies in `setup.cfg`
- potentially switch all deps that are exclusively iohub-related to an `extra` so they would be installed only when doing `pip install psychopy[iohub]`?

What do you think?

**Comment by peircej** [comment]
I really don't mind whether it's pyhook or pywinhook. If the latter is easier to package then sure, although I think a try...except does make sense (because I've been packaging pyhook for a while)

With regards to a `pip install psychopy[iohub]` I don't know. I totally see you point, but not sure if it's worth separating or if that adds confusion. (e.g. with `requests[security]`, which installs some ssl libs as well, I wish they would just make that the norm rather than a special case)

**Comment by peircej** [comment]
OK, on windows the absence of pywinhook was preventing me from building on Py36_64. I've just got the 64bit version working too. Yay for the future! I wonder how many windows boxes in labs are still running Win32

**Comment by hoechenberger** [comment]
I believe I also need to publish Py3.6 wheels, mhmh. 

--
