### ISSUE TITLE
Iohub (Psychopy 1.84.2): database cannot handle long experiment names and does not warn you.

### ISSUE THREAD

**Issue by hannehuygelier** [psychopy/psychopy#1773]
I may have found a small bug in Iohub (not sure whether it is still present in the latest updated psychopy).

If you have a long experiment name, each time you run the experiment the label for the experiment in the database is not recognized and therefore in the database a new ID is made for each experiment. To prevent this issue, it would be useful when using the LaunchHubServer function to get a warning if your string is longer than the ones that can be used in the database. Because now it doesn't complain and the characters that exceed the max length are just cut off which produces problems later on.

In addition, when the database adds a new unique experiment it has to make a new ID number. This throws an Type error in the script "server.py" in the iohub package at line 282. It throws a "serialize" error, so probably the database receives an integer rather than a string so there is probably a type conversion missing in the code.

**Comment by peircej** [comment]
Hi there, thanks for this. Could you either check in the latest version and/or send a minimal demo of the problem so we can test it here? cheers

**Comment by hannehuygelier** [comment]
Hi,

With this code I can elicit the issue if I run the code a few times:

`def IoHubTest(LongExpName = True, SlowLoop = True, FakeTrials = 200):

    # IMPORT LIBRARIES:
    from psychopy import iohub, monitors, core
    from psychopy.iohub import launchHubServer, devices
    
    # CONSTANTS AND OTHER STUFF TO DECLARE AND DEFINE:
    ID = "Debug"
    Date = "27-03-2018"
    Mon = monitors.Monitor("Laptop", distance = 34, width = 32)
    
    # CHOOSE NAME OF EXPERIMENT:
    if LongExpName:
        ExpName = "ThisIsAWayTooLongNameForAnExperimentButIDontKnowTheMaxLength"
    else:
        ExpName = "Short"
    
    # LAUNCH SERVER FOR EYETRACKER:
    io = launchHubServer(experiment_code = ExpName, 
                         psychopy_monitor_name = Mon, 
                         iohub_config_name = "iohub_config_SMI.yaml", 
                         session_code = ID + "_" + Date)            
    eyetracker = io.devices.tracker
    experiment = io.devices.experiment
    experiment.enableEventReporting(True)
    
    # SET UP EYETRACKER:
    eyetracker.runSetupProcedure()
    
    # START RECORDING GAZE:
    eyetracker.setRecordingState(True)
    
    print("start experiment")
    
    for t in range(0, FakeTrials):
        
        # Which Trial?
        print(t)
        
        # Send database info on start of the trial:
        io.sendMessageEvent(str(t))
        
        # Do Trial related stuff:
        print("present some stuff on the screen")
        print("wait until participant gives a response")
        
        # If Fast Loop Go quickly otherwise wait 3 s:
        if SlowLoop:
            core.wait(10)
    
    # END OF EXPERIMENT:
    print("exp finished")
    
    # STOP EYETRACKER RECORDING:
    eyetracker.setRecordingState(False)
    experiment.enableEventReporting(False)
    eyetracker.setConnectionState(False)
    io.quit()

IoHubTest(True, True, 5)`

**Comment by isolver** [comment]
iohub experiment code's have a max length of 24 characters. Adding this to list of things to fix in iohub refactor work.

**Comment by isolver** [comment]
Increased max length of these fields greatly, so the chances of running into the issue will be much lower. 

Still need to add check / report issue if > max is used, but have added that to the "improved error handling" list, so closing this issue.
