### ISSUE TITLE
Add arabic_reshaper to standalone distribution

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#1785]
Following up from this discussion:
https://discourse.psychopy.org/t/reshaping-english-text-to-arabic/4235

 we could solve the issues with displaying Arabic/Farsi & related text by bundling the `arabic-reshaper` package with the PsychoPy standalone distribution:
https://github.com/mpcabd/python-arabic-reshaper

PsychoPy already comes with the `python-bidi` package. I think that is sufficient for displaying Hebrew properly, but languages that use the Arabic alphabet need this extra reshaping step to display letters in their proper context-dependent llinked form.

`arabic-reshaper` is GPL and available via Pip (but note that in the pip index the package name has a hyphen rather than an underscore).

@peircej : being a bit presumptuous and assigning this issue to you, because I've got no idea what is involved on the standalone packaging side. I have installed the package in my local Anaconda Python 3 installation and confirmed that it works properly with PsychoPy text stimuli.

For future development, we could easily add the functionality of both `python-bidi` and `arabic-reshaper` to the `TextStim`, but to get this functionality out as soon as possible, it would be sufficient to just distribute both packages with PsychoPy and use their functions as required.

**Comment by peircej** [comment]
No worries. Yes, I'll add it in to the Standalone.
