### ISSUE TITLE
TextBox broken?

### ISSUE THREAD

**Issue by glupyan** [psychopy/psychopy#1790]
See https://discourse.psychopy.org/t/textbox-broken/4202

**Comment by peircej** [comment]
I'm not seeing this problem on the Standalone installations of 1.90.1 so either it's something that has been fixed or it's a problem with the anaconda installation.

**Comment by hoechenberger** [comment]
Working for me with a conda installation (Python 2.7) on macOS with latest stable. @glupyan, can you try again with the latest PsychoPy release?

**Comment by hoechenberger** [comment]
Closing, cannot reproduce.
