### ISSUE TITLE
Global Event Keys seems to be unavailable on PsychoPy 1.90.1 (Python 3)

### ISSUE THREAD

**Issue by CarlHey** [psychopy/psychopy#1792]
The [example code](http://www.psychopy.org/coder/globalKeys.html#a-working-example) of the chapter *Global Event Keys* of PsychoPy Documentation seems unavailable on PsychoPy 1.90.1 on my laptop. I copied the code and run it on the Coder View of PsychoPy(Python 3), but it seems that the *event* module didn't take effect. Is it a bug? Or is there something wrong running the code?

**Comment by CarlHey** [comment]
I'm using Windows10, and there aren't any error message. As the screenshot shows:

![20180406205627](https://user-images.githubusercontent.com/30583524/38422502-93f07f46-39dd-11e8-8849-440c8722da7e.png)

I can't stop this window so I use the button on the coder view to stop it. And there are no new message after I stop the script.

**Comment by CarlHey** [comment]
My Num Lock key is active as I run the script above.
I turned it off just now and test the script again. It's working this time! 

Thank you for your suggestion, it works!

But I wonder why the script can't work when the Num Lock key is active. Is it because the keys that psychopy detected contain the modifier key?

**Comment by hoechenberger** [comment]
This is simply something that never occurred to me on the systems I've tested so far :) I will think about a way to fix this – probably Num Lock should just be ignored. Thanks for reporting!
