### ISSUE TITLE
No cedrus device detected in psychopy. 

### ISSUE THREAD

**Issue by jyjd99** [psychopy/psychopy#1796]
Hello, all.

I am having psychopy windows8 & mac os sierra
I would like to derive a pulse through stimulation tracker and get a voice response through cedrus SV-1. In doing so, I expect that I can see both devices.

I am able to import pyxid - that was released 5 months ago. In both system, no cedrus devices detected. Outputs from python interpreter is like this. 
Is there any one solving this problem?

devices = pyxid.get_xid_devices()
devices
[]

Thank you for reading.

**Comment by peircej** [comment]
This looks like an issue for Cedrus (they make the hardware and they write the pyxid library). I suggest you open an issue at https://github.com/cedrus-opensource/pyxid instead
