### ISSUE TITLE
voice-key pyo init is not working on windows

### ISSUE THREAD

**Issue by jyjd99** [psychopy/psychopy#1799]
Hello, everyone. 

I am a newbie of psychopy.
I have a psychopy version. 1.90.1b only with python2 on my windows8 labtop. 
I have to use stimtracker and found that pyxid lbrary does not work with python3.

I would like to use psychopy voice-key function so basically copied code from word-naming demo.
When I run the initial setting, I got an error message that:

```python
pyo version 0.8.7 (uses double precision)
portaudio error in Pa_OpenStream: Invalid device
Portaudio error: Invalid deviceportaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized

Server not booted.
Portmidi warning: no midi device found!
Portmidi closed.
The Server must be booted!
Traceback (most recent call last):
  File "C:\Users\**\Desktop\TEST\RT_lastrun.py", line 214, in <module>
    vpvk = vk.OnsetVoiceKey( sec= 3, file_out='data/trial_'+str(trials.thisN).zfill(3)+'.wav')
  File "C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy\voicekey\__init__.py", line 112, in __init__
    raise VoiceKeyException(msg)
psychopy.voicekey.VoiceKeyException: Need a running pyo server: call voicekey.pyo_init()
```

I would like to hearing your advice. 
Thank you. 

Best 
YJ

**Comment by peircej** [comment]
The issue with using the failing voicekey was most likely the need for pyo to be used as sound library but this clashed with sounddevice when that was set to be the primary device in the preferences. See #2447

The issue with pyxid has also been fixed and in release 3.1.1
