### ISSUE TITLE
unsupported view for screen resolution 3200 X 1800 ?

### ISSUE THREAD

**Issue by EfratMeir** [psychopy/psychopy#1802]
my laptop screen is 4K resolution.
this is the error im getting when trying to run a scripts (that works in other computers):

psychopy\psychopy-master\psychopy\visual\backends\pygletbackend.py", line 334, in screenID
    _screenID = 0xFFFFFFFF & scrBytes
TypeError: unsupported operand type(s) for &: 'long' and 'LP_c_void'
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method Window.__del__ of <psychopy.visual.window.Window object at 0x0000000014CE4780>> ignored

I guess it has something to do with the length of the screen id variables.
any suggestion?
trief to change the screen settings but does not help

**Comment by peircej** [comment]
See #1779
