### ISSUE TITLE
blend modes not working

### ISSUE THREAD

**Issue by djmannion** [psychopy/psychopy#1808]
The ```win.blendMode = "add"``` functionality no longer seems to be working.

Demo code:

```python
import psychopy.visual
import psychopy.event

with psychopy.visual.Window((512, 512), useFBO=True) as win:

    grating = psychopy.visual.GratingStim(win=win, contrast=0.25, sf=3)

    for (blend_mode, h_pos) in zip(["avg", "add"], [-0.5, +0.5]):

        win.blendMode = blend_mode

        grating.pos = (h_pos, 0)

        for grating_ori in [0, 90]:
            grating.ori = grating_ori
            grating.draw()

    win.flip()

    psychopy.event.waitKeys()
```
From the current version (1.90.1) back to 1.85.4, this gives:

![blend_demo_1_85_4](https://user-images.githubusercontent.com/1371039/39108901-bae9ba94-470d-11e8-9640-0bb2faa768f0.png)

At v1.85.3, this gives:

![blend_demo_1_85_3](https://user-images.githubusercontent.com/1371039/39108919-ce8afd06-470d-11e8-8140-41fdc47646c7.png)

These are with the all the same packages, with the psychopy version the only change.

I can't see anything in between 1.85.3 and 1.85.4 that would have caused this, but I will keep investigating.

**Comment by djmannion** [comment]
See also https://discourse.psychopy.org/t/blurred-mask-for-rdk/4271

**Comment by djmannion** [comment]
It looks like ```GratingStim``` has its own blend mode, which overrides the blend mode of the window (https://github.com/psychopy/psychopy/commit/65219f225cb0108a1c485c1255dcea49da16cc0f#diff-75d98c90e8f2c1488b86a88502403649).

I don't think this is necessary? It is straightforward to change the blend mode of the window before drawing, and having it bound to the GratingStim means that custom blend modes (i.e. other than 'avg' and 'add') can't be used. And I like custom blend modes :)

**Comment by djmannion** [comment]
But, it is also straightforward to override by setting ```blendmode=None``` when creating the ```GratingStim```.

**Comment by peircej** [comment]
I think the reasoning was to have a per-stimulus setting that could override the window (as is the case with most other settings, like units) but I guess the mistake is that this should be `None`, to inherit from the Window, by default

**Comment by peircej** [comment]
I think it is useful to have this feature in general but if there's something we need to chagne to make custom blend modes possible too then that's something we should think about.

**Comment by djmannion** [comment]
Oh, setting ```blendmode=None``` won't work in 1.90.1 because ```win.blendMode``` now raises an error if the blend mode isn't "add" or "avg".

I think it is fine to leave as-is; it's a niche case and I can override ```draw``` if necessary.

**Comment by peircej** [comment]
No, no. Think like stimulus units arguments:

```
class GratingStim:
  def __init__(self, ......blendMode=None....)
    ...
    if blendMode is None:
       self.blendMode = win.blendMode
    else:
       self.blendMode = blendMode
```

(actually I think that code can be simplified with `self.blendMode = blendMode or win.blendMode` but that's just sugar)

**Comment by djmannion** [comment]
Sorry, I wasn't clear by what I meant in my message - I was responding to my statement that "it is also straightforward to override by setting blendmode=None when creating the GratingStim".

I was thinking I could set ```blendmode=None``` in ```GratingStim``` and it wouldn't change the window's blend mode when drawing, without needing to modify any of the psychopy code. This was the case up until 1.90.1, but now a blend mode of None raises an error rather than just having no effect - so this workaround won't work.

I agree that the way you mention would work well :)
