### ISSUE TITLE
IDE Mirrored for Right-to-Left Locales

### ISSUE THREAD

**Issue by arkravitz** [psychopy/psychopy#1818]
Reproduction:
Search in windows for "locale" and click "date, time, and number format" (May be different if not on Windows 7).
Change the format to any RTL language (ex. Hebrew).
Open Psychopy IDE
Text and buttons are on the wrong side of the window. Input is backward as well.
![capture](https://user-images.githubusercontent.com/1297252/39575845-b2f3756c-4ee4-11e8-98d2-91621b721104.PNG)

**Comment by peircej** [comment]
I guess when we set the locale of the wx app (which we do so that dialogs can change their language) we should watch out for the RTL languages and force the locale back to eng_us in these cases?
