### ISSUE TITLE
iohub.devices.gamepad and iohub.devices.xinput fail to import

### ISSUE THREAD

**Issue by lindeloev** [psychopy/psychopy#1819]
I tried registering responses from a Logitech GamePad f310 using iohub on Mac OS 10.13.4 and Ubuntu 16.04 (not tested on Windows). It fails to import. I haven't tried using gamepads before, so I can't say whether this is specific to psychopy version 1.90.1, but I would figure as much since I would assume a larger number of bug reports if it never worked.
The iohub demos use `iohub.devices.gamepad`, but this fails to import:

    from psychopy import iohub
    io = iohub.launchHubServer()
    gamepad = io.devices.gamepad  # No module named 'gamepad'

The iohub documentation use `iohub.devices.xinput.GamePad` but `xinput` also fails to import:

    from psychopy import iohub
    kwargs = {'psychopy_monitor_name':'testMonitor', 'xinput.Gamepad':{}}
    io = iohub.launchHubServer(**kwargs)
    gamepad = io.devices.xinput.GamePad()  # No module named xinput

**Comment by hoechenberger** [comment]
I tried with PsychoPy 1.90.2, xinput 0.1.3, installed on Python 3.6.5 on Win10 64-bit using the following code ([derived from `iohub.client.connect.py`](https://github.com/psychopy/psychopy/blob/3ab90722cd3860bfe00aebe3eb61d16b3d075638/psychopy/iohub/client/connect.py#L121):

```python
from psychopy.iohub.client import launchHubServer

iohub_kwargs = {'xinput.Gamepad': dict()}
io = launchHubServer(**iohub_kwargs)
gamepad = io.getDevice('gamepad')
```

This seems to work, until iohub tried to actually initialize/use the device via an apparently outdated API. So it's definitely broken with the latest xinput release.

**Comment by lindeloev** [comment]
Meanwhile, I got it to work with the `inputs` module. Just put `inputs.py` in your experiment folder, and you can do:

```
import inputs
def waitGamepad(keyList=[], maxWait=float('inf'), timeStamped=True, state='down'):
    """
    Equivalent to psychopy.event.waitKeys(timeStamped=True) but for gamepads using the inputs module. Returns (key, rt) instead of [(key, rt)]. Assumes that a clock = core.Clock exists. 
    
    maxWait: number of seconds to wait before returning None
    timeStamped: True, False or a core.Clock
    state: 'down' or 'release'. The state of the button.
    """
    if timeStamped in (True, False):
        clock.reset()
    else:
        pass  # Using the same clock
    
    while clock.getTime() < maxWait:
        presses = inputs.get_gamepad()
        for press in presses:
            if press.code in keyList:
                if (state == 'down' and press.state != 0) or (state == 'release' and press.state == 0):
                    return press.code, clock.getTime()
    
    else:
        return '', ''
```

**Comment by isolver** [comment]
This device code was likely never properly moved to python3 and has since been removed from the iohub supported device list. 

Should I bring this back in? The time stamping of events from an xinput device has the same considerations as a keyboard or mouse, i.e. accurate time stamping requires ability to process events as soon as they are available
