### ISSUE TITLE
Bug: experiment data doesn't appear in data folder

### ISSUE THREAD

**Issue by BeritJanssen** [psychopy/psychopy#1826]
PsychoPy 1.90.1. PY3 seems to not save data correctly on Windows: instead of the "data" folder (where only log files are written to), the files appear in the same folder as the .psyexp file. In this experiment with audio stimuli randomly presented in a loop, the files were named after the audio stimuli, rather than participants.

**Comment by peircej** [comment]
If you've changed the experiment setting governing the data filename then maybe you just left off the part where it says "data/......" ? 

i.e. what is your experiment data filename set to be?

**Comment by BeritJanssen** [comment]
I used PsychoPy in class, so I cannot check right now, but the students didn't change the settings as far as I'm aware. This happened to 5 students, all working on Windows. Could it have something to do with sharing .psyexp files between Mac and Windows?

**Comment by peircej** [comment]
Yes, it's possibly due to a difference in that, but in general on windows data *are* saved in the data folder. When you said that the files were named after audio stimuli rather than participants, how was that achieved if not through the Experiment Settings?

**Comment by hoechenberger** [comment]
@BeritJanssen Does this problem still persist or can this issue be closed?

**Comment by BeritJanssen** [comment]
I haven't had the chance to do more testing, so I couldn't say. If there are no more people who ran into this problem, I guess we can close this issue for now.
