### ISSUE TITLE
OpenGL deprecated in next macOS major release

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1849]
I'm afraid this is going to cause us a major headache.

> Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14. Games and graphics-intensive apps that use OpenGL should now adopt Metal. Similarly, apps that use OpenCL for computational tasks should now adopt Metal and Metal Performance Shaders.
> Metal is designed from the ground up to provide the best access to the modern GPUs on iOS, macOS, and tvOS devices. Metal avoids the overhead inherent in legacy technologies and exposes the latest graphics processing functionality. Unified support for graphics and compute in Metal lets your apps efficiently utilize the latest rendering techniques. For information about developing apps and games using Metal, see the developer documentation for Metal, Metal Performance Shaders, and MetalKit. For information about migrating OpenGL code to Metal, see Mixing Metal and OpenGL Rendering in a View.

https://developer.apple.com/macos/whats-new/#deprecationofopenglandopencl

**Comment by mdcutone** [comment]
Macs with dedicated graphics might not be affected since the vendors provide OpenGL support through their drivers. It's going to suck for people who use those all-in-one desktops and laptops though. With the GLFW backend, we can support Vulkan in a pinch if things get really bad.
