### ISSUE TITLE
windows gamma table bias

### ISSUE THREAD

**Issue by djmannion** [psychopy/psychopy#1859]
It looks like windows does not use the full uint16 range when setting the gamma ramp, causing repeated get/set calls to reduce the screen brightness (see [this discourse report](https://discourse.psychopy.org/t/monitor-gamma-or-something-else-brightness-contrast-light-related-decreases-each-time-i-run-my-experiment/4706)).

For example, the following returns ```65280```:
```python

import ctypes
import numpy as np
import psychopy.visual

win = psychopy.visual.Window()

ramp = np.tile(np.linspace(0, 1, 256)[:, None], (1, 3))
win.gammaRamp = ramp

hw_ramp = np.empty((3, 256), dtype=np.uint16)
ctypes.windll.gdi32.GetDeviceGammaRamp(win.backend.screenID, hw_ramp.ctypes)

print(hw_ramp.max())

win.close()
```

I think the problem is the following lines in ```gamma.py```:

```python
newRamp = (255.0 * newRamp).astype(numpy.uint16)
# necessary, according to pyglet post from Martin Spacek
newRamp.byteswap(True)
```
This can be seen by ```np.array(255.0).astype(np.uint16).byteswap(True)``` giving ```65280```.

Could we replace these two lines with:
```python
newRamp = (65535.0 * newRamp).astype(numpy.uint16)
```

This seems to resolve the issue for me, but perhaps there is another issue that it raises by not having the ```byteswap``` in there?

**Comment by peircej** [comment]
I don't know why the byteswap was previously necessary and now not! :-/ I wonder if this is about a) 64 bit windows or b) Win10 or c) pyglet 1.3. Actually I don't see how it could be (3) because we're making calls directly to the windows functions, but either (1) or (2) seem plausible still

**Comment by djmannion** [comment]
It was with Windows 7 for me.

Actually, I think the ```byteswap``` might still be necessary - but there might also need to be one when *getting* the gamma table.

(It sounds like Windows takes the first 8 bits as the LUT index and ignores the second 8 bits. So '1111111100000000' = 65280 would be right).

So rather than:

```python
origramps = numpy.empty((3, rampSize), dtype=numpy.uint16)
# ...
origramps = origramps/65535.0 # rescale to 0:1
```

something like:
```python
origramps = numpy.empty((3, rampSize), dtype=numpy.uint16)
# ...
origramps = origramps.byteswap(True)  # back to 0:255
origramps = origramps / 255.0
```

**Comment by djmannion** [comment]
A separate but related issue has come up in that casting without rounding seems to affect the linearity of the gamma table (see this [discourse thread](https://discourse.psychopy.org/t/display-raw-pixel-values/4910)).
