### ISSUE TITLE
Can't download Psychopy

### ISSUE THREAD

**Issue by sabacso** [psychopy/psychopy#1902]
Hi there,

I can't download StandalonePsychoPy2-1.90.3-MacOS.dmg for my mac. I also tried downloading the Windows version on a different computer and it did not work. The message "failed - network error" keeps appearing and the download stops. Any pointers on how to get around this?

Thanks,

Sarah

**Comment by peircej** [comment]
There's not much I can do with a network error I'm afraid. Can you go somewhere else to download it with a faster network?
