### ISSUE TITLE
OS X: beta3: py2.7 hangs, py3 works

### ISSUE THREAD

**Issue by njvack** [psychopy/psychopy#1916]
One more weird thing from me: I've downloaded the beta3 releases. The python 2 launches and shows me the builder window and tip of the day, but I get a spinning beachball and can't click on anything.

The python3 version seems to work normally.

I haven't delved into the packages and tried to run them with traces or the like.

**Comment by peircej** [comment]
I am seeing this too on one of my machines (that's good! Improves the chances of fixing it!)

**Comment by peircej** [comment]
Update. I *think* this is related to the tip of the day coming up (if I disable that it seems fine), but I can't make it hang reliably yet. Sometimes it works fine with tips turned on too, which is really frustrating

**Comment by peircej** [comment]
I'm not sure, because I could never make it fail reliably, but I think this is fixed in 3.0.0b6.
Maybe you could check and close this issue if it's now working for you?

**Comment by njvack** [comment]
No dice. It doesn't hang for me, but it starts and closes without showing any windows.

I'm guessing it's related to the error I get for the PY3 beta6, which I'll put in a different ticket.

**Comment by peircej** [comment]
In beta7 I've turned off tooltips in the Py2.7 Mac version, because I think it was some threads clash with that dialog

**Comment by peircej** [comment]
There is no Py2.7 at the moment (I can't get it to build properly for unknown reasons) but Standalone Py3 3.0.0b11 is launching fine (whether or not you have things like git installed or set up) so I'm closing this
