### ISSUE TITLE
Error loading libsndfile.dylib library

### ISSUE THREAD

**Issue by mario-bermonti** [psychopy/psychopy#1922]
Got this error when trying to run any experiment: I am running psychopy 1.90.3 on Mac OS X El Capitan 10.11.6

Traceback (most recent call last):
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/demos/coder/stimuli/soundStimuli.py”, line 22, in 
from psychopy import sound, core
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/sound/init.py”, line 79, in 
from . import backend_sounddevice as backend
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/sound/backend_sounddevice.py”, line 20, in 
import soundfile as sf
File “soundfile/init.pyc”, line 1, in 
File “soundfile/soundfile.pyc”, line 270, in 
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/cffi/api.py”, line 141, in dlopen
lib, function_cache = _make_ffi_library(self, name, flags)
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/cffi/api.py”, line 802, in _make_ffi_library
backendlib = _load_backend_lib(backend, libname, flags)
File “/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/cffi/api.py”, line 797, in _load_backend_lib
raise OSError(msg)
OSError: cannot load library ‘/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib’: dlopen(/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib, 2): no suitable image found. Did find:
/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib: stat() failed with errno=20. Additionally, ctypes.util.find_library() did not manage to locate a library called ‘/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib’

This was apparently due to the site-packages folder not unzipping automatically. When I did it manually (as suggested in this [post](https://discourse.psychopy.org/t/sound-crashes-with-macos-high-sierra-10-13-4/4488)) and deleted the .zip-file things started working

**Comment by peircej** [comment]
I think this is fixed in 3.0.0b6. Maybe you could check that it works for you and then close the issue?

**Comment by romanakazi** [comment]
@peircej 

Hi, I was using 1.90.1 on a Mac.

I'll try the above.

**Comment by hoechenberger** [comment]
Hello @romanakazi, has this issue been resolved?
