### ISSUE TITLE
cant install Psychopy

### ISSUE THREAD

**Issue by badench** [psychopy/psychopy#1927]
I run ubuntu and wanted to install Psychopy to use in a project. I followed the instructions to first install it using 'sudo apt install psychopy'. I tried launching the application and after it checks my computer it just crashes. I then tried going through and installing everything manually following the pip commands given on the website. I am able to get everything except Psychopy. when I try pip install pscyhopy here is the error i get at the very end.  
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1321, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-build-_le569xv/wxPython/buildtools/build_wxwidgets.py", line 375, in main
        "Error running configure")
      File "/tmp/pip-build-_le569xv/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m3.90s)
    Finished command: build (0m3.90s)
    Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_le569xv/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yxvehf7n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_le569xv/wxPython/

could anyone point me in the right direction?

**Comment by peircej** [comment]
The error message suggests that wxPython hasn't installed properly
