### ISSUE TITLE
Binary incompatability with numpy

### ISSUE THREAD

**Issue by badench** [psychopy/psychopy#1929]
Hi i am currently running psychopy 1.90.2 and numpy 1.15.0. it says it supports python 2.7 which is the version of python i am using. when i start psychopy i get a bunch of warnings that says 'RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime'. when i create a simple test like the one in your youtube video i can run it and i get the first pop up for participants then when i click ok the experiment goes to a black screen then freezes then crashes. that binary incompatibility warning is the only thing i can seem to find in terms of error reporting. Any ideas?

**Comment by peircej** [comment]
Please copy/paste actual error messages in full. We can't tell what's wrong from this info

**Comment by djmannion** [comment]
I have been getting similar messages too, recently (as well as a new 'hello' message from pygame, as shown below). I don't think they are psychopy related, and they don't seem to cause any problems.

After ```pip install psychopy``` in a clean virtual environment, I get:

```
> python -c 'import psychopy.visual'
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/damien/venv/pt/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/damien/venv/pt/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
```

The ```RuntimeWarning``` messages no longer appear if I do:
```bash
pip uninstall pandas
pip install --no-binary pandas pandas
pip uninstall scipy
pip install --no-binary scipy
```

System info:

```
#[ PsychoPy2 RuntimeInfoStart ]
  #[[ PsychoPy ]] #---------
    psychopyVersion: 1.90.2
    psychopyHaveExtRush: True
  #[[ Experiment ]] #---------
    experimentRunTime: 2018_08_08 19:57 (Year_Month_Day Hour:Min)
    experimentRunTime.epoch: 1533722223
    experimentScript: -c
    experimentScript.digestSHA1: None
    experimentScript.directory: /home/damien
  #[[ System ]] #---------
    systemFlacVersion: flac 1.3.2
    systemHaveInternetAccess: True
    systemHostName: djm_desktop
    systemLocale: en_AU.UTF-8
    systemMemFreeRAM: 9731.9296875
    systemMemTotalRAM: 11969.6328125
    systemPlatform: linux 4.17.12-arch1-1-ARCH
    systemRavailable: R version 3.5.1 (2018-07-02) -- Feather Spray
    systemRebooted: 2018-08-08 12:06
    systemSec.GPGHome: /home/damien/.gnupg
    systemSec.GPGVersion: gpg (GnuPG) 2.2.9
    systemSec.OpenSSLVersion: OpenSSL 1.1.0h  27 Mar 2018
    systemSec.pythonSSL: True
    systemTimeNumpySD1000000_sec: 0.0049
    systemUser: damien
    systemUserID: 1000
    systemUserProcCount: 36
    systemUserProcFlagged: Firefox
    systemUsersCount: 1
  #[[ Window ]] #---------
    windowRefreshTimeSD_ms: 0.006
    windowRefreshTimeMedian_ms: 16.665
    windowRefreshTimeAvg_ms: 16.665
  #[[ Python ]] #---------
    pythonVersion: 2.7.15
  #[[ OpenGL ]] #---------
#[ PsychoPy2 RuntimeInfoEnd ]
```

**Comment by peircej** [comment]
Those warning can apparently be ignored (I say apparently as I know nothing about them and they aren't coming from psychopy):

https://github.com/ContinuumIO/anaconda-issues/issues/6678

**Comment by peircej** [comment]
@badench does the experiment actually work, but just gives you these warnings, or are there further issues?

**Comment by badench** [comment]
@peircej only the initial small pop up window asking about your participant number pops up. after that the experiment freezes then crashes

**Comment by badench** [comment]
@peircej here is the full error after the experiment crashes


######## Running: C:\Users\badenh\Documents\stroo\stroopexp_lastrun.py #########
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Python27\lib\site-packages\pandas\_libs\__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
C:\Python27\lib\site-packages\pandas\__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (hashtable as _hashtable,
C:\Python27\lib\site-packages\pandas\core\dtypes\common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos, lib
C:\Python27\lib\site-packages\pandas\core\util\hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import hashing, tslib
C:\Python27\lib\site-packages\pandas\core\indexes\base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (lib, index as libindex, tslib as libts,
C:\Python27\lib\site-packages\pandas\tseries\offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.tslibs.offsets as liboffsets
C:\Python27\lib\site-packages\pandas\core\ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos as libalgos, ops as libops
C:\Python27\lib\site-packages\pandas\core\indexes\interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs.interval import (
C:\Python27\lib\site-packages\pandas\core\internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import internals as libinternals
C:\Python27\lib\site-packages\pandas\core\sparse\array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.sparse as splib
C:\Python27\lib\site-packages\pandas\core\window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.window as _window
C:\Python27\lib\site-packages\pandas\core\groupby\groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (lib, reduction,
C:\Python27\lib\site-packages\pandas\core\reshape\reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos as _algos, reshape as _reshape
C:\Python27\lib\site-packages\pandas\io\parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.parsers as parsers
C:\Python27\lib\site-packages\pandas\io\pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos, lib, writers as libwriters
Traceback (most recent call last):
  File "C:\Users\badenh\Documents\stroo\stroopexp_lastrun.py", line 59, in <module>
    blendMode='avg', useFBO=True)
  File "C:\Python27\lib\site-packages\psychopy\visual\window.py", line 375, in __init__
    self.backend = backends.getBackend(win=self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\psychopy\visual\backends\__init__.py", line 32, in getBackend
    return Backend(win, *args, **kwargs)
  File "C:\Python27\lib\site-packages\psychopy\visual\backends\pygletbackend.py", line 227, in __init__
    self._origGammaRamp = self.getGammaRamp()
  File "C:\Python27\lib\site-packages\psychopy\visual\backends\pygletbackend.py", line 326, in getGammaRamp
    return getGammaRamp(self.screenID, self.xDisplay)
  File "C:\Python27\lib\site-packages\psychopy\visual\backends\pygletbackend.py", line 338, in screenID
    _screenID = 0xFFFFFFFF & scrBytes
TypeError

**Comment by peircej** [comment]
Ah! And now you post the error message we can see the real problem that you're having. 😉 

The warnings are not causing the crash. That comes from the final line `_screenID = 0xFFFFFFFF & scrBytes` which is a known problem that has been fixed. Could you try 1.90.3 (or 3.0.0b4, but then you might find other problems! 😄 )
