### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1939]
The dependency `astunparse` does not currently support Python 3.7, see https://github.com/simonpercivall/astunparse/issues/26 It's unclear if and when a fixed version will be released (there _is_ a fix in the `astunparse` `master` branch, though.)

**Comment by peircej** [comment]
I don't know what we can do about this other than wait it out but, in due course, this will fix itself.

**Comment by hoechenberger** [comment]
Yes, I just created this issue as some kind of reminder / heads up :) Would you mind keeping it open, just for reference?

**Comment by hoechenberger** [comment]
`astunparse` 1.6 has recently been released and fixes this issue.

**Comment by leeweizhe1993** [comment]
It seems like I run into the same error @peircej  :
![image](https://user-images.githubusercontent.com/32242263/48816998-640cf380-ed7f-11e8-98b7-160eb4932a14.png)
Collecting tables (from psychopy)
  Using cached https://files.pythonhosted.org/packages/4d/53/8f34ce887c2a2ad80518980419a5f6f41defc85a287a355987e559ce9385/tables-3.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/05/cqptwrtn1_l8n2w5kcl_2pg80000gp/T/H5closeh4du2eta.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    /var/folders/05/cqptwrtn1_l8n2w5kcl_2pg80000gp/T/H5closeh4du2eta.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    ld: library not found for -lhdf5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    * Using Python 3.7.0 (default, Jun 28 2018, 07:39:16)
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/05/cqptwrtn1_l8n2w5kcl_2pg80000gp/T/pip-install-473aync2/tables/

my environment is Python3.7 in conda
