### ISSUE TITLE
psychopy.org connection should be encrypted

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1956]
These days, [psychopy.org](http://psychopy.org) is _literally_ the only website I use regularly which doesn't support TLS encryption. Considering that recent versions of Chrome [mark](https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html) the website as "not secure" as the ecosystem has been moving towards an "encrypt all connections by default" policy, we're lagging behind a couple of years here. I would really appreciate this being addressed some time soon (I know there seem to be more urgent issues right now, but I also think the lack of encryption hurts the professional appeal of the entire project).

**Comment by peircej** [comment]
Yes. The reality is that it has no impact on anything as far as I can imagine: the site never allows you to type anything in at all, let alone asking for passwords, so I'm not really clear what the goal is of encrypting an entirely static site. But I agree that it affects the professional appeal

It looks like I might be able to provide ssl certificate in the existing location

But, yes, there are more urgent fires burning right now!

**Comment by peircej** [comment]
psychopy.org has been https for a while
