### ISSUE TITLE
Error in psychopy.psychopy.gui.qtgui.fileSaveDlg

### ISSUE THREAD

**Issue by ChaiGuangJie** [psychopy/psychopy#1962]
when cancel the Dlg, fileSaveDlg return a tuple like ('',''), rather than None!

**Comment by hoechenberger** [comment]
Can you please provide a minimal working example? Thank you.

--

**Comment by peircej** [comment]
And tell us about your system too. When I run the following on a mac it works fine.

```python
from psychopy.gui import wxgui as gui

files = gui.fileOpenDlg()
print(files)
```

**Comment by ChaiGuangJie** [comment]
@peircej @hoechenberger  not `wxgui.fileOpenDlg`,but `qtgui.fileSaveDlg`  in windows10 , PsychoPy 1.90.3
```
from psychopy.gui import qtgui as gui

files = gui.fileSaveDlg()
print(files)
```
output : ('', '')

**Comment by peircej** [comment]
Yes, on Mac this works correctly for both Open and Save dlgs, but I can replicate the problem on Win10. Looking into it now
