### ISSUE TITLE
event.waitKeys() crashes when using the GLFW backend

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#1966]
Calling waitKeys() crashes PsychoPy when using the GLFW backend. This is expected as waitKeys() has no GLFW specific code. However, it's an issue people should be aware of until a fix is issued.

**Comment by billbrod** [comment]
Is this still the state of this? Using the GLFW backend with `Psychopy==3.1.5`, I don't get that `waitKeys()` crashes, but it does get stuck there, unable to receive any input, until I have to `ctrl-c` to quit out of it.

The way I've avoided this for now is to replace this:
```
text.draw()
win.flip()
keys = event.waitKeys()
```

With this:
```
text.draw()
win.flip()
keys = []
while not keys:
    text.draw()
    win.flip()
    core.wait(.1)
    keys = event.getKeys()
```

which is obviously much less elegant and readable, but seems to work.

**Comment by m-macaskill** [comment]
This doesn't directly address this bug, but the `event` module should be deprecated in favour of the new `Keyboard` class, which has superior capabilities and performance: https://www.psychopy.org/api/hardware/keyboard.html

**Comment by billbrod** [comment]
Good to know! Is there an equivalent for `waitKeys()`? It's not clear to me from a quick read of that page.

**Comment by peircej** [comment]
I actually haven't written the waitKeys() equiv. It would be similar to your code above, although that's a little more complicated than it needs - having drawn and flipped you don't need to keep flipping (waitKeys itself does not):

``` python
kb = hardware.Keyboard()

text.draw()
win.flip()
keys = []
kb.clock.reset()
while not keys:
    core.wait(.005)
    keys = kb.getKeys()
for key in keys:
    print(key.rt, key.key)  # use the rt from the keyboard itself
```

**Comment by billbrod** [comment]
Alright, thanks all! I wasn't able to get the `psychtoolbox` python module installed off of pip easily (though I didn't spend too long trying, to be fair) -- if that's not installed, it looks to me like `kb.getKeys()` is the exact same as `event.getKeys()`, is that correct?
