### ISSUE TITLE
Text wrapping looks messed up in TextBox

### ISSUE THREAD

**Issue by nat-n** [psychopy/psychopy#2002]
I tried running the textbox_simple.py example by selecting it from the Demos menu and clicking the run button in the IDE, but it looks like the text is not laying out properly.

My Environment:
Psychopy version: 3.0.0b7
macOS 10.13.5 (17F77)
MacBook Pro (15-inch, 2017)
External display: 2560x1440

Here's what it looks like for me:
![screen shot 2018-09-01 at 17 07 15](https://user-images.githubusercontent.com/880829/44947218-1cbf3880-ae0a-11e8-923d-646564b5ce8b.png)

Minimal example code:
```python
from psychopy import visual, core, event

window = visual.Window((800, 600), units="norm", fullscr=False, allowGUI=True, screen=0)

textbox = visual.TextBox(
    window=window,
    text="This TextBox illustrates many of the different UX elements.",
    font_size=32,
    font_color=[1, -1, -1],
    background_color=[-1, -1, -1, 1],
    border_color=[-1, -1, 1, 1],
    border_stroke_width=4,
    textgrid_shape=[20, 4],
    pos=(0.0, -0.25),
)

textbox.draw()
demo_start = window.flip()

event.clearEvents()
while True:
    textbox.draw()
    kb_events = event.getKeys()
    if kb_events:
        break

core.quit()
```

**Comment by peircej** [comment]
Yes, I've seen this, but I couldn't work out what's going wrong from the underlying code. I'm actually currently writing my own alternative that will supersede TextBox and allow fonts that aren't only monospaced. So I'm not planning to work on this one myself, but happy to take a pull request for TextBox if someone works out the source of the problem.
