### ISSUE TITLE
Unfortunate kwarg and method names in data; how to address?

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2035]
# `trialList` kwarg

The `__init__()` methods of `data.trial.TrialHandler`, `TrialHandler2` and `TrialHandlerExt` expect a kwarg named `trialList`, which actually neither refers to trials (but conditions instead), nor must necessarily be a list (can be pretty much any iterable, or even a file name). I wonder if we could change the existing signatures:

`TrialHandler*.__init__(trialList, ...)`

to

`TrialHandler*.__init__(conditions, ..., trialList=None)`, i.e. a backward-compatible "soft deprecation" of the `trialList` kwarg.

# `saveAsWideText()`
The `saveAsWideText()` methods in `data.trial` don't save data as wide, but as long text, i.e. one row per trial. I therefore propose to rename the existing methods to `saveAsLongText()`, while still keeping the old method names alive for backward-compat and the sole purpose of future confusion ;)

```python
def saveAsLongText(...):
    [existing method body here]

saveAsWideText = saveAsLongText
```

**Edit** Same applies to `ExperimentHandler.saveAsWideText()`.

**Edit 2** I can totally see the intention behind naming it `wide text`, as one trial (i.e., row) can contain more than one response / observation. So what we actually save strictly doesn't fit into the `long` / `wide` naming scheme, that's probably where my confusion arises. I am still wondering whether there could be a better name?

**Comment by peircej** [comment]
I'm closing this - not important enough a change to warrant breaking people's existing code
