### ISSUE TITLE
Proposal: Global preference on backend type (e.g. pyglet, GLFW, pygame)

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2039]
I was looking into getting some additional input event features working with the GLFW backend to bring it to feature parity with Pyglet. One complication was that if you have multiple backends installed, the conditional checks on `have*` (e.g. havePyglet) or `use*` variables cause conflicts within the events module. For instance, if using the GLFW backend, having Pyglet installed will execute Pyglet specific code. Since the 'events' module does care about the type of backend the window is actually using, but rather if the graphics library is present and imported makes it difficult to isolate calls that pyglet and GLFW can't share. 

I propose that we make backend a global preference, rather than specifying it with winType when instantiating the window. It's probably unusual for people to use a mixed environment of windows running different backends anyways.

**Comment by peircej** [comment]
Yes, I hear you. 

But here's another thing to throw into the mix: Mario Kleiner, of psychtoolbox, has now ported his usblib/HID code to allow access from Python (I haven't had time to check it out and glue it into psychopy) so the the other aspect of this is that window and event backends might not be tied anyway (all window backends could (should?) use the new event backend because it will be window-independent (and faster, and support any USB input device).

**Comment by mdcutone** [comment]
Very nice, I was unaware of that. Did he port it to a pure C library?

**Comment by peircej** [comment]
> Very nice, I was unaware of that. 
 
Well, yes, it's new news.

> Did he port it to a pure C library?

It isn't the pure dylib, combined with ctypes/cffi, that I would have preferred. Apparently it would have taken too long to decouple the calling code from the C code. They had built a semi-automated step they call "scripting glue" that made it possible to build more easily. I haven't looked at the outputs yet, and they are just a first draft, but my guess from what he's said is that the code is compiling pyd files.

**Comment by mdcutone** [comment]
> They had built a semi-automated step they call "scripting glue" that made it possible to build more easily.

That should be fine based on what I know of it. I can only see a problem if MATLAB is required (for header files or w/e) during the build process, that's something I don't have readily available.

> It isn't the pure dylib, combined with ctypes/cffi, that I would have preferred. 

Its something that could eventually be done once the sources are made available.
