### ISSUE TITLE
OSError: cannot load library

### ISSUE THREAD

**Issue by romanakazi** [psychopy/psychopy#2041]
Hi, 

Need help understanding the following problem that I'm encountering with Psychopy.
Please advise. 

Thank you!

Error message:
raise OSError(msg)
OSError: cannot load library '/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib': dlopen(/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib, 2): no suitable image found.  Did find:
    
/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib: stat() failed with errno=20.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/site-packages.zip/soundfile/_soundfile_data/libsndfile.dylib'

**Comment by peircej** [comment]
Closing as duplicate #1922
@romanakazi maybe you could reply (to that thread not this one) which version you were using?
