### ISSUE TITLE
PsychoPy3 GUI returns list instead of string

### ISSUE THREAD

**Issue by lindeloev** [psychopy/psychopy#2043]
In PsychoPy 3.0.0.10b on Windows, gui-DlgFromDict returns a list of characters instead of a string when presenting options. Minimal example:

    from psychopy import gui
    vars = {'gender': ['male', 'female']}
    gui.DlgFromDict(vars)
    print(vars)

Returns either ``['m','a','l','e']`` or ``['f','e','m','a','l','e']`` when it should return either ``'male'`` or ``'female'``.

This is also true of the ``inputs --> GUI.py`` demo.

**Comment by lindeloev** [comment]
As an extremely hacky temporary workaround, add this after the dialogue: 

```
for key, value in vars.items():
    if isinstance(value, list):
        vars[key] = ''.join(value)
```

**Comment by peircej** [comment]
I wonder if this is a new problem introduce by #2005

**Comment by peircej** [comment]
Ah, sorry, I checked this on Mac and there was no problem, then forgot to look into it on windows

**Comment by peircej** [comment]
FYI the use of {'number':[30,45]} still won't return an int though (and never did). We don't handle tracking the types of sub-elements yet
