### ISSUE TITLE
PsychoPy 1.90.3 isn't on PyPI

### ISSUE THREAD

**Issue by Kodiologist** [psychopy/psychopy#2048]

**Comment by tjwilli58** [comment]
@peircej , thanks for clarifying that. I've been away for awhile, and am anxious on getting back in the mix.
I ran into the ColorPicker issue #1985 , and am glad to see that it is fixed. We use psychopy on a standalone machine, or isolated network, so it will be interesting to see how Psychopy3 handles that.

**Comment by peircej** [comment]
1.90.3 and 3.0.0b11 are both now on PyPI
I think you can do:
```
pip install -U psychopy # to get 1.90.3
pip install -U psychopy-dev # to get 3.0.0b11
```
