### ISSUE TITLE
Can't install 3.0.0b10

### ISSUE THREAD

**Issue by Kodiologist** [psychopy/psychopy#2049]
$ sudo -H pip3.6 install PsychoPy-3.0.0b10.zip 
    Processing ./PsychoPy-3.0.0b10.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-ne5qm4gw/setup.py", line 22, in <module>
            with open('version') as f:
        FileNotFoundError: [Errno 2] No such file or directory: 'version'
    $ sudo -H pip2.7 install PsychoPy-3.0.0b10.zip 
    Processing ./PsychoPy-3.0.0b10.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-VSxdQo/setup.py", line 15, in <module>
            from setuptools.config import read_configuration
        ImportError: No module named config

I'm running Ubuntu 18.04 and pip 18.1.

**Comment by hoechenberger** [comment]
Hi @Kodiologist 

```python
$ sudo -H pip3.6 install PsychoPy-3.0.0b10.zip 
Processing ./PsychoPy-3.0.0b10.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ne5qm4gw/setup.py", line 22, in <module>
        with open('version') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'version'
```

I suspect this is caused by an incomplete revert of our (my) attempt to use `versioneer` for versioning.
Introduction of `versioneer`: #1970, #1973, #1975
Removal: #1981

```python
$ sudo -H pip2.7 install PsychoPy-3.0.0b10.zip 
Processing ./PsychoPy-3.0.0b10.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-VSxdQo/setup.py", line 15, in <module>
        from setuptools.config import read_configuration
    ImportError: No module named config
```

What is the output of 
```
python2.7 -c "import setuptools; print setuptools.__version__"
```

I suspect Ubuntu's `setuptools` for Python 2.7 is horribly outdated.

**Comment by Kodiologist** [comment]
I'm using a freshly downloaded pip from `get-pip.py`; the Ubuntu packages `python-pip` and `python3-pip` only provide pip 9.0.1 as of Ubuntu 18.04.

My Python 2.7 `setuptools` seems to be at 28.2.0.

**Comment by peircej** [comment]
Try doing `pip2 install -U setuptools`

When I just did that the setuptools version went from 39.0 to 40.4 so 28.2 was probably a while ago and doesn't have that function

**Comment by Kodiologist** [comment]
Thanks, I think you're right. I upgraded to setuptools 40.4.3 and `sudo -H pip2.7 install PsychoPy-3.0.0b10.zip` now gives the same error as for Python 3. Should I just be using `master` for now instead of the last beta release?

**Comment by peircej** [comment]
Glad that fixed the setuptools bug. Yes, I would use master rather than beta10 (beta 10 is neither stable nor cutting edge!)
