### ISSUE TITLE
Installing and running psychopy on Ubuntu 18.04 with conda python 3.6

### ISSUE THREAD

**Issue by iancharest** [psychopy/psychopy#2082]
Hi guys, 

I have recently gone through the trouble of installing psychopy on an Ubuntu 18.04 desktop (Intel® Core™ i7-4790S CPU @ 3.20GHz × 8) 64 bit, running python 3.6 with a anaconda install. I just thought I would detail how I managed to make it work so that others may save some time in the future.

1 - install anaconda
`bash ~/Downloads/Anaconda3-5.3.0-Linux-x86_64.sh `

2 - set system python to 3.6
`conda install python=3.6`

3 - upgarde pip
`pip install --upgrade pip`

4 - grab a copy of psychopy from github
`cd ~/Documents/GitHub &
git clone git@github.com:psychopy/psychopy.git`

5 - install wxpython using conda (running psychopyApp.py was leading to : ModuleNotFoundError: No module named 'wx')
`conda install wxpython`

6 - install libwebkitgtk using sudo apt-get (running psychopyApp.py was leading to : ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory)
` sudo apt-get install libwebkitgtk-1.0-0`

7 - installing the newer intel drivers (following intuition from reading https://github.com/psychopy/psychopy/issues/2061 and getting the ppa for drivers from the ubuntu launchpad https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)
`sudo add-apt-repository ppa:oibaf/graphics-drivers`
`sudo apt-get updated`
`sudo apt-get upgrade`

8 - explictly set the driver in an xorg conf :
`nano /etc/X11/xorg.conf.d/20-intel.conf`
once in the editor, add the following code and save
```bash
Section "Device"
   Identifier "Intel Graphics"
   Driver "intel"
EndSection
```
9 - reboot and enjoy psychopy.

**Comment by peircej** [comment]
I'm closing this though as it doesn't require any action (other than creating a proper conda environment)

**Comment by flipphillips** [comment]
@peircej - you might want to add the ubuntu package install (step 6) into the instructions on the Anaconda page. Note also that we upgraded one of the lab machines to 19.04 for 'fun' and there doesn't seem to be an official package for that release yet, so caveat emptor, etc.

**Comment by peircej** [comment]
Maybe you could tweak the install instructions yourself (I don't know what you called and what's mising)? The docs are all on github:
https://github.com/psychopy/psychopy/tree/master/docs/source

**Comment by shyamcody** [comment]
I downloaded psychopy-2020.2.4. For me, [this libSDL](https://github.com/wxWidgets/Phoenix/issues/991) issue was also there. Also, libwebgtkit is required to be 3.0-0 version for 2020.2.4.; if someone is wondering.
