### ISSUE TITLE
Can't install 3.0.0b8

### ISSUE THREAD

**Issue by tjwilli58** [psychopy/psychopy#2095]
I wasn't sure if I should just reopen #2049 or start a new issue. I'm basically having the same problem.
I'm have psychopy-1.90.3 installed in an anaconda environment, and wanted to try out PsychoPy3. I did a 
`pip  uninstall psychopy` , downloaded the latest PsychoPy3 release, and tried to install it with pip.  I got the error

`FileNotFoundError: [Errno 2] No such file or directory: 'version'`

I then saw that 3.0.0b11 was not a stable release and found #2049 . I then download 3.0.0b8 and updated my setuptools to v40.6.2

I'm still getting the error when I try to do a pip install.

> (perceptionlab) L:\Downloads\Anaconda\PsychoPy\psychopyWheels>pip install --no-index -f . psychopy==3.0.0b8
> Looking in links: .
> Collecting psychopy==3.0.0b8
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\TIMOTH~1.WIL\AppData\Local\Temp\4\pip-install-ha2vxtkb\psychopy\setup.py", line 22, in <module>
>         with open('version') as f:
>     FileNotFoundError: [Errno 2] No such file or directory: 'version'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\TIMOTH~1.WIL\AppData\Local\Temp\4\pip-install-ha2vxtkb\psychopy\
> 

Thanks for any help.

**Comment by peircej** [comment]
As in the issue you linked to, you're installing a version that is neither cutting edge nor a bug-free stable version. Recommended options would be:

- 1.90.3 is the latest stable release (fewer bugs)
- use `pip install -U psychopy-dev` to get the latest release from the development branch
- install from the github repository to get the latest cutting-edge code (including not yet released features and possibly bugs)

Installing 3.0.0b8 is using the recent branch but before we fixed several bugs
