### ISSUE TITLE
Error message when running online study

### ISSUE THREAD

**Issue by mark0425** [psychopy/psychopy#2097]
I use windows and try to run my expeiment on pavlovia. The experiment runs perfectly on my computer,while encountered an error after i push files to github and activate the experiment.
Here is error message:
![default](https://user-images.githubusercontent.com/45162673/48693427-67d03700-ec14-11e8-9a28-82cc2c42f8ca.PNG)
The experiment file had been on github, and  i have no idea how to fix this Error.

**Comment by peircej** [comment]
@apitiot any idea why a project would fail to activate with this message?

**Comment by peircej** [comment]
@mark0425 could you give us the name or url for the experiment to help us test it?

**Comment by apitiot** [comment]
Good morning Mark,

The issue had to do with how the older beta version of the library, 3.0.0b9, interacts with the latest version of the server. I have been trying to be as backward compatible as possible but this particular situation had escaped my attention. It's now been dealt with, and you can open a session.

However you are now running into a known issue of 3.0.0b9: failure to deal with an empty resource folder. This has been addressed in subsequent versions. Could I encourage you to move to 3.0.0b11, which is the latest?

Best wishes,


Alain

**Comment by mark0425** [comment]
Thank you guys so much!! I added a resoure folder and able to click ok to run.
But I encountered another error : Rect is not defined 
![1](https://user-images.githubusercontent.com/45162673/48704134-c5727c80-ec30-11e8-8ab1-07c62bdbef3f.PNG)
Is this error do with my Leave blank of rectangles properties in psychopy builder ?

**Comment by apitiot** [comment]
Hello,

This is an issue with code generation. It should be visual.Rect instead of Rect.
@dvbridges : could you look into it?
I changed Rect to visual.Rect and that problem went away, to be replaced with the following: "currentTrial_B is not defined" in experimentInit()...


Alain

**Comment by mark0425** [comment]
"currentTrial_B"  is actually the variable I wrote in code of psychopy builder.
Maybe I should add my code in js file?

**Comment by peircej** [comment]
In the code component there's now an option to write code in both flavours. Select "both" and write your JS code onthe right and Python code on the left. You do need to get the JS syntax right though - we aren't auto-translating yet

**Comment by dvbridges** [comment]
> This is an issue with code generation. It should be visual.Rect instead of Rect.
> @dvbridges : could you look into it?

No problem, fixed in commit #2102
