### ISSUE TITLE
Psychopy error on installation 

### ISSUE THREAD

**Issue by lgyed5** [psychopy/psychopy#2098]
Hi, 
Downloaded the most recent version but when i click to open the app, a message appears saying 'psychopy error' and gives me the option of either open console or terminate. Either way, it doesnt work and don't know how to download it

**Comment by peircej** [comment]
My guess is that you're using a Mac? It would help to say exactly which version (latest stable is 1.90.3 but latest beta version is 3.0.0b11). If you're trying the latest beta release then one thing to try would be to install Git from here:
  https://git-scm.com/downloads

I'm afraid I'm still working on a way that this isn't needed in the 3.0.0 releases but right now it's necessary I'm afraid.
