### ISSUE TITLE
Only coder opens

### ISSUE THREAD

**Issue by fancyaf** [psychopy/psychopy#2099]
When I open PsychoPy, only the coder view pops up. I have tried everything (I even uninstalled it and re-installed it 3 times), but the builder view is just nowhere to be seen.

**Comment by peircej** [comment]
It just means you closed the builder view at some point and then shutdown (PsychoPy opens the views you had open most recently and stores these in a prefs file so that when you update your prefs are remembered).

Go to the view menu and select Builder view
