### ISSUE TITLE
request error :error

### ISSUE THREAD

**Issue by SucciWang** [psychopy/psychopy#2116]

**Comment by SucciWang** [comment]
hello ! what's wrong with online study ? I couldn't open any experiment online , include mine.

**Comment by peircej** [comment]
We are looking into this. For future reference, a bit more information in the bug report would have been useful (e.g. a precise error message, a url for a test experiment etc...)

**Comment by peircej** [comment]
This is now fixed.

**Comment by SucciWang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thanks a lot!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wangdaileyan1016
                            
                    
                        
                            
                                    wangdaileyan1016@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/25/2018 18:17，Jon Peirce<notifications@github.com> wrote： 


This is now fixed.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
