### ISSUE TITLE
Mojave update breaks key recording

### ISSUE THREAD

**Issue by iancballard** [psychopy/psychopy#2139]
Hello,

I just updated to 10.14.2 from 10.14.1. I'm using Psychopy with python 3.5, installed as instructed on the install page. After the update, event.waitKeys() and event.getKeys() are not registering any keypresses. Waitkeys will wait indefinitely, despite the keypresses appearing in the terminal window. This was working moments before the upgrade. 

Any advice (beyond restoring from backup) would be appreciated!

Thank you,

Ian

**Comment by hoechenberger** [comment]
This MWE works for me (but only if I create a `Window`, which, I believe, is expected behavior):

```python
from psychopy.visual import Window
from psychopy.event import waitKeys, getKeys

win = Window(fullscr=False, allowGUI=True)
keys = ['space']

print('waitKeys() …')
waitKeys(keyList=keys)
print('… ok.')

print('getKeys() …')
while not getKeys(keyList=keys):
    pass
print('… ok.')
```

**Comment by iancballard** [comment]
Hi @hoechenberger. Thanks for the input. I misstyped-- I am running Python 3.6.6 (via anaconda). I just checked with the standalone version and keypresses are registering and if I run my code from there it works fine (but still not via terminal). I'm wondering if perhaps it has to do with security, as I had to authorize the standalone version before opening. I'm not sure how to add a security exception to an anaconda package.

**Comment by m-macaskill** [comment]
I think the security authorisation on a Mac is only necessary if you are using ioHub to collect your keypresses (as it uses special accessibility functions that allow it to intercept events that should be going to another window/process). The `PsychoPy.event` functions, meanwhile, can only capture keypresses directed to the PsychoPy process' own window, so there are no security issues.

**Comment by hoechenberger** [comment]
@iancballard I just tested with `Terminal`, without granting any additional access rights. Works without problems, just as suggested by @m-macaskill. The fact that you see the input characters appear in the terminal actually indicates that you didn't create, or at least didn't activate, a `psychopy.visual.Window`, which would capture the keystrokes.
