### ISSUE TITLE
Troubleshooting guide needs updates

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2152]
- [x] http://www.psychopy.org/troubleshooting.html#the-application-doesn-t-start
 mentions to  execute `"C:\Program Files\PsychoPy2\python.exe" "C:\Program Files\PsychoPy2\Lib\site-packages\PsychoPy-VERSION-py2.6.egg\psychopy\app\psychopyApp.py"`, but we've long stopped shipping Python 2.6 builds

- [x] http://www.psychopy.org/troubleshooting.html#cleaning-preferences-and-app-data only mentions PsychoPy 2 settings directories, but we'll soon have PsychoPy 3 directories too

- [x] The Windows paths
  ```
  ${DOCS AND SETTINGS}\{USER}\Application Data\psychopy2\appData.cfg
  ${DOCS AND SETTINGS}\{USER}\Application Data\psychopy2\userPrefs.cfg
  ```
  actually look different on Windows 10 (didn't check other Windows versions); should probably be sth like `%APPDATA%\psychopy...`

**Comment by peircej** [comment]
I think these are all fixed. The first is improved by the fact that we can do:

    python -m psychopy.app.psychopyApp

(so the user doesn't need to know where the lib actually is at all, but they do need to use the correct `python`)

The second is tricky but I've now provided a command to tell the user the how to find the folder on their own system using `psychopy.prefs`

The 3rd I've mentioned `%APPDATA%\psychopy` (but users that struggled before will probably struggle with tat too!) and the above strategy as well.

**Comment by hoechenberger** [comment]
Haha, sorry, I missed the fact that this is currently in a PR that will close this issue. Reopening until then :D
