### ISSUE TITLE
Changes to Builder readme files are lost when window is closed without prior explicit saving

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2161]
<strike>Either we save the edited readme alongside the project, or we should disable editing.</strike>

**Comment by hoechenberger** [comment]
Ok so this seems to be a UI issue:

When the Readme is opened, edited and closed, all changes are lost without further notice.

When the Readme is opened, edited, the experiment is saved and Builder is quit, all changes to the Readme are lost, too.

To retain changes to the Readme file, one has to 
- realize the entire menu changes when the Readme is opened
- use `File / Save` to save the Readme

Expected behavior for me would be

- getting asked whether to keep the changes when the readme is closed or PsychoPy is being quit
- potentially, Readme should be automatically saved alongside the experiment whenever the user chooses to save it

**Comment by peircej** [comment]
I think we should definitely allow editing, and probably save the file every time its window closes (i.e. no need for explicit save either in the window or in the experiment

**Comment by TEParsons** [comment]
Editing README is now done in Coder, so this no longer applies
