### ISSUE TITLE
Potentially add UTF-8 BOM header to data files

### ISSUE THREAD

**Issue by heaton2016** [psychopy/psychopy#2166]
Hi Jon:
I find this problem when I'm running a quite simple program, and I've found a way to fix it. Just change 'utf-8' to 'utf-8-sig' in experiment Handler when saving. Maybe this experience can do some help.

 [problem] In this study, I created a condition.xlsx to make Instructions change in every repeat. And I have to input the instructions in Chinese. When I run the program, everything is quite fine.Of course, Chinese characters can be displayed quit well. However, the `.csv `file in the output data folder was in a mess, especially the columns including Chinese instructions. 

[fix] And I track to psychopy.data.experiment.saveAsWideText() function. In this function, the parameter `encoding = 'utf-8'` may not be suitable for windows system, so I change it to `utf-8-sig.` Finally, the output file is correct.

Therefore, I'm wondering if this experience could help us to make psychopy3 more compatible to windows PC? Especially in Non-English countries.
p.s.
Thank you for your excellent efforts for psychology researches :+1: . And if you are interested in seeking cooperation in China, don't hesitate to contact me. And I own a Master's Degree in Applied Psychology in East China Normal University, ShangHai. :)

[some information]
Psychopy version: v3.0.0.b13
OS name: Microsoft Windows 7 enterprise
OS version: 6.1.7601 Service Pack 1 Build 7601

**Comment by heaton2016** [comment]
Hi @hoechenberger 
Thank you for your suggestion! I've installed LibreOffice just now. The CSV file containing Chinese character is not tidy until I set LibreOffice as default. You are right, EXCEL may add BOM to the file.

I agree with you. UTF-8 is quite well, considering we need to use R for analysis. `utf-8-sig` should never replace 'utf-8'.

However, I'm afraid that most Windows users use Excel to open CSV file, which may frustrate these Psychopy learners when their non-English files are messy. Especially when their mother language is not English, they are more likely to use other languages in the condition file. Maybe we could find out other solutions to it, for example add a Tip for windows users :)

**Comment by hoechenberger** [comment]
Needs tests (CSV condition file with non-ASCII characters in both header and body, with BOM).

**Comment by peircej** [comment]
Can you upload a csv with this encoding so I can take a look and test on a couple more things? (Excel and SPSS are the most common apps for users)

**Comment by hoechenberger** [comment]
Sure: [example.csv](https://github.com/psychopy/psychopy/files/2717537/foo.csv.txt)

**Comment by hoechenberger** [comment]
@peircej You can also create your own using the code snippet I posted above

**Comment by peircej** [comment]
> @peircej You can also create your own using the code snippet I posted above

Ah yes, sorry! :-) I can't see a way to even detect the difference between these files, let alone find a way they break existing behaviour so I agree that if this fixes an issue for someone (as it apparently does) then this should be new default for writing files.

**Comment by hoechenberger** [comment]
> I can't see a way to even detect the difference between these files

If you're on macOS, what you can do is view the file(s) with `less` in the terminal; it displays the BOM for me.

**Comment by peircej** [comment]
I'm actually feeling pretty comfortable that this isn't going to cause any problems, or it does they'll be pretty rare corner cases. Rare enough that having one more beta release probably won't reveal the problem (we'll need thousands of testers before one finds a problem and we'll only get that when we release final 3.0.0)

**Comment by hoechenberger** [comment]
I leave this up to you :) But I also think we've done some quite thorough testing, so should be good in MOST cases!!
