### ISSUE TITLE
Last Component in a Routine might have unexpected duration

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2169]
The Builder creates Routine code like the following (here: with a `TextComponent` in the Flow that is to be displayed for 10 frames):

```python
while continueRoutine:
    ...
    # *text* updates
    if text.status == STARTED and frameN >= (text.frameNStart + 10):
        text.setAutoDraw(False)
    
    # check if all components have finished
    if not continueRoutine:  # a component has requested a forced-end of Routine
        break
    continueRoutine = False  # will revert to True if at least one component still running
    for thisComponent in trialComponents:
        if hasattr(thisComponent, "status") and thisComponent.status != FINISHED:
            continueRoutine = True
            break  # at least one component has not yet finished
    
    ...
    
    # refresh the screen
    if continueRoutine:  # don't flip if this routine is over or we'll get a blank screen
        win.flip()
```

What is interesting here is the last 3 lines:
```python
    # refresh the screen
    if continueRoutine:  # don't flip if this routine is over or we'll get a blank screen
        win.flip()
```
They cause the stimulus to remain on screen **even after the user-requested duration has passed**. This is **always** the case for the _last_ stimulus in _any_ Routine.

This behavior is commonly _hidden_ because as soon as the _next Routine starts_ or _the experiment ends_, we will flip again so the behavior is _not obvious_.

Now if we were to assume my experiment consisted of two Routines: the one shown above, and another one that does some preparatory calculations before it actually starts. Let's further assume these preprations of the second Routine take longer than one screen refresh. In that case, we will "skip" or "drop" one frame, and the duration of my `TextComponent` would be extended by this one frame.

It may also lead to `win.callOnFlip()` calls getting delayed or never executed (at the end of an experiment), as is the case e.g. with the `ParallelOutComponent`.

This was already briefly dscussed with @m-macaskill and @peircej a couple weeks back, and while I don't remember the details, I _do_ remember that we agreed this behavior is typically not what a user expects. (Personally, I consider it a bug, because stimulus duration might deviate from what the user requests.)

I have been working on a fix, for which I will open a PR.

**Comment by peircej** [comment]
The reason it works like this is that until we know what the frame *after* the current one should be we shouldn't flip. We have to render the first frame of the next routine before we can end the current routine. In most cases this *does* do the right thing. If we added something here that immediately flipped to a blank screen then in most cases we would *not* do the right thing - we would have a blank screen in between all Routines and no way for them to progress smoothly from one to the next.

**Comment by hoechenberger** [comment]
Ooooh now I see. So this is actually not too trivial to fix then? Since we don’t know how long the following Routine will take until it’s ready to flip... damn. :/

--

**Comment by hoechenberger** [comment]
So the main issue here seems to be in my (previous) understanding of a Routine being some sort of an “isolated” entity. Whereas if one considers the entire experimental Flow as a whole, potentially spanning multiple Routines, one simply has to follow the ordinary rules: nothing you do should take longer than one screen refresh.

Which would reduce the issue to the fact that we never flip at the very end of an experiment, which seems to be a minor issue (but may lead to confusion during testing, because e.g. the `ParallelOutComponent` will not switch its trigger lines back to LOW if it’s the last Component in the experiment and the user selected to sync activity to the screen refresh)

**Comment by peircej** [comment]
Yes, that's basically it. If there is a timing error then probably the best fix will be in the beginning of the *next* routine, rather than introducing a new flip between them. 
The issue you're thinking of will only occur if the first frame of the next routine takes too long (e.g. because an image is being loaded "on every repeat" which means during the first frame).

Things I can think of to help:
- provide a warning that expected timing was not achieved so that people at least know (without having to check log files
- some work on the static component so that if that is set to run from t=0 it actually draws the first frame and *then* goes into its static mode to make sure the first frame does get drawn. (It might be this is already being done - I haven't checked yet)
- integrity checks during script compile should warn the user of things that are *likely* to cause bad timing (e.g. loading an image "on every repeat")
