### ISSUE TITLE
Add timing audit data to .csv output files

### ISSUE THREAD

**Issue by njvack** [psychopy/psychopy#2187]
After [trying some things to get stimulus start time into my output CSV file](https://discourse.psychopy.org/t/logging-stimuls-start-and-end-or-onset-and-offset-with-builder/6196/3), my next thought was... Maybe this stuff belongs in the actual Component code generators?

My next next thought was to subclass `TextComponent` but I don't think there's a way to inject what I want where I want it.

I think adding some `addData()` to the setAutoDraw areas of the python and javascript generators (in either BaseComponent or BaseVisualComponent) would do what I want.

But that leads to a few questions:
* Do you even want that functionality in psychopy?
* If so, would you want it behind a component configuration checkbox? (I'd have no problem with these fields for every component, but that might be too verbose for folks sometimes?)

**Comment by peircej** [comment]
Yes I've actually been thinking about adding this myself. Critically, at least for visual stimuli, we want the timestamps to reflect the time of the screen refresh e.g. by using a callOnFlip command you record a timestamp. 

And then, yes, I do wonder if we want to Maggie it an option of the stimulus whether to save it. Some experiments have a lot of components and this would add 2 columns for every component

**Comment by njvack** [comment]
I think it's better to have the columns there; at very least it should default to on. Having too many columns in a file is a little annoying, but I've had multiple times where we have 200 data files and then say "hey we wish we had more time logging in there, too bad though."

Excel and R and pandas can all handle a million columns just fine.

**Comment by njvack** [comment]
Thinking a bit more: I really want it for input components as well. If I'm getting RT from a keyboard, I want to know what time it's relative to if I'm going to do an audit.

**Comment by njvack** [comment]
I've bodged this into my local copy of psychopy and it looks like it does what I want. I could submit a PR, but at the same time, the code is trivial and incomplete for psychopy as a whole — it doesn't support the javascript generators, doesn't have tests, and doesn't make start/stop times optional; it just always writes them.

Getting all that up and going will be hard-ish for me — I don't even have a proper psychopy dev environment going, and have been just hacking up my app bundle (yes, I am a terrible person).

Would it still be helpful to file a PR in this condition?

**Comment by peircej** [comment]
Thanks. I do intend to write something on this line myself soon. If you get a chance to submit it then I could use it to check and maybe use it for inspiration. If you're new to this then try to make your changes in a different branch of your repo, not the master. That way if you ever fix other bugs then the changes you make to this stuff won't get in the way.

Just to be clear, are the timestamps you're using:

- a global time (from start of experiment in secs)?
- a universal time (e.g. unix time)?
- something else?

**Comment by njvack** [comment]
Thanks! I'll push to a feature branch.

I'm using core.monotonicClock.getTime(), which seems like the global-est clock without going all the way to unix epoch time. I'm coming to psychopy from the eprime world, and this basically how time reporting works there.

There's also a global clock defined in the generated script, but I don't know why I'd ever want that instead of core.monotonicClock — probably they should just be the same clock...?

**Comment by hoechenberger** [comment]
I believe this was closed via #2213.
