### ISSUE TITLE
Troubling with Installation

### ISSUE THREAD

**Issue by H0616** [psychopy/psychopy#2188]
I am having an extremely hard time installing pyschopy. I have python installed and Github. It looks like I have downloaded pyschopy but am unable to open it? I have done this in the past and it was simple but now I can not seem to open it.

**Comment by hoechenberger** [comment]
Hello, this is by far not enough information to really help you. Please try downloading one of the standalone installers appropriate for your computer platform, available from https://github.com/psychopy/psychopy/releases, and try again.

**Comment by m-macaskill** [comment]
Also note that user support is available from the forum at https://discourse.psychopy.org

Please go there for guidance and help with _using_ the software. This site is really for _developing_ the software (i.e. reporting and fixing bugs, requesting and adding features, and so on).
