### ISSUE TITLE
python code conversion of JS in online experiment (Pavlovia)

### ISSUE THREAD

**Issue by Katsuragiai** [psychopy/psychopy#2194]
Dear all, 

We are looking to publish our psychopy experiment on pavlovia, and we understand that we need to manually translate our python code to Javascript code in order for custom code components to work. After some unfruitful searches, we still don't understand why our simple code block does not work (system gives the error message: "group" undefined). I'm posting the code component here.

Python: 
```
import numpy as np

result = np.random.randint(2)


if result == 0:

   Group = "BlockRandomizationFile_1.xlsx"

else:

   Group = "BlockRandomizationFile_2.xlsx"


```

JS: 

```
var Group = "BlockRandomizationFile_1.xlsx";

var test = Math.floor(Math.random() * 2);

switch (test){

    case 0:

        Group = "BlockRandomizationFile_1.xlsx";

        break;

    case 1:

        Group = "BlockRandomizationFile_2.xlsx";
```

what we are doing here is a two step thing: 

1. generate a random number between 0 and 1. 

2. according to the number generated, we create a variable "Group" and assign it with one of our block order files. 

Thanks in advance!

**Comment by dvbridges** [comment]
Hi Katsuragiai, if "group" undefined is your actual error, then you may want to look at the case of your ```group``` variable. JavaScript is case-sensitive, where ```group```  and ```Group``` would refer to different variables.

Questions relating to experiment code are better posted on the [PsychoPy forum](https://discourse.psychopy.org/). On the forum, you may find more users who can help, and your problem and solution will be helpful to others with similar problems. The GitHub repo issues are for issues with the PsychoPy program itself.

**Comment by m-macaskill** [comment]
Closing this issue because, as noted, it relates to the use of the software rather than development _per se_. Support is available at https://discourse.psychopy.org
