### ISSUE TITLE
How to get repeated keys in Psychopy (Pyglet backend)

### ISSUE THREAD

**Issue by bpinsard** [psychopy/psychopy#2215]
I am running scripts in Psychopy3 on ubuntu18 and I cannot get repeated keys when a keyboard key is kept pressed down.
The backend is Pyglet and the key repeat is activated in Ubuntu settings.
Any ideas?
Thanks.

**Comment by peircej** [comment]
Yes, holding the key down counts as a single press in Pyglet and in PsychoPy. It does not fire repeated events.
