### ISSUE TITLE
Issue downloading standalone PsychoPy for Mac

### ISSUE THREAD

**Issue by golnousha** [psychopy/psychopy#2219]
Hi there,

I have attempted to download the most up to date standalone PsychoPy for Mac "StandalonePsychoPy3-3.0.1-MacOS.dmg" but the download stops after a few mins. Each time, I see one of the following errors "Failed - Forbidden" or " Failed-Network error".  Is the download restricted to a given browser?

Any help would be much appreciated! Thank you in advance.

**Comment by peircej** [comment]
No. It is a large package. Maybe you're on a slightly slow network and it just gives up because it's taking too long? But I just checked andit downloads fine for me. Not much we can do about this one I'm afraid
