### ISSUE TITLE
pyqmix missing in Windows standalone

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2221]
It appears [`pyqmix`](https://pypi.org/project/pyqmix/), which is required to operate syringe pumps, is currently missing in the Windows standalone distribution

(NB it only works on Windows anyway, so does not need to be bundled with the macOS distribution)

**Comment by peircej** [comment]
I've just added to my dev installs on windows and planning to release a 3.0.2 today (bugfixes only) so it should be there :-)

**Comment by hoechenberger** [comment]
Wow neat, thank you!!

**Comment by peircej** [comment]
Is uploaded already ready for testing
