### ISSUE TITLE
the PIXI representation of the stimulus is unavailable.

### ISSUE THREAD

**Issue by huppfi** [psychopy/psychopy#2227]
When trying out my Experiment on Pavlovia the Error in the Title gets thrown. The experiment works just fine locally. 

All it does is show 3 pictures in a row and then let's people rate it.

**Comment by apitiot** [comment]
@peircej I could not reproduce the issue with peircej/posner3 on my end. The experiment works fine on both Firefox and Chrome (Linux and tablet). Would you mind trying it again?

@huppfi Could you let me know which experiment you are running?

**Comment by huppfi** [comment]
Hey, first of all thanks for looking into it. 

Here is some more information. 
When I start the Experiment on Chrome this happens.
![image](https://user-images.githubusercontent.com/8363426/51824615-08149d00-22e3-11e9-99b8-96cbb81512fe.png)

The Inital Error doesn't happen anymore(eventhough I didn't change anything) but now this happens:
![image](https://user-images.githubusercontent.com/8363426/51824811-8ffaa700-22e3-11e9-98da-3f3afd87a64c.png)

Heres the Link to the study: [https://pavlovia.org/run/huppfi/test4/html/]( https://pavlovia.org/run/huppfi/test4/html/)

**Comment by huppfi** [comment]
![image](https://user-images.githubusercontent.com/8363426/51829909-e6b9ae00-22ee-11e9-8954-0ca43bbb34fb.png)

OK thanks to @dvbridges I fixed the text issue myself and got the Old error again

I made a new Study to test everything out: [https://pavlovia.org/run/huppfi/ratingfood/html/](https://pavlovia.org/run/huppfi/ratingfood/html/)

@apitiot @peircej

**Comment by huppfi** [comment]
Ahh that might be it. I directly set the image in a Code Component.

**Comment by huppfi** [comment]
This is my Image Stimulus(prime):
![image](https://user-images.githubusercontent.com/8363426/51833664-5da77480-22f8-11e9-8a4f-35f9b915e422.png)

And this is the code component in the same routine:
![image](https://user-images.githubusercontent.com/8363426/51833684-6b5cfa00-22f8-11e9-8e22-ae213474cf0a.png)

![image](https://user-images.githubusercontent.com/8363426/51833699-7879e900-22f8-11e9-904b-29c5737f0b33.png)

**Comment by dvbridges** [comment]
Ok, do you have the equivalent code in the JS code view? You can access this by setting "Code Type" as JS, or for easier translation, select "Both".

**Comment by peircej** [comment]
Right now you've got Python code there but no JavaScript code. Change your code component to show "Both" and write the equivalent JS code.

**Comment by huppfi** [comment]
Oh wow I am an Idiot, no the JS view is empty. Didn't realize I have to write the JS code myself. Thank you so much!

**Comment by huppfi** [comment]
Everything works now thanks!
