### ISSUE TITLE
Probably incorrect write modes in a few places

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2237]
`tools.wizard.BaseWizard.save()` [opens](https://github.com/psychopy/psychopy/blob/64449dd68b7e5c0d01d9f893c333821edebe1289/psychopy/tools/wizard.py#L492) a file in `wb` mode where it should probably be `w` instead (it's a text file). While fixing, we should probably also switch from using `codecs.open()` to `io.open()`.

**Comment by hoechenberger** [comment]
Same in [`experiment._experiment.Experiment.saveToXML()`](https://github.com/psychopy/psychopy/blob/64449dd68b7e5c0d01d9f893c333821edebe1289/psychopy/experiment/_experiment.py#L308)

**Comment by hoechenberger** [comment]
But we're also passing an encoding, which typically doesn't make sense for `b`inary files… I will do some testing after lunch! :-)

**Comment by hoechenberger** [comment]
Yes but that's not what I meant :) What I meant was, we should check whether the `encoding`kwarg even has an effect when using binary writing mode, or whether it gets silently disregarded.

**Comment by hoechenberger** [comment]
You are right about the effect on line endings on Windows, though.

**Comment by peircej** [comment]
Using `io.open()` (or python3 `open()`) with 'wb' and `encoding` gives an error:
```python
>>> with open("test.xml", "wb", encoding="utf-8") as f:
...  f.write("Richard Höchenberger\n")
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: binary mode doesn't take an encoding argument
>>> 
```
but the existing code uses `codecs.open()` with mode `'wb'` and `encoding='utf-8-sig'` and that's apparently fine.

**Comment by hoechenberger** [comment]
Very interesting!

**Comment by peircej** [comment]
`open()` now has a newline param (which seems to make 'wb' somewhat redundant?) so we could now do 
```
with io.open(filename, mode='w', newline='\n') as f:
    ...
```
and I *think* that would work. Or we could just carry on using codecs lib with the policy of "if it ain't broke don't fix it"

**Comment by hoechenberger** [comment]
Hah, check this one out:

> Note Files are always opened in binary mode, even if no binary mode was specified. This is done to avoid data loss due to encodings using 8-bit values. This means that no automatic conversion of '\n' is done on reading and writing.
https://docs.python.org/2/library/codecs.html#codecs.open

**Comment by hoechenberger** [comment]
> Or we could just carry on using codecs lib with the policy of "if it ain't broke don't fix it"

Yep, agree. Just thought I might have found a bug there when I first saw these lines of code!

**Comment by hoechenberger** [comment]
Going to close this for now.
