### ISSUE TITLE
Travis currently not building

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2238]
I believe the problem we're having with Travis right now is the one mentioned here: https://github.com/pypa/pip/issues/6165

It's related to a recent `pip` update to 19.0:

> pip 18.1 was a lot kinder, but would generate invalid RECORD files and fail to properly handle uninstalls.

**Comment by peircej** [comment]
We just noticed that one too. _Strict_ is OK, but _working_ is better! 😉 
Should we disallow 19.0? I bet they'll fix this in 19.1 because I imagine a lot of travis python testing just broke!

**Comment by hoechenberger** [comment]
@peircej ;)

I just proposed a PR to (temporarily) pin pip to <19.0. I suggest we follow the discussions about this issue on their side. I wonder why we're running into this problem anyway, are we doing something wrong?

**Comment by hoechenberger** [comment]
I had a look at the `RECORD` file created by `pip wheel`. There is a number of invalid entries (lines 998ff):

```
psychopy/tests/data/winScalePos_ori0_scale-1,-1_pos-0.4,0.png,sha256=GzFxAFXYZKYHbSl6-csyIL0BytopsEnlIvw9hgOAj8A,1530
psychopy/tests/data/winScalePos_ori0_scale-1,-1_pos0,0.png,sha256=2QU6uKnT4JniZWVXzH-JvM72xx5fdGNqKlmrHfDbCag,1538
psychopy/tests/data/winScalePos_ori0_scale-1,1_pos-0.4,0.png,sha256=Drh-P9SI8A_78q6-6sZpDge01hFRBHmm81O_1XO_AWs,1549
psychopy/tests/data/winScalePos_ori0_scale-1,1_pos0,0.png,sha256=JuJgP-EISHEql5-KXY4_3-6-fde5esfnlYZ8AWS0LO8,1549
psychopy/tests/data/winScalePos_ori0_scale-2,-2_pos-0.4,0.png,sha256=rxPyVKxvQWV44DpBuDVBbkoIcNwowEzgVEIu8GzhFzM,2294
psychopy/tests/data/winScalePos_ori0_scale-2,-2_pos0,0.png,sha256=5lFV8g-MdUD5aq2VfA3hTMWR_fNv48KQsf9SznDCp3Y,2328
psychopy/tests/data/winScalePos_ori0_scale-2,2_pos-0.4,0.png,sha256=-EilGzg2c7y9CzQmiSCg05ZInp287f39MRwsRGnvNKk,2364
psychopy/tests/data/winScalePos_ori0_scale-2,2_pos0,0.png,sha256=R6sv7LRryDC8P4MooSyQjc2AfOiwIkJy1HEbwRVoeVY,2397
psychopy/tests/data/winScalePos_ori0_scale1,-1_pos-0.4,0.png,sha256=rdtIlp1xxPKXB5E7zurk6IGvlXYd46FT_8YTVt6QrHw,1575
psychopy/tests/data/winScalePos_ori0_scale1,-1_pos0,0.png,sha256=uF1dEUlgx6chKt7ph3nA_2VKUxOEv-N8bgMDcFSlXYo,1557
psychopy/tests/data/winScalePos_ori0_scale1,1_pos-0.4,0.png,sha256=tGsNaK_i8-vO94ukHGO44drYJxbniLKpo0XeZgulVUk,1507
psychopy/tests/data/winScalePos_ori0_scale1,1_pos0,0.png,sha256=9PyQN_qXtsDAcW0pxK1OQs_pvvX-FYqmc_Gt6SlEraM,1496
psychopy/tests/data/winScalePos_ori0_scale2,-2_pos-0.4,0.png,sha256=dI4Qje8bhi1N6Dra7OMyZN_-lHz-aSHS21Cb8jPMhBo,2301
psychopy/tests/data/winScalePos_ori0_scale2,-2_pos0,0.png,sha256=ysUR8mFeiLNvGe5LfcYFEnttnuZNqk4c0Ahy0X5Tnmw,2335
psychopy/tests/data/winScalePos_ori0_scale2,2_pos-0.4,0.png,sha256=HMc6Y2g3Cc4D9WyHrTKIMFjSlC0RezsjIJkk8oWScmM,2400
psychopy/tests/data/winScalePos_ori0_scale2,2_pos0,0.png,sha256=In8xpTkkfuFhr1QWVzVFXGP-M9nmmvBWhgXtSdvcn3k,2432
psychopy/tests/data/winScalePos_ori45_scale-1,-1_pos0,0.png,sha256=MHrkINIBwfdpe3uBoglkM8b2PvaF6VEdNOSf50Xsg4U,2221
psychopy/tests/data/winScalePos_ori45_scale-1,1_pos0,0.png,sha256=FAQwDffzCoV9_hr-fe19V9Vl2hXtdzLRSY01O63037w,2108
psychopy/tests/data/winScalePos_ori45_scale-2,-2_pos0,0.png,sha256=3oVe17xBOs9iaxEg0HWF3nA2AeygfASC7yPwq64RRak,4758
psychopy/tests/data/winScalePos_ori45_scale-2,2_pos0,0.png,sha256=uhfLLgjikaGblub8xpfKpLBwoOOeo8PeucTQzI2fupU,4528
psychopy/tests/data/winScalePos_ori45_scale1,-1_pos0,0.png,sha256=0cBjqqnpobTbCchy-RD7N5jcfORlBG6TfsAd9qF7jg4,2071
psychopy/tests/data/winScalePos_ori45_scale1,1_pos0,0.png,sha256=wX6Cblrzpc-9BGYRfaemHLBnRSeWaaSQVyXT0OwKJXc,2250
psychopy/tests/data/winScalePos_ori45_scale2,-2_pos0,0.png,sha256=u20yZ5lqXLUJvvyCQx61VrMXxq7jUtjtrDRStucycu4,4630
psychopy/tests/data/winScalePos_ori45_scale2,2_pos0,0.png,sha256=zbf9wghNAz1-VjGN8_9N9NqBr_k-tSEEOCD3mWce_3w,4841
```
Each row is supposed to have 3 values only. These contain five. Question is, how do they come into existence?

----

Hah. These filenames actually do contain commas. We should probably rename them.

Related issue: https://github.com/pypa/wheel/issues/280

**Comment by hoechenberger** [comment]
(We could also just wait for the `wheel` folks to fix the issue :))

**Comment by hoechenberger** [comment]
Just wanted to point out again, more explicitly, that while the next `pip` bugfix release (19.0.2) is going to work for us again, we will still end up with invalid entries in the `RECORD` file. This is a bug that needs to be fixed in `wheel` (pypa/wheel#280).

**Comment by peircej** [comment]
I'm happy just to change those filenames though so that they don't contain commas. It's looks like we could do this just by removing the commas from:
https://github.com/psychopy/psychopy/blob/26dc8c9a7e2faa8d306aac44ccd3f28caf2159fe/psychopy/tests/test_all_visual/test_winScalePos.py#L76
```
                    scalestr = str(scale[0]) + ',' + str(scale[1])
                    posstr = str(offset[0]) + ',' + str(offset[1])
```

BUT bizarrely when I try to run the test it always skips this test anyway so the files never get (re)generated. I can't work out why it's skipped (we don't request the skip).

**Comment by peircej** [comment]
Well, even more weirdly, now some of the tests run (so new files have been saved) but not all of them:
https://github.com/psychopy/psychopy/pull/2243/commits/65e6e3c2510dee1b8c6217de27cea479968ac9ed

**Comment by peircej** [comment]
Ooooh, I've got it. The test was skipped by `compareScreenshot` which only expected one screenshot per test, This single test has many screenshots so they get created one per test and then a skip

**Comment by hoechenberger** [comment]
Meanwhile, `pip` 19.0.2 has been released that doesn't fail, but displays a warning when encountering an incorrect `RECORD` file: https://pip.pypa.io/en/stable/news/#id1
