### ISSUE TITLE
Error when using pavlovia, PIXI representation of the stimulus is unavailable 

### ISSUE THREAD

**Issue by phenomify** [psychopy/psychopy#2249]
When launching my experiment I am met with these error messages:

1.When setting the autoDraw attribute of stimulus: image
2. The PIXI representation of the stimulus is unavailable

This is a simple rating task of image stimuli. This was created entirely in builder mode.

https://pavlovia.org/run/niewrzol/test/html/

What am I doing wrong?

**Comment by peircej** [comment]
I just tried your task and didn't get an error (Mac chrome). Is it still showing a problem for you or did you resolve this somehow?

**Comment by Edward250250** [comment]
> I just tried your task and didn't get an error (Mac chrome). Is it still showing a problem for you or did you resolve this somehow?

I have exactly the same issue. Here is my experiment.
https://pavlovia.org/run/edward250250/pocker/html/

It happens all the time, it runs well on psychopy but not on pavlovia. Can you please kindly take a look at it?

**Comment by peircej** [comment]
I took a look at the pocker experiment, but when I looked at the files I was puzzled what the actual experiment is. Is it called crash.psyexp? It seems to be a single image stim set to be None. When you say it runs well on PsychoPy what does it do exactly?

**Comment by Edward250250** [comment]
> I took a look at the pocker experiment, but when I looked at the files I was puzzled what the actual experiment is. Is it called crash.psyexp? It seems to be a single image stim set to be None. When you say it runs well on PsychoPy what does it do exactly?

Thank you very much for replying to me.
The actual file that has the logic is "crappy two screen.py". When I run it in Psychopy, it will use two screens. The experiment allows  two person to bet their poker numbers the bigger one wins. So the local experiment will display the two pictures on each screen. However on pavlovia, after I enter the participant and session, and wants to display the poker card image, then the error occurs.

"1.When setting the autoDraw attribute of stimulus: image
2. The PIXI representation of the stimulus is unavailable" 

Can you please kindly let me know where should I focusing on and how to fix the issue. I have stuck on this issue for few days and can't make it work.

Thanks you in advance.

**Comment by Edward250250** [comment]
Based on the hint you gave, I probably found the issue. There are many .py files which are not related are all stored in the folder. I found one unrelated file called crash_lastrun.py has the following code.

# Initialize components for Routine "trial"
trialClock = core.Clock()
image = visual.ImageStim(
    win=win, name='image',
    **image=None**, mask=None,
    ori=0, pos=(0, 0), size=(0.5, 0.5),
    color=[1,1,1], colorSpace='rgb', opacity=1,
    flipHoriz=False, flipVert=False,
    texRes=128, interpolate=True, depth=0.0)

I am going to remove those files and try it again. Hopefully it is the root cause.  Keep finger crossed.

**Comment by Edward250250** [comment]
> I took a look at the pocker experiment, but when I looked at the files I was puzzled what the actual experiment is. Is it called crash.psyexp? It seems to be a single image stim set to be None. When you say it runs well on PsychoPy what does it do exactly?

I removed all the .py file that could be able to affect the behavior and generate a new project.
https://pavlovia.org/run/supermario000/slim-poker-experiment/html/
However the issue still occurs.

Couldn't find which " single image stim set to be None" as you mentioned?

**Comment by dvbridges** [comment]
I think your problem with running this study, is that `image` is passed an image, and so stays undefined. I think that is why you get the pixi error.
