### ISSUE TITLE
Builder icons corrupted on Ubuntu 18.04

### ISSUE THREAD

**Issue by mdovgialo** [psychopy/psychopy#2254]
Good day.
I'm using psychopy on Ubuntu 18.04.1, and have this problem. Icons in the builder are corrupted:
![image](https://user-images.githubusercontent.com/6193380/52220778-f82b2900-289f-11e9-91e4-579875ebea11.png)
This occurs randomly, different icons can be affected every psychopy launch.

I get this output in the terminal when I launch psychopy:
```
(psychopy-upstream-env) marian@marian-Lenovo-E5:~/psychopy-upstream/psychopy$ psychopyApp.py 

(psychopyApp.py:9094): Gtk-WARNING **: 17:25:55.509: Theme parsing error: gtk-main.css:73:38: Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css: No such file or directory
05:25:55 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
05:25:55 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
05:25:55 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'


```

I've tested psychopy versions 3.0.0, 3.0.3 and from master ( commit 494d7fe4e7b24e41b67a692f1a077b1d308ac9ed )
Tested different wxPython versions: 4.0.4, 4.0.0, 4.0.1. All compiled automatically using pip.
Tested different desktop enviroments: gnome and KDE. Nothing helps.

Anyone have this problem too?

Additionally buttons on the sidebar change to black color after hovering over them, this persists until you change focus to another window. Same psychopy/wxPython versions.

![image](https://user-images.githubusercontent.com/6193380/52221792-3d505a80-28a2-11e9-9e62-9a6193233605.png)

I might help, I've been customizing psychopy for my needs before but I have no idea where to start on this one.

**Comment by peircej** [comment]
I have seen the former issue myself. Like you I don't really know where to begin, given the unpredictable nature of it. :-(

**Comment by TEParsons** [comment]
Does this still happen with v2020.2.x? We have all new icons so the question is whether it's those files which were corrupt or something corrupting whatever file is used for that purpose...

**Comment by peircej** [comment]
I think it's more likely that the issue was the image importing method, but that has actually changed too. I don't have a linux box in my home office to test on (although I could spin up a virtualbox I guess)

**Comment by TEParsons** [comment]
I think #6276 should fix this - assuming this error comes from the same place as the "iCCP known invalid format" warning on Windows with classic icons.
