### ISSUE TITLE
Allow non-slip timing for durations defined by variables

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#2255]
_Apologies for the length of this, but it might be useful to provide context for the problem to then explore how it might be resolved._

Builder has a long-standing issue that leads to unnecessary accumulation of timing errors across consecutive trials. At the moment it makes a distinction between routines whose duration is known "at compile time", which get non-slip timing applied (and the cherished green routine icon in the flow panel). If the duration is not known in advance (e.g. because it is dependent on a participant response), then that form of timing can not be used, and the routine is coloured red:

https://github.com/psychopy/psychopy/blob/master/docs/source/general/timing/nonSlipTiming.rst

However, deciding which routines are eligible for non-slip timing is currently overly strict. e.g. if the duration of any of the stimuli within a routine is defined by a variable rather than a literal numeric value, then non-slip timing is not applied. This is despite the fact that even if the value of that variable is not known at the time the script is generated, it will be known at runtime, before the routine begins. Therefore, the value of that variable could be used in place of a literal value with no issue at all. 

This can be demonstrated by editing a generated non-slip timing script to use a variable to specify trial duration. Let's say a routine contains a single stimulus with a duration of a constant 1.0 seconds, expressed as a literal value of 1.0, in a loop that runs 60 times. Non-slip timing will be applied, and the loop will run for almost exactly 60 s. But let's say the design requires the duration to vary across trials pseudo-randomly (20 trials each of 0.5, 1.0, and 1.5 seconds). The total duration should still be 60 seconds, but now the actual performance will run slightly longer than that, as non-slip timing will not be applied, due to the stimulus duration being specified as a variable. But if the generated non-slip version of the script is manually edited, with the variable name simply replacing the literal `1.0` value, it will run perfectly well and finish exactly at 60 s.

This sort of requirement (of consecutive trials of variable but deterministically-specified duration) is crucial in any task that requires staying in sync with some specified timeline (e.g. an fMRI acquisition sequence, or presenting words in time with an audio track playing in the background), and the absence of non-slip timing very quickly accumulates apparent errors over anything more than few repetitions.

Would it be possible to disallow "non-slip" timing only when it is actually impossible (e.g. when durations or end times are unspecified or contingent on a condition?) i.e. if duration, time, or frameN is specified with a variable name, that variable name should be treated just like a literal value in constructing an expression for the total duration of the routine.

I've tested this by manually editing scripts which have just a single duration specified, but things would naturally get more involved when dealing with multiple components, some or all of which might have variables in their duration or time fields. The key function in determining whether non-slip timing will be applied is `getMaxTime()` in `routine.py`:
https://github.com/psychopy/psychopy/blob/494d7fe4e7b24e41b67a692f1a077b1d308ac9ed/psychopy/experiment/routine.py#L382

This returns a `maxTime` value and a boolean specified whether non-slip timing can be applied. I guess it might need to be modified to return a list of times and variable names rather than a single numeric variable, which could then be used in a `max()` function in the line which determines the duration of a non-slip routine, in place of the current literal numeric value.

I'm reluctant to try to make changes to this function, and the code that handles its result when generating the script, as I'm not sure I really understand it and so am also not sure that I wouldn't introduce unintended consequences.

Any comments on this? Is it worth pursuing? I'd say it is, because it really does hamstring users in generating reliable scripts that are intended to produce long runs of consecutive trials, and those users will often be surprised by that non-obvious behaviour (the red/vs green routine icons notwithstanding).

**Comment by peircej** [comment]
I agree that it would be great to solve this. The tricky thing is how to do so. 

Options: 

**1. determine at run time (not compile time) if we could use non-slip.** That would correctly allow a time test that is variable between trials but known at the start of each. The reason we currently want to try and detect non-slip at _compile_ time is that the code is actually different according to which it uses (a `while` loop for non-slip and a `for` loop for standard). **So, to make this work we'd need to rethink the code structure so that it's more similar between the 2 mechanisms**. That could be something like switching to use a for loop always and then adding a test with `continueRoutine=False` (so that it behaved like a `while`).

**2. set a value in the builder so that users can effectively override the components and enforce a given end time.** So far Routines don't really have settings of their own but we probably should go that route in the future. So a routine setting could be "forceEndAtTime"

**Comment by m-macaskill** [comment]
I guess I was thinking that we could retain the decision making at compile time, and the same while vs for code structure. i.e. a third option, which is basically just (hopefully slightly) modify what we currently do.

My rough idea is that we simply replace the fixed literal value for the `while` test. e.g. replace the literal value  in something like `while t < 3.0` with a `max()`. e.g. for a routine where we have several stimuli, some defined with a literal end time, another with a variable, and another with a start time plus a duration: `while t < max(3.0, fixation_dur, 1.0 + stim_dur)`. 

That is, the current `getMaxTime` function seems to cycle through all the components to work out the maximum absolute time. Perhaps we just delay _that calculation_ from compile time to runtime, by passing a list of possible candidate max times rather than a single value.

There might be more to that calculation than a simple `max`, but again, maybe that could be performed just prior to the `while` loop line?

**Comment by dfareri** [comment]
Hi, has there been a verified solution to this issue?

**Comment by TEParsons** [comment]
Implemented in #6603 - Routines are now represented by objects at runtime, with a `duration` set at Routine start. If `forceNonSlip` is checked in the Routine settings, and the Routine is given a fixed duration (even if it's a variable) then it will use nonslip timing.
