### ISSUE TITLE
Package imageio-ffmpeg for conda-forge

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2260]
`imageio`'s `ffmpeg` plugin [now depends on `imageio_ffmpeg`](https://github.com/imageio/imageio/commit/b6dd8bfcc3adb324a9314352bc9683ee3ab00453), which currently doesn't exist on `conda-forge`. Relevant for `moviepy` / `MovieStim3`.

**Comment by hoechenberger** [comment]
I can work on this tomorrow evening.

**Comment by hoechenberger** [comment]
Somebody's already working on this: https://github.com/conda-forge/staged-recipes/pull/7730

**Comment by hoechenberger** [comment]
Issue was originally brought up here: https://github.com/imageio/imageio-ffmpeg/issues/9

**Comment by zhuziying** [comment]
when i run FaceSwap in windows10,an error raised that is ModuleNotFoundError: No module named 'imageio_ffmpeg'.and i run command 'conda install -c conda-forge imageio-ffmpeg',then run FaceSwap again,the problem remains the same. 'conda list' result is below:

imageio 2.5.0 py37_0 conda-forge
imageio-ffmpeg 0.3.0 py_0 conda-forge

Why?
