### ISSUE TITLE
Feature request: ability to clear output window

### ISSUE THREAD

**Issue by dfkettle** [psychopy/psychopy#2285]
IMHO, it would be nice if you could clear the messages from the output window. Sometimes a run-time error results in dozens of error messages displayed in the output window, but it's usually the first one or two that indicate where in your code the error originated. So on a first run, you can just scroll all the way to the start to find it. But on subsequent runs, you have to scroll back until you find where the trace starts. I usually end up exiting PsychoPy and starting it again (I know, I'm lazy), but if I could clear the output window before each subsequent run, I wouldn't have to do that. Maybe there's already some way to do this, but I couldn't find it.

**Comment by peircej** [comment]
Agreed. First up I guess the panel needs a button ("clear") and maybe ("copy")? @dvbridges might enjoy this one! After adding those buttons, the mechanics of actually clearing the buffer (or copying to clipboard) are pretty trivial.

**Comment by dvbridges** [comment]
Yes, would like to do this thanks 👍

**Comment by dvbridges** [comment]
@peircej , are we thinking to add a Coder tool (in toolbar) for this? Or add something to the actual output panel?

**Comment by dfkettle** [comment]
Thanks! I don't know if a copy button is really needed. A standard copy-and-paste works (at least in Windows). But I guess if there are dozens of messages, a button might be convenient.

**Comment by m-macaskill** [comment]
Agree wholeheartedly with the need for this, but rather than cluttering the interface for a relatively rare operation, what about just adding an option from a contextual menu from right-clicking (i.e. along with the copy/paste options)? That would be the first place I'd think of looking, if there wasn't an obvious button.

**Comment by dvbridges** [comment]
Leaving as unassigned for now, in case someone else ones to join in. I have other priorities (e.g., timing tests) for the next week or so.

**Comment by dfkettle** [comment]
I just took a look at the context menu for the output tab. If you right-click on the tab, there already are options to "Select All", "Cut", "Copy", "Paste" and "Delete". but the "Cut" option is grayed-out, even if some text has been selected. The "Copy" function works, though.
