### ISSUE TITLE
Iohub eyetracker (eyelink): sendToHub returns None when calling runSetupProcedure

### ISSUE THREAD

**Issue by lukassnoek** [psychopy/psychopy#2302]
When calling `runSetupProcedure()` after initializing an eytracker device with Iohub, the program crashes because the command `self.sendToHub` in the `iohub.client.DeviceRPC` class (in `__call__`) expects a list (or string) as return value, but it returns `None`. As such, it will crash in the next line (line 63 of `__init__.py`) when running `r = r[1:]`:

```python
TypeError: 'NoneType' object is not subscriptable
```

Any idea what might've caused this? I'm using the following environment/setup:
- Python3.6 and installed a clone of PsychoPy's master branch (using `python setup.py install`) without errors on Windows 7 (64-bit);
- Using an Eyelink 1000 eyetracker;
- Notably, the eyetracker *does* seem to receive the command sent by iohub (it briefly starts the calibration procedure).

**Comment by isolver** [comment]
closing, whatever the issue was, it should be fixed in the latest source. Tested eyelink 1000 on win10, linux (Mint 19.1), and macos Catalina.
