### ISSUE TITLE
Mismatching filenames and experiment names cause online studies to fail

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#2305]
When users change the experiment name (e.g., to ```myExp```) in experiment settings to one that is different from the original filename (e.g., ```myOriginalName.psyexp```), the HTML file calls a JavaScript file by the experiment name defined in the  experiment settings e.g., ```myExp.js```, however the actual JavaScript file has the same name as the psyexp file (```myOriginalName.js```).

For solutions:
1) We could instead populate HTML and JS outputs using the psyexp filename
2) Write the JS output scripts using filenames created from experiment settings exp. name
3) Make experiment name field immutable
4) Warn the participant of what is happening, but do nothing

**Comment by peircej** [comment]
I think option 1. It's confusing if the filenames are different for the python and JS files.

I think we should still allow the experiment name to differ (although by default it tries to track the filename). I might use something in that field that's easier to read (e.g. with punctuation) even though I wouldn't personally do that in the filename.
