### ISSUE TITLE
cannot use an Excel Macro-Enabled Workbook (.xslm) for “Conditions” in the Builder

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2309]
I tried to load a sheet from an Excel Macro-Enabled Workbook (.xslm) for “Conditions” in the Builder. But It is mentioned the following: “No parameters set (conditionsFile not found)”. It only works when I have the same sheet (without any macros).

My question: is it possible to use a sheet from .xslm (an excel sheet with macros)?

**Comment by peircej** [comment]
From a quick google It sounds like openpyxl can read xlsm files but I think it will just treat it as a regular xlsx file. The macro won't be usable from within Python. I guess the question is what your macro is doing and whether it's needed for the conditions file to operate

**Comment by mmolet** [comment]
Thanks Jon, how could I use openpyxl to read the xlsm file so that it can be treated as an xlsx file and be read by Psychopy to set the conditions in the builder?

**Comment by hoechenberger** [comment]
This is already happening underneath the sheets (no pun intended!) What Jon meant to say is, depending on what your macros do, it may or may not lead to usable results in PsychoPy. Would it not be possible for you to first convert the files to xlsx, i.e. get rid of the macros?

**Comment by mmolet** [comment]
Hi, and thanks for responding. The macro does a "complicated" randomization (I understand that I could use some code in Python to do the same but I am more familiar with macros). My goal is as follows: a macro does the randomization so that the sheet can be used by Psychopy. I really would like to explore this possibility.

**Comment by peircej** [comment]
So I think the solution, which @dvbridges is working on, will get the file to load, but I'd be amazed if it _runs_ the macro. 

The macro will have been written in something like Visual Basic (or does it use some other syntax these days?) and I don't think the xlread or pyopenxl libraries will be providing Visual Basic interpreters. So if you're expecting the macro to re-do the randomization on each load this won't work and you'll need to do the same thing in Python instead. If the macro is something that you manually run (from within excel) but want it kept with the file for convenience then I think that will be fine.

**Comment by mmolet** [comment]
Yes this is VB, I don't expect the macro to be started with Psychopy and re-started; I will have a start/restart button for this on the desktop.

**Comment by peircej** [comment]
OK, then yes, I think David's commit will address that use case :-)
