### ISSUE TITLE
proposed ENH: batch handling of Builder scripts

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#231]
I guess this is a proposed new feature, not an enhancement.

It would be nice to have a batch-handling script that can run several Builder (or code) experiments. Some people like to run their experiments this way, and it seems easy enough to support. I'm thinking that the Tools menu could have a Batch command. The basic idea takes just a few lines of code, https://gist.github.com/4076435 .  

Ideally it would prompt for subject and session info once, and then run several scripts, passing the exp info to all of the scripts. One way to do this would be via sys.argv. For this to work, all Builder-generated scripts would need to check if sys.argv[1] exists and is a dict, and if so use those values to pre-populate the expinfo gui. (Pre-populating the relevant fields seems best. Individual experiments might prompt for unique things not needed in other experiments, and so a gui might be needed for each experiment, not just one gui for the whole batch.) 

It might seem nice to create a visual.Window() once and use it for all experiments, rather than revealing the desktop between experiments, but I don't think this is the right way to go. Instead, I think its best to create a large, blank, non-full screen window in the batch launcher script. This would hide the desktop between experiments and yet allow other processes (= experiments) to present dialogs themselves and also take control of the window. 

A batch-mode could do other nice things, such as use write-protected files as the source (so that accidental changes are not going to happen--this could be done without a batch launcher of course), randomly order the experiments per subject, and so on. It could take .py files or .psyexp files as its input, or you could give it a directory and it could run everything that's run-able in the directory. It would be nice to remember the last directory used across runs, for easier running.

Keeping track of the order in which to run experiments would be nice but more complicated: alphabetical sorting order, random, a specified order, allow user to change the specified order, ...

**Comment by mdcutone** [comment]
This seems like it has been addressed with the inclusion on the "Runner" view.
