### ISSUE TITLE
cannot import xlwings for a code

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2315]
HI all, 

I tried to import xlwings for a code but I received the following “ModuleNotFoundError: No module named 'xlwings”  when I hit ‘run’. Though it is correctly installed (xlwings in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)

Any idea why this is not working?

**Comment by peircej** [comment]
Maybe you have multiple python installations? In the script that you'r running you can use this to find out what python interpreter is being used:
```
import sys
print(sys.executable)
```

But this is not a PsychoPy issue. Please use the forum for user support questions
