### ISSUE TITLE
iohub and core clocks out of sync on macOS with Python 3

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2326]
On macOS 10.14.3, Python 3.7.2, PsychoPy `master`, I cannot use `iohub` to measure response times because the `iohub` and `psychopy.core.getTime()` time bases seem to be out of sync.

MWE:
```python
from psychopy.iohub import launchHubServer
from psychopy import core


io = launchHubServer()
keyboard = io.devices.keyboard

io.clearEvents('all')
t0 = core.getTime()

while True:
    events = keyboard.getKeys()
    if events:
        t_getTime = core.getTime()
        t_iohub = events[0].time
        break

print(f'core.getTime() timestamp: {t_getTime}')
print(f'iohub timestamp:          {t_iohub}')
```
Running this code and pressing a key produces output like:
```python
/Users/hoechenberger/miniconda3/envs/psychopy-test/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.3/scratches/scratch_19.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
core.getTime() timestamp: 4.988316210000001
iohub timestamp:          3.8018358130000003
ioHub Server Process Completed With Code:  0

Process finished with exit code 0
```
The `iohub` timestamp is dragging behind the `core.getTime()` timestamp, although my understanding is that they should both be ~identical in this example.

Works as expected on a Windows 10 machine with Python 3.6.

**Comment by hoechenberger** [comment]
More minimalist example:

```python
from psychopy.iohub import launchHubServer
from psychopy import core

io = launchHubServer()
print(f'getTime(): {core.getTime()}')
print(f'iohub:     {io.getTime()}')
```
Output:
```python
/Users/hoechenberger/miniconda3/envs/psychopy-test/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.3/scratches/scratch_20.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
getTime(): 5.628593663
iohub:     3.6614230229999998
ioHub Server Process Completed With Code:  0

Process finished with exit code 0
```

**Comment by hoechenberger** [comment]
Interestingly, `iohub.Computer.getTime()` yields to same time as `core.getTime()`. Apparently it's only the timestamps of events that are affected.

**Comment by hoechenberger** [comment]
Okay. So. `iohub.client.ioHubConnection._startServer()` calls `launchHubProcess.py` with a [parameter](https://github.com/psychopy/psychopy/blob/7fd0f5b80452687a5123e7b440a1019e4e947525/psychopy/iohub/client/__init__.py#L936) `Computer.global_clock.getLastResetTime()`, which is then [interpreted](https://github.com/psychopy/psychopy/blob/7fd0f5b80452687a5123e7b440a1019e4e947525/psychopy/iohub/launchHubProcess.py#L108) as an offset that gets [passed on](https://github.com/psychopy/psychopy/blob/7fd0f5b80452687a5123e7b440a1019e4e947525/psychopy/iohub/launchHubProcess.py#L123) to `Computer.global_clock`. But even when I force-set this offset to zero, I get the discrepancy in timing described in the comments above.

**Comment by peircej** [comment]
@sol has been looking into iohub and Py3 in the last few days so he might have some insight.

**Comment by peircej** [comment]
Apologies. Wrong @sol (you'll probably want to mute this conversation so you don't get a barrage of updates) I meant to tag @isolver

**Comment by aforren1** [comment]
I think this is due to a change in behavior of `timeit.default_timer` between Python 2 and 3, which psychopy and iohub use for getting time on Macs.

In Python 2, `default_timer` maps to `time.time` (https://github.com/python/cpython/blob/2.7/Lib/timeit.py#L75), which uses `gettimeofday` under the hood (https://github.com/python/cpython/blob/2.7/Modules/timemodule.c#L993) (time since the Unix epoch), and should be the same across processes (so the `_timeAtLastReset` is an absolute time).

Anything greater than Python 3.3 uses `time.perf_counter` as the `default_timer` instead (https://github.com/python/cpython/blob/3.7/Lib/timeit.py#L61), which uses `mach_absolute_time` (time since last reboot?) and subtracts off a process-specific reference time (https://github.com/python/cpython/blob/3.7/Python/pytime.c#L802) (taken the first time that `time.perf_counter` is called) to preserve precision. `_timeAtLastReset` ends up being relative to the start of the first process, and doesn't end up accounting for the offset between the start of the two processes.

Then a solution could be to replace `default_timer` with a MacOS-specific timer, based off `mach_absolute_time` but without the reference subtraction (e.g. https://github.com/aforren1/toon/blob/master/toon/input/mac_clock.py).

**Comment by hoechenberger** [comment]
@aforren1 Great, thanks! I already suspected something like that, but couldn't quite figure it out.

**Comment by isolver** [comment]
Yes, the clock used by psychopy and iohub need to share the same origin across processes. The getLastResetTime() is used to correct for the offset applied to the timebase by psychopy Clock.

For macOS only, could we switch to use time.time as the timebase in PsychoPy3 Python 3 and keep using default_timer in 2.7? Or does time.time have poor resolution in Python 3 on macOS?

**Comment by isolver** [comment]
Would changing clock.py to this be OK? Could someone on macOS please try this if you have time, otherwise I will try once I get my macos python 3 env working.

``` python
if sys.platform == 'win32':
    from ctypes import byref, c_int64, windll
    _fcounter = c_int64()
    _qpfreq = c_int64()
    windll.Kernel32.QueryPerformanceFrequency(byref(_qpfreq))
    _qpfreq = float(_qpfreq.value)
    _winQPC = windll.Kernel32.QueryPerformanceCounter

    def getTime():
        _winQPC(byref(_fcounter))
        return _fcounter.value / _qpfreq
elif sys.platform == "darwin":
    # Use time.time on macOS for multproc support
    getTime = time.time
else:
    # TODO: Is timeit.default_timer still multiproc safe on Linux Python 3.6?
    import timeit
    getTime = timeit.default_timer
```

**Comment by hoechenberger** [comment]
Hi Sol, I can try this tonight.

**Comment by aforren1** [comment]
The advantage of a `mach_absolute_time` solution is that the clock will be monotonic, which isn't guaranteed for `time.time` -> `gettimeofday` (or `clock_gettime(CLOCK_REALTIME, ...)`, which looks like it may be used for macOS 10.12+).

Re: `timeit.default_timer` on Linux + Python 3, I haven't seen any issues (it looks like Python doesn't set an origin ([source](https://github.com/python/cpython/blob/3.7/Python/pytime.c#L880)), and the implementation uses `clock_gettime(CLOCK_MONOTONIC)`, at least on my Ubuntu 18.04).

**Comment by hoechenberger** [comment]
@isolver This branch of the `if` statement never gets executed for me, as [`_ispkg` is `False`](https://github.com/psychopy/psychopy/blob/7fd0f5b80452687a5123e7b440a1019e4e947525/psychopy/iohub/util/clock.py#L12).

**Comment by isolver** [comment]
How about using the code @aforren1 references. Makes sense to use it for both P2.7 and P3.
@hoechenberger, mind trying this version out please:

```python
elif sys.platform == "darwin":
    # Monotonic getTime with absolute origin. Suggested by @aforren1, and
    # copied from github.com/aforren1/toon/blob/master/toon/input/mac_clock.py 
    import ctypes
    _libc = ctypes.CDLL('/usr/lib/libc.dylib', use_errno=True)
    
    class mach_timebase_info_data_t(ctypes.Structure):
        _fields_ = (('numer', ctypes.c_uint32), ('denom', ctypes.c_uint32))
    
    _mach_absolute_time = _libc.mach_absolute_time
    _mach_absolute_time.restype = ctypes.c_uint64
    
    _timebase = mach_timebase_info_data_t()
    _libc.mach_timebase_info(ctypes.byref(_timebase))
    _ticks_per_second = _timebase.numer / _timebase.denom * 1.0e9
    
    def getTime():
        return _mach_absolute_time() / _ticks_per_second
else:
    import timeit
    getTime = timeit.default_timer
```

**Comment by hoechenberger** [comment]
> @hoechenberger, mind trying this version out please:

I applied these changes and ran the following code:
```python
from psychopy.iohub import launchHubServer, Computer
from psychopy import core

io = launchHubServer()
core_time = core.getTime()
io_time = io.getTime()
computer_time = Computer.getTime()

print(f'getTime():      {core_time}')
print(f'iohub server:   {io_time}')
print(f'iohub.Computer: {computer_time}')
```
Output:
```python
getTime():      3.613459045009222
iohub server:   3.613592561974656
iohub.Computer: 3.61378367402358
```

**Comment by isolver** [comment]
@hoechenberger and @aforren1  Thanks very much.

**Comment by peircej** [comment]
There's another option as well now that Sol and I think might be useful. The new `psychtoolbox` package (I've pushed some alpha release wheels to pypi https://libraries.io/pypi/psychtoolbox) has a `GetSecs()` function that uses the best timer it can find on each platform. That will be the base clock being used for time-stamping events using the psychtoolbox lib so it makes sense to use that for all our other events too when available.

So I think we should end up with

```python
try:
    import psychtoolbox
    havePTB = True
except ImportError:
    havePTB = False

if havePTB:
    getTime = psychtoolbox.GetSecs
elif sys.platform == 'win32':
    # use Kernel32.QueryPerformanceCounter ?
elif sys.platform == 'darwin':
    # use _mach_absolute_time
else:
   getTime = timeit.default_timer
```

Anyone mind that approach? For what it's worth, under the hod GetSecs is using the same mechanisms we refer to above anyway (http://psychtoolbox.org/docs/GetSecs)

Added bonus with `ptb.GetSecs` is that we can ask it for "wall time" (http://psychtoolbox.org/docs/GetSecs-AllClocks) which can then also be stored and converted to date/hour etc. In practice I just tested that on my Win10 box and it gave me the wrong date (was fine on a mac), but the theory is good!

**Comment by isolver** [comment]
> Anyone mind that approach? 

That will work really well. It should also work with iohub, but this should be checked on each OS though.

**Comment by aforren1** [comment]
I think `ptb.GetSecs` would be marginally worse on Linux+Python 3 re: precision, given it still uses `gettimeofday`/`CLOCK_REALTIME`? It looks like Mario's been considering switching to `CLOCK_MONOTONIC` ([commit message](https://github.com/kleinerm/Psychtoolbox-3/commit/d73c5234266d367fab84ba21d54b141dcfa3b48f), [yahoo post](https://groups.yahoo.com/neo/groups/psychtoolbox/conversations/messages/21678)).

Excited to try the new psychtoolbox functionality! Should there be wheels for linux (I only see windows & mac on PyPi)?

**Comment by peircej** [comment]
You can now try out the new Keyboard class in psychopy/master to see the improvements for yourself. I added a demo in demos/coder/input/ that shows roughly:
- Much more faster than getKeys() (especially on windows for some reason?)
- 0.5ms faster than waitkeys() on windows
- 3ms faster than waitKeys() on Mac

@aforren1 I very much hope I can build wheels for linux but right now I can't build them using manyLinux (and I don't want to build them for each distro like wxPython). The problem is that manyLinux uses Centos/RHEL5 to make itself widely compatible but that doesn't support Xinput2 which psychtoolboxHID requires. Apparently there's a new manylinux2010 on its way that uses RHEL6 and should then support Xinput2. Do you want me to push an sdist so that (I think) pip will at least try to install it by compiling?

**Comment by aforren1** [comment]
Sure, that would be great! Thank you.

**Comment by peircej** [comment]
I've pushed a sdist to pypi my own ubuntu VM is installing some mega udpates so I can't check if it worked/helped with the pip install

**Comment by aforren1** [comment]
It looks like the sdist doesn't have the linux source files:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e3wy772s/psychtoolbox/setup.py", line 182, in <module>
        sources = get_basesources(name, osname),
      File "/tmp/pip-install-e3wy772s/psychtoolbox/setup.py", line 41, in get_basesources
        return(basefiles_common + get_sourcefiles('./PsychSourceGL/Source/' + osname + '/Base/') + get_sourcefiles('./PsychSourceGL/Source/Common/' + name) + extrafiles)
      File "/tmp/pip-install-e3wy772s/psychtoolbox/setup.py", line 19, in get_sourcefiles
        for filename in os.listdir(path):
    FileNotFoundError: [Errno 2] No such file or directory: './PsychSourceGL/Source/Linux/Base/'
    Platform reported as: Linux
    
    Building for Linux...

```

I can install from your fork in the meanwhile.

**Comment by peircej** [comment]
eeesh. I think that means manifest files doesn't it! :-(

**Comment by peircej** [comment]
OK, I've added a manifest file that seems to have done the trick. 
To build you'll need to make sure you have the dependent libs (including header files) which you can get with this (on ubuntu):
```bash 
sudo apt-get install libx11-dev libasound2-dev portaudio19-dev libusb-1.0.0-dev libxi-dev
```
Then I did
```
pip install psychtoolbox==3.0.15dev2
```
and it installed! I haven't tested if it *works* but it installed!!

**Comment by isolver** [comment]
I need to reinstall Mint Linux 19.1 xfce again, so I'm noting some things down this time:

1) add python3-dev to apt-get list

2) I used the pythonisms branch of jpeirce/Psychtoolbox-3 and did:

sudo python3 setup.py install

3) pyglet version 1.4.0.b1 that is installed as part of psychopy build gives following error:

```
PsychoPy 3.0.6
Traceback (most recent call last):
  File "sysInfo.py", line 41, in <module>
    win = visual.Window([100, 100])  # some drivers want a window open first
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/window.py", line 389, in __init__
    self.backend = backends.getBackend(win=self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/__init__.py", line 32, in getBackend
    return Backend(win, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/pygletbackend.py", line 101, in __init__
    defDisp = pyglet.window.get_platform().get_default_display()
AttributeError: module 'pyglet.window' has no attribute 'get_platform'
```

could this be related to #2386 ?

downgrading to pyglet 1.3.2 does not give that error, but now I get:

```
PsychoPy 3.0.6
Traceback (most recent call last):
  File "sysInfo.py", line 41, in <module>
    win = visual.Window([100, 100])  # some drivers want a window open first
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/window.py", line 389, in __init__
    self.backend = backends.getBackend(win=self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/__init__.py", line 32, in getBackend
    return Backend(win, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/pygletbackend.py", line 227, in __init__
    self._origGammaRamp = self.getGammaRamp()
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/pygletbackend.py", line 326, in getGammaRamp
    return getGammaRamp(self.screenID, self.xDisplay)
  File "/usr/local/lib/python3.6/dist-packages/PsychoPy-3.0.6-py3.6.egg/psychopy/visual/backends/gamma.py", line 152, in getGammaRamp
    raise AssertionError('XF86VidModeGetGammaRamp failed')
AssertionError: XF86VidModeGetGammaRamp failed
1.8373 	WARNING 	Monitor specification not found. Creating a temporary one...
2.2042 	WARNING 	The size of the gamma ramp was reported as 0. This can mean that gamma settings have no effect. Proceeding with a default gamma ramp size.
Exception ignored in: <bound method Window.__del__ of <psychopy.visual.window.Window object at 0x7f47c3642e10>>
```
which I assume is because I need to install a graphics driver..

to be continued.......

**Comment by isolver** [comment]
Can we close or rename this issue, as I do not think the OP regarding iohub is not a problem anymore.
