### ISSUE TITLE
When opening an experiment in Builder, Routine tabs of previously opened file(s) are not closed

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2336]
One ends up with a messy interface where tabs of the Routines of the previously loaded file(s) are still being displayed (but not functional), additionally to the ones corresponding to the newly opened experiment file. Super confusing, esp. since there can be name overlaps (e.g., multiple tabs with name "trial"). And the old tabs cannot be closed either.

Latest `master`, Py3, on macOS. But I've witnessed the same behavior on Win 10 too.

Why don't we open files in a new frame? `File -> New` generates a new frame too… So this seems to be inconsistent anyway.

cc @shirllim

**Comment by peircej** [comment]
## Routines remaining:

That's weird. It didn't used to do this, but I wonder if something changed in wx4.

## Use of same-frame or new-frame:

Yes, I figured initially that people doing Open would want to open in the same frame, but that has confused a few people. The fact that New did open in a separate tab was the way to allow both behaviours (you can just Open for same-frame or New, Open for a new frame).

Happy for this to be changed. The other related issue then is that we should list the current open builder frames in the view menu. That wasn't needed in a world where people only typically had a single builder and single coder frame (only need controls to switch between them), but will be needed if people often have multiple open experiments.

**Comment by peircej** [comment]
I can't replicate the title issue (with Mac, Py3.6, wx4.0.4, psychopy master). When I open a new experiment from either the demos or File>Open the routines are correctly removed/replaced by the new study.

**Comment by hoechenberger** [comment]
Thanks for looking into this, Jon. I just figured that wxpython 4.0.3 is installed on both systems, which we had discovered to be problematic in the past. Will try with different versions tomorrow! But I'm almost certain that's probably the issue!

**Comment by hoechenberger** [comment]
Downgrading to wxpython 4.0.1 actually fixed the issue. Sorry for the buzz, should have checked that first! :S

**Comment by hoechenberger** [comment]
Also fixed in wxpython 4.0.4 on macOS.
