### ISSUE TITLE
 Experiment not running-v 3.05-windows8

### ISSUE THREAD

**Issue by caiqin7** [psychopy/psychopy#2340]
Hello. 
I have designed an experiment on psychopy builder v3.05. 
 I try to run it by clicking the green man and the man's color turns to grey.
However,it shows nothing even the error. The experiment couldn't run.

**Comment by dvbridges** [comment]
This sounds related to how you have set up your experiment, rather than a software issue. Please repost your issue on the [PsychoPy forum](https://discourse.psychopy.org/) with the details of what you are trying to do, how you created your experiment, and what errors you received.
