### ISSUE TITLE
several import problems 

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2342]
Hi all,
I made a program (for a colleague) using a Mac and Psychopy 3.0.5 (StandalonePsychoPy3-3.0.5-MacOS.dmg). It runs perfectly on my machine. My colleague installed Psychopy 3.0.5 on his machine that is a PC (StandalonePsychoPy3-3.0.5-win64.exe) and she got several import problems trying to run the program, please the attachment. **Anyone has an idea how to solve this?**
![cannot import](https://user-images.githubusercontent.com/47699196/54159109-30330800-441a-11e9-8b14-00b62cdcb45a.png)

**Comment by hoechenberger** [comment]
I believe this was fixed in version 3.0.6, could you ask your colleague to update to this version please?

**Comment by mmolet** [comment]
Yes, I can ask her to download the new version, I will keep you posted! Thanks for helping.

**Comment by mmolet** [comment]
Quick question related to this issue: would that be a problem to keep a previous version of Psychopy on a machine along with a newest version? I am asking because she told me that she has an older of Psychopy in addition to the 3.0.5 version on her machine?

**Comment by hoechenberger** [comment]
I don't think that would matter, no. But simply using the built-in upgrade feature of 3.0.5 to transition to 3.0.6 won't suffice, hence my suggestion to uninstall 3.0.5 entirely and then install 3.0.6.

**Comment by mmolet** [comment]
No longer an issue with the newest version! Thank you.
