### ISSUE TITLE
Pip fails to install psychtoolbox lib

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#2360]
When running `pip install psychtoolbox` on Windows 10 64bit, I get the following error:

```
Collecting psychtoolbox
  Using cached https://files.pythonhosted.org/packages/e5/d7/9f034f120788b4a6ab79ecf6888abdd761f174c07ffe75938df911d47de1/psychtoolbox-3.0.15a1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-58wqpse7\psychtoolbox\setup.py", line 115, in <module>
        'PsychPython/')
      File "c:\program files (x86)\python37\lib\shutil.py", line 245, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "c:\program files (x86)\python37\lib\shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'PsychSourceGL/Cohorts/libusb1-win32/MS32/dll/libusb-1.0.dll'
    Platform reported as: Windows
    Building for Windows...

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\USERNAME\AppData\Local\Temp\pip-install-58wqpse7\psychtoolbox\
```

**Comment by peircej** [comment]
What's your Python here? I only built the wheel on a Py3.6 64bit. If you're using py3.7, for instance it will fail. I guess I'll go and build one of those too!

**Comment by czen** [comment]
I have stumbled on this problem myself today. Is there any chance of compiling psychtoolbox for other python versions? 
Successfully building it from sources on Windows seems too complicated, but without psychtoolbox I can't easily get key press durations in psychopy and restricting my own builds to python 3.6 is a gigantic pain in the rear.

I would imagine compatibility with python 2.x is not even on the table?

**Comment by peircej** [comment]
No, going forwards we're only really going to support 64bit installs of 3.6, 3.7
Python 2.7 reaches "End of Life" on 1st Jan (no more support from Python.org) and there's increasingly no need to support it further by us (as hardware transitions to 3.x support)

**Comment by CaoKang-David** [comment]
> What's your Python here? I only built the wheel on a Py3.6 64bit. If you're using py3.7, for instance it will fail. I guess I'll go and build one of those too!

I got the same problem, and I want to know when to build the wheel on a Py3.7 64bit?

**Comment by siddsuresh97** [comment]
The build fails for me too! I am running Python 3.7 (64 bit version). When would it be able to support this version of python?

**Comment by peircej** [comment]
I should look into making this work for multiple versions/operating systems using the matthew-brett/multibuild package
