### ISSUE TITLE
Prefs.general or prefs.hardware for audiolib?

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#2377]
I discovered that a lot of the code refers to ```prefs.hardware['audiolib']```, but in a psychopy shell if I import prefs and then look for ```prefs.hardware['audiolib']``` I get a keyerror. It instead seems to be under ```prefs.general['audiolib']```, despite being the hardware tab of the preferences menu.

This is something I'm a little skittish about trying to fix myself because I'm worried that a bunch of different pieces of code will refer to different things. For example, in movie3, audioseek checks prefs.hardware, and in principle so does sound.__init__, but it wouldn't be picked up by a test because the travisCI setting for sound specifies ```prefs.hardware['audioLib'] = ['sounddevice']```

So, prefs.hardware, prefs.general, one as an alias for the other? I'm a bit confused but I'd like to be able to make it consistent one way or another.

**Comment by peircej** [comment]
@hoechenberger felt it was more a hardware thing than general and changed it (which determines the tab it appears in in the preferences). Maybe it simply didn't get changed in all locations? Are you working from recent master?

**Comment by jfkominsky** [comment]
This is in 3.0.6, if you go to the shell and import prefs you can see it
yourself. It's been this way at least since 3.0.5.

**Comment by hoechenberger** [comment]
I take all the blame 😬 Can only have a look at it at the end of the week, though!

**Comment by hoechenberger** [comment]
Cannot reproduce. The setting is correctly stored in `prefs.hardware['audioLib']` -- mind the capitalized `L`.

**Comment by jfkominsky** [comment]
Quite right, my mistake. It is also true that prefs.general['audioLib'] exists, which is mildly confusing, but it looks like I was just putting in the wrong thing.

**Comment by hoechenberger** [comment]
> Quite right, my mistake. It is also true that prefs.general['audioLib'] exists, which is mildly confusing,

This could actually be a "leftover" in the configuration file, which had been created by a version of PsychoPy before the audio setting was moved to the `hardware` section. – @peircej, do you think this could cause any harm? Isn't there a way to easily remove this bit automatically?

**Comment by peircej** [comment]
I'm surprised in 2 ways.

- **Magic that isn't happening**: this should _already_ have been removed. preferences.py uses configobj to test the current preferences file against the preferences spec and (I thought) should remove entries that don't exist in the spec. Apparently some part of that isn't working
- **Magic that is happening**: given that the option clearly is there in prefs, I'm not sure why it isn't showing up in the preferences dialog under 'general'. I thought I'd written the prefs panel to inherit whatever it finds in `psychopy.prefs`
