### ISSUE TITLE
TextStim.verticesPix throws TypeError: unsupported operands type(s) for *: 'attributeSetter' and 'float'

### ISSUE THREAD

**Issue by wjhopper** [psychopy/psychopy#2381]
It seems that there is a problem with accessing the `verticesPix` attribute of a `TextStim` object.

```python
from psychopy import visual
win = visual.Window()
text = visual.TextStim(win, text="Hello, World!")
print(text.verticesPix)

Traceback (most recent call last):
  File "C:\Anaconda3\envs\psypy3\lib\site-packages\psychopy\visual\basevisual.py", line 477, in verticesPix
    self._updateVertices()
  File "C:\Anaconda3\envs\psypy3\lib\site-packages\psychopy\visual\basevisual.py", line 516, in _updateVertices
    verts = numpy.dot(self.size * verts * flip, self._rotationMatrix)
TypeError: unsupported operand type(s) for *: 'attributeSetter' and 'float'
```
It seems that the `.size` attribute isn't resolved correctly, something to do with how it is wrapped in the `attributeSetter` class.

If you go ahead and draw + flip the text, the `.verticesPix` attribute up and vanishes completely:
```python
from psychopy import visual
win = visual.Window()
text = visual.TextStim(win, text="Hello, World!")
text.draw()
win.flip()
print(text.verticesPix)

Traceback (most recent call last):
  File "C:\Anaconda3\envs\psypy3\lib\site-packages\psychopy\visual\basevisual.py", line 478, in verticesPix
    return self.__dict__['verticesPix']
KeyError: 'verticesPix'
```
I'm thinking something related to inheritance is going awry.

All this raises a larger question: am I doing it wrong? My goal is to find out where boundaries of the text are on the screen. I know about the `.boundingBox` property, but the API docs give me the impression that this is just the width and height of the text in pixels. Is this impression correct? And is there a correct and consistent way to find boundaries that works for all stimuli types?

**Comment by TEParsons** [comment]
Vertices aren't hugely relevant to TextStim as it doesn't really have an x size - it just has a height and is as long as the characters are. However, when the rework of `.size` and `.pos` is in, I've added to that something to estimate the width of the TextStim based on letter height, so vertices can at least be estimated if not set. However, for creating text with settable and sensible vertices, TextBox2 is really the way to go.

**Comment by TEParsons** [comment]
link #4211
