### ISSUE TITLE
can quit with cmd+q on Mac but no equivalent (ALT+F4) works on PC

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2383]
HI all,
Here is the configuration:  I unable the “Show info dialog” and unable 'Escape key" then I cannot press “Esc” which is expected but while I can use Cmd-Q to stop the experiment on a MAC nothing seems to work on a PC (e.g., ALT+F4). Importantly, there is no keyboard component present. What I don't understand is why Cmd-Q has an effect on a MAC and nothing works on PC

**Comment by peircej** [comment]
I think it's quite reasonable that subjects can't quit the app during a run. Can other experiment packages be quit during running? I think I'm surprised that Cmd-Q works - that certainly isn't deliberate - but I think I'd need persuading that it's a good idea to allow Alt-F4
