### ISSUE TITLE
Bundle pylsl

### ISSUE THREAD

**Issue by tstenner** [psychopy/psychopy#2384]
The [Labstreaminglayer](https://github.com/sccn/labstreaminglayer/) is one of the most robust and widespread methods of synchronizing various streams (e.g. EEG data, stimulus markers, eye trackers) over the local network.

It's already bundled in [Presentation](https://www.neurobs.com/pres_docs/html/03_presentation/06_hardware_interfacing/02_lab_streaming_layer.htm) and the python module [pylsl]([pylsl](https://pypi.org/project/pylsl/)) can be installed in Psychopy relatively easy, but it would be easier to use (and recommend to other psychopy users) if it were preinstalled.

**Comment by peircej** [comment]
Agreed. Will do

**Comment by peircej** [comment]
I just checked and it was just hte 64bit windows installer where I hadn't done this already. I've fixed that for the 64bit installer too
