### ISSUE TITLE
Alternative classes for parallel module not working

### ISSUE THREAD

**Issue by mpratt14** [psychopy/psychopy#2392]
I see this in the init, and also directions online....

``The :class:`~psychopy.parallel.Parallel` class described below will
attempt to load whichever parallel port driver is first found on your
system and should suffice in most instances. If you need to use a specific
driver then, instead of using :class:`~psychopy.parallel.ParallelPort`
shown below you can use one of the following as drop-in replacements,
forcing the use of a specific driver:
    - `psychopy.parallel.PParallelInpOut`
    - `psychopy.parallel.PParallelDLPortIO`
    - `psychopy.parallel.PParallelLinux``

My system always defaults to DLPortIO whether its installed or not, and I can't get it to use InpOut32 instead

`AttributeError: 'module' object has no attribute 'PParallelInpOut'`

Windows 10 64-bit with Python 2.7 32-bit

**Comment by espressofiend** [comment]
we are having this issue as well, with PsychoPy v3.2.4 (32 bit) / Python 3.6.7 / Windows 8, with the inpout.dll driver

**Comment by peircej** [comment]
@mpratt14 I believe parallel ports are now working seamlessly in the Win10 version of PsychoPy. I think the issue used to be around the fact that the driver was 32bit and didn't play nicely with 64bit operating systems. We now ship Standalone only in 64 bit format and I haven't heard of anyone having issues recently but if I'm wrong about that then do reopen this issue
