### ISSUE TITLE
WindowWarp not doing anything

### ISSUE THREAD

**Issue by adamjcalhoun** [psychopy/psychopy#2394]
As far as I can tell, when I call it nothing happens (the image displayed doesn't change)? Even using the code example provided in the documentation? Is there something else I am supposed to do? It is definitely calling createVertexAndTextureBuffers() on creation and drawWarp() in place of the normal draw() function (added print commands to debug). 

In projectionSphericalOrCylindrical, tcoords and vertices are also definitely changing depending on the parameters... I've tried playing around with warpGridSize and eyepoint but nothing ever changes in the displayed visual stimuli?

This is Python 3.7 on both OS X and Windows

Sample code:
```
from psychopy import visual, core, event
from psychopy.visual.windowwarp import Warper

mywin = visual.Window([1440,900],monitor='testMonitor', 
             fullscr=True, useFBO = True)

warper = Warper(mywin,
                warp='spherical',
                warpfile = "",
                warpGridsize = 300,
                eyepoint = [0.5, 0.5],
                flipHorizontal = False,
                flipVertical = False)

#create some stimuli
fixation = visual.GratingStim(win=mywin, size=5, pos=[0,0], sf=50, color=-1)
fixation.draw()
mywin.update()
```

**Comment by djmannion** [comment]
I think it needs to know about the screen distance - see [this discourse thread](https://discourse.psychopy.org/t/how-to-use-cylindrical-warping/7183).

**Comment by adamjcalhoun** [comment]
Okay this definitely fixes it - thanks! I wonder if there is any possibility something about this could be alluded to in the documentation? Or that dist_cm could be a parameter passed to Warper?

For anyone who sees this in the future changing warper.dist_cm and calling changeProjection() fixes the issue:
```
warper.dist_cm = 10.0
warper.changeProjection("cylindrical")
```
