### ISSUE TITLE
Exception during component registration seems to silently get swallowed

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2396]
I just fetched `master` and started Builder, and the Pump Component seems to have disappeared from the Components panel. It ought to appear under `Custom`.

**Comment by hoechenberger** [comment]
Ok so turns out I didn't have the dependency `pyqmix` installed into my virtual environment. The Pump Component imports `hardware.qmix`, which imports `pyqmix`. This must've raised an exception that was swallowed somewhere, leading to a silent failure when the components were compiled. So this is not a bug with the Pump Component `per se`, but rather it seems we need to look into exception handling during component registration…

**Comment by hoechenberger** [comment]
I would still classify this as a bug though!

**Comment by peircej** [comment]
I don't recall exactly where this is being trapped during component registration and I agree that some level of message would be appropriate. 
**Simple solution is to output the message** using logging.warning() (or logging.info()? In a way the thing is that whether someone that doesn't have a pump and hasn't installed that lib (see recent discussion on pip minimal installations) do they wnat to have a warning about lots of Components not working, that they never wanted anyway

**Maybe better solution** would be that the component shows up with a strike-through icon and you can click on the icon to see a dialog box that explains what's wrong. That's obviously a lot more work

**Comment by peircej** [comment]
The swallowing is probably occurring as a result of 
https://github.com/psychopy/psychopy/blob/28c67754612386b9dbdb75e0e72b0c445affd203/psychopy/experiment/components/__init__.py#L149
That's actually there originally not so much to check for failing modules but for other objects (folders?) in the Components location that aren't components at all and shouldn't be treated as such. So to solve your issue we'd need to test "This does **look like** a module, but it fails to load"
