### ISSUE TITLE
pyxid library included in PsychoPy3 for Windows is not adapted for Python3

### ISSUE THREAD

**Issue by demsarjure** [psychopy/psychopy#2419]
pyxid library included in PsychoPy3 for Windows is not adapted for Python3, the one included in Mac version is adapted.

line 52 in __init__.py has to be changed from
`print d.device_name, d.get_next_response()`
to
`print(d.device_name, d.get_next_response())`

**Comment by peircej** [comment]
Yes, the version I'm about to provide in 3.1.0 is converted to Py3 using Py2to3 script. Maybe you could check it's working for you when it comes out (today I believe) and close this if it's fixed?

**Comment by demsarjure** [comment]
Sure, I will test this later today or tomorrow and close the issue if it will work as intended. Thanks.

**Comment by peircej** [comment]
I've uploaded a test release: https://github.com/psychopy/psychopy/releases/tag/3.1.0

**Comment by demsarjure** [comment]
It now works, thanks!
