### ISSUE TITLE
Psychtoolbox module not found in standalone v.3.1.0 for Win10 Py3.6 64bit

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#2437]
See also https://discourse.psychopy.org/t/cant-use-the-new-keyboard-component-from-psychtoolbox/7634

**Comment by peircej** [comment]
I've made sure this is inserted now. It will be in 3.1.1

**Comment by xihanjia** [comment]
Hi
I meet the same problem, how to solve it?
