### ISSUE TITLE
Can't run any experiments in builder, got a ValueError: embedded null byte

### ISSUE THREAD

**Issue by sakimarquis** [psychopy/psychopy#2438]
updating
I tried some methods from Internet, none of them goes well
And i think it might be some problem with the compiling function.
So i complied to a script in my laptop, using the script to run, everything works fine so far
-------------------------------------------------------------------------

I designed the experiments in my laptop(win10 x64) with psychopy3-3.1.0-win64, it runs fine in my laptop and my friends laptop. But when i run the experiments in my lab(win7 x86 sp1 with i3-2120 and AMD 7470) with psychopy3-3.1.0-win32. Any experiments won't run, including the demo. So i think there must be some compatible issues. But i don't know how to find them. here is the error messages. Thank you for your attention.

> Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\builder\builder.py", line 2127, in runFile
    self.generateScript(fullPath)  # Build script based on current version selected
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\app\builder\builder.py", line 2353, in generateScript
    psyexpCompile.compileScript(infile=self.exp, version=None, outfile=experimentPath)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\scripts\psyexpCompile.py", line 195, in compileScript
    _makeTarget(thisExp, outfile, targetOutput)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\scripts\psyexpCompile.py", line 174, in _makeTarget
    script = thisExp.writeScript(outfile, target=targetOutput)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\experiment\_experiment.py", line 187, in writeScript
    localDateTime = data.getDateStr(format="%B %d, %Y, at %H:%M")
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\data\utils.py", line 573, in getDateStr
    now = time.strftime(format, time.localtime())
ValueError: embedded null byte

**Comment by peircej** [comment]
According to the post below, that message is caused by Windows needing an update:
https://bugs.python.org/issue25023

Could you check for windows updates on that system?

**Comment by peircej** [comment]
You reacted with a heart emoji to your own post but was that because you fixed it or your attempt to get more attention to your issue?

**Comment by sakimarquis** [comment]
> You reacted with a heart emoji to your own post but was that because you fixed it or your attempt to get more attention to your issue?

Thank you for your attention. I fixed my problem following the link provided by you. The issue can be closed.

**Comment by peircej** [comment]
great!

**Comment by devount** [comment]
when this issue happended in my project,I tried to chage the "use psychopy version"  item to "3.1" in "Experimental settings " tool,and  now it works well. ps:My os is win7 but I  didn't update it. 
So I think there may be some compile issues when compile the experiments to python script  while use some special psychopy version like 3.2.4.
I hope this method will be helpful,and this bug will be fixed in next new version.
![psychopy_error](https://user-images.githubusercontent.com/43286985/68991658-f1ecc300-089b-11ea-95a1-e51cf1ab2cb2.png)
![psychopy_error1](https://user-images.githubusercontent.com/43286985/68991659-f1ecc300-089b-11ea-8863-364e6e09def0.png)
