### ISSUE TITLE
UnicodeDecodeError in Psychtoolbox module

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#2453]
Hi,

I installed psychtoolbox module by `pip install psychtoolbox` and run an empty Builder experiment (i.e. no components and loops were included).  I got following error message. My environment is the latest PsychoPy (the main branch of the repository), python 3.6.1 x64, Japanese Windows 10 x64.

```
Fatal Python error: (pygame parachute) Segmentation Fault
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte

Current thread 0x00002a78 (most recent call first):
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\psychtoolbox\hid.py", line 36 in devices
  File "C:\Users\Hiroyuki\Dropbox\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\psychtoolbox\hid.py", line 52 in get_keyboard_indices
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\hardware\keyboard.py", line 303 in __init__
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\hardware\keyboard.py", line 283 in getBuffer
  File "C:\Users\Hiroyuki\Dropbox\git-repository\psychopy\psychopy\hardware\keyboard.py", line 166 in __init__
  File "D:\work\import\untitled_lastrun.py", line 103 in <module>
```

It seems that some of my HIDs have non-ASCII characters in their names.
Is there anything I can do to fix this issue?

**Comment by peircej** [comment]
I guess the thing we need to do is work out whether the problem is at the level of the compiled psychtoolbox code (probably needs @kleinerm to fix) or the python wrapper (we can fix).

Could you try this:
```
from psychtoolbox import PsychHID
devices = PsychHID('Devices', device_class)
```

If that fails (without us trying to print or do anything with the device values) then the issue must presumably be with the compile code not converting strings into unicode. If that code passes then I guess it must be a failure on our part to handle the unicode values after they're received.

**Comment by hsogo** [comment]
What is the value of `device_class` (that is, the second argument of `PsychHID()`)?
If I omitted `device_class`, `PsychHID()` finished without error.  If I passed a number as `device_class` (I tried 0, 1, 2), Python process crashed without error message.

**Comment by peircej** [comment]
OK, device_class should be None or an int (device_class=4 is the one setting we use on windows only). If the issue is only caused by that setting then, in `get_keyboard_indices()` we could drop that part and just do `devs = devices()` for all platforms and rely on the other filters (`usagePageValue` etc) to find only keyboards.

Let me know if that fixes the issue you're seeing

**Comment by hsogo** [comment]
Replacing lines 51-54 of psychtoolbox/hid.py (see below) with 'devs = devices()', the Builder experiment run without error.

```
    if sys.platform != 'darwin' and sys.platform != 'win32':
        devs = devices(device_class=4)  # on linux this is just keyboards
    else:
        devs = devices()
```

**Comment by kleinerm** [comment]
Hm. Atm. the Windows version of PsychHID only distinguishes between no device_class given, -1, and other value. Each OS is very different in how it enumerates HID devices. Looking over the code, i can't see how this could cause a crash on Windows, unless the OS or some input device driver is buggy and returns a string which isn't 0-terminated. Have you tested on different Windows machines? If lack of 0-termination due to Windows driver bug would be the problem then i could implement a workaround in PsychHID. The code above should be the correct way to do it. One needs device_class=4 on Linux and some value, e.g., 4 on Windows, for devices to correctly enumerate. Leaving the value out gives macOS behaviour, which is only correct for macOS, as Linux and Windows use different ways of enumerating and selecting input devices.

**Comment by hsogo** [comment]
I've run Jon's code on 4 different Windows PC (three custom desktop PCs and DELL XPS13 notebook) and got the same  error (that is, Python process crashed without error message).  I attached VisualStudio Debugger to Python process and got following error.

![2](https://user-images.githubusercontent.com/2094930/57905722-6bd2ce00-78b2-11e9-93f3-f047b215da27.png)

This says "Access violation at address 0xC0000005, Write of address 0x0000000000000000".   I'm afraid that UnicodeDecodeError might occur because non-ASCII characters were not in device names, but in error message (Python returns error messages in Japanese on Japanese Windows10).

Where can I get source code of PsychHID?  I want to build and debug it on my PC, if possible.

**Comment by peircej** [comment]
You can see the code broadly at 
  https://github.com/Psychtoolbox-3/Psychtoolbox-3 
and probably, specifically
  https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/PsychSourceGL/Source/Windows/PsychHID/PsychHIDStandardInterfaces.cpp

Can compile with Python in the standard way (from the root of the project):
```
python setup.py build
python setup.py install
```

**Comment by peircej** [comment]
> One needs device_class=4 on Linux and some value, e.g., 4 on Windows, for devices to correctly enumerate

When I try on linux (I just tested on Mint) with `device_class=None` I do get devices back as expected, which we can then examine to detect keyboards using the `usage` fields etc so, as far as I can tell, using this method does _work_ even if it isn't _efficient_. 

What is the symptom of it being broken? Is there something I can test to show that it's actually not working after all?

**Comment by hsogo** [comment]
Thank you Jon, I downloaded the code and run it on VisualStudio debugger.

The problem occurs at `PyUnicode_FromString()` in `mxCreateString()` (line 436 of PsychScriptingGluePython.c).  This function converts **UTF-8** string to uniocde.  However, in Windows, encoding of device name is NOT UTF-8.  Actually, the encoding depends on locale, and it is **CP932** in Japanese Windows.

**Comment by peircej** [comment]
Good hunting @hsogo 
@kleinerm the line is https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/2ad56475c2b5059701e2616cc1b77a6f6f20380b/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c#L438

It looks like there's an alternative `PyUnicode_DecodeLocale(s)` https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeLocale

I guess the aim would be to use that, test if a result was returned, and fallback to UTF8 encoding if the locale encoding didn't work? @kleinerm, would you be interested in implementing that (or at least in a bugfix pull request?). Cheers, Jon

**Comment by kleinerm** [comment]
I've pushed two commits to my devel repo:
https://github.com/kleinerm/Psychtoolbox-3

Can you pull and see if it improves anything? While i can see why the
current code would crash on invalid UTF-8, as PyUnicode_FromString() should
fail and return a NULL ptr, which i didn't handle, i'm puzzled about the
location of the crash in PyUnicode_FromString(). It shouldn't crash on non
UTF-8, but just fail and set a UnicodeDecodeError exception. Spent some
time looking at CPython's implementation of these functions and can't see
obvious reasons for crashing. If i feed Shift-JIS text into the Linux
version, it returns NULL and UnicodeDecodeError as expected, but doesn't
crash in PyUnicode_FromString(). Can't test on Windows atm., i first have
to setup a new build system.

I've also added some code to PsychHID to protect against drivers
potentially returning non-0 terminated strings, which is the only obvious
way i could see to crash PyUnicode_FromString().

Maybe if it still crashes, add some printf() statements to the
mxCreateString() routine before the PyUnicode_FromString() like in the
following patch, so we can see what the actual input is:

diff --git
a/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c
b/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c
index 3ecd59ebd..7eaf4833d 100644
--- a/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c
+++ b/PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c
@@ -436,6 +436,11 @@ PyObject* mxCreateLogicalMatrix(ptbSize rows, ptbSize
cols)
 PyObject* mxCreateString(const char* instring)
 {
     PyObject* ret;
+    int i;
+    printf("\n");
+    for (i = 0; i < strlen(instring); i++)
+       printf("%d, ", (unsigned char) instring[i]);
+    printf("\n\n");

     if (!instring)
         return(PyUnicode_FromString("NULL"));

**Comment by hsogo** [comment]
Ah, I'm sorry for explaining enough.

The root of the error is `PyUnicode_FromString()`, but fatal error occurs when we access to NULL pointer returned by `PyUnicode_FromString()`.  Detail is as follows.
1. `PsychHIDEnumerateHIDInputDevices()` is called in `PSYCHHIDGetDevices()`
2. `PsychSetStructArrayStringElement("product", deviceIndex, dev->tszProductName, deviceStruct)` is called in `PsychHIDEnumerateHIDInputDevices()`.
3. In `PsychSetStructArrayStringElement()`, `mxFieldValue = mxCreateString(text)` is called. Value of `text` is `dev->tszProductName` **(line 3157 of PsychScriptingGluePython.c)**.
4. `mxFieldValue` is set to NULL because `PyUnicode_FromString()` in `mxCreateString()` returns NULL.
5. `mxSetField(pStruct, (ptbIndex) index, fieldName, mxFieldValue)` is called in `PsychSetStructArrayStringElement()` **(line 3160 of PsychScriptingGluePython.c)**.
6. In `mxSetField()`, `PyDict_SetItemString(arraySlot, fieldName, pStructInner)` is called.  Value of `pStructInner` comes from `mfFieldValue`, that is, NULL.
7.  `PyDict_SetItemString()` raises fatal exception because `pStructInner` is NULL.

**Comment by hsogo** [comment]
@kleinerm I downloaded your code and tested on my PC.  `PsychHID('Devices', 4)` run without exception and a lot of `"WARNING: INVALID UNDECODABLE STRING!"` appeared in the returned object.

**Comment by kleinerm** [comment]
@hsogo Ok, that makes more sense, thanks. Now the puzzle is why it would do that. I couldn't get the current code to ever end in that warning. Not with a NULL string, not with an empty string containing only a 0-terminator, not with a non-utf8 encoding, not even with a encoding that isn't the system locale. PyUnicode_DecodeLocale(instring, "surrogateescape"); always returned something - worst case simply the whole string in escaped untranslated form.

Can you comment out the PyErr_Clear() at the end of mxCreateString(), and add the patch mentioned above for printing the raw 'instring'? Something pretty weird happens here.

**Comment by kleinerm** [comment]
@hsogo: I've force-pushed another update, adding more fallbacks. Let's see how that goes. Apparently there have been multiple incompatible changes to the PyUnicode_DecodeLocale() function in Python 3.0 -> 3.2, 3.2 -> 3.6 and 3.6 -> 3.7, sometimes also only affecting specific OS'es. So to cover all bases we now try almost any half sane method. At the end it falls back to Latin-1 encoding, which worst case should at least return the raw byte data of the string, wrapped into Latin-1 Unicode values 0 - 255.

My suspicion after looking at CPython's code for over 8 hours now is that somehow some of your device(s) return a broken/incomplete multibyte character sequence, ie. the string is somehow truncated. Afaics, Python treats that as complete failure, throwing away even the part of the string that was correctly decoded, if any.

**Comment by hsogo** [comment]
@kleinerm Updated version returns the raw byte data of string like `'\x83L\x81[\x83{\x81[\x83h'`, which is `'キーボード'` (keyboard in English) in cp932 encoding. I added your patch (https://github.com/psychopy/psychopy/issues/2453#issuecomment-494659873) to update version and got following output (note that I modified `%d` to `%x` because I'm not familiar with decimal representation of cp932).
```
73,6c,61,76,65,20,6b,65,79,62,6f,61,72,64,

83,4c,81,5b,83,7b,81,5b,83,68,

83,4c,81,5b,83,7b,81,5b,83,68,

73,6c,61,76,65,20,70,6f,69,6e,74,65,72,

83,7d,83,45,83,58,

83,7d,83,45,83,58,

73,6c,61,76,65,20,63,75,73,74,6f,6d,65,72,20,75,73,61,67,65,

55,53,42,20,52,65,63,65,69,76,65,72,
(omitted below)
```
I copied these lines and saved as "output.txt" and run following python script.
```
import locale

# print encoding
print('Encoding: {}\n'.format(locale.getpreferredencoding()))

fp = open("output.txt","r")

for line in fp:
    l = line.rstrip()

     # drop last item because it is empty string
    items = l.split(",")[:-1]

    if len(items) > 0: # slip blank lines
        # original output
        print(l)
        
        # get Bytes object
        b = bytes([int(x, base=16) for x in items])

        # print Bytes object
        print(b)
        
        # Convert Bytes -> Str and print
        print(b.decode(locale.getpreferredencoding())+'\n')
```
The result was as follows.  All lines were successfully decoded.  Strings are encoded in cp932 and none of them is broken.
```
Encoding: cp932

73,6c,61,76,65,20,6b,65,79,62,6f,61,72,64,
b'slave keyboard'
slave keyboard

83,4c,81,5b,83,7b,81,5b,83,68,
b'\x83L\x81[\x83{\x81[\x83h'
キーボード

83,4c,81,5b,83,7b,81,5b,83,68,
b'\x83L\x81[\x83{\x81[\x83h'
キーボード

73,6c,61,76,65,20,70,6f,69,6e,74,65,72,
b'slave pointer'
slave pointer

83,7d,83,45,83,58,
b'\x83}\x83E\x83X'
マウス

83,7d,83,45,83,58,
b'\x83}\x83E\x83X'
マウス

73,6c,61,76,65,20,63,75,73,74,6f,6d,65,72,20,75,73,61,67,65,
b'slave customer usage'
slave customer usage

55,53,42,20,52,65,63,65,69,76,65,72,
b'USB Receiver'
USB Receiver
(omitted below)
```

**Comment by hsogo** [comment]
@kleinerm I found that [PyUnicode_DecodeMBCS()](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeMBCS) works fine on my PC.
My test code is [here](https://github.com/hsogo/Psychtoolbox-3/commit/2d12c166400b2a817e630091459b27839f95e221).  No error occurs and device names are correctly converted.

In my previous post, raw string was output.  I traced the code and found these output came from `PyUnicode_DecodeLocale(instring, "surrogateescape")` (note: I use Python3).  So `PyUnicode_DecodeMBCS()` must be tried before this function.

**Comment by kleinerm** [comment]
@hsogo Thanks for finding the solution! I've added your solution, fixed for style and with some explanation to my commit and force-pushed again. Finally i also found Microsoft docs which explain what is happening here and why, so this makes sense.
