### ISSUE TITLE
NUMPAD not recognized

### ISSUE THREAD

**Issue by mirh** [psychopy/psychopy#2471]
For starters I think if I set `'5'` to a key press, it should get triggered by it, and it doesn't. 
But then, I also tried all the possible combos of this worlds (NUMPAD_5, NUM_5, VK_whatever_5) to no avail. 

I wonder if you haven't [lost](https://github.com/psychopy/psychopy/blob/3bf8a1c4ead9570552b58de309ad7f04f150b68a/psychopy/CHANGELOG.txt#L2003) support with the py3 [switch](https://discourse.psychopy.org/t/python3-compatibility-issues/3581/3).

**Comment by m-macaskill** [comment]
Please provide a minimal reproducible example of the issue, and details of version numbers and operating system.

**Comment by peircej** [comment]
Have you tried the what_key demos (there's one in the Builder and Coder demo menus)? These allow you to test on your keyboard what the name of any given key is

**Comment by peircej** [comment]
On the other hand, this is the top hit searching for "psychopy numpad"
https://discourse.psychopy.org/t/numbers-on-the-right-side-of-the-keyboard-are-not-working/1728/2
and might be what you need?

**Comment by mirh** [comment]
`'num_5'` did the job. I wasn't really expecting the thing to be case-sensitive. 
(and I wasn't expecting somebody to call the thing "numbers on the right side", lol)

So, in this sense is already *less* of a bug... But I don't know, I would imagine the program at least by default behavior to work at the symbol level (_1_ is always _1_) rather than the virtual key one?

**Comment by peircej** [comment]
The fact that this is case sensitive really shouldn't be surprising. Strings are generally case sensitive in programming. Nothing is being done to detect the meaning of the key. This is simply the key's name, not a value that it represents, which changes in complicated ways according to the operating system, the keyboard settings, the locale and the combination of modifier keys being pressed.

**Comment by mirh** [comment]
Makes sense. 
But you could at least mention it [here](https://www.psychopy.org/builder/components/keyboard.html) though.
