### ISSUE TITLE
Version number lagging?

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#2473]
Should the version number of the latest release not now be 3.1.2? I'm not sure where this is actually specified, outside of this automatically generated file:

https://github.com/psychopy/psychopy/blob/3bf8a1c4ead9570552b58de309ad7f04f150b68a/psychopy/__init__.py#L15

**Comment by peircej** [comment]
was fixed in 723891f0bd0c393f11e602447798dc1f72fe95be which hadn't initially been pulled in to master
