### ISSUE TITLE
expression: FALSE

### ISSUE THREAD

**Issue by apoptoticbleb** [psychopy/psychopy#2476]
PsychoPy 3.1.2 (and 3.1.1, both 64 and 32-bit versions have been attempted) are both crashing immediately after I launch PsychoPy and the builder window opens. I am getting the following error with 3.1.1:

Program: C:\Program Files (x86)\PsychoPy3\python.exe
File: src/hostapi/wdmks/pa_win_wdmks.c, Line 1061

Expression: FALSE

I’m not sure what the most useful system info is, but I am running Windows 10 home 64-bit (v.1809) on a Dell XPS 9550 from 2015. I believe this is an issue with portaudio but I can't seem to get around it by updating my sound driver or changing it to a default Windows one. 

Any help with getting PsychoPy to run on my machine would be supremely appreciated! Thanks!

**Comment by mirh** [comment]
https://github.com/spatialaudio/python-sounddevice/issues/7
I guess like you could try pyo, or you could swap libportaudio dlls (in whatever folder `site-packages\_sounddevice_data\portaudio-binaries` is) with [the ones here](https://github.com/adfernandes/precompiled-portaudio-windows/blob/master/portaudio-r1891-build.zip?raw=true) renamed.

**Comment by apoptoticbleb** [comment]
Hey mirh, thanks for your reply! Are you able to provide any more info on how to try pyo as you said? I'm a beginner at all of this!

**Comment by mirh** [comment]
Just swap the order of entries in the hardware tab of the psychopy preferences.

**Comment by apoptoticbleb** [comment]
Ok, how do I access the preferences? If you're referring to the userPrefs.cfg file I can't seem to find it and don't think I have one yet? The program has never run successfully.

**Comment by mirh** [comment]
Oh right.. It's crashing before it can even launch. 
Then you could try to create your own `userPrefs.cfg` in `%appdata%\psychopy3` with
```
[hardware]
    audioLib = pyo, sounddevice, pygame
```
...or edit [this line](https://github.com/psychopy/psychopy/blob/3.1.2/psychopy/preferences/Windows.spec#L111).

Or as I said, swap portaudio dlls.

**Comment by apoptoticbleb** [comment]
Holy cow, that worked!

I tried making my own userprefs file and adding that line to it but nothing changed.  I'm not sure how to edit that line like you said. 

the portaudio-binaries folder contained a readme and then libportaudio64bit.dll.  In that zip file you sent I copied over the portaudio_x64.dll file from x64/Release and renamed it libportaudio64bit.dll (just a wild guess, I don't know why they would be different names), and that worked!  Why did that work? haha

Thanks so much mirh, sending you good karma now.

**Comment by daciansolgen3** [comment]
File "C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\dacia\Desktop\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
