### ISSUE TITLE
TESTS: Upcoming issue with TravisCI and Xenial

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#2477]
This is a pre-emptive bug report because I just had to deal with it in PyHab's testing environment (which is a partial clone of PsychoPy's) and it'll hit you soon enough: Travis is shifting its default linux build to Xenial for everyone this month, and that breaks some stuff that PsychoPy needs in its environment setup, specifically libavbin0. So, you will either need to add dist: trusty to the travis.yaml file when you define your environment, or you'll need to figure out what to change in order to get it to play nice with Xenial. I went the former route.

**Comment by peircej** [comment]
Thanks for the heads-up. I have installed PsychoPy on 16.04 and 18.04 so I'm sure we'll find a way, but thanks for the warning.

**Comment by peircej** [comment]
Oh, FYI we are currently setting `dist: trusty` explicitly which is why we probably haven't been bitten by this already.

**Comment by TEParsons** [comment]
The test suite runs via GitHub Actions rather than Travis now so closing this
