### ISSUE TITLE
VNC input not working while running experiment

### ISSUE THREAD

**Issue by vnckppl** [psychopy/psychopy#2483]
I have an iPad connected to my Mac via VNC. I would like to use the iPad as input device (yes, I am aware of the potential lag). 

My mac registers input from the iPad just fine in any app, including PsychoPy, except for when PsychoPy is running an experiment. 

How can I have PyschoPy register input from my iPad via VNC during whilst running an experiment?

**Comment by peircej** [comment]
I'm afraid I have no idea about how VNC interactions work and what would be needed for this. I think it's more something to try asking about on the forum though, rather than here (which is more for bugs etc). I don't see it being something the core team would spend time trying to support.
