### ISSUE TITLE
Dialogue appearing behind the window

### ISSUE THREAD

**Issue by Volcore** [psychopy/psychopy#250]
Hi,

I'm currently building an experiment where the user is supposed to enter her/his age. I've tried using gui.DlgFromDict for that. The problem is that the dialogues seem to appear behind the main window, rendering them invisible in fullscreen mode (which is required for this study). 

This happens on both OSX and Windows 8, and I've tried version 1.74 and 1.76 RC1.

I've tried playing around with the psychopy settings for allowGUI, fullscreen, and the project settings for fullscreen, allow mouse, to no avail so far. I've also tried pyglet and pygame, without success. 

I can see the dialogue box in the tab bar preview when i press alt+tab in fullscreen mode on windows 8, but I can not get it into the foreground.

Am I missing something, or is this maybe a regression and it should work with an older version of psychopy?

Cheers,
Volker

**Comment by shanishalgi** [comment]
Hi, I am running my window with allowGUI=False
myWin = visual.Window([1280, 1024],monitor='acerLCD',allowGUI=False,units='pix',waitBlanking=False)
and my dialogs following are displayed behind the window. This just started happening, after I installed a new (better - NVIDIA GeForce GT-730) graphics card. Before the instalation all the dialogs were presented on top of the screen and everything was ok.

**Comment by nateGeorge** [comment]
@shanishalgi looks like you can call `dlg.activateWindow()` and bring the window to the front.

**Comment by nateGeorge** [comment]
Here is how to do it: https://stackoverflow.com/a/56550014/4549682

(code snipped copy-pasted):

```python
# bring window to top and act like a "normal" window!
window.setWindowFlags(window.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)  # set always on top flag, makes window disappear
window.show() # makes window reappear, but it's ALWAYS on top
window.setWindowFlags(window.windowFlags() & ~QtCore.Qt.WindowStaysOnTopHint) # clear always on top flag, makes window disappear
window.show() # makes window reappear, acts like normal window now (on top now but can be underneath if you raise another window)
```

**Comment by nateGeorge** [comment]
I was able to get it working with:

```python
from PyQt5 import QtCore
dlg = gui.Dlg(title="Error")
dlg.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
dlg.show()
```

**Comment by peircej** [comment]
@nateGeorge I don't think that solves the issue of dialogs appearing on top in full-screen mode. It *shouldn't* affect that anyway! 
Always-on-top could help, though, in the case of not being in fullscreen mode but the user clicking on the psychopy window or moving to a different app while waiting for the dialog to appear

**Comment by nateGeorge** [comment]
@peircej right, sorry, that only works if you are not in fullscreen. For me in Win10, the window was behind the console I was running the code from.
