### ISSUE TITLE
Incorrect documentation for mouseVisible and allowGUI

### ISSUE THREAD

**Issue by ariekahn** [psychopy/psychopy#2524]
Version: 3.1.4
Platform: Mac

The documentation for `mouseVisible` states that:
> If Window was initialized with ``allowGUI=True`` then the mouse is
> initially set to invisible, otherwise it will initially be visible.

I think this may be backwards. The behavior I see is that `allowGUI=True` shows the mouse, otherwise it's hidden, which seems more sensible anyways.

Should the docs be updated?

**Comment by m-macaskill** [comment]
Thanks for your report @ariekahn
