### ISSUE TITLE
I have issues with the frameclock attribute of window

### ISSUE THREAD

**Issue by alucardkoten** [psychopy/psychopy#2527]
Basically, when I initialize an experiment, only background comes out without text. And It takes very long until the text comes out. The error message seems to be about the "win" object cannot fetch the framerate. And replicate this in the monitor center, the error message says that "Window" object has no attribute "frameclock."

**Comment by peircej** [comment]
We'll need more info than that (this isn't a normal problem). Please paste in the complete error message and provide info about your platform and how you installed PsychoPy

**Comment by peircej** [comment]
Will reopen if we get further info about the issue
