### ISSUE TITLE
Add parselmouth to standalone distr

### ISSUE THREAD

**Issue by YannickJadoul** [psychopy/psychopy#2531]
Is there any reason why I cannot install packages with `pip` into a standalone distribution of PsychoPy? I know I'm stretching the installation a bit like this, but when I run, for example:

```
$ export PYTHONPATH=/Applications/PsychoPy3.app/Contents/Resources/lib/python36.zip
$ /Applications/PsychoPy3.app/Contents/MacOS/python -m pip install praat-parselmouth
```

I get an error saying `No module named pip.__main__; 'pip' is a package and cannot be directly executed`. A similar thing happens when I try to do this with `subprocess` and `sys.executable` from within the PsychoPy Python shell.

To sketch the context a little bit: I have created a Python library for the Praat software (phonetics and speech related), [Parselmouth](https://github.com/YannickJadoul/Parselmouth), and one of its selling points is that it can be easily integrated with PsychoPy. However, [the current instructions to install it into a standalone version of PsychoPy](https://parselmouth.readthedocs.io/en/latest/installation.html#psychopy), are ... rather extensive, following your [guide on using external modules](https://www.psychopy.org/recipes/addCustomModules.html).

However, given the hassle of making sure potential users download the correct version of the library (given the Python version and OS), it would be nice if `pip` could do this automatically since it was designed to do all that.

So, I'm wondering: Is there any reason this method is disabled in standalone PsychoPy? Would there be another way of using `pip`, or making the process a little bit easier? I'd be happy to help out and contribute if this would require some work on the PsychoPy side :-)

**Comment by peircej** [comment]
pip isn't deliberately disabled but I don't know what's going on - I think it's to do with the way that py2app 'freezes' the application. I guess the expectation is that an application shouldn't change after installaton. 

I do have in my head that we could change the way standalone works, to use an installer script that launches pip/conda rather than installing the files directly. 

But also I'm very happy simply to package Parselmouth *as a part of* Standalone. It seems like a very handy package for our linguist friends! :-) you'd need to let me know when updates should be made though

**Comment by YannickJadoul** [comment]
Thanks for the quick reply! :-)

> pip isn't deliberately disabled but I don't know what's going on - I think it's to do with the way that py2app 'freezes' the application. I guess the expectation is that an application shouldn't change after installaton.

Ha, I'm not familiar with `py2app`, but that makes sense!

> But also I'm very happy simply to package Parselmouth as a part of Standalone. It seems like a very handy package for our linguist friends! :-) you'd need to let me know when updates should be made though

That would be great and greatly appreciated by those linguists, I'm sure! I find it hard to get an idea of how much exactly this would be used, though, and given that Parselmouth's wheels are currently [+- 7 to 9 MB in size](https://pypi.org/project/praat-parselmouth/0.3.3/#files) (I fully compile Praat's source code and include as part of the library), I'll leave that tradeoff/decision up to you.
I'm more than happy to drop a line whenever I release a new version, though!
