### ISSUE TITLE
Windows installer 64bit use 32bit installation dir

### ISSUE THREAD

**Issue by marcogaio** [psychopy/psychopy#2535]
I'm testing your software, in a mixed Win7 32/64bit enviroment.

Seems that installer does not respect fully the Windows rules: the 32bit installer on a 64bit environment correctly install the software on %ProgramFiles(x86)% path, but also 64bit installer install software on %ProgramFiles(x86)% path, instead on %ProgramFiles% path.

Also, seems that '/D=' option does not work, in silent mode. EG:
  StandalonePsychoPy3-3.1.5-win64.exe /S /D=%ProgramFiles%\PsychoPy3

still install software on %ProgramFiles(x86)%\PsychoPy3 .

Thanks.

**Comment by peircej** [comment]
Ah, it looks like the NSIS script needs to be told to use $PROGRAMFILES64 instead of just $PROGRAMFILES (not the way I would have organised the decision but never mind). We'll need to add in a test to see if $arch is '64bit' and change the $InstDir value to be $PROGRAMFILES64 accordingly

**Comment by peircej** [comment]
https://github.com/psychopy/psychopy/blob/14088062c579e4a15b76198ec83c22849e8188b2/buildCompleteInstaller.nsi#L103

**Comment by peircej** [comment]
see commit 8cd75b8072f9b48c3d9ea3965217c5df892a2c31

**Comment by marcogaio** [comment]
Ahem, i'm not a windows developer, so it is a bit hard for me to setup a build environment to build a test installer: can provide you one to test?

Also, for the '/D' option, i've tried also:
  StandalonePsychoPy3-3.1.5-win64.exe /S /D=C:\PP3

and still install software on %ProgramFiles(x86)%\PsychoPy3, ignoring totally '/D'.

**Comment by peircej** [comment]
Yes, don't worry. I'll be making one and testing it for the next release. I was just logging the necessary change here for the record. To make /D flag work I'll have to read more about NSIS scripts (they're complicated and something I only occasionally work on!)

**Comment by marcogaio** [comment]
OK, many thanks!!!

**Comment by marcogaio** [comment]
I've tried 3.2.4 and seems fixed, thanks!
