### ISSUE TITLE
'No parameters set/conditionsFile not found' Files not being imported 

### ISSUE THREAD

**Issue by carlijnoo** [psychopy/psychopy#2539]
Trying to import an xlsx conditions file in builder, this worked until yesterday (July 18 EST) morning, now nothing seems to work anymore. Also, often when I try to upload a file through the browse function, it loads for a very long time and then crashes/shuts down psychopy. 

I have tried converting the file to csv, checked the file multiple times, checked with different files, made a new projects and tried with different xlsx and csv files - nothing imports. I’ve also tried putting the path to the file in manually. Experiments that worked before with their respective conditions file now also don’t load those or others in anymore.

What specifically went wrong when you tried that?
It either does not seem to reach the file at all - after using Browse… it will still say `no parameters set` or the file's name will come up (but only in about 20% of the time) and then say `no parameters set (conditionsFile not found)`.  
I don't have any columns in the file starting with numbers, so that shouldn't be the problem

**Comment by TEParsons** [comment]
We've changed a fair bit about how conditions files are loaded in since this issue was raised, could you give it another go in the latest version (2021.2.2)?
