### ISSUE TITLE
Feature Request - Run Local Development Version

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#2553]
Discussion started from [psychopy's discourse](https://discourse.psychopy.org/t/resource-registration-management-of-psychojs/7136/2), but it would be great to run a local development version of psychojs tasks to avoid the `edit - commit - push - test - repeat` cycle. 

The main problems are:

1. Lib management (npm / yarn? How is this handled in pavlovia's environment now?)

2. Local server - Some local server must be started just to serve the files in a way they'll be validly loaded due to cross-site restrictions, either python -m SimpleHTTPServer  -m http.server (py2 / py3).

3. Local server-side script for handling 1. building and serving config.json and 2. saving data to the local disk. I see a server manager in the psychojs lib ("remote PsychoJS manager running on the remote https://pavlovia.org server"), but the remote manager doesn't look like it's part of the client-side code anywhere. Is this available / planned to be released?

Even if it's not built in to the builder _yet_, it would be helpful to discuss a first pass at making this work. @peircej suggested fixing 1) by loading scripts remotely from pavlovia.org, which is a fine solution but will be pretty aggressive on server load if we actually build it and release it that way. Perhaps including a version .lock file that could be read would be one step, though that introduces dependencies on a manager (npm, eww) that I'd want to avoid. Any thoughts on any of these (really, 2-3 are the same for the purposes of fixing things I think). 

Thanks,

**Comment by kastman** [comment]
Ohh, issue transfer? Fancy! I think there's likely still some substantial work that would happen in psychojs re: packaging, dependency management, but there may be more in psychopy so I'm good with the switch. 👍

**Comment by dvbridges** [comment]
@kastman , local debug mode is available from #2771

**Comment by kastman** [comment]
Thanks @dvbridges  - can't wait to kick the tires!
