### ISSUE TITLE
Pavlovia "the PIXI representation of the stimulus is unavailable"

### ISSUE THREAD

**Issue by mayagos** [psychopy/psychopy#2559]
The project:
https://gitlab.pavlovia.org/Goschorska/doors_test

The experiment runs fine locally (PsychoPy), but not on Pavlovia.

I'm getting two errors:
1. Cannot find two of the stimuli (images of arrows). 
2. If  I remove the arrows, the instructions screen is correctly displayed, but then:
![image](https://user-images.githubusercontent.com/53911158/62719083-85923600-ba07-11e9-8507-38ff0e1ab91d.png)
I tried to apply the correction from other similar threads, but the error stays. What am I doing wrong?

**Comment by peircej** [comment]
Most likely this is an issue with the experiment rather than with PsychoPy itself. The forum is the right place to discuss that.
