### ISSUE TITLE
calculate and log memory usage for ImageStim (OpenHatch?)

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#256]
This might be an OpenHatch-sized issue.

It would be useful to save the memory usage of visual.ImageStim into the log file (e.g., as the last thing that ImageStim.**init**() does).

sys.getsizeof() does not do the trick. There are ways to extend it, but the simplest approach might be to calculate the expected usage (size-x \* size-y \* bytes per pixel), taking into account that its an RBGA image, and might have a mask. There might be other things going on too, so verifying the numbers is important.

logging.info('ImageStim init: expected memory usage = %.1f kB' % (bytes / 1024.))

Extensions: do the same thing for BufferImageStim, GratingStim, MovieStim, SimpleImageStim, ...

**Comment by peircej** [comment]
Closing this for long inactivity! :-)
