### ISSUE TITLE
Playing sounds for 0.5 seconds or less

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#2564]
Just by chance today, we tested an experiment where a student is playing two sound files with short durations of 0.5.

- First sound starts at 0 and finishes at 0.5.
- There is a 1 second gap
- Then a second sound plays at 1.5 and finishes at 2 seconds (0.5 duration).

This works perfectly on 1.85.3, but on 3.1.3 (Py2 32-bit edition, Win 10) the two sound components overlap.   This is because there is now a check to see if the duration is greater than 0.5, and if it isn't then the .stop() function isn't ran.

I believe that this was to fix another issue as detailed here: https://github.com/psychopy/psychopy/issues/2446#issuecomment-491222608 

I'm just wondering if there might be a better way of checking that a sound isn't stopped before its started,  as the current fix now prevents quick duration sound playing for anything 0.5 seconds or less.  I suspect there will be quite a few people who would have a need to run sounds for that time or less as well.

**Comment by peircej** [comment]
Oh. I can look into that. Actually right now I'm about to release 3.2.0 which has an entirely new enginge based on the psychtoolbox code. That has much, much faster timing and I think we don't need to worry about this catch anyway. I'll try and replicate the effect myself and then see what is needed to fix it on both the old and new sound engines. I might need you to send a minimal example of the issue if I can't easilly replicate from your description

**Comment by frankgasking** [comment]
Hi Jon,

Here is a test script demonstrating the issue.    If you change the sound durations to > 0.5, then it works fine.   Hope this helps.

If its fixable for 3.2.0 - then I may ask them to use this version for the upcoming academic year.
[sound-test.zip](https://github.com/psychopy/psychopy/files/3500997/sound-test.zip)


Frank

**Comment by peircej** [comment]
OK, yes, I'm just going to get rid of that short-stimulus test altogether. It's caused more probs
than it solved! This will be in 3.2.0
