### ISSUE TITLE
Issues syncing with Pavlovia (maybe related to gitlab library)

### ISSUE THREAD

**Issue by mkallmayer** [psychopy/psychopy#2572]
**OS:** Linux (5.2.9-arch1-1-ARCH)
**Python Version:** 3.5
**PsychoPy Version:** 3.1.5 (pip install)
**python-gitlab Version:** 1.10.0

Hey there,

up until recently, I've had no issues syncing with Pavlovia whatsoever.
However, when I tried syncing a project (with which I've had no issues before) with Pavlovia, I got the following error, which seems to be raised by the overloaded \_\_eq\_\_ function for gitlab projects:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/psychopy/app/builder/builder.py", line 2393, in onPavloviaRun
    pavlovia_ui.syncProject(parent=self, project=self.project,
  File "/usr/lib/python3.5/site-packages/psychopy/app/builder/builder.py", line 2438, in project
    elif self.filename and pavlovia.getProject(self.filename):
  File "/usr/lib/python3.5/site-packages/psychopy/projects/pavlovia.py", line 1100, in getProject
    if proj.pavlovia == 0:
  File "/usr/lib/python3.5/site-packages/gitlab/base.py", line 105, in __eq__
    if self.get_id() and other.get_id():
AttributeError: 'int' object has no attribute 'get_id'
```
So, to my understanding, the bug is caused because the evaluation of

```python
proj.pavlovia == 0
```

calls the line 

```python
...
        if self.get_id() and other.get_id():
...
```

in .../python3.5/site-packages/gitlab/base.py: ```__eq__()```, which basically throws a runtime type error because ```0``` is not  a gitlab project object. Why this only occurs after reopening a project is a mystery to me, though. 
Maybe it has something to do with the way the Pavlovia project corresponding to a .psyexp file is fetched when opening a .psyexp file or that the process of retrieving the project from the knownProjects file may be broken. The project settings were stored correctly in ~/.psychopy3/pavlovia/projects.json:

```json
  "mkallmayer/bug_repl": {
    "id": "mkallmayer/bug_repl",
    "idNumber": 11028,
    "localRoot": "[...]/.testing/bug_replication",
    "remoteHTTPS": "https://gitlab.pavlovia.org/mkallmayer/bug_repl.git",
    "remoteSSH": "git@gitlab.pavlovia.org:mkallmayer/bug_repl.git"
  },

```

I have been able to replicate this behaviour under the following conditions:
When creating a new experiment in builder and syncing after creating a new Pavlovia project (all within PsychoPy), initial syncing works just fine, even pushing changes made in the same session works. However, when I reopen the .psyexp file (doesn't matter whether I reopen PsychoPy as well), the error occurs.

Deleting both ~/.psychopy3/pavlovia/projects.json and $project/.git yields the same behaviour as creating a new project: syncing with Pavlovia works in the current session but will throw the same error in a new session.

I should maybe also add that I have no issues syncing using the terminal.

Another note: libgit2 was recently (2019-08-15) updated on my machine. I don't know whether this is relevant or not (I presume it's not).

Has anyone else run into this?

**Comment by peircej** [comment]
Thanks for looking into this. Basically, you're using a newer version of python-gitlab to me. (I've been packaging version 1.5.1 and they've added a new function to the __eq__ operator which is leading to your issue, so we can't now test directly against an integer. 
https://github.com/python-gitlab/python-gitlab/commit/3d60850aa42351a0bb0066ef579ade95df5a81ee#diff-88b7b76c9248a07e02a7119df9c96dcf

So I think you could do one of:

- downgrade your python-gitlab to 1.5.1
- apply the fix in the commit that I'm currently pushing:
   `if proj.pavlovia and proj.pavlovia.get_id() == 0:`

**Comment by peircej** [comment]
Thanks for tracking it down for us
