### ISSUE TITLE
TextStim position when using Pyglet 1.4+

### ISSUE THREAD

**Issue by tiborauer** [psychopy/psychopy#2590]
I have tried the latest TESTING version (as in master), because I have noticed that it has gammaErrorPolicy implemented.
However, running the same script as I used in 3.1.5, caused TextStim severely misaligned horizontally (shifted leftwards), even though stim.pos = (0,0).

**Comment by peircej** [comment]
Were you using a Standalone installation? If not, what version of pyglet do you have installed?

**Comment by tiborauer** [comment]
I installed from the GitHub via pip, so it was the latest pyglet (1.4.2). Switching back to version 1.3.2 solved the issue. Thank you for the hint.

**Comment by mdcutone** [comment]
Pyglet 1.4 overhauled how text positioning works. I haven't figured out yet how to convert the old positioning system to work with the new one without breaking anything.

**Comment by EoinTravers** [comment]
This also comes up if you follow the conda installation instructions on https://www.psychopy.org/download.html.

I've proposed a change (https://github.com/psychopy/psychopy/commit/6a287ee4c8cf369cac98a1733cbb6f208c501d70) that should work.

**Comment by vijaygopal1234** [comment]
Until this is fixed, can we update installation instructions or change the requirements when installed from pip? It took me a while to understand this bug on Linux, and it would be nice is there was a note or the dependency requirements are changed.

https://www.psychopy.org/download.html

**Comment by peircej** [comment]
Master branch now supports pyglet 1.4 with correct text alignment. Additionally now supports text alignment of multiline text (center left or right)

**Comment by peircej** [comment]
Fixed in #2693
