### ISSUE TITLE
builder: conditional branching

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#26]
branching is possible in the builder (branching.psyexp), yet it would be more intuitive to have bifurcating lines in the flow panel that translate into "if: ... else: ..." in lastrun.py

**Comment by mirh** [comment]
So.. Did that go anywhere?
There's still no straightforward way to control the number of times one same stimulus is presented inside a trial. 

An idea I had was an "universal" loop button (which could be applied to just about everything, including single components *inside* a routine, with whatever granular conditions/wait time), or some kind of "repeat" tab for all the possible elements that might benefit of it.

**Comment by peircej** [comment]
To repeat stimuli within a trial you can simply use a loop. That doesn't need the sort of conditional branching we're talking about here.
![image](https://user-images.githubusercontent.com/380582/57986197-dda14800-7a69-11e9-8203-52ddd88838ec.png)

To the question of what happened to the branching suggestion... that is still intended but current issues around making online studies work smoothly are more pressing

**Comment by mirh** [comment]
I see. Would be cool if you could at least add/update your wiki here with an updated TODO tho :stuck_out_tongue: 

Anyway (putting aside that it's kind of ugly to sub-divide routines that way) I need to sync more than a single image with respect to each other. 
And even though at least in this case none of them is simultaneous (i.e. I could somehow keep track myself of "global time" and have them kind-of sequential this way) it seems even more ghetto and shaky than my current "normally add all the stimuli that should be conditional to the routine in builder, then manually add the condition to the `.status == NOT_STARTED` line" solution
