### ISSUE TITLE
Replace video file in MovieStim demo, the playback speed is slower than the actual video

### ISSUE THREAD

**Issue by SeanYXWang** [psychopy/psychopy#2606]
Hi

After replacing the default video file in MovieStim demo, the playback speed is slower than the actual video playing speed, I didn't find a method to set the playback speed or frame rate, or I missed it, Could any developer help me with this problem? 

Thanks 
Sean

**Comment by SeanYXWang** [comment]
resize the stimulus before play it in movieStim, seems solve the problem. see joe's comment here.[https://discourse.psychopy.org/t/frame-drop-causing-audio-video-lag-with-moviestim3/3800/12](url)

**Comment by peircej** [comment]
yes, presenting high-res movies does present difficulties (although I would have expected it to be playing at the right "speed" just skipping frames if it got behind). So it's something for us to look into in the future.
