### ISSUE TITLE
enter table no respond

### ISSUE THREAD

**Issue by yeshuaikang** [psychopy/psychopy#2625]

**Comment by peircej** [comment]
Sorry, could you expand on that please?

**Comment by yeshuaikang** [comment]
And this phychopy have some bug,te big trouble I think is the table,such as ,when I set the instruction is’please pint the ‘enter’table to end the experiment,but it have no respond. Jast always repain the interface.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jon Peirce <notifications@github.com>
发送时间: Tuesday, September 24, 2019 10:19:13 PM
收件人: psychopy/psychopy <psychopy@noreply.github.com>
抄送: 叶帅康 <y6663960@Outlook.com>; Author <author@noreply.github.com>
主题: Re: [psychopy/psychopy] enter table no respond (#2625)


Sorry, could you expand on that please?

―

**Comment by peircej** [comment]
Sorry, your message really isn't clear. Please rewrite carefully, or with someone that has better english, to help explain the issue. We can't fix anything from the information provdided.

**Comment by yeshuaikang** [comment]
In this software there is a big problem, is that I set up a stimulus presentation feedback is to press ‘enter‘ built, clearly set in it to press the ‘enter‘ key can skip this interface, but ’enter‘ key can not, i'm sorry, my English level is somewhat poor, please understand.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Jon Peirce<mailto:notifications@github.com>
发送时间: 2019年9月24日 22:36
收件人: psychopy/psychopy<mailto:psychopy@noreply.github.com>
抄送: 叶帅康<mailto:y6663960@Outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [psychopy/psychopy] enter table no respond (#2625)


Sorry, your message really isn't clear. Please rewrite carefully, or with someone that has better english, to help explain the issue. We can't fix anything from the information provdided.

―

**Comment by peircej** [comment]
We can reopen this if it becomes clear that there is actually a bug to fix
