### ISSUE TITLE
Print a log message / warning when compiled experiment contains a disabled component

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2633]
We ran into an issue with some parts of an experiment mysteriously not working, only to find out (after lengthy “debugging” via email) that we had disabled some essential components for testing purposes earlier, and forgot to enable them again. Finding the cause of the issue would have been easier had there been a log message indicating that some components were still disabled.

**Comment by peircej** [comment]
Too much fine-grained ability to disable things? ;-)

**Comment by hoechenberger** [comment]
The “Disable component” thing is actually used frequently in our lab, so I generally like it ;) Maybe graying out disabled component icons (not just their “time bar”) in the flow could have helped here, too...

**Comment by dvbridges** [comment]
We can add a new alert using the new alert system we are developing. I will add relevant tests etc tomorrow.

**Comment by hoechenberger** [comment]
sounds neat!

**Comment by hoechenberger** [comment]
I think #2636 does the trick for me, so closing for now. But feel free to reopen!
