### ISSUE TITLE
Demos menus (coder and builder) should incl links to wiki pages

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#264]
For examles of how to include URL links in a menu see the code for the help menus (with links to the psychopy home page)

Suggested link from coder:
http://www.psychopy.org/wiki/home.php/Code/Experiments
Suggested link from Builder:
http://www.psychopy.org/wiki/home.php/Builder/Experiments

The links should ideally come at the top of the menu with a separater for the other entries in the menu (which are actual demos).

**Comment by jeremygray** [comment]
How about links to API pages for Coder demos?
