### ISSUE TITLE
Remove uses of `**kwargs`

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2645]
A number of classes have been written to use `**kwargs` which is something I'm increasingly strongly against. It makes things easier as a developer because you don't have to add arguments to subclasses after adding them to the Super, but for the user allow kwargs means that I can now supply args with typos and not get an erorr message.

Classes where it's caused me issues already:
- Window (used so the kwargs can be passed to backends)
- Rect, Circle etc (passing kyargs to BaseShapeStim)

I'm in favour of going through these and manually inserting the additional arguments where they are correct, unless someone (@hoechenberger ? @mdcutone ?) has an idea of how to allow this for passing thoruhg but still detect kwargs that have/will not been used?

**Comment by hoechenberger** [comment]
I’m totally not a friend of **kwargs either, let’s kick those out wherever possible.

**Comment by mdcutone** [comment]
Yeah, let's get rid of them. But there are some cases where they are used for backend specific features, like things GLFW supports but Pyglet doesn't. We'll probably need to check if the argument is supported by the backend and raise an implementation warning if not.

**Comment by mdcutone** [comment]
This has been resolved in a recent PR.
