### ISSUE TITLE
Documentation about preferences the audio backend is incorrect

### ISSUE THREAD

**Issue by maartenuni** [psychopy/psychopy#2651]
On the page: https://www.psychopy.org/api/preferences.html
The following code is mentioned in order to set the backend for the psychopy.sound.Sound class.
```
from psychopy import prefs
prefs.general['audioLib'] = ['pyo']
from psychopy import sound
```
However, this doesn't seem to work. After the inspection of the configuration file and the following page https://www.psychopy.org/general/prefs.html I came to the conclusion that 
`prefs.hardware['audioLib'] = ['pyo']`
does the trick.

On the page about sound presentation with psychopy https://www.psychopy.org/api/sound.html there is a hyperlink that points to the incorrect documentation confusing the users it is the highlighted link called "setting the audioLib option".

So perhaps the code fragment can be changed to reference `prefs.hardware['audioLib']` instead of `prefs.general['audioLib']`

**Comment by m-macaskill** [comment]
I think you are correct. For a tiny change like that, you could edit the source of that page directly within Github here:
https://github.com/psychopy/psychopy/blob/master/docs/source/api/preferences.rst

and issue a pull request to have it incorporated.

**Comment by peircej** [comment]
Thanks @maartenuni
