### ISSUE TITLE
Incompatibility of name of numpad keys

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#2660]
OS: Windows 10
PsychoPy version: 3.2.4 64bit

Attached file is a simple Builder experiment that shows name of pressed keys.
[keyname_test.zip](https://github.com/psychopy/psychopy/files/3750445/keyname_test.zip)

When I run this experiment on 64bit version of PsychoPy 3.2.4, number keys on numpad return `'end'`, `'Down'`, ... even if numlock is enabled.  On the other hand, on Builder's keyNameFinder demo, they return `'num_1'`, `'num_2'`, ...  This is because the attached experiment uses `psychopy.hardware.keyboard` module (i.e. PTB keyboard module) while keyNameFinder demo uses `psychopy.event.getKeys()`.  This means that experiments created on old versions of Builder (which use `psychopy.event.getKeys()`) may not work on the latest Builder if numpad keys are used.  

Is there any good way to resolve this incompatibility?

**Comment by peircej** [comment]
I have actually seen this on a laptop and I basically don't know the answer. If we're reasonably confident that the keys map that way consistently then we could just remap the keycode to these names. My concern is that it varies by keyboard. Open to suggestions though!

**Comment by hsogo** [comment]
I compared codes returned by `psychopy.hardware.keyboard` module with Windows virtual key codes ([link](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)) and guessed that the module returns virtual key codes.  If so, lines 431-433 of psychopy/hardware/keyboard.py should be as follows.

```
    97: 'num_1', 98: 'num_2', 99: 'num_3',
    100: 'num_4', 101: 'num_5', 102: 'num_6', 103: 'num_7',
    104: 'num_8', 105: 'num_9', 96: 'num_0',
```

This doesn't fix the problem completely (numlock key still has no effect), but fixes the issue that name of numpad keys collide with other keys (e.g. numpad_2 key returns 'down').

**Comment by hsogo** [comment]
I run keyboardNEW.py demo on Windows10, MacOS 10.11.6 and Ubuntus 18.04 (version of PsychoPy is 3.2.4). The reuslt was as follows.  In this table, "o" means "numlock works" and "x" means "numlock doesn't work".  The column entitled "numpad 2 key" shows obtained key name if numlock doesn't work.

| OS | event | PTB | numpad 2 key|
|----|:--:|:--:|----|
|win|o|x|down|
|mac|x|x|num_2|
|ubuntu|o|x|num_2|

Mac and Ubuntu returns "num_2" on PTB keyboard when numpad 2 key is pressed.  So, applying fix in my previous post, behavior of PTB keyboard coincide among these OSs.  I think it is worth applying the fix. What do you think?

By the way, in Windows, we can know status of numlock by following code.  It takes about 0.0016 ms in average on my core i7-6700 PC.

```
import win32api
import win32con
win32api.GetKeyState(win32con.VK_NUMLOCK)
```

In Ubuntu 18.04, we can know the status by following code (root privilege is required). It takes 0.0020 ms in average on corei7-2600k PC.

```
import os
import struct
import fcntl

DEVICE = '/dev/console'
_KDGETLED = 0x4B31
num_lock = 0x02

fd = os.open(DEVICE, os.O_WRONLY)
bytes = struct.pack('I', 0)
bytes = fcntl.ioctl(fd, _KDGETLED, bytes)
[leds_state] = struct.unpack('I', bytes)
status = leds_state & num_lock != 0
```

I hoped that this also worked on Mac, but it didn't.

**Comment by Joe-Hilgard** [comment]
I'm encountering this issue now. It's unfortunate that both num_5 and num_6 are actually mapped to the same key: in keyboard.py both keys 101 and 102 are named 'right'.

**Comment by hsogo** [comment]
Thank you for reporting that. I have the same problem (both of num_5 and num_6 return 'right').  I heard at a local meting that several people have experienced the same issue.

@peircej I think it is better to return "num_5", "num_6", ... than to return "right".  Can I send a pull request to change key mappings as follows for Windows?

```
    97: 'num_1', 98: 'num_2', 99: 'num_3',
    100: 'num_4', 101: 'num_5', 102: 'num_6', 103: 'num_7',
    104: 'num_8', 105: 'num_9', 96: 'num_0',
```

**Comment by peircej** [comment]
Yes, let's do that

**Comment by peircej** [comment]
I've found another few fixes to make too, so we could push out another super-quick bugfix today/tomorrow?

**Comment by hsogo** [comment]
I haven't found any bug to be fixed right now.

**Comment by peircej** [comment]
Fixed in GH-2812
