### ISSUE TITLE
importing readline in backend_soundevice.py crashes visual.Window instance

### ISSUE THREAD

**Issue by heuristicwondering** [psychopy/psychopy#2662]
Hi! I was having trouble creating instances of MovieStim3 when there was sound in the videos. It would crash the previously created window instance. I tracked this down to an import call to the readline module (line 21 in backend_sounddevice.py). It doesn't seem like readline is used anywhere and commenting it out allowed me to load and play movies using MovieStim3.

Below is a MWE of this behavior:
```
from psychopy import visual
from psychopy import monitors

screensize = (1280, 1024)
monitor = monitors.Monitor('subjectMonitor')
vidFullFile = '/path/2/file/my-movie.avi'

win = visual.Window(screensize, fullscr=True, screen=1,
                                allowGUI=False, allowStencil=False,
                                monitor=monitor,
                                color=[0, 0, 0], colorSpace='rgb',
                                blendMode='avg', useFBO=True)

movie = visual.MovieStim3(win=win, name='test',
                            noAudio = False, filename = vidFullFile, units='pix',
                            color='black', colorSpace='rgb',
                            ori=0, pos=(0, 0), opacity=1)
```

**This won't work unless `import readline` is commented out and then it will work fine.**

Can anyone confirm that this is an issue and why readline might be crashing things? Thanks!

**Comment by hoechenberger** [comment]
Importing `readline` is just done to work around a certain issue, see https://github.com/psychopy/psychopy/issues/2230

Could you try importing `psychopy.sound` as the very first import, i.e., before `psychopy.visual`? Even if you don't use the `sound` module :)

**Comment by heuristicwondering** [comment]
Oh yes, that worked perfectly. Thank you so much for the work around!

**Comment by peircej** [comment]
OK. For 2020.1.1 release I'm going to try putting `import readline` right into the `psychopy.__init__` in the hope this will be fixed once and for all (even though it might confuse some people and code-linters seeing it there!). I'll close this issue for now but we can reopen if it doesn't fix it.
