### ISSUE TITLE
"openexp" module

### ISSUE THREAD

**Issue by aligh94** [psychopy/psychopy#2667]
Hi everyone, I want to use "openexp" module in psychopy but I couldn't add it in psychopy, can anyone help me?
thanks

**Comment by peircej** [comment]
Issues on github are for us to track bugs etc. As I said when you asked on the forum, openexp is not a part of PsychoPy and not something we can support you with. You need to get get help from the person that wrote the script for you. Or, if you aren't sure yourself what openexp is for then you could try commenting out that code (maybe it's providing features that you don't even need).

**Comment by aligh94** [comment]
> Issues on github are for us to track bugs etc. As I said when you asked on the forum, openexp is not a part of PsychoPy and not something we can support you with. You need to get get help from the person that wrote the script for you. Or, if you aren't sure yourself what openexp is for then you could try commenting out that code (maybe it's providing features that you don't even need).

thank you so much, unfortunetely I don't have access to the one who has written the script. I need to add a "libet clock" to my task in psychopy; I found some code from the web in which "openexp" module is used.

**Comment by peircej** [comment]
Well I suggest you read (and possibly post) the code where the openexp lib gets used and see what it's actually doing. Nobody can help from the little information you're supplying so far
