### ISSUE TITLE
"No module named PyQt5.sip" with a fresh 3.2.4 Psychopy installation on Windows 10

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#2668]
Hi,
I've installed Psychopy 3.2.4 recently (Windows installer) but I can't run any Builder procedure because I get "No module named PyQt5.sip" error.
![image](https://user-images.githubusercontent.com/8452354/68092045-62044d80-fe87-11e9-9535-8c898aacf52b.png)

I can still run procedures that were coded, not built with Builder because then PyQt5 is not imported.
I'd be happy to give any additional information you think is necessary to resolve this issue.

**Comment by mmagnuski** [comment]
Importing `PyQt5` from shell:
```
>>> import PyQt5
>>> from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'

>>> from PyQt5 import QtGui
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by peircej** [comment]
Oh, that's weird. Which version of 3.2.4 did you install?

**Comment by mmagnuski** [comment]
The one recommended on the "download" page: 64 bit with Python 3.6
But I checked about 20 other windows machines today (I had a class using Psychopy3 :) ) and it works well. I will try reinstalling Psychopy on my laptop. I might have had Psychopy2 and after installing Psychopy3 unistalled Psychopy2, but I don't know why/whether it would make any difference.

**Comment by peircej** [comment]
OK. I've checked and can't replicate so let me know if you get any further info. cheers

**Comment by hoechenberger** [comment]
Closing for now, but feel free to reopen.

**Comment by mmagnuski** [comment]
I am still having this issue after psychopy reinstall. I will try investigating some more.

**Comment by mmagnuski** [comment]
One of my students experienced this lately on a windows machine in classroom. I still don't know why it's the case, but the student claimed that on previous classes the same machine and psychopy version worked well.

**Comment by waa8128** [comment]
i meet the same question in my windows 10. The psychopy worked several months ago， but it made the error now. 
```

Generating PsychoPy script...
####### Running: C:\Users\THINK\Desktop\e3_lastrun.py #######
Traceback (most recent call last):
  File "C:\Users\THINK\Desktop\\e3_lastrun.py", line 18, in <module>
    from psychopy import sound, gui, visual, core, data, event, logging, clock
  File "C:\Users\THINK\AppData\Roaming\Python\Python36\site-packages\psychopy\gui\__init__.py", line 45, in <module>
    from .qtgui import *
  File "C:\Users\THINK\AppData\Roaming\Python\Python36\site-packages\psychopy\gui\qtgui.py", line 35, in <module>
    from PyQt5 import QtWidgets
ModuleNotFoundError: No module named 'PyQt5.sip'
```

and in the shell

```
import PyQt5
from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
from PyQt5 import QtGui
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
```
