### ISSUE TITLE
ioHub Server not starting when specifying a config file

### ISSUE THREAD

**Issue by psilonpneuma** [psychopy/psychopy#2684]
Hi,
I have issues setting up a simple eyetracker experiment as the ioHub Server won't start. I am working on Windows 7, 64bit, with the latest Standalone version of Psychopy 3 and Python 3.6. 
When running the command:

`io=launchHubServer(**config_file)`
(where `config_file` is a python dictionary with the config specifications)

the program crashes with the following error:

```
Traceback (most recent call last):
  File "C:\Users\lscpuser\Desktop\manybabies1-psychopy-master\manybabies1_et.py", line 216, in <module>
    io=launchHubServer(**io_config)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\iohub\lazy_import.py", line 278, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\iohub\client\connect.py", line 262, in launchHubServer
    return ioHubConnection(iohub_config)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\iohub\client\__init__.py", line 295, in __init__
    raise RuntimeError('Error starting ioHub server')
RuntimeError: Error starting ioHub server
ioHub Server Process Completed With Code:  1
```
I have tried to print `self.iohub_status`, which simply returns `ioHub startup failed.` with no further text: this does not correspond to any line within the _init_.py file, so I am not sure of where the error might be coming from.

On the other hand, this does not happen when instead the command is called without any keyword argument, as in:

`io=launchHubServer()`

But in this way, the configuration file is the default one, and thus I am unable to run my experiment:

`{'monitor_devices': [{'Display': {'override_using_psycho_settings': False}}, {'Experiment': {}}, {'Keyboard': {}}, {'Mouse': {}}], 'global_event_buffer': 2048, 'udp_port': 9034, 'windows_msgpump_interval': 0.001, 'data_store': {'enable': False, 'filename': 'events', 'multiple_experiments': False, 'flush_interval': 32}, 'log_raw_kb_mouse_events': False, 'coverage_env_var': 'None'}`

Any idea of how I could solve this?
Many thanks in advance.

**Comment by hoechenberger** [comment]
Which values, exactly, do you pass to `launchHubServer()`?

**Comment by hoechenberger** [comment]
Friendly ping to @psilonpneuma

**Comment by psilonpneuma** [comment]
I have tried several things: the ultimate goal is to read a yaml file into a python dictionary. But I get an error even just writing the dictionary myself with one simple entry:

```
tracker_config = {'eyetracker.hw.gazepoint.gp3.EyeTracker':
    {'name': 'tracker', 'device_timer': {'interval': 0.005}}}
io = launchHubServer(**tracker_config)
```

**Comment by peircej** [comment]
@isolver Would you be free to help debug this issue?

**Comment by isolver** [comment]
@psilonpneuma, do you have the gazepoint 3 connected and the Gazepoint Control app running in the background before starting your experiment? The example you give, which is from demos/coder/iohub/eyetracking/simple.py, seems to run fine for me (I get the GP3 calibration and then 1 GC trial). I'm testing using the latest PsychoPy3 source. Thanks.

**Comment by psilonpneuma** [comment]
I figured the Gazepoint Control app was not running properly (probably blocked automatically by my antivirus). Issue solved thanks!
