### ISSUE TITLE
Random key assignment- Psychopy

### ISSUE THREAD

**Issue by student1234567891** [psychopy/psychopy#2689]
I want to use different set of keys to record responses. I am doing an AMP and want different keys determined randomly by computer to tell the participant to use these keys after the presentation of "mask" for each individual trial.
I am using Psychopy 1.85.2

**Comment by dvbridges** [comment]
Hi @student1234567891 , the GitHub repository is for software related issues, rather than questions about building experiments. You can post question on the [PsychoPy Discourse forum](https://discourse.psychopy.org/).
