### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by benbao9749** [psychopy/psychopy#2703]
Hi, I just downloaded the 3.2.4 standalone version on my window 10. 
I couldn't start the installation process. This error message popped up. 
![image](https://user-images.githubusercontent.com/56982840/70002974-b571c600-152f-11ea-927c-ceeae35a410c.png)

How do I fix this?

**Comment by peircej** [comment]
I've never seen that before. Are you sure the file fully downloaded? Did you get the 64 bit version on a 32 bit Windows or vice versa? Is there anything else "unusual" about your computer (that might explain why most users aren't having a problem)?

**Comment by benbao9749** [comment]
I have solved it. I downloaded the 64 bit version. Turns out, I can't open it up because it was in disk C:, once I moved it to disk D:, it worked normally. I think it's some sort of authorization issue.
