### ISSUE TITLE
pyglet testing on Travis

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2707]
Currently we test all supported Py3 versions with both pyglet 1.3 and 1.4. I'm wondering if we could reduce the number of pyglet 1.3 tests, e.g. only test on Python 3.6 (which is what's included in the standalone build) to save CI resources? WDYT?

**Comment by peircej** [comment]
I'm fine with that. From psychopy 3.3 onwards I'll ship with pyglet 1.4 so that will become the new default. I think I'd vote for testing pyglet 1.3 for backwards compatibility for a while, maybe on the py2.7 installation (essentially now a legacy install)

**Comment by hoechenberger** [comment]
Ok cool! :)
