### ISSUE TITLE
Could I recording subjects' face expression by camera?

### ISSUE THREAD

**Issue by waa8128** [psychopy/psychopy#2713]
I'd like to recording the face expression of subjects by opencv,the code like:
`
from scipy.spatial import distance as dist
from imutils.video import FileVideoStream
from imutils.video import VideoStream
from imutils import face_utils
import numpy as np
import argparse
import imutils
import time
import dlib
import cv2
 
 
def eye_aspect_ratio(eye):
    A = dist.euclidean(eye[1], eye[5])
    B = dist.euclidean(eye[2], eye[4])
    C = dist.euclidean(eye[0], eye[3])
    ear = (A + B) / (2.0 * C)
    return ear

EYE_AR_THRESH = 0.18
EYE_AR_CONSEC_FRAMES = 1

COUNTER = 0
TOTAL = 0

print("[INFO] loading facial landmark predictor...")
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')
 
(lStart, lEnd) = face_utils.FACIAL_LANDMARKS_IDXS["left_eye"]
(rStart, rEnd) = face_utils.FACIAL_LANDMARKS_IDXS["right_eye"]
 
cap = cv2.VideoCapture(0)
t0 = 0
while True:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    rects = detector(gray, 0)
    # t0 = 0
    for rect in rects:
        shape = predictor(gray, rect)
        shape = face_utils.shape_to_np(shape)
        leftEye = shape[lStart:lEnd]
        rightEye = shape[rStart:rEnd]
        leftEAR = eye_aspect_ratio(leftEye)
        rightEAR = eye_aspect_ratio(rightEye)
        ear = (leftEAR + rightEAR) / 2.0
 
        leftEyeHull = cv2.convexHull(leftEye)
        rightEyeHull = cv2.convexHull(rightEye)
        cv2.drawContours(frame, [leftEyeHull], -1, (0, 255, 0), 1)
        cv2.drawContours(frame, [rightEyeHull], -1, (0, 255, 0), 1)

        left = rect.left()
        top = rect.top()
        right = rect.right()
        bottom = rect.bottom()
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 255, 0), 3)    
        
        if ear < EYE_AR_THRESH:
            COUNTER += 1
        else:
            if COUNTER >= EYE_AR_CONSEC_FRAMES:
                TOTAL += 1
                tick = time.time()
                print(tick-t0)
                t0 = tick
            COUNTER = 0
        
        for (x, y) in shape:
            cv2.circle(frame, (x, y), 1, (0, 0, 255), -1)
         
        cv2.putText(frame, "COUNTER: {}".format(COUNTER), (150, 30),
        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)    
        cv2.putText(frame, "Blinks: {}".format(TOTAL), (10, 30),
        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        cv2.putText(frame, "EAR: {:.2f}".format(ear), (300, 30),
        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
 
    cv2.imshow("Frame", frame)
    # print(len(rects))   
    # if the `q` key was pressed, break from the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()         

`
Could use opencv and psychopy at same time?

**Comment by m-macaskill** [comment]
This sort of support request really belongs on the PsychoPy discussion forum at https://discourse.psychopy.org. Github is really for development aspects of the project. But in essence, yes, you can use OpenCV and PsychoPy at the same time, but you will want to draw the output into the PsychoPy window. See the example here: https://www.psychopy.org/recipes/webcam.html

**Comment by waa8128** [comment]
ok, i'm sorry for issues in git and thanks for your answer.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael MacAskill"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 下午3:02
收件人:&nbsp;"psychopy/psychopy"<psychopy@noreply.github.com&gt;;
抄送:&nbsp;""<253012016@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [psychopy/psychopy] Could I recording subjects' face expression by camera? (#2713)




This sort of support request really belongs on the PsychoPy discussion forum at https://discourse.psychopy.org. Github is really for development aspects of the project. But in essence, yes, you can use OpenCV and PsychoPy at the same time, but you will want to draw the output into the PsychoPy window. See the example here: https://www.psychopy.org/recipes/webcam.html
