### ISSUE TITLE
[bug] visual.Rect component does not recalculate vertices after change of size, width and height properties

### ISSUE THREAD

**Issue by PanBartosz** [psychopy/psychopy#2714]
Which results in inability to update width and height of Rect during main loop. I have noticed that Rect class was updated (commit from 14 october), but this update made it unusable. Fix is simple, update vertices after setting size and set self._needVertexUpdate to True to enable redrawing updated shape.

**Comment by PanBartosz** [comment]
This bug was introduced in 3.2.4 update, 3.2.3 works fine.

**Comment by hoechenberger** [comment]
> Fix is simple, update vertices after setting size and set self._needVertexUpdate to True to enable redrawing updated shape.

Do you fancy making a PR with a fix?
