### ISSUE TITLE
[bug] TextStim is broken in pyglet >= 1.4.0 on Linux (but possible on other platforms too)

### ISSUE THREAD

**Issue by PanBartosz** [psychopy/psychopy#2715]
PsychoPy renders text incorrectly, for example "norm" position of (0,0), which should indicate center of the screen is rendered as something like (-1,0) (left  border of the screen). The text is also larger than it should be. This scaling and possitioning issue applies only to TextStim (and components which internally use it, i.e. RatingScale). Other stimuli (shapes etc.) seem to be unaffected by this bug. Downgrading pyglet to 1.3.3 solves this issue.

**Comment by hoechenberger** [comment]
Are you using the latest development version from `master`? If not, it's not expected to work :)

**Comment by peircej** [comment]
Yes, this is fixed in master and will be part of the 3.3 release (soon)

**Comment by kupiqu** [comment]
> Yes, this is fixed in master and will be part of the 3.3 release (soon)

Got bitten by this. Looking forward to version 3.3

**Comment by PanBartosz** [comment]
This issue is present on 2020.2.4 version of PsychoPy (linux). This time downgrading pyglet does not work (maybe the root of the problem is somewhere else?).

**Comment by peircej** [comment]
I can't replicate that. When I run this (with pyglet 1.4.10, PsychoPy 2020.2.4 on Win10) I get the text in screen center as expected. Could you send the minimal example that is not working?
``` python
from psychopy import visual, core

import pyglet
print(pyglet.version)

win = visual.Window(units='norm')

txt = visual.TextStim(win, 'test')
txt.draw()
win.flip()
core.wait(2)
```
