### ISSUE TITLE
polygon_5 is can‘t be used ？？

### ISSUE THREAD

**Issue by iuype** [psychopy/psychopy#2723]
“That name is in used” is what the Builder told me。。

But I didn’t use the name in source code 。

It is bug on checking existing name ？

**Comment by peircej** [comment]
Hard to know without seeing your experiment. Maybe you previously had a component called `polygon_5` but removed it and PsychoPy failed to update its list of permitted names? If you close and reopen the experiment is it now allowed?

**Comment by iuype** [comment]
Thank you. 
It's my carelessness.
now, it works very well.
