### ISSUE TITLE
platform.dist removed in Python 3.8

### ISSUE THREAD

**Issue by cbrnr** [psychopy/psychopy#2733]
The attribute `platform.dist` has been deprecated since Python 3.5 and has been removed in Python 3.8 (https://docs.python.org/3.5/library/platform.html#platform.dist). This is used in [`sendUsageStats`](https://github.com/psychopy/psychopy/blob/master/psychopy/app/connections/sendusage.py#L42), [`updates.py`](https://github.com/psychopy/psychopy/blob/master/psychopy/app/connections/updates.py#L623), and [`testSoundLatency.py`](https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/hardware/testSoundLatency.py#L99).

I don't know if this functionality can be replaced by something from the standard lib (if some loss of information is acceptable), otherwise this means yet another dependency such as https://pypi.org/project/distro/.

**Comment by hoechenberger** [comment]
We're already using `distro` in some places, would be good to extend this, sure!

https://github.com/psychopy/psychopy/pull/2690/commits/aaf4fb5234cdeff0ecc997f698eb8c686124429a

**Comment by hoechenberger** [comment]
Feel like making a PR for this, @cbrnr?

**Comment by cbrnr** [comment]
Sure, will do!

**Comment by hoechenberger** [comment]
Great!
