### ISSUE TITLE
Check number of available screens while initialising gui.Dlg

### ISSUE THREAD

**Issue by colinquirk** [psychopy/psychopy#2741]
Using Windows 7 and psychopy3-3.2.4 and window type=pyglet, I'm finding that dialog boxes are not correctly centering when gui.dlg.screen = 1 and there is only 1 available monitor. For a small dialog box, this resulted in the dialog being completely off the screen and unable to be interacted with. This issue does not appear on os x for me, dialog boxes are still centered. Furthermore, on both os x and windows, the visual.Window seems to be created and displayed normally.

Changing screen to 0 fixes the issue, but the code then is no longer correct when used on a different, 2 monitor set up. This is a small issue obviously, and I'm not even sure that the behavior I was relying on was ever purposefully designed, but it would be nice if it worked. I confirmed it worked on version 1.90.3. The following repex is enough to see the issue for me:

```
psychopy.gui.Dlg(screen=0).show()
psychopy.gui.Dlg(screen=1).show()
```

**Comment by peircej** [comment]
We weren't doing anything within PsychoPy to assert this so it was presumably an artefact of the underlying WX/Qt implementations, which may have changed. But I agree that it would be good to do this (in both widget engines).

It should be easy enough to do:
- during `Dlg.__init__` we should detect the number of screens. For WX that can be done with this https://wxpython.org/Phoenix/docs/html/wx.Display.html and I'm sure there's somethign similar for PyQt
- set `screen = min(screen, nScreens-1)`

**Comment by peircej** [comment]
The equivalent call in PyQt is uses the `Application.screens()` method:
https://doc.qt.io/qt-5/qguiapplication.html#screens

**Comment by colinquirk** [comment]
> We weren't doing anything within PsychoPy to assert this so it was presumably an artifact of the underlying WX/Qt implementations, which may have changed.

I figured as much, I will try to take a crack at fixing this!

**Comment by peircej** [comment]
Just touching base on this - it was done, right? At least in Qt. I thnk we don't care about wx anyway because it currently has a threading clash with pyglet that makes it useless!

**Comment by colinquirk** [comment]
Then yup, I think you are free to close!

**Comment by peircej** [comment]
Brilliant! Thanks for your help!
