### ISSUE TITLE
Should we vendor javascripthon?

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2757]
I had to patch javascripthon to get it to work on Py3.8, see upstream PR: https://github.com/metapensiero/metapensiero.pj/pull/50

(conda-forge packages have this patch applied automatically)

Since the project seems rather inactive, I'm wondering whether it would make sense to vendor the patched version, or to do some monkey-patching...

**Comment by hoechenberger** [comment]
Also, I'm quite concerned about relying on this package anyway: Python 3.9 is going to be releases in October, which is probably going to cause new issues. The project seems pretty much dead to me.

**Comment by peircej** [comment]
I'm Ok with us taking over a copy and potentially updating ourselves if that's needed. @apitiot had looked at quite a few options I think and this was the one that did the job (whereas lots of packages claim to) so I think it will be hard to get by without it

**Comment by azazel75** [comment]
Just inform you guys that I had some time to spend on Javascrypthon and I've updated it to Python 3.9, if still useful for you can you please try it out the unrelased master branch? 
I've also removed the dependency on macropy
Also, I saw your preprocessor for the math functions, would you like to have it integrated with Javascripthon?

**Comment by peircej** [comment]
OK, fantastic, thanks for getting in touch @azazel75 :-) 

Great to hear the project still has support. @apitiot and @tpronk in particular have done some work extending your (excellent) work for our particular needs which, yes, often involves maths and sometimes numpy. If you were interested in extending javascripthon itself with some of these functions that would take some of the code off our plate which would be nice but I guess it would need to be coordinated.

I'll email you (and I'll close this issue)
