### ISSUE TITLE
Cedrus device not found on Psychopy3

### ISSUE THREAD

**Issue by Dee73** [psychopy/psychopy#2770]
There seems to be a problem with using a cedrus device on Psychopy3.

 I created a very simple experiment with a cedrus device in the first routine and ran it on both Psychpy2 (there was no problem, it ran properly) and then again on psychpy3 and it doesn't run and it has an error "Could not find cedrus device".

This issue repeated on several computers.

**Comment by peircej** [comment]
This is actually fixed in Release 2020.1
It's a long-standing issue to do with the fact that the cedrus boxes complain if you try to initialise them more than once.
