### ISSUE TITLE
Mac HID devices not found (due to privacy settings)

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2787]
On Catalina mac now complains about our use of the PsychHID connection to the USB keyboards.
The user needs to add PsychoPy to the accepted devices in SysPrefs?Privacy

To make this easier/clearer we need to try and make it happen from the app (before an experiment is launched). That way I think MacOS will bring up an "Allow access"? dialog automatically now, but if not we can, at least, provide a warning having detected that the USB keyboard couldn't be reached

**Comment by peircej** [comment]
No, unfortunately that doesn't work. We can detect that the error occurred but it doesn't bring up the dialog to add permissions

**Comment by peircej** [comment]
I think we need to add a warning and a event.getKeys() fallback for Mac :-(

**Comment by peircej** [comment]
Mario has announced that Catalina is simply not supported

**Comment by hoechenberger** [comment]
> The user needs to add PsychoPy to the accepted devices in SysPrefs?Privacy

So, this solution does not work then?

**Comment by hoechenberger** [comment]
https://github.com/atheriel/accessibility looks interesting, but the project seems to be dead.

**Comment by peircej** [comment]
I've found a pretty doable solution actually. See #2800 
I couldn't make it work to generate the pop-up (I agree I've seen that but I can't work out when it does/doesn't occur). But I have found a way to bring up the necessary setting in the SysPrefs dialog and the user can then drag in the necessary app bundle

**Comment by hoechenberger** [comment]
Great!

**Comment by isolver** [comment]
This would be great for iohub ease of use as well on macOS.
