### ISSUE TITLE
Selecting preferences on windows 10 crashes psychopy

### ISSUE THREAD

**Issue by denisfitz57** [psychopy/psychopy#2794]
After building psychopy via Anaconda per instructions, upon opening psychopy and selecting Preferences from the File menu, psychopy crashes, with Python has stopped working window popping up.

**Comment by denisfitz57** [comment]
Also happens with StandalonePsychoPy3-3.2.4-win64.exe

**Comment by peircej** [comment]
This doesn't happen *in general*. My guess is that you've got an error in your userPrefs.cfg or appdata.cfg (PsychoPy isn't very good at validating the values you put in to prefs especially). Could you grab those files and upload them here for me to take a look? Maybe I can build better resilience.

Then, to get working again I think deleting/moving the files and restarting PsychoPy should do it

**Comment by peircej** [comment]
I'm closing this for now but we can reopen if you can fetch the files

**Comment by denisfitz57** [comment]
The files are attached.  After removing them, the program crashed shortly after the splash screen appeared.

**Comment by peircej** [comment]
Looks like the attachements got wiped from email. Could you click on the link to view in github and drop them ont he box where it says "attach files", although if deleting them didn't fix the issue then there' something more seriously wrong on your machine.

And there was no error message when it crashed (either on prefs or during launch?) . Maybe you could follow the other advice of trying to launch from the command line in case an error is being swallowed up. 
"C:\Program Files\PsychoPy3\python.exe" -m psychopy.app.psychopyApp

**Comment by denisfitz57** [comment]
Added txt file extension because cfg not accepted.


[userPrefs.cfg.txt](https://github.com/psychopy/psychopy/files/4171495/userPrefs.cfg.txt)
[appData.cfg.txt](https://github.com/psychopy/psychopy/files/4171496/appData.cfg.txt)

**Comment by denisfitz57** [comment]
![Psychpy](https://user-images.githubusercontent.com/1459124/74042050-711a0080-498c-11ea-974e-f4560111d9d2.png)
This is what I see after running from the command line.

**Comment by peircej** [comment]
Thanks - could you try python.exe instead of pythonw.exe?

**Comment by denisfitz57** [comment]
![Psychpy](https://user-images.githubusercontent.com/1459124/74044038-0965b480-4990-11ea-8cda-3534d4e00d04.png)

**Comment by peircej** [comment]
Those errors in red are all to do with not getting the command quite right. On powershell (rather than cmd.exe) if you give the name python.exe using a string like "C:\Program Files...." then you have to preced it with an & to indicate to powershell that's what you're doing. Then you need to *either* use -m psychopy.app.psychopyapp *or* the full path to the file.

So could you paste in *exactly* this (copy it and then right-click in the shell to paste):
```
& "C:\Program Files\PsychoPy3\python.exe" "C:\Program Files\PsychoPy3\Lib\site-packages\psychopy\app\psychopyApp.py"
```

**Comment by denisfitz57** [comment]
Thanks for your patience! To be clear, this is with the cfg files removed.

![Psychpy](https://user-images.githubusercontent.com/1459124/74045435-5ba7d500-4992-11ea-832f-d3328f2d47f2.png)

**Comment by peircej** [comment]
OK, and no sign of any error being sent to the terminal either then. I'm afraid I'm quite mystified. I'm particularly puzzled about what could be different on your machine than any other - most people on Win10 are running 3.2.4 Standalone with no problems :-/

**Comment by denisfitz57** [comment]
Your efforts are appreciated, thanks!

Denis
