### ISSUE TITLE
Inconsistent parameter name in docs?

### ISSUE THREAD

**Issue by luketudge** [psychopy/psychopy#2797]
The docstring for `importConditions()` refers to a `trialTypes` argument to `TrialHandler()` ([here](https://github.com/psychopy/psychopy/blob/c12258260fdbbecf89fa78df8d78b39a67e990d0/psychopy/data/utils.py#L174)). But this argument is actually called `trialList` (see [here](https://github.com/psychopy/psychopy/blob/master/psychopy/data/trial.py#L60)).

**Comment by peircej** [comment]
True. You could pull-request that change to take credit?

**Comment by luketudge** [comment]
Thanks! Just wanted to check I had understood this right. PR is #2798.
