### ISSUE TITLE
Working directory issues with 2020.1.1 (most likely related to the new run window)

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#2816]
See https://discourse.psychopy.org/t/working-directory-change-with-2020-1-and-later/11143 and https://discourse.psychopy.org/t/both-the-stim3d-py-and-trialhandler-py-programs-with-psychopy-2020-1-1-do-not-run-properly/11201

At least on Mac (have not tested on Windows), since upgrading to 2020.1.1, if you run a script, the working directory is set to /Applications/PsychoPy3.app/Contents/Resources, rather than the directory that contains the script. This completely breaks any script that uses relative paths for relevant files expecting the working directory to be the script's directory. This includes some of the demos (see second link above) and my PyHab project.

In the short run you can just add the following to the top of every file where it matters:

```
import os
os.chdir(os.path.dirname(os.path.realpath(__file__)))
```

but this is basically a kludge and bad for backwards-compatibility. Does it need to be this way or can we get the new running window to use the script's directory as the working directory by default?

**Comment by peircej** [comment]
I'm sure there's no need for it to be this way. Looks like the code copied over to Runner class 

https://github.com/psychopy/psychopy/blob/3e8adf5debf381169a8598e799dbd0b71243bfa7/psychopy/app/runner/scriptProcess.py#L91

came from Builder 

https://github.com/psychopy/psychopy/blob/7d6b1a878f124999f986828e612bc6b36b68963c/psychopy/app/builder/builder.py#L2198

Now, Builder doesn't strictly need to update the cwd because your solution (set cwd to __file__) is done automatically in the Builder-output scripts, so it was probably left out but for hand-written scripts I definitely think it's amore expected thing to have the cwd automatically set to the script folder, so I think it would be cool to update scriptProcess as above to point the process cwd to the necessary location. Do you want to submit a PR on that or shall I?

**Comment by jfkominsky** [comment]
I'm traveling, so probably faster if you do it, but if I get a moment and
you haven't already taken care of it I'll take a crack at it.

**Comment by jfkominsky** [comment]
#2819 Submitted. NOTE: I don't have access to a Windows machine for a couple days to test it on Windows, and I highly recommend testing it. I couldn't just create a path object because the cwd argument of popen does not accept path objects in windows prior to Python 3.7, according to docs. It has to be a string. So, I had to manually get the last / or \ from the filename, in the conditionals that are already in the RunFile function for dealing with Windows-specific stuff.

**Comment by mdcutone** [comment]
The coder UI stuff I've been working on has a few options for changing the cwd through the menus. There is an option to change the CWD to the location of the currently opened file.

**Comment by jfkominsky** [comment]
Three questions then:

1. Can you make the default having the file location be the CWD? 
2. More broadly, is there any upside to _not_ having the file location be the CWD? The option seems reasonable to me, but from the sound of things this is literally an accidentally introduced bug, not a beneficial behavior. If it's something that just never has any benefit, making it an option seems relatively pointless. Now, an option that just let you set the CWD to be whatever you wanted, but defaulted to the file location, that I could see uses for.
3. If we do stick with making it an option, will that be part of the next planned update, and if not can this function as a temporary fix?

**Comment by peircej** [comment]
Yes, first step will be to make sure it always uses __init__ folder and then we'll work out whether it's worth making that an option. I agree that it might not be worth it - I don't recall anyone asking for that as an option in the past.

**Comment by peircej** [comment]
By the way Jonathan, above you fetched the folder with `os.path.dirname(__file__)` or these days I would often use a pathlib solution: `Path(__file__).parent` but I noticed you used a manual separation of the directory in the pull request you made. It doesn't really matter but I wonder if that would be less robust than the methods above. Was there a reason to use that?

**Comment by jfkominsky** [comment]
Didn't know about pathlib, mostly. There's a note in the docs that popen's cwd argument doesn't take path objects on Windows prior to 3.7, but there's no reason I can see that pathlib will differ from my current solution on that front. I can revise that.

**Comment by jfkominsky** [comment]
Updated PR, and I've now tested it on a Windows machine with the standalone, which uses Python 3.6, and confirmed that it works. Should be good to go.

**Comment by mdcutone** [comment]
I think we should look at how RStudio/Spyder/MATLAB handle the CWD and emulate that. Most users are probably familiar with those environments.

**Comment by jfkominsky** [comment]
RStudio handles it very badly, in my opinion, requiring you to manually set it every time and defaulting to the home folder.

I would say there's no harm in having it default to the file's location, and the option to change that default to an arbitrary path probably has some uses, but that can also be achieved in the code itself. Given that this is a feature that will only really matter to relatively code-saavy users, my main concern is that it defaults to what I certainly find the most intuitive behavior (the directory of the script file being run), and I'm neutral on whether we have a GUI option to change it versus just letting people use os.chdir in their code.

**Comment by mdcutone** [comment]
If we go that route, that can be done easily by having CWD change in the editor tab changing event.

**Comment by peircej** [comment]
At present there's no need for the editor itself to change dir - it can be done purely in the subprocess and the editor stays fixed

**Comment by mdcutone** [comment]
That's actually a much better idea.

**Comment by jfkominsky** [comment]
I think we've been talking past each other - that's all this change is targeted to. It only affects the working directory of the subprocess created with popen when the "run" button is hit. The issue is that currently, that subprocess is locked to the app resources folder unless you change it within the subprocess itself. My pull request reverts to the earlier behavior where the subprocess uses the file's location as its working directory, but affects nothing else in PsychoPy.
