### ISSUE TITLE
Error when uploading participant's results

### ISSUE THREAD

**Issue by gcauli** [psychopy/psychopy#2821]
Hi everyone,

I'm having troubles running my experiment on Pavlovia properly.

I'm working in builder mode and running a priming experiment with Russian verbs (i.e. written in Cyrillic), so after a few screens with instructions &co I have a loop with the test, for which I imported an xls file containing two columns (target, prime). After the 2nd item for every repeat appears, a response key should get saved with the answer provided from the participant.

Now, if I run the experiment on my laptop, I get a weird csv table in which the list of target-prime pairs doesn't appear. The results can be retrieved by reading the log files, but this isn't the best way to do it I guess.

When I try and run it on Pavlovia no data gets saved.
I checked the experiment steps and created online experiments multiple times, I honestly don't know what to do anymore.

I'm doing this experiment for my master thesis and I'm kinda desperate at this point..
Thanks in advance! 

Link to the repository: https://gitlab.pavlovia.org/gcauli/new_primingexp

These are the error boxes I got after I completed an online session.

<img width="1440" alt="Screenshot 2020-03-02 at 14 39 03" src="https://user-images.githubusercontent.com/61697174/75683614-c699b280-5c97-11ea-82da-ff44aea029f1.png">

<img width="1440" alt="Screenshot 2020-03-02 at 14 39 44" src="https://user-images.githubusercontent.com/61697174/75683672-e204bd80-5c97-11ea-9f14-8ad9cc01ac6b.png">

**Comment by gcauli** [comment]
For future reference:
I saved the project on a complete new path, without redundancies with previous versions.
The data have been saved properly by editing the trials loop.
At first I had one single routine with two different text fields, one for the target and one for the prime:

<img width="1078" alt="Screenshot 2020-03-02 at 20 20 31" src="https://user-images.githubusercontent.com/61697174/75709596-4721d880-5cc3-11ea-8267-ba9e93fadaba.png">

In the new functioning version every text field got its own routine:

<img width="1080" alt="Screenshot 2020-03-02 at 20 19 32" src="https://user-images.githubusercontent.com/61697174/75709540-248fbf80-5cc3-11ea-9168-54b6cf1110e3.png">

**Comment by peircej** [comment]
I'm not sure why that would make a difference :-/ but glad you got it working
