### ISSUE TITLE
Add a separator argument to data.importConditions()

### ISSUE THREAD

**Issue by AnnaTruzzi** [psychopy/psychopy#2824]
When importing a csv file the column separator may be either a comma or a semi colon depending on the system settings (different regions have different settings). 
Therefore it would be nice to have the possibility to set the separator by passing that argument to the pd.read_csv function within data.importConditions(). Would you be interested in accepting a pull request for this change?

**Comment by peircej** [comment]
Sounds good Anna, yes. Lovely to see someone going from workshop attendee to contributor in a space of hours! Long live open-source! ;-)

I wonder if this is something we should try to do automatically (try an import with , and then try ; if it fails?). We could call that sep='auto' as a default and then allow sep=',' and sep=';' as other options. It adds a bit more code but might be good for the average user, who wouldn't know to go looking for such things? For instance, in the Builder interface I'd prefer not to have to add this as a dialog entry.

thanks

**Comment by AnnaTruzzi** [comment]
ahahah! You got me :)  Long live open-source!

Sure that sounds brilliant, I'll work on that and come back to you ASAP then. 
Thank you!

**Comment by peircej** [comment]
Great! Let me know if you want any help with it. If you could write the commit title with BF: at the beginning to indicate a bugfix. That tells me it should be included in bug-fix releases immediately (rather than new features that usually should wait for a major version). The label for the pull request doesn't matter so much though.

**Comment by AnnaTruzzi** [comment]
Will do, thanks!

**Comment by peircej** [comment]
This is handled by #2825 and extended by #2828
