### ISSUE TITLE
Allow for explicitly choosing the preferred code type view in code blocks.

### ISSUE THREAD

**Issue by mkoculak** [psychopy/psychopy#2831]
Would it be possible to allow for setting a default code type view for code blocks in Builder?

I am not using JS and since the pop-up windows with code always have the same size (and are not remembering previous size modifications), having the "Auto -> JS" option as the default makes half of the window unusable. Forcing me to either resizing the pop-up or changing the code type every single time.
This makes working with code blocks very tedious.

Simple option in the PsychoPy preferences would improve it immensely.

**Comment by peircej** [comment]
Yes, I think this would make sense. Would be a good "first issue" for someone :-)
