### ISSUE TITLE
version numbers of 2020.1.3 release broken on macOS

### ISSUE THREAD

**Issue by core-code** [psychopy/psychopy#2834]
i've downloaded version 2020.1.3 but when selecting it in the Finder it claims to be version 2020.1.2

you did forget to update the CFBundleShortVersionString entry in your Info.plist

also the 'CFBundleGetInfoString' entry has been deprecated for more than 10 years and should be removed

<img width="466" alt="Screenshot 2020-03-11 at 13 07 44" src="https://user-images.githubusercontent.com/1261954/76415440-7dcdb200-6399-11ea-8a24-2862fb190167.png">

**Comment by peircej** [comment]
I'll look into why the version number got inserted incorrectly for that version. This is an entriely automated procedure so I'm puzzled!

Removing CFBundleGetInfoString is easy enough, and that needs replacing with NSHumanReadbleCopyright?

**Comment by core-code** [comment]
> I'll look into why the version number got inserted incorrectly for that version.
> This is an entriely automated procedure so I'm puzzled!

thats weird, i had assumed it was done manually, which is easy to forget from time to time

> Removing CFBundleGetInfoString is easy enough,
> and that needs replacing with NSHumanReadbleCopyright?

indeed, if you have/want copyright information it should be put into 'NSHumanReadbleCopyright' these days.

**Comment by core-code** [comment]
while you are at it, you may want to look at the CFBundleVersion = 0.0.0 thing. while 'CFBundleShortVersionString' is more or less cosmetic, CFBundleVersion is used to determine the newest version by the operating system (if multiple are installed). 

setting it to the same thing as 'CFBundleShortVersionString' should be an easy fix

**Comment by peircej** [comment]
Yes, will do. I do all this via py2app (using whatever fields it suggested in its demo years ago) but I think it allows me to use whatever fields I like so I'll do that.
