### ISSUE TITLE
Test suite fails with `ModuleNotFoundError`

### ISSUE THREAD

**Issue by TheChymera** [psychopy/psychopy#2840]
I am trying to run the test suite on the latest release (`2020.1.3`) with:

```
pytest -v -s -m "not needs_sound" psychopy
```

And I get the following test failure:

```
ImportError while loading conftest '/var/tmp/portage/sci-biology/psychopy-2020.1.3/work/psychopy-2020.1.3/psychopy/tests/conftest.py'.
psychopy/tests/conftest.py:5: in <module>
    from psychopy.app._psychopyApp import PsychoPyApp
psychopy/app/_psychopyApp.py:46: in <module>
    from psychopy import projects
psychopy/projects/__init__.py:11: in <module>
    from . import pavlovia
psychopy/projects/pavlovia.py:18: in <module>
    from psychopy.tools.filetools import DictStorage, KnownProjects
psychopy/tools/filetools.py:21: in <module>
    import json_tricks
E   ModuleNotFoundError: No module named 'json_tricks'
```

This is the full [build.log](https://github.com/psychopy/psychopy/files/4385311/build.log).

Any idea what I am doing wrong?

**Comment by peircej** [comment]
Presumably you don't have `json_tricks` installed.
That's a pure python lib that we need so we can save/retrieve things like numpy arrays and datetime objects in json files (the built-in json loader doesn't support them).
The full dependencies are in https://github.com/psychopy/psychopy/blob/master/setup.cfg

**Comment by TheChymera** [comment]
Thanks, that solved it :)
