### ISSUE TITLE
Mouse component status will never update if "end routine on press" is set to "never"

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#2844]
If you set "end routine on press" of a mouse component to "never", its status is never updated and you cannot create temporal windows of activation. In fact, it does not update on each frame by default, unless you have added a code component that does the updating.

I have created a demo (which has some demo code for solving someone else's problem) in this project: https://gitlab.pavlovia.org/jfkominsky/testmousecontains

This is true in both JS and Python.

**Comment by peircej** [comment]
Thanks for that. I'll check the logic. To be fair, with mouse and keyboard, getting the logic correct with the full range of different behaviors is surprisingly hard!
