### ISSUE TITLE
Math formulas not rendering in documentation

### ISSUE THREAD

**Issue by pn2200** [psychopy/psychopy#2845]
Math formulas are not rendered in documentation on website, for example on https://www.psychopy.org/general/gamma.html. See image:

<img width="362" alt="gamma" src="https://user-images.githubusercontent.com/489253/78308812-53859500-74fe-11ea-8efc-a832d60a3d16.png">

Math content is not rendered because the MathJax.js is not being loaded from http://mathjax.connectmv.com. It is blocked by Chrome, Firefox and Safari browsers with error message "Mixed Content: The page at 'https://www.psychopy.org/general/gamma.html' was loaded over HTTPS, but requested an insecure script 'http://mathjax.connectmv.com/MathJax.js'. This request has been blocked; the content must be served over HTTPS." in the browser developer console.

**Comment by peircej** [comment]
Thanks! :-)
