### ISSUE TITLE
Autotranslate JS: randint() followed by something

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2847]
There is no `randint` in Math.js

`posY = randint(-50,50)`
correctly translates to 
`posY = (Math.floor((Math.random() * ((50 - (- 50)) + 1))) + (- 50));`
but
`posX = randint(-50,50)/100`
isn't detected as a randint function and translates to 
`posX = (randint((- 50), 50) / 100);`
which fails

Maybe rather than a complex translation we should just create the randint function, no?

**Comment by peircej** [comment]
Oh, as an addendum if turns out that `random()` also doesn't autotranslate to be `Math.random()`

**Comment by hoechenberger** [comment]
> Maybe rather than a complex translation we should just create the randint function, no?

Why not use `tensorflow.js`? Yes it's big, but… so what:

https://www.tensorflow.org/api_docs/python/tf/random/uniform

**Comment by hoechenberger** [comment]
> Maybe rather than a complex translation we should just create the randint function, no?

Why not use `tensorflow.js`? It's bit, but… who cares :)
https://www.tensorflow.org/api_docs/python/tf/random/uniform

**Comment by hoechenberger** [comment]
Why not simply use `tensorflow.js`? Yes it's big, but who cares :)

https://js.tensorflow.org/api/latest/#randomUniform
