### ISSUE TITLE
Auto-translate JS: Loop names are translated verbatim, rather than using 'trials'

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#2848]
This is potentially causing user issues, because no error is given when using the actual loop name in the auto-translated JS script - `loop.finished = true;` just fails to end the loop. Example, see https://github.com/psychopy/psychojs/issues/68

**Comment by reblando** [comment]
Hi, can you please explain more what you mean in the linked thread for how to fix this issue of currentLoop.finished = 1; failing to end the loop. I have been struggling with this for awhile now.

**Comment by dvbridges** [comment]
Hi @reblando , the PsychoPy Discourse forum is a good place to find these sorts of solutions. In this case, you can use `trials.finished = true;`, rather than "currentLoop".

**Comment by peircej** [comment]
Version 2020.2 will support
- `nameOfLoopHere.finished`
as well as
- `currentLoop.finished`
as in PsychoPy local runs

Builder code fixed here: d338f1710b8e9f9d9f1c5b1be628919705e6b01e
but there were also changes to psychojs
