### ISSUE TITLE
Cannot open Builder Image component when value no longer exists...

### ISSUE THREAD

**Issue by PsyTechMMU** [psychopy/psychopy#2855]
When a Builder Image component (possibly others) has its update field set to a value that no longer exists in the project, the component cannot be opened/edited.

Error:
`    index = allowedUpdates.index(param.updates)
ValueError: 'set during: init.initISI' is not in list`

Repro:
1. Create two Routines: add an ISI to the first and an Image component to the later one
2. Set the Image component to be set in the ISI
3. Delete the first Routine (the one with the ISI in it)
4. Click the Image component (or right-click - Edit)

Observed: error and cannot open the Image component to edit it.

**Comment by TEParsons** [comment]
Okay, I've added a fix for this! It's just a case of `if not in` - it now defaults to the first choice in the list if it can't find the original option.
