### ISSUE TITLE
Python 2 dependencies

### ISSUE THREAD

**Issue by danielshub** [psychopy/psychopy#2856]
The Arch Linux packaging system picked up a few files that have a shebang line for Python 2

psychopy/contrib/mseqSearch.py
psychopy/contrib/mseq.py
psychopy/localization/__init__.py
psychopy/contrib/quest.py
psychopy/demos/coder/hardware/crsBitsAdvancedDemo.py

I am not sure if these files really require python 2 or just never got updated.

**Comment by peircej** [comment]
I have a strong suspicion that those just weren't updated. I'll push a fix
