### ISSUE TITLE
Slider marker not showing up in online version?

### ISSUE THREAD

**Issue by DarinkaTruebutschek** [psychopy/psychopy#2860]
Dear all,

I've noticed that, when run online, the marker typically associated with the slider object is not shown. It seems to be the case that this only happens when the slider response is also set to end the routine, so it has been suggested to add an additional response requirement to a slider, to have the marker show up. However, is there any way to show the slider marker online as is done in the offline version? Thanks a lot!

**Comment by TEParsons** [comment]
This has since been fixed by @thewhodidthis on the JS end :)
