### ISSUE TITLE
Error when installing with latest wxPython

### ISSUE THREAD

**Issue by grszkthfr** [psychopy/psychopy#2864]
Following [instructions](https://www.psychopy.org/download.html) for an installation on Ubuntu 18.04 leads to an unuseable instance when using the latest wxPython wheel ([wxPython-4.1.0-cp36-cp36m-linux_x86_64.whl](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/)).

By unusable I mean nothing is clickable and it gives the following errors (e.g. when trying to open the preferences). 

```
Welcome to PsychoPy3!
v2020.1.2
Traceback (most recent call last):
  File "/home/XXX/.local/share/virtualenvs/XXX-It8ZLjAZ/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 771, in showPrefs
    prefsDlg = PreferencesDlg(app=self)
  File "/home/XXX/.local/share/virtualenvs/XXX-It8ZLjAZ/lib/python3.6/site-packages/psychopy/app/preferencesDlg.py", line 175, in __init__
    sizer.Add(line, 0, lineStyle, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at /home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/sizer.cpp(2077) in DoInsert(): Vertical alignment flags are ignored in vertical sizers

```

And from the terminal:

```
05:48:49 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
05:48:49 PM: Debug: Adding duplicate animation handler for '1' type
05:48:49 PM: Debug: Adding duplicate animation handler for '2' type
05:48:49 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
05:48:49 PM: Debug: Adding duplicate animation handler for '1' type
05:48:49 PM: Debug: Adding duplicate animation handler for '2' type
05:48:49 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
05:48:49 PM: Debug: Adding duplicate animation handler for '1' type
05:48:49 PM: Debug: Adding duplicate animation handler for '2' type
05:48:50 PM: Debug: "Shift+Tab" is not supported as a keyboard accelerator with GTK
```

The older wheel (wxPython-4.0.7-cp36-cp36m-linux_x86_64.whl) works fine.

FYI, I am separating python environments using pipenv. Not sure if this plays a role here...

**Comment by mdcutone** [comment]
This is expected since wxPython 4.1 removed lots of deprecated stuff. For now use the wxPython 4.0.x.

**Comment by TEParsons** [comment]
I've been working on the next release in wx 4.1 and have been removing depreciated function errors as I go, this particular error is definitely one I've come across & fixed. Will be pulling in the fix along with various changes and updates in the next few weeks!

**Comment by peircej** [comment]
I believe this is largely working now. I intend to ship the standalone for 2020.2 with wx4.1 so we'll soon find out if it isn't! ;-)

**Comment by radiantone** [comment]
Hi. I still get this error using 4.1.1 on ubuntu 20.10

wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at /tmp/pip-install-8zhwx37h/wxPython/ext/wxWidgets/src/common/sizer.cpp(2143) in DoInsert(): Vertical alignment flags are ignored in vertical sizers

**Comment by peircej** [comment]
@radiantone what version of psychopy do you have installed?

Actually, did you change your post to remove the full traceback? From what I can see of your unedited version it wasn't even in a PsychoPy dialog box that you were seeing the error message. I think yours is an unrelated issue with your own code; a bug in your `GSASIIimgGUI.py`

**Comment by radiantone** [comment]
yeah, it wasn't related to psychopy, and probably I shouldn't have posted on this ticket (thought maybe it was same root issue), but downgrading wxPython to 4.0.7.post2 did solve the problem for me FWIW.
