### ISSUE TITLE
Type error in the JS file after "export HTML" 

### ISSUE THREAD

**Issue by sou-chon** [psychopy/psychopy#2871]
This is my exported code as is:

```JS
  psychoJS.experiment.addData('too_late_prac_1_resp.keys', too_late_prac_1_resp.keys);
  if (typeof too_late_prac_1_resp.keys !== undefined) {  // we had a response
    psychoJS.experiment.addData('too_late_prac_1_resp.rt', too_late_prac_1_resp.rt);
    routineTimer.reset();
  }
```

I think `typeof too_late_prac_1_resp.keys !== undefined` will always return true because the type of `undefined` is `'undefined'` (as string)

**Comment by dvbridges** [comment]
@sou-chon , the keyboard parameter "keys" is set to `undefined` by default, however the typeof operator returns the type result as a string (`"undefined"`), so this is the reason for your issue. See docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

You could instead remove the `typeof` operator to fix this issue.

**Comment by sou-chon** [comment]
Sorry if I wasn't clear - this is the exported component code from pyschopy builder. Therefore there's a problem with javascript code generation when it "exports html". I was hoping someone could fix that :-)

**Comment by sou-chon** [comment]
Ah! upon closer reading of your comment I understand now. I was using core-3.2. Good that it was fixed in 2020. thanks!
