### ISSUE TITLE
getGlyphPositionForTextIndex errors when giving location of a newline

### ISSUE THREAD

**Issue by DanBennettDev** [psychopy/psychopy#2874]
If the character indexed is a newline, as in this example
```
     displayTxt="A\n"
    textbox.setText(displayTxt)
    cursorPos = textbox.getGlyphPositionForTextIndex(len(displayTxt)-1)
```
or still if the newline is not the last character

```
     displayTxt="A\nA"
    textbox.setText(displayTxt)
    cursorPos = textbox.getGlyphPositionForTextIndex(len(displayTxt)-2)

```

Then getting the position of that character produces the following error

```
  File "D:\edu\phd\Projects\Interaction Dominance\KeystrokeDynamics\Experiments\Software\Experiment Interface\prototype1.py", line 210, in <module>
    cursorPos = textbox.getGlyphPositionForTextIndex(len(displayTxt)-1)
  File "C:\Users\dan\Anaconda3\envs\psychopy\lib\site-packages\psychopy\visual\textbox\__init__.py", line 535, in getGlyphPositionForTextIndex
    ox, oy = glyph_data['offset'][
TypeError: 'NoneType' object is not subscriptable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\dan\Anaconda3\envs\psychopy\lib\site-packages\pyglet\media\codecs\wmf.py", line 834, in __init__
    ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
  File "_ctypes/callproc.c", line 940, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set

```

Indexing a non-newline character in a string which contains a newline, is not a problem
E.g.
```
     displayTxt="A\nA"
    textbox.setText(displayTxt)
    cursorPos = textbox.getGlyphPositionForTextIndex(len(displayTxt)-2)
```

Platform: Win 10
font - issue arrises with both both fonts tested: 'Input Mono Condensed' and Lucida Sans Typewriter

**Comment by peircej** [comment]
We are currently working on TextBox2 which supercedes TextBox and supports various additional features. TextBox was purely for monospaced fonts and did not include features to make the text editable. These are being built into TextBox which will be a part of 2020.2 release. I don't anticipate further work by the core team on TextBox itself due to duplication of effort.

**Comment by DanBennettDev** [comment]
Thanks - I'll look forward to 2020.2 This one is not so tough to work around.
