### ISSUE TITLE
Creating Sound objects before MovieStim3 objects causes channel issue on Windows 10

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#2886]
Repro: Create a copy of moviestim.py coder demo. Add after first set of import statements:

```
from psychopy import sound

demoSound = sound.Sound('someaudiofile.wav')
```

(Any arbitrary audio file will work.) When the sound.Sound object is created before the visual.MovieStim3 object (but not when the MoveiStim3 object is created first), Windows 10 will produce the following error when using the sounddevice audio library:
`From cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x0000021E1D8E77B8>:
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy3\lib\site-packages\sounddevice.py", line 740, in callback_ptr
    return _wrap_callback(callback, data, frames, time, status)
  File "C:\Program Files\PsychoPy3\lib\site-packages\sounddevice.py", line 2516, in _wrap_callback
    callback(*args)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\sound\backend_sounddevice.py", line 208, in callback
    toSpk[:len(dat), :] += dat  # add to out stream
ValueError: non-broadcastable output operand with shape (128,1) doesn't match the broadcast shape (128,2)`

This will first pop up in an error alert window but the program will not crash, however no audio will play for either movie or audio stimuli (visuals will still play, however). If PTB audiolib is used, the program crashes outright with the following:
`Exception: Number of columns of audio data matrix doesn't match number of output channels of selected audio device.`

After some further diagnostics in the sounddevice backend, the issue seems to be with the "channels" property of soundStream objects: when the Sound object is created first, PsychoPy recognizes there being 2 channels in the input and 2 channels in the output for the sound, but when it gets to the movie it thinks there is only 1 channel for the _output_, and furthermore the stereo to mono conversion fails. The change in channels is the foundational issue here as that should not happen, but it's unclear if the stereo/mono conversion is also part of the problem.

This is specific to recent versions of Windows 10 and does not seem to occur on MacOS.

**Comment by TEParsons** [comment]
@mdcutone does still this happen with the FFMPEG video class?

**Comment by mdcutone** [comment]
No, the new FFMPEG class uses SDL2 for audio output and wont have these issues. Might not actually fix the problem for people needing audio to play through interfaces accessed through `Sound`.

**Comment by MichaelWoodc** [comment]
> No, the new FFMPEG class uses SDL2 for audio output and wont have these issues. Might not actually fix the problem for people needing audio to play through interfaces accessed through `Sound`.

I can confirm that as of this date, a similar issue still exists but it might  not be identical as we don't seem to get an error code.  

I can have an experiment working PERFECTLY!  BUT if I go to the beginning to add sound, it causes all following videos to no longer play sound.  Also, the frame rate of the videos is out of control with this sound added before the videos.

**Comment by peircej** [comment]
I suggest we actually close this issue as it related to a now-deprecated movie stim class. We're keen to make MovieStim the one and only movie class, and push people to use it with `backend='ffpyplayer'`

I think we should focus on fixing issues just in that set up and closing issues for older classes. @MichaelWoodc maybe you could provide a minimal working example of the new problem as a new issue? thanks
