### ISSUE TITLE
make the csv-separator selectable

### ISSUE THREAD

**Issue by JensBoelte** [psychopy/psychopy#2891]
Hello,

this is a more general remark or feature request. At the moment, PsychoPy and pavlovia allow to store the data in csv-format which can easily be processed with excel. Well, only as long as you use a country scheme that employs a comma as a separator which is, for instance, not the case in Germany. A German excel is unfortunately not clever enough to import a PsychoPy/pavlovia csv-file properly without some preprocessing or altering defaults. So, I wonder if it were possible to add a feature allowing to select the column separator?

cheers Jens

see discussion on [PsychoPy-discourse](https://discourse.psychopy.org/t/make-csv-separator-selectable/14273)

**Comment by mdcutone** [comment]
Note to devs for addressing this. A way around this is to enclose values in quotes so strings with commas are considered values:

```
0, "1,000", Something
```
Excel is smart enough to put 1,000 in it's own column without splitting it to 1 and 000 if it gets this input. If you make this the default behavior, rather than specifying additional delimiters, pretty much all programs that import the CSV format can make sense of it (Pandas, R, LibreOffice, etc.)

**Comment by m-macaskill** [comment]
Hi Matt, but does that handle the localisation issue _within_ cells? i.e. would '1,000' still be interpreted in a German locale as `1.000`?

**Comment by JensBoelte** [comment]
Hello Matt,

Excel would interpret „1,000“ as string and not as number. In addition, Excel with a German layout would still not handle the csv properly. Notice that this an Excel-specific problem. LibreOffice imports csv-file properly even with a German scheme. I am asking for this option because I teach undergraduates. Excel is installed on the university computers and not LibreOffice. I‘d rather speak 15 minutes about PsychoPy, R aso. instead of speaking about deficits in Excel.

Cheers Jens

**Comment by peircej** [comment]
> I am asking for this option because I teach undergraduates. Excel is installed on the university computers and not LibreOffice. I‘d rather speak 15 minutes about PsychoPy, R aso. instead of speaking about deficits in Excel.

Haha I do hear you! Would be lovely if Excel could cope with csv file shared between countries! I wonder what settings/variants we'll need for this. Possibly a setting for cell separator (, or ;) as well as decimal separator (. or ,)

**Comment by mdcutone** [comment]
Yes, you're right they would be interpreted as strings and the cells would require manual formatting afterwards. Not a problem for small files, but I assume things can get really messy with lots of columns.

**Comment by JensBoelte** [comment]
Hi

in the best of all worlds Excel could handle these csv-files as LibreOffice can. There is an option deeply buried in the Excel-settings which alters this behavior but has consequences at different places. I'd like to avoid these consequences. ;-) A (;) as column separator would work; a (,) as decimal separator would in a German layout as well.

Cheers Jens
