### ISSUE TITLE
TextBox2 remaining issues

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2898]
- [x] Cursor doesn't currently work (although it did before, so might revert the move to a separate Caret class)
- [x] Clicking on the box with the mouse should give the box focus of the keyboard (Tab does work to switch between editable boxes though)
- [x] The box itself doesn't resize correctly yet around the text
- [ ] Alignment isn't done yet (centre/left/right align) although anchors do work to align pos with box

**Comment by peircej** [comment]
@TEParsons I'm right in thinking that the cursor is now working correctly, right? I wasn't sure where we are with the other parts of this. If you hit a block with it then assign it back to me

**Comment by TEParsons** [comment]
Yep, caret is working & so is click focus :)

**Comment by TEParsons** [comment]
Alignment is done now, what do you mean by not resizing correctly? Like adjusting height when size[1] is -1? Or is this just padding?

**Comment by peircej** [comment]
When I had the box outline/fill visible it didn't necessarily appear correctly arount the text (check with a range of anchor settings)

**Comment by TEParsons** [comment]
Ahh okay cool, that'll have been fixed as part of adding padding functionality :)

**Comment by peircej** [comment]
The last one, to handle alignment is now a separate issue #3017 for next release
