### ISSUE TITLE
Text field in TextComponent is showing as Code

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2929]
This was already a bit strange in previous versoins but it now looks especially odd with dark mode and line numbers being added!:
![image](https://user-images.githubusercontent.com/380582/87447719-d2589680-c5f2-11ea-8319-bdbbfc718395.png)

**Comment by mdcutone** [comment]
Probably not the best thing to use there. Just use the regular TextCtrl and pick a monospace font using the coder font setting in prefs.

**Comment by peircej** [comment]
My thoughts too. Not sure why that got turned into an STC in the past
