### ISSUE TITLE
inconsistent software and hardware durations

### ISSUE THREAD

**Issue by neurochen** [psychopy/psychopy#2930]
I got inconsistent stimulus durations when measuring it in software and hardware ways. Software duration means the time stamp returned after win.flip(), with vsync enabled in both NVIDIA and psychopy settings. Hardware one means the voltage up duration calculated from photodiode reads. 

Although all the software duration is correct, in my case 100 ms (6 frames), but the hardware one will be occasionally either 5 or 7 frames. I tried lots of debugging, and it seems to be related to my pyqt window ot other windows in the OS in general. After interactions with other windows, the hardware timing in psychopy window becomes inaccurate, althouth the software ones returned from psychopy functions remains the same. 

Does anyone encounter similar issue? As vsync is enabled, it's hard for me to understand why this could happen. In principle, what we get from software reads should be what photodiodes give as well. 

Below is my setup:
- windows 10 build 1903
- python 3.8.3
- psychopy 2020.1.2
- pyglet 1.5.5
- pyqt 5.14.2

Update: this happens in a more or less periodic way, ~22 seconds to have inconsistent results.

**Comment by peircej** [comment]
> related to my pyqt window

You're interacting with a PyQt window? Are you not in fullscreen mode?

**Comment by neurochen** [comment]
@peircej I am in fullscreen mode. Otherwise, the software timing will not be accurate. I wrote another script to just simply create a psychopy window and flip the back buffer. It turned out that the inconsistency between software and hardware duration appears once interacted with any window, no matter it's pyqt from the same python process or other windows such as chrome. 

Did you ever encounter software/hardware timing discrepancy? Do you know any possible cause for that?

**Comment by peircej** [comment]
I don't understand. If you're in fullscreen mode how are you interacting with any other window? I would fully expect there to be timing errors while you interact with other windows but the point of fullscreen mode is pretty much to prevent that from happening

**Comment by neurochen** [comment]
@peircej Thanks for thinking about the rig configuration. We have dual monitors running in extended screen mode. This setting is required as we need a UI to visualize behavior measures and adjust experimental parameters. This is a use case for animal rather than human studies.

**Comment by peircej** [comment]
I see. Well, as I say, it isn't surprising that thing stutter while you interact with the system user interface (i.e. window controls). Operating systems assign really high priorities to mouse/window events and when they get received the OS goes and spends time working out what to do about it. That takes time and takes priority over all else.

**Comment by neurochen** [comment]
Thanks, Jon.
