### ISSUE TITLE
Line/Column values invalid for unsaved document in coder.

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2936]

**Comment by TEParsons** [comment]
Invalid in what way?

**Comment by peircej** [comment]
I can't replicate it! Let's close for now

**Comment by mdcutone** [comment]
Still getting this issue. Might be a Windows thing?

![Capture](https://user-images.githubusercontent.com/5150568/88296394-a2815100-cccc-11ea-9b06-c66b775ecddc.PNG)

**Comment by mdcutone** [comment]
Okay, I think I figured out how it happens. If the cursor is at the very end of the document it reports an invalid value on all documents. Seems to be easily evident in empty files.

**Comment by mdcutone** [comment]
Fixed the issue, was caused by STC not reporting the caret as visible when at the end of the document. Put in a little hack to get it working.
