### ISSUE TITLE
Crash when calling "applyToRichText"

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2939]
PsychoPy 2020.2 crashes upon startup with the following traceback, due to how the theme is applied.

```
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\runner\runner.py", line 822, in write
    self._applyAppTheme()
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 281, in _applyAppTheme
    handlers[thisType](target)
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\themes\_themes.py", line 230, in applyToRichText
    fontName = base['font'].replace("bold", "").replace("italic", "").replace(",", "")
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by peircej** [comment]
this will have been caused by recent switch to have a list of fonts instead of a single font

**Comment by TEParsons** [comment]
What theme file is it reading in? It's probably because you have the old spec in your user prefs folder, but it should be able to handle that anyway... If you could also get the value of `ThemeMixin.codeColors['base']` at this point that would be helpful

**Comment by mdcutone** [comment]
These are the values I get, crashes on the last one I assume:

```
{'fg': wx.Colour(220, 220, 220, 1), 'bg': wx.Colour(30, 30, 30, 1), 'font': 'Consolas', 'size': 9}
{'fg': wx.Colour(220, 220, 220, 1), 'bg': wx.Colour(30, 30, 30, 1), 'font': 'Consolas', 'size': 9}
{'fg': wx.Colour(220, 220, 220, 1), 'bg': wx.Colour(30, 30, 30, 1), 'font': 'Consolas', 'size': 9}
{'fg': wx.Colour(220, 220, 220, 1), 'bg': wx.Colour(30, 30, 30, 1), 'font': 'Consolas', 'size': 9}
{'fg': wx.Colour(220, 220, 220, 1), 'bg': wx.Colour(30, 30, 30, 1), 'font': ['Lucida Console'], 'size': 9}
```

**Comment by TEParsons** [comment]
Aha! Found the problem - if code font / output font are both "From theme..." then `base['font']` goes through `ThemeMixin.extractFont` before being used, but it doesn't if either font is set from prefs, meaning it remains a list. I'll get cracking on a fix.
