### ISSUE TITLE
Coder loses focus while typing (due to new code analysis feature?)

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2944]
When I type into new Coder view as I enter parenths the cursor disappears and I have to click on the window to type any more.

e.g. type 
```
print(
```
and then have to click again

**Comment by peircej** [comment]
I guess more generally there's a question about whether we need to be able to turn off auto-completion and code analysis if it slows things down?

**Comment by mdcutone** [comment]
Don't have focus problems here, but there is an option in prefs to disable autocomplete. The issue may be due to the autocomplete system slowing things down.

**Comment by peircej** [comment]
Ah, yes, and turning autocomplete off does get rid of the problem. But it isn't a matter of time per se - if I wait the focu doesn't ever come back. I wonder if it's an issue with not being able to provide the tooltip and then bailing out

**Comment by peircej** [comment]
It's specifically something to do with the calltip. The following works fine:

```python
from psychopy import prefs
prefs.
```
It pauses but correctly gives the correct info and doesn't lose focus

**Comment by peircej** [comment]
Ah, OK it's a wx version-specific bug I think. On 4.0.7 it loses focus at the point when the calltip should have come up. On wx 4.1.0 it works, so I guess we still need something to allow the calltip code **only on wx 4.1**

**Comment by peircej** [comment]
Other slightly ugly thing is that the calltip stays on after I've closed the bracket 🤮

**Comment by mdcutone** [comment]
We could do something where the calltip is closed when the bracket it was opened at gets paired.
