### ISSUE TITLE
Untitled (in-memory) documents keep prompting to be reloaded from disk.

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2952]
When creating a new document in Coder, I periodically get prompted to reload the file from disk. Even though the document has not been saved yet. This might be due to the document checking the modification time against a non-existent file.

**Comment by TEParsons** [comment]
I can't seem to replicate this - do you mean you get the reload dialog, or just that something happens in the code which you can see with a breakpoint?

**Comment by mdcutone** [comment]
Get a reload document. Seems to only affect documents named "untilted.py". Just create a new file and open some others then switch between them.

**Comment by TEParsons** [comment]
Still doesn't seem to do it, and I've pulled down the Master branch. Could be specific to Mac?

**Comment by mdcutone** [comment]
No still having the issue. I'll probably show what's happening over Zoom or something if you have the chance.

**Comment by TEParsons** [comment]
I'm free today, any time but 11 basically :) Just drop me a message on Slack when you're about

**Comment by mdcutone** [comment]
Figured it out. I had a file named "untitled.py" in the current working directory. It kept asking to reload it, even though it was not been opened from disk. We should check if a file exists only if the document file path is an absolute path. Currently checking both absolute and relative paths.
