### ISSUE TITLE
Unmodified Coder documents prompt to save.

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2953]
Documents that have been opened but are unmodified prompt to save before closing. This is a bit annoying since you get a salvo of prompts when shutting down coder if you have a bunch of documents opened. The behaviour is inconsistent sometimes, but it seems to happen to unmodified documents that you set focus to over a session.

**Comment by peircej** [comment]
This is one I think that was introduced while implementing the live-updates for themes. I think I turned off an update call which was also being used for `setFileModified`. I'll hande it

**Comment by peircej** [comment]
OK, not what I thought. This is to do with calls to `Frame.Update()` which apparently sends EVT_STC_MODIFIED events. We need to do Refresh but not Update during theme applications I think
