### ISSUE TITLE
$ sign gets removed from JS code component

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#2955]
The standard PsychoJS web page includes jQuery, so I tried to use $('somethingsomething') in a JS code component to select an HTML element. The $ is still there in the .psyexp file, but it got removed when running the task via PsychoJS.

**Comment by TEParsons** [comment]
This looks deliberate, here's the code where it happens:
```
            if isStr and self.val.startswith("$"):
                # a $ in a code parameter is unnecessary so remove it
                val = "%s" % self.val[1:]
            elif isStr and self.val.startswith("\$"):
                # the user actually wanted just the $
                val = "%s" % self.val[1:]
```
Should be as simple as removing this code, but just wanted to check that we definitely want this gone?
