### ISSUE TITLE
Coder demos always appear modified

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#2967]
Most likely something changed about them when loaded, can probably fix by just loading all demos from root & saving changes

**Comment by peircej** [comment]
Is this just about demos? Or is it loading of *any* file? I think the latter

**Comment by TEParsons** [comment]
Just the demos, removing Update() from _applyAppTheme fixes it for other files

**Comment by peircej** [comment]
oooh! That's cool. That one was boggling my brain! :-)

**Comment by peircej** [comment]
Maybe it's to do with not having write-access to that location?

**Comment by TEParsons** [comment]
Could be! I thought it could be to do with differences in compiling but it applies to Coder demos just the same...
