### ISSUE TITLE
App error dialog Ctrl-C copies entire text even if something is selected

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#2969]
At times I just want to copy a single word (so I can search the code for that) but Ctrl-C in this dialog always copies all the text of the dialog. Should detect if text is selected and just copy that. Copy entire box if nothing selected

**Comment by mdcutone** [comment]
That's working as intended, it's suppose to copy the entire text to clipboard oppose to saving it so you can paste it into error reports. I could set it up where if there is a selection, it will only copy that.

**Comment by peircej** [comment]
Yes, I could totally see why you'd done it the other way but it keeps biting me. Selecting text and doing Ctrl-C is such a natural thing to do that it seems broken when it doesn't respect the selection
