### ISSUE TITLE
Editor styles don't apply if unstyled document is opened

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2982]
Here's a weird one. You can invoke this bug by opening a Python file in Coder. Styling will appear correct for subsequent Python files opened. However, if you open a plain text (unstyled) text file, any Python files opened afterwards will not have syntax highlighting applied.

**Comment by TEParsons** [comment]
It still correctly identifies the lexer and applies all the right style tags, so it's gotta be it not recognising keywords in Python. No idea what's causing it or why it only appears after opening a plain text file, but will keep at it tomorrow.

**Comment by TEParsons** [comment]
I think I've got it! Essentially at the beginning of `_applyAppTheme` it gets `ThemeMixin.codeColors` and stores it as `spec`, but `spec` is transformed when a plain text document is opened. I was treating it as if `spec` was just a copy of all the values, but I think it's actually a handle.
