### ISSUE TITLE
Missing attributes cause crash when starting coder.

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2984]
PsychoPy Coder crashes when starting due to missing attributes.

```
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\coder\coder.py", line 2215, in setCurrentDoc
    self.toolbar.EnableTool(self.cdrBtnRunner.Id, isExp)
AttributeError: 'CoderFrame' object has no attribute 'cdrBtnRunner'
```

The coder class is missing both attributes ```cdrBtnRunner``` and ```cdrBtnRun```.

**Comment by TEParsons** [comment]
These are made in `PsychopyToolbar`, which is called before any calls to `setCurrentDoc`, and I can't replicate this on my PC... I know Mac handles toolbars differently, if you put a breakpoint just after this bit:
```
self.toolbar = PsychopyToolbar(frame=self)
self.SetToolBar(self.toolbar)
```
(coder.py, lines 1128 & 1129)

Do `self.cdrBtnRunner` and `self.cdrBtnRun` exist?

**Comment by mdcutone** [comment]
Doesn't appear to be created on my end.

**Comment by TEParsons** [comment]
What if you set a breakpoint at line 256 in utils.py? Do you have `self.frame.cdrBtnRun`, and is `self.frame` correctly pointing to your coder frame?

**Comment by mdcutone** [comment]
Doesn't appear to even run that code. Why are we using statements like:

```
elif frame.__class__.__name__ == 'CoderFrame':
```

to identify the class the toolbar is being applied to instead of:

```
elif isinstance(self.frame, CoderFrame):
```

**Comment by mdcutone** [comment]
Oh great, things are working now after a rebase on my end, even though nothing changed with respect to the files affected by this bug. Closing for now.

**Comment by TEParsons** [comment]
I've found the problem anyway! At the end of the __init__ for PsychopyToolbar the "makeTools" command was commented out. The reason I used __class__.__name__ is that importing the CoderFrame class to compare lead to a circular import

**Comment by peircej** [comment]
hmm, I think I commented that out because after making tools we then call `applyTheme()`, which does `clearTools()` and `makeTools()` again. On my instance, commenting out this call to makeTools didn't affect anything but possibly it depends on something (like the order the frames were created or presence of reloading prev files or something like that).

**Comment by peircej** [comment]
I guess we could keep it for now but it feels like we're doing a lot of needless making/deleting of tools! (another solution might be only to change their state to enabled/disabled if they've been created and then not need to create until applying theme?)
