### ISSUE TITLE
A loop of loopType fullRandom seems to draw without replacement

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#2988]
I made a little experiment to test conditions and randomizations: https://gitlab.pavlovia.org/tpronk/e2e_conditions
- In this experiment, the first loop has its loopType set to "fullRandom", which should randomize with replacement.
- nReps is set to 1, so each condition should occur once
- The condition file has four conditions, displayed as the numbers 1, 2, 3, 4

I'd expect that I sometimes see one of the numbers occur twice in the random sequence, but I don't, so I suspect that fullRandom randomizes with replacement.

I think the issue in the code might be over here:  https://github.com/psychopy/psychopy/blob/9047a6c0061b697c28beff39881b6205e1a84166/psychopy/data/trial.py#L273

**Comment by peircej** [comment]
No fullRandom is not "with replacement". You should still get exactly nReps of each condition

`random` means shuffle, repeat, shuffle, repeat
`fullRandom` means concatenate the nReps*conditions and then shuffle that long list

from the documentation: 
> ‘fullRandom’ fully randomises the trials across repeats as well, which means you could potentially run all trials of one condition before any trial of another.

but maybe that could be clearer!
