### ISSUE TITLE
"Save As..." should update the editor file path to the new file location in title bar.

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#2994]
Title says it all.

**Comment by peircej** [comment]
Thi smight sound strange but I'm not entirely sure why the editor needs to have a file path at all. The files themselves have an associated path (e.g. needed as cwd when running the script) but what does it mean for the app to have a path?

**Comment by mdcutone** [comment]
This refers to the informal text in the title bar not being updated. You know, where it says `/my/file/code.py - PsychoPy3 Coder` in the title bar.

**Comment by peircej** [comment]
Oh I see, just that, yes :-)
