### ISSUE TITLE
pylint stumbles on several parts of the visual module

### ISSUE THREAD

**Issue by dillonplunkett** [psychopy/psychopy#3055]
PsychoPy version: 2020.2.1
Python version: 3.6.11
Pylint version: 2.5.3

Running Pylint (e.g., automatically through VS Code, but also directly) on scripts that use the visual module seems to produce a number of false errors. For example, this script runs without issue: 

```python
# test.py
# Runs without issue. 

from psychopy import visual

win = visual.Window()
shape = visual.ShapeStim(win)
poly = visual.Polygon(win)
```

But `pylint test.py` gives:
```
************* Module test
test.py:4:8: E1101: Module 'psychopy.visual' has no 'ShapeStim' member (no-member)
test.py:5:7: E1102: visual.Polygon is not callable (not-callable)
```

Out of my depth, so not sure if there's anything that can be done or even if this is a PsychoPy issue, but wanted to report it.

**Comment by peircej** [comment]
That's a false alarm. We use a system called "lazy import" for these packages so that they only get loaded when they're actually needed. That's relatively unusual, which is why pylint didn't understand it, but it isn't a problem
