### ISSUE TITLE
Wrong websocket library packaged with windows binary

### ISSUE THREAD

**Issue by bollaking** [psychopy/psychopy#3077]
The Emotiv hardware relies on the package:
websocket_client==0.57.0
This seems to be correctly included in the Mac binary.

The websocket package in windows seems to be 
websocket==0.2.1
and this does not work.

**Comment by peircej** [comment]
ah, yes, looks like the 32bit version picked up the wrong lib. That's fixed on the build machine and will be in the next bugfix release
