### ISSUE TITLE
Add system for Routine templates in experiment menu

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#31]
Lots of routines have common goals;
- provide feedback
- run a go/no-go trial
- run a 2IFC/2AFC trial
- get a rating

These could be saved as templates in the experiment menu. The system for copying and pasting routines between experiment windows already exists, this could probably be re-used here, but with saving to disk instead of clipboard.

**Comment by TEParsons** [comment]
We could potentially add this now that we have standalone routines! They could be managed by a dlg and appear in the component panel in their own category
