### ISSUE TITLE
Error is thrown if "cancel" is pressed in in the select root dir dialog for syncing a pavlovia project. 

### ISSUE THREAD

**Issue by j-ales** [psychopy/psychopy#3103]
Stack trace for thrown error.  

Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/project.py”, line 364, in onSyncButton
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py”, line 640, in sync
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py”, line 743, in getRepo
AttributeError: Cannot fetch a PavloviaProject until we have chosen a local folder.

**Comment by TEParsons** [comment]
I'm struggling to replicate this - that error should only appear if there is no local folder set, but the dialog when creating a project will throw an error if you try to click okay without choosing a local folder. Could you run me through exactly what you did to get this error?

**Comment by j-ales** [comment]
That probably explains it.   I can't quite recreate the steps now.  But there is no local folder set for this project for some reason.  I didn't create it using the dialog, but by forking/cloning/copying another project using git commands outside of PsychoPy.  Where is the local folder location saved?

**Comment by TEParsons** [comment]
#4374 introduces an entirely new interface for Pavlovia in Builder, so the dialog causing this bug no longer exists.
