### ISSUE TITLE
Automatically translating brush.reset() in JS

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychopy#3163]
With reference to [a recent forum thread](https://discourse.psychopy.org/t/getting-the-start-and-end-timing-for-a-brush-component/16529/19
), converting reset calls on Brush components to JS could be improved. While a `brushReset()` method is awesomely made available and used in the boilerplate to clear the canvas by turning off autoDraw on the ShapeStim instance, a `brush.reset()` typed inside the Coder lacks JS mapping. I was able to get away with manually adjusting the JS in 'both' edit mode, but making that happen automatically might also be possible.

**Comment by TEParsons** [comment]
Forgot to mention issue number, but this was fixed in #3186
