### ISSUE TITLE
autocomplete is raising an error on mac standalone

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3170]
My guess is that jedi needs to be packaged differently so that it isn't "frozen"

**Comment by mdcutone** [comment]
I originally wrote a Python autocomplete system from scratch that worked well enough, a was a bit faster too but not as smart as Jedi. I might revive it if Jedi becomes a bit of a pain to work with.

**Comment by peircej** [comment]
Don't worry for now. I _think_ it will be an easy fix when packaging
