### ISSUE TITLE
When generating JS the `frameRemains` math is sometimes off

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychopy#3182]
Could it be because of a delay parameter left empty in PsychoPy? Sometimes [`undefined` will sneak into the `frameRemains` calculation](https://gitlab.pavlovia.org/thewhodidthis/cl_acceptability_judgement/blob/master/cl_accept_judgement.js#L1204), which can lead to unpredictable results.

**Comment by TEParsons** [comment]
What parameter do you think it is? If it's `psychoJS.window.monitorFramePeriod` then that's something that's calculated from their hardware I think?

**Comment by peircej** [comment]
No the thing @thewhodidthis points to is in the script generated from PsychoPy (ie calculated at compile-time not run-time)

**Comment by peircej** [comment]
I think this is happening any time stop val is set to None, but I'm not sure why that wouldn't have come up as an issue before. I would have thought this was a common thing to do and must have been in numerous previous experiments (e.g. stroop) :-/

https://github.com/psychopy/psychopy/blob/196dd7a4aafc24757102fe4e8596396e411eb638/psychopy/experiment/components/_base.py#L363

**Comment by thewhodidthis** [comment]
Because of JS type coercion, instead of throwing, the result of adding `undefined` is first `NaN` then eaten up by the comparison operator just evaluating to `false` I believe

**Comment by peircej** [comment]
Fixed in d2ab058

**Comment by peircej** [comment]
Basically, this was cropping up only for Movie, and when the user gave stopTime=None. When that occurs the entire block that you're seeing shouldn't have been written (there is no specified stop time so we don't need any if statement about when to stop. We were failing to detect that the value was None because we had converted that to 'undefined' in the wrong way :-)
