### ISSUE TITLE
setAutoDraw(false) skipped when video shorter than duration given in PsychoPy

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychopy#3183]
This happens because when a **MovieStim** is done playing its status turns to `PsychoJS.Status.FINISHED`, but the check that is generated in place is expecting a status of `PsychoJS.Status.STARTED`:
```js
if (movie.status === PsychoJS.Status.STARTED && t >= frameRemains) {
  movie.setAutoDraw(false);
}
```

I believe having a check along the following lines might help:
```js
if ((movie.status === PsychoJS.Status.STARTED || movie.status === PsychoJS.Status.FINISHED) && t >= frameRemains) {
  movie.setAutoDraw(false);
}
```

**Comment by peircej** [comment]
interesting. Yes, that makes sense I guess, but it sounds strange said out loud! ;-)
