### ISSUE TITLE
I can't open my psychopy builder

### ISSUE THREAD

**Issue by guoweiwuorgin** [psychopy/psychopy#3185]

**Comment by guoweiwuorgin** [comment]
It is no response after I click the chart of psychopy build or the run gui. I don't know why and I have tried to redownload and rebuild the pspychopy ,but it did not work.

**Comment by peircej** [comment]
I would have thought the most likely thing is that the window is appearing somewhere that you aren't able to see it. What version of PsychoPy are you using? What operating system?

**Comment by guoweiwuorgin** [comment]
Thanks a lot for your kindly reply. I have solved the problem. But I encountered a new problem. Because the ioHub have improved and importing iohub submodules and classes is no longer all in the root iohub, I can't use the old version example of eyetracking stroop task to reproduce my experiment in a new eyetracking experiment. How can I check the change in the import function?

**Comment by peircej** [comment]
I'm not sure the answer to that. If you post on the user forum, with more detail, like what version you're using and what (complete) error messages you're getting then I'm sure you'll be able to get help there. This Issues list is really for us to track issues in the code. Thanks

**Comment by guoweiwuorgin** [comment]
I'm using the the psychopy3.0 2020.2.4 and I encountered the error :"ImportError: cannot import name  EventConstants " and the same problem encountered when I import load function from the ioHub.

**Comment by guoweiwuorgin** [comment]
and my platform is Windows
