### ISSUE TITLE
Review how canceling audio playback is handled in JS boilerplate

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychopy#3194]
There seems to be a problem with how the on-each-frame callback decides when a sound needs stopping, in cases where its duration is variable at least. I have created [a simple experiment to demostrate the problem](https://run.pavlovia.org/thewhodidthis/dynamic-sound-durations-almost/) and a possible fix. You'll hear the same sound play back five times in the first loop. In the second loop, the sound plays back only once because the routine end callback never fires.

In the snippet below, the `frameRemains` calculation alone seems both accurate and enough to have the sound stop on schedule. Can the `if (duration > 0.5) {}` conditional be safely removed?

```js
var onset = 0.5;
var duration = 0.5;
// ...
function trialRoutineEachFrame(snapshot) {
  return function () {
    // ...
    frameRemains = onset + duration - psychoJS.window.monitorFramePeriod * 0.75;
    if (sound_1.status === PsychoJS.Status.STARTED && t >= frameRemains) {
      if (duration > 0.5) {
        sound_1.stop();  // stop the sound (if longer than duration)
        sound_1.status = PsychoJS.Status.FINISHED;
      }
    }
    // ...
  };
}
```

Context: [discourse.psychopy.org/t/in-running-online-just-the-first-sound-of-many-sounds-is-presented &rarr;](https://discourse.psychopy.org/t/in-running-online-just-the-first-sound-of-many-sounds-is-presented)

**Comment by peircej** [comment]
The reason we had the code for `if (duration > 0.5)` was that forcibly stopping very brief sounds tended to cause some nasty effects from "spectral splatter" but maybe we should revisit that
