### ISSUE TITLE
Sound file cannot be played in a loop

### ISSUE THREAD

**Issue by elvisjade** [psychopy/psychopy#3197]
Hello, the problem I am currently experiencing is that my sound file cannot be played in a loop

Can someone help me? This is really important to me, thank you for your help!

I have read all the articles about sound loops or music loops in the forum, but still can’t solve my problem.
What I want to achieve is to repeat a sound 70 times during the experiment.

I wrote loops = 70 in my code, but only played once during the actual operation, and never played again later. I now want to achieve 70 repeats of playback under this code structure. I don’t know if it can be achieved.

My previous idea was to write a block that plays sound stimulation in the GUI version and then loop the block 70 times, but there are loops in my own code, I am worried that the nested loops in the loop will not be good.

This is my code:
numReps = 70
bstim = sound.Sound(value=bsoundfilename,loops=numReps-1,sampleRate=11025,autoLog=True)
dstim = sound.Sound(value=dsoundfilename,loops=numReps-1,sampleRate=11025, autoLog=True)
random.shuffle(adaptrials)
for trial in adaptrials: # 1 set of adaptors + test
    
    while paused:
        waitforunpause()
    
    # LISTEN prompt
    listenScr.draw() #draw test indicator slightly before soundfile
    win.flip()        
    
    i+=1
    
    if trial[0]==bendpoint:
        cond='b'
        adaptor = bstim
    else:
        cond='d'
        adaptor = dstim
        
    trialClock.reset()
    
    while trialClock.getTime() < adapGap:
        checkEsc()
        
    # play adaptors
    
    for j in range(trial[1]): # number of repeats
        trialClock.reset()  # clock
        adaptor.play()
    
    trialClock.reset()
    adaptor.play()
    
    while trialClock.getTime() < expoDur*numReps+2:
        longcheckEsc(adaptor,trialClock)
            
    # switch from LISTEN to RESPOND
    win.flip(clearBuffer=True) # clear window            
    trialClock.reset()
    while trialClock.getTime() < adapGap*.5:
        checkEsc()
My computer version is macOS 10.14.6
My psychopy version is 2020.2.4post1(install by conda)

**Comment by RebeccaHirst** [comment]
Hi There, It sound like you might want to move this over to discourse.psychopy.org 

So that we can be of more help there, please can you sync your code and associated files to pavlovia.org (this can be done from coder view even if you have no intention to run the study online). Then if you share the URL to your gitlab page it will be likely we can offer more support and try to replicate the problem. 

Thanks,
Becca
