### ISSUE TITLE
uninstall: cannot change path

### ISSUE THREAD

**Issue by shpj123** [psychopy/psychopy#3201]
Hello,
the current uninst.exe is fixed to the path C:\Program Files\PsychoPy3,
which makes it impossible to uninstall an old version in another fold or disk.
Best
PJ

**Comment by peircej** [comment]
It looks like it's coded to the install directory from this: https://github.com/psychopy/psychopy/blob/fd5ec48ae2569b36db866a4f7818bc0a7e3a204b/buildCompleteInstaller.nsi#L127

**Comment by shpj123** [comment]
> It looks like it's coded to the install directory from this:
> 
> https://github.com/psychopy/psychopy/blob/fd5ec48ae2569b36db866a4f7818bc0a7e3a204b/buildCompleteInstaller.nsi#L127

thanks for the reply.
![image](https://user-images.githubusercontent.com/50408937/95774068-014cda00-0cc0-11eb-9b0c-840d5a694a1d.png)

This was installed to drive D. But the uninstall path is still for drive C...
![image](https://user-images.githubusercontent.com/50408937/95774171-2f321e80-0cc0-11eb-8abf-1454aac340cb.png)

**Comment by peircej** [comment]
I wonder if it was installed to C: and then moved to D:? 
Or maybe a new drive has been added/moved so that what was C is now D?

**Comment by shpj123** [comment]
> I wonder if it was installed to C: and then moved to D:?
> Or maybe a new drive has been added/moved so that what was C is now D?

it was installed directly to D:
the thing is, that we could specify a different directory during the install, but this is not possible for the uninstall.

**Comment by peircej** [comment]
It isn't surprising that the uninstall folder is fixed. It should point only the location of the installation. What I don't understand is how it could end up pointing to the wrong folder

**Comment by SRSteinkamp** [comment]
Just want to report that I have the same issue on Win10 after installing PsychoPy 3 2020.2.4 on my D: drive. The Path is fixed to C:\Progam Files\... as well. 

I am wondering if it's save to simply remove the PsychoPy folder and maybe remove the PsychoPy Path?

**Comment by peircej** [comment]
So maybe this is a bug with NSIS and D drive. As a workaround yes, I would have thought you can delete the folder. The un/installer also adds/removes a couple of entries to the registry and I suppose one issue might be that if you then try to install psychopy again later it will think it's still installed and try/fail to uninstall again
