### ISSUE TITLE
TextBox2 unable to display Hindi text

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#3203]
The TextStim class has issues with displaying Hindi text like कोशिकायें ,truncating characters and not linking them together (see thread at https://discourse.psychopy.org/t/display-hindi-words/17158).

TextBox2 fails harder. When using `Arial` as the font, only boxes are shown. When trying to use `Arial Unicode`, which is recommended for showing Hindi on a Mac, the following error occurs:

```
File ".../psychopy/psychopy/visual/textbox2/textbox2.py", line 164, in __init__
    if self.glFont.atlas.format == 'rgb':
AttributeError: 'bool' object has no attribute 'atlas'
``` 

Hindi text seems to display okay when using PsychoJS, even when just specifying `Arial` as the font, whether using the Text or TextBox2 components.

This page provides suggestions on fonts to use for displaying Hindi on either Mac or PC:
https://dlsdc.com/blog/what-font-to-use-for-what-language/

**Comment by TEParsons** [comment]
I don't get the error with Arial Unicode MS - just a Textbox with boxes, as I'd expect if there was no unicode glyph for that character. What happens if you do:
```
from psychopy.visual.textbox2.fontmanager import FontManager
FontManager().getFont("Arial Unicode MS").atlas
```

**Comment by TEParsons** [comment]
When I try these characters with the font set to Noto Sans (https://fonts.google.com/specimen/Noto+Sans) the characters display fine, what happens if you download that font and use it on your machine? It could be a Mac thing maybe?

**Comment by m-macaskill** [comment]
- This is the result when using Noto Sans, not much different than when using other fonts (the upper one is a TextStim, the lower one is TextBox2): <img width="498" alt="Noto sans" src="https://user-images.githubusercontent.com/931027/99625776-d4959a80-2a95-11eb-8aa9-714aa3c15c1c.png">

- Noto Sans does work fine when testing locally via PsychoJS rather than PsychoPy, but so does Arial… 

- I don't know what platform the OP is using

- I was using the wrong name to refer to `Arial Unicode MS` (on my system it should just be `Arial Unicode`). But it seems that font is no longer supported by MS anyway, so your suggestion of Noto Sans looks like a more reliable option for testing against such unicode issues.

**Comment by jaycbcsgh** [comment]
tried with online..

Arial Unicode MS is not working properly. there is problem with some words which has some text in lower part

Noto Sans is not working

**Comment by TEParsons** [comment]
@m-macaskill, could you pull down #3335 on your machine and see if `test_glyph_rendering` (psychopy/tests/test_all_visual/test_textbox.py) passes for you? `textbox_tyke_1.png` is what it generated on my Windows machine using the text from this issue and Travis seems to match, so I'm keen to see how it looks on Mac

**Comment by isolver** [comment]
I can reproduce this issue on win10. TextBox also does not draw characters like कोशिकायें. I've been testing using FantasqueSansMono, which does have the character glyphs in question. In TextBox, the hindi characters are not displayed (a blank area is displayed), in TextBox2 they are drawn as a box, like:

![textbox2_hindi](https://user-images.githubusercontent.com/1795082/107037037-e92e2880-6790-11eb-81f7-b3043b266748.png)

I wonder if this is a limitation of freetype-py, or how we are using it. Have not have time to digest all the info, but it seems like this has been [an ongoing issue for others](https://github.com/python-pillow/Pillow/issues/2255) as well.

**Comment by TEParsons** [comment]
So far as I can tell, this is now working - please do reopen the issue if you can recreate the error in 2022.1 still!
