### ISSUE TITLE
Error when applying preferences

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3211]
I get the following error when applying preferences using the GUI. 

```
Traceback (most recent call last):
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 885, in OnOKClicked
    self.applyPrefs()
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 845, in applyPrefs
    self.updateBuilderUI()
  File "C:\Users\matth\PycharmProjects\psychopy\psychopy\app\preferencesDlg.py", line 861, in updateBuilderUI
    builder = self.app.builder
AttributeError: 'PsychoPyApp' object has no attribute 'builder'

```

I guess because there is no Builder frame open and were trying to apply preferences to it.

**Comment by peircej** [comment]
Actually, having looked at the code it also assumes there's a single Builder frame (there is only one Coder frame permitted currently but multiple Builder frames).

I believe, rather than updateCoder and updateBuilder we should be using an updateFrames method and letting that handle both types:

```python

    def updateFramesUI(self):
        """Update the Coder UI (eg. fonts, themes, etc.) from prefs."""
        for frame in self.app.getAllFrames():
            if frame.frameType == 'builder':
                frame.layoutPanes()
            elif frame.frameType == 'coder':
                # apply settings over document pages
                for ii in range(frame.notebook.GetPageCount()):
                    doc = frame.notebook.GetPage(ii)
                    doc.theme = prefs.app['theme']
                for ii in range(frame.shelf.GetPageCount()):
                    doc = frame.shelf.GetPage(ii)
                    doc.theme = prefs.app['theme']
```

**Comment by peircej** [comment]
I've made that change in https://github.com/psychopy/psychopy/pull/3227/commits/db7325496e72abfc919d36627c808b244ce2743d

BUT I'm not sure it's needed at all:
- setting app.theme should update the UI for each frame itself, as part of its setter
- We just need to make sure that app.theme is being set when the preference dlg closes and that's the bit I'm not sure about. I can see a line there that sets `self.app.theme = self.app.theme` based on this commit https://github.com/psychopy/psychopy/commit/69c92dd5c950a1bd196986d6cf69c40e5a832cc2 but I can't see anything that fetches the (new) theme from the prefs dialog

@TEParsons any idea about this last bit?

**Comment by TEParsons** [comment]
Calling the property `self.app.theme` returns `prefs.app['theme']`, this should be the new theme as it will have been saved by the dlg to `prefs`, right?

**Comment by peircej** [comment]
OK, decision time, I'll pull my fix into the repo for now, with some doubts about performance/redundancy (notably, about setting themes too many times from a single call) but I'll leave it out of the maintenance release branches and we'll handle optimization later
