### ISSUE TITLE
Issue with pyglet, green lines appearing across the screen

### ISSUE THREAD

**Issue by mar-mite** [psychopy/psychopy#3228]
Hi there,

When I run any kind of window or stimulus there are green lines that appear across the window. Attached are some example images and I also get these error messages:

```
C:\Users\ra150\PycharmProjects\pythonProject\venv\lib\site-packages\pyglet\media\codecs\wmf.py:838: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))
C:\Users\ra150\PycharmProjects\pythonProject\venv\lib\site-packages\pyglet\image\codecs\wic.py:292: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))
```

![text](https://user-images.githubusercontent.com/73116931/96455823-a2ceb100-1215-11eb-94d0-6703732cb628.png)
![circle gray](https://user-images.githubusercontent.com/73116931/96455829-a5310b00-1215-11eb-9545-ced2b3bed7e8.png)
![grating](https://user-images.githubusercontent.com/73116931/96456047-e3c6c580-1215-11eb-82ec-9c2b81b5b1bb.png)

Cheers

**Comment by peircej** [comment]
Sorry, I have no ideas about this. Not problem I've seen before. You're using your own installation by the looks of it and a version of Python (3.8) that I haven't used (probably with a version of pyglet I haven't tried as well) so my guess it that there's a problem with one of those things but I really couldn't offer any explanation as to what.

**Comment by peircej** [comment]
This has cropped up on another user's computer at one of our workshops. Using Standalone 2020.2.5. This was the sysInfo.py output:

```
Python info
C:\Program Files\PsychoPy3\pythonw.exe
3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
numpy 1.18.1
scipy 1.4.1
matplotlib 3.3.0
pyglet 1.3.3
pyo 0.9.7
PsychoPy 2020.2.5
have shaders: True
OpenGL info:
vendor: Intel
rendering engine: Intel(R) UHD Graphics P630
OpenGL version: 4.6.0 - Build 27.20.100.8336
(Selected) Extensions:
     True GL_ARB_multitexture
     True GL_EXT_framebuffer_object
     True GL_ARB_fragment_program
     True GL_ARB_shader_objects
     True GL_ARB_vertex_shader
     True GL_ARB_texture_non_power_of_two
     True GL_ARB_texture_float
     False GL_STEREO
    max vertices in vertex array: 1048576
2.6564     WARNING     Monitor specification not found. Creating a temporary one...
```

**Comment by mdcutone** [comment]
Does the problem go away when useFBO=True?

**Comment by mdcutone** [comment]
Seems to be a bug with the 630 series of Intel graphics cards. 

https://community.intel.com/t5/Graphics/Intel-HD-630-green-lines-in-OpenGL-apps/td-p/1192516

**Comment by mar-mite** [comment]
Someone discovered a temporary fix to this by setting multiSample = true and numSamples = 16.

https://stackoverflow.com/questions/64333695/does-anyone-know-how-to-fix-random-green-lines-appearing-on-psychopy-stimuli

**Comment by peircej** [comment]
Good info. Thanks @mdcutone and @mar-mite. So this could be fixed either by updating the Intel graphics driver https://downloadcenter.intel.com/download/29808/Intel-Graphics-Windows-10-DCH-Drivers?product=98909

And for those that can't do it could be solved with a mysterious change to multisample settings!

**Comment by mdcutone** [comment]
I wonder if this issue goes away with `useFBO=True`.

**Comment by mar-mite** [comment]
The issue doesn't go away with `useFBO=True` , in fact it morphs into both green and pink lines.
The driver installation has provided a permanent fix now. Thanks for that.

**Comment by mdcutone** [comment]
Okay that pins it down as a driver bug, thanks.
