### ISSUE TITLE
Regression in automatic Python->JS translation

### ISSUE THREAD

**Issue by bbonf** [psychopy/psychopy#3241]
Hi,

I have a sample experiment in which I use the following code in a Text element to display feedback based on responses:

```
$'correct' if train_response.corr else 'incorrect'
```

To be honest I don't know whether this is a legitimate use of PsychoPy's scripting support, but it does work on 2020.2.4 and it no longer works on master. (the script is written in the JS file without translation, and everything breaks)

I traced it back to the following commit:
https://github.com/psychopy/psychopy/commit/275d2abf

**Comment by peircej** [comment]
Thanks for tracking that down and letting us know (just before it got released!) as we had unwittingly turned off JS conversion of component parameters while trying to better handle someone else's issue (with their own code). We'll revert this one until we find a way that works for both!
