### ISSUE TITLE
keyboard demo failed

### ISSUE THREAD

**Issue by yuewu57** [psychopy/psychopy#3249]
Hi

I was trying to run the keyboard demo (the second example, i.e., example B, in https://www.psychopy.org/api/iohub/device/keyboard.html)
on Windows 10 system under Python 3.6.0 with PsychoPy (2020.2.5.post1, just updated to fix previous issue #3246), greenlet 0.4.17, **gevent-20.9.**0.

### Note example A works fine for me only example B does not work, so I guess there is something wrong with 'keyboard.waitForPresses':
------------------------------------
from psychopy.iohub import launchHubServer
from psychopy.core import getTime

io = launchHubServer()

keyboard = io.devices.keyboard
presses = keyboard.waitForPresses(maxWait=5.0)

print(presses)
io.quit()

------------------------------------

Error msgs:

r is None: ('EXP_DEVICE', 'DEV_RPC', 'Keyboard', 'getCurrentDeviceState', (), {})

------------------------------------

It might be related to my recent reported issue: https://github.com/psychopy/psychopy/issues/3248

I would appreciate your support.

Many thanks,
Yue

**Comment by peircej** [comment]
I *think* this might just be a long list of messages (from debugging?) telling you that there were not any keys pressed this frame.
