### ISSUE TITLE
Relative path for additional resources is wrong

### ISSUE THREAD

**Issue by bbonf** [psychopy/psychopy#3266]
When adding additional resources under the Online tab in the experiment settings, I get an extra '..' added to the beginning of the file path. This prevents PsychoPy from finding the resources and defining them in the JS export.

I tried manually fixing the paths in the .psyexp file but then I run into a different issue, which I didn't have time to further debug, with the fileList param being read as a string and not as a list.

**Comment by peircej** [comment]
Yes, we've seen this one and I'm working on a fix

**Comment by peircej** [comment]
Fixed in #3285

**Comment by bbonf** [comment]
Thanks for fixing this. Do you maybe know how to work around it on 2020.2.5?
