### ISSUE TITLE
sortKeys as TRUE rather than FALSE as a default for dlg

### ISSUE THREAD

**Issue by HeJasonL** [psychopy/psychopy#3279]
If I am building a task completely in builder view, I am currently unable to sort the 'Experiment Info' in the order that I've placed them in. PsychoPy currently automatically sorts them in alphabetical and/or numeric order, which seemed odd as a default. 

I had a look and the code: 

"dlg = gui.DlgFromDict(dictionary=expInfo, sort_keys=False, title=expName)"

which has sort_keys=False as a default is right, but doesn't work because sort_keys should now be sortKeys. When run with the code:

"dlg = gui.DlgFromDict(dictionary=expInfo, sortKeys=False, title=expName)"

The Experiment info is no longer sorted in alphabetical and/or numeric order. 

Thanks!

**Comment by peircej** [comment]
For context, the reason that this is True by default is that originally Python didn't support Ordered Dicts so it was either alphabetical or *random*! We used sorting to allow some sort of reason to the world! And then we kept it as the default for compatibility, but that's something I think we could change in the next major version update (where we permit changes in behaviour)

But the name aspect is surely a bug that we should fix!
