### ISSUE TITLE
Text component with empty with empty text -> issue with generated JS

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3288]
If I create a text component with an empty text, the generated JS does not give any value to the text property of the corresponding object, causing a syntax error, so the experiment won't start. Using any other text (as a single space) does not cause this issue.

**Comment by TEParsons** [comment]
Got a fix for this in already :) A few people on the forum were having this issue. It's in Master but not .5 (I thought it was so I'll have to backtrack on some forum responses...), so will make a point to include it in .6
