### ISSUE TITLE
Extending BinocularEyeSampleEvent for Gazepoint GP3 HD

### ISSUE THREAD

**Issue by PanBartosz** [psychopy/psychopy#3294]
Hello! I plan to  extend capabilities of Gazepoint GP3 support in iohub/psychopy.
I think it would be great to include in BinocularEyeSampleEvent:
1. Pupil diameter im meters (LPUPILD and RPUPILD parameters in Open Gaze API)
2. Best POG (BPOGX and BPOXY in Open Gaze API)
If I understand relevant code correctly in order to do that i need to:
1. Modify `BinocularEyeSampleEvent` to include these measures.
2. Modify `_parseSampleFromMsg` to parse these measures from message from the eyetracker
Am I correct? If yes, is there a chance to include my improvements in the upstream?
Kind regards,
Bartosz Maćkiewicz

**Comment by peircej** [comment]
closed by #3295
