### ISSUE TITLE
2020.2.6 crashes upon startup on macOS Big Sur

### ISSUE THREAD

**Issue by trettenbrein** [psychopy/psychopy#3304]
Hi all,

I just updated my laptop to macOS Big Sur and an no longer run PsychoPy. Upon startup, the latest version for Mac (2020.2.6) crashes with the following error message:

> Traceback (most recent call last):
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/__init__.py”, line 378, in __getattr__
> AttributeError: ‘NoneType’ object has no attribute ‘_create_shadow_window’
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File “/Applications/PsychoPy.app/Contents/Resources/__boot__.py”, line 498, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/__boot__.py”, line 476, in _run
>   File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 104, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 100, in main
>   File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 28, in start_app
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py”, line 226, in __init__
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py”, line 262, in onInit
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/__init__.py”, line 7, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/builder.py”, line 46, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/dialogs/__init__.py”, line 28, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/validators.py”, line 27, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/window/__init__.py”, line 1896, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/__init__.py”, line 384, in __getattr__
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/__init__.py”, line 100, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/lib.py”, line 141, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/lib_agl.py”, line 49, in <module>
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/lib.py”, line 118, in load_library
>   File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/lib.py”, line 286, in load_framework
> ImportError: Can’t find framework /System/Library/Frameworks/OpenGL.framework.

Interestingly, I also have an old version of PsychoPy installed (PsychoPy2_1.90.2) which still starts up without any issues, despite the system update to Big Sur.

**Comment by bf777** [comment]
I've experienced this error as well (and seen it reported a few times too) - I trust that the team is looking into this issue.

**Comment by peircej** [comment]
I did reply to this version of the report on the repo https://discourse.psychopy.org/t/psychopy-on-big-sur-on-mac/18095

The issue ultimately comes down to Pyglet not knowing that Apple has changed its directory structure. I've now got a Big Sur virtual machine set up to work on it (I'm not going to upgrade my actual development machine for fear we'll break PsychoPy for everyone else!) but, of course, anyone else that can chip in and work on it is a bonus!

**Comment by trettenbrein** [comment]
My apologies, I only searched the bug tracker here before reporting the issue. Thanks for looking to into this so promptly! I just tried to run the 2020.2.7rc1 version and can confirm that the GUI works on Big Sur (MBP 15", Mid 2015) yet experiments do not run terminating with the same error message already discussed in the thread you linked to above.

**Comment by peircej** [comment]
@trettenbrein no worries - this one does warrant being here to keep track of.

OK, there's now a test release availabe that I think works fine on Big Sur on everything except for the new TextBox (I have the fix for that implemented as well but it requires rebuilding the binaries)

Hopefully 2020.2.7 final will be out this afternoon with full Big Sur support back in

https://github.com/psychopy/psychopy/releases/tag/2020.2.7rc3

for reference, the things that needed fixing:
- updated Pyglet to 1.5.11 to get rid of OpenGL loading error
- switched TextBox to use pyglet.gl instead of OpenGL.GL (because pyOpenGL isn't fixed for Big Sur)
- upgraded Python to 3.6.8 to get rid of CoreFoundation loading error

**Comment by peircej** [comment]
2020.2.8 is now out and I believe it works fine with Big Sur but let me know if you have any further issues! 🚀
