### ISSUE TITLE
Possible bugfix for unhandled internal syntax error when exporting JS?

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3313]
One of our forum participants applied a fix for an issue they discovered. Might this be useful for the psychopy library?
https://discourse.psychopy.org/t/unhandled-internal-error-syntaxerror-invalid-syntax/16700

**Comment by TEParsons** [comment]
I remember this bug when we were in the run up to 2022.1.0, it's (so far as I can tell) fixed now - essentially the transpiler was assuming any expression without a left-hand target was a comment
