### ISSUE TITLE
confusing warning messages

### ISSUE THREAD

**Issue by hsogo** [psychopy/psychopy#3320]
I'm updating my PsychoPy Builder tutorial and noticed that the latest Builder (2020.2.8) show somewhat confusing warnings.
Firstly, if we use `FINISHED` in **start** and **stop** properties as a part of condition, Builder says "Variable name $FINISHED is in use (by PsychoPy module). Try another name". 
![4](https://user-images.githubusercontent.com/2094930/100316846-ab798a80-2ffe-11eb-967e-7b087d357692.png)

Next, if we have single key name in **Allowed keys$** of Keyboard component, Builder says "Variable name $\_\_doc\_\_ is in use (by Psychopy module). Try another name)".
![5](https://user-images.githubusercontent.com/2094930/100316851-ad434e00-2ffe-11eb-9b50-6d29c85b6a82.png)

Although they settings work as intended when experiment is executed, these warnings are very confusing, I think.

**Comment by peircej** [comment]
Todd could you look into this one (Maybe with git bisect to track back the change)? Maybe it was the change to use safe eval (from ast lib) rather than literally doing eval.

**Comment by hsogo** [comment]
I run git bisect and found that the phenomenon started with c1305d0430e068e628ee3e4d99d00c69afdedd67.

**Comment by TEParsons** [comment]
I've put in a PR to address the first instance, but the second appears to be a problem only with the standalone, looks like something we've done on Master and not added to the release fixes it. I'll try and track that down :)
