### ISSUE TITLE
TypeError: input.matchAll is not a function

### ISSUE THREAD

**Issue by wakecarter** [psychopy/psychopy#3323]
Experiments which previously worked are now failing on some browser/device combinations.

I'm using Chrome on an iPhone 6.

For example https://run.pavlovia.org/Wake/emotional-stroop/html/ works on my touchscreen laptop (in Chrome) but not on my iPhone (same error in Chrome and Safari) where it worked a fortnight ago in both.]]

Links 

https://discourse.psychopy.org/t/error-input-matchall-is-not-a-function/18186

https://discourse.psychopy.org/t/online-experiment-not-working-consistently-on-different-computers/18034

https://discourse.psychopy.org/t/severe-memory-leak-issue-for-all-browsers-task-crashes-for-the-majority-of-participants/17632/16

**Comment by thewhodidthis** [comment]
Hi @wakecarter, thanks for flagging, this is in fact a PsychoJS issue https://github.com/psychopy/psychojs/issues/226
