### ISSUE TITLE
Textbox input is not displayed, Regarding #3326

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychopy#3328]
Now 2020.2.9. can save the unicode text input properly, without any error. However it doesn't shows any text in textinput2 box contents even english one with Arial font setting, including the default text before any input.  
Would you check it please?
![100461619-63e12480-310c-11eb-8c29-f5c3bff1bfed](https://user-images.githubusercontent.com/28276515/100562060-d6652680-32fd-11eb-877f-eebd80f56c37.png)

**Comment by peircej** [comment]
OK, fixed in #3330 
I'll build a new release shortly (this week)

**Comment by iPsych** [comment]
@peircej Thanks.
I put the files manually and tested. Now the text visible but not editable again...

**Comment by peircej** [comment]
Hmm, could you share the script that isn't working for you so I can try and recreate. It's working for me here using the demo code at https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/stimuli/textbox_editable.py

**Comment by iPsych** [comment]
@peircej Hi,
Actually I used builder. Below I Attach the psyexp file.
Maybe you should change font (AppleGothic to Arial) for english only system.
[textbox_test.psyexp.zip](https://github.com/psychopy/psychopy/files/5624341/textbox_test.psyexp.zip)

**Comment by peircej** [comment]
For me your experiment is working (on a mac) with the new relase 2020.2.10

thanks for your patience
