### ISSUE TITLE
encoding parameter causes crash when using Python 3.9

### ISSUE THREAD

**Issue by dschreij** [psychopy/psychopy#3340]
In Python 3.9, the `encoding` kwarg of `json.loads` is removed, see https://docs.python.org/dev/whatsnew/3.9.html#removed:

> The encoding parameter of json.loads() has been removed. As of Python 3.1, it was deprecated and ignored; using it has emitted a DeprecationWarning since Python 3.8. (Contributed by Inada Naoki in bpo-39377)

This causes a crash because the encoding parameter is passed to json_tricks in https://github.com/psychopy/psychopy/blob/master/psychopy/monitors/calibTools.py#L446
which forwards it to `json.loads` 

```python
  ...
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/site-packages/json_tricks/nonp.py", line 266, in load
    return loads(string, preserve_order=preserve_order, ignore_comments=ignore_comments, decompression=decompression,
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
I think this parameter can be safely removed for Python 3, since it is a dud anyway, but you may want to retain it for Python 2.

**Comment by tirkarthi** [comment]
I have created https://github.com/psychopy/psychopy/pull/3343 as a potential fix
