### ISSUE TITLE
TextBox component missing JS multiline option for proper sizing in height

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychopy#3352]
As it happens, when translating for JS, a given `TextBox` instance needs to be declared as `multiline` to enable height adjustments.

Context:
[discourse.psychopy.org/t/16870 &rsaquo;](https://discourse.psychopy.org/t/16870)

Example:
[run.pavlovia.org/thewhodidthis/textbox &rsaquo;](https://run.pavlovia.org/thewhodidthis/textbox/)

**Comment by peircej** [comment]
This is going to be easy to add. Can you think of any occasions where it would be a bad thing? I'm wondering whether we set this in the Builder dialog box as a tick-box or whether we just assume multi-line is true always

**Comment by thewhodidthis** [comment]
Should be OK if we keep [multi-line off by default in PsychoJS](https://github.com/psychopy/psychojs/blob/master/js/visual/TextBox.js#L152) I believe

**Comment by peircej** [comment]
I was more thinking the opposite. Is there a time when anyone really needs multiline to be off? They specify the size of the box and then the assumption would be that multiple lines are possible. So I think default should be multiline=true. I was wondering if we _ever_ need multiline=false.
