### ISSUE TITLE
PsychoPy doesn't start on macOS after installing via conda-forge

### ISSUE THREAD

**Issue by cbrnr** [psychopy/psychopy#3362]
I followed the [instructions to install PsychoPy with `conda`](https://www.psychopy.org/download.html#conda) on macOS Big Sur, but PsychoPy doesn't start. A blank icon pops up in the dock, but then nothing happens. When I force quit with Ctrl+C, I get the following messages (pointing to an issue with subprocess communication that somehow fails):

```
Traceback (most recent call last):
  File "/opt/anaconda/envs/psychopy/bin/psychopy", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 93, in main
    stderr=True)
  File "/opt/anaconda/envs/psychopy/lib/python3.6/site-packages/psychopy/core.py", line 162, in shellCall
    stdoutData, stderrData = proc.communicate(stdin)
  File "/opt/anaconda/envs/psychopy/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/anaconda/envs/psychopy/lib/python3.6/subprocess.py", line 1534, in _communicate
    ready = selector.select(timeout)
  File "/opt/anaconda/envs/psychopy/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

The standalone version does work though.

**Comment by bollaking** [comment]
Have you tried clicking on the icon in the application bar?  I have noticed that on start up when launching from the terminal the app seems to hang... but if you click on the icon the flash screen appears and everything runs as normal

**Comment by cbrnr** [comment]
That doesn't work unfortunately. Nothing happens if I click on the icon.

**Comment by peircej** [comment]
@bollaking The thing with the dock icon is a known issue that I don't understand -  it launches fine from the terminal but when I bundle it into an Apple app bundle it does this strange thing pausing in the dock. I suspect it's somehow due to the gatekeeper but not sure what exactly.

@cbrnr I'm afraid I don't know about the issue you're having - looks like a conda thing. I wonder if it's an issue with the pythonw setting. That behaves strangely on some python installations. On Windows, calling a script with simple python means you get a commandline window in the background, and pythonw prevents that. But on mac, what happens with/without the w is unspecified and variable.

**Comment by cbrnr** [comment]
Yes, I've always had problems with conda running GUI apps (that's the main reason why I'm not using it myself). However, I thought that this `python`/`pythonw` business was solved because it is now just a symbolic link started from an app bundle (so at least the Python interpreters are identical, previously `python` would be newer than `pythonw` in general). On macOS, executables accessing the GUI need to be started from an app bundle, that's what `pythonw` is supposed to be doing (the proper solution is to build Python as a framework, which Homebrew and the official Python both do).

Can someone else confirm that PsychoPy works/doesn't work with conda on macOS (Big Sur)?

**Comment by isolver** [comment]
Same issue as @cbrnr when running with anaconda python3.6 on macOS Catalina. Also occurs if I try to start the application using:

```
cd [path_to_psychopy_source]
python psychopy/app/psychopyApp.py
```

Running psychopy coder demo's works fine though.   

Also, no issue running `psychopyApp.py` on Windows 10 with anaconda python3.6.

**Comment by angoodkind** [comment]
> Have you tried clicking on the icon in the application bar? I have noticed that on start up when launching from the terminal the app seems to hang... but if you click on the icon the flash screen appears and everything runs as normal

This also works with the standalone version.

**Comment by isolver** [comment]
>Have you tried clicking on the icon in the application bar? I have noticed that on start up when launching from the terminal the app seems to hang... but if you click on the icon the flash screen appears and everything runs as normal

This does not work for me when using anaconda, but does when starting the standalone app. When using anaonda waited 5 minutes and clicking on the python icon in the app bar does nothing I can see. 

When ctrl+c the terminal, the keyboard interupt printed this stack trace: 

```
(psychopy) sol@MacBook-Pro psychopy % python ./psychopy/app/psychopyApp.py 
^CTraceback (most recent call last):
  File "./psychopy/app/psychopyApp.py", line 104, in <module>
    main()
  File "./psychopy/app/psychopyApp.py", line 93, in main
    stderr=True)
  File ".../psychopy/psychopy/core.py", line 162, in shellCall
    stdoutData, stderrData = proc.communicate(stdin)
  File ".../anaconda3/envs/psychopy/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File ".../anaconda3/envs/psychopy/lib/python3.6/subprocess.py", line 1534, in _communicate
    ready = selector.select(timeout)
  File ".../anaconda3/envs/psychopy/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

So I wonder if it is hanging while waiting for a subprocess to start?

**Comment by hoechenberger** [comment]
I just set up PsychoPy on Big Sur and the app starts without any issues. Here's what I did:

```
mamba create -c conda-forge -n psychopy psychopy
conda activate psychopy
pip install psychtoolbox
psychopy
```
Had to wait a bit (30 secs? a minute?), but then the GUI started up successfully:

<img width="1193" alt="Screen Shot 2021-05-14 at 09 38 35" src="https://user-images.githubusercontent.com/2046265/118237972-2abd2680-b498-11eb-9ef2-0ef7582176be.png">

This is with macOS 11.3.

**Comment by cbrnr** [comment]
Yes, you're right! After half a minute the GUI starts successfully (`pip install psychtoolbox` isn't even necessary).

**Comment by hoechenberger** [comment]
Great! For me it's only the first startup that takes so long, subsequent launches are much faster.

**Comment by peircej** [comment]
What's this `mamba` business?! Too many snakes! My head's full! 😉

**Comment by hoechenberger** [comment]
> What's this `mamba` business?! Too many snakes! My head's full! 😉

🐍 

It's a faster re-implementation of `conda` :) It typically solves the dependency tree in much less time!

https://github.com/mamba-org/mamba#the-fast-cross-platform-package-manager
