### ISSUE TITLE
Installation error at 'Collecting opencv-python' get_requires_for_build_wheel

### ISSUE THREAD

**Issue by paulavillafulton** [psychopy/psychopy#3388]
pip --version: 20.3.3
Python --version: 2.7.17
Linux 18.04

when I run pip install psychopy in cmd I get the following error. I have looked it up and cannot find anything. I tried with python 3 and separately installing opencv-python-4.3.0.38 but no luck so far! 

Thanks for any tips. 

![image](https://user-images.githubusercontent.com/56651907/103765251-26ca5500-501d-11eb-9e96-4eceb15d0cd9.png)

**Comment by peircej** [comment]
To me this looks like an issue upstream in the pip install for opencv, which is outside what we can do. If `pip install opencv-python` on its own fails then I think we can't help very much there. That said, you might well not need opencv for your experiment (it is used for one of the movie backends but not MovieStim3 which we would recommend anyway). Try commenting it out in the requirements file and trying the install of psychopy again.

**Comment by paulavillafulton** [comment]
Thank you for your rapid response. Yes, you are right, that is the issue. I was able to resolve it using the answer here (https://stackoverflow.com/questions/63346648/python-2-7-installing-opencv-via-pip-virtual-environment), which indicates the following:


Python 2.7 is not supported anymore in opencv-python-4.3.0.38 the support was dropped since 4.3.0.36, see this issue.

The workaround I found was to install opencv-python version 4.2.0.32 (which is the latest supported for Python 2.7, see this for all releases) like this:

pip2 install opencv-python==4.2.0.32



I hope this does not cause any issues later on when using Psychopy.. 

Best,

**Comment by peircej** [comment]
I hadn't noticed you wrote you're using Py2.7
I would recommend moving to Py3.6 or 3.7 when you get a chance. We've stopped testing PsychoPy on py2.7 now and I think we'll be fully incompatible with that version in PsychoPy 2021.2 (mid-2021)
