### ISSUE TITLE
A problem readme files if MarkdownIt not installed

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3391]
This came from the Navon demo task with MarkdownIt missing. I wonder if there was a removal of \n somewhere when markdown support was added?

![image](https://user-images.githubusercontent.com/380582/103944331-62ebdb80-512b-11eb-8d36-8f362ea3b87e.png)

**Comment by TEParsons** [comment]
Ah I see the problem - if MarkdownIt is not installed, then it defaults to just printing the original text. I was thinking that would be the same as befpre, but it prints it as undecorated HTML, meaning no line breaks. I can solve this specific problem by a straight replacement of "/n" for "<br>", but could we add MarkdownIt to the project requirements?

**Comment by TEParsons** [comment]
Didn't occur to me that html would be interpreted by GitHub in the comment :') I meant to say 
```
<br>
```
