### ISSUE TITLE
$ in Keyboard Comp keylist causes syntax error

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3392]
As shown in the attached study, if the key list is set to be $keys it will cause an error because the $ is not needed (but we used to be more tolerant of that issue)

[keysErr.psyexp.zip](https://github.com/psychopy/psychopy/files/5784045/keysErr.psyexp.zip)

**Comment by peircej** [comment]
Possibly the issue here was that we needed to drop support for the $ in a this-is-code parameter, but if that's the case we at least need an Alert to warn people that this param looks like it has a $ and shouldn't do

**Comment by TEParsons** [comment]
Found it! Problem is that the code compiling for keyboard component does a lot of stuff manually so it skips things like the `__str__` overload for list params, so the dollar doesn't get stripped like it does in other params. Putting in a fix for this specific issue, but I think we can actually cut out a lot of this code as it's already handled by param printing. I'd like to tidy it up for the summer release.

**Comment by peircej** [comment]
Mouse/keyboard code writing is very tricky to get right - we've had *many* issues with it in the past. Needs to be handled with **extreme** caution
