### ISSUE TITLE
Debug messages printed when starting psychopy app on linux

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3420]
OS: Mint Linux 18.3
Python: Anaconda Python 3.8, with [wxPython-4.1.1-cp38-cp38-linux_x86_64.whl](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl)
Psychopy: 2020.2.10

Starting the psychopy app on linux prints these errors / warnings as the app starts up:

```
(base) user@mint18-3 ~/Documents/GitHub/psychopy/$ psychopy
10:26:04 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:26:04 AM: Debug: Adding duplicate animation handler for '1' type
10:26:04 AM: Debug: Adding duplicate animation handler for '2' type
10:26:04 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
10:26:04 AM: Debug: Adding duplicate animation handler for '1' type
10:26:04 AM: Debug: Adding duplicate animation handler for '2' type
10:26:04 AM: Debug: "Shift+Tab" is not supported as a keyboard accelerator with GTK
```

**Comment by peircej** [comment]
Yes, I'm afraid these ones have me baffled. They appear to be harmless and probably some sort of issue under the hood in WX but a bit annoying

**Comment by isolver** [comment]
closing, we can live with annoying for now.
