### ISSUE TITLE
App crashes when Coder context dlg cannot find context

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#3427]
At least that's what I think it is - if you open any file in Coder, type a name which doesn't exist and then a full stop, it crashes.

**Comment by mdcutone** [comment]
@TEParsons have you had time to look into this? Seems like something I can handle.

**Comment by TEParsons** [comment]
I've not, so yes please do!

**Comment by mdcutone** [comment]
How do I replicate this? I might be missing how this works.

**Comment by mdcutone** [comment]
Okay I figured this one out. I'll put a patch out.
