### ISSUE TITLE
ensure pyglet < 1.5 is used

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3429]
If pyglet 1.5.x is installed on win10 with python 3.6, annoying warning messages get printed 
```
pyglet\media\codecs\wmf.py:838: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
```

and, iohub eye tracking calibration freezes with this error being printed:

```
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
```

**Comment by isolver** [comment]
@peircej, can I change the setup.cfg to pyglet==1.4.1 for now?

**Comment by peircej** [comment]
yes, or just pyglet<1.5 I think

**Comment by isolver** [comment]
done in setup.cfg, still need to do in anaconda env yml

**Comment by isolver** [comment]
Looks like pyglet 1.5.1x is needed for macOS Big Sur, need to use 1.4.x on windows and linux and 1.5.11 on macOS.
Is there a way to tell pip to install 1.4.11 if it is macos version <= catalina, otherwise install 1.5.1x?

**Comment by danielshub** [comment]
Is pyglet < 1.5 still a hard requirement on Linux? It seems like things work with pyglet 1.5.24 on Arch Linux. Is there a unit test (or some other way) to check if the issue still exists?
