### ISSUE TITLE
Editable TextBox2 issues if formating is used.

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3436]
Run the demos/coder/stimuli/coder_editable.py example (using the latest master branch source) and press tab to try to make the formatted psychopy test string editable. Error will occur:

```
Traceback (most recent call last):
  File "textbox_editable.py", line 67, in <module>
    win.flip()
  File "psychopy\psychopy\visual\window.py", line 1026, in flip
    thisStim.draw()
  File "psychopy\psychopy\visual\textbox2\textbox2.py", line 551, in draw
    self.caret.draw()
  File "psychopy\psychopy\visual\textbox2\textbox2.py", line 848, in draw
    gl.glVertex2f(self.vertices[0, 0], self.vertices[0, 1])
  File "psychopy\psychopy\visual\textbox2\textbox2.py", line 946, in vertices
    chrVerts = textbox.vertices[range((ii-1) * 4, (ii-1) * 4 + 4)]
IndexError: index 1212 is out of bounds for axis 0 with size 1176
```

The error seems to be from the formating using in the txt2 of the demo. remove the \<b> etc. from the string and tabbing between the textbox2 stims works.

**Comment by isolver** [comment]
Fixed original crash. However, need to review how formating is implemented because I'm not sure how well it works in terms of editing the text after intial draw. For example, deleting a char does not take into account formatting.

I also get drawing gliches / artifacts sometimes when deleting text from a textbox with format text. Will try to attach screen shot.

**Comment by isolver** [comment]
So remaining issues to look into:
- [ ] Drawing glitch issue (seem on win10 and macos
- [ ] Deleting text in the editable text box sometimes causes the caret to move to the wrong location.
- [ ] Text line wrapping functionality should also be checked again.

**Comment by isolver** [comment]
Fixed, but not optimized. Should create a new issue for that.

**Comment by isolver** [comment]
Notes on current text formating limitations:

1. Text formating must be valid. Code assumes well structured styling tags in text
2. No way to display formatted tag text when setting text. Should add escape char detection.
3. Formatting gfx could be improved, or we could use the bold and italic font faces in ttf file instead of opengl manipulations.

**Comment by isolver** [comment]
Finally, note that get /set of TextBox2.text is a little different than normal when formatting is used:

```
# Setting text with styling tags are converted to text style gfx changes  
textbox2.text="The word <b>bold</b> is styled bold."

# Getting textbox2.text returns only the visible / displayed text chars.
print(textbox2.text)
```

prints

`The word bold is styled bold.`
 
This makes sense from a usability POV to me, but thats me.

Maybe we should add a method to textbox2, say `getTextWithTags`, that returns the text with formatting tags included, even if the text has been edited by user. Using the above example, `textbox2.getTextWithTags()` would return `'The word <b>bold</b> is styled bold.'`


@peircej, what do you think? Should I create some new issues around this?

**Comment by peircej** [comment]
I think the getter for text should return the full text, including formatters. My guess is that the fields are there as non-printing unicode chars that need converting back (although it's a little surprising that this is stored internally as the text rather than being included only in the rendering step)

**Comment by isolver** [comment]
> My guess is that the fields are there as non-printing unicode chars that need converting back

Formatting is now completely removed from the text and formating info is stored in a seperate list. Otherwise text editing operations become a nightmare.

In editing situations, researchers will want to get the text that was entered by the participant, not any format stuff that was never visible to the user as text.  I think we need to give access to the text both with and without formaters, Q is how. 
Could do as I suggest in earlier comment, or to get what you are suggesting, I can change it so .text returns the formatting tags, and then store the text to draw in an internal variable that can be returned using a new method like `getVisibleText()`.

**Comment by isolver** [comment]
@peircej, so I'll change it so that `textbox2.text` returns the text with formating tokens (<b>, </b>, ..) included as you suggest. I'll also add a read-only `textbox2.visibleText` property that returns only the visible / drawn text chars. Cool?

**Comment by isolver** [comment]
I've implemented the changes discussed above and committed into existing PR.

**Comment by peircej** [comment]
sounds good
