### ISSUE TITLE
retina display iohub calibration gfx issue 

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3441]
If a retina display is being used, iohub draws calibration targets at wrong positions, at least for eyelink implementation.  Check tobii if possible (the Tobii T120 has a built in display so I'm not sure I can test myself)

**Comment by isolver** [comment]
Confirmed it is a retina display issue. No issue with target positions when using same macbook pro connected to / using an external monitor only (run with macbook closed) and external keyboard / mouse.

**Comment by mdcutone** [comment]
We tried to generalize our handling of retina displays to handle HiDPI at some point. If you need the "true" window backbuffer size for some operation, you can access the Window's 'frameBufferSize' attribute instead of `size` to get it.

**Comment by isolver** [comment]
@mdcutone, on my macbookpro 13" with retina display both win.size and win.frameBufferSize are returned as [2880 1800], while pyglet says the window size is 1440, 900. If I create a fullscreen window using garbage size like 100,100, psychopy prints:

```
User requested fullscreen with size [100 100], but screen is actually [1440, 900]. Using actual size
```

And it seems like stim .pos should be specified using the 1440,900 pixel coord space to be placed correctly.

Just checking this is working as expected. Thanks.

**Comment by mdcutone** [comment]
Might have got it mixed up, `frameBufferSize` for actual back buffer size, and `clientSize` for reported window dimensions.

**Comment by isolver** [comment]
Should win.size always == clientsize so the logic is consistent across OS /
display type? Right now win.size == framebuffersize on macos with retina
but win.size == client size on win10 and linux. The latter is correct IMO.

**Comment by isolver** [comment]
will create seperate issue about win.size vs clientSize vs frameBufferSize
