### ISSUE TITLE
Circle stim now requires lineColor or fillColor to be displayed

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3448]
Previously you could draw a circle with 'default' colors (black line, no fill) by using:

```
visual.Circle(win, radius=300, units='pix')
```

However using latest master source the circle not being shown. For the circle to be displayed either `lineColor` and/or `fillColor` must be provided as a param.

Should lineColor and fillColor be made required params for Circle, or can it use default colors if none are provided?

**Comment by mdcutone** [comment]
Not sure how the system works now. There still is a `color` and `colorspace` argument, I thought setting that would set both line and fill colour to provide backwards compatibility.

**Comment by peircej** [comment]
oops, accidental close. I agree with above. color and colorSpace should set both line and fill

**Comment by TEParsons** [comment]
I see the problem - it is setting default colours, it's just that the default is None, i.e. transparent :P color and colorSpace already do work like that, but it checks whether fillColor and lineColor are set by comparing them to None, so adding in a non-None default for fillColor and lineColor would stop that working...  I think setting color then overwriting with fillColor and lineColor is a better way of doing it, so I'll switch the logic around and set the default to be None fill + 'black' line
