### ISSUE TITLE
TextBox exception when loading some font files on macos or linux

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3449]
Running any of the demos/coder/stimuli/textBoxStim examples on macos catalina fails for me with the following error.

```
Traceback (most recent call last):
  File "textbox_simple.py", line 28, in <module>
    units='norm',
  File "psychopy/psychopy/contrib/lazy_import.py", line 120, in __call__
    return obj(*args, **kwargs)
  File "psychopy/psychopy/visual/textbox/__init__.py", line 384, in __init__
    self._font_name, self._font_size, self._bold, self._italic, self._dpi)
  File "psychopy/psychopy/visual/textbox/fontmanager.py", line 220, in getGLFont
    font_atlas.createFontAtlas()
  File "psychopy/psychopy/visual/textbox/fontmanager.py", line 390, in createFontAtlas
    face.load_char(uchar, FT_LOAD_RENDER | FT_LOAD_FORCE_AUTOHINT)
  File "/site-packages/freetype/__init__.py", line 1455, in load_char
    if error: raise FT_Exception( error )
freetype.ft_errors.FT_Exception: FT_Exception:  (unknown error)
```
The same error occurs whether I use my own Python env or the last official PsychoPy standalone installer for macos.

- Win10 seems fine.
- TextBox2 demo runs.

**Comment by isolver** [comment]
To debug, I added a `try: except:` around the code that was failing and printed out information about the font glyph being loaded. It looks like it is failing to load 1 glyph from the two font files it can find:

```
Building atlas for font:  {'path': '/System/Library/Fonts/SFNSMono.ttf', 'family_name': b'.SF NS Mono', 'style_name': b'Light', 'charmaps': ['FT_ENCODING_UNICODE', 'FT_ENCODING_UNICODE'], 'num_faces': 1, 'num_glyphs': 1625, 'units_per_em': 2048, 'monospace': True, 'charmap_id': 1, 'label': "b'.SF NS Mono'_b'Light'", 'id': "b'.SF NS Mono'_b'Light'"}

Warning: Could not load font face for charcode / uchar / category:  8377  /  ₹  /  Sc

Building atlas for font:  {'path': '/System/Library/Fonts/SFNSMono.ttf', 'family_name': b'.SF NS Mono', 'style_name': b'Light', 'charmaps': ['FT_ENCODING_UNICODE', 'FT_ENCODING_UNICODE'], 'num_faces': 1, 'num_glyphs': 1625, 'units_per_em': 2048, 'monospace': True, 'charmap_id': 1, 'label': "b'.SF NS Mono'_b'Light'", 'id': "b'.SF NS Mono'_b'Light'"}
Warning: Could not load font face for charcode / uchar / category:  8377  /  ₹  /  Sc
1.1825 	WARNING 	Monitor specification not found. Creating a temporary one...
```

Not sure why it is failing on that one. It is not the last glyph in the map or anything and others are loaded fine after.

**Comment by isolver** [comment]
Other notes / issues:

- [ ] Looks like there might be some P3 related cleanup to do - some font info is being saved with "b'xxx'" - the byte string identifier b'xx' should not be part of the font info values.
- [ ] textbox drawing is totally messed up on macos with retina display.

**Comment by HinTak** [comment]
The pull looks wrong. If freetype-py cannot load SFNSMono.ttf , and emits an "unknown error" for exception, that's a freetype-py problem and perhaps even a freetype problem. It is possible that the font itself is unusual - afaik it is Apple's own San Francisco Mono, built for newer Apple OS/UI, and hence they don't have to make it loadable by 3rd-party font loader, though that's rare.

**Comment by HinTak** [comment]
I don't know what version of freetype you are using, but see if you can reproduce with current. Here is a reasonably recent build: https://github.com/HinTak/Font-Validator/tree/master/bin/Darwin

**Comment by isolver** [comment]
This occurs on macos and on linux (mint 19). TextBox now just skips a glyph if loading it raises an error, printing a warning message. Should still investiagte root issue.
