### ISSUE TITLE
elementArrays.py demo exception

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3450]
Running demos/coder/stimuli/elementArrays.py using the latest master branch source gives:

```
Traceback (most recent call last):
  File "elementArrays.py", line 85, in <module>
    globForm.draw()
  File "psychopy/psychopy/visual/elementarray.py", line 541, in draw
    RGBAs[v,:] = col.render('rgba1')
IndexError: index 500 is out of bounds for axis 0 with size 500
```

**Comment by mdcutone** [comment]
Is this even going to work correctly, seems like it would just set all the elements to the same color. This is why the original `colorspacetools` functions were all vectorized and why they should remain that way.

**Comment by isolver** [comment]
@TEParsons, is this something you can look into or should it be assigned to someone else. Not sure I'm the best person for this one. Thanks.

**Comment by TEParsons** [comment]
I'll have a look into this :) and @mdcutone it currently creates a list of Color objects from a list of color values, so `col` in the error above is a single value from that list as it's being iterated through

**Comment by mdcutone** [comment]
This should be fixed when the vectorized color class is pulled in.
