### ISSUE TITLE
Coder frame size is small on fresh install

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3472]
When opening coder for the first time after a fresh install (or deleting all the prefs) it has a uselessly small frame size. Sizes are persistent across application startups when the user manually sets the size of the frame and panels, so that works at least. However, I cannot figure out why no matter what I set the initial frame size to, it gives me some completely different result.

**Comment by peircej** [comment]
Fixed in 59869dee78d07c7f69b4a089b15901995ac775d9
