### ISSUE TITLE
Some Windows standalone python packages need to be updated

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3504]
Some of the python packages used by the Windows standalone installer should be upgraded. This list maybe expanded as more testing is done.

- [x] `python-vlc` : vlcmoviestim and moviestim2 demo's fail because of incompatibilities with version of python-vlc being used.
- [x] `pyglet`: shipping with 1.3.x, should upgrade to 1.4.x

It might even be simplest to uninstall all the psychopy dependencies and reinstall with the latest (supported) versions in the python env being packaged with the windows standalone installer.

**Comment by peircej** [comment]
I don't fancy upgrading the entire dependency stack just before a release. I've updated:
- python-vlc to 3.0.1115 
- pyglet to 1.4.11 on Win (and it was already 1.5.10 on macOS)

**Comment by isolver** [comment]
Thank you.
