### ISSUE TITLE
Rating slider instruction (scale description) does not work

### ISSUE THREAD

**Issue by Reoge** [psychopy/psychopy#3576]
The problem is with Buider (2020.2.10).

If Rating slider component used with "Lowest value", "Highest value" and "Scale description", than scale has instruction (Scale description). Builder effectively creates this code:
rating = visual.RatingScale(win=win, name='rating', marker='triangle', size=1, pos=[0.0, -0.4], low=1, high=7, labels=[''], **scale='SOME SCALE INFO'**)

But if "Category choices" are used than instruction is not present, because "scale" argument is omitted:
rating = visual.RatingScale(win=win, name='rating', marker='triangle', size=1, pos=[0.0, -0.4], **choices=['1', '2', '3', '4', '5', '6', '7']**, tickHeight=-1)

**Comment by TEParsons** [comment]
We're in the process of deprecating RatingScale and replacing it with Slider, so in this case it's better to make a Slider whose style is "rating", and then add a Button component and a TextBox component for the done button and scale info respectively.
