### ISSUE TITLE
Unpacking demos creates unwanted folders, but only in compiled app

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#3602]
Demos unpack as intended when using the app from GitHub:
![Screenshot (2)](https://user-images.githubusercontent.com/25686106/108695779-98d8f980-74f8-11eb-9396-f72976a37410.png)
![image](https://user-images.githubusercontent.com/25686106/108695804-9d9dad80-74f8-11eb-82a3-8206f969add7.png)

but when unpacking them in the latest version (installed rather than pulled) I get this:
![Screenshot (4)](https://user-images.githubusercontent.com/25686106/108696247-33393d00-74f9-11eb-8e39-1669565545c3.png)
![image](https://user-images.githubusercontent.com/25686106/108696089-fc632700-74f8-11eb-8ca0-a3eaecc1e385.png)

**Comment by peircej** [comment]
I'll look at this. They're probably left over files on the dev machine that aren't cleared away by git

**Comment by peircej** [comment]
I believe this is fixed in 2021.1.2
