### ISSUE TITLE
Readme.txt window appears to have lost Ctrl-I/Cmd-I shortcut key to hide

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3604]
Toggling the readme page for a Builder experiment no longer works (at least on mac).

Cmd-I will bring up the page but pressing again no longer gets rid of it.

I guess a new class has been created for the new markdown-supported frame, and this doesn't have the shortcut keys attached?

**Comment by TEParsons** [comment]
Yep that's exactly it, I actually didn't know about this shortcut so I didn't add it back in... Can do now!
