### ISSUE TITLE
Look at improving TextBox2 draw performance.

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#3612]
Try to improve the draw time performance of `psychopy.visual.TextBox2`, in particular when text has not changed since last flip(). Running the [demos/coder/stimuli/compare_text_timing.py](https://github.com/psychopy/psychopy/blob/release/psychopy/demos/coder/stimuli/compare_text_timing.py) demo gives these results on windows 10, psychopy v2021.1.0, nvidia 1060:

```
-------Text Draw Duration Test---------

+ Draw Order: ['TextBox', 'TextBox2', 'TextStim']
+ Text Stim Char Length:         160

+ TextBox INIT Dur (sec):       1.3761405000113882
+ TextBox2 INIT Dur (sec):      1.4610392000176944
+ TextStim INIT Dur (sec):      0.22892449999926612

+ Text Change Flip Perc:        20.00
+ Total Flip Count:              600
+ Test Duration (secs):         4.029
+ FPS:                          148.938

+ Average Draw Call Durations (msec):

  Text Object           No Txt Change   Txt Change
  TextBox               0.251           1.270
  TextBox2              1.247           4.235
  TextStim              0.472           7.119
```

TextBox2 appears to be 1.5 - 2 times _faster_ than TextStim when drawing changed text.
TextBox2 appears to be 2 - 3 times _slower_ than TextStim when redrawing unchanged text.
 
Ideally TextBox2 performance would be closer to that of TextBox, which is fast but limited to using monospace fonts.

**Comment by isolver** [comment]
One option might be to use the same old school approach as the original TextBox stim but generalize it to work with any font. This is possible and the performance should end up being about the same as the current TextBox. Not saying this is the way to go, just pointing out it is an option.

**Comment by isolver** [comment]
This maybe of relevence. https://github.com/psychopy/psychopy/pull/3624#issuecomment-786617692. Not sure how much time of textbox2 settext() is spent doing text parsing / layout vs. rebuilding the vert arrays needs by draw() based on the layout. That might influence where it is worth redoing the actual drawing code vs. optimizing the text parsing wrapping.

**Comment by hsogo** [comment]
My code consists of following 4 parts.  I inserted `time.perf_counter()` to the code to to measure which part takes time.  

1.segment text at breakable point using psychopy.tools.linebreak module ([lines 579-581](https://github.com/hsogo/psychopy/blob/8bed2639c33d82eaf6cab7755966957750811716/psychopy/visual/textbox2/textbox2.py#L579))
2. get width of each segment ([lines 583-653](https://github.com/hsogo/psychopy/blob/8bed2639c33d82eaf6cab7755966957750811716/psychopy/visual/textbox2/textbox2.py#L583))
3. concatenate segments to build line ([lines 656-676](https://github.com/hsogo/psychopy/blob/8bed2639c33d82eaf6cab7755966957750811716/psychopy/visual/textbox2/textbox2.py#L656))
4. build lines ([lines 679-717](https://github.com/hsogo/psychopy/blob/8bed2639c33d82eaf6cab7755966957750811716/psychopy/visual/textbox2/textbox2.py#L679))

I ran settext() 10 times for Chinese, German, English and Japanese texts (500 characters).

```
stim_set = (
{'lang':'zh', 'font':'Noto Sans SC', 'text':text_c[:500]},
{'lang':'de', 'font':'Noto Sans', 'text':text_d[:500]},
{'lang':'en', 'font':'Noto Sans', 'text':text_e[:500]},
{'lang':'ja', 'font':'Noto Sans JP', 'text':text_j[:500]}
)

for stim in stim_set:
    print('--{}--'.format(stim['lang']))
    textbox.font = stim['font']
    result = timeit.timeit("textbox.text=stim['text']", globals=globals(), number=10)

```

The results were as follows (Windows10, Python 3.6.1, Core i7-3770).  Columns represent times consumed for 4 parts (left to right). Unit is milliseconds.  The 2nd part consumed quite a long time immediately after font was changed.  This is prominent when font was changed to Noto Sans SC and JP.  I guess it's because file of these fonts are much larger than Noto Sans.  Other than that, the 4th part took the longest time.

```
   0.23,  39.81,   0.01,   0.21    #Initialization of TextBox2: font is Noto Sans
--zh--
   2.93,1163.18,   0.13,   4.52  #font was switched to Noto Sans SC. Text was changed.
   2.91,   1.50,   0.11,   4.40
   2.91,   1.48,   0.11,   4.34
   2.89,   1.45,   0.11,   4.45
   2.89,   1.46,   0.11,   4.33
   2.89,   1.56,   0.16,   4.55
   2.98,   1.53,   0.11,   4.32
   2.98,   1.51,   0.11,   4.56
   2.89,   1.50,   0.11,   4.84
   3.26,   1.64,   0.12,   4.50
--de--
   2.48, 108.64,   0.05,   4.25  #font was switched to Noto Sans. Text was changed.
   2.62,   1.41,   0.04,   4.28
   2.47,   1.51,   0.04,   4.37
   2.43,   1.42,   0.06,   4.30
   2.43,   1.35,   0.04,   4.35
   2.45,   1.37,   0.04,   4.38
   2.44,   1.32,   0.05,   4.35
   2.50,   1.28,   0.04,   4.07
   2.47,   1.32,   0.03,   4.05
   2.64,   1.32,   0.04,   4.08
--en--
   2.54,   3.73,   0.03,   4.03  #setFont was called but font was actually unchanged. Text was changed
   2.42,   1.30,   0.03,   4.25
   2.37,   1.29,   0.03,   4.33
   2.40,   1.33,   0.03,   4.28
   2.48,   1.37,   0.03,   4.22
   2.54,   1.36,   0.04,   4.24
   2.47,   1.37,   0.04,   4.27
   2.50,   1.41,   0.04,   4.19
   2.40,   1.91,   0.06,   4.71
   2.50,   1.48,   0.06,   4.23
--ja--
   3.00, 893.34,   0.19,   4.48  #font was switched to Noto Sans JP. Text was changed.
   2.92,   1.60,   0.13,   4.18
   2.86,   1.54,   0.13,   4.09
   3.11,   1.58,   0.13,   4.11
   3.03,   1.53,   0.13,   4.17
   3.04,   1.53,   0.13,   4.16
   3.04,   1.63,   0.13,   4.31
   3.07,   1.59,   0.14,   4.34
   3.15,   1.60,   0.13,   4.47
   3.06,   1.60,   0.13,   4.37
```

**Comment by isolver** [comment]
Some _Ideas_ around the layout part

#### Where possible, use numpy arrays instead of for / while loops

Maybe we could speed things up by trying to vectorize the layout operation as much as possible. Say we keep some lookup tables (numpy arrays) about the text and glyph advance info:

- `text_ords`: array of text ord() values / lookup codes for font. 
- `font_advances`*: dict of arrays, holding advance of each char in the font, where font_advances[char_ord] = advance for char. 
- `possible_wrap_boundaries`*: array of possible valid text wrap indices in text - from the linebreak code.

\* These two arrays should only need to be created when text is set. Text 'editing' (adding / removing part of current text) should only need to update some existing arrays, not always rebuild from scratch.

Build the initial array of glyph advances for the text:

```
text_char_advances = numpy.take(font_advances , text_ords)
text_advance_accumulator  = numpy.cumsum(text_char_advances)
```

To get the array of soft / valid wrap points for each line of the text, `soft_wrap_points`, something like:

```
max_line_width = 1000 # textbox max width is 1000 pixels, just for example. 
last_wrap_index = 0  
current_line_index = 0 

# Loop through each _line_ of text.
while last_wrap_index < len(text_ords):
    # Get the char index that would be a hard wrap.
    hard_wrap_index  = numpy.searchsorted(text_advance_accumulator[last_wrap_index:],
                                                                      current_line_index*max_line_width) + last_wrap_index
    
    # Find the closest soft wrap index that is before hardwrap point. 
    # and add it to the array of soft wrap indices in text.
    soft_wrap_points[current_line_index] = numpy.searchsorted(possible_wrap_boundaries[soft_wrap_index:],
                                                                    hard_wrap_index ) + last_wrap_index
    
    last_wrap_index = soft_wrap_points[current_line_index]
    current_line_index+=1
```
It would be nice to figure a way to get rid of the `while` loop and vectorize the soft_wrap_points calculation as well, atleast it is only looping over the lines, not each char.

#### Use bold and italic font faces for \<b> and \<i> styling

Instead of using opengl to try to make text look **bold** or _italic_, use the bold and italic faces for the font. To generalize, this means supporting use of multiple font files / faces within the same textbox, which would be good anyhow. It will look better too. ;)

#### Full text layout vs Visible text layout, vs Update text layout

- Support full text layout operation as well as a text insert / delete re-layout operation. i.e. the text layout should not have to always be totally recalculated when text is just being edited for example. 
- Only layout the likely visible lines of text. Otherwise this will scale to editing large passages of text where most of the text is not even visible on screen. For example, if you have a book of text, but know at most 1000 chars can be seen in the textbox, only layout the 1000 chars, not the full book.
