### ISSUE TITLE
.xltx files seem to be excluded standalone build

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#3617]
In the repo, there are some .xltx files in the following folders:
`psychopy/experiment/form`
'psychopy/experiment`

these are the Excel templates which the Open In Excel button on `TableCtrl`s uses to make new files if none is specified, but on the standalone release these files aren't there

**Comment by peircej** [comment]
I believe this is fixed by the change to the manifest in #3646 (and the files should be in release 2021.1.2) but do check and reopen if it didn't fix it
