### ISSUE TITLE
"AttributeError: 'list' object has no attribute 'contains'" when running the posner task workshop example in 2021.1.0

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3634]
This error message came up during the workshop when a participant running PsychoPy 2021.1 tried to create a clickable button without using the button component (the old method).

```
## Running: C:\Users\****\Desktop\PsychoPy Workshop\posnerfirst\posner_lastrun.py ##
20.3468     EXP     Imported conditions.xlsx as conditions, 10 conditions, 3 params
20.3474     INFO     Loaded monitor calibration from ['2021_01_13 15:54']
20.3725     EXP     Imported conditions.xlsx as conditions, 10 conditions, 3 params
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
0.6324     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
Traceback (most recent call last):
  File "C:\Users\****\Desktop\PsychoPy Workshop\posnerfirst\posner_lastrun.py", line 209, in <module>
    if obj.contains(resp):
AttributeError: 'list' object has no attribute 'contains'
##### Experiment ended. #####
```

Seems this change breaks compatibility across versions since the rest of the workshop using the preceding version did not have this issue.

**Comment by peircej** [comment]
That looks like a bug in the user code. If `obj` is a visual stimulus and `resp` is a Mouse or a coordinate, then that code will work. In this case it looks like `obj` is not a visual stimulus but a list, so the script has failed.

Maybe `obj` has been used more than once in the experiment to define different objects (so need a better name to avoid this happening?)
