### ISSUE TITLE
Adding asarray function for time variable for JS code

### ISSUE THREAD

**Issue by yoshihiko1218** [psychopy/psychopy#3661]
Hi, I updated to latest version of psychopy and currently using builder to make task. However, when I convert the task to JS file, it make asarray outside of time variable. So it cannot be ran online since there is no asarray function in JS. I think this might be some error when converting task to JS. OR I wonder did variable usage in components changed? Thank you!
![image](https://user-images.githubusercontent.com/35363296/109966144-dde80180-7d2a-11eb-8842-19440d79313e.png)
![image](https://user-images.githubusercontent.com/35363296/109966195-ec361d80-7d2a-11eb-9eac-74d5c158c32e.png)

**Comment by peircej** [comment]
I believe this has been fixed by https://github.com/psychopy/psychopy/pull/3731
