### ISSUE TITLE
contrast property of ElementArrayStim is not working in version 2021.1

### ISSUE THREAD

**Issue by Mrswolf** [psychopy/psychopy#3714]
contrast property of **ElementArrayStim** is not working in this version.

I have seen many refactoring work about colors in #3396 and it deletes codes about contrast. I'm currently using **ElementArrayStim** with a 240Hz monitor and changing its contrast property in each frame.
Although it is possible to achieve the same effect with the new **setColors** function, I'm not sure if this would cause performance loss comparing to the old one.

**Comment by TEParsons** [comment]
This should be fixed on pulling in #4196 :)
