### ISSUE TITLE
TextStim pyglet italic/bold not working

### ISSUE THREAD

**Issue by bpinsard** [psychopy/psychopy#3716]
I was not able to make italic or bold working with TextStim with pyglet, it seems to be broken, maybe by a pyglet update.
I tried either with italic/bold boolean, or adding Italic to the font name (Palatino Linotype).
environment: ubuntu, psychopy 2021.1.3 , pyglet 1.4.11

The only way I was able to fix it was to do:
```
txt_stim._pygletTextObj.set_style('italic', True)
```
It seems that TextStim get the font for itself using `pyglet.font.load_font` (maybe to infer the bounding box??), 
https://github.com/psychopy/psychopy/blob/336cdd7dedb387566bb7fb6910bfd73f27c8265f/psychopy/visual/text.py#L279-L282

but then the italic and bold parameters are not given to `pyglet.text.Label` so pyglet has no idea.

https://github.com/psychopy/psychopy/blob/336cdd7dedb387566bb7fb6910bfd73f27c8265f/psychopy/visual/text.py#L383-L389

And it seems that adding "italic" to the font name does not help (font not found, fail and uses default silently!).

Thanks

**Comment by TEParsons** [comment]
In theory, italic and bold tags should be in the font itself, so are passed via `self.font`. If adding Italic to the font name leads to "Font not found" error, it could just be that you don't have Palatino Linotype Italic installed, so Pyglet defaults to the closest font it can find (Palatino Linotype Regular)

**Comment by bpinsard** [comment]
I do have the font installed, I think it's by default on ubuntu.
![image](https://user-images.githubusercontent.com/1155388/118147042-30a20180-b3dd-11eb-9d7a-9ef8c97c4f52.png)
Does bold/italic works for you? 

Because from the code it shouldn't, here:
https://github.com/psychopy/psychopy/blob/336cdd7dedb387566bb7fb6910bfd73f27c8265f/psychopy/visual/text.py#L383-L389
what is given to `pyglet.text.Label` is the font name (self.font, not self._font), and italic/bold is not given, so when creating the visual stimuli, pyglet has no idea it has to be bold/italic. 

Preped a PR.  solved by https://github.com/psychopy/psychopy/pull/3790
