### ISSUE TITLE
URLs in README files won't open

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3721]
[This experiment](https://gitlab.pavlovia.org/tpronk/cep_2021_april7-9_assignment_stroop/) has a README file that displays upon opening the psyexp file via builder. There are a couple of URLs in there, pointing to gitlab repos. While the URLs are valid, when I click them, PsychoPy gives an error message. For example:

PsychoPy3 Error

Unable to open requested HTML document:
https://gitlab.pavlovia.org/tpronk/tutorial_js_syntax_error

**Comment by tpronk** [comment]
I noticed that anchors to another location within a page also don't work. For example, in the README of the project below, I link to a section titled "prolific" as follows:
`[Prolific](#prolific)`
Clicking this link in gitlab takes me to the right sections, but in Builder I get "HTML anchor prolific does not exist"
https://gitlab.pavlovia.org/tpronk/demo_chaining

**Comment by TEParsons** [comment]
Looks like the default behaviour for links in a `wx.html.HtmlWindow` is to try to open them as a HTML document, which is... interesting. Thankfully a link click emits and event which we can rebind, so I've just made a function which does what we actually want and rebound to that.

**Comment by TEParsons** [comment]
Anchors probably won't work until we find a better solution than a `HtmlWindow` - I don't think they have that kind of functionality at all. 

I am looking for a better alternative anyway as I'd like to have a CSS stylesheet for each PsychoPy app theme which styles README files, even have the main two written already:
https://codepen.io/todd_parsons/pen/XWjYOgr
https://codepen.io/todd_parsons/pen/dypKwJb
