### ISSUE TITLE
builder iohub stroop_keyboard demo refers to nonexistent eyetracking

### ISSUE THREAD

**Issue by datalowe** [psychopy/psychopy#3727]
The [stroop_keyboard demo](https://github.com/psychopy/psychopy/tree/release/psychopy/demos/builder/Feature%20Demos/iohub/stroop_keyboard) instructions include this:

> To toggle gaze position visibility, press 'g'.

However, the .psyexp/.py files and the corresponding config file do not specify any eyetracker configurations. There is also no check for 'g' keypresses in the trial's code snippet (it only has `if iok.key in [u'down',u'left',u'right']:`).

Either the 'gaze position toggle' part of the instruction needs to be removed, or the experiment needs be updated so that it does include gaze measurement. If the latter is done, the experiment folder would probably need to be renamed to clarify that eyetracker usage is also involved in the demo. 

Since there is the separate 'visualsearch_eyetracker' demo experiment for showcasing eyetracker usage, to me it makes the most sense to simply remove the gaze part of the instruction here. But I'm guessing that @isolver knows best.

**Comment by isolver** [comment]
Ya, this is an issue of the readme not being updated. It is not suppose to use the eye tracking. Will fix. thanks for pointing it out.

**Comment by isolver** [comment]
Given the better Builder - iohub integration since 2021.2.x, this demo will be removed in the next release, so closing the issue.
