### ISSUE TITLE
Backslash in ImageStim image path causes unknown resource error

### ISSUE THREAD

**Issue by JLC827** [psychopy/psychopy#3734]
If backslashes are used instead of forward slashes in image resource paths PsychoPy reports an "unknown resource" error. Forward slashes are used for file paths on Unix, but Windows allows forward and backslashes interchangeably, so it's not unreasonable for a user to not notice this difference. I'm not sure whether to best way to solve this problem would be to allow backslashes for file paths, or to report an error to the user if a backslash is present in a file path.

**Comment by peircej** [comment]
We really need to get people using forward slashes so that if they want to run online it still works too. The question is whether to automatically/silently replace with forward slashes or to warn user verbally
