### ISSUE TITLE
BF Can't access preferences in Ubuntu 20.04 due to case sensitivity of icon's names

### ISSUE THREAD

**Issue by jakub-jedrusiak** [psychopy/psychopy#3735]
I use Ubuntu 20.04 with Python 3.8.5. For quite a while, when I tried to access the preferences window, I was getting the following error message:
```
Traceback (most recent call last):
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/themes/_themes.py", line 810, in _loadBitmap
    im = wx.Image(filename)
TypeError: Image(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'NoneType'
  overload 3: argument 1 has unexpected type 'NoneType'
  overload 4: argument 1 has unexpected type 'NoneType'
  overload 5: argument 1 has unexpected type 'NoneType'
  overload 6: argument 1 has unexpected type 'NoneType'
  overload 7: argument 1 has unexpected type 'NoneType'
  overload 8: argument 1 has unexpected type 'NoneType'
  overload 9: argument 1 has unexpected type 'NoneType'
  overload 10: argument 1 has unexpected type 'NoneType'
  overload 11: argument 1 has unexpected type 'NoneType'
  overload 12: argument 1 has unexpected type 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/_psychopyApp.py", line 754, in showPrefs
    prefsDlg = PreferencesDlg(app=self)
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/preferencesDlg.py", line 557, in __init__
    self.populatePrefs()
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/preferencesDlg.py", line 733, in populatePrefs
    icon = self.app.iconCache.getBitmap(choice.Text)
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/themes/_themes.py", line 837, in getBitmap
    self._loadBitmap(name, theme, emblem=emblem, size=size)
  File "/home/jakub/.local/lib/python3.8/site-packages/psychopy/app/themes/_themes.py", line 812, in _loadBitmap
    raise FileNotFoundError("Failed to find icon name={}, theme={}, "
FileNotFoundError: Failed to find icon name=FlowTop_CompRight, theme=light, size=48, emblem=None
```
The problem persisted until I've changed the names of some icons in light, dark and classic folders in app/Resources. The buggy files were named „flowtop_compright.png” and „flowtop_compleft.png” but the program demanded „FlowTop_CompRight.png” and „FlowTop_CompLeft.png” with the capitals. After **changing the names of the files to their correct form**, I can access the preferences window. Surprisingly, FlowBottom_CompRight.png and FlowBottom_CompLeft.png are named correctly (with the capitals) and thus don't cause any problems.

**Comment by peircej** [comment]
Well done Jakub. Thanks for tracking that down (I can see why that isn't an issue on Win32 but I'm puzzled that it doesn't cause an error on macOS as that does use case-sensitive names)

Anyway, do you fancy submitting this as a pull request (create a branch off the release trunk and make a commit with BF: prefix) so that you're credited with the fix? I can help you through it if you haven't done this before. Or if you'd prefer I simply do it myself that's fine too! 😉

**Comment by jakub-jedrusiak** [comment]
@peircej I can do it, but help would be appreciated 😅

**Comment by jakub-jedrusiak** [comment]
@peircej OK, I might have done it. At least I hope so.

**Comment by peircej** [comment]
Well done, yes :-)
Normally we have to make sure the test suite passes but I have to admit that right now that is failing for unrelated reasons that we need to work on. Thanks!
