### ISSUE TITLE
Duration field needs a "$" sign in new release

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3739]
Previously it was necessary for users to add a $ sign at the start of the duration field to use custom code in that field, but in 2021.1.3 and 2021.1.4 this will throw an error. Need to add a $sign to the parameter fieldname in the dialog box.

**Comment by peircej** [comment]
@TEParsons maybe this is another case where the code has moved incorrectly to number and should be code (or similar)?

**Comment by TEParsons** [comment]
Spot on, yes, it needs changing back to `valType="code"`. Putting in a pull request now :)
