### ISSUE TITLE
TextStim in second glfw window causes error if initialized with text

### ISSUE THREAD

**Issue by Jolinda** [psychopy/psychopy#3742]
Hi, I am playing with glfw windows on both MacOs & Windows 10, build 2021.2.4, and getting identical behavior on both platforms. 

The following code:

```
win1 = visual.Window(units="height", winType = 'glfw', pos = (0,0))
msg1 = visual.TextStim(win = win1, text = 'Hello')
msg1.draw()
win1.flip()

win2 = visual.Window(units="height", winType = 'glfw', pos = (800,0))
msg2 = visual.TextStim(win = win2, text = 'World')
msg2.draw()
win2.flip()
```
fails with pyglet.gl.lib.GLException: b'invalid operation' during the initialization of the second TextStim. This can be avoided by using the default constructor and changing the text attribute after construction:

```
win1 = visual.Window(units="height", winType = 'glfw', pos = (0,0))
msg1 = visual.TextStim(win = win1)
msg1.text = 'Hello'
msg1.draw()
win1.flip()

win2 = visual.Window(units="height", winType = 'glfw', pos = (800,0))
msg2 = visual.TextStim(win = win2)
msg2.text = 'World'
msg2.draw()
win2.flip()
```
However, the text in the second window will not render correctly:
![glfw_render](https://user-images.githubusercontent.com/16389242/115448736-e8713400-a1ce-11eb-89d5-092f5ec6a08e.png)

unless the second TextStim is either a different font or a different height that the first message, for example:
```
win1 = visual.Window(units="height", winType = 'glfw', pos = (0,0))
msg1 = visual.TextStim(win = win1)
msg1.text = 'Hello'
msg1.draw()
win1.flip()

win2 = visual.Window(units="height", winType = 'glfw', pos = (800,0))
msg2 = visual.TextStim(win = win2)
msg2.text = 'World'
msg2.height = .99 * msg1.height
msg2.draw()
win2.flip()
```
![glfw_good](https://user-images.githubusercontent.com/16389242/115450280-8d404100-a1d0-11eb-90ed-3949ac39bd91.png)

**Comment by Jolinda** [comment]
I found out that this and a lot of other oddness can be prevented if you share objects between the two contexts:

`win2 = visual.Window(units="height", winType = 'glfw', pos = (800,0), backendConf={'share':win1})`

**Comment by mdcutone** [comment]
A PR was introduced to solve this problem. https://github.com/psychopy/psychopy/pull/3740
