### ISSUE TITLE
Inconsistent auto generation of JavaScript code specifying component duration

### ISSUE THREAD

**Issue by JLC827** [psychopy/psychopy#3744]
I am setting the duration of components dynamically using code. As in the following image:
![image](https://user-images.githubusercontent.com/38880886/115564867-c94ad300-a2b0-11eb-9da0-31307c88438c.png)

This works as expected for Image elements, but does not works for a Keyboard element. Instead the following error is given
`ReferenceError: asarray is not defined`

Taking a look at the js shows that the generated code is different for each element.:

For the Image elements:
`frameRemains = 0.0 + shifting_shelf_experiment.get_transition_display_time() - psychoJS.window.monitorFramePeriod * 0.75;`

For the Keyboard element:
`frameRemains = 0.0 + asarray($shifting_shelf_experiment.get_transition_display_time()) - psychoJS.window.monitorFramePeriod * 0.75; `

This is related to https://github.com/psychopy/psychopy/issues/3661 , but I'm not sure if adding asarray as a js function is the solution. Unless there is a specific reason why Keyboard elements use asarray could that be removed? Unsure of its exact purpose here. Either way the code should ideally be consistent.

**Comment by peircej** [comment]
I believe this has been fixed by GH-3731
