### ISSUE TITLE
BUG: orientation parameter of slider does not function locally

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3775]
Setting the orientation parameter of slider to 90 does not create a vertical slider in 2021.1.4.

**Comment by RebeccaHirst** [comment]
Ohhh I see this is because the orientation of a slider is determined by its size parameter locally (note that in PsychoJS the orientation of the slider is set using an `slider.ori` attribute, and setting the orientation parameter to be 90 in builder results in a vertical slider for online use - enabling the orientation parameter to function the same locally and online would be intuitive)

**Comment by peircej** [comment]
Yes, I had used the height/width to determine how it behaved but maybe ori would have been better. I hadn't realised @apitiot had handled it that way in PsychoJS. I guess we could do the same in PsychoPy. We could set a flag early on that says checks both the height/width and effectively flips them if ori=90 (and stores what was requested separately from what's used in the rendering)

**Comment by TEParsons** [comment]
Fixed in 2022.1.0, and tested in [test_horiz](https://github.com/psychopy/psychopy/blob/8a4eb272cd809851000617d08c987240fb3a5825/psychopy/tests/test_visual/test_slider.py#L37)
