### ISSUE TITLE
Failure to convert nDots (of Dots component) and texRes (of Noise component) into integer

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#3778]
Psychopy (at least version 2021.1.2 and 2021.1.4) for Noise auto-translates the texRes parameter, which is written as “128” in the Builder parameters, into “128.0”, and for Dots auto-translates the “100” nDots as “100.0”. But texRes and nDots must be integers, so this creates an error. People seem to have also reported this here 1 and here 1 (without identifying the underlying problem). For an example, see test.psyexp [here](https://discourse.psychopy.org/t/psychopy-builder-erroneously-codes-texres-as-a-float-instead-of-an-integer/22802).

Somehow the magic that is the PsychoPy Builder → Python code generation previously seems to have known that the texRes parameter should be an integer, but no longer knows that.

While we wait for a fix, people with this problem can fix it manually by going to the auto-generated Python code and removing the decimal point from nDots or texRes.

Note that the Builder’s Noise demo works, even though creating a psyexp with Noise from scratch does not. I don't know enough about PsychoPy Builder to be confident about the implications of this fact.

**Comment by peircej** [comment]
Thanks @alexholcombe 
We did some refactoring of params in 2021.1 to to make for more flexible inputs in the dialogs. The logic being that if a parameter knows what type of entry to expect then it can offer better options to the user (like browse buttons, number spinners etc) but that refactoring has produced some rough edges. They're relatively easy fixes once we know though so thanks for reporting
