### ISSUE TITLE
Image component: selecting Image via file picker doesn't translate well to PsychoJS

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3793]
On my Windows 10 device, I selected an image via the file picker, and so the path `img\request_landscape.png` ended up in the Image field. In the generated JS, two different things happened with the backslash in this path:
- In `psychoJS.start`, as a resource the backslash got converted to a slash (`img/request_landscape.png`), so the resource got correctly downloaded
- However, in the `image` property of the `visual.ImageStim`, the backslash got converted into two backslashes instead of a slash (`img\\\\request_landscape.png`), so the experiment could not find the resource

**Comment by tpronk** [comment]
I compiled a test using the dev branch and commit dd2200175ac53dcd560290cd7b5eabd0a… but this issue still seems to be there:
* [example of issue](https://staging.psychopy.org/experiments/issue_demos/wdio_img/)
* [corresponding psyexp file](https://github.com/psychopy/psychojs_testing/tree/main/tests/wdio_img)

**Comment by TEParsons** [comment]
So is this a problem with relative paths? Does it need to have `../` at the beginning or something? If so I could add a condition whereby if a param is `valType="file"` and is a relative path it compiles to JS with necessary characters appended/prepended

**Comment by tpronk** [comment]
This issue is fixed I believe. There were a couple of PRs (amongst which one by you) for that, and the last one being PR #3957
