### ISSUE TITLE
Syncing via Builder sometimes gives problems if only capitalization changed

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3794]
When renaming a file from `slideshow.js` to `Slideshow.js`, I noticed that this change wasn't synced to Pavlovia. As a workaround, I first removed the file, synced, then added it again.

Next, I tried to reproduce this problem in a fresh project. At first, changes in capitalizations did get synced, but after a couple of syncs not anymore. I guess a good way to reproduce this problem is via a somewhat older project.  The project I used for testing is: https://gitlab.pavlovia.org/tpronk/test_capitals

I didn't notice any difference between files with different extensions (tried `.txt`, `.js`, and `.yolo`), nor different directories (tried the root directory and a subdirectory `js/`).

The problem remained when I changed the capitalization and the content of a file. Stepwise:
1. I create an file called `THISISATEST.txt`, synced. Now `THISISATEST.txt` is on Pavlovia.
2. Renamed it to `thisisatest.txt`, synced. Builder doesn't notice any change, file is still `THISISATEST.txt` on Pavlovia.
3. Edited my local `thisisatext.txt`, added the content `Some content Hellooooo`, saved.
4. Synced again, Builder notices a change. Now `THISISATEST.txt` on Pavlovia has the content `Some content Hellooooo`, but the filename still hasn't changed.

**Comment by peircej** [comment]
This is a git issue with windows because win32 doesn't distinguish case in filenames. We can't fix without getting really ugly
