### ISSUE TITLE
Setting Audio To Only Play For Certain Trials

### ISSUE THREAD

**Issue by dhabershon98** [psychopy/psychopy#3799]
I'm very new to PsychoPy and have no coding experience whatsoever, so I don't really get much of it and am using mainly the builder. I'm creating a simple stop-signal task that consists of an arrow indicating the position of the stimulus followed by a stimulus to which you have to respond with the correct arrow key. The idea is that a tone will play before the stimulus appears at random intervals as the stop signal. However, i've tried allsorts but I can't get it to work in the way I want. It keeps playing the sound for every single trial rather than just the stop ones that it is set for on the excel doc. I've tried setting a silent audio file for the go tasks and it says it doesn't support multiple portaudio streams. 

Is there something i'm missing?
Thank you.

**Comment by peircej** [comment]
This doesn't appear to be a bug or a feature change. Please use the forum for usage queries.
