### ISSUE TITLE
Bug Report: Builder-generated button component registers clicks from previous routine

### ISSUE THREAD

**Issue by jan-lukas-bichel** [psychopy/psychopy#3817]
I’m using the builder on version 2021.1.4 and encountered a bug with the button component. If two routines following each other have a button in the same spot, and the first button press ends the first routine, then your mouse will still be in the same spot in a pressed state when the next routine starts. This way you will skip all the other routines following the first one immediately, if they have a routine-ending button in the same spot.

**Comment by TEParsons** [comment]
Finally had time to look into this! Just to check, do you have "Run Once Per Click" ticked in your button component?

**Comment by jan-lukas-bichel** [comment]
Thank you for looking into it! "Run Once Per Click" is ticked in all of the button components.

**Comment by jan-lukas-bichel** [comment]
I just tried to replicate the bug in a new experiment. It seems that you can avoid skipping the following routines, if you instantly release the mouse-button after you click. But if you hold down the mouse button for a fraction of a second to long, then it will also click the button in the following routine.

**Comment by TEParsons** [comment]
Ah okay, when I try this I can replicate it in 2021.1.4 but not in 2021.2.x (aka the next release), I have changed some stuff around how it checks for `wasClicked` and handles the "Run Once Per Click" setting so something I did must have fixed it... At any rate, this will no longer be a bug in the next release :)

**Comment by jan-lukas-bichel** [comment]
Thank you :)
