### ISSUE TITLE
JS boilerplate: Functions declared twice if routine used twice, produces syntax error

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3897]
If a function is declared in the before experiment tab and then the routine is used multiple times in the flow, then the function is also declared multiple times in the JS output. This produced an error when run online 'Uncaught SyntaxError: Identifier FUNCTION NAME has already been declared'.

Minimal demo of bug here: https://gitlab.pavlovia.org/lpxrh6/double_function_test/tree/master

**Comment by peircej** [comment]
This is fixed in #4009
