### ISSUE TITLE
Textbox: cannot set every repeat using variable

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3899]
Setting the value of textbox.text on each repeat (using input from a conditions file i.e. $thisWord) results in error (tested on windows). Could be associated with python installation rather than PsychoPy per say? Doesn't occur for updating TextStim. 

C:\Users\44797\mypython\lib\site-packages\pyglet\media\codecs\wmf.py:838: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))
C:\Users\44797\mypython\lib\site-packages\pyglet\image\codecs\wic.py:292: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))

Tested on windows: Minimal demo here: https://pavlovia.org/lpxrh6/update_textbox_test

**Comment by TEParsons** [comment]
When I run this in latest dev I don't get any errors, could you pull down the latest and try it again?

**Comment by RebeccaHirst** [comment]
yep can confirm now woks
