### ISSUE TITLE
Keyboard: Correct answer box greyed out and not editable if store correct checked

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3900]
If the "Store Correct" box in the data tab is checked in a keyboard component the Correct Answer field remains greyed out, so the user cannot enter the correct answer i.e. `$corrAns`

**Comment by RebeccaHirst** [comment]
update, if you check the Store Correct box > press OK > reopen the component, the Correct Answer field is *then* editable

**Comment by TEParsons** [comment]
I'd wager this is the same validation bug I've just passed to @mdcutone as I couldn't figure it out... It also means that if you add invalid code, the warning message doesn't go away and the Okay button doesn't enable even after you fix the code

**Comment by TEParsons** [comment]
The validation bug was affecting this but the crucial thing is that this box had its own special method outside the `depends` system - it doesn't do anything special though, so deprecating the function and using `depends` instead is the way to go. On it now :)
