### ISSUE TITLE
Keyboard: AttributeError: 'Keyboard' object has no attribute '_buffers'

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3901]
Using a keyboard response with default parameters results in experiment closing with the following error: 

AttributeError: 'Keyboard' object has no attribute '_buffers'

Minimal demo here: https://pavlovia.org/lpxrh6/keyboard_bug_demo 

(all issues reported on dev branch)

**Comment by isolver** [comment]
fixed in PR 3910

**Comment by peircej** [comment]
additional fix in https://github.com/psychopy/psychopy/pull/3922
