### ISSUE TITLE
Microphone: Cannot function in loop because thisTrialN used for saving

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3902]
Data from the microphone cannot be stored if the routine is not enclosed in a loop. Produces error:

"C:\Users\44797\Documents\PsychoPy_Job\development\new_release_tests\microphone\basic_no_loop_lastrun.py", line 204, in <module>
    thisExp.addData('mic.clip', os.path.join(micRecFolder, 'recording_mic_thisExp_%s.wav' % thisExp.thisTrialN))
AttributeError: 'ExperimentHandler' object has no attribute 'thisTrialN'

This is because an attribute of the trial handler is used to create the variable name 
https://github.com/psychopy/psychopy/blob/dev/psychopy/experiment/components/microphone/__init__.py#L360

**Comment by TEParsons** [comment]
It's worse than that, in JS I actually hard coded it to be `trials` regardless of the loop/experiment handler's actual name... Whoops! Will change the boilerplate now!
