### ISSUE TITLE
Cannot launch experiments from builder in dev branch "NameError: name 'defaultKeyboard' is not defined"

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3923]
Launching experiments from builder in dev branch returns error "NameError: name 'defaultKeyboard' is not defined"

**Comment by TEParsons** [comment]
Ah whoops, that was an indentation typo on my part... Moving the code to make defaultKeyboard to the ioHub code to it appears in the right place relative to ioHub servers, I forgot to dedent it so it's now only written if there's an Eyetracker chosen. Easy fix, will push out now!
