### ISSUE TITLE
Eyetracking calibration: Selecting options freezes up routine 

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3944]
When a calibration routine is added to the flow, if the user selects to make any change within the routine (e.g. uncheck randomize, change target layout) a small white box appears in the top left of the routine (visible if theme is dark) and no further edits can be made to that routine until the user selects a different routine and then returns to the calibration routine.

**Comment by isolver** [comment]
This is also reported in an [open Clickup issue](https://app.clickup.com/t/x18xdh) - I thought we were using that for new feature issues in Dev.

**Comment by TEParsons** [comment]
In current dev I'm no longer getting this bug... Did someone fix it by accident?

**Comment by isolver** [comment]
Agreed, seems to be fixed in latest Dev

**Comment by RebeccaHirst** [comment]
Still a bug with the animation tab specifically https://github.com/psychopy/psychopy/issues/4010
