### ISSUE TITLE
Eye tracking: Calibration routine cannot be placed at several locations in flow

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3946]
Currently the calibration routine can only be added to the flow once. This limits functionality for those wanting to repeat calibration at several points in their experiment (e.g. by presenting it every nth trial).

**Comment by RebeccaHirst** [comment]
issue needs investigation - could add calibration several times after closing and reopening PsychoPy

**Comment by RebeccaHirst** [comment]
@TEParsons @isolver sorry this one is back! the word "calibration" is greyed out in the "insert routine" tab

**Comment by TEParsons** [comment]
Fixed in #4028
