### ISSUE TITLE
Code Component dialog not opening (error with WarningsManager)

### ISSUE THREAD

**Issue by peircej** [psychopy/psychopy#3950]
Traceback (most recent call last):
  File “/Users/lpzjwp/code/psychopy/git/psychopy/app/builder/builder.py”, line 2325, in onClick
    timeout=timeout)
  File “/Users/lpzjwp/code/psychopy/git/psychopy/app/builder/dialogs/dlgsCode.py”, line 153, in __init__
    self.warnings = WarningManager(self, self.okButton)  # to store warnings for all fields
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by TEParsons** [comment]
I was getting this too but I'm not in the latest dev, is this fixed?

**Comment by peircej** [comment]
Sorry, yes, fixed in #3951
