### ISSUE TITLE
PsychoJS code generation: setting text in a textbox doesn't show up

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3969]
[This experiment](https://github.com/psychopy/psychojs_testing/tree/main/tests/wdio_textbox) contains a non-editable textbox that presents the content of a variable named `$msg`. In a code component, begin routine tab, this variable is set to the value `"this is a test"`. I compiled this experiment to JS with a current version of the dev branch of PsychoPy. However, this value isn't shown. It seems two things are going wrong at the side of the code generation:
1. The `setText(msg)` part is before the "begin routine" part that assigns a value to `msg`
2. Because `reset()` is called after `setText(msg)`, the textbox is emptied again.

Below some JS as was generated:
```
textbox1_2.setText(msg)
textbox1_2.reset()
msg = "This is a test";
```

Below an adjustment that can make the text display
```
msg = "This is a test";
textbox1_2.reset()
textbox1_2.setText(msg)
```

**Comment by tpronk** [comment]
I don't think we're there yet. If I run the same test now, I get these lines of JS.
```
textbox1_2.reset();
textbox1_2.setText(msg)
msg = "This is a test";
``` 
Howver, the text still isn't visible, because `msg` is assigned a value *after* it's used to set the text

**Comment by peircej** [comment]
The second issue is a user error. You have the Code Component that defines the `msg` coming _after_ the Text Component that uses it. i.e. the order needs to change in the experiment in order to change in the output code.
