### ISSUE TITLE
Unit tests for Python -> JS transpiler?

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3980]
@apitiot has done some amazing work on the transpiler. Let's add some unit tests to ensure that they will be stable across future updates of PsychoPy

**Comment by peircej** [comment]
You could extend psychopy/tests/test_py2js
It currently only tests expression2js (e.g. for parameters) not snippet2js for larger chunks

**Comment by tpronk** [comment]
Will do; added it to my list!

**Comment by TEParsons** [comment]
I'd forgotten about this issue, but I have added some more tests for the transpiler! Check out `test_params.py`, the method `test_param_str` tests a bunch of parameter values are compiled to JS as expected
