### ISSUE TITLE
What's this error message exactly?

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3988]
I'm wondering what that symbol between "or" and "no spaces" should mean? 

![image](https://user-images.githubusercontent.com/8987504/121728088-b3a19f00-cae4-11eb-8655-a6fd9bf67a6b.png)

**Comment by TEParsons** [comment]
Every character has to be alphanumeric (`[A-Za-z\d]`) or an underscore, definitely could word that error better... I'll look up where it's defined

**Comment by tpronk** [comment]
Maybe it should be a valid Python varname (in which case it may not start with a number and may also contain underscores)? In that case, the message we've got in our loop template could be nice:
"Variable names need to start with a letter or an underscore (_), followed by only letters, numbers and underscores."

**Comment by peircej** [comment]
The warning message might not have been very self-explanatory, but it was a lot better that the issue raised about it! 😉 
Try to keep issue titles clear to everybody so that when someone sees the list they have a better idea what this refers to (including in the future)
