### ISSUE TITLE
Slider markerColor is not in generated JS

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#4003]
This [test-experiment](https://github.com/psychopy/psychojs_testing/tree/main/tests//wdio_slider) features a slider with a blue marker (markerColor == 'Blue'). In PsychoPy I see a blue marker, but in PsychoJS I don't. If I generate JS using a recent version of the dev branch, I don't see any `markerColor` arguments in the Slider constructor. See [this line](https://github.com/psychopy/psychojs_testing/blob/6a82d8edfe17a1d3404d431b939d9f0c35f38b6b/compiled_experiments/wdio_slider/wdio_slider.js#L123) .

Note I only tried out `markerColor`, but perhaps this also applies to a whole bunch of other color parameters? Tagging @thewhodidthis so he's in the loop.

**Comment by RebeccaHirst** [comment]
does this link to this? https://github.com/psychopy/psychojs/issues/322

**Comment by tpronk** [comment]
Well spotted @RebeccaHirst! Yes. I think there might be an issue on the side of the PsychoJS library as well. Both need fixing before we'll actually get to see a colored marker

**Comment by thewhodidthis** [comment]
This looks like a boilerplate thing as far as `markerColor` is concerned. However, the `Slider` class in PsychoJS does lack border / line options https://github.com/psychopy/psychojs/issues/401
