### ISSUE TITLE
Eyetracking: Calibration routine, Animation Position Changes causes freeze

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#4010]
If the "Animate Position Changes in the Animation tab is checked/unchecked the routine freezes with a white box in the corner of the routine panel - like this https://github.com/psychopy/psychopy/issues/3944

**Comment by TEParsons** [comment]
Ahh I see why this was accidentally fixed now - the thing that fixed it will be when I fixed the flicker by only laying out when there's a visibility change from checking depends. Can actually fix this properly now I know where it's erroring!
