### ISSUE TITLE
Shall we add `===` and `---` title options to our markdown parser?

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#4069]
Shall we add `===` and `---` title options to our markdown parser? I ran a little test and confirm that the following works on our gitlab:
```
Level 1 heading
===============
Level 2 heading
---------------
```
NB - This suggestion is inspired on a suggestion by @peircej.

**Comment by TEParsons** [comment]
So far as I can tell this works on the latest standalone: 
![image](https://user-images.githubusercontent.com/25686106/128146141-9c594b2a-18c1-4390-8c87-099bf51a5c6d.png)

We use markdown-it to parse markdown in the REAME files, which also exists in JS, so if GitLab will let us use a custom parser we could apply markdown-it JS to Pavlovia for synchronicity?
