### ISSUE TITLE
Specifying number of trials as parameter in Trialhandler

### ISSUE THREAD

**Issue by MPBagger** [psychopy/psychopy#407]
It would be very nice if you could specify a specific number of trials in the Trialhandler instead of having to implement a counter and an if loop with the body trials.finished = True.

E.g. if one has a design with 50 possible trials but only want to randomly loop through 25 of them. 

Something like:

```
trials = data.TrialHandler(design, nReps=1, nTrials=25, method='random', extraInfo='info', name='Trial')
```

instead of:

```
if count > 25:
    trials.finished = True
```

**Comment by dvbridges** [comment]
Hi there. Thank you for your suggestion. We (@peircej and myself) looked at the idea of adding the nTrials parameter to trial handler. However, we decided that the additional nTrials parameter is rarely useful. It is not often that one would use a random subset of trials from an experiment as this may affect any counterbalancing in place. Also, if subsets are required for practice blocks, then it would make more sense to control the list of practice trials through other methods, e.g., by presenting a single block of trials from the main task by using nReps=1 in a separate practice routine.
