### ISSUE TITLE
The GUI (including the pop-up help message) says use brackets [ ] but the pre-populated value uses parentheses () instead, and using brackets causes a syntax error.

### ISSUE THREAD

**Issue by R180** [psychopy/psychopy#4070]
The GUI (including the pop-up help message) says use brackets [ ] but the pre-populated value uses parentheses () instead, and using brackets causes a syntax error.
Win10
2021.1.4:
Standalone

If I select TEXT - LAYOUT, I see “Position [x,y] $”
It’s as though the user is being asked to enter a list.
However, the corresponding, pre-populated value is not [0,0] but (0,0)
It’s as though the user is being asked to enter a tuple rather than a list.
As it turn out, only the use of parentheses works. The use of brackets (as recommended in the GUI-provided suggestion) generates a syntax error. So, is “TEXT - LAYOUT, Position [x,y] $” supposed to read, “TEXT - LAYOUT, Position (x,y) $” ?

**Comment by TEParsons** [comment]
Square brackets not working was a bug that is now fixed :) `size` and `pos` are both list-type inputs, meaning you can specify them as:
`[x, y]`
`(x, y)`
or
`x, y`
