### ISSUE TITLE
Edited images on gitlab do not appear when I run experiment on Pavlovia 

### ISSUE THREAD

**Issue by eyavuz21** [psychopy/psychopy#4096]
Dear all,

When I try to replace an image on an experimental project on Gitlab, and then run the experiment on Pavlovia, the new image does not appear, only the old one!

I have attached a screenshot of what I am trying to do! 

![Screenshot 2021-07-01 at 14 39 47](https://user-images.githubusercontent.com/59828368/124133925-37aecd00-da7a-11eb-8340-eacdc6749315.png)

Is this the right of way of editing the images?

Is there something else/another step missing that I need to do before I can then run the experiment again on Pavlovia? 

BW,

Emre

**Comment by TEParsons** [comment]
Did you sync your experiment inbetween? It looks like the last update to those files was 1 month ago

**Comment by peircej** [comment]
I think this was most likely an issue with not refreshing the browser cache after updating the experiment. I'm closing for now but reopen if this is still an issue
