### ISSUE TITLE
Tobii eyetracker with EPU not works in PsychoPy

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychopy#4098]
<p style="color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The PsychoPy experiment using tobiiresearch works weird in Mac OS.<br>Below are tested.<br>-tested with two X3-120 with EPU in two different Mac Pro with High Sierra (2x2 design…) and<span> </span><strong style="font-weight: bolder;">same issue.</strong><br>-run same experiment with Tobii Pro Nano, Tobii Pro Fusion, 4C (All USB trackers, and all works fine).<br>-run simplified version of experiment with X3-120 with EPU in Windows (<strong style="font-weight: bolder;">works</strong>).<br>-replace tobiiresearch to fresh downloaded 1.7, and 1.8 of Psychopy’s python library folder. (<strong style="font-weight: bolder;">no change</strong>).</p><p style="color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">When EPU with X3-120 connected, everything works fine in Tobii Eyetracker manager (calibration, and gaze display for long time). Even calibration works properly by calling it inside PsychoPy.</p><p style="color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">However in actual experiment, after &lt;.05 sec, the connection is lost and all nan gazes are subscribed. Also found the pause script for movie3 ‘fails’ after the point of gaze stream lose.</p><blockquote style="border-left: 5px solid var(--primary-low); background-color: var(--blend-primary-secondary-5); clear: both; margin-left: 0px; margin-right: 0px; padding: 12px; color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="md-table" style="overflow-y: auto; margin-top: 0px !important; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px;">

17.6841 | EXP | Failed Set tmstim_01 paused
-- | -- | --
17.6841 | EXP | Failed Set tmstim_03 paused
17.6841 | EXP | Failed Set tmstim_48_04 paused
17.6841 | EXP | Failed Set tmstim_48_05 paused
17.6841 | EXP | Failed Set tmstim_48_06 paused
17.6841 | EXP | Failed Set tmstim_07 paused
17.6841 | EXP | Failed Set tmstim_48_08 paused

</div></blockquote><p style="color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">So, I am suspicious about the asynchronous ‘subscription’ process.

Also attached files in https://discourse.psychopy.org/t/anyone-use-tobii-epu-x3-120-with-macos/23833 
too.
</p>

**Comment by isolver** [comment]
@iPsych , looking at the project you attached on Discourse, it looks like you are using the Tobii Python SDK directly in the custom code of your Builder experiment, starting your own subprocess for calibration, etc.  Do I have that right? If so, I'm not sure how we can help with this. Have you contacted Tobii about the issue, maybe trying to create an example outside of psychopy that recreates the issue you are having in standard python?

You way also want to try using psychopy iohub to access the Tobii eye tracker instead of using tobii research directly. I'm not sure what you mean by a 2x2 Tobii design; if you are trying to use 2 tobii trackers at the same time in the same experiment then I do not think iohub would not support that either.

This maybe of no help, but when looking through your project code I see you are calling the following at the start of each trial (in your Begin Routine custom code):

```
my_eyetracker.subscribe_to(tr.EYETRACKER_GAZE_DATA,......)
```

and this in the End Routine:

```
my_eyetracker.unsubscribe_from(tr.EYETRACKER_GAZE_DATA, gaze_data_callback)
```

Could that be causing an issue somehow? What if you moved that code to the Begin / End Experiment section of the custom code? Again, I'm just throwing out ideas here. ;) 

thank you.

**Comment by iPsych** [comment]
@isolver Thanks.
Actually putting subscribe and unsubscribe in routine doesn't make any problem with USB type ones.
However, yes, it's weird way.

So, I tested very simple code attached directly in python and in coder shell, same result. ( I attached the file)
[tobiitest2.py.zip](https://github.com/psychopy/psychopy/files/6792265/tobiitest2.py.zip)

**Comment by iPsych** [comment]
@isolver
Update! the problem only happens with tobii_research >=1.6.2.
I tested all available versions one by one, and found the issue disappears in 1.6.1 and 1.6.0.
It seems the issue is directly related to .so file Tobii provided.
If anybody using Mac and use X3-120, please replicate the issue :)

Update2! 
Yes. After force unzip and replaced tobiiresearch in lib folder of PsychoPy3 2021.1.4 Version,
The experiment works flawlessly.
It's turned out as the bug related to specific model of eyetracker (X3-120 with EPU) in Mac OS, in tobii_research >1.6.1 version.
@isolver, thanks again. your comment inspired me to investigate basic things.
