### ISSUE TITLE
Button and ResponseScale missing

### ISSUE THREAD

**Issue by haley-beck** [psychopy/psychopy#4116]
Someone in my lab just installed version 2021.1.4 and the Button and ResponseScale options are missing from her builder. We have both looked around online for solutions but it doesn't seem that people have run into this issue before. She tried uninstalling and reinstalling the program and this did not fix it. Any suggestions for fixing this? Thank you.

**Comment by TEParsons** [comment]
RatingScale was hidden in version 2021.1.0 onwards, existing RatingScale components will still exist but the button is no longer in the components panel - we recommend using Slider instead as it can do all the same stuff as RatingScale but is actively maintained and more stable.

Button certainly should be there though - in your preferences, is Button listed in "Hidden Components"?
