### ISSUE TITLE
Builder Calibration or Validation shortens time / skips first trial if duration is used 

### ISSUE THREAD

**Issue by isolver** [psychopy/psychopy#4118]
If an experiment specifies trial length by duration (say 5 seconds), adding eye tracker Calibration or Validation Component before the trial causes the trial to be skipped. It is as if the timer for the trial is not being reset before the trial starts. 

Run attached example and you will not see any trial screen (experiment will just exit after validation). 
[singlescreen.zip](https://github.com/psychopy/psychopy/files/6783170/singlescreen.zip)

**Comment by isolver** [comment]
updated OP to indicate both Calibration and Validation components seem to have same isssue. @TEParsons, would you be able to look into this please?

**Comment by isolver** [comment]
Current work around is to add an empty Routine to the flow right before the trial routine, and after Validation. The empty routine seems to cause the trial timer to be set correctly.

**Comment by TEParsons** [comment]
Looks like the problem is with the routine timer - it gets reset at the end of the previous routine, but I guess it doesn't for standalone routines, so rather than starting counting down to 0 at 5s it starts at like -70s (or however long the previous routines took)
