### ISSUE TITLE
Use tab to go to the next field in the builder (also for name field)

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#4124]
I like to use tab to go from one field to the next when editing a component in the builder. This works well with fields that have a numeric value, such a "Start" and "Stop". However, when I press the tab in a "Name" field, it adds a tab to the value in that field instead of going to the next field. 

Since tabs aren't allowed in variable names anyways, could we make it such that we can also go the next field when we're in the Name field?

**Comment by mdcutone** [comment]
Sounds reasonable. I think we just need a `TAB_TRAVERSAL` flag when instancing our input fields. Something Todd or I can do.
