### ISSUE TITLE
broken links on psychopy.org landing page -- templating issue?

### ISSUE THREAD

**Issue by NickleDave** [psychopy/psychopy#4133]
Hi `psychopy` maintainers,

just noticed that the link to Documentation on the drop-down from the main landing page is broken

(I get "https://www.psychopy.org/%7B%7B%20pathto('documentation')%20%7D%7D" from pasting)
![Screen Shot 2021-07-12 at 9 24 35 PM](https://user-images.githubusercontent.com/11934090/125375736-9536f980-e357-11eb-87e4-da59b0033e6a.png)

when I click that, I get something that looks like templating, like jinja or something?
Posting a screenshot because it won't let me cut and paste correctly

![Screen Shot 2021-07-12 at 9 23 20 PM](https://user-images.githubusercontent.com/11934090/125375649-73d60d80-e357-11eb-9d14-4e6befdec128.png)

**Comment by NickleDave** [comment]
Update: it's all the links in that dropdown 😬 -- I get something similar trying to go to the API reference

![Screen Shot 2021-07-12 at 9 27 45 PM](https://user-images.githubusercontent.com/11934090/125376002-0f677e00-e358-11eb-8096-16f1fce76810.png)

**Comment by peircej** [comment]
I believe this is fixed now. Thanks
