### ISSUE TITLE
PsycoPy 2021.2.0.1 still issue in MacOS BigSur

### ISSUE THREAD

**Issue by thewoz** [psychopy/psychopy#4134]
Hi,
I have download the laste version on the code.
I still get this error running an experiment.

Process:               python [3280]
Path:                  /Applications/PsychoPy.app/Contents/MacOS/python
Identifier:            org.opensciencetools.psychopy
Version:               2021.2.0 (2021.2.0)
Code Type:             X86-64 (Native)
Parent Process:        PsychoPy [3268]
Responsible:           PsychoPy [3268]
User ID:               501

Date/Time:             2021-07-14 11:51:20.024 +0200
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        69D5400E-B6FB-8C2A-708E-6FD6773CB4FB

Sleep/Wake UUID:       EFC35146-00E3-4BE5-AAEA-0B17BC3B1792

Time Awake Since Boot: 6900 seconds
Time Since Wake:       2900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  PTB mainthread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [3280]

Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread

Thread 0 Crashed:: PTB mainthread  Dispatch queue: com.apple.main-thread
0   libdispatch.dylib             	0x00007fff2026f887 __DISPATCH_WAIT_FOR_QUEUE__ + 387
1   libdispatch.dylib             	0x00007fff2026f475 _dispatch_sync_f_slow + 171
2   PsychHID.cpython-36m-darwin.so	0x0000000109584446 PsychHIDOSKbQueueCreate + 182
3   PsychHID.cpython-36m-darwin.so	0x000000010957f745 PSYCHHIDKbQueueCreate + 405
4   PsychHID.cpython-36m-darwin.so	0x0000000109571448 PsychScriptingGluePythonDispatch + 1672
5   org.python.python             	0x0000000108ec87cb _PyCFunction_FastCallDict + 491
6   org.python.python             	0x0000000108f4a747 0x108e72000 + 886599
7   org.python.python             	0x0000000108f46eb7 _PyEval_EvalFrameDefault + 27559
8   org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
9   org.python.python             	0x0000000108f4bae1 0x108e72000 + 891617
10  org.python.python             	0x0000000108f4a721 0x108e72000 + 886561
11  org.python.python             	0x0000000108f46eb7 _PyEval_EvalFrameDefault + 27559
12  org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
13  org.python.python             	0x0000000108f4bdfb _PyFunction_FastCallDict + 763
14  org.python.python             	0x0000000108e7f6b7 _PyObject_FastCallDict + 247
15  org.python.python             	0x0000000108e7f7d5 _PyObject_Call_Prepend + 149
16  org.python.python             	0x0000000108e7f4f0 PyObject_Call + 96
17  org.python.python             	0x0000000108ee0add 0x108e72000 + 453341
18  org.python.python             	0x0000000108edcd09 0x108e72000 + 437513
19  org.python.python             	0x0000000108e7f685 _PyObject_FastCallDict + 197
20  org.python.python             	0x0000000108f4a648 0x108e72000 + 886344
21  org.python.python             	0x0000000108f46eb7 _PyEval_EvalFrameDefault + 27559
22  org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
23  org.python.python             	0x0000000108f4bdfb _PyFunction_FastCallDict + 763
24  org.python.python             	0x0000000108e7f6b7 _PyObject_FastCallDict + 247
25  org.python.python             	0x0000000108e7f7d5 _PyObject_Call_Prepend + 149
26  org.python.python             	0x0000000108e7f4f0 PyObject_Call + 96
27  org.python.python             	0x0000000108ee0add 0x108e72000 + 453341
28  org.python.python             	0x0000000108edcd09 0x108e72000 + 437513
29  org.python.python             	0x0000000108e7f685 _PyObject_FastCallDict + 197
30  org.python.python             	0x0000000108e7fac5 _PyObject_FastCallKeywords + 197
31  org.python.python             	0x0000000108f4a648 0x108e72000 + 886344
32  org.python.python             	0x0000000108f46f56 _PyEval_EvalFrameDefault + 27718
33  org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
34  org.python.python             	0x0000000108f4bae1 0x108e72000 + 891617
35  org.python.python             	0x0000000108f4a721 0x108e72000 + 886561
36  org.python.python             	0x0000000108f46eb7 _PyEval_EvalFrameDefault + 27559
37  org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
38  org.python.python             	0x0000000108f4bdfb _PyFunction_FastCallDict + 763
39  org.python.python             	0x0000000108e7f6b7 _PyObject_FastCallDict + 247
40  org.python.python             	0x0000000108e7f7d5 _PyObject_Call_Prepend + 149
41  org.python.python             	0x0000000108e7f4f0 PyObject_Call + 96
42  org.python.python             	0x0000000108ee0add 0x108e72000 + 453341
43  org.python.python             	0x0000000108edcd09 0x108e72000 + 437513
44  org.python.python             	0x0000000108e7f685 _PyObject_FastCallDict + 197
45  org.python.python             	0x0000000108f4a648 0x108e72000 + 886344
46  org.python.python             	0x0000000108f46eb7 _PyEval_EvalFrameDefault + 27559
47  org.python.python             	0x0000000108f4b1af 0x108e72000 + 889263
48  org.python.python             	0x0000000108f40244 PyEval_EvalCode + 100
49  org.python.python             	0x0000000108f76381 PyRun_FileExFlags + 209
50  org.python.python             	0x0000000108f75bf2 PyRun_SimpleFileExFlags + 882
51  org.python.python             	0x0000000108f8fb12 Py_Main + 3554
52  python                        	0x0000000108e66df8 0x108e66000 + 3576
53  libdyld.dylib                 	0x00007fff20427f5d start + 1

**Comment by mdcutone** [comment]
This seems to be related to #4081 which is a problem we're aware of.

**Comment by peircej** [comment]
Could you try with 2021.2.1 (just released)? I believe there was an issue with the psychtoolbox in the previous version, although from the useless error message it's hard to know exactly what the issue was! So in 2021.2.1 I've switched to a different version of psychtoolbox (3.0.16) which was certainly previously working

**Comment by thewoz** [comment]
Hi, 
I need to download the just released 2021.2.1 here on Github or I can also download it from the web site (www.psychopy.org)?
