### ISSUE TITLE
Duplicate item in Builder demo menu

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#4159]
See picture below. This is 2021.2.1 on Windows 10.

![dup_menu_in_builder_demo](https://user-images.githubusercontent.com/5150568/126680647-dd134108-d934-4882-ba66-ba931128880f.PNG)

**Comment by TEParsons** [comment]
This is the thing I was complaining about with the standalone, think it's fixed in the .2 release but you might have to manually delete the demos folder for it to no longer appear if you had .0 installed previously. @peircej am I right in thinking that?
