### ISSUE TITLE
psychopy.info check of other processes running no longer works, at least on MacOS

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#4168]
The problem seems to be that to create a list of processes running, info.py uses
                proc = shellCall("ps -c -U " + os.environ['USER'])
However, this no longer works, as I discovered by executing
shellCall("ps -c -U") from the shelf.

It seems that perhaps Psychopy should now be using psutil as described [here](https://thispointer.com/python-get-list-of-all-running-processes-and-sort-by-highest-memory-usage/)

In the meantime, the output of info.RunTimeInfo is misleading because it suggests that no other processes are running when the `try` yields an `exception` on approximately line 451. But I'm not sure how to gracefully indicate to the user that checking for processes failed.

**Comment by mdcutone** [comment]
Thanks, I'll try to get this sorted out.
