### ISSUE TITLE
Publishing before saving only pushes changes to .js, not .psyexp nor .py

### ISSUE THREAD

**Issue by tsgouvea** [psychopy/psychopy#4223]
If after making changes through Builder one clicks "Sync with the web project" without also clicking "Save current experiment file", a commit will be pushed with changes to the `.js` files only.

It appears that in order for a commit to reflect the same changes on the three files (`.psyexp`, `.py`, and `.js`), one would have to take three distinct actions (respectively: save, render to python, and render to js - the last one interchangeable with publishing to Pavlovia).

I believe it is desirable that those three files are kept as much in sync as possible, and that the button that syncs to Pavlovia (ie. GitLab) should trigger Save, and perhaps also rendering a new Python file.

PsychoPy v2021.2.0
Windows10

**Comment by peircej** [comment]
I agree with the notion that the psyexp should be saved before sync. I'm not sure about rendering the `last_run.py` as that feels more like something that should render just at run-time. Arguably we should even exclude it from the sync, as a compile object that should be redone locally. Or maybe we add that as a separate option. Either way, I think that one needs more discussion/thought
