### ISSUE TITLE
Dollar sign turns code into text

### ISSUE THREAD

**Issue by arnon-weinberg** [psychopy/psychopy#4259]
#https://discourse.psychopy.org/t/bug-dollar-sign-turns-code-into-text/24659

In PsychoPy 2021.2.3 (using Javascript):

The dollar sign ($) as code indicator in any TextBox’s Text property appears to be foiled by another dollar sign.

So this works: `$Math.E+'%'` generates `2.72%` as expected.
But this does not: `$Math.E+'$'` generates `Math.E+'$'` instead of `2.72$`.
This also behaves strangely: `$Math.E+'\$'` generates `2.72\$` instead of `2.72$`.

![Screenshot from 2021-08-23 18-43-01](https://user-images.githubusercontent.com/62275680/131434794-5212ebfb-5bb8-4e63-9908-11809daf5f45.png)

**Comment by TEParsons** [comment]
I think the correct solution to this should be to use `$Math.E+'\$'` - the reason this doesn't work is a fix we put in for file paths which replaces all `\` with `/`. The changes in #4229 should fix this, so I'll make a point of testing this out again once that's pulled in!
