### ISSUE TITLE
Bold characters not showing up 

### ISSUE THREAD

**Issue by AdoNunes** [psychopy/psychopy#4270]
For some reason, psychopy does not render bold text characters. For example, running the demo  \psychopy\demos\coder\stimuli\textbox_editable.py , PsychoPy should be in bold but it is not the case:

![image](https://user-images.githubusercontent.com/17873774/132697249-d7416332-478e-4e1d-92cb-ccf0d40a21d4.png)

Any suggestions on how to make TexTBox2 bold letters?

**Comment by TEParsons** [comment]
This is a feature we're planning to add but haven't yet - currently, we don't show HTML tags like `<b>`, and adding them does mark those characters internally as bold, but we're still working on the code to actually render these characters in a different font weight. So textboxes have to be either all bold or all non-bold, for now. 

Watch this space though, we're doing a lot on Textbox currently!
