### ISSUE TITLE
ImageStim + Transpiler: start time parameter not correctly transpiled to JS

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#4283]
If the onset of an imagestim is "condition" based and a python operator is used, that operator is not correctly transpiled to Javascript (note that this example does correctly transpile in the ButtonStim - so it should be possible the same way).

e.g. if we have 2 sliders and want an image to pop up when both sliders have ratings. The `Start` parameter of that image would be `slider1.rating and slider2.rating` and that should be transpiled to `slider1.rating && slider2.rating` in JS. currently this will cause an error online due to translation error and the user must replace instances of `and` with `&&` (which means the experiment cannot be run locally.

**Comment by TEParsons** [comment]
I can't find the PR, but this is fixed in `release`! Essentially start/stop values were being treated as a special case rather than going through the same string-ification process as other params, so they weren't being transpiled.
