### ISSUE TITLE
Default Polygon color settings lead to drawing invisible stimulus.

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#4294]
This is not really a bug, rather a minor inconvenience. Using the default Polygon fill and edge colors leads to invisible stimulus (the same color as the default window background).
```python
from psychopy import visual, event, core

window = visual.Window()
circle = visual.Polygon(window, edges=32, radius=150, units='pix')

circle.draw()
window.flip()
event.waitKeys(keyList=['space'])
core.quit()
```
This behavior is also different from Builder defaults where fill and border color is `'white'`.

**Comment by mdcutone** [comment]
I see how this can be confusing for users. Thoughts @TEParsons?

**Comment by TEParsons** [comment]
I think this might be a carry over from before the colour rework - before, `None` would have meant "default" for some stimuli and "transparent" for others. Now it always means "transparent", which is better, but I'm guessing Polygon still has its default fill colour as `None` from when `None` meant "default". Should be as simple as changing the default from `None` to `'white'`, I'll just need to check it doesn't break anything else further down the line.
