### ISSUE TITLE
Windows - Cannot import QtWidgets from PyQt5

### ISSUE THREAD

**Issue by celstark** [psychopy/psychopy#4297]
Fresh install of Psychopy (both the January and August builds -- same) on Windows 10 and attempts to use the GUI methods fail.  Here's the output from the GUI demo:

```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\input\GUI.py", line 10, in <module>
    from psychopy import gui  # Fetch default gui handler (qt if available)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\gui\__init__.py", line 45, in <module>
    from .qtgui import *
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\gui\qtgui.py", line 35, in <module>
    from PyQt5 import QtWidgets
ImportError: DLL load failed: The specified procedure could not be found.
##### Experiment ended. #####
```

Here's manually doing the loads as asked for in another thread.
```
import PyQt5
from PyQt5 import QtWidgets
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

Craig

**Comment by ArielZJ** [comment]
I was literally in the process of writing out my bug report for the same problem when I noticed this issue. Let me add my own information:

I'm unable to run any .psyexp files at all without encountering this error message:

```
Welcome to PsychoPy3!
v2021.1.0
Generating PsychoPy script...

## Running: C:\Users\zelez\My Drive\tLab\Precision Phenomenology\Colour calibration\Isoluminance-Psychopy\test_lastrun.py ##
55.4408     INFO     Loaded monitor calibration from ['2021_09_15 12:12']
1.0988     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
Traceback (most recent call last):
  File "C:\Users\zelez\My Drive\tLab\Precision Phenomenology\Colour calibration\Isoluminance-Psychopy\test_lastrun.py", line 18, in <module>
    from psychopy import sound, gui, visual, core, data, event, logging, clock, colors
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\gui\__init__.py", line 45, in <module>
    from .qtgui import *
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\gui\qtgui.py", line 35, in <module>
    from PyQt5 import QtWidgets
ImportError: DLL load failed: The specified procedure could not be found.
##### Experiment ended. #####
```

I've tried installing and running all the standalone versions, both 32 and 64 bit, from v2021.1.0 onwards. All of them produce the same error for me.

My machine is a ThinkPad Carbon X7 running Windows 10 Pro version 21H1.

This problem seems to have come up a few times, but the advice in previous threads hasn't helped me:

 * [Sep 2018](https://github.com/psychopy/psychopy/issues/2040): Packaging issue that was solved in a future version
* [Feb 2019a](https://discourse.psychopy.org/t/error-when-trying-to-run-experiment/6855): problem was a university security system. I am running this on my private device
 * [Feb 2019b](https://discourse.psychopy.org/t/gui-error-in-psychpy-version-3-0-5/6792): unsolved
* [Feb 2019c](https://github.com/psychopy/psychopy/issues/2297): packaging issue, solved in future standalone update.

Help?

**Comment by ArielZJ** [comment]
I don't really know what I'm doing, but I get the impression it can't see the .pyd files for some reason. See here:

```
dir(PyQt5)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_os', '_path', 'colordict']
import pyo
from PyQt5 import QtGui
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by ArielZJ** [comment]
FYI, after an ungodly number of hours messing around, I finally managed to get an installation to work by installing through Anaconda.

**Comment by peircej** [comment]
I'm afraid I have no idea what would have caused PyQt not to load, just in a very very small number of users. Is it possible that you have another python/qt installation on your system and the two were conflicted?
PyQt and all the necessary files are certainly included in the current standalone release

**Comment by peircej** [comment]
I've just tested on a clean virtual machine (win10 pro) and I can't replicate the issue. I'm closing for now, pending any further reports and clues as to what this could be.

**Comment by sasaju** [comment]
I uninstall python3.6.4 and python launcher which in my system. Then, reboot，all run correctly. I think if only remove python's route in PATH maybe also can slove this problem.

**Comment by firejake308** [comment]
Ran into this same problem today. One possible problem is that my computer did not have Python before I installed PsychoPy from the installer, so I think that might be one of the preconditions to replicate this bug.

**Comment by andreifoldes** [comment]
> FYI, after an ungodly number of hours messing around, I finally managed to get an installation to work by installing through Anaconda.

I'm having the same issue and tried installing Psychopy through Anaconda creating a new environment, but it's still giving me the same error.

What fixed it for me was 
`pip install --upgrade --force-reinstall PyQt5
`

**Comment by adarshatimsina** [comment]
> > FYI, after an ungodly number of hours messing around, I finally managed to get an installation to work by installing through Anaconda.
> 
> I'm having the same issue and tried installing Psychopy through Anaconda creating a new environment, but it's still giving me the same error.
> 
> What fixed it for me was `pip install --upgrade --force-reinstall PyQt5 `

 Yup it worked for me too  and thanks btw
