### ISSUE TITLE
Text component uses expected duration, rather than duration (frames)

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#4313]
See [Discourse issue](https://discourse.psychopy.org/t/expected-duration-rather-than-duration-frames-is-setting-stimulus-timing/25381). Text stim is displayed for the duration of the "expected duration" rather than the requested duration when using duration (frames) - tested in version 2021.2.3 with the following 

![bug](https://user-images.githubusercontent.com/22459095/137382818-44973c7c-5f58-4049-8ac4-79c466df7135.png)

Users probably wouldn't do this, but I thought expected duration was not supposed to control stim duration

**Comment by TEParsons** [comment]
This no longer happens in 2022.1.1, so I'll close this issue but please do test this out on your own machine and reopen if this is specific to my setup
