### ISSUE TITLE
Loop variable referenced before defining, gives NameError

### ISSUE THREAD

**Issue by danaris** [psychopy/psychopy#4322]
In trying to put together a fairly simple project using the Builder, I came upon this error. I have two text stimuli, each with its text changing each repeat. Upon compilation, the second of these has its _initial_ value set to the loop variable `varA`—which is not yet set.

Attached are the Builder file and the compiled Python file zipped together (trial.zip), the loop variables file (trial-list-1.csv), and the program output (PsychoPyError.txt).

[trial-list-1.csv](https://github.com/psychopy/psychopy/files/7401028/trial-list-1.csv)
[trial.zip](https://github.com/psychopy/psychopy/files/7401030/trial.zip)
[PsychoPyError.txt](https://github.com/psychopy/psychopy/files/7401046/PsychoPyError.txt)

**Comment by TEParsons** [comment]
That's because text_2 has its text value set to "Constant" - meaning it's set at the start of the experiment, before the loop has started so before the loop values exist yet. You'll need to set it to "Set each repeat"
