### ISSUE TITLE
Data Saving Error

### ISSUE THREAD

**Issue by salilabwfu** [psychopy/psychopy#4325]
A participant reported to me today an error message that I have not encountered before. It is quite long and refers to an issue with gitlab:

“Unfortunately we encountered the following error: when flushing participant’s log for experiment, when uploading participant’s log for experiment, when saving logs from a previously opened session on the server. File exists. Another git process seems to be running in this repository, e.g. an editor opened by git commit’. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repositroy earlier: remove the file manually to continue. Try to run the experiment again. If the error persists, contact the experiment designer.”

Interestingly, the participant’s data seem to have saved with no problem. I have another participant’s data file with the same timestamp. Is it possible this occurred because both files were trying to save simultaneously? Is there any reason to think that the data file should not be trusted? I’ve run many participants in this study and this is the first I’ve seen this outcome. 

Thank you in advance for taking a look!

**Comment by TEParsons** [comment]
If GitLab is involved I'm guessing this was encountered by the participants when running online via Pavlovia, if so then this issue more appropriate for the [psychojs](https://github.com/psychopy/psychojs) repo. I'd be happy to copy it across but it might be better if you do it as it means you'll get notifications of status changes!
