### ISSUE TITLE
Crash upon second use of color picker

### ISSUE THREAD

**Issue by danaris** [psychopy/psychopy#4331]
When attempting to choose the color of text stimuli on macOS, I have experienced a recurring bug that causes PsychoPy to crash reliably on either the first or second use of the color picker.

The most reliable reproduction method I have found is as follows:

- Create a new project
- Create a text stimulus
- Go to the Appearance tab
- Click on the color picker 
- Select a color on the right
- Click Insert (sometimes crashes here)
- Click OK or click on the color picker again, and it will crash here.

I have attached a macOS crash log:
[PsychoPy Crash Log.txt](https://github.com/psychopy/psychopy/files/7443013/PsychoPy.Crash.Log.txt)

**Comment by mdcutone** [comment]
Thanks for reporting this. We're aware of the issue and are trying to resolve it.
