### ISSUE TITLE
Set monospaced fonts as the default font for Coder and the code component in Builder

### ISSUE THREAD

**Issue by Tiger-0512** [psychopy/psychopy#4349]
Monospace fonts allocate equal space for each character.
e.g., The letter 'i' is given as much horizontal space as the letter 'k'.
That may look unnatural for other types of text and typography, but it's perfect for coding.

These are the candidates.
- [Fira code](https://fonts.google.com/specimen/Fira+Code)
- [Ubuntu mono](https://fonts.google.com/specimen/Ubuntu+Mono)
- [Iosevka](https://github.com/be5invis/Iosevka/)

We may have to consider other fonts.

**Comment by mdcutone** [comment]
Perhaps we should default to one of the monospace fonts we already ship with? @TEParsons

**Comment by TEParsons** [comment]
Currently the default font is monospace - it should be Jetbrains Mono. I think what's most likely happening is it's not detecting it on your machine and so is defaulting to the system default - what OS are you on?

**Comment by Tiger-0512** [comment]
Thank you for your prompt response.
I found that the monospace font is set in the newest version of PsycoPy(I mainly use PsycoPy v2021.1.4).
I am sorry for the lack of confirmation.
