### ISSUE TITLE
Flake8 and LGTM.com issues

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [psychopy/psychopy#4354]
Would you accept PRs for [Flake8](https://flake8.pycqa.org) and [LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/alerts/?severity=error) alerts, at least those that seem more relevant?

**Comment by mdcutone** [comment]
Generally, its okay to submit PRs fixing LGTM issues, particularly the ones marked as "Errors". However, avoid fixing lots of issues across multiple files in a single PR. Doing so may cause merge conflicts and other headaches for everyone else working on the project.

Don't bother working on Flake8 stuff for now. If you want to help with style issues, converting docstrings to [NumpyDoc](https://numpydoc.readthedocs.io/en/latest/format.html) format and general documentation cleanup would be helpful.

**Comment by DimitriPapadopoulos** [comment]
Some Flake8 issues are also LGTM.com issues, but I get it: too many changes, and especially stylistic ones, will disturb the workflow of other contributors.
