### ISSUE TITLE
PsycoPy keeps quitting

### ISSUE THREAD

**Issue by harkiran1** [psychopy/psychopy#4384]
Hello,

I am using PsychoPy for an assignment i have however it keeps quitting every time i open it or try to use it. In case you needed more information i am using my mac book and the mac OS version is 12.0.1.

**Comment by mdcutone** [comment]
Does the application quit unexpectedly or does this only happen when running experiments?

**Comment by harkiran1** [comment]
Hi,

Thank you for getting back to me. The issue seems to have been resolved.


Thanks.
________________________________
