### ISSUE TITLE
The framerate is more than 180hz in macOS Monterey ?!

### ISSUE THREAD

**Issue by huyiting11** [psychopy/psychopy#4386]
Hi there,
after I upgrade my macOS to Monterey 12.0.1, I find that the framerate is more than 180hz in my experiment data, and it aways changes a lot, sometimes it is even 205hz，it was about 60h z before?!! How can it be? My Mac is mac book air 2017, and it don't have the function to change the screen refresh framete, my screen refresh is 60hz.

**Comment by m-macaskill** [comment]
Monterey introduced support for variable refresh rate/adaptive sync/free sync. Although this shouldn't affect your 2017 MBA, it looks like you have been caught out by a quirk. Regardless, this issue really belongs on the forum as it's not a specific code issue, and I see you have already cross-posted there: <https://discourse.psychopy.org/t/the-framerate-is-more-than-180hz-in-macos-monterey/26101> so will close this issue for the time being.
