### ISSUE TITLE
Required "Experiment info" fields

### ISSUE THREAD

**Issue by richlv** [psychopy/psychopy#4412]
According to https://discourse.psychopy.org/t/require-filling-in-experiment-info-fields/7014 , it is not currently possible to mark fields as required for the locally run experiments.
It does seem to be possible for the online experiments: https://discourse.psychopy.org/t/demographic-form-at-the-beginning-of-online-experiments/9773 .
Would be great to have such a capability also for the local experiments.

**Comment by jessicabrinegar** [comment]
@TEParsons Has this issue been addressed by any chance?

**Comment by TEParsons** [comment]
Not yet no, but it's on the list!

**Comment by ainazay** [comment]
@TEParsons Hi, I'm trying to work on this feature. I was wondering if you'd know which folder and where exactly the code is located for the online experiments. I was looking to adapt it for the local experiments (are they also located in the same location?) to make the fields there, required, too. Thanks!
