### ISSUE TITLE
Polygon Component Line Width (maybe more) don't update on Every Repeat

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#454]
Quick Bug Report - when you change attributes with set "Set Every Repeat" for a polygon component in Builder, the attributes are still all being defined at initiation and not during frame or routine loops. I'll try to throw in a quick fix, but wanted to report it in case I don't. 

Cheers,
Erik

**Comment by hoechenberger** [comment]
Does this problem still exist?

**Comment by kastman** [comment]
Don't know when this was fixed, but verified good in 1.83.04 and 1.84.02!
