### ISSUE TITLE
PTB sound not able to play mono sounds

### ISSUE THREAD

**Issue by 4bgt** [psychopy/psychopy#4542]
When generating sounds via 

    import psychtoolbox as ptb
    from psychopy import prefs
    prefs.hardware['audioLib'] = 'PTB'
    prefs.hardware['audioLatencyMode'] = '3'
    from psychopy import sound

    mySound = sound.Sound('A',secs=3)    
    now = ptb.GetSecs()
    print(now)
    mySound.play(when=now+0.5)  # play in EXACTLY 0.5s

using PTB I am getting the following Exception: Number of columns of audio data matrix doesn't match number of output channels of selected audio device.

I guess it has something to do with the generated sound being mono instead of stereo, since stereo *.wav files can be played without creating this problem, but mono *.wav files produce the same error.

Traceback (most recent call last):
 line 687, in <module>
    mySound = sound.Sound('A',secs=3)    
  File "\psychopy\sound\backend_ptb.py", line 333, in __init__
    self.setSound(value, secs=self.secs, octave=self.octave,
  File "\psychopy\sound\backend_ptb.py", line 428, in setSound
    _SoundBase.setSound(self, value, secs, octave, hamming, log)
  File "\psychopy\sound\_base.py", line 186, in setSound
    self._setSndFromNote(value.capitalize(), secs, octave,
  File "\psychopy\sound\_base.py", line 225, in _setSndFromNote
    self._setSndFromFreq(thisFreq, secs, hamming=hamming)
  File "\psychopy\sound\_base.py", line 241, in _setSndFromFreq
    self._setSndFromArray(outArr)
  File "\psychopy\sound\backend_ptb.py", line 500, in _setSndFromArray
    self.track = audio.Slave(self.stream.handle, data=self.sndArr,
  File "\site-packages\psychtoolbox\audio.py", line 289, in __init__
    self.fill_buffer(data)
  File "\site-packages\psychtoolbox\audio.py", line 232, in fill_buffer
    buffer = Buffer(stream=self, data=data)
  File "\site-packages\psychtoolbox\audio.py", line 249, in __init__
    self.handle = PsychPortAudio('FillBuffer', self.stream.handle,
Exception: Number of columns of audio data matrix doesn't match number of output channels of selected audio device.

**Comment by mdcutone** [comment]
What version of PsychoPy are you using? Running your code and I cannot replicate the issue.

**Comment by 4bgt** [comment]
2021.2.3 using anaconda python 3.8.8

**Comment by peircej** [comment]
I also can't replicate this (using the current dev branch) so I'm closing for now but reopen if this is confirmed in the current code
