### ISSUE TITLE
Two small graphical glitches in the Builder

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#4604]
I don't know if there is something that can be done about this at the PsychoPy end, but I've experienced this over and over on multiple computers (all Windows) and decided to report just in case. See the attached gif, it shows:
1. a misaligned horizontal line when trying to rescale the flow part of the Builder
2. the "Insert ..." buttons in the flow part partially disappearing when scrolling the flow horizontally.

![psychopy_small_vis_glitches](https://user-images.githubusercontent.com/8452354/153060713-18e45dc2-edf9-42d6-ad9e-20b861178aef.gif)

**Comment by mdcutone** [comment]
Thanks for pointing these out. First issue is likely a glitch in the GUI toolkit we're using. The second one is something we can fix.
