### ISSUE TITLE
Failed building wheel for pyWinhook

### ISSUE THREAD

**Issue by pavi1303** [psychopy/psychopy#4615]
I'm using the Pycharm IDE and the python version is 3.9.7 and I tried installing PsychoPy using pip. But when I do that, I get an error which says - Failed building wheel for pyWinhook and 
swig.exe -python -o pyWinhook/cpyHook_wrap.c pyWinhook/cpyHook.i
      error: command 'swig.exe' failed: None
![image](https://user-images.githubusercontent.com/59095277/153520549-0362e5d2-7565-4e9a-8267-906e2893cb27.png)

I installed swig from SourceForge and I added it to the path variable. It doesn't seem to solve the problem. Any recommendations would be helpful. Thanks!

**Comment by peircej** [comment]
pywinhook is a pain because it needs compiling but Christoph Gohlke has done a rather impressive job of packaging up wheels for a range of packages so you can probably fetch it from his set like this:

`pip install --extra-index-url https://www.lfd.uci.edu/~gohlke/pythonlibs pyWinhook`

**Comment by pavi1303** [comment]
I had a very simple workaround. So, I installed the standalone version of the PsychoPy software. When doing this, PsychoPy installs the python version that is compatible with it. So, when I create a new project within Pycharm all I had to do was to use the Python.exe available in the Psychopy installed folder to create a virtual environment. This automatically loaded all the packages including Psychopy and all the additional dependencies. Anyone running into issues installing PsychoPy with Pycharm or any other IDE please follow the above procedure.
