### ISSUE TITLE
ParallelPort doesn't work because of underlying pyparallel failure

### ISSUE THREAD

**Issue by mscheltienne** [psychopy/psychopy#4667]
Hello, to raise awareness on this, we experienced a failure when using `psychopy.parallel` on our Linux computers with an LPT port on a PCIe extension slot. The failure is described here: https://github.com/pyserial/pyparallel/issues/15

As I don't feel pyparallel is maintained, maybe you could consider moving the relevant code to psychopy directly.

**Comment by mscheltienne** [comment]
I did find a cleaner solution, as explained in https://github.com/pyserial/pyparallel/issues/15 but it is IMO a problem that the parallel class does not work by default on Linux Ubuntu 20.04.

**Comment by TEParsons** [comment]
Is there a package you've found works on Ubuntu 20.04? We already query the OS and change the backend used accordingly, so could add in a check for Ubuntu version and switch to a different package for newer versions

**Comment by mscheltienne** [comment]
I am not aware of a different package than `pyparallel` to interact with the parallel port in Python. That would be indeed a good solution.. 

Alternatively, even some documentation to explain the problem and that it can be resolved by blacklisting the `lp` module as described [here](https://github.com/pyserial/pyparallel/issues/15#issuecomment-1065089349) would be an improvement.
