### ISSUE TITLE
Error when installing version 2022.2.1 -- about tobii resrearch

### ISSUE THREAD

**Issue by RyanY11** [psychopy/psychopy#4668]
Hi, just got an error said:

ERROR: Could not find a version that satisfies the requirement tobii-research (from psychopy) (from versions: none)
ERROR: No matching distribution found for tobii-research (from psychopy)

I use pip to upgrade from 2021.1.4, but the same error occured when I tried it from 2021.2.3

**Comment by isolver** [comment]
The pip error suggests that tobii-research does not support the version of Python being used. What version are you using? I think tobii-research currently supports Python <= 3.8

**Comment by Gumphrey** [comment]
tobii-research is not compatible with python 3.7, which I just tried.  (same error message as RyanY11.)   I will update if I get it working.

**Comment by peircej** [comment]
Tobii Research appears to support only Python3.8 (at least publicly on PyPI):
https://pypi.org/project/tobii-research/1.10.1/#files

(our installation pages recommend using Python 3.8 for exactly this reason - in our experience it's the most widely supported for hardware at the moment)
