### ISSUE TITLE
AttributeError when creating new Pavlovia project from Builder

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#4683]
Hi!

I get an AttributeError when I do the following:
* Running Windows 10, 64 bit, PsychoPy v2022.1.1.  
* Got the Builder open, being logged in on Pavlovia as tpronk.
* Click Pavlovia.org -> New

This is the full error message:
```
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\app\pavlovia_ui\menu.py", line 127, in onNew
    if pavlovia.getCurrentSession().user.username:
AttributeError: 'User' object has no attribute 'username'
```

Best, Thomas

**Comment by bastosfh** [comment]
Hi @tpronk!

I'm having the exact same issue on Ubuntu 21.10 and PsychoPy v2022.1.1.

> Traceback (most recent call last):
>   File "/home/flavio/.local/lib/python3.9/site-packages/psychopy/app/pavlovia_ui/menu.py", line 127, in onNew
>     if pavlovia.getCurrentSession().user.username:
> AttributeError: 'User' object has no attribute 'username'

I'm available to run some tests :)

Best,
Flavio
