### ISSUE TITLE
Unexpected Token Error when on Pavlovia

### ISSUE THREAD

**Issue by eawhit** [psychopy/psychopy#4702]
Hello,

I have a PsychoPy program that works on my laptop, but when it's uploaded to Pavlovia it gets stuck on the 'Initialising experiment' phase. Below is the error I receive.

Alert 4210:JavaScript Syntax Error in 'Begin JS Experiment' tab. See 'Line 1: Unexpected token' in the 'Begin JS Experiment' tab.
	For further info see https://psychopy.org/alerts/4210.html

In my python code, I use the 'import random' function in order to randomize colors in PsychoPy. I read somewhere that this package does not function in JS. I'm not sure if this is the issue, but everything works online up to the point where the 'random' function is utilized. (I took the project apart and re-uploaded to Pavlovia piece-by-piece to determine for sure when the error occurs). 

If anyone has any suggestions please let me know! Thank you!

Elise

**Comment by peircej** [comment]
I don't think this is a bug as such. You shouldn't need to do `import random` and the auto-translator doesn't know how to handle that. There are quite a number of discussions on the forum about how to randomise/shuffle items and I think this is better handled there
