### ISSUE TITLE
visual.ShapeStim ctypes.ArgumentError

### ISSUE THREAD

**Issue by gcyoung1** [psychopy/psychopy#4716]
I got this error when I set the autoDraw to True for a visual.shapeStim stimulus:
  
File "C:\Computer Science\Educ 464\Experiments\hollow_dots\hollow_dots_lastrun.py", line 446, in <module>
    win.flip()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\window.py", line 1082, in flip
    thisStim.draw()
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\shape.py", line 609, in draw
    GL.glLineWidth(self.lineWidth)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

This is the (abridged) code:
**Begin Routine:**
reference_dot_xs = np.random.randint(-150, -10, num_reference_dots)
reference_dot_ys = np.random.randint(-70, 70, num_reference_dots)
reference_dot_xys = np.stack((reference_dot_xs, reference_dot_xs), axis=-1)

reference_dot_stim = visual.ShapeStim(
    win=win, 
    units="pix",
    colorSpace="rgb",
    lineWidth="5",
    lineColor="black",
    fillColor="black",
    vertices=reference_dot_xys,
    size=5,
    autoDraw=False
)

**Each Frame:**
frame += 1
if frame == 29:
    target_dot_stim.autoDraw = True
    reference_dot_stim.autoDraw = True
elif frame == 41:
    target_dot_stim.autoDraw = False
    reference_dot_stim.autoDraw = False

**Comment by TEParsons** [comment]
The problem is that you've supplied `"5"` as the lineWidth rather than `5`; this is something the class could handle so I'll add in a quick conversion so in future it knows that `"5"` just means 5, but in the meantime removing the quotes should fix your code :)
