### ISSUE TITLE
2022.1.1: Unable to find projects under groups using the Psychopy Pavlovia Interface

### ISSUE THREAD

**Issue by miguelfradinho** [psychopy/psychopy#4723]
In release 2022.1.1, the interface to create and sync the projects on Pavlovia was overhauled.
However, on the previous release it was possible to also find projects that were under gitlab groups.
In this release, if I try to search for a project that clearly exists on gitlab under the `test_pavlovia_groups`
![imagem](https://user-images.githubusercontent.com/24386108/160112112-fecb79fc-7793-4cff-8efe-971d64e272d0.png)

No results are shown on the PsychoPy interface:
![imagem](https://user-images.githubusercontent.com/24386108/160112191-d7fafcf9-b943-4523-a8a9-06d202458447.png)

But shows up on pavlovia.org's dashboard:
![imagem2](https://user-images.githubusercontent.com/24386108/160508965-c90bb815-3890-4ac6-a97f-48b16b425c00.png)

Was this change in only allowing personal projects intentional or is it a bug?

**Comment by TEParsons** [comment]
I think this is most likely that the Pavlovia API (which PsychoPy uses to search projects) doesn't consider your current login to be a valid level of authentication to show that project, for whatever reason. It may be that you aren't logged in, or you are logged in but the authentication token of a user in a group which has access isn't accepted by the API as sufficient.

**Comment by miguelfradinho** [comment]
Is the Pavlovia API the same API [pavlovia](https://pavlovia.org/) uses under the hood?
If so, then I don't think that seems to be the case, as I'm able to see and interact with them (e.g change to pilot) through the dashboard, e.g.
![imagem](https://user-images.githubusercontent.com/24386108/160508965-c90bb815-3890-4ac6-a97f-48b16b425c00.png)
(I'll also edit the original post to include this image)

Additionally, the feature was also present in the latest 2021 version, 2021.2.3, as seen here: 
![imagem](https://user-images.githubusercontent.com/24386108/160513168-58969a56-a87b-4d0b-9a60-0fffcff2030d.png)

I didn't read the pull requests related to the update in UI, so maybe it changed from gitlab API to Pavlovia API?
Though, still wondering regarding the 1st case of this point, where it's still present in pavlovia.org

**Comment by TEParsons** [comment]
The Pavlovia API is for interacting with Pavlovia from outside - so I think it's a different system than the internal search function uses. And yep, exactly right - between 2021 and 2022 we moved from using the gitlab API to the pavlovia API, which is why it's different.

Another possibility is that PsychoPy is using a different authentication token to send requests to the API than the website does

**Comment by miguelfradinho** [comment]
Ah, that explains it

Should this probably be reclassified as feature request or does it still technically fall under a bug because of change in behaviour across versions?

**Comment by TEParsons** [comment]
This is definitely a bug, and one which I believe is fixed now! #4791 should solve it.

It's essentially that using `resquests.get` doesn't include the authentication, so we needed to be using the `get` method of a `requests.Session` object instead.
