### ISSUE TITLE
shapes.py and stim3d.py demos crash in 2022.1.2

### ISSUE THREAD

**Issue by dcnieho** [psychopy/psychopy#4728]
As per #4722, (at least) two demos don't work in 2022.1.2:

```
## Running: C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\shapes.py ##
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
1.6686     WARNING     Monitor specification not found. Creating a temporary one...
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\shapes.py", line 32, in <module>
    donut = ShapeStim(win, vertices=donutVert, fillColor='orange', lineWidth=0, size=.75, pos=(-.2, -.25))
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\contrib\lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\shape.py", line 486, in __init__
    self.vertices = vertices
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\shape.py", line 553, in vertices
    WindowMixin.vertices.fset(self, value)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\basevisual.py", line 1378, in vertices
    self._vertices = Vertices(value, obj=self, flip=self.flip, anchor=self.anchor)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\layout.py", line 640, in __init__
    assert len(verts.shape) == 2, (
AssertionError: Vertices must be coercible to a Nx2 numpy array
################ Experiment ended with exit code 1 [pid:93284] #################
```
and
```
## Running: C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\stim3d.py ##
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Alert 8105: Color space attribute `.colorSpace` is no longer in use, as colors are no longer tied to one space.
Hello from the pygame community. https://www.pygame.org/contribute.html
For more info see https://docs.psychopy.org/alerts/8105.htmlAlert 8110: RGB attribute `.diffuseRGB` is no longer in use, as non-RGB colors now handle their own conversion.
For more info see https://docs.psychopy.org/alerts/8110.htmlTraceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\demos\coder\stimuli\stim3d.py", line 18, in <module>
    redLight = LightSource(win, pos=(0, 1, 0), diffuseColor=(.5, 0, 0),
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\contrib\lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 89, in __init__
    self.diffuseColor = diffuseColor
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 139, in diffuseColor
    setColor(self, value, colorSpace=self.colorSpace, operation=None,
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\helpers.py", line 222, in setColor
    setattr(obj, colorAttrib, color)
  File "C:\Program Files\PsychoPy\lib\site-packages\psychopy\visual\stim3d.py", line 138, in diffuseColor
    self._diffuseColor = np.asarray(value, np.float32)
TypeError: float() argument must be a string or a number, not 'Color'
################ Experiment ended with exit code 1 [pid:98368] #################
```

**Comment by TEParsons** [comment]
The error in `shapes.py` is essentially the new `psychopy.layout.Vertices` class being over-zealous with validating values - it didn't occur to me when writing it that vertices with a hole in would be a 3d array. That one is fairly easy to fix so I'll have a PR in for it ASAP.

The error in `stim3d` is harder to fix - it looks like `psychopy.colors.Color` objects aren't accepted by 3d objects at all, when they should be really for consistency with the rest of the library. This one we can work on for the next major release as it's a bit too big of a change for just a bug fix release.

**Comment by mdcutone** [comment]
Lots of recent changes might have broken things a bit, but we need to think through how to handle 2D and 3D going forward. 

Material colors for 3D objects have to be handled differently than colors in other stimuli.

Also 3D objects don't and shouldn't use `layout` stuff, but rather `RigidBodyPose` for positioning to be consistent with PsychXR and 3D engines in general (units like `cm`, `deg`, etc. are meaningless in 3D). Vertices for 3D objects are stored as arrays on the GPU and the `RigidBodyPose` object computes the transformation matrices to position them in the scene. This is a bit different than how we handle 2D shapes where the vertices are stored in client memory space and mapped during a draw (for the most part). Doing transformations on the data held by `Vertices` is not ideal. The solution here might be to use `Vertices` to hold vertex data as Numpy arrays which reference data in a VBO and have the option to use `RigidBodyPose` to transform them. We can give the illusion to the user of being able to manipulate vertex data directly like the would with 2D objects but really they are dealing with data in a memory mapped VBO.

**Comment by naiqixiao** [comment]
Hi,

Do you know when we can expect this color issue being fixed? Or is there another way to set LightSource for 3D object display?

Thanks!

**Comment by mdcutone** [comment]
We have a fix for the issue nearly ready, should soon be available soon in a bug fix release. The system we have here simplifies working with lighting, otherwise you'd need to use OpenGL directly which is your only option at this time.

**Comment by naiqixiao** [comment]
That's good to hear! Thanks!
