### ISSUE TITLE
Mouse click inaccurate position

### ISSUE THREAD

**Issue by dedp88** [psychopy/psychopy#4731]
I'm new to PsychoPy. I'm using the 2022.1.2 version on a Mac with Retina Display - Monterey.

I'm testing the simplest experiment - a mouse click over an image should play audio and then clicking another image should terminate the trial. The first image is at the (0,0) and i'm using a star from the polygon options, and the second one is at (-0.4, 0). The position of both images is correct when displayed; however, clicking over the star does not play the audio. The audio plays when the upper right corner is clicked. So the mouse event is not getting the same position as the monitor sets. The (0,0) for the mouse is moved to the upper right corner.

**Comment by mdcutone** [comment]
Please post a minimal working example to help us determine the cause of the issue.
