### ISSUE TITLE
cannot animate width/height of visual.Rect in v2022.1.2

### ISSUE THREAD

**Issue by dcnieho** [psychopy/psychopy#4739]
Tagging @marcus-nystrom.

The below code worked in v2021.2.3 (I see a fixation cross that changes in size) but not in v2022.1.2 (size does not change). Is this a bug or should i animate a rect differently?

```
from psychopy import visual, event, core
import numpy as np

win = visual.Window(monitor='testMonitor')
screen_refresh_rate = float(win.getActualFrameRate())
outer_diameter=0.5
inner_diameter=0.1
outer_color = 'black'
inner_color = 'white'
units = 'deg'

line_vertical = visual.Rect(win, width=inner_diameter, height=outer_diameter,
                            fillColor=inner_color, units = units)
line_horizontal = visual.Rect(win, width=outer_diameter, height=inner_diameter,
                            fillColor=inner_color, units = units)

tick = 0
while 1:
    target_size = np.abs(1 - np.sin(3 * tick / screen_refresh_rate + 4*np.pi/2)) + 0.2
    print(target_size)

    line_vertical.height = target_size
    line_horizontal.width = target_size

    line_vertical.draw()
    line_horizontal.draw()
    win.flip()

    k = event.getKeys()
    if 'escape' in k:
        win.close()
        break
    
    tick += 1
```

**Comment by TEParsons** [comment]
We changed how objects lay themselves out in 2022.1, but this change is purely on the back end so behaviour should stay the same - so yes this is a bug :) I'll look into why it's no longer working

**Comment by dcnieho** [comment]
@TEParsons: I see you pushed a commit that hopefully fixes this. Would you be able to make a new bugfix release soon? This bug breaks our Titta eye tracker interface, and we can't use the latest Tobii SDK with anything older than 2022.1 because it requires Python 3.8, so we're in a catch 22.
(Note by the way that the button on the psychopy website still says python 3.6: "Standalone PsychoPy® 2022.1.2 for 64bit Windows (using Python3.6)".

**Comment by TEParsons** [comment]
That pull request may not make it into the upcoming bug fix release, but as this bug is specific to the `width` and `height` setters you can get around it by instead specifying the rect's size as `size=(width, height)`

**Comment by dcnieho** [comment]
Thanks, that solves that problem indeed.

But i discovered two further problems that i think may be bugs in psychopy. The following code produces a rotating cross, one arm of which flickers on and off on version 2021.2.3. However, on 2022.1.2, the cross doesn't rotate, it only deforms, and instead of one arm not being drawn when `np.nan` is given as position, its is draw in the top-left corner of the screen (`(np.nan,np.nan)` is apparently interpreted as `(0.66667,0.5)` for some reason).

```
from psychopy import visual, event, core
import numpy as np

win = visual.Window(monitor='testMonitor')
screen_refresh_rate = float(win.getActualFrameRate())
outer_diameter=2.5
inner_diameter=0.5
inner_color = 'white'
units = 'deg'

line_vertical = visual.Rect(win, width=inner_diameter, height=outer_diameter,
                            fillColor=inner_color, units = units)
line_horizontal = visual.Rect(win, width=outer_diameter, height=inner_diameter,
                            fillColor=inner_color, units = units)

tick = 0
while 1:
    target_ori  = 45*(np.sin(3 * tick / screen_refresh_rate)+1)

    line_vertical.ori = target_ori
    line_horizontal.ori = target_ori

    if tick%30<10:
        line_vertical.pos = (np.nan,np.nan)
    else:
        line_vertical.pos = (0.,0.)

    line_vertical.draw()
    line_horizontal.draw()
    win.flip()

    k = event.getKeys()
    if 'escape' in k:
        win.close()
        break
    
    tick += 1
```

**Comment by TEParsons** [comment]
That is indeed a bug, so good spot! A user on the forum beat you to it though - so we have a fix in for it:
https://github.com/psychopy/psychopy/pull/4772

Essentially it's that rotation was applied to the base vertices so the corners were moving around the edges of the original object bounds rather than creating new bounds.

**Comment by dcnieho** [comment]
Glad that's already fixed! Is the change in how `(np.nan,np.nan)` is interpreted as a pos also something that you consider a regression that should be fixed?

**Comment by dcnieho** [comment]
@TEParsons i wanted to ping on my last comment, "Is the change in how (np.nan,np.nan) is interpreted as a pos also something that you consider a regression that should be fixed?"
Should i open a new issue since this one is closed now?
