### ISSUE TITLE
Change foregroung and background colors of gratings

### ISSUE THREAD

**Issue by sowmyamanojna** [psychopy/psychopy#4777]
Thank you for this wonderful package.  

I would like to know if there are any options to change the background color of gratings. Currently, only the foreground color can be specified, while the background color is automatically calculated. 

Any help or direction in this regard is highly appreciated. Thanks!

**Comment by peircej** [comment]
This is really by design. See the discourse topic at https://discourse.psychopy.org/t/controlling-gratingstim-colors/1261 (although it's come up more than once). I don't want to change the software to encourage something that I would generally discourage. If that makes sense
