### ISSUE TITLE
Building non-symbolic number comparison task

### ISSUE THREAD

**Issue by Anki-82t** [psychopy/psychopy#4778]
![download](https://user-images.githubusercontent.com/103921154/163765094-5eaf46dd-f529-40c7-a778-fe0d17dc5373.jpg)
I want to build an experiment, where a few dots would be presented in two boxes, without an outline. The size and number of the dots in each box should vary randomly in a fixed range. I tried using builder for this but I am failing at the part on how to split the screen.

**Comment by eswarnaveen** [comment]
I also need help with this, like how to vary the size of dots to different sizes.

**Comment by m-macaskill** [comment]
Issues here at Github are for reporting problems with the PsychoPy source code itself, not for support requests about how to implement experiments. The place to get assistance like that is at the dedicated support forum at https://discourse.psychopy.org
