### ISSUE TITLE
ExpInfo array not closed properly when no properties set in builder

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#4799]
In 2022.1.3 (Windows 64-bit), if you remove all start up properties in experiment settings (participant, session etc) so there is nothing at all, the python generated will not close the expInfo array correctly, leaving you with something like so:

expInfo = }

I've attached an example script for information.  It is rare that anyone would not want start up parameters, but there could well be instances (like we have had).

[expinfo-eg.zip](https://github.com/psychopy/psychopy/files/8583103/expinfo-eg.zip)

**Comment by TEParsons** [comment]
This is one of those that sits in between user error and bug - as there is a safe method to not show a dialog at all (deselecting "show info dialog"), but also PsychoPy should be able to handle blank values for that control. I'll look into making the code construction more robust to handle it.

**Comment by frankgasking** [comment]
Ah, I didn't notice the show info dialog option - thanks for flagging that up.
