### ISSUE TITLE
PsychoPy3 (2020.2.3) crashing in Monterey 12.3.1

### ISSUE THREAD

**Issue by jooyun-ha** [psychopy/psychopy#4812]
Hello, 

my mac version is Monterey 12.3.1 and psychopy installed version PsychcoPy3-2020.2.3.
When I open the application, the message below comes up and come up with warning message saying
'PsychoPy Error. Open Console or Terminate'

I tried clearing userPrefs.cfg and appData.cfg according to the link below.
https://psychopy.org/troubleshooting.html
And tried uninstalling the application and installed couple of other versions.
How can I solve this problem? 

Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/__init__.py”, line 378, in __getattr__
AttributeError: ‘NoneType’ object has no attribute ‘_create_shadow_window’

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/__boot__.py”, line 498, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/__boot__.py”, line 476, in _run
  File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 104, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 100, in main
  File “/Applications/PsychoPy.app/Contents/Resources/psychopyApp.py”, line 28, in start_app
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py”, line 226, in __init__
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/_psychopyApp.py”, line 262, in onInit
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/__init__.py”, line 7, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/builder.py”, line 46, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/dialogs/__init__.py”, line 27, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/app/builder/validators.py”, line 27, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/window/__init__.py”, line 1896, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/__init__.py”, line 384, in __getattr__
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/__init__.py”, line 100, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/lib.py”, line 141, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/gl/lib_agl.py”, line 49, in <module>
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/lib.py”, line 118, in load_library
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyglet/lib.py”, line 286, in load_framework
ImportError: Can’t find framework /System/Library/Frameworks/OpenGL.framework.

**Comment by peircej** [comment]
This was fixed in newer versions of PsychoPy. In Big Sur, Apple moved one of the libs to a new location so we had to change things in PsychoPy. I'd recommend you use [the latest version](https://github.com/psychopy/psychopy/releases) if possible, or [2020.2.10](https://github.com/psychopy/psychopy/releases/tag/2020.2.10) if you need compatibility with the 2020.2 release series

**Comment by jooyun-ha** [comment]
Thank you for the comments. I appreciate it. It's working well after downloading the latest version. Thank you :)
