### ISSUE TITLE
Cannot Install -- error: metadata-generation-failed

### ISSUE THREAD

**Issue by BunnyRider** [psychopy/psychopy#4817]
This is what I receive when I try to install. I am extremely new at python so I am sorry if this is a silly question. Thank you so much for any help

> Collecting PsychoPy==2022.1.2
>   Using cached PsychoPy-2022.1.2.zip (25.9 MB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Requirement already satisfied: requests[security] in c:\users\18508\pycharmprojects\pythonproject\venv\lib\site-packages (from PsychoPy==2022.1.2) (2.27.1)
> Collecting cryptography
>   Using cached cryptography-37.0.2-cp36-abi3-win_amd64.whl (2.4 MB)
> Requirement already satisfied: numpy in c:\users\18508\pycharmprojects\pythonproject\venv\lib\site-packages (from PsychoPy==2022.1.2) (1.22.3)
> Requirement already satisfied: scipy in c:\users\18508\pycharmprojects\pythonproject\venv\lib\site-packages (from PsychoPy==2022.1.2) (1.8.0)
> Collecting matplotlib
>   Using cached matplotlib-3.5.2-cp310-cp310-win_amd64.whl (7.2 MB)
> Requirement already satisfied: pandas in c:\users\18508\pycharmprojects\pythonproject\venv\lib\site-packages (from PsychoPy==2022.1.2) (1.4.2)
> Requirement already satisfied: pillow in c:\users\18508\pycharmprojects\pythonproject\venv\lib\site-packages (from PsychoPy==2022.1.2) (9.1.0)
> Collecting glfw
>   Using cached glfw-2.5.3-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl (492 kB)
> Collecting pygame
>   Using cached pygame-2.1.2-cp310-cp310-win_amd64.whl (8.4 MB)
> Collecting pyo
>   Using cached pyo-1.0.4.tar.gz (6.1 MB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
> 
>   error: subprocess-exited-with-error
>   
>   python setup.py egg_info did not run successfully.
>   exit code: 1
>   
>   [6 lines of output]
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "C:\Users\18508\AppData\Local\Temp\pip-install-htn358f_\pyo_47a37c2234254aa38dd3aa3356f0cf58\setup.py", line 293, in <module>
>       for f in os.listdir(data_files_common_path)
>   FileNotFoundError: [WinError 3] The system cannot find the path specified: 'win64dlls\\win64_pyo_data_files_common'
>   [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> Encountered error while generating package metadata.
> 
> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
>

**Comment by peircej** [comment]
I don't know what that error is but I don't believe it's an error in PsychoPy. f you're really really needing to install PsychoPy to an existing Python installation then use `pip install psychopy` with a Python 3.8 installation (it looks like you've got Python 3.10 which will be harder to get things working on due to dependencies). 

But for a beginner I really strongly recommend you install the standalone instead! That's what we support directly because we can check and update the dependencies

**Comment by hiki-t** [comment]
Actually, I also encountered this problem and found a work around.
My environment, OS Ubuntu 18.04

There seems to be a problem with the latest pip (e.g. 22.2.2).

[stackoverflow.com](https://stackoverflow.com/questions/71009659/note-this-error-originates-from-a-subprocess-and-is-likely-not-a-problem-with)

I downgraded to
pip==21.3.1

and the error is gone.
