### ISSUE TITLE
Circle-Stim doesn't update radius when redrawing in 2022.1.2

### ISSUE THREAD

**Issue by The-C-Wolf** [psychopy/psychopy#4824]
I implemented a pulsating circle a while ago and just noticed, that the pulsing no longer works.

My current workaround is to downgrade to some version from last year (e.g. 2021.1.3), where it still works.

### A minimal implementation:

```python
from psychopy import visual

win = visual.Window(size=(500,500), fullscr=False, units="pix", color="white")
circle = visual.Circle(win, radius=5, units="pix", lineColor="black", fillColor="grey")

for i in range(100):
    circle.setRadius(circle.radius + 2)
    circle.draw()
    win.flip()
```

### The faulty behavior in the latest 2022.1.2:
- the circle.radius property actually changes its value
- but the circle keeps a constant (initial) size

I just noticed, that the latest release is newer than "2022.1.2" - but it's accidentally been called "2021.1.3"?! I didn't check, if this latest version already solves this problem (the fixes don't seem to mention this, though).

**Comment by TEParsons** [comment]
Ah, I see the problem... There's a missed call to `_updateVertices` in the backend of Circle. Will put in a PR to fix it, in the meantime you can fix the problem in your code by adding this after `circle.setRadius`:
```
circle._updateVertices()
```

**Comment by The-C-Wolf** [comment]
Thank you, that fixes it! 
I obviously overlooked this missing call when having a quick look into the backend.
