### ISSUE TITLE
Possible Bug - Risk of Data Loss!: 2022.1.x URL Parameter not included in filename

### ISSUE THREAD

**Issue by shabkr** [psychopy/psychopy#4831]
I think I have encountered a bug with the interaction between URL parameters and datafile saving in 2022.1.1 and 2022.1.3 of PsychoPy/JS. I have additionally posted about this issue on the [PsychoPy Discourse](https://discourse.psychopy.org/t/possible-bug-2022-1-1-2022-1-3-url-parameter-not-included-in-filename/29080)

**OS:** Windows 10
**Coder or Builder?:** Builder
**PsychoPy or PsychoJS?:** PsychoJS
**Offline or Online:** Both
**PsychoPy version:** 2022.1.x

**What are you trying to achieve?**
I use URL parameters to transfer information from my participant recruitment site (e.g. [Prolific](https://www.prolific.co/)) to my Pavlovia-hosted experiment. One of the URL parameters is the participant number, which I use to name the file with the format ```participant_expName_Time.csv```. 

**Experiment Set-up**
-  Experiment Settings > Data > Data Filename says 
```u'data/%s_%s_%s' % (expInfo['participant'], expName, expInfo['date'])```
- provide link with URL parameter 
(e.g., ```https://run.pavlovia.org/USER/EXPERIMENT/?participant=1```)

**Previous Behaviour - tested on version 2021.2.3**
- participant does not have to input a participant number
- upon experiment completion or interruption:
    - datafile is saved at ```data/1_expName_TIMESTAMP.csv```
    - datafile contains column ```participant``` and each cell includes the URL parameter provided participant number ```1```

**Current Behaviour - tested on versions 2022.1.1 and 2022.1.3**
- participant does not have to input a participant number
- upon experiment completion or interruption:
    - datafile is saved at ```data/expName_TIMESTAMP.csv``` **note how the participant number is missing from the data filename**
    - datafile contains column ```participant``` and each cell includes the URL parameter provided participant number ```1```

**What did you already try?**
- This behaviour can be reproduced offline using the Run Local JS option if you append 
```/?participant=1``` to the LocalHost URL
data is saved as ```_expName_TIMESTAMP.csv```
- If the participant number is filled manually during the dialog box (offline or online) the filename is correctly saved as ```1_expName_Time.csv```
- I have replicated this behaviour on two computers running version 2022.1.1 (current behaviour) and one computer running versions 2021.2.3 (previous behaviour) and 2022.1.3 (current behaviour).

As it currently stands, this behaviour may be problematic for researchers who wish to automate parts of the data collection/analysis if participant numbers are expected in the file name. Additionally, there may be a risk of data loss depending on how a system handles identical filenames.

**Comment by shabkr** [comment]
I quickly tested behaviour of duplicate filenames:
- Experiment Settings > Data > Data Filename is
```u'data/%s_%s' % (expInfo['participant'], expName)```

(2022.1.1) Offline via PsychoPy Runner on Windows 10:
- append ```/?participant=1``` to the LocalHost URL
- data can be downloaded as ```_expName.csv```. If the data is downloaded and the experiment is run again, the second data can be downloaded as ```_expName (1).csv```

(2022.1.1) Online via Pavlovia PILOTING on Windows 10:
- append ```&participant=1``` to the end of the Pavlovia pilot URL (after the token information)
- behaviour is the same as above

(2022.1.1) Online via Pavlovia RUNNING:
- This URL format: ```https://run.pavlovia.org/USER/EXPERIMENT/?participant=1```
- I ran an experiment twice (participant=1 and participant=2), then downloaded the results from Pavlovia.
- There are two .log.gz files, labelled with the format
```participant_expName_Timestamp.log.gz``` e.g. ```1_test_2022-05-10_15h10.37.875.log.gz```
- There is **only one csv** labeled ```expName.csv```. This csv contains the data from "participant 2"

Based on this testing, I am concerned there is currently a risk of data loss for researchers running studies on Pavlovia using 2022.1.x

**Comment by peircej** [comment]
Thanks @shabkr we're looking into this right now

**Comment by shabkr** [comment]
Saw some recent discourse posts about this issue, so here is list of affected/unaffected versions for reference.

Unaffected Versions:
- 2021.2.3

Affected Versions:
- 2022.1.1
- 2022.1.3
- 2022.2.1 (https://discourse.psychopy.org/t/participant-id-not-saving-in-data-file-name/30623 and https://discourse.psychopy.org/t/participant-info-not-saved-on-filename-csv/30029)
- 2022.2.4

Untested Versions:
- pre-2021.2.3 (I assume these are unaffected)
- 2022.1.0
- 2022.1.2 (I assume affected, see https://discourse.psychopy.org/t/participant-id-saved-in-name-gz-file-not-in-name-csv-file/28573. Version is unspecified, but the most recent version at the time was 2022.1.2)
- 2022.1.4, 2022.2.0, 2022.2.2, 2022.2.3 (I assume these are affected)



Possible work around until the bug is fixed:
[Credit here for first proposing the workaround](https://discourse.psychopy.org/t/participant-id-not-saving-in-data-file-name/30623/9). I modified this solution to use a code component

In the Before Experiment section of a Javascript code component you can add:
```
util.addInfoFromUrl(expInfo);
```
and this seems to force the URL parameters to be read before the participant file is created. I briefly tested this in a minimal example in Version 2022.2.4, but have not tried it in a full experiment yet.

**Comment by shabkr** [comment]
This might be caused by the order of code lines in the ```updateInfo()``` JS function.

In version 2022.2.4 (bug present), the file-name is created with 
```  psychoJS.experiment.dataFileName = (("." + "/") + `data/${expInfo["participant"]}_${expName}_${expInfo["date"]}`);```
before the URL parameter info is read with 
```util.addInfoFromUrl(expInfo);```

In versions 2020.1 and 2021.2.3, the ```psychoJS.experiment.dataFileName``` is not in ```updateInfo()``` but ```util.addInfoFromUrl(expInfo);``` is still present.


I've forked the PsychoPy repository and moved dataFileName to be after addInfoFromUrl in ```JS_setupExp.tmpl```. ~~First time contributing code, I haven't been able to test this or make a pull request because of [issues with my developer's install](https://discourse.psychopy.org/t/issues-with-developers-install-on-windows-11/31312)~~.

**Comment by peircej** [comment]
Fixed by #5171
