### ISSUE TITLE
Textbox component receiving input from Keyboard component in separate routine in prior trial

### ISSUE THREAD

**Issue by Chalmes** [psychopy/psychopy#4863]
I put this in discussion but so far no comments, this seems like a bug to me.

**OS (e.g. Win10):** Win10
**PsychoPy version (e.g. 1.84.x):** 2022.1.3 and 2022.1.4
**Standard Standalone? (y/n) If not then what?:** Standard Standalone
**What are you trying to achieve?:**
I have 2 routines in the trial, the first has a textbox component to ask for text input from the participant. I’m detecting when they hit the Enter key to continue onto the next routine in the trial which has a keyboard response component to ask for a specific key response. However, when the experiment iterates onto the next trial, the response for the keyboard object in the previous trial appears in the textbox.

**What did you try to make it work?:**
I’ve tried explicitly setting the textbox text to blank, and calling textbox.reset in the Begin Routine section of a code component. My textbox component has its Text set to “set every repeat”.  I've tried explicitly clearing keyboard buffers.

**What specifically went wrong when you tried that?:**
Neither of the above worked. I seem unable to prevent the response made to the keyboard object from appearing in the textbox on the next iteration.

**Test file here:**
[testTextbox.zip](https://github.com/psychopy/psychopy/files/8794890/testTextbox.zip)

**Comment by TEParsons** [comment]
I think I've found the problem - it's that the Keyboard component in the y/n routine uses `waitRelease=False`, but the Textbox listens for key releases, not key presses. So the routine ends when the key is pressed, but the character is sent to the textbox when the key is released. It may be as simple as just having Keyboard use `waitRelease=True` but I'll need to investigate further what the effects of that would be (I'm wary of introducing a new bug by fixing this one!)
