### ISSUE TITLE
[Bug] 2022.1.3-4 MacOS mouse-click location still screwy in 2022.1.4 for Catalina (10.15) and Mojave (10.14)

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#4893]
In 2022.1.4 I tried to run my PyHab builder, which is essentially a bunch of clickable boxes each of which opens a different dialog. I discovered that all the mouse-click locations had somehow been relocated. I'm using Mouse.isPressedIn to figure out which shape a mouse-click occurs in, but it only registers if the location clicked is some ways up and to the right.

I've had other people report this as well. The problems seem to arise on Macs with retina displays running Catalina (10.15) and Mojave (10.15)

Notably the amount of skew is different (smaller) from 2022.1.0, but it's still not accurate. In 2022.1.0, all the clicks have to be in the top right corner, like the window the mouse sees is 1/4 the size of the real window. In 2022.1.3 and 4 the bottom-left button is moved about 1/4 of the window size up and to the right.

**Comment by peircej** [comment]
I fixed this here: https://github.com/psychopy/psychopy/pull/4924
Should be fine in 2022.2.x
