### ISSUE TITLE
DotStim size parameter does not correspond to displayed size

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#4902]
The size attribute of a DotStim does not correspond to its actual displayed size. For example, below are two polygons each set to have a size of (2.5, 2.5) deg, and a DotStim notionally of the same size and units:

![dotstim_size_issue_25](https://user-images.githubusercontent.com/931027/173257711-11dbcdf8-372f-4b59-857a-724853fe08a1.png)

This is not a diameter/radius confusion, as doubling the size of the polygons still does not match the extend of the DotStim field (see https://discourse.psychopy.org/t/dotstim-fieldsize-argument-has-unclear-units/29520/3 )

When using other units, such as `height` rather than `deg`, the displayed size does not seem to lawfully correspond to the specified values (see the initial post in the Discourse thread above).

***This then raises questions about whether the specified dot speeds are correct, if the stimulus doesn't know its own angular extent.***

Below is another example, where all three stimuli were set to have sizes of (0.5, 0.5) in height units. In this case, the DotStim is now markedly smaller than the reference polygons:
![dotstim_size_issue_05_height](https://user-images.githubusercontent.com/931027/173289148-c1a179bc-eb44-4609-9a5c-58d91fb7ffbb.png)

**Comment by TEParsons** [comment]
I'm surprised the test suite didn't catch this - I've just tried it out and replicated what you've got there so I'll try and get a fix in ASAP. Once I do I'll add a test too, this should definitely be caught!

**Comment by m-macaskill** [comment]
Thanks Todd - we're just piloting a random dot task at the moment and then I had a sudden moment of panic that the parameters we're applying might not actually be what the subject sees.

**Comment by TEParsons** [comment]
Ah I know what it is - silly mistake on my part. When fixing #4691 I added a line which updates `.vertices` from `._baseVertices`, but didn't realise that `._baseVertices` isn't normalised while `.vertices` needs to be. Easy fix, just need to divide by size.

**Comment by m-macaskill** [comment]
Great - I didn't realise it was my own previous bug report that indirectly led to this issue - had assumed it was a long-standing problem. So the good news is that this won't have been a long-standing error affecting users - would be good to get a bug fix out as soon as possible though.

**Comment by davidhildebrand** [comment]
Thanks for sorting this out!
Was very confused for a while when trying to set up some moving dot stimuli... and now I understand why.
