### ISSUE TITLE
TextBox2 can't find local fonts on macOS

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#4978]
Fonts on a Mac can be installed in the following folders:

    /System/Library/Fonts
    /Library/Fonts
    ~/Library/Fonts

`TextStim` can use fonts from all three locations. `TextBox2`, however, can not find local user fonts stored in `~/Library/Fonts` and seems to fall back on using `Verdana` when that happens.

The only option at present is to move the font to one of the System-level font folders, but the user might not have permissions to do that, or might consciously want to keep files restricted to their user folder. More likely, the user won't be aware that fonts can be stored in different places and simply be puzzled why `TextBox2` displays some fonts but not others.

It is difficult to provide a reproducible example, as it depends upon what fonts are on the particular system being tested. Be aware that if a font is in the local user folder but is also present in one of the system-level folders, then it might appear to work, but only because `TextBox2` is able to use the duplicate system-level font.

**Comment by TEParsons** [comment]
That's surprising as `/Library/Fonts/` is included in `_OSXFontDirectories` - I'll investigate when I next have access to the office Mac

**Comment by m-macaskill** [comment]
It's not `/Library/Fonts` that has the issue, but the user-level folder `~/Library/Fonts`.

**Comment by peircej** [comment]
The issue about local (user) fonts is fixed by this Pull Request: https://github.com/psychopy/psychopy/pull/5057

Note that it's probably better to install them in /Library so they're available to all users anyway but macos uses ~/Library by default (can be changed in FontBook preferences)
