### ISSUE TITLE
Typo in Release Title for 2022.2.1 (shows "2021.2.1")

### ISSUE THREAD

**Issue by lboel** [psychopy/psychopy#5000]
The Typo "2021" in the Release Title has just confused some of my students, I am not sure if it is easily fixable without rerelease (?)
![image](https://user-images.githubusercontent.com/8046474/177150914-310c3d77-248d-4583-a732-b655b70a30ab.png)

**Comment by peircej** [comment]
Thanks! Yes that was just a typo in the release title on github. Now fixed. I look forward to when the year has higher digits and hoping that will be less confusing! 😆
