### ISSUE TITLE
Incompatibility with Python 3.10, wx, and implicit conversion to integers

### ISSUE THREAD

**Issue by danielshub** [psychopy/psychopy#5015]
Python 3.10 no longer uses implicit conversion with loss from a float to an int (https://bugs.python.org/issue37999). This screwed up wxpython (https://github.com/wxWidgets/Phoenix/commit/173d0796810bb65de9bdfdc6941d24a04628f6c2) and it is having effects on PsychoPy. For example, in psychopy/app/builder/builder.py on line 3626:

`font.SetPointSize(1400 / self.dpi - fontSizeDelta)`

for most DPIs the point size is not going to be an integer and eventually wx is going to crash. In other cases it is not clear where the integer becomes a float. For example, in psychopy/app/builder/builder.py on line 3470:

`pdc.DrawLine(x1=currX, y1=self.linePos[1], x2=currX + gap,  y2=self.linePos[1])`

This issue also shows up in psychopy/app/builder/dialogs/__init__.py (and probably other places I have not found yet). In the ideal world, things that should be integers would be created that way and never changed into floats. That seems like it may be difficult to ensure and cause lots of incompatibilities. Maybe a more reasonable approach would be to convert floats to integers right before calls to wx. Along that line, maybe the easiest thing would be to somehow overload/intercept the affected wx calls with a wrapper that does the conversion. There is also the issue of how to efficiently track down the offending code. Maybe the unit tests can find them.

**Comment by mdcutone** [comment]
Thanks for pointing this out. There are likely lots of changes needed here.

**Comment by danielshub** [comment]
@mdcutone this is great. Have you seen https://discourse.psychopy.org/t/psychopy-2021-2-3-1-fails-to-start/27067/6?u=daniel.e.shub which suggests that psychopyApp.py also needs changes. Maybe your changes in builder.py get takes care of it. Trying to apply your patch now to see what happens.

**Comment by danielshub** [comment]
I am trying to package PsychoPy on Arch Linux with Python 3.10. Initially, i could not even start PsychoPy. After copying builder.py from your pull request and I can now start PsychoPy, so that is super helpful. Now, large chunks of the unit testing fail. In builder.py there appears to still be floats floating around in font.SetPointSize, dc.DrawBitmap, and PseudoDC.DrawText (and potentially other places) that need to be converted.

**Comment by mdcutone** [comment]
Thanks for following up. Might take a bit of time to go through the whole code base.
