### ISSUE TITLE
Create virtual on-screen button box

### ISSUE THREAD

**Issue by joshdoe** [psychopy/psychopy#503]
For an experiment I'd like the participant to identify an object with one of 20 labels. The RatingScale doesn't appropriately scale to this number of labels, especially when they're natural English words. What would be better is a grid of buttons, such as 4 x 5.

What would it take to create such a grid of buttons? Should I just inherit from BaseVisualStim and then create 20 Rect's and 20 TextStim, placing them appropriately in a grid? Perhaps there are some other features of pyglet or other libraries that would help with this?

**Comment by tjwilli58** [comment]
I would also like to have a way to use buttons as feedback to a visual stimulus. The buttons would be the set of answers, instead of a list of keyboard inputs.

**Comment by peircej** [comment]
The next release of PsychoPy (1.90.0) has a new option in the Mouse Component of the Builder to set visual objects as "clickable" which means essentially that any visual stimulus can be converted into a button. 
The question of the box around the button might also be handled by the new TextBox2 that I'm working on (not in this release but hopefully in 1.91) which is a faster, more flexible text stimulus and will probably include a background color and border color.
So, the virtual buttons here are probably superseded byt he new features (except for the buttons array). I'll close this for now
