### ISSUE TITLE
setGammaRamp() fails on WinPython-64bit-2.7.5.3 (GetDC)

### ISSUE THREAD

**Issue by jaybo** [psychopy/psychopy#504]
About half the time, setGammaRamp() fails on Win7 with WinPython 64bit V2.7.5.

I believe this error is due to a sign extension problem in the ctypes wrapper for GetDC().

The Win32 function returns a 32bit value, and it’s (improperly) getting sign extended to a negative 64bit value by ctypes.  About half the time, the 32bit handle returned by Windows will have the high bit set, which is why the bug is only sometimes reproducible.

    In [1]: from ctypes import *
    In [10]: a = windll.user32.GetDC(None)
    In [11]: a
    Out[11]: -2013190841
    In [23]: type(a)
    Out[23]: int
    In [24]: hex(a)
    Out[24]: '-0x77fedab9'

I’ve tried a bunch of likely hacks in Pyglet to fix this, but nothing has worked.  Here’s a good clue:
http://stackoverflow.com/questions/3323778/is-pythons-ctypes-c-long-64-bit-on-64-bit-systems  

We've successfully hacked around this by masking the return values from GetDC() as in:
\psychopy\gamma.py, line 48:

    success = windll.gdi32.SetDeviceGammaRamp(pygletWindow._dc & 0xFFFFFFFF, newRamp.ctypes)  

This same error is probably causing problems with Fonts and any other call on x64 systems which utilize self._dc.

**Comment by hoechenberger** [comment]
Closing, as it has been [fixed](https://bitbucket.org/pyglet/pyglet/commits/021505b88a845d38c78a3f8ce4b84fc11afe3819) upstream in Pyglet.
