### ISSUE TITLE
Pocketsphinx troubles

### ISSUE THREAD

**Issue by glupyan** [psychopy/psychopy#5097]
We've been having a hell of a time getting pocketsphinx to work. We're not the only ones it looks like -- these issues https://github.com/cmusphinx/pocketsphinx/issues/171 are still not fully resolved.

Is there a way of using the Psychopy.microphone without it? We don't need it to do any actual speech to text.

**Comment by mdcutone** [comment]
Which version of PsychoPy are you using?

**Comment by TEParsons** [comment]
Closing this as the microphone component can be used without pocketsphinx - if "Transcribe audio" is unchecked or if the transcription backend is something else then it doesn't use pocketsphinx - and our default backend is now Whisper
