### ISSUE TITLE
column separator in output file

### ISSUE THREAD

**Issue by JensBoelte** [psychopy/psychopy#5141]
Hello,

while PsychoPy supports different output separators in the result csv-files, the csv recorded via Pavlovia only come with a comma as separator. It would be nice if Pavlovia uses the same separator as set in PsychoPy.

Best wishes and thanks for your work Jens

**Comment by EitanHemed** [comment]
@TEParsons I've looked at what it requires here and on the PsychoJS repo, and would like to help with this one, if you're OK with that (i can't assign myself).
