### ISSUE TITLE
wglChoosePixelFormatARB is not exported by the available OpenGL driver.  ARB_pixel_format is required for this functionality.

### ISSUE THREAD

**Issue by Ao-zhang** [psychopy/psychopy#5149]
when i try to use flask to support request calling functions to raise such a test, it shows me the error above.
it seems that psychopy don't support running in not-main thread?

don't know how to fix that
![image](https://user-images.githubusercontent.com/52751986/192362417-f548c225-dc2a-4c01-b50f-4604985321d7.png)

**Comment by mdcutone** [comment]
Your driver does not support that extension, therefore it cannot export the function which depends on it.

**Comment by Ao-zhang** [comment]
> Your driver does not support that extension, therefore it cannot export the function which depends on it.

but I don't know which openGl driver can support it

**Comment by peircej** [comment]
I don't think this is an issue in PsychoPy, right? If so then please reopen and paste the full error traceback rather then just the last lines (which don't show where in the psychopy code the error you see is coming from).
