### ISSUE TITLE
timeline number format changes to scientific notation

### ISSUE THREAD

**Issue by puterleat** [psychopy/psychopy#515]
Sometimes the number format of the timeline reverts to scientific format, which makes it harder to read than needed... It strikes me the format of the scale could always be {:3g} or similar.

**Comment by peircej** [comment]
We are using .2g and have been for some time which already means 0.00001 is the first point it switches
- dropping to .3g would help does the same (strangely to me)
- The difference between g format and G format is only at the large-value end, not small vals

So I think this is handled already
