### ISSUE TITLE
Button component: Option to only register a "new" click

### ISSUE THREAD

**Issue by jolgen** [psychopy/psychopy#5164]
Apparently, the button component does not check whether it registers a "new" klick or if it's just a continuing "mouse down"-event.
This leads to issues when button components are used to advance to the next routine and those buttons are placed in the same spot for multiple routines.

Example:
When the user presses button bt_a on routine A, continueRoutine is set to False and A is terminated at the end of the current frame. Routine B (which has a button component bt_b placed at the same location as bt_a) begins. bt_b checkes if is' being clicked and - because the user did not release the mouse button in less than 1/60 seconds - detects the same mouse down event that ended routine A. It therefore sets continueRoutine to False and ends routine B immediately on the very first frame.

I know that you can set a starting condition for buttons, etc. But It'd make much more sense to me that you have an option in psychopys builder (for the button component) so that it only registers new clicks.

**Comment by TEParsons** [comment]
This is a bug, if a button starts the routine clicked then it definitely should not count as a new click! PR #5190 fixes this by making sure that `.wasClicked` is set to `True` if the routine begins with a mouse button already pressed, meaning it isn't registered as a new click.
