### ISSUE TITLE
FYI, pyglet is releasing v2.0 soon, which has breaking changes

### ISSUE THREAD

**Issue by benmoran56** [psychopy/psychopy#5168]
For a heads up, pyglet 2.0 will be released in the near future.
This includes migrating the core of pyglet to OpenGL 3.3+, which may cause issues for projects that use legacy OpenGL calls.
In the immediate future it might be a good idea to pin the pyglet dependency to `pyglet<2.0`, until it can be checked against the new release.

**Comment by mdcutone** [comment]
Thanks for the heads up. We're planning to move to OpenGL 3.3 anyways in the next few releases.

**Comment by peircej** [comment]
Yes, thanks for getting in touch @benmoran56 

Just to clarrify, does this mean that pyglet will not be exposing the older calls in the lib? Mostly we use pyglet to create the window and then use it merely as a conduit to the gl library, so that might not affect us enormously. How will we check this out to test? Is pyglet 2.0 going to be based on the current pyglet master branch or is this in a separate repo?

**Comment by benmoran56** [comment]
Hi Matthew, Jon,

Yes, the 2.0 code is in master. It's also on pypi as `2.0b1`, with a full release to come shortly.

The legacy gl bindings are still there, but have been moved to `pyglet.gl.gl_compat`. pyglet will now create a GL 3+ context when you create a Window, so if you wanted to use legacy GL you would need to make a custom `gl.Config` to pass in. This hasn't been tested much though, so I'd have to check.
Also, pyglet 1.5 should remain for the foreseeable future, but probably won't see much development outside of bugfixes. 

As for upgrading, how much legacy GL is PsychoPy reliant on? I had a quick browse, but only saw the project/matrix calls. I'm afraid I'm not very familiar with the library.

**Comment by mdcutone** [comment]
"As for upgrading, how much legacy GL is PsychoPy reliant on? I had a quick browse, but only saw the project/matrix calls. I'm afraid I'm not very familiar with the library."

Quite dependent actually, we use lots of legacy calls, even our shader code is not 3.3 compliant. We do have a library called `gltools` which is intended to simplify porting over to newer OpenGL versions, but we haven't begun that process yet.

**Comment by benmoran56** [comment]
In that case, it's probably best to just pin the version as `pyglet<2` for the time being.
The 1.5 branch will remain for the foreseeable future.

**Comment by mdcutone** [comment]
Once again, thanks for informing us. We just pegged the version in our release branch to 1.5.
