### ISSUE TITLE
what is the correct input parameter to run psychopy/psychopy/contrib/quest.py

### ISSUE THREAD

**Issue by dorcatty** [psychopy/psychopy#5182]
Dear all,

In order to better understand how 'Quest.py' demo works, i would like to run this python code first.
However, i got some errors, while testing with input values, as following: 
Specify true threshold of simulated observer: -2
Estimate threshold: -1
----
The intensity scale is abstract, but usually we think of it as representing log contrast.
Specify true threshold of simulated observer: -2
Estimate threshold: -1
Trial   1 at -0.7 is right
Traceback (most recent call last):
  File "quest.py", line 484, in <module>
    demo() # run the demo
  File "quest.py", line 466, in demo
    q.update(tTest,response);
  File "quest.py", line 381, in update
    self.pdf = self.pdf*self.s2[response,iii]
IndexError: index 225 is out of bounds for axis 0 with size 2

could someone let me know how to resolve this issue ? what are the proper values that i can test with this demo code ?

thanks in advance

**Comment by peircej** [comment]
responses to any staircase procedure should be True/False or 1/0 indicating whether the participant was correct on this trial. I don' think this is a bug/issue so closing
