### ISSUE TITLE
Declare optional dependencies with extras_require

### ISSUE THREAD

**Issue by tbenst** [psychopy/psychopy#5217]
Psychopy is difficult to build on systems without `sudo` access due to dependency on `pyo`, which in turn requires certain system packages to be installed which can't be done in userspace. `pyo` however is just one of multiple choices for audio backends. AFAICT, `pyo` is thus an optional dependency as as such [should be listed under `extras_require` instead of `install_requires`](https://stackoverflow.com/questions/41268863/difference-between-extras-require-and-install-requires-in-setup-py). This would then allow users without root access to install psychopy.

btw huge appreciation for all the work on psychopy, great piece of software. hopefully these issues are useful! I know open source software can be thankless sometimes so want to make sure I emphasize how much I appreciate your work :).

**Comment by peircej** [comment]
**For the general statement (as in the title):** it's complicated by the fact that it depends what's considered an "optional" dependency. There's a long debate about what is an "optional" dependency, and Python dependency management doesn't have a system to require "at least one of..." so we can't say that "at least one of ptb, pyo, sounddevice should be installed" for sound stimuli to work.

**Our general solution:** We're moving to a plugin system that means more things can be moved out of the dependencies of psychopy itself. This is part of the work for release 2023.1.x and [about 20 plugins have already been made](https://pypi.org/search/?q=psychopy-) moving code out of core psychopy. 

**For the specific question of `pyo`:** that was moved out of the dependencies in 64813fe562d96 so in the 2023.1 release that will certainly not be a dependency
