### ISSUE TITLE
PsychoJs files created within index.html folder instead of next to psyexp causing 403 forbidden error (when using run the study online button on new project)

### ISSUE THREAD

**Issue by frankpapenmeier** [psychopy/psychopy#5222]
PsychoPy Builder sometimes creates the js (and html) files in a folder called "index.html" which then causes a "403 Forbidden" error message on Pavlovia because the files are not in the expected location (next to the psyexp file).

I think this bug already exists longer (maybe since 2022.2.0), but before I was not able to easily reproduce it. Today, I noticed that it always occurs if one creates a new projects and instantly runs it with the "run the study online" button.

I also recorded a video showing the issue:
https://user-images.githubusercontent.com/5979916/203097947-e2feb648-9a08-47a7-bb68-4f378c2918da.mp4

Important note:
If one does the very same as in the video, but first hits the "sync with web project" button and thereafter the "run the study online" button, it works as expected (js and html files are created next to the psyexp file).

**Comment by TEParsons** [comment]
Good catch! I think I see what's causing this - both the Pavlovia Run and Pavlovia Sync buttons call `self.fileExport` (the method which makes the js and html files), but while Pavlovia Sync uses `self._getHtmlPath(self.filename)`, Pavlovia Run uses `Path(self.project.localRoot) / 'index.html'` - which is incorrectly interpreted as a folder and that's how the `index.html` folder is created.

The easy answer is just to use the same values, but it may be better to actually call the Pavlovia Sync method when Pavlovia Run is clicked, to avoid any other discrepancies. Will look into it and hopefully get this fixed quickly!
