### ISSUE TITLE
PR655 failure to detect

### ISSUE THREAD

**Issue by da5nsy** [psychopy/psychopy#5237]
Copying from: [Cannot connect Photoresearch PR655 to PC using Psychopy, Communication Protocol Problem?](https://discourse.psychopy.org/t/cannot-connect-photoresearch-pr655-to-pc-using-psychopy-communication-protocol-problem/25595)

Cannot connect PR655 using PsychoPy3, but works fine with PsychoPy2.

It looks like it looks like [this](https://github.com/psychopy/psychopy/pull/2537/files/8cd75b8072f9b48c3d9ea3965217c5df892a2c31#diff-49289a0e20d98dfa6c35eecf682144d539f02e1a270cb4886216cd954d13efa6) was the commit that removed the special case for the PR655, specifically the removal of [this line](https://github.com/psychopy/psychopy/pull/2537/files/8cd75b8072f9b48c3d9ea3965217c5df892a2c31#diff-49289a0e20d98dfa6c35eecf682144d539f02e1a270cb4886216cd954d13efa6L390), as noted [here](https://discourse.psychopy.org/t/cannot-connect-photoresearch-pr655-to-pc-using-psychopy-communication-protocol-problem/25595/12?u=da5nsy).

If it could be re-added, that would be lovely.

**Comment by peircej** [comment]
Sorry for the long absence on this issue - my own experience with PR655 has been so painful that I've tried to leave it in a drawer! 😆 
I will investigate and hopefully get this tested and back in for 2023.1 release series, due to drop in a few weeks

thanks for pinging

**Comment by peircej** [comment]
Thanks again Danny. I've tested this now on a PR655 under macos/Py3.8

FYI the code for hardware is gradually porting to plugins, so the fix here has been made in a separate repo. In PsychoPy 2023.1 you'll install the photoresearch plugin from the >tools menu
