### ISSUE TITLE
psychopy.visual compares numpy.array against string (FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison)

### ISSUE THREAD

**Issue by flyingfalling** [psychopy/psychopy#5252]
When passing a mat (numpy matrix) to e.g. ImageStim, we get the following warning:

```
/home/riveale/.local/lib/python3.10/site-packages/psychopy/visual/basevisual.py:952: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if tex in ["none", "None", "color"]:
```

The implementation in in psychopy.visual.basevisual.py:
```

if tex in ["none", "None", "color"]:
            tex = None
```

Does not check the type of tex first (which may be a numpy array, etc.). So, in the future, this may e.g. compare every element of the passed memory against the strings.

It should be changed to check the type of tex dynamically, e.g. lower down:
`
if type(tex) == numpy.ndarray:`

**Comment by TEParsons** [comment]
Good catch, thanks! I've just put in a fix to the release branch which should sort this out - just need to check that `tex` is a string before comparing it to `"none", "None", "color"`
