### ISSUE TITLE
conditions info not always reloaded from file

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#526]
Its possible to manually edit the values in a .csv conditions file, but at least sometimes the .psyexp script has already latched onto values and does not update them internally, even if you quit and restart PsychoPy. I don't understand the motivation to store them internally at all--seems like they should always be read from the external file when the script (last_run.py) is run.

**Comment by hoechenberger** [comment]
Is this still the case with 1.84.x?
