### ISSUE TITLE
Current conda formula installs 2022.1.4 not the 2022.2.x series or the latest version (2022.2.5)

### ISSUE THREAD

**Issue by mdtdev** [psychopy/psychopy#5288]
The environment file for Conda [here](https://github.com/psychopy/psychopy/blob/dev/conda/psychopy-env.yml) does not install the current version of PsychoPy. The version that it installs is:
```
> psychopy --version

PsychoPy3, version 2022.1.4 (c)Jonathan Peirce 2018, GNU GPL license
```
I am trying to get the latest version of PsychoPy in a Conda environment. Is there a way to do this? Is there another formula for this somewhere?

Also the environment file linked on the [installation page](https://psychopy.org/download.html#conda) of the main PsychoPy website is to an even older version, tied to Python 3.6.

Not sure how to fix this or proceed. Thanks!

**Comment by peircej** [comment]
Happy to see contributions here. Updating the env files is easy. Taking that to the next level of building the pipeline and make sure it all works is harder. Previously @hoechenberger had handled this. He's now working on other projects, but may be able to advise

**Comment by hoechenberger** [comment]
Working on this in https://github.com/conda-forge/psychopy-feedstock/pull/53

**Comment by hoechenberger** [comment]
PsychoPy 2022.2.5 is now available from conda-forge. Feel free to test and report any packaging-related issues at https://github.com/conda-forge/psychopy-feedstock/issues

**Comment by mdtdev** [comment]
I just did a test install (with `mamba`), and it appears to work for me. Although it took a very long time.

One question: on the PsychoPy website they say you need to use an environment file to install it. Is that true, or can you just make an empty conda environment and install with the line quoted in the feedsotck's page: `conda install psychopy`. I mention this because the website's `environment.yml` file was out of date and linked to Python 3.6, I think.
