### ISSUE TITLE
ButtonStim missing autoDraw property/does not carry over to TextBox2

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#5296]
See https://discourse.psychopy.org/t/visual-buttonstim-not-working/32736

Looking at the ButtonStim code, the autoDraw property is just missing from the init statements for both the ButtonStim itself and for the TextBox2 it creates. Should be a very straightforward fix, since autoDraw has already been implemented for TextBox2, I just don't have time to do a proper branch/pull for it right now.

**Comment by TEParsons** [comment]
I can't find the PR now, but this is fixed :) #5326 also adds a test so that the test suite catches this in future components
