### ISSUE TITLE
Not saving .EDF file (eyetracker) when pressing 'esc'

### ISSUE THREAD

**Issue by GonzaloRuarte** [psychopy/psychopy#5442]
I noticed that when I press 'esc' or when there's an exception, the .edf file (when using an eyetracker) doesn't get transferred, but when the experiment ends normally, it does.

I think the problem is that this code here is run when the experiment ends
![imagen](https://user-images.githubusercontent.com/18074827/224441182-bb71d3ed-a533-4228-b368-c1fd95e767a0.png)

but when I press 'esc' only this code is run
![imagen](https://user-images.githubusercontent.com/18074827/224441352-5885e91d-daaf-423d-a88f-48d17012ed65.png)

Is there a way you can make it so that the connection with the eyetracker is severed when 'esc' is pressed as well?

**Comment by GonzaloRuarte** [comment]
I forgot to mention that this is the code generated by the psychopy Builder (the last version available on the webpage)

**Comment by TEParsons** [comment]
Thanks for spotting this, I'll add the code to close the eyetracker to the on-escape bit for the next release :) In the meantime you should be able to close the eyetracker on escape by adding this to the Each Frame tab of a Code component:
```
if endExpNow or defaultKeyboard.getKeys(keyList=["escape"]):
    eyetracker.setConnectionState(False)
```
