### ISSUE TITLE
maxFALL and maxCLL function implementation?

### ISSUE THREAD

**Issue by vincentdory** [psychopy/psychopy#5447]
Hello,

I am interested in using Psychtoolbox to get the maxCLL and maxFALL values for images, and in the original implementation of PsychToolbox, this function is used to get these values: 
[http://psychtoolbox.org/docs/ComputeHDRStaticMetadataType1ContentLightLevels](http://psychtoolbox.org/docs/ComputeHDRStaticMetadataType1ContentLightLevels)

However, I am interested to see if this same functionality has been ported over to psychopy, but I couldn't really find any similar to it in this repo. 

Can you confirm if the function `ComputeHDRStaticMetadataType1ContentLightLevels` or something similar to it has been implemented here in Psychopy?

Thanks!

**Comment by peircej** [comment]
It hasn't I'm afraid - the only parts of psychtoolbox that have been compiled for Python are psychPortAudio and psychHID
