### ISSUE TITLE
Error message on macbook

### ISSUE THREAD

**Issue by user-name23** [psychopy/psychopy#5457]
<img width="572" alt="Screen Shot 2023-03-17 at 11 20 57 am" src="https://user-images.githubusercontent.com/128106093/225809737-075b84ef-a315-4588-9066-4d8c0b01cf40.png">

This error message comes up when i enter PsychoPy and I can't run experiments. I have a Macbook pro with a M1 chip

**Comment by user-name23** [comment]
<img width="716" alt="Screen Shot 2023-03-17 at 3 04 55 pm" src="https://user-images.githubusercontent.com/128106093/225810003-3f7d61b2-d595-4d55-b6b9-4d9ee91d038b.png">
This is the full image of the error

**Comment by peircej** [comment]
This occurs when you simply try to launch the app?
What version are you trying to launch?
Have you tried examining the output from `~/.psychopy3/last_app_load.log`?
Have you tried deleting or moving the user config files?

**Comment by mdcutone** [comment]
This issue was fixed in https://github.com/psychopy/psychopy/pull/5538
