### ISSUE TITLE
Issues installing PsychoPy 2023.1.1 on Windows

### ISSUE THREAD

**Issue by JalalAl-Tamimi** [psychopy/psychopy#5486]
Hello 
I have been using Psychopy 2022.2.5 for a while and wanted to upgrade to 2023.1.1 . I am aware that many packacges can be installed via the new gui, but there is a serious issue with installing pyo. I tried the packages soundcard, etc. but there are many incompatibilities with nimpy, pyo, sound pre-installed by Psychopy 2023.1.1 using the pre-compiled windows version and the psychopy pyo. 
Not sure how to resolve this?  This is impacting on audio quality of sounds.
I can add more details if needed
Thanks
Jalal

**Comment by peircej** [comment]
Please give us a more specific issue than "many incompatibilities with nimpy, pyo, sound pre-installed by Psychopy 2023.1.1 using the pre-compiled windows version and the psychopy pyo"

We recommend the use of ptb as the audio backend and that's the version we're currently investing our dev time in supporting

**Comment by JalalAl-Tamimi** [comment]
HelloApologies for the little information I had provided for this. Here is a small summary of the issues: I am running a couple of experiments with audio files (sampling frequency at 22050 Hz). When playing the audios, the sound files had a funny noise (duck like). When searching online, a suggestion was to use pyo as an audio driver, which I used previously under In PsychoPy 2022.2.5. The audios were playing with no issues. With the upgrade to 2023.1.1, I looked at the audio drivers, under preferences, hardware, audio drivers, and I only have: Primary sound, ASIO, Audigy. I tried any of the three and had the same funny noise (duck like). I tried installing pyo. When I searched for “Audio Playback support using Pyo Library” PsychoPy crashes completely. I then searched for ptb, which was not installed. I installed it and the noise like was still there. Then I tried resampling the audio files to 44010 Hz, and this seems to have fixed the issue.  Checking the audio drivers under preferences I now see Audigy as the audio driver, but not ptb. Is this normal? Many thanks indeed. Jalal    Sent from Mail for Windows From: Jon PeirceSent: 03 April 2023 17:21To: psychopy/psychopyCc: Jalal Al-Tamimi; AuthorSubject: Re: [psychopy/psychopy] Issues installing PsychoPy 2023.1.1 on Windows (Issue #5486) Please give us a more specific issue than "many incompatibilities with nimpy, pyo, sound pre-installed by Psychopy 2023.1.1 using the pre-compiled windows version and the psychopy pyo"We recommend the use of ptb as the audio backend and that's the version we're currently investing our dev time in supporting—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by peircej** [comment]
In short, you should use the ptb backend for playing or recording sounds. In 2023.1 the audio library setting has moved to the Experiment Settings instead of preferences. When using the ptb audio engine the audio driver setting isn't needed. You simply choose your device and the driver is automatic

> I then searched for ptb, which was not installed. I installed it and the noise like was still there.

I don't understand why psychtoolbox wasn't there. It's included with all Standalone releases. How did you detect it "was not installed"

But these don't sound like bugs so I'm closing for now

**Comment by JalalAl-Tamimi** [comment]
Many thanks for this. When I did not find the audio devices under preferences, I went to “Tools => plugins/packages manager”, I searched for ptb under packages and I have the “install” option available; I did install it. Not clear if this actually did override the default installation? Then I tried searching for “Audio playback support using Pyo library” as the benchmark indicated this was missing, but each time I click on it, Psychopy crashes.  When I went to audio settings within the experiment settings, I changed that to ptb, and the duck noise was still there. Changing the audio device to pygame fixed the issue. Note that if this is changed to pyo, I have an error message that the audio engine is missing. Anyway, managed to find a solution for my experiment and all is working currently.  ThanksJalal Sent from Mail for Windows From: Jon PeirceSent: 12 April 2023 16:05To: psychopy/psychopyCc: Jalal Al-Tamimi; AuthorSubject: Re: [psychopy/psychopy] Issues installing PsychoPy 2023.1.1 on Windows (Issue #5486) In short, you should use the ptb backend for playing or recording sounds. In 2023.1 the audio library setting has moved to the Experiment Settings instead of preferences. When using the ptb audio engine the audio driver setting isn't needed. You simply choose your device and the driver is automaticI then searched for ptb, which was not installed. I installed it and the noise like was still there.I don't understand why psychtoolbox wasn't there. It's included with all Standalone releases. How did you detect it "was not installed"But these don't sound like bugs so I'm closing for now—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
