### ISSUE TITLE
PsychoPy 2023.1.2 still crashes with $ in text component

### ISSUE THREAD

**Issue by drkitty28** [psychopy/psychopy#5518]
I downloaded and installed PsychoPy- 2023.1.2.zip on Ubuntu 22.04 in a venv.  Same issue as #4207 #5514.  For this version, no error dialog, PsychoPy just crashes and closes when an attempt is made to edit a text component to use $var.  The zip file did indeed launch the correct version of PsychoPy this time (unlike PsychoPy-2023.1.1.zip), but the $var issue remains a bug.

![image](https://user-images.githubusercontent.com/26172078/231774415-2cda9d5b-f371-4b95-a017-c9622b1e9e43.png)

![image](https://user-images.githubusercontent.com/26172078/231773337-5def94cc-7185-4c8a-9b7e-442ea1a1a1b2.png)

![image](https://user-images.githubusercontent.com/26172078/231772529-f221c5ec-9fc4-47a4-899e-b772158d8f78.png)

**Comment by drkitty28** [comment]
A bit more info.  If an earlier version script is opened, just selecting the text component in a routine will crash PsychoPy-2023.1.2

**Comment by TEParsons** [comment]
Is the only contents of the text field in question `$var`? Or is it `$var + "something"`? From looking at the code the only thing I can think which would cause a recursion error is the code to substitute curly quotes for regular quotes, but that's only hit if the value has either of the following unicode characters in:
```
\u201c\u201d
```

Next time I'm at a Linux machine I'll try to recreate this!

**Comment by drkitty28** [comment]
Just need to type "$" in the text box for it to crash - I'm actually running PsychoPy 2-23.1.2 under Wine on Ubuntu 22.04 and that seems to work, but I noticed that PsychoPy Win version is much slower to launch, and the dialogs (e.g., participant) are also slower to launch than linux versions.

**Comment by drkitty28** [comment]
Any progress on this issue?  I did do extensive testing on various releases and found that this issue exists for **all releases** post 2022.1.2.  Release 2022.1.2 works with both python 3.8 and 3.9 with a small caveat.  In the text component, the $var needs to be entered anywhere below the first line, then moved up to the top manually using the return key.  Pasting won't work.  So, something changed after this release.

**Comment by seymatakir** [comment]
I'm having the same problem, did you find any solution?
Ubuntu:20.04, python:3.8

**Comment by drkitty28** [comment]
Short answer - no.

**Comment by peircej** [comment]
@drkitty28 we believe this was [fixed in 2023.2](https://github.com/psychopy/psychopy/pull/5729)

**Comment by drkitty28** [comment]
I just installed 2023.2.3  with pip and it won't launch

  Building wheel for psychopy (pyproject.toml) ... done
  Created wheel for psychopy: filename=psychopy-2023.2.3-py3-none-any.whl
size=37267798
sha256=37f15007fe4aa3538f3bed61ab29a7fd95556e60083465e58bc2bf35b7e0d74e
  Stored in directory:
/home/cat/.cache/pip/wheels/87/36/43/2d4d4ec72c407fe14f92a4b456178f84d057ff35da71185cd4
Successfully built psychopy
Installing collected packages: psychopy
Successfully installed psychopy-2023.2.3


Catherine

**Comment by peircej** [comment]
If it fails to launch entirely that sounds like a different issue. Could you check what's in 
`~/.psychopy3/last_app_load.log` that could tell us what didn't work?
