### ISSUE TITLE
Video for the MoviePause.py coder demo is missing

### ISSUE THREAD

**Issue by EitanHemed** [psychopy/psychopy#5556]
**Windows 11, PsychoPy 2023.1.0.**

While running [this demo](https://github.com/psychopy/psychopy/blob/5d79806a5be72871262dabccf2eb83a7415e2522/psychopy/demos/coder/stimuli/MoviePause.py#L16), **jwpIntro.mp4** is missing (and the demo crashes). 

It seems it should be in the same directory as the demo script.

**Comment by peircej** [comment]
Ah, yes, we removed that a while ago. We should use `default.pm4` which is automatically provided in the app resources

**Comment by EitanHemed** [comment]
OK, I'll submit a PR to fix it.
