### ISSUE TITLE
Builder: longer component names truncated

### ISSUE THREAD

**Issue by abraver** [psychopy/psychopy#5574]
In the routine view, component names longer than about 10 characters get cut off, even when "View > Routine smaller" is set to the smallest text size.  See image below.

Any method of changing the ratio of space given to the names vs. the timeline would be much appreciated.  For me, at least, the component names are more important than the timeline.

![adf314ceca9dbbfe2595aa66d3641c844df47405_2_1380x900](https://user-images.githubusercontent.com/2888701/236318071-fa32078a-1a35-43f4-baa8-59069e4214b4.jpeg)

**Comment by TEParsons** [comment]
Ideally I'd like to have a draggable sash like we have between panels, but as the Routine Canvas is all custom via a PseudoDC this would have to be coded from scratch which... could get crunchy.

One option could be that we set the width of the section with the names according to the length of the longest name? With an option in preferences to disable this and just have a fixed size like it is now (for people with extremely long component names and a need for more timeline space)

**Comment by TEParsons** [comment]
Addressed this in #5586, if you have a dev environment setup feel free to pull down and give it a go!

**Comment by abraver** [comment]
Many thanks, @TEParsons!  I don't have a dev environment set up, so I'll have to wait until it makes its way into a release.
