### ISSUE TITLE
Interference between Movie and Sound components

### ISSUE THREAD

**Issue by naiqixiao** [psychopy/psychopy#5584]
OS: Ubuntu 22.04.2
PsychoPy version: 2023.1.2
movie backend: ffpyplayer
audio backend: ptb

I'm testing an experiment including a movie (with sound) and audio playing. The movie playing was affected by the existence of any sound component. The movie would be played without audio. Also, if the movie is set to loop, the movie plays only once then stops.

Movie playing is normal (with sound and can loop), when I remove the sound component.

Movie playing is also normal (with sound and can loop), when I create a sound object in a code component AFTER the movie routine.

It seems the creation of Sound component affected movie component.

I haven't tested it in other OS. I do patched **_psychopy/sound/backend_ptb.py_** with this version:
https://github.com/psychopy/psychopy/commit/84726874eed40eb1d6408d3d2041ab86b65bb7d0

**Comment by peircej** [comment]
**Audio blocking:** I wonder if this is to do with exclusive mode on the PTB audio engine. What is the [priority setting](https://psychopy.org/api/sound/playback.html#ptb-audio-latency-modes) you're using there? I think the ffpyplayer movie engine uses SDL to play its audio (@mdcutone can confirm?) and when you set ptb to use exclusive audio on the same device it will then surely block SDL from playing any sound. You could try shared high-priority for your sound (which may restrict you to a particular sample rate, like it's 44100 on Windows but I'm not sure about that on Linux)

**Failing to loop:** conceivably this is related (if the sound fails to play it thinks the sound has 'ended'?) but I've no idea. That would need @mdcutone  to check

**Comment by naiqixiao** [comment]
Thanks for the reply! The priority is set to 3.

I have a feeling that it might be related to audio sample rate (44.1KHz vs. 48KHz) and compatible sound devices. When I used PulseAudio in Psychtoolbox to create a handle PulseAudio('Open'). The program crashes when sample rate was 44.1KHz, but it worked fine when the sample rate was 48KHz. This happened without running any audio file.

What's more interesting was that after I connected the speaker (a headphone connector) to the computer via an USB audio adaptor (Sound Blaster X G1), 44.1KHz worked. So, the headphone jack comes with my computer (mother board) might not support 44.1KHz (on Linux?). Here is a comment from Mario Kleiner on this issue: https://psychtoolbox.discourse.group/t/psychportaudio-only-lets-me-use-sampling-frequency-48000/4464/2?u=dbneg

I haven't tested whether the USB audio adaptor (Sound Blaster X G1) could change the issue that I described in my initial post. But the issue is a OS independent one, as it happened in both Win11 and Ubuntu 22.04.2. I will update it here when I have the chance to test.

**Comment by peircej** [comment]
OK, well then it sounds like the audio output device doesn't support the sampling rate that your movie audio is coded in. I'm surprised that there wasn't an error message telling you that though. 

You might be able to recode that using Handbrake or similar or you might be able to set the timing priority of the audio to be 0 (not important) which will mean that the card will be willing to interpolate (that's slow so not to be done when timing is critical).

Either way, this doesn't *sound* like a bug as such - more a user support issue, so I'm closing this unless there's further info suggesting there's something we could have done differently in the lib
