### ISSUE TITLE
Sound function does not work

### ISSUE THREAD

**Issue by zeltass** [psychopy/psychopy#5602]
In my experiment, I have implemented a loop where a beep sound is supposed to play as a response onset for each trial. This functionality worked flawlessly when I initially developed the experiment using Psychopy version 2022.1.2. However, after updating to the newer version, I have encountered a problem where the beep sound is only played for the first trial and subsequently fails to play for any subsequent trials.

To troubleshoot the issue, I ensured that the code responsible for playing the beep sound is placed correctly within the loop. It worked perfectly fine in the previous version, and I haven't made any changes to the code. Despite this, the problem persists in Psychopy 2023.1.2, so that I had to install the older version.

Here is the relevant part of my code if you want to have a look at it. 

```
beep_sound=sound.Sound(900,secs=0.15)

def Training_dotTrial(myWin, nDot, signal,studyTime):

    test=visual.DotStim(myWin, nDots=nDot, fieldPos=(0.0, 0.0), fieldSize=(1), fieldShape='circle', dotSize=4.0)
    test.draw()
    respTime=core.Clock()
    myWin.flip()
    core.wait(signal)
    beep_sound.play()
    studyTime.reset()
    resp=event.waitKeys(maxWait=.6, keyList=['up','down'])
    Latency=studyTime.getTime()
    RT=respTime.getTime()
    myWin.flip()
    fixation = visual.TextStim(myWin, '+', color='green', height=0.1, pos=[0, 0], alignHoriz='center')
    fixation.draw()
    myWin.flip()

for c, stim in enumerate(training_stimlist):
    presdot = int(stim[1])
    signal = float(stim[0])
    trialResp = Training_dotTrial(myWin, presdot, signal,studyTime)

    PracticeFile.write('%i \t %i \t %.3f \t %i \t %.4f \t %.4f\n'
                       %(c, presdot, signal, trialResp['response'], trialResp['Latency'], trialResp['RT']))
    myWin.flip()
    core.wait(.5)
PracticeFile.close()
```

**Comment by naiqixiao** [comment]
I felt this issue might be related to an update in ptb sound driver. Double check if the sample rate of your audio file. For me, only 48kHz audio files work for me. Others claimed the opposite that only 44.1kHz files work.

**Comment by zeltass** [comment]
> I felt this issue might be related to an update in ptb sound driver. Double check if the sample rate of your audio file. For me, only 48kHz audio files work for me. Others claimed the opposite that only 44.1kHz files work.

Hi, thanks for the suggestion. However, the sound works in the first trial, but it fails the others. I believe if there was a problem with that, the sound would not have been played in the first trial either. Moreover, I do not have any audio files, I command psychopy to create a sound for me with the frequency and duration values that I provide.
And I tried many other solutions such as using sounddevice or other functions of psychopy. Unfortunately, they again only worked in the older version.

**Comment by naiqixiao** [comment]
I see. How about adding beep_sound.stop() at the end of each trial?

**Comment by zeltass** [comment]
The problem is solved by putting the beep variable as an input of the function and defining it within the trial loop:

```
def Training_dotTrial(myWin, nDot, signal,beep, studyTime):

    test=visual.DotStim(myWin, nDots=nDot, fieldPos=(0.0, 0.0), fieldSize=(1), fieldShape='circle', dotSize=4.0)
    test.draw()
    respTime=core.Clock()
    myWin.flip()
    core.wait(signal)
    beep.play()
    studyTime.reset()
    resp=event.waitKeys(maxWait=.6, keyList=['up','down'])
    Latency=studyTime.getTime()
    RT=respTime.getTime()
    myWin.flip()
    fixation = visual.TextStim(myWin, '+', color='green', height=0.1, pos=[0, 0], alignHoriz='center')
    fixation.draw()
    myWin.flip()

for c, stim in enumerate(training_stimlist):
    presdot = int(stim[1])
    signal = float(stim[0])
    beep=sound.Sound(900,secs=0.15)
    trialResp = Training_dotTrial(myWin, presdot, signal,beep, studyTime)

    PracticeFile.write('%i \t %i \t %.3f \t %i \t %.4f \t %.4f\n'
                       %(c, presdot, signal, trialResp['response'], trialResp['Latency'], trialResp['RT']))
    myWin.flip()
    core.wait(.5)
PracticeFile.close()
```
