### ISSUE TITLE
mouse coordinates doubled in Mac retina displays

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#5603]
I see some references to retinaScale in the psychopy source code but perhaps it's not included in the mouse.
See [this forum thread](https://discourse.psychopy.org/t/mouse-coordinates-doubled-when-using-deg-units/11188/5) for more details.

**Comment by peircej** [comment]
I believe this is fixed in 2023.2.0 through this PR:
https://github.com/psychopy/psychopy/pull/5758
