### ISSUE TITLE
Splash screen is too big

### ISSUE THREAD

**Issue by visserle** [psychopy/psychopy#5682]
Love psychopy, hate launching it. 
The splash screen occupies 1/3 of my total screen for over 30 s and I can't do anything about it anytime I open psychopy. Please make it either moveable or smaller. 
Thank you so much!

**Comment by peircej** [comment]
You can turn off the splash screen entirely in preferences, but I know what you mean. We'll look into it

**Comment by chguw** [comment]
> You can turn off the splash screen entirely in preferences, but I know what you mean. We'll look into it

Hi, I can't find the setting, can you tell me where it locates, thanks.
