### ISSUE TITLE
Bug: Microphone vocal onset RT is not recorded

### ISSUE THREAD

**Issue by shabkr** [psychopy/psychopy#5715]
OS: Windows 10 & 11
Coder or Builder?: Builder
PsychoPy or PsychoJS?: PsychoPy
Offline or Online: Offline
PsychoPy version: 2022.2.5, and other versions as well

See also Psychopy Form Post: https://discourse.psychopy.org/t/voice-key-rt-issues/35463

**What are you trying to achieve?**

I and other users are trying to use the microphone component to record the vocal onset RT. 

**What did you already try?**
I have tried unchecking & rechecking the ```Speaking start/stop times``` box in the microphone component, but this appears non-functional. I've tried building a voice-onset detector using the [psychopy.voicekey class](https://www.psychopy.org/api/voicekey.html) but haven't had success yet. 
The non-functional speaking start/stop times button might be a bug, and the voicekey class might just need some improved documentation/demos.

Is there currently a way to record vocal onset RTs in 2022.2.5+?

-shabkr

**Comment by TEParsons** [comment]
This is a feature we originally planned to include but (if memory serves) it wasn't possible with the backends we were using. I must have forgotten to remove the parameter (🤦), so thanks for catching this! 

This data will very soon (2023.2.0) be available thanks to the [psychopy-whisper](https://github.com/psychopy/psychopy-whisper) plugin, as whisper transcription does provide this information, though this won't be doable without manual code until probably the next major release (2024.1.0).

I believe that, if you're using the whisper backend in 2023.2.0+, you'll be able to do this in a Code component after the Routine has finished and transcription has happened:
```
speechStart = mic.lastScript.wordData[0]['start']
speechEnd = mic.lastScript.wordData[-1]['end']
thisExp.addData("mic.speechStart", speechStart)
thisExp.addData("mic.speechEnd", speechEnd)
```
(with `mic` being your Component name)

Though I've been unable to test this yet so don't take my word for it, @mdcutone will be able to give a more solid answer!

**Comment by shabkr** [comment]
Thanks for the update and the recommended code, @TEParsons. I will keep an eye out for the 2023.2 and 2024.1 releases!
-shabkr

**Comment by TEParsons** [comment]
It turned out to be much simpler than expected to fully add this functionality so this will actually be in the 2023.2 release! Checking "Speaking start/stop times" should add these to the data file :)

**Comment by Ziliang-Zhu** [comment]
Hi! I am interested in whether this bug have been solved? Actually, I have the similar question with the latest version of PsychoPy 2024.1.0.
Specificly, I run PsychoPy Builder on a PC with windows 11. I want to record the latency of the auditory respone (so the _Speaking start/stop times_ was checked). But the coresponding data was not generated in the output files (.csv). 
So, 1) I mean, the similar bug is still exist in the latest PsychoPy Builder? And, how can I fix it?
2) To record the speaking start/stop times, I must use the _Transcription_ module?
