### ISSUE TITLE
Bug: Component named 'self' in python is translated to 'this' in JS

### ISSUE THREAD

**Issue by roelofsaj** [psychopy/psychopy#5736]
Today we got a request for help troubleshooting an experiment that worked in PsychoPy but got stuck on the initialising screen in Pavlovia. The console log showed an invalid left-hand assignment error. It turned out they had named one of their components "self" (as in "self" image and "other" image), and the component name was translated to "this" in the JavaScript code, causing the error. I was able to duplicate the issue in a very basic experiment [here](https://gitlab.pavlovia.org/abbeyjoy/this_self/blob/master/this_self.js#L101). 

I looked around on the forums and issues but didn't see anything related to this, so apologies if it's a duplicate. At the very least it should maybe be mentioned in the documentation somewhere that "self" isn't currently a valid component name for experiments that will be run on Pavlovia.

**Comment by TEParsons** [comment]
We have a system in place to catch when a Component name is already used (i.e. as a Python keyword) which derives Python keywords from `keyword.kwlist`, but looks like `self` isn't on that list which probably explains why this is missed! Fully agree that a Component name "self" should be considered an invalid name. 

I wonder if it's also worth adding all Python terms from the PsychoJS translation dict as keywords... Most are probably already invalid for being numpy functions, Python keywords or containing invalid characters, but certainly if something is going to change on compiling to JS then it shouldn't be used as a Component name!
