### ISSUE TITLE
Saving Pyschopy Task CSVs in external storage such as Google Drive/Onedrive

### ISSUE THREAD

**Issue by NoxLab-cam** [psychopy/psychopy#5737]
Greetings!

Our laboratory has developed a psychopy task that we would like to share with other research labs. By providing them with the online task URL, they can ask their own participants to easily access and participate in the task. However, the challenge we face is that when someone uses our Psychopy task URL, the resulting CSV files are currently stored in our repository. This means that we have to manually share the CSVs with each lab that uses our task :frowning:

I am curious if you know of a solution that would enable others to use our task URL while allowing them to store their participants’ CSV responses in their preferred storage locations, such as OneDrive, Google Cloud, or other platforms. The main constraint is that we want to avoid requiring them to create their own GitLab repository for this purpose.

Your input would be greatly appreciated! Thank you so much for maintaining this platform that has been so useful in our academic studies!!

Sincerely,
Swati

**Comment by TEParsons** [comment]
This Issues list is for bug reports about PsychoPy, for help on this sort of thing you should post on the forum instead: https://discourse.psychopy.org/

It sounds like what you're wanting to do is run in "pilot mode" (i.e. data is downloaded by the participant on completion rather than being stored in the project repo) - can set the Running Mode to "Pilot" to achieve this

**Comment by srajwal1** [comment]
> This Issues list is for bug reports about PsychoPy, for help on this sort of thing you should post on the forum instead: https://discourse.psychopy.org/
> 
> It sounds like what you're wanting to do is run in "pilot mode" (i.e. data is downloaded by the participant on completion rather than being stored in the project repo) - can set the Running Mode to "Pilot" to achieve this

Thank you so much @TEParsons for the suggestion. However, the Pilot URL is valid only for 1 hour. So, a lab using our task's URL will only be able to collect data for one hour unless we regenerate the pilot url which is not very convenient. 

Do you have any other workaround?
