### ISSUE TITLE
No public implementation of GLFW backend plugin?

### ISSUE THREAD

**Issue by efunn** [psychopy/psychopy#5786]
I wanted to test the GLFW backend on PsychoPy 2023.1.3 but ran into the issue:
```
"GLFW window backend support is not installed. To get support, install "
"the `psychopy-glfw` package and restart your session."
```
`psychopy-glfw` does not exist on PyPI or anywhere like `github.com/psychopy/psychopy-glfw`. Is there a plan to create such a package/plugin, or is it not working for some other reason?

I ended up creating the plugin manually, using [the old GLFW backend code](https://github.com/psychopy/psychopy/blob/42f5a908ea7829f7a6e3192f330363d9c31e1761/psychopy/visual/backends/glfwbackend.py) as `__init__.py` in an empty `psychopy_glfw` package and replacing the local references with global psychopy ones (e.g. replace `from .gamma import createLinearRamp` with `from psychopy.visual.backends.gamma import createLinearRamp`).

It seems to work OK (I can draw my screen and stims with `winType='glfw'` now), but please let me know if there is an 'official' implementation or if I am missing something really silly.

**Comment by TEParsons** [comment]
The package exists as [mdcutone/psychopy-glfw](https://github.com/mdcutone/psychopy-glfw) - I'm not sure what state it's in but as soon as it's ready we'll push out to PyPi! In the meantime, it is installable via:
```
pip install git+https://github.com/mdcutone/psychopy-glfw
```

**Comment by efunn** [comment]
I'm guessing that's a private repo that you have access to? I can't see it at the url, pip install, or git clone.

**Comment by TEParsons** [comment]
Ah, it may be... Spoke to @mdcutone about this earlier today and he's pushing it to PyPi, so hopefully it'll be available via pip soon

**Comment by efunn** [comment]
Thanks, I can see it now. For what it's worth, the approach I took to manually make it appears about the same as what he did. So, now I know how to make PsychoPy plugins! 😅
