### ISSUE TITLE
ElementArrayStim not accepting Nx1 as colours

### ISSUE THREAD

**Issue by djmannion** [psychopy/psychopy#581]
ElementArrayStim has stopped accepting Nx1 to specify the colours. This is due to val2array (called by setColor, which is called by setColors) working with 1D arrays.

For example, passing a 100x1 array gives "ValueError: Invalid parameter. Should be length 3but got length 100".

It will break backward compatability for some people (but probably not many), but its probably easiest just to remove the section in the documentation that says that Nx1 will be accepted.

**Comment by dvbridges** [comment]
@peircej Has this been fixed?

**Comment by peircej** [comment]
Is definitely still current. The question (as @djmannion rightly says) is whether to fix the documentation or make the function `setColor` handle convert Nx1 into Nx3 automatically
