### ISSUE TITLE
[Bug]: ValueError when using visual.Circle: The truth value of an array with more than one element is ambiguous

### ISSUE THREAD

**Issue by luzhengang** [psychopy/psychopy#5847]
### PsychoPy Version

2022.2.5

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

I created a conda env using python 3.9. when I tried to draw a circle in a window, this value error appeared. 

### Expected Behaviour

Draw a circle.

### Steps to Reproduce

1.import psychopy.visual
2.win = psychopy.visual.Window(
    size=[400, 400],
    units="pix",
    fullscr=False,
    color=[1, 1, 1]
)
3.circle = psychopy.visual.Circle(
    win=win,
    units="pix",
    radius=150,
    fillColor=[0, 0, 0],
    lineColor=[-1, -1, -1]
)
...

**Comment by TEParsons** [comment]
Could you share the full script you were using and the full error stack? The code attached seems to work fine

**Comment by luzhengang** [comment]
I got this new M2 mac mini and tried to install PsychoPy on it. The program runs fine on an older Intel MacBook pro. Please see the screenshot. This is the whole script.
![Screenshot 2023-08-24 at 11 42 03 AM](https://github.com/psychopy/psychopy/assets/11756541/402d613d-50b7-4e37-9f47-3c14c681030c)

![Screenshot 2023-08-24 at 11 45 13 AM](https://github.com/psychopy/psychopy/assets/11756541/bf791138-68e7-417e-8b20-678412bc00fe)

**Comment by TEParsons** [comment]
Ah, I recognise that line... I fixed this bug in January this year, so the fix is in the latest version of PsychoPy. Should just be a case of updating your PsychoPy install :)

The specific commit is:
dbb872806aa63f738e51ca3e6ac9b1040616aed5

**Comment by luzhengang** [comment]
I used pip install psychopy. It didn't install the latest version of PsychoPy but instead installed 2022.2.5. So how can I update by pip?
