### ISSUE TITLE
[Bug]: Installing psychopy in a clean virtual-enviroment on Ubuntu 23.04 results in broken builder.

### ISSUE THREAD

**Issue by Jencke** [psychopy/psychopy#5848]
### PsychoPy Version

2023.1.3

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

I've Installed psychopy in a clean virtual environment (python 3.11.4) using pip. I can use the coder and in general, psychopy seems to work fine. However, starting the builder and clicking on any component in the Components sidebar (e.g. Keyboard) triggers an PsychoPy3 Error with the message:

`Traceback (most recent call last):
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/builder.py", line 2462, in onClick
    dlg = _Dlg(frame=self.parent.frame,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 1784, in __init__
    _BaseParamsDlg.__init__(self, frame=frame, element=element, experiment=experiment,
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 824, in __init__
    self.ctrls = ParamNotebook(self, element, experiment)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 675, in __init__
    page = self.CategoryPage(self, self.parent, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 516, in __init__
    self.addParam("name", param)
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 541, in addParam
    self.ctrls[name] = ParamCtrls(self.dlg, param.label, param, self, name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joerg/.virtualenvs/psychopy/lib/python3.11/site-packages/psychopy/app/builder/dialogs/__init__.py", line 120, in __init__
    fieldName=fieldName, size=wx.Size(self.valueWidth, 24))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
`

### Expected Behaviour

The Component should be added to the current trial.

### Steps to Reproduce

1. Setup new virtual enviroment
2. `pip install psychopy`
3. run the psychopy builder and click on any Component in the Components sidebar

### Additional context

arabic-reshaper==3.0.0
astunparse==1.6.3
beautifulsoup4==4.12.2
blosc2==2.0.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
decorator==4.4.2
distro==1.8.0
dukpy==0.3.0
egi-pynetstation==0.0.0rc1
esprima==4.0.1
et-xmlfile==1.1.0
ffpyplayer==4.5.0
fonttools==4.41.1
freetype-py==2.4.0
future==0.18.3
gevent==23.7.0
gitdb==4.0.10
GitPython==3.1.32
greenlet==2.0.2
html2text==2020.1.16
idna==3.4
imageio==2.31.1
imageio-ffmpeg==0.4.8
javascripthon==0.12
jedi==0.19.0
json-tricks==3.17.2
kiwisolver==1.4.4
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
moviepy==1.0.3
msgpack==1.0.5
msgpack-numpy==0.4.8
ntplib==0.4.0
numexpr==2.8.4
numpy==1.23.5
opencv-python==4.8.0.74
openpyxl==3.1.2
packaging==23.1
pandas==2.0.3
parso==0.8.3
Pillow==10.0.0
proglog==0.1.10
psutil==5.9.5
PsychoPy==2023.1.3
psychtoolbox==3.0.19.0
py-cpuinfo==9.0.0
pycparser==2.21
pyglet==1.5.27
pyparallel==0.2.2
pyparsing==3.0.9
pypi-search==1.2.2
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.12.2
pyserial==3.5
python-bidi==0.4.2
python-dateutil==2.8.2
python-gitlab==3.15.0
python-vlc==3.0.18122
python-xlib==0.33
pytz==2023.3
PyYAML==6.0.1
pyzmq==25.1.0
questplus==2023.1
requests==2.31.0
requests-toolbelt==1.0.0
scipy==1.11.1
six==1.16.0
smmap==5.0.0
soundfile==0.12.1
soupsieve==2.4.1
tables==3.8.0
tqdm==4.65.0
tzdata==2023.3
ujson==5.8.0
urllib3==2.0.4
websocket-client==1.6.1
wxPython==4.2.1
xarray==2023.7.0
xlrd==2.0.1
zope.event==5.0
zope.interface==6.0

**Comment by TEParsons** [comment]
I think this is fixed in 2023.2.0 onwards - in the release branch at least, that value `self.valueWidth` is now wrapped in `int()` so should be fine now.
