### ISSUE TITLE
[Bug]: PDF manual is empty

### ISSUE THREAD

**Issue by gdevenyi** [psychopy/psychopy#5855]
### PsychoPy Version

2023.2.1

### What OS are your PsychoPy running on?

Other

### Bug Description

The PDF manual linked at resources is empty:

https://psychopy.org/documentation.html

https://www.psychopy.org/PsychoPyManual.pdf

### Expected Behaviour

There is a manual.

### Steps to Reproduce

N/A

**Comment by peircej** [comment]
Ah, interesting! 🤔 
We did have a refactor of the docs a few weeks ago so will look and see why that seems to have broken the build of the pdf

thanks

**Comment by peircej** [comment]
This is definitely fixed now (a while ago but I forgot to close the issue)
