### ISSUE TITLE
[Bug]: App completely freezes after install

### ISSUE THREAD

**Issue by joshunrau** [psychopy/psychopy#5857]
### PsychoPy Version

2023.2.1

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

I tried to install the PsychoPy GUI app on my Macbook. When I opened the app it immediately froze and I had to force quit. Then I opened it again and it worked (although sometimes there were random freezes or slowdowns).

### Expected Behaviour

The app should not freeze at random, especially right after installation

### Steps to Reproduce

1. Install on Macbook
2. Try to run app

### Additional context

M1 Macbook Air

**Comment by peircej** [comment]
I can't replicate this on my silicon macbook air with standalone 2023.2.1, and there isn't enough information here to know where to start looking. Please re-open if anything more informative comes to light to narrow the issue down a little (e.g. is it to do with reloading a previous experiment that's struggling? Is it to do with a particular network configuration?
