### ISSUE TITLE
[Bug]: Failed to render empty cell

### ISSUE THREAD

**Issue by Tongzhao9417** [psychopy/psychopy#5867]
### PsychoPy Version

2023.2.1

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

Hi everyone, I’m a newcomer of psychopy. I faced a problem that I can’t solve. In order to better illustrate, I simplified my experimental question.

For example, I want to conduct two block. In every block, the text component would display text from the conditional file. The first text is $display1 and second text is $display2.

I want just show one text component in each block, so I set empty content in each block. For example, In block 1, I set display2 is empty. Similarly, $display1 is empty in block 2.

My question is that when the progress into block 2, the content of $display1 still remain on the screen. But the fact is the content of display1 is empty. Why did this problem occur? How could I show empty when the progress in block 2?

<img width="640" alt="image" src="https://github.com/psychopy/psychopy/assets/42951960/b25e3260-866a-4eb1-8682-a80ee292fad7">
<img width="640" alt="image" src="https://github.com/psychopy/psychopy/assets/42951960/0881885b-3a00-49dc-a33d-9ad5dcb3ab56">

Also, I found psychopy failed to solve the “None” text.
<img width="1055" alt="image" src="https://github.com/psychopy/psychopy/assets/42951960/2165f21c-acc5-4eaa-a07a-4d280963801b">

As the screenshot shown, the $display1 is None, but the "text: text = “it’s 10"” still display 10, the content of last block of $display1.

### Expected Behaviour

When the cell is empty, the text content is empty either.

### Steps to Reproduce

[text.zip](https://github.com/psychopy/psychopy/files/12484697/text.zip)
You can reproduce the bug by using  my example file

**Comment by TEParsons** [comment]
This is because blank cells are read in as `None`, and setting the text of TextStim to `None` means essentially "don't change"

If you want blank text, it's best to put a space in the cell so the text is set to just a space

**Comment by Tongzhao9417** [comment]
> This is because blank cells are read in as `None`, and setting the text of TextStim to `None` means essentially "don't change"
> 
> If you want blank text, it's best to put a space in the cell so the text is set to just a space

Thanks!  You solved my problem that bother me 3 days!!
