### ISSUE TITLE
[Feature Request]: more flexible settings for measuring frame rate

### ISSUE THREAD

**Issue by cbrnr** [psychopy/psychopy#5937]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

Creating a window with `psychopy.visual.Window()` now displays the text "Attempting to measure frame rate of screen, please wait…" as part of its initialization. Previously, PsychoPy measured frame rate without displaying any text.

### Expected Behaviour

I think the new text is highly distracting, and I'd prefer to have a blank screen instead (just like in previous versions). 

### Steps to Reproduce

1. Create a new window with `psychopy.visual.Window()`
2. You'll see the text while frame rate is being measured.

### Additional context

This question has also come up in the forum: https://discourse.psychopy.org/t/is-there-a-way-to-skip-frame-rate-measurement-on-each-initialisation/36232/1

**Comment by RickLongleyAS** [comment]
I have this issue, too, on MacOS Sonoma

**Comment by peircej** [comment]
This would be a good first issue for someone that wants to contribute. Ultimately we would like a new param in the psychopy/experiment/components/settings called `Check screen timing` that has these options:

1. with info message
2. with no info message
3. never

To achieve that (notably the (2) option) we also need to add an arg to `Window.getActualFrameRate`, something like `infoMsg="Attempting to measure frame rate of screen, please wait ..."`

**Comment by cbrnr** [comment]
I'd still consider this a bug, because the behavior changed suddenly, i.e. without prior notice. In addition, getting the previous behavior (no message) is impossible.

But anyway, I could implement this, at least the non-GUI part. I'd also argue for keeping the default behavior an empty message, because participants do not need to be confronted with the technical implementation details of a PsychoPy experiment. A blank screen for 1–2 seconds is much better than a confusing message, which has nothing to do with the experiment.

**Comment by peircej** [comment]
In software dev we consider a bug to be when something happens that was not the developers' intended behaviour. This was intended. It was also actually notified in advance, [in the changelog for 2023.2.0](https://github.com/psychopy/psychopy/releases/tag/2023.2.0) when it was introduced

Feel free to submit a PR for the parts you have knowledge about. We'll add the application control if that's not your thing.

We'll revisit, in the team, what to make the default and others can chime in here.

**Comment by cbrnr** [comment]
I didn't see that, I apologize for saying that it was not announced.
