### ISSUE TITLE
TextStim.antialias has no effect?

### ISSUE THREAD

**Issue by lindeloev** [psychopy/psychopy#594]
The TextStim remains antialiased whether I set antialias=True or antialias=False. I'm running Ubuntu 14.04 on my laptop, Intel/Nvidia graphics. Here's code to reproduce:

``` python
from psychopy import visual, event
win = visual.Window()
stim = visual.TextStim(win, text='Anti=False', antialias=False, pos=(0, 0.3), height=0.4)
stim_antialias = visual.TextStim(win, text='Anti=True', antialias=True, pos=(0, -0.3), height=0.4)
stim.draw()
stim_antialias.draw()
win.flip()
event.waitKeys()
```

![screenshot from 2014-05-06 10 04 25](https://cloud.githubusercontent.com/assets/1439417/2887088/18112d9a-d4f5-11e3-84ba-b59ac41fc56e.png)

**Comment by hoechenberger** [comment]
Does this problem still occur with the most recent release of PsychoPy?

**Comment by mmagnuski** [comment]
I can confirm on `1.84.1`.  
I'll check today with other `blendMode` too - I think I've had situations when some visual objects ignored anti-alias setting the other way - with anti-alias off all the time.
