### ISSUE TITLE
[Bug]: Psychopy crashing on startup with GTK-Error

### ISSUE THREAD

**Issue by jgman86** [psychopy/psychopy#5958]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

After installing psychopy on linux (tried every python version and approach - conda, pip, manual), psychopy opens up showing the tooltip or some message to warn for a change in version. After closing the dialog box the following error appears:

`Debug: "Shift+Tab" is not supported as a keyboard accelerator with GTK`

and psychopy closes down. After running it again, same behavior this error:

```
Shift+Tab" is not supported as a keyboard accelerator with GTK
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3.8: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted

```

I can not make it run, so I assume it is a bug, as I followed all installation instruction word by word. Help is much appreciated ! 

Greetings j*

### Expected Behaviour

Psychopy not crashing

### Steps to Reproduce

1. Installing Psychopy (no matter which approach)
2. Run it
...

### Additional context

My System Information:

```
         _,met$$$$$gg.           administrator@psyml206
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 11 bullseye
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.10.0-26-amd64
   ,$$P'              `$$$.      Uptime: 6h 27m
  ',$$P       ,ggs.     `$$b:    Packages: 2389
  `d$$'     ,$P"'   .    $$$     Shell: bash 5.1.4
   $$P      d$'     ,    $$P     Resolution: 3840x1200
   $$:      $$.   -    ,d$$'     DE: GNOME 3.38.4
   $$\;      Y$b._   _,d$P'      WM: Mutter
   Y$$.    `.`"Y$$$$P"'          WM Theme: Orchis-Grey-Dark-Compact
   `$$b      "-.__               GTK Theme: Adwaita-dark [GTK2/3]
    `Y$$                         Icon Theme: Adwaita
     `Y$$.                       Font: Cantarell 11
       `$$b.                     Disk: 348G / 2.1T (17%)
         `Y$$b.                  CPU: Intel Core i7-9700 @ 8x 4.7GHz [63.0°C]
            `"Y$b._              GPU: UHD Graphics 630
                `""""            RAM: 6377MiB / 15735MiB

```

**Comment by wieluk** [comment]
I don't know if you still need this but I managed to install psychopy with my installer on a debian 11 VM.

Here is the installer:
[https://github.com/wieluk/psychopy_linux_installer](https://github.com/wieluk/psychopy_linux_installer)

for debian 11 I only needed one extra step at the end:
`export QT_QPA_PLATFORM=xcb`

**Comment by peircej** [comment]
I'm closing at it looks like this is solved but @jgman86 reopen if you find the fix above doesn't solve the issue for you
