### ISSUE TITLE
Mismatch between 1.80.4 zip file and github in textbox

### ISSUE THREAD

**Issue by danielshub** [psychopy/psychopy#606]
The names of the contents of the 1.80.04 zip file
(http://downloads.sourceforge.net/project/psychpy/PsychoPy/PsychoPy-1.80.04.zip)
do not seem to match the 1.80 branch of the GIT hub
(https://github.com/psychopy/psychopy/tree/r1.80/psychopy/visual/textbox)  in the psychopy/visual/textbox/ directory. Specifically, on my Arch Linux system, the names are camelcase while the github names are lowercase (i.e., textgrid.py/textGrid.py and textureatlas.py/textureAtlas.py). The code in **init**.py wants textgrid.py. This causes two of the unit tests to fail.

**Comment by danielshub** [comment]
I think this has resurfaced. The 1.82 branch has lower case file names and the 1.82.02 zip file has camel case

**Comment by peircej** [comment]
dang, yes, possibly. I built that on a different machine to my normal so I'll need to check it. Thanks for picking it up.
