### ISSUE TITLE
ZIP releases (i. e. for classroom installations)

### ISSUE THREAD

**Issue by LenzWinkler** [psychopy/psychopy#6061]
### Description

I've noticed that there were no ZIP releases for PsychoPy version 2023.2.0, while for version 2023.1.3, a "PsychoPy-2023.1.3.zip" was still offered under Assets. Is there a specific reason for this (I couldn't find any information in the changelog)?

At our university, we use the Classroom installation (https://www.psychopy.org/recipes/classroomInstallation.html) so far. Following the instructions in section 5, "Updating to a new version," we typically download the latest .zip release, extract it, and replace the contents of <NETWORK_LOC>\psychopyLib\ with the contents of the zip file.

### Purpose

To utilize the Classroom installation (https://www.psychopy.org/recipes/classroomInstallation.html) and perform an update as described, you would typically follow these steps:

1. Navigate to the PsychoPy download page or GitHub releases section.
2. Download the latest ZIP release of PsychoPy.
3. Extract the contents of the ZIP file.
4. Replace the contents of <NETWORK_LOC>\psychopyLib\ (where <NETWORK_LOC> is the network location specified in our installation) with the extracted contents.

### Is your feature request related to a problem?

I no longer have the ability to perform an update as described at https://www.psychopy.org/recipes/classroomInstallation.html.

### Describe the solution you would like

I want to be able to download a ZIP release again, as before, to perform an update following the instructions at https://www.psychopy.org/recipes/classroomInstallation.html.

**Comment by peircej** [comment]
I've just checked and I recall the problem - it's that the system we use for packaging (used to be setuptools but now pyproject/pdm) outputs a tar.zg file instead of a .zip for the source distribution. You should be able to extract from the tar.gz file and proceed exactly as before though. It's just a different archive format. I'm closing this for now but let me know if it doesn't work
