### ISSUE TITLE
[Bug]: Selecting audio device in builder and coder. 

### ISSUE THREAD

**Issue by Mitchellb16** [psychopy/psychopy#6142]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

As described in this forum [post](https://discourse.psychopy.org/t/how-to-change-audiodevice-in-hardware-preferences/30982), switching audio device in builder preferences just reverts back to the default after hitting apply. 

I've tried to work around this by adding a code component to manually set the audio device as suggested by another user in that thread, but I then see the issue shown in this [thread](https://discourse.psychopy.org/t/error-with-psychportaudio-although-it-works-in-psychtoolbox/27764). I've tried both the ptb and pyo libraries. 

### Expected Behaviour

Sound device should change in preferences and be used in the experiment. 

### Steps to Reproduce

1. Install low latency sound card linked below with driver. 
2. Open psychopy builder and add a sound component. Specifying 250 (pure tone) as the Sound.
3. Open preferences > Hardware > audio device drop down > select your audio device (in my case Speakers (Lynx E44)
4. Run experiment. 

### Additional context

I'm using a low latency sound card, [Lynx e44](https://www.lynxstudio.com/downloads/e44/windows-driver-v2-build-26/) as my applications require audio output at frequencies not possible with the default windows card. This comes with its own driver that I've downloaded and added the .sys file name from the drivers folder (without the .sys extension), I'm not sure if this is correct. 

I'm able to produce sound from the sound card outside of psychopy, so the driver is properly installed.

**Comment by Mitchellb16** [comment]
For now, using the sounddevice backend and psychopy version 2022.2.5 bypasses this problem, but I'd love to be able to use the ptb package in the future!

**Comment by peircej** [comment]
We believe this is fixed in 2024.1.0 but let us know if it's still a problem in your set up

**Comment by Mitchellb16** [comment]
@peircej Thank you! How do I access the 2024.1.0 build? I'm only seeing up to the 2023.2.3 release here.

**Comment by TEParsons** [comment]
2024.1.0 is the release we're currently working on - to use the in-progress code you can `git pull` the `dev` branch of this repo and run from whatever IDE you prefer, but we're hoping to release in a matter of hours (days at most) so you're probably best off just waiting for the release as it'll have the usual straightforward installer :)
