### ISSUE TITLE
textbox can't handle windows in colorSpace 'named'

### ISSUE THREAD

**Issue by djsmedes** [psychopy/psychopy#618]
This isn't a big deal - just something to put on the TODO list.

In __init__.py within textbox, on lines 1017&1018, we see:

rgb=self._window.rgb
rgb=TextBox._toRGBA2(rgb,1,self._window.colorSpace,self._window)

If the window was originally created using a named color, like 'steelblue', self._window.colorSpace will return 'named', but self._window.rbg will return an rgb255 value. This causes the function _toRGBA2 to give this error (again, using steelblue as an example):

ValueError: TextBox: color: [  70.  130.  180.], opacity: 1, is not a valid color for color space named.

This error message comes from line 1164.

Hopefully this is an easy fix. Either way, it's not hard to work around it by simply ensuring that your window is created with an rgb255 value in colorSpace 'rgb255' (I also tried the ordinary 'rgb' colorSpace, which also worked; I don't know about the other colorSpaces).

**Comment by peircej** [comment]
I think this can be closed in favour of the new TextBox2 in PsychoPy 2020.2.
Textbox2 follows similar principles (caching a texture of glyphs and rendering blazing fast once the glyphs are uploaded) but it supports wider range of fonts and a cursor for receiving text input
