### ISSUE TITLE
bug in iohub eyelink binocular mode

### ISSUE THREAD

**Issue by herrlich10** [psychopy/psychopy#620]
In file psychopy / iohub / devices / eyetracker / hw / sr_research / eyelink / eyetracker.py, line 610:

```
g=[pylink.MISSING_DATA,pylink.MISSING_DATA]
```

should be

```
g=[0,0]
```

since `pylink.MISSING_DATA` is `-32768` in standalone psychopy v1.80.03

**Comment by isolver** [comment]
not actually a bug, using [0,0] could be a location.
