### ISSUE TITLE
[Bug]: default_eyetracker.yaml file for Gazepoint eyetracker is not found

### ISSUE THREAD

**Issue by kjaksic** [psychopy/psychopy#6207]
### PsychoPy Version

2023.2.3.

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

default_eyetracker.yaml file for Gazepoint eyetracker is missing from \envs\experimental\lib\site-packages\psychopy\iohub\devices\eyetracker\hw\gazepoint\gp3\ 

This causes calibration to crash.  

### Expected Behaviour

File should be present in the directory. 

### Steps to Reproduce

Run the calibration code with the current version of psychopy and the last version of https://github.com/psychopy/psychopy-eyetracker-gazepoint. 
...

**Comment by mdcutone** [comment]
I'm fixing this issue for the next release. We don't have a GazePoint tracker on-site. If you like, it would be great to help test out the fix once ready.

**Comment by kjaksic** [comment]
Great, sure, no problem.

Thanks.

**Comment by peircej** [comment]
Hi @kjaksic we've been making various fixes to plugins, especially around eyetrackers. We have a new release candidate for psychopy (2024.1.0rc12) and we'd love you to test it out if you can. You may need to update the psychopy-gazepoint plugin as well

windows: https://drive.google.com/file/d/1PjlyCKGLlN4cYSRqSfbXZpPgGilkS-Fg/view?usp=drive_link
macos: https://drive.google.com/file/d/14LgNDrQ9jyz081-asvStHR0dAgdU0izX/view?usp=drive_link

**Comment by kjaksic** [comment]
Hi Jon,

I will be out of office for about 10 days. I can test it when I get back,
if that works for you.

čet, 29. velj 2024. u 15:14 Jon Peirce ***@***.***> napisao
je:
