### ISSUE TITLE
[Bug]: Builder not correctly updating code when options are changed

### ISSUE THREAD

**Issue by MichaelWoodc** [psychopy/psychopy#6250]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

When updating the experiment in builder, the code doesn't get updated automatically.  Please see that the sizes for both different stim are the same:
![Screen Shot 02-19-24 at 12 04 PM 001](https://github.com/psychopy/psychopy/assets/51295010/ba3f2de8-41a8-49c1-9d6d-df6f9e90b3d8)
![Screen Shot 02-19-24 at 12 04 PM](https://github.com/psychopy/psychopy/assets/51295010/3f798d49-8e86-468f-a9c6-c255748838c8)
But, the result is this in code:

"
    option1Image = visual.ImageStim(
        win=win,
        name='option1Image', 
        image='fordvferrari1.jpg', mask=None, anchor='center',
        ori=0.0, pos=((-win.size[0]/3), 0), size=1.0,
        color=[1,1,1], colorSpace='rgb', opacity=None,
        flipHoriz=False, flipVert=False,
        texRes=128.0, interpolate=True, depth=-3.0)
		
    option3Image = visual.ImageStim(
        win=win,
        name='option3Image', 
        image='fordvferrari1.jpg', mask=None, anchor='center',
        ori=0.0, pos=(win.size[0]/3, 0), size=(win.size[0]/5,None),
        color=[1,1,1], colorSpace='rgb', opacity=None,
        flipHoriz=False, flipVert=False,
        texRes=128.0, interpolate=True, depth=-7.0)
"

The result visually for this issue is:
![sizediff](https://github.com/psychopy/psychopy/assets/51295010/41d3c5f7-c54d-4fec-aade-53d6cbfb9a01)

its a very small issue in the case of these images, but you can see the difference.  Please see attached code files:
[test.zip](https://github.com/psychopy/psychopy/files/14335204/test.zip)

### Expected Behaviour

I would expect the image sizes to update in the code after updating them in the builder

### Steps to Reproduce

1. open provided code
2. run experiment
3. screenshot images, notice how two identical ones are different sizes. 
4. generate python script and also notice the differences
...

**Comment by peircej** [comment]
You have set the size of `option1Image` to be `set every repeat` rather than constant. When you do this the size is initially set to a fixed arbitrary value (in this case a value of 1) and only gets set to `(win.size[0]/5,None)` when the `trial` Routine actually begins (on each repeat of the loop). Your `option3Image ` is set to `constant` so it gets its size setting applied when it is initialised.

So the image init code being written here is exactly as expected, but the code change you're looking for is not where you expected. 

Now, there's still a question of why are the images are a different size when set during init or set later, and that's one we'll need to investigate 🤔

**Comment by MichaelWoodc** [comment]
> You have set the size of `option1Image` to be `set every repeat` rather than constant. When you do this the size is initially set to a fixed arbitrary value (in this case a value of 1) and only gets set to `(win.size[0]/5,None)` when the `trial` Routine actually begins (on each repeat of the loop). Your `option3Image ` is set to `constant` so it gets its size setting applied when it is initialised.
> 
> So the image init code being written here is exactly as expected, but the code change you're looking for is not where you expected.
> 
> Now, there's still a question of why are the images are a different size when set during init or set later, and that's one we'll need to investigate 🤔

Sharp eye!  I hadn't noticed that!  I'm editing everything next week, I'll see if changing those things you pointed out on my end can have a different effect.  Thanks!

**Comment by MichaelWoodc** [comment]
I am thinking these issues may be related.  The experiment I had been working on utilized Emotiv EEG components.  I had to do some changes and disabled the Emotiv EEG components.  After re-enabling them, I consistently recieved errors that cortex_rec_2 is not defined, or something along those lines.  After creating an identical experiment from scratch it works!

I think that I am experiencing these issues when I disable a component for testing, then reenable it after, but I'm not entirely sure yet.

**Comment by peircej** [comment]
I'm going to close this one for now. It doesn't seem to be something that's universal/reproducible, but if you get any further in how to reproduce it reliably then let us know
thanks
