### ISSUE TITLE
iohub mouse setPosition not setting y position correctly

### ISSUE THREAD

**Issue by joshdoe** [psychopy/psychopy#631]
I'm trying to center the mouse cursor on an object, and can't use `event.Mouse.setPos()` since I'm using pyglet. The following should center the mouse cursor in the middle of the screen:

``` python
from psychopy import iohub
io = iohub.launchHubServer()
io.devices.mouse.setPosition((0, 0))
```

However this puts the cursor at the middle of the top edge of the screen. Looking in `setPosition()`, [`display._displayCoord2Pixel()`](https://github.com/psychopy/psychopy/blob/master/psychopy/iohub/devices/mouse/__init__.py#L285) returns a negative y component, which when checked with `self._validateMousePosition()` zeros out the y component, thus putting the cursor at the top of the screen.

I could fix this by changing [`iohub.devices.display.Display:_calculateCoordMappingFunctions:psychopy2displayPix()`](https://github.com/psychopy/psychopy/blob/master/psychopy/iohub/devices/display/__init__.py#L557) to `return l+(cx+w/2),t+(cy+h/2)`, but I'm almost certain I'm missing something obvious.

**Comment by isolver** [comment]
This might still be a bug. WTF. I'll look into it.

**Comment by isolver** [comment]
I see two issues:
- [x] iohub mouse.setPosition
- [x] initial mouse position before iohub receives any mouse events

Looks like issue is in iohub.devices.mouse..._initialMousePos(), which sets mouse position in native window env pixel space thathas not been converted to psychopy coord space.
