### ISSUE TITLE
[Bug]: Pandas version differs across operating systems

### ISSUE THREAD

**Issue by achennings** [psychopy/psychopy#6359]
### PsychoPy Version

2024.1.0

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

Recently upgraded to `2024.1.0` and was developing an experiment on my Mac OSX machine. When I went to test on a windows 10 machine, some custom code components broke.

The cause of this seems to be different versions of pandas across the different stand alone versions. Both versions report the same version of python (`3.8.10`). The OSX standalone reports a pandas version of `2.0.2`, while the Windows 10 version reports a pandas version of `1.3.4`.

Is this intentional? If yes, is there a way to update the included python package locally to match distributions?

### Expected Behaviour

I would expect included python packages to have the same version regardless of operating system.

### Steps to Reproduce

1. Download standalone `2024.1.0` on a windows machine
2. In Coder view, start a new session, `import pandas` and return the version number (`pandas.__version__`)
3. Repeat on an OSX machine.
...

**Comment by peircej** [comment]
No, I don't think this was deliberate. More likely there was a *need* to update at one point on the mac and it wasn't *needed* on windows, so windows got left as-is. But your point is fair - I've updated the windows pandas version to be 2.0.2 for the next release (PsychoPy 2024.1.2 onwards)
