### ISSUE TITLE
[Bug]: Use of pythonw on macos conda/mamba environments breaks app

### ISSUE THREAD

**Issue by berkgercek** [psychopy/psychopy#6420]
### PsychoPy Version

2024.1.3

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

When attempting to run the psychopy GUI app following an install in a fresh conda environment:

```
conda create -n pyschopy python=3.10
pip install pyschopy
psychopy
```
Psychopy fails to start.

### Expected Behaviour

Psychopy should not need to call pythonw for versions of python >= 3.9, and the if statement in `psychopyApp.py` should be modified to reflect that probably (or python < 3.9 support dropped entirely for newer versions of the package).

### Steps to Reproduce

After installing as above the following error is returned:

```
Traceback (most recent call last):
  File "/Users/MYUSERNAME/mambaforge/envs/intermod/bin/psychopy", line 8, in <module>
    sys.exit(main())
  File "/Users/MYUSERNAME/mambaforge/envs/intermod/lib/python3.10/site-packages/psychopy/app/psychopyApp.py", line 90, in main
    stdout, stderr = core.shellCall(cmd,
  File "/Users/MYUSERNAME/mambaforge/envs/intermod/lib/python3.10/site-packages/psychopy/core.py", line 153, in shellCall
    proc = subprocess.Popen(cmdObjects, stdin=subprocess.PIPE,
  File "/Users/MYUSERNAME/mambaforge/envs/intermod/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/MYUSERNAME/mambaforge/envs/intermod/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/MYUSERNAME/mambaforge/envs/intermod/bin/python3.10w'
```

This error happens because, according to `psychopyApp.py`, we need to call `pythonw` when running GUI scripts on MacOS in an Anaconda-based environment. However this is an outdated method as of Python 3.9, and [from that version onwards you can now directly call the python binary regardless](https://docs.python.org/3/using/mac.html#running-scripts-with-a-gui). 

In a fresh Python 3.10 installation via conda/mamba the pythonw binary does not exist in the binaries folder for the environment. I have for the moment fixed this by simply symlinking the base python binary to `python3.10w` which psychopy expects, which then allows the app to start.

**Comment by peircej** [comment]
Would the fix in https://github.com/psychopy/psychopy/pull/6423 solve the issue for you?

**Comment by berkgercek** [comment]
It would! But the issue exists for 3.9 too (just spun up a new environment to test). Won't the `>` comparator result in 3.9.0, an edge case admittedly, failing the test? Not sure how the comparator works for sys.version_info.

**Comment by peircej** [comment]
I think actually 3.9.0 gives True for being >3.9 but it won't hurt to change that to be >=(3,9)

**Comment by berkgercek** [comment]
Perfect! Thanks so much for the speedy resolution. I'll go ahead and close this ahead of the PR.
