### ISSUE TITLE
[Bug]: Not able to connect to my Pavlovia account when running local psychopy version

### ISSUE THREAD

**Issue by MarkellaEgglezou** [psychopy/psychopy#6475]
### PsychoPy Version

2024.1.4

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

I run my local psychopy version and tried to connect to my Pavlovia account and I got this error:
Traceback (most recent call last):
  File "C:\Users\user1\Desktop\psychopy\psychopy\app\pavlovia_ui\_base.py", line 128, in checkForLoginURL
    pavlovia.login(self.tokenInfo['token'])
  File "C:\Users\user1\Desktop\psychopy\psychopy\projects\pavlovia.py", line 111, in login
    if currentSession.user is not None:
  File "C:\Users\user1\Desktop\psychopy\psychopy\projects\pavlovia.py", line 465, in user
    self._user = User(self.gitlab.user.username)
  File "C:\Users\user1\Desktop\psychopy\psychopy\projects\pavlovia.py", line 158, in __init__
    assert 'gitlabId' in self.info, _translate(
AssertionError: Could not retrieve user info for user MarkellaE, server returned:
{}

### Expected Behaviour

Connecting to the Pavlovia account.

### Steps to Reproduce

1. Navigate to your local psychopy folder through Git
2. Run this command "python -m psychopy.app.psychopyApp"
3. After psychopy opens, try connecting to a Pavlovia account

**Comment by TEParsons** [comment]
I can't find your account on Pavlovia either:
https://pavlovia.org/MarkellaE

Is the username spelled correctly?

**Comment by MarkellaEgglezou** [comment]
Yes, it is spelled correctly. The link you are using in your comment works just fine for me. Can you still not find my account?

**Comment by TEParsons** [comment]
Strange, clicking on it now I can see it too, but I couldn't when I commented earlier. Maybe something's changed on the server - if you try from PsychoPy do you get the same error now?

**Comment by MarkellaEgglezou** [comment]
I don't get the error anymore and it works just fine. I have no clue what changed but thank you!
