### ISSUE TITLE
[Bug]:  Psychopy standalone won't open

### ISSUE THREAD

**Issue by brunomesqu** [psychopy/psychopy#6517]
### PsychoPy Version

2024.1.4

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

When I attempt to open the builder, coder, or runner, nothing happens. Not even a visible error message. However, when I check the last_app_load.log, I can see an ImportError related to an incompatibility between pandas and numpy.

### Expected Behaviour

That the builder would open as normal.

### Steps to Reproduce

1.Install Psychopy standalone through the official website
2. Attempt to launch the Builder.

### Additional context

[last_app_load.log](https://github.com/user-attachments/files/15517549/last_app_load.log)

**Comment by peircej** [comment]
Apologies, a version incompatibility between pandas and numpy did sneak in there. 2024.1.5 is imminent, with this fixed.
thanks
Jon

**Comment by TEParsons** [comment]
Closing as 2024.1.5 is now out :)
