### ISSUE TITLE
Buh in collecting Reaction Time

### ISSUE THREAD

**Issue by gersonaj** [psychopy/psychopy#653]
I programmed the Stroop Effect but for some stimuli and some participants the reaction time data value is absurd (e.g., 123.867.465.232). These values are found within correct ones in the Excel file. Any suggestions for correcting this bug?

Thank you, Gerson AJ.

**Comment by gersonaj** [comment]
Openning data in notepad was a very usefull suggestion. No problem in the data file was detected. Excel was misinterpreting the numbers. Because I used a portuguese Excel in portuguese 
separators are opposite to English: decimal separator corresponds to the character dot and thousand separator is comma. Making this change Reaction Time data is ok.

Thank ou very much for your help. I do appologize for my late comment. I had stopped using PsychoPy for a while since I had that problem.

**Comment by farialaris** [comment]
> Openning data in notepad was a very usefull suggestion. No problem in the data file was detected. Excel was misinterpreting the numbers. Because I used a portuguese Excel in portuguese separators are opposite to English: decimal separator corresponds to the character dot and thousand separator is comma. Making this change Reaction Time data is ok.
> 
> I am having the same problem. So, what did you do to fix it?

I change the clock.getTime for core.getTime, and the numbers got better. However, excel still showed some numbers like 1.635.545.800.003.450

**Comment by farialaris** [comment]
I am having the same problem. So, what did you do to fix it?

I changed the clock.getTime for core.getTime, and the numbers got better. However, excel still showed some numbers like 1.635.545.800.003.450
