### ISSUE TITLE
[Feature Request]: Builder: detect whether a Linux user can already change the priority, rather than checking for whether the .conf file exists?

### ISSUE THREAD

**Issue by aforren1** [psychopy/psychopy#6530]
### Description

Detect whether the current user has the power to change the priority of the process, rather than looking for an existing `99-psychopylimits.conf` file.

### Purpose

We pre-install PTB on our machines, and through that process users are already members of a group that can change nice/rtprio. When users run the Builder, they're prompted to add a config file that is redundant (in our case) with the existing PTB config/group.

Another potential issue (that I haven't run into & I don't know how likely it is) is that if a user didn't completely follow the instructions, the .conf file _could_ exist, but the user might not be a member of the proper group yet.

### Describe the solution you would like

I would return `False` in the `rush` implementations when the user fails to change the priority, such that PsychoPy can detect whether the priority change actually succeeded or not (currently only "fails" when the ctypes import fails). The Builder can then check whether `Priority(1)` succeeds, and display the config file info if it fails (or be more nuanced about "file exists, but user can't change priority"). 

This does change what `False` means in this context. Another potential drawback is that it would fail to detect if the user has already applied the current advice of setting `cap_sys_nice`, and I'm not sure if that's entirely equivalent to everything the config file does.

For uniformity, I would apply this change to all the `rush` implementations.

**Comment by peircej** [comment]
All this sounds good, yes.
