### ISSUE TITLE
[Bug]: Failed thread_policy_set with EyeLink eyetracker device

### ISSUE THREAD

**Issue by mh105** [psychopy/psychopy#6533]
### PsychoPy Version

2024.1.5

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

It has been reported [a few times](https://discourse.psychopy.org/t/error-when-trying-to-use-eyetracker/10943) in the forum from users using the EyeLink eyetracker from SR-research that there is an error prompt saying `thread_policy_set failed: 4`.

A quick google shows that `4` is an error code for `KERN_INVALID_ARGUMENT` in macOS's Mach kernel environment.

I suspect there might some sort of hard-coded config file for the EyeLink eyetracker that is triggering an incorrect argument to a `thread_policy_set()` call, since this same error prompt is not displayed when `mouseGaze` eyetracker is used (which follows the same steps to create a `ioHubConnection`).

@peircej Sorry to bug you on this, but would you mind providing some brief thoughts on how to investigate this further? My concern is that I don't know what exact policy was ioHub trying but failing to set, so I can't quite grasp on whether this is just a harmless warning message or it actually changes how the eyetracker subprocess is functioning within PsychoPy. Thanks so much!

### Expected Behaviour

This prompt should not appear.

### Steps to Reproduce

1. Select SR-Research EyeLink as the eye tracking device for an experiment
2. Run an experiment on macOS
...

### Additional context

It's possible that this problem is specific to ioHub on macOS, and it'll be fine for me to make a note here for future users that ioHub shouldn't be used with macOS.

**Comment by peircej** [comment]
Caveat: I didn't write this code and @isolver may have better insights

The places that our code touches thread priority are:
- using `psychopy.core.rush()` which ultimately [calls cocoa.thread_policy_set](https://github.com/psychopy/psychopy/blob/fe0e5dbe5288028f04d908ecc8a02000f384a0d8/psychopy/platform_specific/darwin.py#L133) (interestingly it seems macos also now has [thread_policy_set](https://developer.apple.com/documentation/kernel/1418892-thread_policy_set/) but also [thread_set_policy](https://developer.apple.com/documentation/kernel/1418608-thread_set_policy/) 🤷 ). 
- using `iohub.Computer.setPriority()` which ultimately [calls psutil.Process.nice()](https://github.com/psychopy/psychopy/blob/fe0e5dbe5288028f04d908ecc8a02000f384a0d8/psychopy/iohub/devices/computer.py#L131) but I'm not sure that even has any effect on macos (`nice` is more of a linux thing, as far as I know)

I don't *think* these calls are the issue but you could check whether they making a difference (maybe having multiple processes all trying to be dominant priority is an issue, for instance)

The other possibility, supported by the fact that this doesn't occur for the mouse option, is that maybe the pylink lib (or its underlying dylib) is the one causing the issue. To track that down, I think we'll need the SR Research engineers, and I'll try to get their input

**Comment by mh105** [comment]
Thanks so much @peircej for your inputs.

I've pinpointed the failed `thread_policy_set` to the `pylink` package on Apple chip macOS. I have reproduced it with `pylink` versions 2.1.1.0 and 2.1.762.0.

Minimal script to elicit the error message:
```
import pylink
pylink.EyeLink('100.1.1.1')
```
then you should see the error message about thread_policy_set failed posing up. 

I'll close this ticket and open a thread on their SR Research Support forum to ask about this. Thanks again.

**Comment by mh105** [comment]
For future reference: https://www.sr-research.com/support/thread-9062-post-35402.html#pid35402

**Comment by peircej** [comment]
Thanks yes, that's sort of what I expected. Last I knew SRR was using SDL for its stimulus rendering, which I moved away from some years ago because of the relative lack of control that it gives (versus direct handling of OpenGL and audio streams)
