### ISSUE TITLE
[Bug]: Eyetracker Recording - Stop Only - Hangs

### ISSUE THREAD

**Issue by domstoppable** [psychopy/psychopy#6568]
### PsychoPy Version

2024.1.5

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

When using separate `Eyetracker Record` components to start and stop a recording, the stop-component always hangs.

When using a single `Eyetracker Record` component to start-and-stop a recording, everything works as expected, but this has limited applications.

### Expected Behaviour

The eyetracker recording state should be disabled and the experiment should not hang

### Steps to Reproduce

1. Start a new experiment in Builder and configure an eyetracker (I have replicated this with MouseGaze and Pupil Labs (Neon))
2. Add an `Eyetracker Record` component and set it to "Start Only"
3. Modify the routine to have a duration of, say, 3 seconds
4. Add a new routine at the end of the flow
5. Add an `Eyetracker Record` component to the new routine, and set it to "Stop Only"
6. Run the experiment
7. Observe that the experiment hangs. Hit `escape` to bail
8. In the log, you'll see a message for `eyetracker.setRecordingState(True)`, but not one for stopping the recording.
...

**Comment by TEParsons** [comment]
This is fixed in the dev branch now, so fixes will be in 2024.2.0 :)
