### ISSUE TITLE
attrib error for ImageStim using setImage = None

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#666]
@lindeloev (I think you can help with this one, Jonas?)

When updating an ImageStim with the setImage instance method to the value None, there's an attribute lookup error. Seems to me you should still have an image attribute with value none, but maybe there's some dark magic that I'm missing. 

I'm lame and not writing a test ATM, but this script shows the error:

``` python
from psychopy import visual
win = visual.Window(fullscr=True)
image = visual.ImageStim(win=win, name='image',image='sin')
image.setImage(None)

    Traceback (most recent call last):
  File "/Users/kastman/Dropbox (Harvard SNP Lab)/untitled.py", line 6, in <module>
    image.setImage(None)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/visual/image.py", line 279, in setImage
    logAttrib(self, log, 'image', value)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/tools/attributetools.py", line 83, in logAttrib
    value = getattr(self, attrib)
AttributeError: 'ImageStim' object has no attribute 'image'
```

Low priority, but there are lots of valid uses where image=None, so it's probably worth throwing a catch in to the logger?

**Comment by hoechenberger** [comment]
Does this issue still exist?

**Comment by peircej** [comment]
I can't reproduce on 1.84. I think it's done
