### ISSUE TITLE
[Bug]: Calibration for Gazepoint eye tracker giving green screen which flashes 2-3 times.

### ISSUE THREAD

**Issue by krishna-raj-sr** [psychopy/psychopy#6750]
### PsychoPy Version

2024.1.5

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

Builder Calibration for Gazepoint eye tracker giving green screen which flashes 2-3 times.  The starting calibration screen and ending calibration screen show perfectly. If the calibration routine is skipped the eye-tracking data is recorded.

### Expected Behaviour

The eye tracker calibration points and screen should be displayed perfectly.

### Steps to Reproduce

1. Install 2024.1.5 on Windows 11. Install Gazepoint Plugin. 
2. Connect the Eye tracker and run the Gazepoint control.
3. Open the Eye tracker demo experiment. Select Gazepoint Eye Tracker.
4. Run the experiment.
5.
...

### Additional context

I had to add GazepointSampleEvent to PsychoPy\Lib\site-packages\psychopy\iohub\devices\eyetracker\hw\gazepoint\  init files to get it working in the first place

**Comment by TEParsons** [comment]
That sounds like the same bug we were seeing in a few backends - basically it's a unit mismatch making the calibration target huge (e.g. rather than 30px it would be 30x the height of the screen). Try with v2024.2.1 of PsychoPy and v0.0.2 of psychopy-gazepoint, it *should* be fixed I think

**Comment by krishna-raj-sr** [comment]
This issue is sorted when tried with the v2024.2.1 of PsychoPy and v0.0.2 of psychopy-gazepoint
