### ISSUE TITLE
Demo defunct: LaunchScan no longer exists

### ISSUE THREAD

**Issue by skjerns** [psychopy/psychopy#6761]
I have tried using the `fMRI_launchScan` demo in the most recent version of PsychoPy. However, it seems that this does not work anylonger (possibly due to the changes in the plugin system?). (see also #5647), even after `pip install psychopy-mri-emulator`.

https://github.com/psychopy/psychopy/blob/66e617fbaeb138cb64fbf96596cd1684a4c6743c/psychopy/demos/coder/experiment%20control/fMRI_launchScan.py#L13

```python
from psychopy.hardware.emulator import launchScan
ImportError: cannot import name 'launchScan' from 'psychopy.hardware.emulator' 
```

easy fix that I found was to import it directly from the supplying package. However, the demo itself is also outdated and calling old routines/components that no longer exist.

```
from psychopy_mri_emulator import launchScan
```

Generally, I found the documentation and demos to be rather confusing, linking to non-existent pages (e.g. https://psychopy.org/api/hardware/emulator.html , the links for further documentation don't go anywhere).

I'm currently trying to setup an fMRI experiment, and it seems like with the current documentation that turns out to be rather tricky and involving a lot of trial&error

**Comment by caggursoy** [comment]
I have used a workaround to install an earlier version, namely version `2024.1.0` and `psychopy-mri-emulator` from pip. Somehow the emulator part is completely gone in the newest versions. 

But until they come back;
`pip install psychopy==2024.1.0 && pip install psychopy-mri-emulator` should work.

**Comment by TEParsons** [comment]
Looks like the plugin is missing entry points (meaning e.g. `psychopy.hardware.emulator.launchScan` isn't replaced by `psychopy-mri-emulator.emulator.launchScan` when `activatePlugins` is called) so I've [submitted a PR](https://github.com/psychopy/psychopy-mri-emulator/pull/3) to add them, and also added basic documentation / testing / publishing actions in line with most other plugins.

The other part of this is that there wasn't a `PluginStub` for `launchScan`, meaning when you import it you just get "not found" rather than a more helpful "Please install plugin xyz", so I've sorted that out in #6774. Once the documentation for the plugin is built and hosted, I'll change the `PluginStub`'s documentation link from the generic plugins pages to the specific documentation for that plugin.

**Comment by nhuneke** [comment]
I tried to run an fmri experiment today on a new machine. Downloaded latest version of psychopy, but received this error

```
from psychopy.hardware.emulator import launchScan
ImportError: cannot import name 'launchScan' from 'psychopy.hardware.emulator' 
```

Same error when I updated the name to `psychopy_mri_emulator`.

Based on other comments and pull requests, shouldn't this be fixed?

**Comment by TEParsons** [comment]
The fix to give a more helpful error message when importing launchScan is only in the dev branch, which won't make it into a released build until the next major release (2025.1) - however if you install `psychopy-mri-emulator` via the plugins and packages manager in Builder then you should then be able to import `launchScan` from `psychopy.hardware.emulator`

**Comment by nhuneke** [comment]
Thank you! Good to know!

**Comment by yukaizou2015** [comment]
> The fix to give a more helpful error message when importing launchScan is only in the dev branch, which won't make it into a released build until the next major release (2025.1) - however if you install `psychopy-mri-emulator` via the plugins and packages manager in Builder then you should then be able to import `launchScan` from `psychopy.hardware.emulator`

I installed `psychopy-mri-emulator` via the plugins and packages manager in Builder, restarted PsychoPy and my PC, yet got the error message:

```
>>> from psychopy.hardware.emulator import launchScan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'launchScan' from 'psychopy.hardware.emulator' (D:\Program Files\PsychoPy\lib\site-packages\psychopy\hardware\emulator.py)
```

I am on the latest version of psychopy (`2024.2.2`).

**Comment by TEParsons** [comment]
Is this from Builder or Coder? If from Coder (or from the Python shell in Coder), did you first do:
```
from psychopy import plugins
plugins.activatePlugins()
```

**Comment by yukaizou2015** [comment]
> Is this from Builder or Coder? If from Coder (or from the Python shell in Coder), did you first do:
> 
> ```
> from psychopy import plugins
> plugins.activatePlugins()
> ```

Thanks! After running the two lines first I am now able to import `launchScan` from `psychopy.hardware.emulator` without issue. 

I wasn't aware that the two lines need to be run first. In the future it would be helpful to update the [plugins documentation](https://psychopy.org/usingplugins.html).
