### ISSUE TITLE
cleanup hangs after microphone.record is called

### ISSUE THREAD

**Issue by susinmotion** [psychopy/psychopy#677]
I'm running the following code snippet to record using the microphone, and my script never terminates.  

``` .py
from psychopy import microphone
microphone.switchOn(48000, outputDevice=None, bufferSize=None)
mic = microphone.AdvAudioCapture()
mic.record(5)
```

I'm on Mac OS 10.7.5, using python 2.7.8 and psychopy 1.81.00rc1.  I ran the code using verbose mode (`python -v`) and noticed that the cleanup stage seems to hang. The full output is [here](https://gist.github.com/susinmotion/8531c8bcab810d61cae9) - notice that the last line, which never terminates, is `cleanup[2] psychopy.sound`. It looks like the sound module might be trying to clean up open files, but I'm not sure if that's the source of the problem.

**Comment by jeremygray** [comment]
I am getting this or very similar for playing sounds (when using pyo at least).
