### ISSUE TITLE
[Bug]: pyglet window rendering on macOS

### ISSUE THREAD

**Issue by mh105** [psychopy/psychopy#6795]
### PsychoPy Version

2024.*

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

There are a collection of strange behaviors of the `pyglet` backend when opening windows on macOS arm64. The combination of the bugs makes me suspect that there might be some hard-coded logics that are failing for edge cases, which may be reproducible on Windows as well as on Intel macOS.

**[Bug 1]:** Opening a window in full screen seems to disable keyboard inputs, and `win.close()` does not actually close a window.

Running
```python
from psychopy import visual
win = visual.Window(screen=0, fullscr=True)
```
will disable keyboard inputs. But running without full screen option as

```python
from psychopy import visual
win = visual.Window(screen=0, fullscr=False)
```
does not disable keyboard inputs.

In both cases, then calling 
```python
win.flip()
win.close()
```
opens the window but does not close it.

**[Bug 2]:** When there are 2+ monitors, the arrange of their positions is impacting the display. This shows up in a few ways:

- If the main display and the extended display are organized vertically, we have the following issue:
```python
from psychopy import visual
win = visual.Window(screen=1, fullscr=False)
```
for the first time crashes with the error
```python
AttributeError: 'NoneType' object has no attribute 'frame'
```
from the `pyglet` package itself, which is called within `psychopy.visual.backends.pygletbackend.py`. However, running this second time does not have the same error and can indeed `win.flip()` correctly to display, although `win.close()` still doesn't close it properly.

- When there are 2+ monitors, setting `screen` to anything but `1` in the experiment setting panel in Builder will show the experiment display on the correct screen, but there are vertical offsets filled by black color depending on how the multiple screens are arranged in the macOS Displays Setting -> i.e., the relative positions of the two screens seem to impact how the PsychoPy pyglet screen gets draw. 

p.s.: when the selected screen is filled by black during display, after escaping the experiment, the pilot-run button in the Builder gets automatically toggled into `pilot` even when it was on `run`. I have to say this is the weirdest behavior of all...

### Expected Behaviour

None of the bugs should be present, which all impact experiment display on macOS.

### Steps to Reproduce

I have provided minimal scripts to reproduce the bugs on macOS in the bug description.

### Additional context

@TEParsons I tried looking into this myself but the weird behaviors are making my head spin... any insights would be greatly appreciated! I hope those two-line scripts to reproduce the bugs can help us narrow down on what's happening and fixing them.

**Comment by peircej** [comment]
Could I just confirm, is this on Mac Silicon using Rosetta or with your own (Arm) Python?

**Comment by mh105** [comment]
> Could I just confirm, is this on Mac Silicon using Rosetta or with your own (Arm) Python?

Both produce the same results! For Rosetta I just open a REPL Python session in Coder, and for my own Python I open a Python session from a conda environment with PsychoPy installed.

**Comment by peircej** [comment]
Oh, wait, you're typing these commands into a terminal rather than running a script? I don't think pyglet is designed to work like that due to its app event loop

**Comment by mh105** [comment]
Ah that's a good point. That's likely why [Bug 1] showed up - because running scripts from PsychoPy app indeed works fine. I had that suspicion but I didn't see it had to be wrapped in app contexts in PsychoPy codes so I thought it could be cold called. My bad!

Then I guess the remaining bug here is how the vertical offset is not set correctly for multiple screens on extended display. I'm making some progress in this direction. Looks like the issue occurs during `self.backend.swapBuffers(flipThisFrame)`. And I just confirmed that this is not an issue on Windows - it's likely something specific about Cocoa windows...
