### ISSUE TITLE
[Bug]: Within loop, key_resp start condition as time is ignored

### ISSUE THREAD

**Issue by gjpstrain** [psychopy/psychopy#6932]
### PsychoPy Version

2024.2.3

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

For a routine in a loop; key_resp start time is set to 1 second, meaning that routine should not accept the key_resp unless t >1. Currently, this is ignored and the key_resp can be triggered at any time.

### Expected Behaviour

Key_resp should be disabled until t >1

### Steps to Reproduce

1. Create routine with key_resp
2. Loop around routine with dummy csv
3. set key_resp start condition as duration = 1 second
...

**Comment by peircej** [comment]
Do you have "discard previous" turned on?
<img width="783" alt="image" src="https://github.com/user-attachments/assets/06aeb8a3-c43d-4906-a6d4-c3282f13b131">
If not discarding previous, then a keypress executed before the onset of the keyboard component will still be treated as a key press as soon as the compon starts

Other than that I believe this is working as expected. In the attached experiment file I just ran a test by prssing the the key before the keyboard onset in the first 2 trials (not registered) but within the keyboard period on the following 3 trials (worked fine in the csv file)

data file: [763556_test_keys_2024-10-23_15h39.05.576.csv](https://github.com/user-attachments/files/17493703/763556_test_keys_2024-10-23_15h39.05.576.csv)
exp file: [test_keys.psyexp.zip](https://github.com/user-attachments/files/17493713/test_keys.psyexp.zip)

**Comment by peircej** [comment]
Closing for now but reopen with more information about it going wrong if there's still a problem

**Comment by gjpstrain** [comment]
Thanks Jon. Yes I had discard previous on. I have attached an exp file with the routine I was experiencing an issue with isolated. Funnily, downgrading to 2024.2.1 (with nothing changed) results in the expected behaviour, which is participants having to wait a second in between being able to press space to move onto the next item.

[keypress_Test.zip](https://github.com/user-attachments/files/17506675/keypress_Test.zip)

Edit: I am unable to pilot locally, so have just been piloting on pavlovia
