### ISSUE TITLE
[Bug]: Cannot open file in PsychoPy Coder

### ISSUE THREAD

**Issue by CyrusYu812** [psychopy/psychopy#6935]
### PsychoPy Version

Python 3.13.0

### What OS are your PsychoPy running on?

macOS Intel

### Bug Description

When I was trying to open file in Psychopy Coder, a window popped up and showed me the traceback: 

It said that "Psychopy encountered an unhandled internal error! please send the report under "details" to developers with a description of what you were doing with the software when the error occured"

The Details are:
Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/coder/coder.py”, line 2376, in fileOpen
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/coder/coder.py”, line 2326, in setCurrentDoc
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/coder/fileBrowser.py”, line 668, in gotoDir
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/app/coder/fileBrowser.py”, line 633, in updateFileBrowser
AttributeError: ‘AuiFloatingFrame’ object has no attribute ‘filename’

The code can run smoothly on other PCs with MacOS system, but crashed on this one.

### Expected Behaviour

If everything is going well, I should successfully open the experiment file in the PsychoPy Coder window and then run the experiment.

### Steps to Reproduce

1. Open the PsychoPy and the PsychoPy Coder
2. Click on the "file" icon to open the file
3. The window that shows error would pop up, as described in the Bug Description setion.
...

**Comment by mdcutone** [comment]
Thanks for reporting this, I'll check it out

**Comment by TEParsons** [comment]
I think I've come across this before - there's a function in wx called `GetTopLevelParent` which I'd used in a few places to get reference to the Coder frame itself. Problem is that the behaviour of wx.aui elements (which the Coder frame is) isn't consistent across OS's - on Windows it considers the floating frame a child of the actual frame, so the frame is the top level parent, on Mac (or at least, on some Mac distributions) it doesn't, so the floating frame is the top level parent. This means it's trying to say "Give me the attribute `filename` of the Coder frame" and is actually saying "Give me the attribute `filename` of the AUI floating frame" (hence the error).

As the Coder frame is referenced in the file browser panel anyway (`self.coder`) I think this should be a one-line fix! Will put in a PR
