### ISSUE TITLE
Two (or more) apertures in one experiment

### ISSUE THREAD

**Issue by thomastweets** [psychopy/psychopy#695]
Hello there!

I think I found a bug that occurs when two different apertures exist in one experiment. The shape of the first defined (and used) one is ignored and substituted with the shape of the second defined aperture. I am using 1.80.06

This code produces a circular aperture (while I actually call aperture.enable() that uses a 'square' shape):

```
#!/usr/bin/env python2

"""Demo for the class psychopy.visual.Aperture().
Draw two gabor circles, one with an irregular aperture and one with no aperture.
"""

from psychopy import visual, event

win = visual.Window([400,400], allowStencil=True, units='norm')
instr = visual.TextStim(win, text="Any key to quit", pos=(0,-.7))
gabor1 = visual.GratingStim(win, mask='circle', sf=4, size=1.2, color=[0.5,-0.5,1])
gabor2 = visual.GratingStim(win, mask='circle', sf=4, size=1.2, color=[-0.5,-0.5,-1])

# NOTE: size in Aperture refers to the diameter when shape='circle';
# vertices or other shapes are scaled accordingly
aperture = visual.Aperture(win, size=.9, shape='square')  # or try shape='square'
aperture2 = visual.Aperture(win, size=.9, shape='circle')  # or try shape='square'

print aperture._shape
while True:
    aperture.disable()  # enabled by default when created
    gabor1.draw()
    instr.draw()
    aperture.enable()  # drawing is now restricted to be within the aperture shape
    gabor2.draw()
    aperture.disable()

    win.flip()
    if len(event.getKeys()):
        core.quit()
```

**Comment by christophe0077** [comment]
Is this still True ? I can't get two apertures to run on 2 differents screens.

`# --- Initialize components for Routine "trial" ---
aperture = visual.Aperture(
    win=win, name='aperture',
    units='norm', size=[1], pos=(0, 0), ori=0.0,
    shape='circle', anchor='center'
    ,depth=0
)
aperture.disable()  # disable until its actually used
aperture_2 = visual.Aperture(
    win=win2, name='aperture_2',
    units='norm', size=[1], pos=(-1,-1), ori=0.0,
    shape='triangle', anchor='bottom-left'
    ,depth=-1
)
aperture_2.disable()  # disable until its actually used`

I always get a stack underflow error on the aperture_2 initialisation.

Is there an other way to workaround this ?

Thank you
