### ISSUE TITLE
[Bug]: Additional Configuration Needed... window continuously reappears on Ubuntu 24

### ISSUE THREAD

**Issue by wieluk** [psychopy/psychopy#6950]
### PsychoPy Version

dev (2024.3.0)

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

On Ubuntu 24 (and possibly other Linux distributions), the `Additional Configuration Needed...` window appears each time PsychoPy is launched, even if configuration has already been completed manually or via script. The `Done` button doesn’t close the window (only the `X` does). The Window reappears on every launch of PsychoPy.

### Expected Behaviour

The window should open at most once or not at all if configurations are already set. Pressing Done should close the window.

### Steps to Reproduce

1. Install on ubuntu 24.04
2. Open PsychoPy
3. Done button does nothing, close with X, close PsychoPy
4. Reopen Psychopy
5. Window appears again

**Comment by peircej** [comment]
The test for whether to raise that dialog is simply coming from:
`os.path.isfile("/etc/security/limits.d/99-psychopylimits.conf")`
but the user may have called the file something else (and maybe different linux flavours put the file in different locations?)
https://github.com/psychopy/psychopy/blob/1843d55b3b2c71556ef79a69e21a9dd54c7b9290/psychopy/app/linuxconfig/__init__.py#L132

Happy for pull requests to improve the behaviour e.g. 
- better test for whether the configuration is alreaady implemented
- alternatively, if your new installer script is typically adding this setting during install then maybe we should just start checking at runtime or trapping when it goes wrong (psychtoolbox will crash if it doesn't have powers to raise process priority)

**Comment by wieluk** [comment]
The install script is adding the file automatically, placing it in `/etc/security/limits.d/99-psychopylimits.conf` for every distribution. I haven’t looked into the details—I just used it as is.

Interestingly, the check runs without issues on version 2024.1.4. However, on version 2024.2.4 and the Git version, this problem appears.

**Comment by aforren1** [comment]
In https://github.com/psychopy/psychopy/pull/6535 I changed the behavior such that it detects whether the user can _actually_ change the priority, etc. Is the user a member of the correct group?

Sorry if I broke something!

**Comment by peircej** [comment]
We can see the issue with the Done button not having an effect - that one will be an easy fix - but I can't say why the test is now failing since @aforren1 made the test more exact.

**Comment by wieluk** [comment]
Sorry, my mistake! A reboot is needed to apply `/etc/security/limits.d/99-psychopylimits.conf`. Maybe we add this to the info message? I’ll also add it to the installer output.

**Comment by peircej** [comment]
OK, well now we know that if the file exists but the permissions don't work, it probably needs a reboot
