### ISSUE TITLE
Please include python-bidi package in PsychoPy distribution for Windows

### ISSUE THREAD

**Issue by ehsabd** [psychopy/psychopy#730]
Hi,
I'm from Iran. I use PsychPy for presenting **Persian** text stimuli. Texts in the Persian language are from Right to Left and strings need to be reshaped. For this purpose I need to use **python-bidi** package (https://pypi.python.org/pypi/python-bidi). I install this package manually. Considering the small size of the package (less than 100 kB) it would help a lot if you include the package in PsychoPy preinstalled packages because I have difficulty when I want to have other less professional people work with my experiment project in their computer. It's very hard for them to install python-bidi from command line. I appreciate if you help me this way. This will help all people who want to present **Arabic or Persian** text stimuli (Affects almost all people in the Middle-East who want to use PsychoPy for their local experiments).
Thanks.

**Comment by m-macaskill** [comment]
bidi was added to the PsychoPy 1.82.00 standalone in Jan 2015, so presumably this issue can be closed.
