### ISSUE TITLE
no xlwt in standalone psychopy

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#745]
I often use pandas dataframe to hold information about trials, responses etc.
At specified points in the experiment I then use `to_excel` method of the dataframe.
Unfortunatelly this does not work out of the box with standalone psychopy because `xlwt` module is not distributed with it.
Just thought it may be worth pointing out that some pandas dependencies are not present in standalone psychopy.

**Comment by peircej** [comment]
This has been added to standalone in version 1.82.00

**Comment by mmagnuski** [comment]
Thanks!

**Comment by peircej** [comment]
Sorry, I had to rebuild my build system and forgot that xlwt is used by some people :-/
This is on win32?

**Comment by mmagnuski** [comment]
Yes, windows. I am using pandas to read and write experiment data and I'm saving both csv and xls just in case. But I'm manually adding xlwt now, so that's not a problem.
