### ISSUE TITLE
TextStim.height is reported differently in psychopy 1.81

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#746]
I sometimes rely on checking `TextStim` height parameter to move the text around if it does not fit the screen or add a semi-transparent box between the text and other objects in the background.
In psychopy 1.79 this works correct - the height parameter works as expected.
However in psychopy 1.81 I always get one value irrespective of the actual text box size. Even if the text spans many lines the height parameter contais the value I specified when defining the TextStim object (previously - in 1.79 if the text was wrapped the height value changed).
Is the text box height now a separate parameter?

**Comment by hoechenberger** [comment]
@mmagnuski You may open a new issue with this feature request if you like :)

**Comment by peircej** [comment]
I think the TextStim `boundingBox` attribute does what you're requesting:
http://www.psychopy.org/api/visual/textstim.html#psychopy.visual.TextStim.boundingBox

**Comment by mmagnuski** [comment]
Oh, yes, I tested it now - it shows the same as `_fontHeightPix` for height, but also gives width, thanks!

**Comment by peircej** [comment]
I think it should also handle multiple lines whereas `_fontHeightPix` should be the height of a single line (i.e. the font)

**Comment by mmagnuski** [comment]
Actually `_fontHeightPix` gives multi-line height, while `_heightPix` single line height, but I agree it should be the other way around.
