### ISSUE TITLE
Design tips sought: working on a TrialHandlerExt class that takes a list as nRep

### ISSUE THREAD

**Issue by suddhasourav** [psychopy/psychopy#779]
I'm working on a TrialHandlerExt class that extends the TrialHandler class, and overrides some methods to allow for a list as nReps. Instead of presenting the same number of repetitions for all trial types, this will allow us to specify the number of trials for each type. I'm working on it because the present solutions involve some sort of hacks, and oddball paradigm is used a lot in EEG research.

Before I commit the code though, I'd like to know if I'm violating any core design principles of PsychoPy :-)

Design decisions:
1. Only sequential or full randomization of trials
2. thisRepN will be a list too
3. sequenceIndices is a sum(nRep) x 1 array

Your opinions would be appreciated!

**Comment by peircej** [comment]
I'm moving this to the dev mailing list so that others might contribute 
(it won't get seen by many people as a github issue).

**Comment by peircej** [comment]
https://groups.google.com/forum/#!topic/psychopy-dev/V7cJQ8Q3aLQ
