### ISSUE TITLE
visual.DotStim speed incorrect?

### ISSUE THREAD

**Issue by feilong** [psychopy/psychopy#781]
It seems for me that the speed of dots is relative to the field size of the DotStim. I'm testing the speed using the following code (unit='deg', fps=60) with various width of fieldSize. I counted the number of rebirth for that dot and I got roughly 60 counts each time.

``` python
dot = visual.DotStim(win=win, fieldSize=(10, 5), nDots=1, dotSize=s, dir=0.0, dotLife=-1, coherence=1, speed=1.0/60, units='deg')
while clock.getTime() < 30:
    dot.draw()
    win.flip()
```

I also wrote another version of this stimulus using ElementArrayStim, with a speed of 1 deg/sec. Visually this speed is much slower than the one with DotStim, though theoretically they should be the same.

``` python
dot = visual.ElementArrayStim(win=win, fieldSize=(31.6, 19.7), nElements=1, sizes=0.3, sfs=0, elementMask='circle')
dot.xys = [[0, 0]]
clock = core.Clock()
last_t = clock.getTime()
x = -15.8
while x < 15.8:
    t = clock.getTime()
    dt, last_t = t-last_t, t
    x += dt * 1.0
    dot.xys = [[x, 0]]
    dot.draw()
    win.flip()
print clock.getTime()
```

My version of PsychoPy is 1.81.03.

**Comment by thomastweets** [comment]
For me, that happens, too (1.82.00).

As you mentioned, the speed seems to depend on the fieldSize. A speed of 1/refreshRate seem to result in (signal) dots moving across the whole field in 1 second.

I could not find a recent commit in dot.py that would correspond to this changed behaviour. I would rather suspect the new _updateVertices in ContainerMixin (former _calcSizeRendered and _calcPosRendered). However, I did not check that.

**Comment by feilong** [comment]
@thomastweets I didn't check that either. Currently I'm using `ElementArrayStim` instead of `DotStim`. `ElementArrayStim` works pretty well and gives me more control of the stimuli (e.g., setting dot size with degrees).
