### ISSUE TITLE
Builder doesn't honour ImageStim & ShapeStim drawing order

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#795]
As reported by Sebastian Korb here:
 
http://stackoverflow.com/questions/28014093/psychopy-polygon-on-top-of-image/28017411

When drawing both an ImageStim and a ShapeStim in the same routine, the ImageStim will be drawn on top of the ShapeStim regardless of their relative vertical position in the sequence of stimuli in the Builder window. 

Each sort of stimulus maintains the correct drawing order amongst other instances of the same class, but when they interact, the ShapeStim seems to get some sort of priority over the ImageStim and will get drawn first.

Just reporting the bug here at this stage: haven't yet looked for any cause in the source code.

**Comment by peircej** [comment]
Fixed in af1af9a7a85cee9b4ec8ad5e2ff1f03140bd1a36
