### ISSUE TITLE
ISI disappears in Builder when using variable for duration

### ISSUE THREAD

**Issue by kohlman** [psychopy/psychopy#799]
I wanted to generate a dynamic ISI and therefore used a variable for "duration". Unfortunately, this makes the ISI disappear. Well, also for other objects the visualization of the timing disappears when you do this, but for the other objects, you at least still have the icon to access the object. For the ISI, I wasn't able to access the ISI object at all after that. The object is still there though. I can change the duration variable in my code section and it has an effect, but, for now, I am just not able to reopen the component. As a workaround, you can set the "expected duration". That helps. But it might be a good idea that at least an icon of the ISI sticks around so that one can use the Builder still.

Thanks and best,

Axel

**Comment by jeremygray** [comment]
I agree that at least some sort of icon should be accessible in this case, perhaps on the left like the other components?
