### ISSUE TITLE
Broken links for help buttons

### ISSUE THREAD

**Issue by kohlman** [psychopy/psychopy#800]
My PsychoPy version is 1.81.03, so it still seems to be a current problem. I reported a similar error for the polygon menu before. I found some more broken links for the help button in the component windows. If it is correct that both Image and Grating should now point to the patch page, i would be happy to clean up the help a little bit.

Image component:
http://www.psychopy.org/builder/components/image.html should be http://www.psychopy.org/builder/components/patch.html

Grating component:
http://www.psychopy.org/builder/components/grating.html I guess should also be patch (see above) http://www.psychopy.org/builder/components/patch.html

Cedrus Button Box:
http://www.psychopy.org/builder/components/cedrusButtonBox.html
There is no page yet or should it just point to http://www.psychopy.org/builder/components/ioLabs.html ??

Parallel Out:
http://www.psychopy.org/builder/components/parallelout.html
There doesn't seem to be a page yet.

I checked all the current components for now, so these should be the only ones missing.

**Comment by peircej** [comment]
Hi, thanks for this. I'll get them added as needed. :-)

On 21/01/15 15:20, kohlman wrote:
>
> My PsychoPy version is 1.81.03, so it still seems to be a current 
> problem. I reported a similar error for the polygon menu before. I 
> found some more broken links for the help button in the component 
> windows. If it is correct that both Image and Grating should now point 
> to the patch page, i would be happy to clean up the help a little bit.
>
> Image component:
> http://www.psychopy.org/builder/components/image.html should be 
> http://www.psychopy.org/builder/components/patch.html
>
> Grating component:
> http://www.psychopy.org/builder/components/grating.html I guess should 
> also be patch (see above) 
> http://www.psychopy.org/builder/components/patch.html
>
> Cedrus Button Box:
> http://www.psychopy.org/builder/components/cedrusButtonBox.html
> There is no page yet or should it just point to 
> http://www.psychopy.org/builder/components/ioLabs.html ??
>
> Parallel Out:
> http://www.psychopy.org/builder/components/parallelout.html
> There doesn't seem to be a page yet.
>
> I checked all the current components for now, so these should be the 
> only ones missing.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/800>.
>

-- 
Jon Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
