### ISSUE TITLE
selection in Builder/Experiment Info

### ISSUE THREAD

**Issue by st-wolff** [psychopy/psychopy#812]
I cant create a selection box in the "Experiment Info" of the Buider interface:
language   ['de','en'] 
appears as string "['de','en']", not as selection.

**Comment by hoechenberger** [comment]
Apparently everything entered in the dialog is currently being converted to a string. Probably not the best idea in some cases...

**Comment by peircej** [comment]
At the point of entry it is (necessarily) unicode object. Possibly we can require users to specify the type that they mean it to have and convert it back to that at the point of compiling the script. Or possibly we allow a dollar sign so the user can convert it to code (not sure why that isn't already the case).

**Comment by hoechenberger** [comment]
Sounds good, shall we open a new issue for this feature suggestion?

**Comment by peircej** [comment]
I think it's OK here
