### ISSUE TITLE
High `lineWidth` values are ignored/ capped

### ISSUE THREAD

**Issue by smathot** [psychopy/psychopy#818]
Hi,

I spotted an issue with the `lineWidth` keyword to `ShapeStim`. If I run this:

``` .python
from psychopy import visual
s = visual.ShapeStim(win, lineWidth=128, vertices=[(-100,0), (100, 0)])
s.draw()
l = visual.Line(win, lineWidth=128, start=(-100, 100), end=(100,100))
l.draw()
win.flip()
```

... I expect to see two really thick lines. Instead I see:

<a target='_blank' style='border:none;' href='http://img.cogsci.nl/?q=54c9fc2f94e8d'><img src='http://img.cogsci.nl/uploads/54c9fc2f94e8d.jpg' /></a>

This particular snapshot is taken with OpenSesame 2.9.2 using PsychoPy 1.81.02 on Kubuntu 14.04.1. But I've received reports of the same issue on other systems as well.

Cheers,
Sebastiaan

Version info:

```
OpenSesame 2.9.2
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1]
OpenCV is available (version is unknown)
OpenCV2 2.4.9
QProgedit 2.1.0
Expyriment 0.7.0b~opensesame2 (Revision ; Python 2.7.8)
NumPy 1.8.2
PIL is available (version is unknown)
PsychoPy 1.81.02
PyAudio 0.2.8
PyGame 1.9.1release
PyGaze 0.5.0~opensesame3
Pyglet 1.2alpha1
PyOpenGL 3.0.2
PyQt 4.11.2
PySerial 2.6
python-bidi 0.3.4
python-markdown 2.5.1
SciPy 0.14.0
```

**Comment by peircej** [comment]
I don't think this is to do with psychopy per se. We simply call the OpenGL function GL.glLineWidth(lineWidth) and then GL.glDrawArrays(GL.GL_LINE_LOOP, 0, nVerts).
It's up to the GL renderer how to interpret that.

I guess we could impose our own cap on the linewidth (127?) and provide a warning that it can't be set above that cap and suggest the user uses a rectangle instead of a line to draw such wide things?

**Comment by smathot** [comment]
Yes, I guess it makes sense to throw a warning, or perhaps even raise an `Exception`. In the OpenGL docs it says:

> Not all widths can be supported when line antialiasing is enabled. If an unsupported width is requested, the nearest supported width is used. Only width 1 is guaranteed to be supported; others depend on the implementation. Likewise, there is a range for aliased line widths as well. To query the range of supported widths and the size difference between supported widths within the range, call glGet with arguments GL_ALIASED_LINE_WIDTH_RANGE, GL_SMOOTH_LINE_WIDTH_RANGE, and GL_SMOOTH_LINE_WIDTH_GRANULARITY.

From: https://www.opengl.org/sdk/docs/man/html/glLineWidth.xhtml
