### ISSUE TITLE
Docs: Put current page first in HTML title for better usability?

### ISSUE THREAD

**Issue by onesandzeroes** [psychopy/psychopy#824]
Having spent a fair bit of time combing through the online API docs over the last few weeks,
I've noticed it's difficult to return to a docs page you have open once you have a few tabs
going. This is because the project name and version occurs first in the HTML title, so they
become the only things visible in the tab bar, e.g.

![tab_titles](https://cloud.githubusercontent.com/assets/1460294/5994432/e580e188-aac6-11e4-9c17-5b1c0febc92e.png)

I'm not a usability expert by any means but I feel it would be more useful to put the current
page first in the html title- the official Python docs do this, for example. Would allow easier swapping between tabs when you're keeping multiple different pages open and going back and forward between them.

Looks like it would
just require a slight edit to the Sphinx template in `layout.html`, basically swapping the order
of the tags in:

```
<title>{{ titlesuffix }}{{ title|striptags }}</title>
```

I'm happy to do the PR myself, but any feedback would be welcome before I get started.

**Comment by jeremygray** [comment]
sounds good to me
