### ISSUE TITLE
python seg faults when remove info field from exp settings dialog 

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#827]
when I have the exp settings open, python crashes when clicking '-' to remove a field

**Comment by jeremygray** [comment]
The source of the crash is in psychopy/app/dialog.py, in class ListWidget(GlobSizer), method onRemoveElement(), line: `self.DeleteRow(row)`. If I comment that out, no crash.

To play around, I copied code from here https://github.com/sloria/psychopy-project-template/blob/master/psychopy/psychopy/app/dialogs.py
and added code for the method DeleteRow into app/dialog.py  In step 4, if I replace `obj.Destroy()` with `del obj` then things seem to work. No crash. I have not checked for memory leaks, etc.

**Comment by hoechenberger** [comment]
Cannot reproduce with latest release, closing.
