### ISSUE TITLE
Dynamic TextStim disappear after so many setText()'s

### ISSUE THREAD

**Issue by jasonhays** [psychopy/psychopy#829]
Greetings PsychoPy devs,

When I have TextStim components that update every frame or every repeat, the contents disappear after some number of setText()'s.  I can make the text disappear sooner by calling setText() in a loop within a frame or by having more than one TextStim setting its text per frame.

Once the problem starts, every text box that has non constant text disappears after it is set again: meaning, text that is set with each repeat disappears on repeat while text set per frame disappears the next frame.

It is as though they disappear after a specific amount of setText()'s.  At first, there are no errors, but if you wait long enough, and then change routines (the next routine, in my case, loaded an image), there will be pyglet errors.

In summary, text that updates can disappear after letting some number of frames pass (this seemed to vary between computers, but it's consistent on a single computer).  On an experiment that's around 30 minutes, the text consistently disappears in a TextStim that is showing a word that the participant is typing because of the number of setText()'s.

I made a very simple experiment with just a TextStim that shows a frame count, and it eventually disappeared at around 7760 frames on one computer.  On this one, I think it was more like 5600, but I made so many changes to the mini experiment to investigate yesterday, I lost track.

I'd greatly appreciate a fix, and I hope I gave you enough information to recreate the problem I'm having.  I think PsychoPy is really awesome, so I really want to help resolve this.

Here's my sysinfo output, but please let me know if you need any more information:
##### Running: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.81.00-py2.7.egg\psychopy\demos\coder\sysInfo.py #####
Paths to files on the system:
    userPrefsFile: C:\Users\Researcher\AppData\Roaming\psychopy2\userPrefs.cfg
    appDataFile: C:\Users\Researcher\AppData\Roaming\psychopy2\appData.cfg
    demos: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.81.00-py2.7.egg\psychopy\demos
    appFile: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.81.00-py2.7.egg\psychopy\app\PsychoPy.py

System info:
Windows-7-6.1.7601-SP1

Python info
C:\Program Files (x86)\PsychoPy2\python.exe
2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]
numpy 1.9.0
scipy 0.14.0
matplotlib 1.4.0
pyglet 1.2alpha1
pyo version 0.6.6 (uses single precision)
pyo 0.6.6

PsychoPy 1.81.03
have shaders: True

OpenGL info:
vendor: Intel
rendering engine: Intel(R) HD Graphics 4600
OpenGL version: 4.0.0 - Build 9.18.10.3131
(Selected) Extensions:
	True GL_ARB_multitexture
	True GL_EXT_framebuffer_object
	True GL_ARB_fragment_program
	True GL_ARB_shader_objects
	True GL_ARB_vertex_shader
	True GL_ARB_texture_non_power_of_two
	True GL_ARB_texture_float
	False GL_STEREO
	max vertices in vertex array: 1048576
0.5116 	WARNING 	Movie2 stim could not be imported and won't be available
1.0752 	WARNING 	Monitor specification not found. Creating a temporary one...

Thanks,
Jason

**Comment by jeremygray** [comment]
I was still going and quit at 20000 (visible, no errors) with this code:

    from psychopy import visual
    win = visual.Window()
    t = visual.TextStim(win)
    i = 0
    while True:
      t.setText(str(i))
      t.draw()
      win.flip()
      i += 1
      print i

I have 1.82.01+ (latest upstream master), on Mac 10.9.5, with 64 bit python, pyglet1.2alpha. 

Suggestions:
- Try 1.82.00 and update to .01, if you can
- Keep track of how many setText()'s you've done, and create a new TextStim instance if you are at some number (2000? 5000? 1000?).

**Comment by jasonhays** [comment]
Thank you for the fast feedback.  I will look into 1.82, but making a new TextStim in the current version doesn't resolve the issue.  As I touched on, every TextStim that I use setText() with seems to be affected.  So, hopefully 1.82 will help--I assumed I had the latest version.  I'll get back to you shortly.

**Comment by jasonhays** [comment]
I borrowed my colleague's Mac.  The standalone 1.81.03 install (the version she had) for Mac OSX functions correctly.  I think the Processor was a 64-bit one (Intel Core i5).

Based on that, the disappearing text may be specific to the Windows setup.  Both of the Windows computers I mentioned were 64-bit.

Here is the sysinfo output for the Mac laptop that is working (tested up to 30k frames):

##### Running: /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/demos/coder/sysInfo.py #####
Paths to files on the system:
    userPrefsFile: /Users/amanda_renfro3/.psychopy2/userPrefs.cfg
    appDataFile: /Users/amanda_renfro3/.psychopy2/appData.cfg
    demos: /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/demos
    appFile: /Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/PsychoPy.py

System info:
Darwin-14.1.0-x86_64-i386-32bit
OS X 10.10.2 running on x86_64

Python info
/Applications/PsychoPy2.app/Contents/MacOS/python
2.7.3 (v2.7.3:70274d53c1dd, Apr  9 2012, 20:32:06) 
[GCC 4.0.1 (Apple Inc. build 5493)]
numpy 1.8.0
scipy 0.12.0
matplotlib 1.3.0
pyglet 1.1.4
pyo 0.6.6

PsychoPy 1.81.03
have shaders: True

OpenGL info:
vendor: Intel Inc.
rendering engine: Intel HD Graphics 4000 OpenGL Engine
OpenGL version: 2.1 INTEL-10.2.46
(Selected) Extensions:
	True GL_ARB_multitexture
	True GL_EXT_framebuffer_object
	True GL_ARB_fragment_program
	True GL_ARB_shader_objects
	True GL_ARB_vertex_shader
	True GL_ARB_texture_non_power_of_two
	True GL_ARB_texture_float
	False GL_STEREO
	max vertices in vertex array: 1048575
0.5063 	WARNING 	Movie2 stim could not be imported and won't be available
0.5404 	WARNING 	TextBox stim could not be imported and won't be available.
0.5404 	WARNING 	TextBox Font Manager Found No Fonts.
0.8789 	WARNING 	Monitor specification not found. Creating a temporary one...

I hope that helps,
Jason

**Comment by jeremygray** [comment]
Its possible that the video card (Intel) is the key factor, rather than the
operating system.

**Comment by jasonhays** [comment]
While I'm not familiar with a lot of the hardware details, it would be weird if the Mac's Intel 4000 out-performed the Intel 4600 on the Windows computers.  To test the idea, I'll check some of the labs on campus for a Windows computer with a different video card and get back to you.  However, I'm not sure if I'll be able to find one with an Intel 4000, which would be ideal.

**Comment by jasonhays** [comment]
Okay, on a 64-bit Windows computer with an Intel 3000 video card, it worked.

Do you have any suggestions to fix the text problems on the affected computers given that it is likely something about the Intel 4600 or the OpenGL version?

Thanks,
Jason

Computer 5:
############ Running: C:\Users\Amanda\Documents\PsychoPyBugCheck.py ############
0.9077 	WARNING 	Movie2 stim could not be imported and won't be available
1.4947 	WARNING 	Monitor specification not found. Creating a temporary one...

Problem compiling: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\PsychoPy2\\lib\\site-packages\\psychopy-1.82.00-py2.7.egg\\psychopy\\demos\\coder\\sysInfo.pyc'
##### Running: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.82.00-py2.7.egg\psychopy\demos\coder\sysInfo.py #####
Paths to files on the system:
    userPrefsFile: C:\Users\Amanda\AppData\Roaming\psychopy2\userPrefs.cfg
    appDataFile: C:\Users\Amanda\AppData\Roaming\psychopy2\appData.cfg
    demos: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.82.00-py2.7.egg\psychopy\demos
    appFile: C:\Program Files (x86)\PsychoPy2\lib\site-packages\psychopy-1.82.00-py2.7.egg\psychopy\app\PsychoPy.py

System info:
Windows-7-6.1.7601-SP1

Python info
C:\Program Files (x86)\PsychoPy2\pythonw.exe
2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]
numpy 1.9.0
scipy 0.14.0
matplotlib 1.4.0
pyglet 1.2alpha1
pyo version 0.6.6 (uses single precision)
pyo 0.6.6

PsychoPy 1.82.00
have shaders: True

OpenGL info:
vendor: Intel
rendering engine: Intel(R) HD Graphics Family
OpenGL version: 3.1.0 - Build 8.15.10.2430
(Selected) Extensions:
	True GL_ARB_multitexture
	True GL_EXT_framebuffer_object
	True GL_ARB_fragment_program
	True GL_ARB_shader_objects
	True GL_ARB_vertex_shader
	True GL_ARB_texture_non_power_of_two
	True GL_ARB_texture_float
	False GL_STEREO
	max vertices in vertex array: 1200
0.8382 	WARNING 	Movie2 stim could not be imported and won't be available
2.3597 	WARNING 	Monitor specification not found. Creating a temporary one...

**Comment by jeremygray** [comment]
I don't have any good ideas how to work around the problem on the computers where it is an issue. Depending on your budget and timetable, you might try upgrading one of the graphics cards and seeing if it makes a difference. I am not an expert on graphics cards, and its possible that something else is responsible for the behavior you are seeing. So upgrading would be something you could try. If you do get a new card, try to get one that is returnable :-) Also, do try updating the drivers before buying a new card. Don't rely on the Microsoft drivers update. Go to the website of the company (Intel) and download drivers from there if at all possible.

**Comment by jasonhays** [comment]
Awesome, updating the drivers did the trick.  Had me worried for a minute. :)

I just updated to the drivers that Intel posted on October 23, 2014.

Thanks a lot,
Jason
