### ISSUE TITLE
Display is not updated after routine resize in Builder

### ISSUE THREAD

**Issue by kohlman** [psychopy/psychopy#841]
The issue might be specific to Mac OS 10.8.5. and/or PsychoPy 1.81.03. By coincidence, I tried the resize option in the "View" menu. Flow resize works fine. But if I use "Routine Larger" or "Routine Smaller", the Routine window goes white (with a little box in the corner, it seems). The changes do take effect when I resize the windows then. So I guess it's an update/redraw problem.

Cheers,

Axel

**Comment by peircej** [comment]
The little white box usually occurs when wx has tried to render a window 
but found a problem. Probably an error message is being generated that 
you aren't getting to see.  Could you;

 1. open coder view
 2. return to the Builder
 3. do your resize
 4. go and see if an error appeared in the output panel (bottom of the
    coder view)?

cheers,
JOn

On 20/02/2015 08:47, Axel Kohler wrote:
>
> The issue might be specific to Mac OS 10.8.5. and/or PsychoPy 1.81.03. 
> By coincidence, I tried the resize option in the "View" menu. Flow 
> resize works fine. But if I use "Routine Larger" or "Routine Smaller", 
> the Routine window goes white (with a little box in the corner, it 
> seems). The changes do take effect when I resize the windows then. So 
> I guess it's an update/redraw problem.
>
> Cheers,
>
> Axel
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/841>.
>


-- 
Jonathan Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by kohlman** [comment]
No, unfortunately no output appears at all. I thought it's just an update/redraw problem because size of the routine **IS** in fact changed after I do the frame resizing. So the change is registered OK, but just not drawn.

Cheers,

Axel

**Comment by hoechenberger** [comment]
@kohlman Does this problem still exist for you with the latest release of PsychoPy?

**Comment by hoechenberger** [comment]
Closing for now due to lack of response. Feel free to re-open at any time if the problem persists!
