### ISSUE TITLE
pandas 0.12 not working properly in StandAlone; upgrade to 0.15?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#842]
As reported on the users list (Feb 21 2015), some pandas.DataFrame operations do not work as expected in the StandAlone, but do elsewhere. I don't know what the problem is, but if upgrading pandas might fix it that seems worth trying, and worth doing anyway since there have been various bug-fixes and updates in pandas. Perhaps we could package pandas 0.15? (or 0.16 if that becomes stable?)

**Comment by peircej** [comment]
I'll try and update forthe next release
Jon

On 22/02/2015 14:39, Jeremy R. Gray wrote:
>
> As reported on the users list (Feb 21 2015), some pandas.DataFrame 
> operations do not work as expected in the StandAlone, but do 
> elsewhere. I don't know what the problem is, but if upgrading pandas 
> might fix it that seems worth trying, and worth doing anyway since 
> there have been various bug-fixes and updates in pandas. Perhaps we 
> could package pandas 0.15? (or 0.16 if that becomes stable?)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/842>.
>

-- 
Jonathan Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by mmagnuski** [comment]
I've had issues with standalone where changing dataframe values in the following way:
```python
df.loc[1:5, 'RT'] = RT_array
```
would result in error saying that slice does not support len.
I am sure this works well on pandas 0.15.

**Comment by hoechenberger** [comment]
The latest standalone RC contains pandas 0.16.2, and the following example is working without any problems, therefore I think this issue can be closed.

```python
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame({'Trial:': range(10), 'RT': np.random.rand(10)})
>>> df.head(n=10)
         RT  Trial:
0  0.192752       0
1  0.027256       1
2  0.523922       2
3  0.560451       3
4  0.211519       4
5  0.476894       5
6  0.114966       6
7  0.690833       7
8  0.171140       8
9  0.385712       9
>>> df.loc[1:5, 'RT'] = 1 + np.random.rand(5)
>>> df.head(n=10)
         RT  Trial:
0  0.192752       0
1  1.469210       1
2  1.514877       2
3  1.193049       3
4  1.298629       4
5  1.731061       5
6  0.114966       6
7  0.690833       7
8  0.171140       8
9  0.385712       9
>>>
```

**Comment by mmagnuski** [comment]
:+1:
