### ISSUE TITLE
unicode in participant name = crash on save .psydat

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#846]
as called in `__del__` of an ExperimentHandler.

changing from cPickle to pickle (for doing `pickle.dump(self, f)`) avoids the unicode error, but I get

    Exception RuntimeError: RuntimeError('sys.meta_path must be a list of import hooks',) in <bound method ExperimentHandler.__del__ of <psychopy.data.ExperimentHandler object at 0x113c11cd0>> ignored

**Comment by hoechenberger** [comment]
The issue with cPickle is probably fixed in 7c19a85c886c85a4f362acf15928b78dc7b82957.

**Comment by jeremygray** [comment]
fixed in 7c19a85
