### ISSUE TITLE
Movie2 stim warning confusing for users

### ISSUE THREAD

**Issue by kohlman** [psychopy/psychopy#851]
I had the experience myself and now see it with my students. I don't know if this is only Mac-specific with a standard install, but I guess on any system missing the *cv2* package, the following warning will be logged and appear in the output at the end of the experiment: **WARNING 	Movie2 stim could not be imported and won't be available**

I think there shouldn't be a warning coming up for standard installations. And the warning is also not informative because it's just the cv2 package missing (which is standard for some (all?) systems). Would it be possible to handle this differently? I could make the changes, just wanted to have some feedback from the core team.

Info: The warning is generated in \__init__.py of the *visual* module. The cause is the failing of `import cv2` in *movie2.py*.

**Comment by peircej** [comment]
Actually, for the more recent full installs of Standalone PsychoPy cv2 
is included.
The reason this message still appears is one of:
     - the standalone has been updated to new version but not 
reinstalled (so the dependencies are from before it was provided)
     - the vlc application has not been installed
     - the vlc application is the wrong architecture. We're still using 
32bit python in the standalone and so the vlc app needs to be the 32bit 
version.

So the annoying thing right now is that the error message does tell you 
*why* it failed, although we can distinguish the 3 reasons in the error 
messages we receive (I've written code to do this correctly but I guess 
it's on my laptop and not committed yet. I wrote it on a train 10 days 
ago). Let me get home to my laptop and make sure it's still there before 
changing anything for now.

Further improvements:
     - distribute the vlc dynamic lib ourselves rather than requiring 
the user to install it (would also mean distributing the c code to 
comply with the license but should be OK)
     - or switch to releasing standalone in 64bit options. This would be 
great (anyway) and I think only hinges on me getting 64bit sound working

On 27/02/2015 09:14, Axel Kohler wrote:
>
> I had the experience myself and now see it with my students. I don't 
> know if this is only Mac-specific with a standard install, but I guess 
> on any system missing the /cv2/ package, the following warning will be 
> logged and appear in the output at the end of the experiment: *WARNING 
> Movie2 stim could not be imported and won't be available*
>
> I think there shouldn't be a warning coming up for standard 
> installations. And the warning is also not informative because it's 
> just the cv2 package missing (which is standard for some (all?) 
> systems). Would it be possible to handle this differently? I could 
> make the changes, just wanted to have some feedback from the core team.
>
> Info: The warning is generated in __init__.py of the /visual/ module. 
> The cause is the failing of |import cv2| in /movie2.py/.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/851>.
>

-- 
Jonathan Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by kohlman** [comment]
Alright, Jon. So you basically have a solution already. Great!

**Comment by peircej** [comment]
"solution" would probably be a generous term, but we have some degree of 
improvement on the way ;-)

On 27/02/2015 10:53, Axel Kohler wrote:
>
> Alright, Jon. So you basically have a solution already. Great!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/851#issuecomment-76375983>.
>

-- 
Jonathan Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by gesasophia** [comment]
Hello, I just downloaded psychopy on my mac OX X 10.10.2, and I got this error message after running some simple code from one of the tutorials. What should I do now?
