### ISSUE TITLE
useVersion not ok with newer versions?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#852]
I set it up this way, interactively, the first time:

    >>> from psychopy.tools.versionchooser import useVersion
    >>> useVersion('1.80.04')
    Cloning Psychopy Library from Github - this may take a while
    git clone -o github https://github.com/psychopy/versions versions
    Cloning into 'versions'...
    remote: Counting objects: 1936, done.
    remote: Total 1936 (delta 0), reused 0 (delta 0), pack-reused 1936
    Receiving objects: 100% (1936/1936), 3.02 MiB | 792.00 KiB/s, done.
    Resolving deltas: 100% (1166/1166), done.
    Checking connectivity... done.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 52, in useVersion
        requestedPath = _setupRequested(requestedVersion)
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 80, in _setupRequested
        _cloneRequested(requestedVersion)
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 128, in _cloneRequested
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, cwd=VERSIONSDIR)
      File "/Users/jgray/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'checkout', '1.80.04']' returned non-zero exit status 1

Seems odd to get an error here.

But I did seem to be able to switch, but only to 1.77.x through 1.80.x versions:

    >>> useVersion('1.77.01')
    Now using PsychoPy library version:  1.77.01
    True
    >>> useVersion('1.80.03')
    Now using PsychoPy library version:  1.80.03
    True

    >>> useVersion('1.81.01')
    fatal: Not a git repository (or any of the parent directories): .git
    Now using PsychoPy library version:  1.80.03
    True
    >>> useVersion('1.82.01')
    fatal: Not a git repository (or any of the parent directories): .git
    Now using PsychoPy library version:  1.80.03
    True
   
It seems odd that it returns true even if unable to load the requested version.

**Comment by jeremygray** [comment]
The newer tags (1.81.00+) are missing from my version repo:

% cd ~/.psychopy2/versions
% git tag
1.76.00
1.77.00
1.77.01
1.77.02
1.78.00
1.78.01
1.79.00
1.80.00
1.80.01
1.80.02
1.80.03
1.80.05
1.80.06

**Comment by jeremygray** [comment]
I'd like to see useVersion() return the current version, rather than True. 

ps. @kastman: useVersion is so cool, I love it!

**Comment by peircej** [comment]
Yes, it looks like the commits to the repository worked but not the tagging.
Will fix that.

On 27/02/2015 17:08, Jeremy R. Gray wrote:
>
> The newer tags (1.81.00+) are missing from my version repo:
>
> % cd ~/.psychopy2/versions
> % git tag
> 1.76.00
> 1.77.00
> 1.77.01
> 1.77.02
> 1.78.00
> 1.78.01
> 1.79.00
> 1.80.00
> 1.80.01
> 1.80.02
> 1.80.03
> 1.80.05
> 1.80.06
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/852#issuecomment-76430573>.
>

-- 
Jonathan Peirce
http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by kastman** [comment]
Glad it's [almost] working! So refreshing when that happens.

That's an annoying git gotcha - `git push github --tags` should work: http://git-scm.com/book/en/v2/Git-Basics-Tagging#Sharing-Tags

What's the thinking behind returning the version? The caller should know what they requested, and it's still deterministic;  '~>1.80' isn't set up yet. 

Also, if you hadn't done it in the same initialization step you should have gotten a more informative error, but we should catch that edge case too.  See https://github.com/psychopy/psychopy/blob/df68d434973817f92e5df78786da313b35322ae8/psychopy/tools/versionchooser.py#L110 vs. L127

Also, maybe we should move some of those prints ('Now using version...') back to psychopy.logger?

**Comment by jeremygray** [comment]
I am thinking that returning the version is useful when the version you request could not be achieved, for whatever reason. It was still returning True, so the calling end had no easy access to the current status. The '~>1.80' will be another usage. I was also thinking of if you request "1.80" it could find the highest within the 1.80.xx series, and let you know what it found. "git tag --list '1.80*'"

Yeah, I think moving prints into logging sounds good.

**Comment by kastman** [comment]
At the very least, success is now returned [either as True or as None ](https://github.com/psychopy/psychopy/blob/df68d434973817f92e5df78786da313b35322ae8/psychopy/tools/versionchooser.py#L47), which is not so good!

I think if the requested version can't be found, we should hard-stop with an error. I think I meant to do this, but am [accidentally letting some git errors pass](https://github.com/psychopy/psychopy/blob/df68d434973817f92e5df78786da313b35322ae8/psychopy/tools/versionchooser.py#L81) by not including an `else: raise` when trying to checkout or clone fails for a reason besides not having a tag.

Does that jive with what you were thinking?

**Comment by jeremygray** [comment]
Yes, I like a hard-stop if the requested version can't be found. I just think if success was returned as the achieved version number, that would be more informative in a wider range of situations, and still usable as a boolean flag. `ver = useVersion('1.81.02')` Its like one Starbucks barrista saying "Dopio" to which the other replies "Dopio" instead of something less specific like "yes" or "I hear you".

Which makes me think of another thing: Is there a way to update the local repo (in .psychopy2/versions/)? I looked in the .git/config and did not see any likely looking definitions except for 'remote'. But 'git pull remote master' failed.

**Comment by peircej** [comment]
Haha, yes I know how to push the tags, but this is done with an automated script so I need to see whether the tagging is even working. Will have to wait until monday though.

**Comment by peircej** [comment]
I agree - it would be nice to return the version that was used if successful. Potentially we could also have a command getVersions() so you could see what the options are.

Jeremy I think the git command you want it `git fetch <name of remote>` rather than `git pull`. In this case the remote has been called github when we created the local clone so you want `git fetch github` from within .psychopy2./versions/

**Comment by kastman** [comment]
Jon, no offense intended. I had to look it up for myself and thought I might save you the time! :) +1 to getVersions()

Didn't get to it today, but I should be able to out a better try: except and returning a version within the week... Ping me again if you don't hear anything!

**Comment by jeremygray** [comment]
A function to update the local versions repo (per Jon: git fetch github from
within .psychopy2/versions/) would be handy too. That way, if the requested
version is larger than the largest current one, the code could
automatically try to download newer versions, and try again.

**Comment by kastman** [comment]
Yep - fetch is in there already. If the versions repo were tagged correctly it would have done this for you!

**Comment by peircej** [comment]
Looks like my automated script was creating the necessary tags but not pushing them to the github repos (actually it might be that I decided deliberately not to push them within the script but then forgot to do that manually!)
