### ISSUE TITLE
gamma.createLinearRamp() fails on Mac 10.10.x

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#862]
The logic for deciding the `rampType` never sets a value when `osxVer` == '10.10.2' (because '10.10' < '10.5'). So it ends up as `None` which causes a crash. Setting `rampType` to any one of the 4 options works for me -- all test_gamma tests pass, no matter what ramp is used. So I'm not sure what the best fix is.

My tech specs:
rendering engine: NVIDIA GeForce GT 650M OpenGL Engine
OpenGL version: 2.1 NVIDIA-10.2.1 310.41.15f01

**Comment by peircej** [comment]
ah, we need to use distutils.version.LooseVersion for this I think
I'll fix it in a second...

**Comment by peircej** [comment]
I think this is fixed in acac60458f1fc5f2299e66d197394e9a014a2e28 using distutils version comparison

**Comment by jeremygray** [comment]
I think using LooseVersion makes distutils a new dependency. To avoid that
we could roll our own check using platform.mac_ver and expanding .9. to
.09. using zfill.

--Jeremy

**Comment by peircej** [comment]
distutils is part of the standard library python though so everyone 
should have it, no?

On 05/03/2015 15:11, Jeremy R. Gray wrote:
> I think using LooseVersion makes distutils a new dependency. To avoid that
> we could roll our own check using platform.mac_ver and expanding .9. to
> .09. using zfill.
>
> --Jeremy
>
> On Thu, Mar 5, 2015 at 10:06 AM, Jon Peirce <notifications@github.com>
> wrote:
>
> > I think this is fixed in acac604
> > 
> <https://github.com/psychopy/psychopy/commit/acac60458f1fc5f2299e66d197394e9a014a2e28>
> > using distutils version comparison
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/psychopy/psychopy/issues/862#issuecomment-77379520>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/862#issuecomment-77380547>.
>

-- 
Jonathan Peirce
Nottingham Visual Neuroscience

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by jeremygray** [comment]
> distutils is part of the standard library python though so everyone
> should have it, no?


I didn't have distutils with my conda installation (64-bit python 2.7.9), I
had to install separately. And after installing, I can't import LooseVersion

>>> distutils.__version__
'2.7.9'
>>> from distutils import LooseVersion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name LooseVersion

**Comment by jeremygray** [comment]
Ah, for me its from distutils.version import LooseVersion

Rolling our own is trivial for the expected ranges of Mac versions. I like
this way (comparing tuples of ints) more than comparing strings that have
been .zfill()ed:

>>> def LooseVersion(ver_string):
...   return map(int, ver_string.split('.'))
...
>>> LooseVersion('10.5.3') < LooseVersion('10.10.3')
True



--Jeremy

**Comment by peircej** [comment]
OK, then, rolling our own seems the way!

One suggested idea is convert to tuple of integers:

|def  versiontuple(v):
     return  tuple(map(int,  (v.split("."))))

>>>  versiontuple("2.3.1")  >  versiontuple("10.1.1")
False|

from 
http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment]
On 05/03/2015 17:36, Jeremy R. Gray wrote:
> Ah, for me its from distutils.version import LooseVersion
My bad. You're right on that too. ;-)
But the convert-to-tuple thing seems neat. I don't honestly mind!




This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by jeremygray** [comment]
Yeah, the tuple comparison is nifty.

--Jeremy
