### ISSUE TITLE
RatingScale Marker turns grey if the scale times out. Does not refresh.

### ISSUE THREAD

**Issue by vaidarim** [psychopy/psychopy#868]
In psychopy 1.81.03 RatingScale Marker turns gray if the scale times out without submitting and does not refresh to specified color on subsequent trials. 
Any suggestions how to fix that?

**Comment by vaidarim** [comment]
for my own purposes I commented out lines 956-962 to prevent it from turning DarkGray. Still, it's a nice feature, would be great if could be fixed in the future. 
Thanks!

**Comment by jeremygray** [comment]
Thanks for reporting this.

**Comment by vaidarim** [comment]
I tried ratingscale.reset() and it does not seem work.

**Comment by jeremygray** [comment]
@vaidarim are you saying that it is still gray when you are using the NEW code?

**Comment by vaidarim** [comment]
my mistake, works with new code. Thanks!
