### ISSUE TITLE
mic.stop() and block=False do not allow premature escape from running experiment

### ISSUE THREAD

**Issue by gciccarelli3** [psychopy/psychopy#876]
Hi,

First, it seems I have to specify a duration for mic.record, rather than allowing indefinite record time.  I'm in coder view.  

The problem is that when I want to prematurely quit an experiment, mic.stop() works (the wav file really is closed early), and the program stops processing, but the program is frozen until the time for mic.record has completed.  Frozen meaning I'm not bounced back into coder view to restart the experiment or make changes.  Additionally, no commands that I've tried (esc, q, cmd q, ctrl q) allow breaking out of this frozen screen.  I have to hard power off the computer and restart.

I'm modifying someone else's code, and my psychopy knowledge is too immature to post a minimum working example, but this is the gist of it:

Dummy example.
mic = micropohone.AdvAudioCapture(name='mic', stereo = False)
mic.record(sec=10, block = False, filename = 'mySubj.wav')

core.wait(5)

--- Escape interrupt -----
mic.stop()
core.quit()
------  Rest of experiment

mac osx 10.8.2
psychopy version 1.81.03

Thanks,
Greg

**Comment by jeremygray** [comment]
Thanks for reporting this. Something is happening with pyo that is different than how it used to be, and I'm not sure what yet. For now, I suggest trying this code in your escape, after `mic.stop()` and before `core.quit()`:

    sound.pyoSndServer.stop()
    core.wait(0.5)
    sound.pyoSndServer.shutdown()
    core.wait(0.5)

This is supposed to happen automatically when pyo shuts itself down, but for some reason it does not appear to be doing so.

**Comment by gr21783** [comment]
Thanks for the quick reply to both my questions.  Unfortunately, this
solution does not appear to provide any faster shutdown of the sound
module.

Best,
Greg

**Comment by jeremygray** [comment]
If you can edit your copy of microphone.py, you could try this:

near line 88, edit the lines after this one

            pyo.Clean_objects(sec, self.recorder).start()  # handles recording offset

to be like this (everythin until the end of the function):

            timer = threading.Timer(sec, self._stop)
            timer.daemon = True  # allows python exit despite the thread
            timer.start()  # set running flag False

**Comment by gr21783** [comment]
Unfortunately, that does not seem to have changed the behavior either.

I don't understand how timer.start() relates to the comment  of changing a
running flag to false.  Was that a typo?

**Comment by jeremygray** [comment]
Drat. 

Yeah, that comment is a bit cryptic. The purpose of the timer thread is to set the running flag to False after a delay (= when the time is up).

**Comment by gr21783** [comment]
Someone suggested I run the microphone as a psychopy subprocess on another
core?  I don't know how to do that, but would it buy us anything?

**Comment by gr21783** [comment]
Also, is there another way to call the microphone inside the psychopy
script but outside of the microphone class structure?

**Comment by jeremygray** [comment]
Running on another core is not trivial to arrange, and I don't know that it would buy us anything.

**Comment by gr21783** [comment]
I added this at the top of the script, after prompting for user id.

The script quits quickly, but doesn't seem to save a wav file.:

from multiprocessing import Process
def record_process():
    microphone.switchOn()
    mic_1 = microphone.AdvAudioCapture(name='awesome', filename=filename +
'_' + '.wav', stereo=False)
    mic_1.record(sec=20, block=False)
    return
proc=Process(target=record_process)
proc.start()
proc.join()

I also get this message:
The process has forked and you cannot use this CoreFoundation functionality
safely. You MUST exec().
Break on
__THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__()
to debug.

Thanks,
Greg

**Comment by jeremygray** [comment]
I have written another implementation of microphone from scratch (in order to implement a voice key). Its not as fully featured yet, nor as integrated, but you are welcome to try it out. Just let me know.

**Comment by gr21783** [comment]
Sure, I might be able to.  Is there a github branch to checkout or
something?  We literally just need it to record and gracefully close and
save.

**Comment by jeremygray** [comment]
I can send you the files directly, there's not a public repo yet. email me at jrgray@gmail.com and we'll discuss further.

**Comment by gr21783** [comment]
Hi,

As a workaround, we've started and stopped the microphone recording for
each stimulus so we have one wave file per stimulus.  Then, if we cancel
the program, the delay is only several seconds (the duration of one
stimulus presentation).

Thanks,
Greg

**Comment by jeremygray** [comment]
>
> As a workaround, we've started and stopped the microphone recording for
> each stimulus so we have one wave file per stimulus. Then, if we cancel
> the program, the delay is only several seconds (the duration of one
> stimulus presentation).


Thats actually the intended usage, maybe this needs to be better
documented. I have not tried doing everything-in-one-long-recording. Is
that something that people prefer? It seems like the files would get
enormous are hard to work with.

**Comment by gr21783** [comment]
"Preferred" is probably a bit strong.  It's what we were doing in order to
have a file with everything in it that provided an unbroken snapshot of all
that occurred.  Yes, short files are easier to work with.

**Comment by kschuler** [comment]
mic.recorder.stop() rather than mic.stop() will end a recording early.

**Comment by TEParsons** [comment]
@mdcutone is this solved now that we have the new mic backend?

**Comment by mdcutone** [comment]
The new microphone class does not have a `block` method. Use timers instead.
