### ISSUE TITLE
Raise ValueError from TrialHandler.saveAsWideText() when there's no data to write

### ISSUE THREAD

**Issue by onesandzeroes** [psychopy/psychopy#882]
Just had a bit of trouble while developing a new experiment: I'm using the new behaviour of `TrialHandler.saveAsWideText()` returning a pandas DataFrame, and using that to write my data files as I find pandas is better about quoting/escaping/all the stuff that's tricky about csv files. Currently when there's no actual data for the `TrialHandler` to write, it returns an int value of -1, as seen [here](https://github.com/psychopy/psychopy/blob/master/psychopy/data.py#L1175).

This doesn't seem particularly pythonic, and it took me a little while to track down when it started happening. I would think the more typical pythonic thing to do would be to raise an exception here, to make it clear that `saveAsWideText()` may not have done what you wanted but still make it easy to ignore with a quick `try`/`except`.

Happy to do the PR myself, just wanted some feedback.

When I get a bit more time I'd like to refactor `saveAsWideText()` so that we just use pandas to do the write instead of doing it manually, so that pandas can deal with all the quoting/escaping issues.

**Comment by m-macaskill** [comment]
Refactoring to use pandas would be great. Long after `saveAsWideText()` was written, we've now started using pandas for reading in .csv files, so it would be sensible to also use it for exporting, to make use of its more sophisticated capabilities.
