### ISSUE TITLE
.addData() with mutable objects needs to use a copy

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#884]
See http://stackoverflow.com/questions/29362421/understanding-psychopys-data-logging/29366793

Could use copy() for everything, but only needed for mutables

    try: hash(value)
    except: value = copy.deepcopy(value)

**Comment by peircej** [comment]
I tested and it is faster to deepcopy() only when needed as you're doing. One thing that shaves a couple of nanoseconds off it to test using:
  if value.__hash__
rather than
  try: hash(value)

I suspect the `try` call is a wrapper around the `if` call.

**Comment by jeremygray** [comment]
Cool. I also tested timing, but did not think of "if value.__hash__". Good
to know!

--Jeremy
