### ISSUE TITLE
Quit disabled after update (on mac, at least)

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#886]
Have to force-quit to restart the app

**Comment by peircej** [comment]
Yes, this is a long-standing thing and not sure how to fix it. I think if
you switch to builder and back them it works again, so maybe that's a core
to what's going on...?

**Comment by peircej** [comment]
I'm closing this - not sure if it was a wx bug or something in our code but autoupdate isn't currently being used anyway
