### ISSUE TITLE
auto-save .csv data file after every loop?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#890]
Some people have had data loss due to abnormal program exit happening prior to the .csv file being saved. (Possibly from a very slow shutdown, leading them to manually terminate the program, leading to data loss.)

Adding this line to the code after a loop has completed would auto-save at a relatively safe place to do so (safe in terms of being a natural transition point, and so if it took a while it would not be dropping frames during a time-critical operation).

    thisExp.saveAsWideText(thisExp.dataFileName+'.csv', delim=',')

This could be expanded to be made aware of whether the user wants .csv or .xlsx output, etc.

It could also be an option in the loop dialog -- autosave True or False, default = True. 

Ideally you could opt to autosave after every trial, but that would be much more efficient if only new (= as yet unsaved) data could be tracked, and that be written out to disk appending it to the existing file.

**Comment by peircej** [comment]
I think the very slow shutdown is caused most commonly by saving excel 
files (occasionally by writing lots of print statements).
Solutions might be:
     - disable excel file outputs for now
     - add a warning to the stop button that data might be lost as a result

On 22/04/2015 16:28, Jeremy R. Gray wrote:
>
> Some people have had data loss due to abnormal program exit happening 
> prior to the .csv file being saved. (Possibly from a very slow 
> shutdown, leading them to manually terminate the program, leading to 
> data loss.)
>
> Adding this line to the code after a loop has completed would 
> auto-save at a relatively safe place to do so (safe in terms of being 
> a natural transition point, and so if it took a while it would not be 
> dropping frames during a time-critical operation).
>
> |thisExp.saveAsWideText(thisExp.dataFileName+'.csv', delim=',')
> |
>
> This could be expanded to be made aware of whether the user wants .csv 
> or .xlsx output, etc.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/890>.
>

-- 
Jon Peirce
http://www.peirce.org.uk
