### ISSUE TITLE
Need logging of monitor characteristics e.g. gammas

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#904]
We often aim to have all information required to reproduce an experiment be available from the log file and source code.  That's why I include the below in my code: 

`
runInfo = psychopy.info.RunTimeInfo(
        win=myWin,    ## a psychopy.visual.Window() instance; None = default temp window used; False = no win, no win.flips()
        refreshTest='grating', ## None, True, or 'grating' (eye-candy to avoid a blank screen)
        verbose=True, ## True means report on everything 
        userProcsDetailed=True  ## if verbose and userProcsDetailed, return (command, process-ID) of the user's processes
        )
logging.info(runInfo)` 
Until now I believed that this, in conjunction with the source code, would save all info needed to reconstruct the experiment. However, it unfortunately does not save the monitor characteristics that may be used by Psychopy to e.g. determine the RGB values for a desired luminance.  The monitor characteristics are in the Monitor Center, but if one moves to a new machine, they are likely to be lost.

So I think we need RunTimeInfo or something similar to store the results of
`getGammaGrid())` and `getLinearizeMethod()`.
For now, I'm just adding them to the log using a logging.info call.

**Comment by hoechenberger** [comment]
Closes via #905.
