### ISSUE TITLE
Builder loop dialog "Conditions" field truncated contents don't represent actual path

### ISSUE THREAD

**Issue by m-macaskill** [psychopy/psychopy#909]
In the Builder loop dialog box's "Conditions" field, if the path to the conditions file is long, then the text representation of the path is truncated, with some of the middle content replaced by an ellipsis. Presumably this is so the actual file name is always visible. The problem with this is that the displayed text content of the field does not match the actual stored full path. This causes a number of problems, such as not being able to debug issues with the file not being able to be found (as the details of the path can no longer be read), and not being able to copy and paste a path from one dialog to another. The text representation of the path should match the actual path, even if that means that the file name is not visible without scrolling through the field.

**Comment by peircej** [comment]
Yes, I once thought this was a good idea, but alas it was not. We should ditch the whole abbreviation thing there
