### ISSUE TITLE
throws exception while trying to get info within ipython notebook

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#911]
Running
```python
from psychopy import info
info.RunTimeInfo()
```
throws exception since lines could be undefined see 
http://www.onerussian.com/tmp/gkrellShoot_06-02-15_112930.png

**Comment by peircej** [comment]
You're not teaching them to run experiments from notebooks I hope! ;-)
I've got no idea what the python threads will be like (you could end up with lots of background processes that aren't getting shut down) and the timing is probably shocking.

**Comment by yarikoptic** [comment]
I am teaching them from notebooks -- moreover, notebooks ran under VirtualBox (so forget about flip blocking etc).  but yes -- I have alerted them that such setup is just for teaching, so you can sleep tight ;)
