### ISSUE TITLE
Cannot see opened code in coder view

### ISSUE THREAD

**Issue by bpkst2** [psychopy/psychopy#915]
Hello, I am using PsychoPy version 1.82.01 on Mac Mavericks (10.9.5).  When I open script in the Coder view, I get a strange sliver that appears in the upper left part of the screen.  The sliver can be moved around on the screen and can be double clicked (see screenshots).  I can even run the code by double-clicking on the sliver.  But I cannot seem to open the code.  Note that this problem occurs for multiple scripts, including the built-in demos. Note also that I have no problems opening up files in the Builder view.  A restart of the computer hasn't helped. Any help would be much appreciated.  

Thank you...

![screen shot 2015-06-08 at 12 16 48 am](https://cloud.githubusercontent.com/assets/11637381/8028126/6911d77c-0d74-11e5-9105-033b01dfd5ed.png)
![screen shot 2015-06-08 at 12 17 01 am](https://cloud.githubusercontent.com/assets/11637381/8028125/6557a18e-0d74-11e5-8051-e5b0ba9ec668.png)

**Comment by peircej** [comment]
I've never seen this and no idea how to get it into this state. My guess is that the saved window size has become something tiny (or negative?). Trty clearing the application data:

http://www.psychopy.org/troubleshooting.html#cleaning-preferences-and-app-data

**Comment by bpkst2** [comment]
I took your advice, closed the app, removed the files in the terminal (rm ~/.psychopy2/appData.cfg, rm ~/.psychopy2/userPrefs.cfg), and now it works perfectly. Thanks!
