### ISSUE TITLE
Font settings in TextStim ignored in pygame window.

### ISSUE THREAD

**Issue by tmalsburg** [psychopy/psychopy#927]
I tried [`textStimuli.py`](https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/stimuli/textStimuli.py) from the demos directory and it worked as expected.  However, when I change the winType to pygame, all font settings are ignored and some default font is used for everything.  I'm using psychopy on Ubuntu 14.04 and installed it following the instructions given [here](http://www.psychopy.org/installation.html).  Irrespective of the winType, I get the following error message on startup:

    Error importing pytables. FontStore will not be supported.

Perhaps not relevant but when I use pygame, I also get a bunch of the following messages when I exit the application:

    0.8328 	WARNING 	Tried to set contrast while useShaders = False but stimulus was not rebuild. Contrast might remain unchanged.

**Comment by peircej** [comment]
pygame is no longer supported and we aren't fixing pygame specific bugs 
any more
sorry, Jon

On 24/06/15 06:41, Titus von der Malsburg wrote:
>
> I tried |textStimuli.py| 
> <https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/stimuli/textStimuli.py> 
> from the demos directory and it worked as expected. However, when I 
> change the winType to pygame, all font settings are ignored and some 
> default font is used for everything. I'm using psychopy on Ubuntu 
> 14.04 and installed it following the instructions given here 
> <http://www.psychopy.org/installation.html>. Irrespective of the 
> winType, I get the following error message on startup:
>
> |Error importing pytables. FontStore will not be supported.
> |
>
> Perhaps not relevant but when I use pygame, I also get a bunch of the 
> following messages when I exit the application:
>
> |0.8328  WARNING     Tried to set contrast while useShaders = False but stimulus was not rebuild. Contrast might remain unchanged.
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/927>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment]
The warning about pytables isn't important by the way - that's to do with another way of presenting text that we've been working on that's very fast but doesn't currently support anything other than monospace fonts

**Comment by tmalsburg** [comment]
> pygame is no longer supported 

This should be reflected in the documentation which actually [recommends](http://www.psychopy.org/api/visual/window.html#psychopy.visual.Window) using pygame when speed is an issue:

> Pygame has fewer bells and whistles, but does seem a little faster in text rendering.

**Comment by peircej** [comment]
sorry that's outdated. I'm sure you'll understand the difficulties of a project this size. I'll fix it

**Comment by tmalsburg** [comment]
No, problem.  I'm not complaining.  Just explaining why I was using pygame.
