### ISSUE TITLE
Cannot retrieve the size of rendered text with pyglet

### ISSUE THREAD

**Issue by tmalsburg** [psychopy/psychopy#928]
I need the size of a rendered text. When using pygame as the backend, I could use the following code which renders a text and then calculates and renders the bounding box of the text:

``` Python
    from psychopy import visual, core

    width = 600
    height = 300
    x = (-width / 2) + 20
    y = 0

    win = visual.Window([width,height], monitor="testMonitor", units="deg", fullscr=False, winType="pyglet")

    msg = visual.TextStim(win, text=u"\u00A1Hola mundo!", pos=(x,y), alignHoriz="left", alignVert="center", font="Comic Sans MS", height=30, units="pix")

    x1 = x
    x2 = x + msg.width
    y1 = y - msg.height/2
    y2 = y + msg.height/2

    print x1,x2,y1,y2

    rec = visual.Rect(win, x2-x1, y2-y1, units="pix", lineColor=(1,0,0), lineWidth=2, pos=((x1+x2)/2, (y1+y2)/2))

    msg.draw()
    rec.draw()
    win.flip()

    core.wait(4)
    win.close()
```

`Text.Stim.width` is not documented but it gives me the correct value.

However, when I use pyglet, both width and height are too large.  See the attached image:

![screenshot_2015-06-24082518](https://cloud.githubusercontent.com/assets/3817450/8334282/ec2cef96-1a4b-11e5-98ba-96f8453efbb2.png)

The documentation `TextStim.size` says that `TextStim._sizeRendered` can be used to retrieve the actual rendered size but when I try this, I get an AttributeError:

```
>>> msg._sizeRendered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TextStim' object has no attribute '_sizeRendered'
```

I would just use pygame but see #927.

**Comment by peircej** [comment]
Yes, pygame rendered text to a single image and then presented it - that's what used to make it fast (once the image was created) and also meant that you could extract the bounding box.

pyglet thinks of your text more like a 'document' allowing line-wrapping and (potentially) formatting (we haven't exposed that interface to psychopy) so the notion of 'width' then is the width of the line at which a line break will occur, not the width of the characters you've used within that. The vertices of each letter must surely be available in there (Text._pygletTextObj) somewhere but I don't know where personally. Will need some digging with dir() and print to find them

**Comment by peircej** [comment]
OK, I've got it. In text.py add the following to TextStim

        
    @property
    def boundingBox(self):
        """(read only) attribute representing the bounding box of the text (w,h). 
        This differs from `width` in that the width represents the width of the
        margins, which might differ from the width of the text within them
        
        NOTE: currently always returns the size in pixels 
        (this will change to return in stimulus units)
        """
        return (self._pygletTextObj._layout.content_width, self._pygletTextObj._layout.content_height)

then you can do:
  w,h = myText.boundingBox
  box = visual.Rect(win, widht=w, height =h, units='pix')

This returns w, h in PIXELS not in the native units of the stimulus. I'll need to work out somethign to convert that back neatly

**Comment by tmalsburg** [comment]
Thank you.  This is better but still not quite the correct solution.  See [this example](http://imgur.com/Xran21e).  The bounding box is to large both in the horizontal and the vertical dimension.  (The pygame backend gives me the smallest bounding box containing the text.)

I'm preparing an eye tracking experiment that studies reading behavior and I really need to know whether the gaze was fixating on a word or just close to it.  Hm ...

**Comment by tmalsburg** [comment]
Would it make sense to return `content_width` and `content_height` when `TextStim.width` and `TextStim.height` are accessed?  This would be consistent with what the pygame backend is doing and these are probably also the number that most people really want.  If the user wants the width of the "document" (as you call it), they can get this through 'TextStim.wrapWidth'.

In case that you want to include the function `TextStim.boundingBox` in Psychopy, I think it might make sense to return something else then just width and height, because these define the size of the box but not the position.  I think it's more common to specify bounding boxes in terms of the absolute position of the lower left and the upper right corner.

By the way, I'm happy to prepare PRs for any of the proposals I made above, but since I'm new to Psychopy, I'd like hear your feedback first.

**Comment by peircej** [comment]
This has come up several times on the users list. The height of the 
letters in pyglet refers to the height of a font. It doesn't know, 
within that, how much of the available space the characters comsume.
https://groups.google.com/forum/#!searchin/psychopy-users/letter$20height%7Csort:date/psychopy-users/63W13qzlE1g/6YkklpHNbxcJ

On 25/06/15 22:56, Titus von der Malsburg wrote:
>
> Thank you. This is better but still not quite the correct solution. 
> See this example <http://imgur.com/Xran21e>. The bounding box is to 
> large both in the horizontal and the vertical dimension. (The pygame 
> backend gives me the smallest bounding box containing the text.)
>
> I'm preparing an eye tracking experiment that studies reading behavior 
> and I really need to know whether the gaze was fixating on a word or 
> just close to it. Hm ...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/928#issuecomment-115411443>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment]
Yes, I was wondering about this.

The problem is trying not to break people's existing code unless we 
really need to. For `width` I suppose this isn't being accessed in its 
current form very much. But `height` could be confusing because that's 
an argument provided during construction of the text (I wish I had 
called it letterHeight, as I did in the Builder interface, but I'm not 
sure that's important enough to break existing code). It seems weird to 
provide a value for height but then the objects' height attribute 
doesn't match it.

Let me think some more on it.


On 25/06/15 23:06, Titus von der Malsburg wrote:
>
> Would it make sense to return |content_width| and |content_height| 
> when |TextStim.width| and |TextStim.height| are accessed? This would 
> be consistent with what the pygame backend is doing and these are 
> probably also the number that most people really want. If the user 
> wants the width of the "document" (as you call it), they can get this 
> through 'TextStim.wrapWidth'.
>
> In case that you want to include the function |TextStim.boundingBox| 
> in Psychopy, I think it might make sense to return something else then 
> just width and height, because these define the size of the box but 
> not the position. I think it's more common to specify bounding boxes 
> in terms of the absolute position of the lower left and the upper 
> right corner.
>
> By the way, I'm happy to prepare PRs for any of the proposals I made 
> above, but since I'm new to Psychopy, I'd like hear your feedback first.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/928#issuecomment-115415210>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by peircej** [comment]
TextStim.boundingBox was added in v1.83.00 
commit 35c168f1

**Comment by tmalsburg** [comment]
Great, thanks.
