### ISSUE TITLE
ShapeStim should handle complex shapes

### ISSUE THREAD

**Issue by lindeloev** [psychopy/psychopy#936]
Currently, ShapeStim and it's derivatives does not handle concavities and "holes" - what's called "complex shapes" in OpenGL speak. I myself tried to draw a star the other day using ShapeStim but failed. Holes may be more of a fringe case, I guess. It should be possible to do both by using a tesselation helper, see e.g. http://opengl.czweb.org/ch18/575-580.html. 

Have anyone tried implementing this for PsychoPy and shouldn't it be on the wish list?

**Comment by peircej** [comment]
Yeah, definitely not one of the things I cared to fix anytime soon, given a couple of easy enough workarounds, but if you fancy a little challenge that's cool ;-)

**Comment by lindeloev** [comment]
What are those workarounds? Combining multiple ShapeStims as mentioned in the doc or something more clever? I wanted to control line color and fill color for the star dynamically and separately. Ended up using bitmaps instead which felt very unelegant ;-)

**Comment by peircej** [comment]
Yes, bitmaps are workaround number 2. ;-)

**Comment by jeremygray** [comment]
I read on the internets (so must be true) that this python project has useful code for gl-based tesselation  https://pypi.python.org/pypi/glsvg/0.4. The file svg_path_builder.py in that project has lots of references to tesselation

**Comment by jeremygray** [comment]
This seems even more specific: file tesselate.py (BSD licence) in svgbatch https://pypi.python.org/pypi/svgbatch/0.1.9
