### ISSUE TITLE
Is there any function like screen.get_at([0,0]) in pygame?

### ISSUE THREAD

**Issue by wwwhhnbill** [psychopy/psychopy#938]
I need to adjust colors for single pixel and I have found get_at and set_at in pygame were exactly what I want. Here for psychopy, are there any functions do what these two do or is there a way to use them?

Thanks :)

**Comment by peircej** [comment]
No, I don't think you can use those functions from a pyglet window.

You can do this using OpenGL directly, where the only trick is to :

``` python
from pyglet import gl

def drawPixel(x,y,pixel):
    """pixels should be list/array of [r,g,b]"""
    pixelsArr = numpy.array(pixel, numpy.uint8)
    gl.glWindowPos2i(x,y) #pixels (from bottom left?)
    gl.glDrawPixels(1, 1, gl.GL_RGB, gl.GL_UNSIGNED_BYTE, pixelsArr.ctypes)


drawPixel(5,5,[0,100,0])
myWin.flip()
```

The above could be trivially extended to draw more than one pixel when given WxHx3 arrays of values

**Comment by wwwhhnbill** [comment]
Thanks a lot, peircej!

Your drawPixel func perfectly solves the set_at problem, and there's also a glReadPixels func seems is able to replace the get_at.
However, I'm a super novice of coding and failed to work it out.

glReadPixels = _link_function('glReadPixels', None, [GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, POINTER(GLvoid)], None)

It makes me confused that a POINTER(GLvoid) should also be appointed and it print nothing if I give an rgb array
Would you please show me how to get it right or any other way to get rgb of a pixel?

**Comment by peircej** [comment]
All I really know is how I've used glReadPixels int he past which you 
can see in window.py around line 813:
https://github.com/psychopy/psychopy/blob/master/psychopy/visual/window.py

On 22/07/15 15:44, wwwhhnbill wrote:
>
> Thanks a lot, peircej!
>
> Your drawPixel func perfectly solves the set_at problem, and there's 
> also a glReadPixels func seems is able to replace the get_at.
> However, I'm a super novice of coding and failed to work it out.
>
> glReadPixels = _link_function('glReadPixels', None, [GLint, GLint, 
> GLsizei, GLsizei, GLenum, GLenum, POINTER(GLvoid)], None)
>
> It makes me confused that a POINTER(GLvoid) should also be appointed 
> and it print nothing if I give an rgb array
> Would you please show me how to get it right or any other way to get 
> rgb of a pixel?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/938#issuecomment-123745875>.
>

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
