### ISSUE TITLE
Feature Request - 3rd View Option for Task Execution

### ISSUE THREAD

**Issue by pntfx4** [psychopy/psychopy#943]
A limitation of the current two view options, and something that is present in packages like eprime, is a task execution mode where the code can be run but not edited. 

When running an experiment in coder view it is possible for participants/undergrad assistants to accidentally insert characters into the code. The coder view presently pops up a prompt asking if you want to save the file prior to running when such an instance occurs, and you can use the operating system to restrict editing of a file. 

But a view similar to the coder view except without the ability to change the code would enable those who use either coder or builder to more easily deploy tasks without those issues.

**Comment by jeremygray** [comment]
For Coder files, it is not possible to easily store meta-data (such as a boolean: "open this file as read-only"). So it would have to be set manually every time after opening the file, which would be annoying. For Builder files, an experiment-setting would easily allow this, but subjects are not so likely to inadvertently type a random character into the script. 

In contrast, running a script from the command line (using the new option, -x script.py[c]) allows the script to be run by the PsychoPy app without ever being open for editing.

**Comment by jeremygray** [comment]
Actually, a user-pref would work well: a check-box that disallows any edits to any file in the Coder view, but does allow opening and running. This would allow testing-room machines to be read-only for .py files. For Coder, `self.currentdoc.SetReadOnly(True)` is enough to prevent editing. Builder would be more involved (and not really needed).

**Comment by peircej** [comment]
Or forget both current views for this and create a new "launcher" that 
just had the name (and a descr?) for a set of files (psyexp or py) and a 
run button. Tell it which scripts/builder experiments you want to see 
here and select the one you want and run it.

Just as an extra thought. ;-)




This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by jeremygray** [comment]
A launcher would be a lot more code (and a lot slicker to look at). A read-only pref for Coder-view files is just a few lines.

**Comment by peircej** [comment]
yes, fair enough
