### ISSUE TITLE
Coder Shelf Output Font Changes After Error

### ISSUE THREAD

**Issue by pntfx4** [psychopy/psychopy#944]
When using PsychoPy in Coder View, the output window changes the font/size of the font after an exception occurs. It then stays with the new font/size until the Coder View is closed and reopened. This occurs in both PC and OSX standalone implementations and has been present for multiple versions including 1.82. The coder preference window indicates no change in the font or font size after an error, relative to before.

**Comment by TEParsons** [comment]
No longer applicable due to interface changes since 2015
