### ISSUE TITLE
from psychopy import visual exhibits protracted load time for Windows OS

### ISSUE THREAD

**Issue by pntfx4** [psychopy/psychopy#948]
Version 1.82.01 on Windows computers (Windows 7, 64bit) has a very long load time for some psychopy modules. Older versions of psychopy did not have this issue (or at least not to the same degree).

    import time

    t = time.time()
    from psychopy import visual
    print('Loading Time for psychopy visual: %f seconds' % (float(time.time() - t)))

    t = time.time()
    from psychopy import data
    print('Loading Time for psychopy data: %f seconds' % (float(time.time() - t)))

    t = time.time()
    from psychopy import gui
    print('Loading Time for psychopy gui: %f seconds' % (float(time.time() - t)))

    t = time.time()
    from psychopy import core
    print('Loading Time for psychopy core: %f seconds' % (float(time.time() - t)))

Shows psychopy visual takes 3-7 seconds to load, data takes 1-5 seconds, gui takes 0.5 to 1 second, and core loads in under 0.000001 second.

**Comment by peircej** [comment]
Yes, there has gradually been an increase in complexity in all the 
modules, particularly in the dependencies they import as well.
     data now requires pandas, which I think can be slow to import
     visual now loads extra things like opencv for movies and vlc for 
movie sounds (and possibly opens a sound output channel?)

Not sure what can realistically be done about that. "Lazy importing" 
when the module is first needed?

cheers,
Jon

**Comment by pntfx4** [comment]
Given the growth of support for movie related stimuli, would a better long-term solution be to transition movies into their own module? Visual is becoming somewhat of a catch all (http://www.psychopy.org/api/visual.html), which makes sense. But It would seem a more pyonic solution to load only those dependencies necessary. If you just want to present a static image, loading dependencies for playing video/audio seems like overkill. There is certainly precedent for separating movies (which may or may not include sound) from less complex visual stimuli. Clearly this is not such a simple fix, but perhaps could be integrated into future iterations down the road.

Thanks for the insight into why the the loading times were increasing though! Best,

-Matt

**Comment by peircej** [comment]
I think this was fixed by lazy importing #953
