### ISSUE TITLE
'pythonw.exe has stopped working' (audio recording experiment)

### ISSUE THREAD

**Issue by nathawahlang** [psychopy/psychopy#955]
i built a simple experiment to display 38 images and record a description of the images. Sometimes the experiment runs all the way through, but sometimes it crashes and displays this message 'pythonw.exe has stopped working'. I am new to psychopy and not very familiar with python either. What is causing this error?

**Comment by hoechenberger** [comment]
Could you please turn to the [psychopy-users](https://groups.google.com/forum/#!forum/psychopy-users) mailing list and provide the code (or psyexp file) you are using?
