### ISSUE TITLE
gui.DlgFromDict lists broken on Mac

### ISSUE THREAD

**Issue by Ferrick4** [psychopy/psychopy#966]
I'm working from the demo code below on OSX:

psychopy/psychopy/demos/coder/input/GUI.py

The default code works fine but when importing 'psychopy.iohub' along with 'psychopy.gui', lists always default to the first item.

i.e., changing 'from psychopy import gui' to '
```python
from psychopy import gui
```
to...
```python
from psychopy import gui, iohub
```
causes the problem. This also happens when importing pschopy.visual and 'joystick' from psychopy.hardware. Lastly, lists do not work when using the alternative function gui.Dlg. The error sounds similar to "subtle gui.Dlg choices bug #199", however I updated to wx3.0 and the error still occurs.

**Comment by jeremygray** [comment]
I used to get this issue with lists in GUI's, but I don't see it anymore (64-bit python, Mac OS X 10.11, wx 3.0, pyglet 1.2.2). Please try the StandAlone release candidate 1.83.00 from here: https://github.com/psychopy/psychopy/releases and see if you still get the issue.

**Comment by Ferrick4** [comment]
Thank you for your response, the new 1.83.00 StandAlone version fixes the problem on my end.
