### ISSUE TITLE
Setting mouse visibility via Window doesn't work

### ISSUE THREAD

**Issue by smathot** [psychopy/psychopy#971]
If you toggle mouse visibility via the `Window` object, the mouse is shown, but not hidden; that is, this example doesn't work as expected.

``` .python
for i in range(4):
    win.setMouseVisible(False) # win = visual.Window
    clock.sleep(1000) # An OpenSesame call to sleep for 1000 ms
    win.setMouseVisible(True)
    clock.sleep(1000)
```

However, toggling visibility via a `Mouse` object works fine:

``` .python
from psychopy import event
m = event.Mouse(win=win)
for i in range(4):
    m.setVisible(False)
    clock.sleep(1000)
    m.setVisible(True)
    clock.sleep(1000)
```

I looked at the code, and I don't see any major difference between the two ways of toggling mouse visibility. Perhaps it has to do with the attribute-setting mechanism; I'm not sure.

This is on Ubuntu 15.04, using PsychoPy 1.82.02.

**Comment by TEParsons** [comment]
Running the upper code snippet in 2022.2.1 on Windows 10 seems to work, so looks like this has been fixed
