### ISSUE TITLE
visual.MovieStim3 asynchronous sound and video

### ISSUE THREAD

**Issue by emilbunk** [psychopy/psychopy#972]
running the newest release 1.83.00 i finally got movie stimuli up and running on a 64bit mac. However i found that not running the movie stimuli at the start of an experiment would result the video being delayed compared to the sound and some initial frame skipping in the clip.

I haven't been able to precisely pinpoint what happens, but a reset of the movie3 object after initialization seems to do the trick.
```
movietest = visual.MovieStim3(win=win, name='movietest', filename=u'/path/to/file/movie.avi', ori=0, pos=[0, 0], opacity=1, depth=-1.0,)
movietest.reset()
```

**Comment by peircej** [comment]
Thanks - was caused by not always reset the clock during play(). I had only set it to reset if pause had been called but your use case involves an implicit 'pause' as well.
