### ISSUE TITLE
Mouse.clickReset() does not reset event.mouseButtons to [0,0,0]

### ISSUE THREAD

**Issue by simkovic** [psychopy/psychopy#977]
I do:

    from psychopy import core, visual, event
    myWin = visual.Window([400,400.0], allowGUI=False)
    myMouse = event.Mouse()

    while True:
        mkey = myMouse.getPressed()
        if sum(mkey)>0:
            print mkey
            myMouse.clickReset()
            mkey = myMouse.getPressed()
            print mkey, event.mouseButtons
            event.mouseButtons=[0,0,0]
            mkey = myMouse.getPressed()
            print mkey, event.mouseButtons
            core.quit()
        myWin.flip()
    core.quit()

And get

    [0, 0, 1]
    [0, 0, 1] [0, 0, 1]
    [0, 0, 0] [0, 0, 0]

I guess this is not the intended functionality.

Tested with 1.82.01 linux and 1.83.00rc1windows.

**Comment by jeremygray** [comment]
I agree that this seems like not the intended behavior. I'll look into it. Thanks for reporting this.

**Comment by jeremygray** [comment]
My mistake. clickReset() should NOT reset the state of the buttons. `event.mouseButtons` are used by `event.Mouse.getPressed()` and reflect the current state of the mouse. They get "reset" automatically as soon as the mouse is no longer down. Note that a click does not last for only one frame, its often 100-200ms long--the state of the mouse will register "pressed" for multiple visual frames.

So, merely by adding a short delay into your test script, we can see that things are working as expected (in the case of a human-made mouse press):

    from psychopy import core, visual, event
    myWin = visual.Window([400,400.0], allowGUI=False)
    myMouse = event.Mouse()
    
    while True:
        mkey = myMouse.getPressed()
        if sum(mkey)>0:
            print mkey
            myMouse.clickReset()
    
            core.wait(.2)   # a typical mouse-click takes ~100ms, 6-9 frames of the mouse being down
    
            mkey = myMouse.getPressed()
            print mkey, event.mouseButtons
            event.mouseButtons=[0,0,0]
            mkey = myMouse.getPressed()
            print mkey, event.mouseButtons
            core.quit()
        myWin.flip()

And I get:

    [1, 0, 0]
    [0, 0, 0] [0, 0, 0]
    [0, 0, 0] [0, 0, 0]
