### ISSUE TITLE
proposal: support formatted text via pyglet.text.HTMLTextStim

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#978]
pyglet has a class `pyglet.text.HTMLLabel` that looks like it might be any easy way to give people control over the format of color and so on within their text strings.

**Comment by jeremygray** [comment]
hmmm, it sort of works but is pretty rudimentary, and does not appear to support colors

**Comment by peircej** [comment]
I suspect it will also be slow. I think we'd be better focussing on developing the TextBox that @isolver wrote (to start with we need to allow non-monospace fonts). It will be faster and we'll be in control.
