### ISSUE TITLE
The coder demo iohub elotouchscreen fails to run on 1.83.01

### ISSUE THREAD

**Issue by danielshub** [psychopy/psychopy#982]
On 1.83.01 the elotouchscreen demo gives me the following error

##### Running: /usr/lib/python2.7/site-packages/psychopy/demos/coder/iohub/elotouchscreen/run.py #####
  File "/usr/lib/python2.7/site-packages/psychopy/demos/coder/iohub/elotouchscreen/run.py", line 47
    print("queryDevice('ID'):" + str(,id_dict))
                                     ^
SyntaxError: invalid syntax

**Comment by danielshub** [comment]
The fix did does not seem to have made it into 1.83.03 ...

**Comment by vrossum** [comment]
Also still there in 1.83.04
