### ISSUE TITLE
MovieStim3 memory leak

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#983]
If I load the demo movie in a loop 100 times, the python process uses ~1G of RAM to do so. It uses ~10M for each iteration of loading the movie (which is ~415K on disk). The script hangs at the end, and sometimes seg faults (consistent with memory issues). I do not see this when allocating a lot of memory for other things in a loop, like range(1000000). SoundPyo appears to have a similar memory issue.
    
    # test script
    from psychopy import visual, info
    win = visual.Window()
    mem = []
    for i in range(100):
        visual.MovieStim3(win,'/Users/jgray/code/psychopy/psychopy/demos/coder/stimuli/jwpIntro.mov')  # should get garbage collected ~every iteration
        # range(1000000)  # just for comparison, works fine, no mem leakage
        mem.append(round(info.getMemoryUsage(),1))
    print('leakage = {0}M'.format(mem[-1] - mem[0]))
    print(mem)

**Comment by jeremygray** [comment]
Most of the leak in Movie3 appears to be due to the sound. Movie3 leaks far less with noAudio=True

**Comment by peircej** [comment]
hmm, is this a pyo issue? What about sound on but set to use pygame?

**Comment by jeremygray** [comment]
It happens with pyo, no idea about pygame. I poked around a bit with pyo, did not figure much out. It is definitely sensitive to the data type, and does best with lists of regular floats. It accepts numpy arrays of numpy.float64's, but leaks badly in that case (and also if you give it a list of int's). But this should not matter, since sound.SoundPyo converts numpy arrays, using thisArray.T.tolist(), per Olivier's suggestion.

**Comment by jeremygray** [comment]
I told Olivier about pyo's memory leak, and a few hours later he posted a patch which I compiled into my pyo on OS X. sound.SoundPyo works fine for me now, no leak. MovieStim3 still leaks for me, but that might be due to something other than sound?

**Comment by peircej** [comment]
OK, great. I'm not a fan of the previous method - it feels like writing out the wav file could take ages for a moderately long movie

**Comment by peircej** [comment]
Do we think this is fixed with the pyo memory leak fix?

**Comment by jeremygray** [comment]
Yes, fixed with Olivier's patch to pyo
