### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by alvesadrian** [psychopy/psychopy#997]
Hello I'm building this pkg for fedora 24 but code is not building in python3, any suggestion or you gonna provide python3 support? can i use a tool like 2to3?

**Comment by peircej** [comment]
See discussion here:
https://groups.google.com/forum/#!topic/psychopy-dev/w_7MFzxVj_I

**Comment by cle1109** [comment]
See also #1061

**Comment by mdcutone** [comment]
I was just getting excited to see this issue closed.

**Comment by hoechenberger** [comment]
@mdcutone, work on Python 3 support should probably be discussed in #1061. Sorry to disappoint you, but PsychoPy does not yet support Python 3. But any help in getting closer to this goal is very welcome!
